### ISSUE TITLE
Undefined array key "Copy2:DirectoryItemLength" at <memories_path>/lib/Db/LivePhoto.php#78

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#1020]
**Describe the bug**
Live videos seem to not be playing (Android Google Cam photos)

```
{"reqId":"AHxZlrAizYcg37CONz","level":3,"time":"2024-01-25T09:43:30-05:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key \"Copy2:DirectoryItemLength\" at /var/www/nextcloud/apps/memories/lib/Db/LivePhoto.php#78","userAgent":"--","version":"28.0.1.1","data":{"app":"PHP"},"id":"65b934a8993e2"}
```

**To Reproduce**
I'm not sure?

**Platform:**

- OS: Ubuntu
- Browser: Firefox
- Memories Version: 6.2.2
- Nextcloud Version: 28.0.1
- PHP Version: 8.2

**Additional context**

- Any errors in the JS console? None when viewing live photos or when clicking the "play live photos" button
- Any errors in the Nextcloud server logs?

**Comment by reox** [comment]
I get these errors in the log too. Seems to be related to Pixel 7 live photos uploaded to NC via nextcloud app.

**Comment by pulsejet** [comment]
This was addressed in https://github.com/pulsejet/memories/issues/965

You can apply the relevant patch from https://github.com/pulsejet/memories/commit/e6760c7452915a98dfe6c230c4c466579678a75e
