### ISSUE TITLE
Feature: Reindex all photos and clear obsolete previews

### ISSUE THREAD

**Issue by q2apro** [pulsejet/memories#1024]
**Is your feature request related to a problem? Please describe.**
I am forced to use Nextcloud Memories with a Nextcloud Docker installation. I added the app Memories which indexed all photos. Now I removed 20 % of the photos (screenshots) from the file system. However, it seems the images do not get removed from the Memories gallery. (Or do I need to wait one or more days?)

**Describe the solution you'd like**
It would be nice to have a "Clear previews" (or clear cache) button in the app settings that remove all previews and start regenerating all previews.

![image](https://github.com/pulsejet/memories/assets/6764548/d1c998c8-7b06-4403-9ff6-6f450683f0fe)

There below a button "Clear previews and reindex".

**Comment by pulsejet** [comment]
How did you "remove" the images? Did you delete via Nextcloud?

**Comment by q2apro** [comment]
I deleted the from my computer. Nextcloud desktop client synched and removed them from my Nextcloud Server (not my server but Hetzner Storage Share..). 

I just see, 8 hours later they are gone! 

So it seems that it was really the reindexing background process that took time.
