### ISSUE TITLE
person clusters not updated after moving images to other clusters

### ISSUE THREAD

**Issue by andreaskoelsch** [pulsejet/memories#1025]
After detecting and clustering faces, I moved some images from one cluster to another using the given function in memories. After that, the thumbnail of the cluster still shows the wrong person and the number of images in the top left is wrong. This is only the case for the persons in Memories. In Nextcloud Photos, the clusters are updated as expected.

- Memories Version: 6.2.2
- Nextcloud Version: Nextcloud Hub 7 (28.0.1)
- PHP Version: 8.2

**Comment by pulsejet** [comment]
This is a known issue. It's cached for 1 day.

**Comment by pulsejet** [comment]
Fixed with #1071

**Comment by andreaskoelsch** [comment]
Thanks. I guess, this will be in the next release?

**Comment by pulsejet** [comment]
Yes, see https://github.com/pulsejet/memories/blob/master/CHANGELOG.md
