### ISSUE TITLE
Playing video is not protecting against phone going into screen saver mode 

### ISSUE THREAD

**Issue by Phils80** [pulsejet/memories#1029]
**Describe the bug**
While watching video on Memories app phone is entering into screen saver mode after time set up in display settings of the phone.

**To Reproduce**
Upload video lasting longer than your screen saver settings to Memories, choose play and after time setup in your display settings, your phone is going into screen saver mode. 

**Screenshots**
--not applicable--

**Platform:**

- OS: Android 12 / Nextcloud server on Ubuntu 22.04
- Browser: - not applicable - bug is on Android app. version 1.6
- Memories Version: 6.2.2
- Nextcloud Version: 27.1.4
- PHP Version: snap included 8.1

**Additional context**
- no additional context -

**Comment by pulsejet** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/WakeLock

**Comment by pulsejet** [comment]
Note: this will only be functional on HTTPS (most APIs don't work on HTTP)
