### ISSUE TITLE
Missing function to add/upload photos in Memories

### ISSUE THREAD

**Issue by HolgerDoerrschuck** [pulsejet/memories#1044]
**Is your feature request related to a problem? Please describe.**
My frustration is that I am not able to upload photos in memories. I always have to switch to Photos or Files where I can add photos. But both are so slow :-( 
**Describe the solution you'd like**
Same function as available in Photos and Files

![Screenshot 2024-02-13 211712](https://github.com/pulsejet/memories/assets/101668235/eb19ffde-8191-415d-8c28-d0c55d8082e5)

**Comment by johnSamilin** [comment]
duplicates #69
