### ISSUE TITLE
Album only with timeline view

### ISSUE THREAD

**Issue by HolgerDoerrschuck** [pulsejet/memories#1045]
**Is your feature request related to a problem? Please describe.**
I want to send albums via link to friends but the album will always be shown with timeline grouping. 

**Describe the solution you'd like**
I'd like to have a solution to choose whether the album should be shown with timeline or just all pictures at once.

**Describe alternatives you've considered**
I always have to go to Pictures to send that album out

**Additional context**
![Screenshot 2024-02-13 21203x8](https://github.com/pulsejet/memories/assets/101668235/48d63e99-76c7-4d50-b3ef-4d66fce75372)

**Comment by pulsejet** [comment]
The timeline is the key component of lazy loading, so basically this is impossible in the current architecture.
