### ISSUE TITLE
"Specified key was too long" error on installation

### ISSUE THREAD

**Issue by dilettanti** [pulsejet/memories#106]
I am running NextCloud 25 on ubuntu 20.04 with PHP 7.4.3 and MySQL 8.0. I don't have much in my NextCloud installation at this point - the only files I have added are photos I added from my phone using the 'Auto upload' feature in the Android app. When I tried to install Memories, I received the following error:

> An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes

As a result, the installation failed. I tried reinstalling, but get an error saying the a particular database column in 'oc_memories' already exists. I was told on reddit that the error may result from having paths that are too long. But while I may have long filenames elsewhere on the server, the NextCloud installation is mostly just stock (upgraded over several versions) with almost no files at all added (and those have only standard filenames assigned by my phone, e.g., '20220803_113321.jpg'). Memories looks like a great project (clearly superior to the default NextCloud Photos app) and I'd love to use it to organize, view, and share my photos, but I am unable to install it at this point. Thanks!

**Comment by pulsejet** [comment]
Just to confirm, you get this error **during** installation, not after it is installed. That is, on the app store page?

**Comment by dilettanti** [comment]
Yes, that's correct. It crashes *during* installation. The app store then shows it still available for install, but I then get the error about the field already existing on the 'oc_memories' table. The table itself, though, is entirely empty.

**Comment by xtream1101** [comment]
I got the same error on install. When I go back to the Apps list and try to "Enable" it I then get the error 
> The column 'w' on table 'oc_memories' already exists. 

Nextcloud: 24.0.6
PHP: 8.0.20
MySQL: 8.0.29

**Comment by dilettanti** [comment]
Success! Thank you so much for the swift resolution! The app looks great - I particularly love the timeline scroll and the "On this day" feature.

**Comment by pulsejet** [comment]
Perfect. Mysql shenanigans fixed!

**Comment by SidM01** [comment]
I get the same error as @xtream1101 

what do i have to do exactly?

I don't understand what you mean by "oc_memories"
Should I enter this somewhere and if so where?

Many thanks for your Help!

Nextcloud: 26.0.2
PHP: 8.2.6
MySQL: 10.11.3
Memories: 5.1.0 via the nextcloud app page
