### ISSUE TITLE
Add tags to multiple photos

### ISSUE THREAD

**Issue by thegrasshopper104** [pulsejet/memories#1061]
**Is your feature request related to a problem? Please describe.**
I'd like to add a "reference" tag to some photos and I need to open the sidebar and repeat it for every photo.
**Describe the solution you'd like**
I can select 100 photos and click Add tag > "reference"
**Describe alternatives you've considered**
Probably creating an album would have similar results

**Comment by pulsejet** [comment]
Select the photos. Edit Metadata. Add the tag. Done.
