### ISSUE TITLE
Error saving image

### ISSUE THREAD

**Issue by dnavarrocueto** [pulsejet/memories#1063]
**Describe the bug**
Error when trying the save an image after editing with Memories app. It shows a message with "Error saving image". I have tried with all the different formats but all fail: jpeg, png, jpg, webp. In Files app I am able to edit the same photo and save it, but there are some differences in save dialog. By default in Files app, format is empty, the filename does not have extension, and jpeg format is not available but png, jpg and webp yes.

**To Reproduce**
Edit image in Memories app and try to save it.

**Screenshots**

**Platform:**

- OS: Ubuntu 22.04
- Browser: Firefox
- Memories Version: 6.2.2
- Nextcloud Version: 27.1.6snap1 (Nextcloud installed in Ubuntu server 22.04 using snap package)
- PHP Version: 

**Additional context**

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

**Comment by pulsejet** [comment]
> Any errors in the JS console?
?

> Any errors in the Nextcloud server logs?
?

**Comment by dnavarrocueto** [comment]
Hi pulsejet. Thanks for answer. I am new with Nextcloud, where can I see server logs? By the way, same error shows with Memories Android app.

I attach JS console messages where it seems to be some errors.

[console-export-2024-3-7_22-31-28.txt](https://github.com/pulsejet/memories/files/14530338/console-export-2024-3-7_22-31-28.txt)

**Comment by pulsejet** [comment]
> I am new with Nextcloud, where can I see server logs

I believe it's in `/var/www/html/data/nextcloud.log` by default

**Comment by dnavarrocueto** [comment]
Finally I gave up with the snap installation. I installed through all-in-one docker and everything works fine.

Thank you very much, it is a great application!!
