### ISSUE TITLE
Archive function error

### ISSUE THREAD

**Issue by Lumberj4cked** [pulsejet/memories#1064]
**Describe the bug**
When I try to archive photos in the timeline (or anywhere) I get the error : 
`Error: An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'key' at row 1`

**To Reproduce**
Archive a picture on the timeline

**Screenshots**
![afbeelding](https://github.com/pulsejet/memories/assets/57967741/1e292abd-bafe-4b13-a242-be43215cf770)

**Platform:**

- OS: Android, Windows
- Browser: Firefox
- Memories Version: 6.2.2
- Nextcloud Version: 28.0.3
- PHP Version: 8.2.16

**Additional context**
I am using MariaDB, the file I'm trying to archive is at path : 
`Fotos/S24ultra-upload/Whatsapp/WhatsApp Images/IMG-20240306-WA0002.jpg`

- Any errors in the JS console?
`Failed to (un)archive 321854 
Object { stack: "s@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1377534\ns@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1384382\nS@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1371512\nEventHandlerNonNull*64937/A</<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1371681\n64937/A<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1370564\nd@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1382731\nrequest@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1376709\n15793/</t/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1377189\n6785/i/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1388776\nat/</n</</<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1654227\nat/</n</<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1654261\nQe/</t<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1650258\nQe/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1650288\na@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1647201\nVe/r/i[e]/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1647144\nVe/r/i[e]@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1647096\not/i/t[i]<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1653329\nat/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1654574\na@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1653809\nl@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1653927\npromise callback*a@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1653861\nrt/r/i[e]/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1653752\nrt/r/i[e]@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1653704\narchiveSelection@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1683997\nclick@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1676066\nclick@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:1686648\n_n@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:929058\nn@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:921480\n_n@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:929058\n26427/e.prototype.$emit@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:950989\nonClick@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:33047\n_n@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:929058\nn@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:921480\n26427/co/o._wrapper@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:962015\nEventListener.handleEvent*co@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:962041\nFt@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:921767\nmo@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:962422\nA@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:971305\nm@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:970611\nh@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:971062\nm@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:970596\n26427/tr@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:974605\n26427/e.prototype._update@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:951141\ni@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:982112\n26427/e.prototype.get@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:932733\ne@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:932646\n26427/cs.prototype.$mount/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:982136\n26427/cs.prototype.$mount@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:982354\ninit@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:937524\n26427/m/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:970205\nm@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:970482\nh@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:971062\nm@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:970596\nh@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:971062\nm@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:970596\nh@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:971062\nm@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:970596\n26427/S/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:973333\nS@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:973517\n26427/S/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:973042\nS@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:973517\n26427/S/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:973042\nS@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:973517\n26427/tr@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=4161d2df-5:2:974653\n", message: "Request failed with status code 500", name: "AxiosError", code: "ERR_BAD_RESPONSE", config: {…}, request: XMLHttpRequest, response: {…} }
archive.ts:40:14
    n archive.ts:40
    t base.ts:141
    Qe base.ts:139
    a albums.ts:240
    Ve/r/i[e]/< albums.ts:240
    e albums.ts:240
    ot/i/t[i]< base.ts:387
    at archive.ts:47
    a base.ts:387
    l base.ts:387
    (Async: promise callback)
    a base.ts:387
    rt/r/i[e]/< base.ts:387
    e base.ts:387
    archiveSelection SelectionManager.vue:900
    click SelectionManager.vue:357
    click SelectionManager.vue:3
    VueJS 4
    onClick NcActionButton.js:2
    VueJS 33
`
Note that I changed my real personal domain in the error to a fictional 'mydomain.nl' domain.
- Any errors in the Nextcloud server logs?
no

**Comment by pulsejet** [comment]
> Any errors in the Nextcloud server logs?

Are you sure?

This seems like an upstream issue; memories simply calls the nextcloud API to move the files into a different folder.

**Comment by Lumberj4cked** [comment]
> > Any errors in the Nextcloud server logs?
> 
> Are you sure?
> 
> This seems like an upstream issue; memories simply calls the nextcloud API to move the files into a different folder.

In the /settings/admin/logging page when logged in as admin it does not show any errors related to the archiving function. is there a different location you'd like me to check and share with you?

**Comment by pulsejet** [comment]
The log file on the server

**Comment by Lumberj4cked** [comment]
I don't seem to get any errors regarding this in the nextcloud log. only some errors about a file that can't get indexed but that is unrelated to this file and problem.

**Comment by Lumberj4cked** [comment]
it seems like the path is too long I think 
archiving this file gives the error : 
`Fotos/S24ultra-upload/Whatsapp/WhatsApp Images/IMG-20240306-WA0002.jpg`
archiving this file doesn't give an error and works : 
`Fotos/Fiets/20230614_233340.jpg`

**Comment by pulsejet** [comment]
Are you using redis for locking?

**Comment by Lumberj4cked** [comment]
I am not using redis in my setup

**Comment by pulsejet** [comment]
Please apply this patch and try again
https://github.com/pulsejet/memories/commit/162827052c4390e909eb98cfeba88000d9d1048c

**Comment by pulsejet** [comment]
Note: you might need to restart the php server / apache / fpm after patching to clear the opcache

**Comment by pulsejet** [comment]
Okay great!
