### ISSUE TITLE
Android: Share via Telegram: Unsupported Attachment

### ISSUE THREAD

**Issue by jacksbox** [pulsejet/memories#1065]
**Describe the bug**
Sharing of (original as well as reduced size) images via telegram leads to a "Unsupported Attachment" Error. 
WhatsApp on the other hand works  as expected.
Normally there are no issues sharing images via telegram, so I would place the bug in memories.

**To Reproduce**
Share an image via telegram

**Platform:**

- OS: Android (Vanilla, 13)
- Memories App: 1.6

**Comment by sawaanna** [comment]
Same problem. I was able to send an image stored in the phone’s memory from Memories to Telegram. It is sent as file, without compression options
but nothing stored on Nextcloud was sent, "Unsupported attachment" error occurs

**Comment by nate2014jatc** [comment]
Same behavior on 
App: v1.6
Android: 14
Nextcloud: 28.0.3
Nextcloud App: 7.0.2
