### ISSUE TITLE
Display RAW Photos

### ISSUE THREAD

**Issue by emaraszek** [pulsejet/memories#107]
I have photos taken on an iPhone in DNG format that do not display. Would it be possible to add support for RAW formats?

**Comment by emaraszek** [comment]
Yes, I have that app. However the generated previews appear in the Files app. The photos themselves do not appear at all in Memories.

**Comment by pulsejet** [comment]
Ah, right.

**Comment by pulsejet** [comment]
Enabled in next version. You'll need to run `occ memories:index` after upgrade with the raw preview app enabled.

**Comment by emaraszek** [comment]
@pulsejet thanks for the amazingly fast turnaround! I installed the update, ran `occ memories:index` and everything works perfectly

**Comment by pulsejet** [comment]
Awesome! I don't have any RAW myself, so do file any more bugs you encounter. Also I want to hear about any feature requests; please file issues if you have ideas.
