### ISSUE TITLE
Rebuilding places database breaks at version 7.0.2

### ISSUE THREAD

**Issue by echtfrank** [pulsejet/memories#1080]
**Describe the bug**
After migrating from version 7.0.1 to version 7.0.2, rebuilding the places database repeatedly breaks at polygon 1250232_0.

**To Reproduce**
Login to CLI and run command:

`ncc memories:places-setup` ("ncc" is equivalant for "occ" on Nextcloud implementation on DietPi)

**Screenshots**
Last lines of logging:

> Inserted 112000 / 635189 places (17.6%), Last: Sarasota County
Inserted 112500 / 635189 places (17.7%), Last: 沿溪镇
Inserted 113000 / 635189 places (17.8%), Last: Климовский район
Inserted 113500 / 635189 places (17.9%), Last: Nanzdietschweiler
ERROR: Failed to insert polygon 1250232_0 (An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
> In ExceptionConverter.php line 104:
  An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
In Exception.php line 28:
  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
In Statement.php line 130:
  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
memories:places-setup [-f|--force] [-r|--recalculate] [--transaction-size TRANSACTION-SIZE]

**Platform:**

- OS: DietPi on Odroid HC4 (based on Armbian / Dbian Bookworm)
- Browser: N/A
- Memories Version: 7.0.2
- Nextcloud Version: 28.0.3
- PHP Version: PHP 8.2.7 (cli) (built: Jun  9 2023 19:37:27) (NTS)

**Additional context**
Yesterday, after upgrading from Memories 7.0.0 to 7.0.1 I performed the exact same step, and this went well.

- Any errors in the JS console? Unknown
- Any errors in the Nextcloud server logs?

> ExceptionFailed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directoryException thrown: Doctrine\DBAL\Exception

>

**Comment by echtfrank** [comment]
I did an additional re-indexing of all files, and tried to rebuild the places database again.
It it is now running beyond the afore mentioned error.... I'll close this issue if it is correcctly finished.

**Comment by pulsejet** [comment]
https://memories.gallery/troubleshooting/#general-error-2006-mysql-server-has-gone-away

You don't actually need to re run this for the patch versions. Just running it once is good enough

**Comment by echtfrank** [comment]
Thanks, for pointing me to the trouble shooting guide. I am going to investigate and try further.

**Comment by Cyberes** [comment]
My install warned me that `Reverse geocoding has not been configured (-1)` so I ran `occ memories:places-setup --transaction-size=5`.

I got the `2006 MySQL server has gone away` error and adjusted my mariadb config settings to increase the timeout:

```
max_allowed_packet = 256M
net_read_timeout = 60
net_write_timeout = 120
wait_timeout = 28800
innodb_log_file_size = 256M

innodb_buffer_pool_size = 5G
```

I watched the process and the MySQL server isn't overloaded.

**Comment by pulsejet** [comment]
I'm assuming this has been fixed. Please reopen otherwise.
