### ISSUE TITLE
Support folder exclude via .noimage file filter

### ISSUE THREAD

**Issue by mrtumnus** [pulsejet/memories#1084]
**Is your feature request related to a problem? Please describe.**
I already have `.noimage` hidden files to exclude folders throughout my Nextcloud file tree.  I would prefer not to have to add additional `.nomedia` or `.nomemories` files.

**Describe the solution you'd like**
Add `.noimage` to the existing support for `.nomedia` and `.nomemories` file exclusion filters.

**Describe alternatives you've considered**
I could go through and make copies all of my `.noimage` files and rename them as `.nomemories`/`.nomedia`.

**Additional context**
The `.noimage` (and `.nomedia`) filters are already supported in the Recognize and Photos apps.  See:
https://github.com/nextcloud/recognize/pull/457
https://github.com/nextcloud/photos/pull/944

**Comment by pulsejet** [comment]
> I could go through and make copies all of my `.noimage` files and rename them as `.nomemories`/`.nomedia`.

Please do this. This is getting out of hand; each of these exclusions imposes a performance penalty.

`.nomedia` is the standard; I don't know why Nextcloud decided to randomly come up with `.noimage`. The implications are also unclear; are videos not excluded? It's not obvious.

**Comment by pulsejet** [comment]
> I could go through and make copies all of my `.noimage` files and rename them as `.nomemories`/`.nomedia`.

Just wanted to point out this is a one-liner

```bash
find <path-to-nextcloud> -type f -name '.noimage' -execdir mv {} .nomedia \;
```

Then you'll probably want to rescan

```bash
occ files:scan --all
```

**Comment by mrtumnus** [comment]
> Please do this. This is getting out of hand; each of these exclusions imposes a performance penalty.
> 
> `.nomedia` is the standard; I don't know why Nextcloud decided to randomly come up with `.noimage`. The implications are also unclear; are videos not excluded? It's not obvious.

Fair enough!  For some reason, I recall having to figure out whether to put `.noimage` vs `.nomedia` based on which applications I wanted to be able to find content.  So, for a music/video folder, I would put the `.noimage` file.  But for documents/software folders, I'd put `.nomedia`.  But I don't remember that use case specifically.  I'll go with `.nomedia` as the standard.
