### ISSUE TITLE
Select All in albums/folders

### ISSUE THREAD

**Issue by luckkmaxx** [pulsejet/memories#1088]
We cant select all items inside a folder. It could be fine one or two options:
- A "select all" option in the three dots.
- Ability to select all items between first picked and last long-tapped image.

**Comment by pulsejet** [comment]
> Ability to select all items between first picked and last long-tapped image.

Just use Shift+Select: https://youtu.be/vUNJxJMauXk

Duplicate of #132

**Comment by luckkmaxx** [comment]
Ok maybe I forget to mention this is in mobile UI
