### ISSUE TITLE
Shared Users' Comments and Replies

### ISSUE THREAD

**Issue by Danie10** [pulsejet/memories#1090]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
To enable a way for other users to leave comments on photos that we can reply to, in the Memories app. It's great that albums can to shared to other registered Nextcloud users, but they have no way to comment. This would be great for families and friends, and would make Memories really complete!

**Describe alternatives you've considered**
I searched for possible Nextcloud apps that may enable this, but nothing. I thought maybe that standard file sharing within Nextcloud may work but its comments are shown, but only in the files view so not part of Memories or even Photos.

I did try the Photo view with the 'i' Info icon at top right, and there I could enter a comment in the activity tab for the file. But no-one else sees that view or the comment. This may potentially be expanded on from inside the Memories app to possibly provide comments and replies.

**Additional context**
See attached image showing where the Activity could be used to embed comments inside Memories.

![MemoriesComment](https://github.com/pulsejet/memories/assets/1153726/52d417ba-7fe4-4ab1-a735-7e4cd483b57a)

**Comment by pulsejet** [comment]
I believe the activity tab was merged with the comments tab. You can actually use comments on on shared _folders_ but not on shared _albums_ (this is an upstream limitation in `nextcloud/server`; the sidebar doesn't currently open on album DAV paths)

**Comment by Danie10** [comment]
@pulsejet thanks, yes I saw the folders side working which is OK for normal file (or photo file) sharing, but the actual Memories app would be a killer app if there is a way for other registered Nextcloud users to comment, if an album/photos are shared with them.  It's the one real feature I miss as I currently use Piwigo to share all my 10,000+ photos and albums with family and friends - and the great part is the collaborative feedback from everyone that others can comment on too.

So logged this really to see if there si any way to achieve that in Memories (or Photos) on Nextcloud.

**Comment by pulsejet** [comment]
Just to be clear, I meant you already _can_ comment on photos through shared folders in Memories. You just share the folder through Memories and logged in users can use comments through the sidebar.

**Comment by Danie10** [comment]
@pulsejet OK thanks very much for clarifying. I want to do a YouTube video this coming week about Memories. I'll test that a bit and see if it can work with sub-folders under /Photos (the ideal so it could be per album) and see how/whether photo uploads can go into a sub-folder (that would be a first prize).

I'll clarify here what works in a day or so.

**Comment by Danie10** [comment]
@pulsejet thanks again for your previous pointer. OK, I got it working fine in the end with notifications etc happening through the NC Files side, which clicks to open to see/reply to the comments in the Files view (but it does work seamlessly).

I'd like to still make a proposal under this feature request for memories though:
1. Photos can open the sidebar view with Activity (comments) shown, and have that kept open as you scroll left and right through the photos. This make sit super easy to see if there are comments, and quickly reply or add a comment.
2. Memories has the same view via Folders / open folder, open photo and click on "i" icon, then can add comments under Activities tab. The DIFFERENCE, though in Memories, is every time you scroll back or forth, that info/sidebar view defaults back to the Info tab instead of keeping the view on Activities that show comments. This makes comment viewing quite cumbersome in Memories.

Is there a way to either default the sidebar to Activities tab like Photos does, or otherwise to stay on whichever tab was in focus when the photo is changed? The latter one would keep everyone happy, I suppose.

**Comment by pulsejet** [comment]
> in Memories, is every time you scroll back or forth, that info/sidebar view defaults back to the Info tab instead of keeping the view on Activities that show comments

This is a bug. Fix in https://github.com/pulsejet/memories/commit/85fe661a37598ebedc1bbc7f050f4f2a2f32f499

**Comment by Danie10** [comment]
Great thanks that is good news. OK I'll close this so long.

**Comment by pulsejet** [comment]
@Danie10 this fix is released in v7.1. Can you validate and reopen if the issue still exists?

**Comment by Danie10** [comment]
Works perfectly thanks! Ouch just posted a YouTube video this morning about it as https://youtu.be/2A6u0AluCnI but I'll highlight the fix is done. I did mention every time it was going to be fixed soon.

**Comment by pulsejet** [comment]
Fantastic, thanks for the great video!

**Comment by Danie10** [comment]
@pulsejet something is not quite right if you could just check:
1. Main user who uploaded photo - can view comments in Timeline and photo, and from Folders / folder / photo.
2. But user shared with, only sees the shared photo in Albums with no access to comments at all? Folders view in Memories not showing shared photos.

Something seems to have changed? The Folders view I showed at 31:46 in my video - https://youtu.be/2A6u0AluCnI?si=dyTpuXAw2vqiSOu-&t=1906 - no longer shows the shared folders at all. I rebooted the container too.

**Comment by pulsejet** [comment]
Have you shared the folder or an album. They are not the same thing and shared folders won't show up in albums and vice versa. I can't repro the bug on my side.

1. Assuming you shared the folder, can you provide the folder path on both sides (owner and sharee)
2. Is the shared folder visible in the Files app?

**Comment by Danie10** [comment]
Hi there yes I shared it both as a folder and as an album. It worked fine in my video, and all I recall doing was updating the Memories app itself. Let me just triple check the the shares again tomorrow. -------- Original Message --------On 2024/04/02 23:15, Varun Patil  wrote:
Have you shared the folder or an album. They are not the same thing and shared folders won't show up in albums and vice versa. I can't repro the bug on my side.

Assuming you shared the folder, can you provide the folder path on both sides (owner and sharee)
Is the shared folder visible in the Files app?


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/pulsejet/memories/issues/1090#issuecomment-2033112437",
"url": "https://github.com/pulsejet/memories/issues/1090#issuecomment-2033112437",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by pulsejet** [comment]
I just realised there's another possibility: that the migration didn't complete successfully. Try running `occ memories:index -f` if  you can see the folder in the Files app.

**Comment by Danie10** [comment]
OK reindex did not sort it out. It is fully functional under Photos app and can see folder in NC Files.

Memories only shows the shared album under Albums but clicking on info when viewing photo shows info but no Activities tab (or other tabs). The Folders view in Memories also does not show the shared folders.

I double-checked that both the folder and the album are shared to that user. When I tested the update, I had only checked the Activities view on the main user who had shared the album to the other other.

**Comment by pulsejet** [comment]
Very strange. Does turning on hidden folders in the settings change anything? Also is your folders path set to / ?

**Comment by pulsejet** [comment]
> It is fully functional under Photos app

I presume you mean it's visible in the "Shared with you" tab? Photos doesn't show shares in the Folders view.

**Comment by Danie10** [comment]
I'm testing on a user that has had the album shared in Memories, and who has edit permission on the NC folder.

For Photos app, shared album/folder appears in:
* All Media - opens full view with sidebar and comments
* Photos (folder is also shared for permission) - opens full view with sidebar and comments
* Shared with You - does not open photo full view

In Memories app appears in:
* Albums - but no Activities showing with comments, only Info

What I'm thinking here is that Memories is not picking up on the NC folder permissions suddenly any more. Watch this segment where the test user was seeing the shared photos under Folders view in Memories (that has gone) - https://youtu.be/2A6u0AluCnI?si=DJbGanXXSwvO76xg&t=1892. I should have said in on shared folder there (not shared album).

**Comment by pulsejet** [comment]
> Does turning on hidden folders in the settings change anything? Also is your folders path set to / ?

?

**Comment by Danie10** [comment]
OK will try a new folder - it was a folder and album share. Odd thing it is working still under Photos 100%, and it only stopped straight after I updated Memories.

**Comment by pulsejet** [comment]
> Does turning on hidden folders in the settings change anything? Also is your folders path set to / ?

Please check on this too. This is an important piece of information.

**Comment by Danie10** [comment]
Nope exactly the same:

1. Created new folder under /Photos and shared with edit rights to my test user
2. Uploaded a photo in Memories to /Photos/testfolder and added new album called Test Album and added Test user as a collaborator. Also added photo to the previously shared /Photos/Friends album.
3. Main user added comment to the photo.
4. Logged test user out and in again.
5. Sees new photo and comments perfectly in Photos. Memories sees the photo in Memories under Albums (both in Friends and Test albums) but only info shows, no Activities or other tabs.

**Comment by pulsejet** [comment]
> Does turning on hidden folders in the settings change anything? Also is your folders path set to / ?

This

> Memories sees the photo in Memories under Albums (both in Friends and Test albums) but only info shows, no Activities or other tabs.

The albums view only has the info view, that's a limitation of Nextcloud right now. The question is, can you see the folder in the `Folders` view of Memories now, after turning on hidden folders in the settings.

**Comment by Danie10** [comment]
No I turned on both hidden folders and albums, but none of them show under Folders in Memories. They wer disabled when I did my video though, and I was definitely seeing the Activities and comments.

My main user that uploaded the photos does see the Activities and comments fine in Memories with the focus set like you fixed it. The problem is only with the user that the photos were shared with. It's like that user has not got the edit permissions at NC folder level. But in my video it is working 100% with the test user, they just lost focus to the Info tab every time the photo was changed. They were accessing it in Memories via the Folder view - now that view no longer sees those shared albums at all.

**Comment by Danie10** [comment]
This point in my video at https://youtu.be/2A6u0AluCnI?si=Pe43cyePNEhBnpzp&t=1905 clearly shows the shared folders appearing in Memories under Folders.

**Comment by pulsejet** [comment]
OK, got it. I've no idea how this could happen; Photos and Memories actually use the exact same API to get the folders so the results aren't supposed to be different.

By any chance if you could share the test user on your instance that would be very helpful to debug (you can DM me on the Discord server). Otherwise, we need to wait to see if someone else encounters the same issue, then see what's common. I've just not been able to reproduce it on 3 different instances.

**Comment by Danie10** [comment]
Default root for photos was always set to /Photos and the shared folders under /Photos e.g. /Photos/Friends. But nothing was changed there. Did not update Nextcloud in last few days. It was just the Memories app update.

Photos app is still working exactly the same and showing sidebar with comments.

**Comment by Danie10** [comment]
> By any chance if you could share the test user on your instance that would be very helpful to debug (you can DM me on the Discord server). Otherwise, we need to wait to see if someone else encounters the same issue, then see what's common. I've just not been able to reproduce it on 3 different instances.

Yes how can I reach you on Discord?

**Comment by Danie10** [comment]
OK thanks very much - above issue sorted. Timeline folder in memories app settings was /Photos, but the Folder path should have stayed as /, and I had changed it to /Photos as well. Soon as Folders path in settings went back to /, the shared folders all appeared again.

**Comment by EpochalEngineer** [comment]
> You can actually use comments on on shared _folders_ but not on shared _albums_ (this is an upstream limitation in `nextcloud/server`; the sidebar doesn't currently open on album DAV paths)

Is there a relevant issue/feature request in the server or photos repo about this? I haven't had success searching

This is the biggest blocker to using it as a google photos replacement us and would be interested if it is for others as well.

**Comment by pulsejet** [comment]
https://github.com/nextcloud/server/issues/36454
