### ISSUE TITLE
Log spam in index mode 2

### ISSUE THREAD

**Issue by XDjackieXD** [pulsejet/memories#1091]
**Describe the bug**
Every time the indexer runs, my log is spammed with `The specified folder /_empty_ does not exist for <username>`.
This is because many of my users have not (and probably will not) used the memories app yet and therefore still have the default index path `_empty_` set.
I'd expect the indexer to ignore users that have the path not yet set as this is certainly not an error but rather an expected state.

**To Reproduce**
- Install Memories App
- Set index mode to 2 and leave the path as default (`_empty_`) so that users are prompted the first time they open the memories app
- Do not open the memories app
- Run the indexer (or wait for an automatic run)

**Screenshots**

**Platform:**

- OS: Linux
- Browser: Firefox
- Memories Version: 7.0.2
- Nextcloud Version: 28.0.3
- PHP Version:  8.1.27

**Comment by pulsejet** [comment]
Hmmm we should just ignore this error in general unless on the CLI ... it's pointless since the folder might also not exist e.g. if the user deleted it 👀

**Comment by pulsejet** [comment]
@XDjackieXD you can apply the patch above to get the fix early

**Comment by XDjackieXD** [comment]
Thank you for the quick fix! Seems to be working as intended :D
