### ISSUE TITLE
Integration with TagSpaces

### ISSUE THREAD

**Issue by johnSamilin** [pulsejet/memories#1098]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when editing metadata for several pictures at the same time (when I select a bunch and click edit metadata). Adding tags to them overrides previously added tags, replacing them.

**Describe the solution you'd like**
I found out that there's a solution that fits me in terms of tagging files: TagSpaces. It can create so called Sidecars: json files with the information about assigned tags. Would it be ok if I add some optional setting to Memories so it would pick up those files and use them instead of build-in tag system? This built-in functionality have to be way much better than now.

**Comment by johnSamilin** [comment]
@pulsejet could you please comment when you have time?

**Comment by pulsejet** [comment]
These tags still need to be indexed to be used, which would make it **exactly** identical to the current implementation.

The most straightforward way to supporting tag spaces would be to have a _separate_ app to convert the sidecar to nextcloud collaborative tags.
