### ISSUE TITLE
Error querying places: Invalid transaction state

### ISSUE THREAD

**Issue by PatrickJosh** [pulsejet/memories#1099]
**Describe the bug**
Uploading new photos leads to the following error being produced:
```
{
  "reqId": "ZgRzxvWSeQh6tmQ7Bov9OgAAAEo",
  "level": 3,
  "time": "2024-03-27T19:30:15+00:00",
  "remoteAddr": "ip address",
  "user": "joshua.noeske",
  "app": "memories",
  "method": "PUT",
  "url": "/remote.php/dav/files/joshua.noeske/InstantUpload/Camera/20240327_203003.jpg",
  "message": "Error querying places: An exception occurred while executing a query: SQLSTATE[25000]: Invalid transaction state: 1207 Update locks cannot be acquired during a READ UNCOMMITTED transaction",
  "userAgent": "Mozilla/5.0 (Android) Nextcloud-android/3.28.0",
  "version": "28.0.3.2",
  "data": {
    "app": "memories"
  },
  "id": "660473c8667d1"
}
````
I tried rebuilding the database as well as restarting the database server, both did not help.

**To Reproduce**
1. Setup places database
2. Upload photo

**Platform:**

- Nextcloud Version: 28.0.3
- PHP Version: 8.2.17
- Memories version: 7.0.2

**Comment by PatrickJosh** [comment]
The new photos also don't show up when looking at photos taken at the location. Weirdly, some photos which I took this morning are visible there, although I have not changed anything about the server in the meantime.

**Comment by pulsejet** [comment]
How are you running the DB? You need to pass the `--transaction-isolation=READ-COMMITTED` flag to mysql/ mariadb

**Comment by PatrickJosh** [comment]
I do have `transaction_isolation = READ-COMMITTED` in section `[mysqld]` in the `my.cnf`. In case I have not missed anything in the Nextcloud Docs, this should be sufficient as well. Please correct me if I am wrong.

**Comment by PatrickJosh** [comment]
Querying the config of the database at runtime confirms that setting the transaction level succeeded:
```
+---------------+----------------+
| Variable_name | Value          |
+---------------+----------------+
| tx_isolation  | READ-COMMITTED |
+---------------+----------------+
```

**Comment by PatrickJosh** [comment]
Might this be related?
https://jira.mariadb.org/browse/MDEV-26123

**Comment by pulsejet** [comment]
It is related, but I don't know why it's doing READ UNCOMMITTED to begin with ..

**Comment by pulsejet** [comment]
What version of MariaDD are you on?

**Comment by PatrickJosh** [comment]
Sorry, forgot to mention it. 10.5.23.
`mariadb  Ver 15.1 Distrib 10.5.23-MariaDB, for Linux (x86_64) using  EditLine wrapper`

**Comment by PatrickJosh** [comment]
I also have not recently updated MariaDB. I use Fedora 39 and this version of MariaDB was shipped with the initial release of Fedora 39, so I have been using it for about three months now. The error described above did not occur before today.

**Comment by pulsejet** [comment]
This _might_ be fixed by doing the read in a transaction explicitly.
Try this patch: https://github.com/pulsejet/memories/commit/6b442664b8b22cb6e7b10df773d623aaba60b2dc

Or if you don't want to patch the whole thing, go to `lib/Db/TimelineWritePlaces.php` and replace this line

```
$rows = \OC::$server->get(\OCA\Memories\Service\Places::class)
                ->queryPoint($lat, $lon)
            ;
```

with

```
$this->connection->beginTransaction();
$rows = \OC::$server->get(\OCA\Memories\Service\Places::class)
                ->queryPoint($lat, $lon)
            ;
$this->connection->commit();
```

**Comment by PatrickJosh** [comment]
I just applied the whole patch and uploaded a photo for testing. The error did not occur. I then rebuilt the places database, which led to a lot of those errors before having applied the patch, but not any more now. Seems like it works!
Thank you very much! :blush:
