### ISSUE TITLE
Use App without OCC Commands

### ISSUE THREAD

**Issue by w00lfy** [pulsejet/memories#110]
Fantastic and much-needed app!

It would be great if the app would work without OCC commands to enable users on shared hosting plattforms without SSH access to use it. Not sure if this is technically possible but it would be much appreciated.

Thanks!

**Comment by fcrozat** [comment]
Right now, Memories is usable on Hetzner Storage Share (which has just been updated to Nextcloud NC25). However, since there is no way to have occ running on the instance, I can't do an initial indexing, only images added after the initial install of Memories are indexed.

**Comment by QazCetelic** [comment]
> Right now, Memories is usable on Hetzner Storage Share (which has just been updated to Nextcloud NC25). However, since there is no way to have occ running on the instance, I can't do an initial indexing, only images added after the initial install of Memories are indexed.

You can run OCC commands using KonsoleH, including `memories:index`

![image](https://user-images.githubusercontent.com/51381523/218308551-cb6e4b81-e26f-48bc-a050-6b5ed7920aca.png)

**Comment by fcrozat** [comment]
@QazCetelic thanks a lot, I wasn't aware of this feature in Hetzner konsoleH. It seems Hetzner is whitelisting specific occ commands (the recognize ones aren't enabled).

**Comment by jkaemper** [comment]
I asked Hetzner why the memories:video-setup command isn't available in the KonsoleH commands.
Because it needs ffmpg and that is not installed on their Storage Share Instances for performance reasons. 
Is there any workaround for this? I can live without the thumbnails, but it's a pity that I can't even play videos in the memories app.

**Comment by jkaemper** [comment]
I can't access it myself, but the Hetzner Support edited it for me.
Works just fine, except the thumbnails of course.
Thank you!
