### ISSUE TITLE
[Video playback] wrong orientation

### ISSUE THREAD

**Issue by Kybeer** [pulsejet/memories#1103]
**Describe the bug**

The issue I have is the first time I play a video file in Memories, the orientation on the playbackis wrong; it's tilted 90degrees. This is irrespective if I play the clip in web browser or with Android Memories app.

What's even more odd; the **second time** I play the same clip in the **Android Memories app**, the orientation is correct. If I just keep on watching the same video file, it's correct. If I change to another video file, the issue starts over again. 

I use HW transcode as per this guide: https://memories.gallery/hw-transcoding/. The playback itself is not a problem (all video file play wall) and the physical GPU is being used. 

I have tried to use the option "Enable streaming transpose workaround" in Memories Admin interface. But with that setting, no video files play at all. 

The issue has been present across all Memories versions I have tried - 6.2.2 -> 7.0.2

**To Reproduce**

The behavior is the same every time I play video files. 

**Platform:**

- OS: Nextcloud running in Podman container on RHEL8 VM
- Browser: Firefox
- Memories Version: 7.0.2
- Nextcloud Version: 27.1.6
- PHP Version: 8.2.15
- FFMpeg: (N-68911-ge70e9b6554-static).
- go-vod: 0.2.4
- HW transcode running on physical Fedora 39. Go-vod is running in Podman on that machine.

**Comment by pulsejet** [comment]
One thing to quickly check: does the issue go if you turn off hardware transcoding?

**Comment by Kybeer** [comment]
> One thing to quickly check: does the issue go if you turn off hardware transcoding?


If I disable hardware encoding I cannot play video files at all (they are all h264); the Memories web page/player says "The media could not be loaded, either because the server or network failed or because the format is not supported". In the Memories Android app I just get a spinning wheel. 

Note playing video files in the "normal" Nextcloud interface works, regardless of HW transcode setting. And there's never orientation issues there. 

> 
> Also does it only happen for portrait videos or all videos are rotated?

It seems to be all videos.

**Comment by pulsejet** [comment]
Something is off here, all browsers are supposed to be able to play h264 natively.

1. Did you refresh the page after turning off transcoding?
2. Do the videos play in the Files app?

**Comment by Kybeer** [comment]
> Something is off here, all browsers are supposed to be able to play h264 natively.
> 
>     1. Did you refresh the page after turning off transcoding?
> 
>    Yep, refresh the page helped; playback is working. The orientation issue is still there though (in Memories, with HW transcode disabled).

**Comment by pulsejet** [comment]
Can you provide a sample file?

**Comment by Kybeer** [comment]
> Can you provide a sample file?

Sure, please see this link: https://send.sydit.se/download/0264c554f739ad04/#8oJgoj13Y8xJB0wiFqJhDg

I checked a bit more; it's actually not every video file that has orientation issues. I attached one OK and one NOK.

**Comment by pulsejet** [comment]
Hmm I can't repro the bug. The videos are correctly oriented for me with and without transcoding. Can you try a different browser?

**Comment by pulsejet** [comment]
Another thing to try: re-upload the file that doesn't play right and see if that changes anything

**Comment by Kybeer** [comment]
> Hmm I can't repro the bug. The videos are correctly oriented for me with and without transcoding. Can you try a different browser?

It's the same issue, in Firefox, Chrome, Memories Android app

**Comment by Kybeer** [comment]
> Another thing to try: re-upload the file that doesn't play right and see if that changes anything

I have deleted one of the files with wrong orientation, and reuploaded to NC - it's the same issue 

I have tried to upload both from computer (Windows) and on Android - same issue.

**Comment by pulsejet** [comment]
Well I'm stumped

> Could it be related to ffmpeg version? 

Can't be. Without transcoding, ffmpeg isn't used at all except to generate the preview. The original is just being directly played by the browser, so there's no reason it should rotate (also the fact that both files work okay for me; just very weird)

**Comment by Kybeer** [comment]
I upgraded to NC 28.0.4 and Memories 7.1 yesterday; no difference :(

**Comment by pulsejet** [comment]
Could you share a public link to a folder containing these two files (either folder share or album are fine)? You can DM me on the discord server if you want.

**Comment by Kybeer** [comment]
> Could you share a public link to a folder containing these two files (either folder share or album are fine)? You can DM me on the discord server if you want.

I have created a separate NC folder and shared it. Do you have a place where I can DM you?

**Comment by pulsejet** [comment]
The project has a discord at https://discord.gg/7Dr9f9vNjJ

My username is `pulsejet`

**Comment by Kybeer** [comment]
> The project has a discord at https://discord.gg/7Dr9f9vNjJ
> 
> My username is `pulsejet`

I just DM:ed you there

**Comment by Kybeer** [comment]
I just discovered if I convert a problematic video file from h264 to h265, it plays with correct orientation in Memories. The preview thumbnail get s bit distorted though.

**Comment by pulsejet** [comment]
v7.3 ships with a new option that allows using transpose in software. This should fix the issue. See https://github.com/pulsejet/memories/issues/794#issuecomment-2088147456

**Comment by Kybeer** [comment]
> This should fix the issue.

It seems to be working! Would you say there's any obvious downside to the workaround?

**Comment by pulsejet** [comment]
Great! It'll be somewhat slower than doing it all in HW. The frames are decoded and scaled on the device, then copied to main memory and rotated, copied back to the device and encoded. The good part is at least this only happens for portrait videos.

**Comment by Kybeer** [comment]
> It'll be somewhat slower than doing it all in HW

It seems quite fast here anyway :)
