### ISSUE TITLE
Can't select Folders / Timeline Path [Nextcloud <25]

### ISSUE THREAD

**Issue by zell-mbc** [pulsejet/memories#111]
This post is in reference to the exchange here: https://www.reddit.com/r/NextCloud/comments/ybshbu/comment/itq9r0d/?context=3

![image](https://user-images.githubusercontent.com/29018767/197814996-f6389a98-5731-4d7f-9f1b-59f6d704798f.png)

I did update to v3.3.7 and the new dialog opens. Unfortunately the wheel (2) keeps on spinning.
This may be because the path in (1) is wrong, doesn't exist, a leftover from my tests yesterday. But I can't clear that string because the dialog opens right away whenever I select the field.
Same happens when selecting "Timeline Path"

I tried to remove and reinstall the app, but the paths were kept.

Edit: Just saw your question re. JavaScript on Reddit.
Here's what I can see:
![image](https://user-images.githubusercontent.com/29018767/197816244-f873fab8-b29d-4994-95c8-76cb73362d37.png)

Edit, Edit: Think I should mention that I am running NC on Docker, not sure if it's relevant though.

**Comment by pulsejet** [comment]
Can you check the JS console for any errors?

**Comment by zell-mbc** [comment]
Librefox, a stripped down version of Firefox. I can test Chromium as well

**Comment by pulsejet** [comment]
Can you try running
```bash
occ user:setting username memories timelinePath "/"
occ user:setting username memories foldersPath "/"
```
to see if that fixes it? Replace `username` with yours.

**Comment by zell-mbc** [comment]
The docker equivalent ( docker exec --user www-data nextcloud-app php occ user:setting thomas memories foldersPath "/") for both paths, did go through without an error.
And Bingo!
The dialog now works, shows my NC filestructure

Next step is to run the occ index command I guess?

I guess I could set the path for my users the same way I just deleted the wrong path?

**Comment by pulsejet** [comment]
Yep, you can set it the same way or let them do it themselves. There's an initial start page now (see #109)

**Comment by zell-mbc** [comment]
Cool! Index is running. Thanks a lot for being so responsive!

**Comment by pulsejet** [comment]
For future reference, this issue is already fixed in Nextcloud 25. Please keep this issue open so others can find it; I'll close when Nextcloud 26 comes out.

**Comment by zell-mbc** [comment]
Selecting the folder a second time seems to add an additional "\".
Two "/" in a path is usually not a problem but thought I'd flag it.

![image](https://user-images.githubusercontent.com/29018767/197822493-e49d93de-6d9b-4b57-a131-40372e73c646.png)

By the way, I think I understand what Timeline Path is about, that's my photos, but whats the meaning of "Folders Path" then?

**Comment by pulsejet** [comment]
> Selecting the folder a second time seems to add an additional "". Two "/" in a path is usually not a problem but thought I'd flag it.

Shouldn't be a problem. Thanks for reporting anyway!

> By the way, I think I understand what Timeline Path is about, that's my photos, but whats the meaning of "Folders Path" then? Edit: Think I got it, this setting is used for the Folder tab, I guess for cases where people want to access photos outside of their timeline.

Yep. See #85

**Comment by ku8az** [comment]
I have similar problem, after new installation of Memories I can't select Timeline folder, nothing happens and dialog reappears. In JS console is an error: An exception occurred while executing a query: `SQLSTATE[21000]: Cardinality violation: 7 ERROR: more than one row returned by a subquery used as an expression`
After setting of both folders manually via occ, I get the same error in UI as well.

Raspberry Pi 4 (4GB)
NextCloud 25.0.2
PostgreSQL 13.8
Memories 4.9.3
