### ISSUE TITLE
Photo deduplication

### ISSUE THREAD

**Issue by corsac-s** [pulsejet/memories#1112]
**Is your feature request related to a problem? Please describe.**
Photos present twice in the Nextcloud are displayed twice. For example I auto-upload the photos from my phone in a specific folder, and I also export photos both from my digital camera and from my phone in specific folders (mounted as external storage but available locally) for specific events. A photo taken from my phone will then appear twice once indexed.

**Describe the solution you'd like**
Similar photos (metadata content or maybe file hash) are only displayed once in the timeline etc.

**Describe alternatives you've considered**
Not sure, honestly.

**Additional context**
This might be a bit similar to #537 but here the files are exactly the same.

**Comment by ChildLearningClub** [comment]
Are the file names identical, as well as the extension? And being uploaded to the same folder? 

I had a similar issue with the Nextcloud app, uploading with lowercase .jpg extension and the same image exported from my phone through the PC having the same file name but with the uppercase .JPG extension. is this the same issue you’re experiencing?

**Comment by corsac-s** [comment]
In my case the photos are identical in content, have the same exif metadata, the same filename and same extension (and same case) and the same hash. They're not in the same folder.

In my case I *know* they are duplicate and I want to keep them that way, I just would like the indexing to only pick and display one of them.

**Comment by ChildLearningClub** [comment]
Okay, now I understand. So then there would also need to be away for you to choose, which one is displayed and which one is not. The .nomedia flag in the folders that you do not want indexed or visible, is not what you were looking for?

**Comment by corsac-s** [comment]
I don't think it really matters which one is displayed (since they're identical).

.nomedia doesn't work: I do want all the *folders* (the one from my phone autoupload and the one from my manual uploads) to be indexed. I just would like identical photos not to be displayed twice on the timeline, explore etc.

**Comment by ChildLearningClub** [comment]
I see, thank you for clarifying. This would be a useful feature.

**Comment by ChildLearningClub** [comment]
I know this doesn’t completely solve your issue. But I guess until something like this does get implemented, if it’s not too much trouble you can separate The parent folders that each one goes into and then within the Memories settings only select the path to the ones that you want displayed.

**Comment by corsac-s** [comment]
Thanks for the lead, but same that with .nomedia: I actually want photos from both folder to appear in the timeline, because autoupload has all my phone photos, and manual upload has all the camera photo + some phone photos and I want all the phone photos and all the camera photos (just not duplicates :)

**Comment by corsac-s** [comment]
Wow, that was fast

**Comment by pulsejet** [comment]
![image](https://github.com/pulsejet/memories/assets/10709794/82523c71-5330-428d-b978-c2f7e83941fc)

Just a note: this has the potential for false positives in certain cases, e.g. if just the metadata is different on both images is different then they might get incorrectly de-duplicated; which is why it'll default to false. These cases should be rare though.

**Comment by corsac-s** [comment]
Thanks! I don't really have the setup to build, test and confirm back. Are there artefacts from the github actions or something I can try?

**Comment by pulsejet** [comment]
Not really, you'll need to wait for the next release or build from source

**Comment by pulsejet** [comment]
Available with 7.2
