### ISSUE TITLE
Add an option to "pin date on top" for timeline view (and folder view as well)

### ISSUE THREAD

**Issue by AiroPi** [pulsejet/memories#1116]
**Is your feature request related to a problem? Please describe.**
When we are looking for a specific date, it can be difficult to find the good day just by scrolling.

**Describe the solution you'd like**
A simple solution that would simplify this task a lot is to always keep the date of the photos we are looking at at the top of the screen.

<img width="1198" alt="image" src="https://github.com/pulsejet/memories/assets/47398145/fdbd70d0-3809-4fbe-95ee-b891da578278">

So even when we are in the middle of a lot of photos of the same day, we know date day these pictures have been picked up.

For example, if we are looking for a photo taken on may 26th, with use the scrollbar to go to the middle of may. If there is a lot of photos on may 20th, we only see these photos, with no date informations. So we don't know if we should go up or down.

We a date always pinned on top, this would be easier.

This is something Immich do (take a look at the demo), and Google photo iirc. (can't test I have deleted all my photos from GP)

**Comment by pulsejet** [comment]
![image](https://github.com/pulsejet/memories/assets/10709794/8f53fd29-5879-490e-8d2b-0ed6badc5078)
![image](https://github.com/pulsejet/memories/assets/10709794/a8ee335e-e48c-49a6-903d-a1d44b1c796f)
