### ISSUE TITLE
Person page 500 error | posgresql related

### ISSUE THREAD

**Issue by bin101** [pulsejet/memories#1117]
**Describe the bug**
Something in between 7.0.2  and 7.1.0 has broken the person page for me.
Opening the chrome dev console shows an 500 error for the `apps/memories/api/clusters/facerecognition` endpoint:
```
{
    "message": "An exception occurred while executing a query: SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"frp.id\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 40: ...mcov\".\"fileid\")) LIMIT 1) AS \"cover\" FROM (SELECT \"frp\".\"id\"...\n                                                              ^"
}
```

First i thought is was the same issue as in #285 but this to be something new.

**To Reproduce**

**Screenshots**

**Platform:**

- OS: Debian bookworm
- Browser: Chrome
- Memories Version: 7.1.0
- Nextcloud Version: 28.0.4
- PHP Version: 8.1
- Posgresql: 15.6

**Comment by pulsejet** [comment]
Can you validate the patch in https://github.com/pulsejet/memories/commit/ef75771e0823158332155c0c1485e28020a1066a

**Comment by bin101** [comment]
@pulsejet can confirm that this is the fix
