### ISSUE TITLE
Unable to download 2 photos in a row

### ISSUE THREAD

**Issue by AiroPi** [pulsejet/memories#1121]
**Describe the bug**
I am able to download a photo the first time, then it doesn't work, and I need to reload the page to be able to download again.

**Screenshots**

https://github.com/pulsejet/memories/assets/47398145/c3118b8d-9f89-4343-9be5-1720b0f2d717

**Platform:**
- OS: MacOS
- Browser: Chrome
- Memories Version: 7.1.0
- Nextcloud Version: 28.0.3

**Comment by pulsejet** [comment]
Any logs in js console)

**Comment by AiroPi** [comment]
@pulsejet no, I checked, it seemed strange to me but there was nothing
I will try again.

**Comment by pulsejet** [comment]
Perhaps the file is overwritten? Did you try downloading two different files?

**Comment by pulsejet** [comment]
Can you reproduce the error on the demo at https://demo.memories.gallery/apps/memories/

**Comment by AiroPi** [comment]
Hm I have no problem on the demo. The files are correctly downloaded 🤔

**Comment by pulsejet** [comment]
Hm, can you try safari with your instance?

**Comment by pulsejet** [comment]
Another thing to try -- your instance in incognito mode. Maybe some permission (multiple file download) got denied

**Comment by AiroPi** [comment]
It works fine with Safari...

I tested to clear the cache / remove the cookies but it didn't change anything.

**Comment by AiroPi** [comment]
@pulsejet same problem in incognito

**Comment by AiroPi** [comment]
I've tested with an other chromium-based browser and it works fine too 🤷
The problem is only between my current browser and my memories instance.

**Comment by pulsejet** [comment]
Likely a bug in the browser then 😆 
The download logic is too simple, I can't see how it could fail without error ...

**Comment by AiroPi** [comment]
I don't see it either. What's strange is that it doesn't on the demo. I'll keep looking on my own, thanks!

**Comment by AiroPi** [comment]
Btw the same thing occur when I try to download from the files interface, so it isn't related to memories at all.

**Comment by AiroPi** [comment]
If anyone encounters the same problem, the solution is quite simple. Search for "All site settings" somewhere in your chromium-based web browser (or directly goes to chrome://settings/content/siteDetails?site=https://<YOUR_NEXTCLOUD>) and  makes sure "automatic download" isn't blocked. That's it.
