### ISSUE TITLE
Pinned date does not appear when going to the middle of a bunch of photos

### ISSUE THREAD

**Issue by AiroPi** [pulsejet/memories#1125]
This follows #1116.

**Describe the bug**
When we click in the scroll bar in the middle of a bunch of photos from the same date, the pinned date doesn't appear. We need to scroll until the timeline load the date element.

**To Reproduce**
- have a lot of photos of the same day
- click, in the scrollbar, in the middle of the date
- the pinned date isn't present

**Platform:**
- Browser: Chrome
- Memories Version: 7.2.0

**Comment by pulsejet** [comment]
I can't reproduce this. Does it happen under some specific circumstances? E.g. the top pinned date is (intentionally) hidden when there's only one row in the day you're looking at.

**Comment by AiroPi** [comment]
Imagine I have a lot of photos from the 26/04/2019 (enough to fill the whole screen and enough for memories to not load the photos of the next date or the previous date)
While we are not near to the "top of the date" (where the date is actually present without pin), the date doesn't appear on top of the screen (I guess the element isn't loaded because it shouldn't appear while it is not "near to be showed on screen").

**Comment by AiroPi** [comment]
Here is a little video showing this. The date only appear when we are a few rows before where the date is normally present.

https://github.com/pulsejet/memories/assets/47398145/ac9a773c-5cc9-451c-9b90-807f7c5e4544
