### ISSUE TITLE
Database triggers not set up

### ISSUE THREAD

**Issue by portalx** [pulsejet/memories#1128]
**Describe the bug**
Database triggers not set up not working.

**To Reproduce**
Steps to reproduce the behavior: As per help from memories app help.

**Screenshots**

**Platform:**

- OS: ubuntu 22.04
- Browser: [Chrome]
- Memories Version: [7.2.0]
- Nextcloud Version: [28.0.4]
- PHP Version: [8.1.2-1ubuntu2.14]

**Additional context**
c/p from maintenance:repair 
 - Repair MySQL collation
     - All tables already have the correct collation -> nothing to do
 - Repair mime types
 - Clean tags and favorites
     - 0 tags of deleted users have been removed.
     - 0 tags for delete files have been removed.
     - 0 tag entries for deleted tags have been removed.
     - 0 tags with no entries have been removed.
 - Repair invalid shares
 - Move .step file of updater to backup location
 - Add move avatar background job
     - Repair step already executed
 - Add preview cleanup background jobs
 - Migrate oauth2_clients table to nextcloud schema
     - Update the oauth2_access_tokens table schema.
     - Update the oauth2_clients table schema.
     - Delete clients (and their related access tokens) with the redirect_uri starting with oc:// or ending with *
 - Fix potential broken mount points
     - No mounts updated
 - Repair language codes
 - Add log rotate job
 - Clear frontend caches
     - Image cache cleared
     - JS cache cleared
 - Clear every generated avatar
 - Add preview background cleanup job
 - Queue a one-time job to cleanup old backups of the updater
 - Cleanup invalid photocache files for carddav
 - Add background job to cleanup login flow v2 tokens
 - Remove potentially over exposing share links
     - No need to remove link shares.
 - Clear access cache of projects
 - Reset generated avatar flag
 - Keep legacy encryption enabled
 - Check encryption key format
 - Remove old dashboard app config data
 - Add job to cleanup the bruteforce entries
 - Queue a one-time job to check for user uploaded certificates
 - Repair DAV shares
 - Add background job to set the lookup server share state for users
 - Add token cleanup job
 - Clean up abandoned apps
 - Add possibly missing system config
 - Add AI tasks cleanup job
 - Queue a job to generate metadata
 - Add read permissions for existing announcements
    0 [->--------------------------]
 - Upgrading Circles App
 - Fix component of birthday calendars
     - 4 birthday calendars updated.
 - Regenerating birthday calendars to use new icons and fix old birthday events without year
     - Repair step already executed
 - Fix broken values of calendar objects
    0 [----->----------------------]
 - Registering building of calendar search index as background job
     - Repair step already executed
 - Register building of social profile search index as background job
     - Repair step already executed
 - Registering background jobs to update cache for webcal calendars
     - Added 0 background jobs to update webcal calendars
 - Registering building of calendar reminder index as background job
     - Repair step already executed
 - Clean up orphan event and contact data
     - 0 events without a calendar have been cleaned up
     - 0 properties without an events have been cleaned up
     - 0 changes without a calendar have been cleaned up
     - 0 cached events without a calendar subscription have been cleaned up
     - 0 changes without a calendar subscription have been cleaned up
     - 0 contacts without an addressbook have been cleaned up
     - 0 properties without a contact have been cleaned up
     - 0 changes without an addressbook have been cleaned up
 - Remove activity entries of private events
     - Removed 0 activity entries
 - Clean up old calendar subscriptions from deleted users that were not cleaned-up
    0 [--------->------------------]
     - 0 calendar subscriptions without an user have been cleaned up
 - Remove invalid object properties
     - 0 invalid object properties removed.
 - Fix the share type of guest shares when migrating from ownCloud
 - Copy the share password into the dedicated column
 - Set existing shares as accepted
 - Remove any playlist files mistakenly added to music_tracks table
 - Combine multi-disk albums and store disk numbers per track
 - Register Music background jobs and remove legacy registrations
 - Set creation and update dates for the library entities without one
 - Clean up meta table
 - Show a hint about the new editor to existing users
 - Update OAuth token expiration times
 - Install recognize dependencies
 - Create help command
 - Invalidate access cache for projects conversation provider
     - Invalidation not required
 - Cache the user display names
 - Switches from default updater server to the customer one if a valid subscription is available
     - Repair step already executed
 - Send an admin notification if monthly report is disabled
 - Force-reset all Text sessions before Yjs migration
 - Initialize migration of background images from dashboard to theming app
 - Add background job to check for backup codes
 - Repair provider registrations
 - Populating added database structures for workflows

c/p from mysql.
+---------------------------------+-------+
| Variable_name                   | Value |
+---------------------------------+-------+
| log_bin_trust_function_creators | ON    |
+---------------------------------+-------+
1 row in set (0.00 sec)

Restarted the php-fpm.

Error still persists.

- Any errors in the JS console? NO
- Any errors in the Nextcloud server logs? NO

I don't know what else should I search for.  Any advice will be useful.

Thank you

**Comment by pulsejet** [comment]
I don't see the repair steps for Memories being executed. Is the app enabled properly when you run `maintenance:repair`? It should be something like:

```
...
Copy the share password into the dedicated column
 - Set existing shares as accepted
 - Repair steps for Memories
     - External table schema seem up to date
     - Recreated filecache trigger with: Doctrine\DBAL\Platforms\MariaDb1052Platform
     - exiftool binary is configured: /var/www/html/apps/memories/bin-ext/exiftool-amd64-glibc
     - go-vod binary is configured: /var/www/html/apps/memories/bin-ext/go-vod-amd64
     - ffmpeg binary is configured: /usr/bin/ffmpeg
 - Update OAuth token expiration times
 - Install recognize dependencies
 ...
```

Maybe try reinstalling Memories.

**Comment by portalx** [comment]
pulsejet thank you for your answer !
Yes it's enabled and working without problem !! This problem came with the this version. 
I will install it again to check if the error persists.  (I have 45000 photos scanned ! Let's go again :>)

Thank you

**Comment by portalx** [comment]
Reinstalling Memories fixed the problem !

"Database triggers are set up correctly."

Thank you for your support !!

**Comment by steadfasterX** [comment]
having the same issue on a clean install.. 
maintenance:repair does not show up memories at all. Tried also with "--include-expensive" but nothing..

what is the best way for such a re-install? simply via the nextcloud UI an uninstall + install? do we need to re-index etc everything again?

**Comment by portalx** [comment]
Hello steadfasterX,

In my case I just removed and reinstalled the app through the Nextcloud UI. After that, everything worked back. I didn’t do any re-index etc..

I don’t know if you need to do a ctrl & f5 to your browser to load again the page if you are browsing through windows. 

Thank you.

**Comment by steadfasterX** [comment]
thanks @portalx ! I tried now to simply deactivate it. Then activated it again (so no uninstall) and the error message is gone! dunno what that made but at least it seems to work now :)
