### ISSUE TITLE
Question regarding bundled exiftool and SELinux

### ISSUE THREAD

**Issue by PatrickJosh** [pulsejet/memories#113]
Hey,

I recently installed Memories on my Nextcloud instance running on Fedora Server 36. It's a very good app, especially the usage of the EXIF data is very important for me. Thank you very much! 

However, I have a question regarding the bundled version of exiftool. Since Fedora runs in SELinux enforcing mode (and I am not willing to change that), I have some trouble getting the shipped binaries to run. However, I was able to get the bundled perl script to be executable by the php-fpm directly by changing the file context of it. My question now is, does the perl script have any disadvantages compared to the binaries? I suspect that the performance of the binaries is higher, but I do not know what happens internally.

I will still try to figure out a way to make the binaries run with SELinux, but I won't continue until Thursday with this since I have an exam tomorrow. But if I manage to make them executable, I'll let you know, maybe this could be useful for others too.

**Comment by pulsejet** [comment]
They're exactly the same, so don't worry about it.

In fact, the perl script is probably faster since executing the bundled binary also means you've to unpack the Perl interpreter first. Unfortunately, the alpine-based docker images don't ship with perl, and creating a new image is a hassle many people aren't willing to go through; which is why the bundled version.

**Comment by PatrickJosh** [comment]
Oh, that's even better. Thank you very much for the quick response! :smile: 

What could still be useful for other people is how I managed to make exiftool executable by php with SELinux in enforcing mode.
I changed the file context of the exiftool perl script to `httpd_sys_script_exec_t`, which makes it executable by php-fpm. This can be done using the command `sudo semanage fcontext -a -t httpd_sys_script_exec_t <path_to_nextcloud>/apps/memories/exiftool-bin/exiftool/exiftool'` and then applying `sudo restorecon -v <path_to_nextcloud>/apps/memories/exiftool-bin/exiftool/exiftool` to actually change the file context. However, this could lead to problems while updating the app. To update the app, temporarily change the file context back to `httpd_sys_rw_content_t` (if you want to use the web based updater) by using `sudo chcon -t httpd_sys_rw_content_t <path_to_nextcloud>/apps/memories/exiftool-bin/exiftool/exiftool` and applying `sudo restorecon -v <path_to_nextcloud>/apps/memories/exiftool-bin/exiftool/exiftool` after the update.

**Comment by pulsejet** [comment]
Great, thank you!
