### ISSUE TITLE
Local photos in the app are low quality

### ISSUE THREAD

**Issue by Spp595** [pulsejet/memories#1137]
#### Describe the bug:
In the Android application, if you add local folders to the memories feed and then open them, they are shown in very low quality (although they are on my phone), BUT if you zoom in a little, the quality becomes original. I think downgrading photo quality should not apply to local photos

#### Platform:
- OS: Android (App)
- Memories Version: 7.2.0
- Memories App Version 1.9
- Nextcloud Version: 28.0.4
- PHP Version: 8.2.17

**Screenshots**
Original Photo 
![PXL_20240414_122231109](https://github.com/pulsejet/memories/assets/104263581/471d7ce7-ee5d-4104-8035-512f76d49625)
Before zooming
![Screenshot_20240414-162248_Memories](https://github.com/pulsejet/memories/assets/104263581/a7ef2edd-c006-4911-b908-ba2b503ac67f)
After zooming
![Screenshot_20240414-162657_Memories](https://github.com/pulsejet/memories/assets/104263581/9cf0ccb4-d819-4419-8fa5-8d71a7aeab4e)
![Screenshot_20240414-173444_Memories](https://github.com/pulsejet/memories/assets/104263581/9302899f-46b4-42c8-bada-107c9cd539f8)

**Comment by pulsejet** [comment]
Please test with v7.3 if any change

**Comment by pulsejet** [comment]
Note: you also need the latest android version (1.11). This might not be available on Google Play yet, but should be in a few days.

**Comment by Spp595** [comment]
Thank you, the display is correct now. Android 1.11 update is not required, only the server part update is required.
