### ISSUE TITLE
503 on /memories/api/faces

### ISSUE THREAD

**Issue by illnesse** [pulsejet/memories#114]
Used to work fine & super fast last night, all i did in the meantime was updating memories and recognize, then did a memories:index. Now it stays at _pending_, then times out, no errors/warning in the log, latest version. Everything else loads instantly.

Once i open the people tab i see 2 mariadb threads stuck at 94% cpu, otherwise system load is low, lots of free resources

Photos/people works, although uses extreme amounts of cpu and memory clientside, even on a high end system, due to its bad implementation. It just freezes after a few hundred faces and then the browser dies a painful death

```
MariaDB [nextcloud]> select count(*) from oc_recognize_face_detections;
+----------+
| count(*) |
+----------+
|    36632 |
+----------+
1 row in set (0.005 sec)

MariaDB [nextcloud]> select count(*) from oc_recognize_face_clusters;
+----------+
| count(*) |
+----------+
|     4475 |
+----------+
1 row in set (0.001 sec)
```

**Comment by pulsejet** [comment]
Hmm. Does the timeline and folders view work fine or that has this issue too?

**Comment by pulsejet** [comment]
> ```
> MariaDB [nextcloud]> select count(*) from oc_filecache;
> +----------+
> | count(*) |
> +----------+
> |  1247761 |
> +----------+
> ```
> 
> wonder why filecache has so many rows too, i only have like 120k files in storage, any ideas?
> 
> apparently i have smb connections in my oc_storages that aren't in use at all and are not showing up in the ui, with 100k rows in oc_filecache referencing them.. ?

Maybe you need `occ files:cleanup`? There are also other files in there, e.g. previews.

**Comment by pulsejet** [comment]
@illnesse this is hard to test for me since I don't run recognize in production myself. Basically the potential fix is adding an index on `file_id` on `oc_recognize_face_detections`. Could try this and see if it fixes the issue?
Just need to run the SQL:
```sql
CREATE INDEX memories_fileid_idx ON oc_recognize_face_detections (file_id);
```

**Comment by pulsejet** [comment]
Great, thanks! Please leave this open till it's actually fixed.

**Comment by pulsejet** [comment]
@illnesse can you delete the index you added and test with v4.3.8?

**Comment by pulsejet** [comment]
Out of curiosity, how does the People view of the Photos 2.0 app work with so many faces?

**Comment by pulsejet** [comment]
It should have created the index, so it shouldn't be slow anymore. Did you run the migrations after upgrade? Maybe try `occ memories:index` and it should create the index on the recognize table (otherwise something is broken).

**Comment by pulsejet** [comment]
Ahh I see. Running index should still re-add it.

**Comment by pulsejet** [comment]
So to confirm, is it usable after running this (is the index being created right?)

**Comment by pulsejet** [comment]
Did you try a reboot?

**Comment by pulsejet** [comment]
Couple of questions:
1. What kind of ballpark loading time did you have before 3.3.7?
2. Can you confirm the memories index exists on oc_filecache?

**Comment by pulsejet** [comment]
That is similar to what it's doing now with v4.4+. Btw for more background, we had a single index on the actual file path earlier (before v4.3.8). This was super fast, but mysql doesn't like it (#106), and the index tends to get very bulky because the column is VARCHAR(4000). So the newer design uses a CTE to query the folders and then directly look for files in these. Before 4.4, this query is done in PHP; now everything is done in SQL again, by joining the CTE to the base query directly. This should hopefully fix this particular issue of 1000s of operators.

**Comment by pulsejet** [comment]
Huh. Is the timeline fine? (also performance-wise)

**Comment by pulsejet** [comment]
Any query log?

**Comment by pulsejet** [comment]
That looks totally fine. Can you try changing your timeline path to `/` to see if that changes anything?

**Comment by pulsejet** [comment]
Wow 😆 
I'm stumped now. Maybe you need to try some query variations. Or perhaps the memories index is messed up and needs clearing?

**Comment by pulsejet** [comment]
Yup. Try this maybe. If this works then your memories index is broken.
```sql
WITH RECURSIVE oc_cte_folders(fileid) AS (
  SELECT 
    f.fileid 
  FROM 
    oc_filecache f 
  WHERE 
    f.fileid = 5628943 
  UNION ALL 
  SELECT 
    f.fileid 
  FROM 
    oc_filecache f 
    INNER JOIN oc_cte_folders c ON (
      f.parent = c.fileid 
      AND f.mimetype = 2 
      AND f.fileid <> 5628968
    )
) 
SELECT 
  `rfc`.`id`, 
  `rfc`.`user_id`, 
  `rfc`.`title`, 
  COUNT(DISTINCT f.fileid) AS `count` 
FROM 
  `oc_recognize_face_clusters` `rfc` 
  INNER JOIN `oc_recognize_face_detections` `rfd` ON `rfc`.`id` = `rfd`.`cluster_id` 
  INNER JOIN `oc_filecache` `f` ON `f`.`fileid` = `rfd`.`file_id` 
  INNER JOIN `oc_cte_folders` `cte_f` ON `f`.`parent` = `cte_f`.`fileid` 
GROUP BY 
  `rfc`.`id` 
ORDER BY 
  rfc.title <> '' DESC, 
  `count` DESC, 
  `rfc`.`id` ASC
```

**Comment by pulsejet** [comment]
This query isn't using memories anymore, so that's even weirder. How about this:
```sql
SELECT 
  `rfc`.`id`, 
  `rfc`.`user_id`, 
  `rfc`.`title`, 
  COUNT(DISTINCT f.fileid) AS `count` 
FROM 
  `oc_recognize_face_clusters` `rfc` 
  INNER JOIN `oc_recognize_face_detections` `rfd` ON `rfc`.`id` = `rfd`.`cluster_id` 
  INNER JOIN `oc_filecache` `f` ON `f`.`fileid` = `rfd`.`file_id` 
GROUP BY 
  `rfc`.`id`
```

**Comment by pulsejet** [comment]
@illnesse could you join an IM chat at gitter? https://gitter.im/pulsejet/memories
Faster to debug that way.

> 363 rows in set (0.039 sec)

Interesting. I thought you had thousands of faces? (let's continue in gitter hopefully)

**Comment by pulsejet** [comment]
I believe the original issue is now fixed, so let's close this now.
