### ISSUE TITLE
Menu display error in Firefox under MacOS

### ISSUE THREAD

**Issue by joskapista44** [pulsejet/memories#1142]
**Describe the bug**
If I open a picture with memories, I still can see the nextcloud menu "one layer below", and can't use the menu of memories which overlaps on it (for example to start a slideshow)

**To Reproduce**
Open a picture with firefox on MacOS

**Screenshots**
<img width="1553" alt="screenshot 2024-04-16 - 9 45 18" src="https://github.com/pulsejet/memories/assets/28981610/d4ed24aa-f3c8-4b3c-921b-9c869ac265d5">

**Platform:**

- OS: [MacOS 14.4.1]
- Browser: [Firefox 115.9.1]
- Memories Version: [e.g. 7.2.0]
- Nextcloud Version: [e.g. 28.0.4]
- PHP Version: [e.g. 8.1.2]

**Additional context**
With safari, all seems ok.

**Comment by pulsejet** [comment]
See #1104

**Comment by joskapista44** [comment]
Thank you
