### ISSUE TITLE
Photos and previews only showing in grey, live photos are working

### ISSUE THREAD

**Issue by trvrcr** [pulsejet/memories#1146]
**Describe the bug**
No photos show in overview of any page

**To Reproduce**
Steps to reproduce the behavior
Open Memories,
Photos are grey, small broken icon when clicking photo
Live photos start showing, yet after the live part the photo becomes grey again

**Screenshots**
![image](https://github.com/pulsejet/memories/assets/64335794/2d86f36e-e784-4859-9575-4664f3837f4a)
![image](https://github.com/pulsejet/memories/assets/64335794/ca135c22-f004-4af9-886a-21f185563b54)
![image](https://github.com/pulsejet/memories/assets/64335794/de8ec056-e615-453f-8e72-837e1439379e)

**Platform:**

- OS: Debian 12
- Browser: Firefox
- Memories Version: 7.2
- Nextcloud Version: 28.0.4
- PHP Version: 8.1

**Additional context**
I have gone over the configuration multiple times
I have re-initiated the indexing multiple times
I cannot get it to work which is a bummer, as i find the app really cool.
hope you can help me find the issue, or where i have gone wrong.

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

**Comment by pulsejet** [comment]
Can you see previews in the files and photos apps? I'd check the preview generation settings in the Memories admin panel.

**Comment by trvrcr** [comment]
I have checked.
In the files and photo's app the previews and photo's are both shown.

The preview generation settings in de admin panel are as follows:
![image](https://github.com/pulsejet/memories/assets/64335794/8e3be947-6a83-4291-8c3c-8d578a9196ad)
![image](https://github.com/pulsejet/memories/assets/64335794/ccf085ec-15ee-4bd5-8ba7-3703aa49d565)

are the "Additional configuration may still be required." options explained in the [configuration pages](https://memories.gallery/config/#preview-storage)?

**Comment by trvrcr** [comment]
No errors in the nextcloud server logs.
![image](https://github.com/pulsejet/memories/assets/64335794/9e4b3f3f-9110-495f-937c-938acd68e59f)

But errors in the JS console:
![image](https://github.com/pulsejet/memories/assets/64335794/6b8c675f-67e6-45b6-8795-2ff27c1496a7)

How can I check what is blocking the content? 
Is this server-side or client-side?

Mayor thanks to put me on this track!!

**Comment by pulsejet** [comment]
Your http server or reverse proxy is setting a wrong CSP. Just remove any CSP headers from your http config.

**Comment by trvrcr** [comment]
I can confirm this is the solution.
I took my time to find the header that was causing the problem.
Thank you very much for the expertise.
