### ISSUE TITLE
exiftool 测试失败：exiftool version does not match: expected 12.70 but found 12.60。

### ISSUE THREAD

**Issue by Lydds** [pulsejet/memories#1151]
exiftool 测试失败：exiftool version does not match: expected 12.70 but found 12.60。

**Comment by pulsejet** [comment]
Seems like some permissions issue. Clean your /tmp directory, then reinstall memories (make sure the apps/memories folder was deleted)

**Comment by Lydds** [comment]
好的，我试一试。
