### ISSUE TITLE
Error : "Request faild with status code 500" on opening 'folders' on memories mobile

### ISSUE THREAD

**Issue by Lumberj4cked** [pulsejet/memories#1152]
- You are using the latest version of the app. > yes
- You tried and can replicate the bug. > yes
- You have followed the [configuration steps](https://memories.gallery/config/). > yes
- You have looked at the [troubleshooting](https://memories.gallery/troubleshooting/) documentation. > yes
- You have searched the [open issues](https://github.com/pulsejet/memories/issues) > yes, even the closed ones.

-->

**_**Describe the bug**
A clear and concise description of what the bug is._**
when I try to load the 'Folders' page on 'Explore' tab it sometimes loads but mostly shows error 'Request failed with status code 500', this didn't used to happen, I updated nextcloud and memories yesterday, enabled HW transcoding and set --log_bin_trust_function_creators=true on my docker compose for MariaDB, I also missed the 'places' on top of my 'explore' tab on mobile so I tried to recreate the places db and had some issues with that.
doing occ memories:places-setup via `docker exec -u 33 -t nextcloud php occ memories:places-setup` kept freezing, doing it first via `docker exec -u 33 -it nextcloud bash` and then do `php occ memories:places-setup` did work and I still did not see the places on mobile but they did show up on PC so I called it a day.
After this, nextcloud and memories all day. but since halfway today I get that error, in the nextcloud logs it shows the error:

Exception
Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused
Exception thrown: Doctrine\DBAL\Exception

I can connect to my database without issues, and sometimes it works to load the folders page but most of the time I get this error

**_**To Reproduce**
Steps to reproduce the behavior:_**
I try to open the folders page but it shows me the error, it works better on PC/Web than on mobile but it still keeps happening, I don't know what is causing it sadly

**Screenshots**
![Screenshot_20240420_191944_Memories](https://github.com/pulsejet/memories/assets/57967741/5e7e132e-905d-49c7-b7a3-e1654a077213)

![Screenshot 2024-04-20 193120](https://github.com/pulsejet/memories/assets/57967741/e6966947-767d-4ffc-a64d-3589fc412564)

**Platform:**

- OS: Android, Windows-Web
- Browser: Firefox, Android-firefox
- Memories Version: 7.2.0
- Nextcloud Version: 2.8.0.4
- PHP Version: 8.2.18

**Additional context**
I restarted the nextcloud instance, the database instance, i dont use redis.
I can connect to the DB without issues, nextcloud is not in maintenance, i use docker for my Nextcloud and DB instances.

- Any errors in the JS console?
Trying to get this data on PC/web it did not throw me the error on 'Folders' (which it does keep doing on mobile) but on PC it does give the error on 'Explore' and 'Places' and 'Map', and gives this error in JS console : (domain name changed for privacy reasons)
`Object { stack: "D@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:1548662\n61348/Te.xhr</</m/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:1562530\nm@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:1562675\nEventHandlerNonNull*61348/Te.xhr</<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:1562964\n61348/Te.xhr<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:1561653\nIe@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:1565645\nrequest@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:1569271\n61348/</Re.prototype[e]@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:1569565\n61348/i/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:1543515\nfetchDays@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2066436\nasync*_softRefreshInternal@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2061999\nsoftRefreshSync@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2061873\nrouteChange@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2060229\n$route@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2058653\nun@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:563869\n27507/e.prototype.run@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:568285\nns@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:570115\n27507/wn/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:564951\nfn@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:564350\npromise callback*pn@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:564440\nwn@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:565014\nss@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:570611\n27507/e.prototype.update@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:568074\n27507/e.prototype.notify@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:549442\nset@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:551286\nAp.prototype.init/</<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2236447\nAp.prototype.init/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2236426\nop.prototype.updateRoute@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2231344\nop.prototype.transitionTo/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2229199\nop.prototype.confirmTransition/</<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2231208\ns@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2227067\nep@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2227114\nop.prototype.confirmTransition/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2231111\ns@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2227067\nep/s/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2227096\nop.prototype.confirmTransition/v/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2230816\ntp/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2227684\nv@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2230451\ns@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2227076\ns@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2227105\nep@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2227114\nop.prototype.confirmTransition@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2230842\nop.prototype.transitionTo@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2229165\nt.prototype.replace@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2232381\nAp.prototype.replace/<@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2237089\nAp.prototype.replace@https://cloud.mydomain.nl/custom_apps/memories/js/memories-main.js?v=375f8707-5:2:2237052\nrefresh@https://cloud.mydomain.nl/custom_apps/memories/js/memories-components_top-matter_MapSplitMatter_vue.js?v=f155b32e2ada233f23ee:1:5326\ninitialize@https://cloud.mydomain.nl/custom_apps/memories/js/memories-components_top-matter_MapSplitMatter_vue.js?v=f155b32e2ada233f23ee:1:4874\n", message: "Request failed with status code 500", name: "AxiosError", code: "ERR_BAD_RESPONSE", config: {…}, request: XMLHttpRequest, response: {…} }
Timeline.vue:781
`
- Any errors in the Nextcloud server logs?
`{"reqId":"I0xZuF953iNnX2JvLEd2","level":3,"time":"2024-04-20T17:43:24+00:00","remoteAddr":"x.xxx.xxx.xxredacted for privacy","user":"--","app":"core","method":"GET","url":"/apps/memories/api/days/19829%2C19828%2C19827%2C19826","message":"Exception thrown: Doctrine\\DBAL\\Exception","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0","version":"28.0.4.1","exception":{"Exception":"Doctrine\\DBAL\\Exception","Message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused","Code":2002,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1654,"function":"connect","class":"OC\\DB\\Connection","type":"->","args":[]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1081,"function":"getWrappedConnection","class":"Doctrine\\DBAL\\Connection","type":"->","args":[]},{"file":"/var/www/html/lib/private/DB/Connection.php","line":261,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT * FROM `oc_appconfig`",[],[],null]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":337,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT * FROM `oc_appconfig`",[],[],null]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":377,"function":"executeQuery","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":280,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppConfig.php","line":421,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppConfig.php","line":187,"function":"loadConfigValues","class":"OC\\AppConfig","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppConfig.php","line":377,"function":"getApps","class":"OC\\AppConfig","type":"->","args":[]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":734,"function":"getValues","class":"OC\\AppConfig","type":"->","args":[false,"installed_version"]},{"file":"/var/www/html/lib/private/TemplateLayout.php","line":236,"function":"getAppVersions","class":"OC_App","type":"::","args":[]},{"file":"/var/www/html/lib/private/legacy/OC_Template.php","line":142,"function":"__construct","class":"OC\\TemplateLayout","type":"->","args":["error",""]},{"file":"/var/www/html/lib/private/Template/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"/var/www/html/lib/private/legacy/OC_Template.php","line":291,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"/var/www/html/index.php","line":104,"function":"printExceptionErrorPage","class":"OC_Template","type":"::","args":[["Doctrine\\DBAL\\Exception"],500]}],"File":"/var/www/html/lib/private/DB/Connection.php","Line":139,"CustomMessage":"Exception thrown: Doctrine\\DBAL\\Exception"},"id":"6623ffd0378aa"}`

and

`{"reqId":"BgjYRXIPOjjTJreOthEj","level":3,"time":"2024-04-20T17:43:24+00:00","remoteAddr":"x.xxx.xxx.xxredacted for privacy","user":"--","app":"index","method":"GET","url":"/apps/memories/api/days","message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0","version":"28.0.4.1","exception":{"Exception":"Doctrine\\DBAL\\Exception","Message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused","Code":2002,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1654,"function":"connect","class":"OC\\DB\\Connection","type":"->","args":[]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1081,"function":"getWrappedConnection","class":"Doctrine\\DBAL\\Connection","type":"->","args":[]},{"file":"/var/www/html/lib/private/DB/Connection.php","line":261,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT * FROM `oc_appconfig`",[],[],null]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":337,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT * FROM `oc_appconfig`",[],[],null]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":377,"function":"executeQuery","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":280,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppConfig.php","line":421,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppConfig.php","line":187,"function":"loadConfigValues","class":"OC\\AppConfig","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppConfig.php","line":377,"function":"getApps","class":"OC\\AppConfig","type":"->","args":[]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":128,"function":"getValues","class":"OC\\AppConfig","type":"->","args":[false,"enabled"]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":149,"function":"getInstalledAppsValues","class":"OC\\App\\AppManager","type":"->","args":[]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":231,"function":"getInstalledApps","class":"OC\\App\\AppManager","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":90,"function":"getEnabledApps","class":"OC_App","type":"::","args":[]},{"file":"/var/www/html/lib/base.php","line":700,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1200,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":37,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/DB/Connection.php","Line":139,"message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused","exception":[],"CustomMessage":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused"},"id":"6623ffd037965"}`

and

`{"reqId":"BgjYRXIPOjjTJreOthEj","level":3,"time":"2024-04-20T17:43:24+00:00","remoteAddr":"x.xxx.xxx.xxredacted for privacy","user":"--","app":"index","method":"GET","url":"/apps/memories/api/days","message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0","version":"28.0.4.1","exception":{"Exception":"Doctrine\\DBAL\\Exception","Message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused","Code":2002,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1654,"function":"connect","class":"OC\\DB\\Connection","type":"->","args":[]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1081,"function":"getWrappedConnection","class":"Doctrine\\DBAL\\Connection","type":"->","args":[]},{"file":"/var/www/html/lib/private/DB/Connection.php","line":261,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT * FROM `oc_appconfig`",[],[],null]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":337,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT * FROM `oc_appconfig`",[],[],null]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":377,"function":"executeQuery","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":280,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppConfig.php","line":421,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppConfig.php","line":187,"function":"loadConfigValues","class":"OC\\AppConfig","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppConfig.php","line":377,"function":"getApps","class":"OC\\AppConfig","type":"->","args":[]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":128,"function":"getValues","class":"OC\\AppConfig","type":"->","args":[false,"enabled"]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":149,"function":"getInstalledAppsValues","class":"OC\\App\\AppManager","type":"->","args":[]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":231,"function":"getInstalledApps","class":"OC\\App\\AppManager","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":90,"function":"getEnabledApps","class":"OC_App","type":"::","args":[]},{"file":"/var/www/html/lib/base.php","line":700,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1200,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/index.php","line":37,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/DB/Connection.php","Line":139,"message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused","exception":[],"CustomMessage":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused"},"id":"6623ffd037965"}`

**Comment by pulsejet** [comment]
Can you try restarting the server?

**Comment by Lumberj4cked** [comment]
I stopped the docker containers, restarted the host and started the containers again, sadly still get the same errors

**Comment by pulsejet** [comment]
Hmm these errors don't seem to be coming from memories definitely. It's even weirder that you'd get them only on mobile; mobile and desktop are running exactly the same thing.

**Comment by Lumberj4cked** [comment]
I get them on desktop too, only on other pages, like places and map and explore, not on folders (only sometimes)

I also don't think it's coming from memories but it is the only app that is affected, nextcloud itself doesn't give me any errors, so I was hoping you had some idea where it came from and if I screwed something up or if there was something I could check out.

**Comment by pulsejet** [comment]
I see some missing class error in the screenshot. Maybe you're missing some modules. How did you install nextcloud?

See https://github.com/nextcloud/server/issues/5043

**Comment by Lumberj4cked** [comment]
I installed it from docker, with the official docker image (not the AIO one from nextcloud)
I used to run it on another server but recently migrated it to a new vm, but it did work for about a day or two before it started with these errors so I'm not sure if that gave some problems. I did upgrade from nextcloud version 28.0.3 at the same time

**Comment by pulsejet** [comment]
None of these stand out. Something is causing the DB to refuse the connection, maybe something is logged on the DB side, or some max connection settings. Not sure.

**Comment by Lumberj4cked** [comment]
I will check that out, thank you! I'll do that later seeing as I'm not home at this moment

**Comment by Lumberj4cked** [comment]
I updated the mariadb container to a newer version and now it seems to be working stable again, I got the places back on mobile and the connection doesn't go away anymore

Seems that it was a DB issue like you said, thanks for the help! Closing the issue now
