### ISSUE TITLE
Deleting items in android app re-uploads the image/video as .trashed file.

### ISSUE THREAD

**Issue by carnager** [pulsejet/memories#1153]
**Describe the bug**
Allow memories access to local files.
When I delete an item in the android app, instead of moving the item to trash, it renames it in the same folder the original image was stored. It then reuploads the image into the original images folder with name .trashed-1714492983-ORIGINAL_FILENAME.jpg
Checking the files app on my nextcloud instance, I can see that the original images were properly moved into the Trash folder. 

**To Reproduce**
Delete an image in mobile app and say yes if it asks you for permissions to move images to trash.

**Platform:**
Android, GrapheneOS

- Memories Version: 7.2.0
- PHP Version: Not sure (Hosted instance on Hetzner)

**Comment by pulsejet** [comment]
Can confirm this is a bug in the Nextcloud Android app
https://github.com/nextcloud/android/issues/10645

**Comment by tuxArg** [comment]
Hi @pulsejet, I'm sorry to comment on this closed issue.
I don't think the android client would be fixed (and technically it isn't a bug as a hidden file is also a file). But, maybe there's a way to include a "skip trashbin" option when deleting local files in memories?

**Comment by pulsejet** [comment]
With the newest version of memories, these files will automatically be excluded from indexing, so they won't show up in Memories.

Skipping the trashbin might be a good idea, since they will be in trash on the server anyway. Don't know what the APIs look like though.

**Comment by tuxArg** [comment]
When these files are uploaded they aren't in trash on the server, they are just hidden (but its visibility can be toggled), so I don't think that excluding them from memories is the best approach because that would make harder for the user to find them and deleting them (considering that they already wanted to).

**Comment by pulsejet** [comment]
The assumption is that the android app would fix this issue, which is the right place to fix it. Hiding the files is a temporary solution. If the Android app decides not to fix this for whatever reason, an optional cron job can clean these up automatically once they're old enough.

**Comment by tuxArg** [comment]
I understand. I think it is a nextcloud client issue too. But I think (maybe I'm wrong here) memories client should use same criteria than nextcloud client. If the client uploaded .trashed-xxx.jpg as a regular file then memories client should display that file too.

I think the best way to deal with them is just excluding from local trash bin preventing them from being created, if that's possible.

**Comment by pulsejet** [comment]
Files starting with a dot are always hidden. This is a feature, not a bug.
