### ISSUE TITLE
Top right menu overlapping

### ISSUE THREAD

**Issue by sim6** [pulsejet/memories#1156]
**Describe the bug**
Unusable top right menu due to overlapping.

**To Reproduce**
Click a image from Memories Timeline

**Screenshots**
![ksnip_20240423-094521](https://github.com/pulsejet/memories/assets/449834/d1ab8dd4-e890-411e-8715-e68e55a7fe7a)

**Platform:**

- OS: Debian 12.5
- Browser: Firefox 115.9.1esr (64-bit)
- Memories Version: 7.2.0
- Nextcloud Version: 28.0.4
- PHP Version: 8.2.7

**Comment by pulsejet** [comment]
Duplicate of #1104
