### ISSUE TITLE
Search function returns no results

### ISSUE THREAD

**Issue by invario** [pulsejet/memories#1157]
**Describe the bug**
No matter what search string I input, the search results in Memories are always empty.  Maybe I am not understanding how to use it correctly, but I've tried searching for filenames, dates, folder names, etc. all with no results.

**To Reproduce**
Enter anything into the search field.

**Screenshots**
![image](https://github.com/pulsejet/memories/assets/67800603/74cd8427-f5e2-46cc-a109-597b2399a7c0)
**Platform:**

- OS: Windows 10 and Android clients.   Server is on TrueNAS Core 13 in a FreeBSD 13 jail.
- Browser: Windows Chrome and Android Chrome and Windows FireFox
- Memories Version: 7.2.0
- Nextcloud Version: 28.0.4
- PHP Version: 8.2.14

- Any errors in the JS console?
No.
- Any errors in the Nextcloud server logs?
No.

**Comment by pulsejet** [comment]
Currently you can only search for tags, albums, people and places.

**Comment by invario** [comment]
> Currently you can only search for tags, albums, people and places.

Ahhhh well that explains it, lol. Thank you!  Going to close.
