### ISSUE TITLE
Download Dropdown On Single Shared Images Requires Page Refresh to Function

### ISSUE THREAD

**Issue by ChildLearningClub** [pulsejet/memories#1158]
**Describe the bug**

On iOS Safari when opening a link for a individual shared photo the three dots download dropdown does not function. It requires a page refresh in order to then work and display the two options to "Download" and "Download Video"

**To Reproduce**

Create shared link with one image within Memories. Open link in iOS Safari. Attempt to download by tapping three dots, nothing happens. 

**Screenshots**

![IMG_1162](https://github.com/pulsejet/memories/assets/25701774/894ff816-3c5d-4ad7-b7aa-6a6829b268d6)

**Platform:**

- OS: iOS
- Browser: Safari
- Memories Version: 7.2.0
- Nextcloud Version: 29.0.0 but same result on 28.0.3
- PHP Version: 8.1

Update: Alternatively found that hitting the X and then tapping the image will then enable the button to work as well. And will play the live video which does not play on load, which I think is actually a browser feature if I'm not mistaken.

**Comment by pulsejet** [comment]
Does the menu not open at all, or the download buttons don't work?
This sounds like an upstream bug.

**Comment by ChildLearningClub** [comment]
Hi @pulsejet, the download buttons work but require a page refresh for them to appear. When you first load the page and press the three dots nothing happens. I apologize for the confusion.

**Comment by pulsejet** [comment]
@ChildLearningClub I can't test this reliably on iOS but could reproduce it on desktop, which seems fixed now. Pls validate with the next release and reopen if it's not fixed.

**Comment by ChildLearningClub** [comment]
Works in 7.3 Thanks!
