### ISSUE TITLE
tags not getting translated?!

### ISSUE THREAD

**Issue by steadfasterX** [pulsejet/memories#1160]
**Describe the bug**

My assumption is that the tags created by _recognize_ will be translated to my language (German) when using the app.
However, I only see the English tag names instead of German ones.

It works fine when using the web browser, here I can see them translated (while the URI still contains the English tag name which does not matter).

In Nextcloud the user language is set to German.
Not surprisingly the search itself within the app can find English tag names only.

Besides that the search _hint_ text is in English as well so seems to be not translated too (while the rest is translated just fine like Locations=Orte , Settings=Einstellungen, etc)

**To Reproduce**
Open the Memories app ;)

**Screenshots**

![image](https://github.com/pulsejet/memories/assets/8750713/495f2180-bd10-434b-a5e2-60fa32bc98f5)

**Platform:**

- OS: Android 13
- Browser: Brave
- Memories Version: 1.10 installed via F-Droid
- Nextcloud Version: 28.0.4
- PHP Version: 8.1

**Comment by pulsejet** [comment]
Hmm I set my language to German and the tags are translated for me. The search bar text is probably just not translated yet.

What version of recognize are you on?

**Comment by steadfasterX** [comment]
hm...  on the same Memories version? 
Recognize says v6.1.1

**Comment by pulsejet** [comment]
Well not exactly, I'm on master and recognize v7. But nothing has changed here really since the last version; still maybe wait till the next one. Also I noticed you do need face recognition enabled in recognize for translations to work (kinda bug)

**Comment by steadfasterX** [comment]
wait I disabled face recognition ! is that the reason?

**Comment by pulsejet** [comment]
Could be. Try turning it on for a test. Marking this for the next version.
