### ISSUE TITLE
No versions compatible with device on F-Droid for tablet

### ISSUE THREAD

**Issue by tetebueno** [pulsejet/memories#1163]
**Is your feature request related to a problem? Please describe.**
When trying to install Memories through F-Droid I get the "No versiones compatible with device" message.

**Describe the solution you'd like**
To have compatible version forma this device on F-Droid.

**Describe alternatives you've considered**
In the meantime, I've "installed" Nextcloud web app through Chrome to access as any other app.

**Additional context**
I'm currently trying on a Nexus 9 (Android 7.1.2).

**Comment by pulsejet** [comment]
> Android 7.1.2

Minimum SDK is 27, so we don't support anything older than Android 8.1

**Comment by tetebueno** [comment]
Bummer. But understandable, tablet is quite old.

Thanks forma tour time anyway.
