### ISSUE TITLE
no gif previews

### ISSUE THREAD

**Issue by kinghat** [pulsejet/memories#1165]
**Describe the bug**
not sure if this falls into feature request or bug but gif previews are not shown.

**To Reproduce**
for me i have a few gifs created by the google photos app. i think it was by editing a movie photo and saving as gif. i dont fully remember though. these were then transferred over to nextcloud when i made the jump.

**Screenshots**
the gif and its originating movie photo in files:

![image](https://github.com/pulsejet/memories/assets/16073360/f9b01ad2-c175-4eb0-96dc-56d8504a9ef6)

both of them in memories with the gif preview missing:

![image](https://github.com/pulsejet/memories/assets/16073360/a6855511-3295-4d5f-87a7-76535c305137)

the gif item expanded and plays the gif fine:

![image](https://github.com/pulsejet/memories/assets/16073360/6124aaa0-48f9-4071-8ac9-d7721952d441)

**Platform:**

- OS: fedora 40 kde
- Browser: firefox 125.0.3
- Memories Version: 7.2.0
- Nextcloud Version: Nextcloud Hub 8 29.0.0
- PHP Version: 8.3.6

**Additional context**

> XHRGET
> https://nc.example.com/apps/memories/api/image/preview/24027?c=(not-sure-if-sensitive)&x=340&y=340&a=1
> [HTTP/2 500  122ms]

> Failed to load XImg Error fetching single preview: {"message":"No provider successfully handled the preview generation"} XImg.vue:95
>     loadImage XImg.vue:95
>     mounted XImg.vue:50
>     VueJS 18
>     updateVisibleItems vue-virtual-scroller.esm.js:494
>     e vue-virtual-scroller.esm.js:275
>     (Async: FrameRequestCallback)
>     e vue-virtual-scroller.esm.js:271
>     _updateTimeout vue-virtual-scroller.esm.js:291
>     (Async: setTimeout handler)
>     handleScroll vue-virtual-scroller.esm.js:289
>     scroll vue-virtual-scroller.esm.js:746
>     VueJS 3

**Comment by pulsejet** [comment]
What do your memories file support settings look like? Does it have GIF listed?

![image](https://github.com/pulsejet/memories/assets/10709794/6c55efab-9f8c-4539-97d5-d967cafcc7e2)

**Comment by kinghat** [comment]
> What do your memories file support settings look like? Does it have GIF listed?
> 
> ![image](https://private-user-images.githubusercontent.com/10709794/326940874-6c55efab-9f8c-4539-97d5-d967cafcc7e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MDI1MjksIm5iZiI6MTcxNDUwMjIyOSwicGF0aCI6Ii8xMDcwOTc5NC8zMjY5NDA4NzQtNmM1NWVmYWItOWY4Yy00NTM5LTk3ZDUtZDk2N2NhZmNjN2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE4MzcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkYjg1ODQyYzUxNTQzYTExNDA2Yzk3OTVmNTBiZjMwODZlYjJkNDIwNzA2MTgyZjNmN2ZlYzMyNGY2YmQ5YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7tcHRNu4C_80hD00gKFf0_Ia2yamcS-w43-PYatcg7g)

damn im sorry i dont remember that being deselected. how was it generating the common ones not being selected?

![image](https://github.com/pulsejet/memories/assets/16073360/65e2e8da-3ee4-432e-8f76-7629fbfdc79e)

**Comment by pulsejet** [comment]
Might be some other provider. Do you have e.g. imaginary enabled? Strange that it does show image/gif and doesn't work

**Comment by kinghat** [comment]
> Might be some other provider. Do you have e.g. imaginary enabled? Strange that it does show image/gif and doesn't work

yep i have imaginary and is enabled.

**Comment by pulsejet** [comment]
Try removing that from the providers in config.php and enable the images provider above.

**Comment by kinghat** [comment]
> Try removing that from the providers in config.php and enable the images provider above.

what happens to other stuffs in nextcloud if i remove it?

i have enabled the images provider above and i see the gif preview in memories now. the preview is not animated:

![image](https://github.com/pulsejet/memories/assets/16073360/efd9a828-489a-47cf-a1bb-c809923a1d5d)

**Comment by pulsejet** [comment]
> the preview is not animated

Yes, that is intentional.

> what happens to other stuffs in nextcloud if i remove it?

Not much actually. I don't recommend Imaginary in general; it's got other weird bugs e.g. HEIC being wrongly oriented.
