### ISSUE TITLE
Folders with shared folders can be incorrectly hidden

### ISSUE THREAD

**Issue by pulsejet** [pulsejet/memories#1166]
If the outer folder does not have any files, inner shares may not be used for preview listing.

**Comment by pulsejet** [comment]
Fixed with https://github.com/pulsejet/memories/commit/ef2a520a69220ebaac5a5cf42b3b6b3d2f22dd59

**Comment by hahagu** [comment]
@pulsejet 
This issue seems to be back on version 7.4.1

**Comment by pulsejet** [comment]
@hahagu Can't repro, are you sure you're talking about this same issue? The description isn't really clear here.

**Comment by hahagu** [comment]
> @hahagu Can't repro, are you sure you're talking about this same issue? The description isn't really clear here.

Hey, sorry - just checked again.
Seemed to be a configuration error on my nextcloud instance.
Sorry to bother!
