### ISSUE TITLE
"Invalid type for system config preview_max_x, expected integer, got string"

### ISSUE THREAD

**Issue by Sabering1** [pulsejet/memories#1170]
-->

**Describe the bug**
"Invalid type for system config preview_max_x, expected integer, got string" error shows when going to memories in the admin panel

**To Reproduce**
update to latest version

**Screenshots**
![image](https://github.com/pulsejet/memories/assets/39810634/a9d693fe-a3ed-4be5-b9af-745d955dce3e)

**Platform:**

- OS: Linux Debian installed Nextcloud Docker AIO
- Browser: librewolf fork of firefox
- Memories Version: latest
- Nextcloud Version: latest stable
- PHP Version: AIO defaut 

**Additional context**
no

- Any errors in the JS console? no
- Any errors in the Nextcloud server logs? no

**Comment by pulsejet** [comment]
Duplicate of #1168

**Comment by marcello-dev** [comment]
@pulsejet what is the fix for this issue? Why is it set as completed?

**Comment by pulsejet** [comment]
See the linked issue

**Comment by Sabering1** [comment]
fixed after updating to latest
