### ISSUE TITLE
Post 7.3 upgrade Media Index issue - "Last index job was run XXXX seconds ago. It is still running or was interrupted."

### ISSUE THREAD

**Issue by Kybeer** [pulsejet/memories#1171]
**Describe the bug**
After upgrading to 7.3 I have this error in the Administration Settings for Memories:

```
Last index job was run 4147 seconds ago. It is still running or was interrupted.
```

There's no issues with the "normal" cron background job - see screenshots below

Restarting server / services doesn't help. I have never seen this issue before in my setup. 

**To Reproduce**
Happens all the time now after upgrading to 7.3.

**Screenshots**

![image](https://github.com/pulsejet/memories/assets/57593336/a069bd61-968c-4533-953e-17d6fcb6fb7e)

![image](https://github.com/pulsejet/memories/assets/57593336/07f6ef7e-38fa-4099-92a6-967f1aee11e8)

**Platform:**

- OS: Official Nextcloud container running in Podman on RHEL8
- Browser: Firefox
- Memories Version: 7.3
- Nextcloud Version: 28.0.5
- PHP Version: 8.2.18

**Comment by pulsejet** [comment]
1. Can you try running `occ memories:index`
2. Anything in logs?

**Comment by Kybeer** [comment]
> 1. Can you try running `occ memories:index`
> 
>     2. Anything in logs?

After I ran the new index it looks good:

`"Last index job was run 484 seconds ago. It took 22.63 seconds to complete."`

The log just looks like this:
![image](https://github.com/pulsejet/memories/assets/57593336/3bc42bc8-4b1f-4e2e-967d-85903af262e8)

**Comment by pulsejet** [comment]
Looks like the error resolved itself then

**Comment by Kybeer** [comment]
> Looks like the error resolved itself then

Yep let's close this :) Thanks a lot!
