### ISSUE TITLE
Failed to update setting

### ISSUE THREAD

**Issue by CaptainJawZ** [pulsejet/memories#1173]
**Describe the bug**
Recently (well not so recently) I migrated my nextcloud instance from one computer to another (not sure if it's relevant but I mention it in case) overall, it was a pretty seamless process. I have Nextcloud installed as a module from NixOS so it was just a matter of copying my data folders.

However tonight when trying to adjust my settings on the memories app, I noticed that, while the app seems to be working and tagging pictures, this window is completely broken:
![image](https://github.com/pulsejet/memories/assets/43111068/263ac625-79fb-41c8-bba9-f8afe88fc519)

Any setting I change (tried changing all of them) I am met with the error: "Failed to update setting"

I've tried all the steps on the troubleshoot guide (except deleting all the entries from the database, because I am scared of losing my albums, I have a lot of albums, whose grouping I'd hate to lose :(.

Is there anything I can do to fix this? my suspicion is that... because there were some Nvidia related settings at the bottom, and my new computer does not have nvidia, maybe that's messing up with the window, but that's just an assumption, no amount of reinstalling and thinkering with occ has helped.

**To Reproduce**

**Screenshots**

**Platform:**

- OS: NixOS
- Browser: Firefox
- Memories Version: 7.3.0
- Nextcloud Version: 28.0.4
- PHP Version: 8.2

**Additional context**

- Any errors in the JS console?
I get the following on the JS console:
`Request failed with status code 500", name: "AxiosError", code: "ERR_BAD_RESPONSE", config: {…}, request: XMLHttpRequest, response`
- Any errors in the Nextcloud server logs?

**Comment by pulsejet** [comment]
> Any errors in the Nextcloud server logs?

This

**Comment by CaptainJawZ** [comment]
> > Any errors in the Nextcloud server logs?
> 
> This

file_get_contents(/nix/store/rm37d99k5jq728g61nvv158cak5hqnqd-nextcloud-28.0.4-with-apps/store-apps/memories/appinfo/signature.json): Failed to open stream: No such file or directory at /nix/store/3yvdxk2wjwh32cisxxn82h2xzzzss39g-nextcloud-28.0.4/lib/private/IntegrityCheck/Helpers/FileAccessHelper.php#44

Transcode failed: failed to connect to go-vod: cURL error 28: Connection timed out after 1001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:47788/config%2Fconfig/config 

(this one is a bit old, hasnt appeared since last week)
 Error Call to undefined method Rubix\ML\Datasets\Labeled::features()
Error while running background job (class: OCA\Recognize\BackgroundJobs\ClusterFacesJob, arguments: Array ( [userId] => JawZ ) )

**Comment by pulsejet** [comment]
Please try v7.3.1

I don't expect this to fix the issue but it should hopefully fix the above error (and possibly show the actual error that's happening in the logs_

**Comment by CaptainJawZ** [comment]
I did update to hat version two days ago, I've been checking the logs expecting any new logs from memories, but nothing has surfaced.

The Javascript error I get is the same one.

I tried using occ-commands to run memory related tasks, see if I can trigger a log, but nothing.

**Comment by pulsejet** [comment]
Okay try getting more info from the js console error. Expand the "response" field, which might have something like "data"

**Comment by CaptainJawZ** [comment]
{
  "stack": "U@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:957438\n61348/xe.xhr</</v/<@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:971333\nv@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:971478\nEventHandlerNonNull*61348/xe.xhr</<@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:971767\n61348/xe.xhr<@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:970456\nLe@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:974448\n_request@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:978379\nrequest@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:976921\n61348/</t/<@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:978826\n61348/o/<@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:952291\nupdate@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:1044040\ncn@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:242072\nn@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:234865\ncn@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:242072\n27507/e.prototype.$emit@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:263942\nupdate@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:1005421\ntt</<.on[\"update:checked\"]<@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:1009710\ncn@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:242072\nn@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:234944\ncn@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:242072\n27507/e.prototype.$emit@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:263942\nonToggle@https://cloud.servidos.lat/store-apps/memories/js/memories-vendors-node_modules_nextcloud_vue_dist_chunks_NcCheckboxRadioSwitch-BOl1O2zi_mjs.js?v=4dbd3300b2b54883b6b0:1:29040\nclick@https://cloud.servidos.lat/store-apps/memories/js/memories-vendors-node_modules_nextcloud_vue_dist_chunks_NcCheckboxRadioSwitch-BOl1O2zi_mjs.js?v=4dbd3300b2b54883b6b0:1:31001\ncn@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:242072\nn@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:234865\n27507/Ro/s._wrapper@https://cloud.servidos.lat/store-apps/memories/js/memories-admin.js?v=d0449e4e-7:2:274987\n",
  "message": "Request failed with status code 500",
  "name": "AxiosError",
  "code": "ERR_BAD_RESPONSE",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "adapter": [
      "xhr",
      "http"
    ],
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json",
      "requesttoken": "hxJluCRyiB8AyTMSJ6aTrQzWFavKbkryeMgpggVdZR4=:z2cIzmA90F1qhgMrdpL1z2ruQtK+GS/KF7tb8TElKm0="
    },
    "method": "put",
    "url": "/apps/memories/api/system-config/memories.exiftool_no_local",
    "data": "{\"value\":true}"
  },
  "request": {},
  "response": {
    "data": {
      "message": "Invalid system config key: memories.readonly"
    },
    "status": 500,
    "statusText": "",
    "headers": {
      "alt-svc": "h3=\":443\"; ma=86400",
      "cache-control": "no-cache, no-store, must-revalidate",
      "cf-cache-status": "DYNAMIC",
      "cf-ray": "87f2a3234c3e7cf7-LAX",
      "content-length": "58",
      "content-security-policy": "default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'",
      "content-type": "application/json; charset=utf-8",
      "date": "Sun, 05 May 2024 18:01:41 GMT",
      "expires": "Thu, 19 Nov 1981 08:52:00 GMT",
      "feature-policy": "autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'",
      "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}",
      "pragma": "no-cache",
      "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=ohuhlgS11GWCQ8c5fMsMCoKYd5FYwy%2FFm3eFjcnWMVXSnlt8mxDEgfb%2Ff%2BSQgPXitJqa60NRQvhlbyoxlgnyhu8z1ROeoKipBPOVas67HMPmbr8HjPiH1y%2Bekx80BWnwm336oR4ntYt38Bw9EQZlcHE%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
      "server": "cloudflare",
      "strict-transport-security": "max-age=15552000; includeSubDomains",
      "x-firefox-http3": "h3",
      "x-request-id": "x4jNw7aXGnbVpPLuImyx",
      "x-robots-tag": "noindex, nofollow"
    },
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "adapter": [
        "xhr",
        "http"
      ],
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {},
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json",
        "requesttoken": "hxJluCRyiB8AyTMSJ6aTrQzWFavKbkryeMgpggVdZR4=:z2cIzmA90F1qhgMrdpL1z2ruQtK+GS/KF7tb8TElKm0="
      },
      "method": "put",
      "url": "/apps/memories/api/system-config/memories.exiftool_no_local",
      "data": "{\"value\":true}"
    },
    "request": {}
  }
}

does this help?

**Comment by pulsejet** [comment]
Ah this is a bug. You can work around it by temporarily removing `memories.readonly` from your config.

**Comment by pulsejet** [comment]
Something strange is happening here
1. Try a restart of the PHP server
2. Try comment out this check https://github.com/pulsejet/memories/blob/01eb88939978cdcb0a7f74138005421b7afa18e4/lib/Controller/AdminController.php#L61-L63

**Comment by CaptainJawZ** [comment]
just a restart of the php server did the trick, I got no idea why memories was on readonly mode but for now I can update settings and was able to remove the nvidia related settings, thank you very much, sorry the issue was... your average turn it off and on again... heh

**Comment by pulsejet** [comment]
Probably the opcache had something bad
