### ISSUE TITLE
Unable to load admin settings page

### ISSUE THREAD

**Issue by r100gs** [pulsejet/memories#1174]
**Describe the bug**
Unable to load admin settings page with following error message:

"Invalid type for system config preview_max_x, expected integer, got string"

**To Reproduce**
Try to open memories settings with admin account

**Screenshots**

![image](https://github.com/pulsejet/memories/assets/12609988/63981fa0-c13e-4a5e-8e09-24e3c3cc7056)

**Platform:**

- OS: W10
- Browser: Chrome
- Memories Version: 7.3.0
- Nextcloud Version: 25.0.8.1 AIOS
- PHP Version: latest NC AIOS

**Additional context**

- JS logs: Don´t know how to get there

- Any errors in the Nextcloud server logs?
  No

**Comment by marcello-dev** [comment]
Completed? Where is the fix?

**Comment by eibex** [comment]
> Completed? Where is the fix?

https://github.com/pulsejet/memories/issues/1168#issuecomment-2087945300
