### ISSUE TITLE
ERROR creating TRIGGER PostgreSQL version < 14

### ISSUE THREAD

**Issue by manuelfloresv** [pulsejet/memories#1179]
When executing Trigger compatibility mode, running `occ maintenance repair ` gives error when creating the trigger

```
occ  maintenance:repair
     - WARNING: Failed to create filecache trigger (compatibility mode will be used): An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "TRIGGER"
LINE 1: CREATE OR REPLACE TRIGGER memories_fcu_trg

```

Postgresql Logs
```
 nextcloud@nextcloud ERROR:  syntax error at or near "TRIGGER" at character 19
 nextcloud@nextcloud STATEMENT:  CREATE OR REPLACE TRIGGER memories_fcu_trg
	                    AFTER UPDATE ON oc_filecache
	                    FOR EACH ROW
	                    EXECUTE FUNCTION memories_fcu_fun();
```
This line does not account for older version of postgresql that does not support the syntax `CREATE OR REPLACE TRIGGER` but only `CREATE TRIGGER`:
https://github.com/pulsejet/memories/blob/01eb88939978cdcb0a7f74138005421b7afa18e4/lib/Db/AddMissingIndices.php#L121

https://memories.gallery/troubleshooting/#trigger-compatibility-mode

Software Versions
- Nextcloud Hub 7 (28.0.3)
- PHP: 8.1.27
- PostgreSQL: 13.14
-  Memories: 7.2.0

**Comment by pulsejet** [comment]
Yep https://github.com/pulsejet/memories/issues/1106
