### ISSUE TITLE
Some users can't add photos to albums

### ISSUE THREAD

**Issue by thegrasshopper104** [pulsejet/memories#1180]
**Describe the bug**
XYZ gets a lot of errors "Failed to add filename..."  when trying to add a photo to an album. I (admin user but not "admin") can add photos to albums just fine. The photos have been uploaded to a shared folder on my user and shared with a group that includes XYZ.

**To Reproduce**
Select photos
Click add to album
Create or choose an album

**Platform:**

- Memories Version: 7.2.0
- Nextcloud Version: 28.0.4 AIO

I didn't see any relevant errors in logs.

**Comment by pulsejet** [comment]
Yes, you can't add to album from shared folders

Duplicate of https://github.com/pulsejet/memories/issues/669

**Comment by thegrasshopper104** [comment]
That's kinda a big limitation then.
I swear I searched for duplicates though...
