### ISSUE TITLE
Possibility to to sort shared media

### ISSUE THREAD

**Issue by Alex1183** [pulsejet/memories#1181]
**Is your feature request related to a problem?**
There is no possibility to sort the shared media by Exif date/time downwards or upwards.
Furthermore, the media are sorted upwards in shared albums and downwards in shared folders.

**Describe the solution you'd like**
1. Change the sorting direction of media in shared folders upwards by Exif date/time like as with albums.
OR
2. Possibility to choose the sorting direction on creating the share link.
OR
3. Add sort button on the UI with the shared media.

Many thanks for your work. I really like the app.

**Comment by nkinkade** [comment]
Agreed. It would be great if it were possible to select the sort order for photos in shared albums. Today, it appears that shared albums sort chronologically ascending, which feels unnatural, at least as the default with no option to change it. On the other hand, when viewing an album in the Memories app in Nextcloud the photos are sorted chronologically descending (also with no option to change it), which is, I think, the correct and expected default. In my view, the default should be sort chronologically descending, and an option to change it for other uses cases could be nice.

I am in the process of migrating many years worth of photos from Piwigo to Memories, and Memories is great! Thank you for creating and maintaining it!

**Comment by onighost** [comment]
+1 This is literally the only reason stopping me using Memories over the Nextcloud Photos app. I have a shared album with my family for baby photos, having the default being chronologically ascending means if I want to see what the latest photos my wife has shared I have to scroll through hundreds of pictures to get to it.

**Comment by pulsejet** [comment]
Btw you can add `?sort=timeline` to the link to make it descending.

**Comment by pulsejet** [comment]
If you're logged in then there's a user-specific setting. The default is just a matter of preference; more people want chronological albums (like a real album), so that's what the default is.

**Comment by nkinkade** [comment]
Agreed that sort order is completely a preference and/or use-case consideration. I now see the album sort order option, and I believe I had seen it before as well, so my original comment about it not being configurable even when logged into Nextcloud was completely wrong. My main concern, and I think the concern of the OP, was how shared albums are sorted. Having a setting for that would be useful, but the `?sort=timeline` query string you pointed out to me resolved the concern for my use case.

Thanks for engaging and for all the time and effort you have put into the amazing Nextcloud app, as well as the mobile app!

**Comment by nkinkade** [comment]
Oh, and I'll leave it to the original creator of this issue or yourself, but from my perspective this issue can probably be closed.

**Comment by Alex1183** [comment]
Thank you!
