### ISSUE TITLE
Failed to create filecache trigger (compatibility mode will be used)

### ISSUE THREAD

**Issue by Markoise** [pulsejet/memories#1182]
**Describe the bug**
 - Repair steps for Memories
     - External table schema seem up to date
     - **WARNING: Failed to create filecache trigger (compatibility mode will be used): An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1419 You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)**
     - exiftool binary is configured: /var/www/nextcloud/apps/memories/bin-ext/exiftool-aarch64-glibc
     - go-vod binary is configured: /var/www/nextcloud/apps/memories/bin-ext/go-vod-aarch64
     - ffmpeg binary is configured: /usr/bin/ffmpeg

**To Reproduce**

This error comes when running "occ maintenance:repair"

**Screenshots**

<img width="264" alt="image" src="https://github.com/pulsejet/memories/assets/64073726/3f8507e5-bc91-48b4-bf5d-af88f873819c">

**Platform:**

- OS: Windows 11 / Android 14
- Browser: Brave, Chrome, Firefox
- Memories Version: 7.3.1
- Nextcloud Version: 29.0.0
- PHP Version: 8.2

**Comment by pulsejet** [comment]
Did you see the docs linked in the admin page?

**Comment by xxLexanixx** [comment]
I have the same problem. The solution on the admin page didn't help

**Comment by apsilva** [comment]
Hi,

i just hit this issue and when running repair i got:

```
- Repair steps for Memories
     - External table schema seem up to date
     - WARNING: Failed to create filecache trigger (compatibility mode will be used): An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1142 TRIGGER command denied to user 'nextcloud'@'localhost' for table `nextcloud`.`oc_filecache`

```
I didn't have the trigger granted for the nextcloud user, just grant the trigger to the user solve the issue:

`GRANT TRIGGER ON nextcloud.* TO 'nextcloud'@'localhost';`
