### ISSUE TITLE
Curious case of three large video files being dated differently from their metadata

### ISSUE THREAD

**Issue by invario** [pulsejet/memories#1195]
**Describe the bug**
I recorded (3) large HEVC HDR10+ videos via my Samsung GS23+ today.  Two of the files were completely untouched.  One of the files I trimmed 16 seconds from the front end using my GS23+ included Gallery video editor.  All three files were then synced/upped via Foldersync to my NC instance which then showed up in Memories out of order from when the video was created. 

Using the package exiftool in the bin-ext folder, I pulled the time tags:
`perl exiftool -api largefilesupport=1 -time:all 20240516_*.mp4`

```
20240516_165405.mp4 - First video that was recorded and subsequently trimmed with my video editor.

File Modification Date/Time     : 2024:05:16 18:05:28-04:00
File Access Date/Time           : 2024:05:17 09:30:07-04:00
File Inode Change Date/Time     : 2024:05:16 23:31:18-04:00
Create Date                     : 2024:05:16 20:58:58
Modify Date                     : 2024:05:16 20:58:58
Track Create Date               : 2024:05:16 22:05:27
Track Modify Date               : 2024:05:16 22:05:27
Media Create Date               : 2024:05:16 22:05:27
Media Modify Date               : 2024:05:16 22:05:27
```

```
20240516_170511.mp4 - untouched.  Second video recorded:

File Modification Date/Time     : 2024:05:16 17:07:42-04:00
File Access Date/Time           : 2024:05:17 09:30:17-04:00
File Inode Change Date/Time     : 2024:05:16 23:33:04-04:00
Create Date                     : 2024:05:16 21:07:42
Modify Date                     : 2024:05:16 21:07:42
Track Create Date               : 2024:05:16 21:07:42
Track Modify Date               : 2024:05:16 21:07:42
Media Create Date               : 2024:05:16 21:07:42
Media Modify Date               : 2024:05:16 21:07:42
```

```
20240516_172115.mp4 - untouched. Third video recorded:

File Modification Date/Time     : 2024:05:16 17:25:47-04:00
File Access Date/Time           : 2024:05:17 09:30:08-04:00
File Inode Change Date/Time     : 2024:05:16 23:36:32-04:00
Create Date                     : 2024:05:16 21:25:46
Modify Date                     : 2024:05:16 21:25:46
Track Create Date               : 2024:05:16 21:25:47
Track Modify Date               : 2024:05:16 21:25:47
Media Create Date               : 2024:05:16 21:25:47
Media Modify Date               : 2024:05:16 21:25:47
```

In Memories, the videos are being shown out of chronological order per this screenshot.
![image](https://github.com/pulsejet/memories/assets/67800603/3ada2345-ff47-4c40-a925-718e1745abb2)

- It makes sense that 165405 is the newest video per the Track Create Date, due to my trimming the video. However, when I view the Info for this video, it shows this:

![image](https://github.com/pulsejet/memories/assets/67800603/e6cd203b-af0b-428a-99f1-31354f6f3390)
Note it says 10:05PM and that is most certainly not when I trimmed the video. It appears the timezone is not being factored in as I believe I trimmed the video at approximately 6:05PM local. (-4 hours)

- 170511 (original, untouched) shows this correctly as 5:07PM

![image](https://github.com/pulsejet/memories/assets/67800603/d3a6e3d9-7857-4d5e-9c2f-fc093ddf1868)

- But oddly, 172115, which is also the original and untouched shows this incorrectly as 9:25PM when it should be 7:25PM (timezone?)

![image](https://github.com/pulsejet/memories/assets/67800603/fe2d3055-baae-42c7-9182-10124008f8f4)

**To Reproduce**
Record videos on my phone. Uploaded to NC. Browse collection in Memories.

**Platform:**

- OS: TrueNAS Core 13 in FreeBSD 13.2-RELEASE-p11 jail
- Browser: Chrome Android and Windows
- Memories Version: 7.3.1
- Nextcloud Version: Nextcloud Hub 8 (29.0.0)
- PHP Version: 8.2.14

**Additional context**
The files are rather large, FYI.

```
-rw-r--r--  1 www  www  2539766902 May 16 18:05 20240516_165405.mp4
-rw-r--r--  1 www  www  1410936134 May 16 17:07 20240516_170511.mp4
-rw-r--r--  1 www  www  2530825413 May 16 17:25 20240516_172115.mp4

```

- Any errors in the JS console?
No.

- Any errors in the Nextcloud server logs?
No.

**Comment by pulsejet** [comment]
1. Video files usually don't store the timezone. If only a timestamp (e.g. modified time) is present, the server's timezone is used. You might need to set the `TZ` environment variable if running in docker (i.e. your host settings may not be used)
2. `CreateDate` always takes precedence. I'm actually not sure why `170511` shows the correct date. The only possible explanation is that this video has the timezone embedded while the other doesn't (the other place from where the timezone is extracted is the geolocation, but neither video has a tag). Something does seem different in the two files since exiftool could extract the dimensions from one but not the other.

**Comment by pulsejet** [comment]
I just realised large file support isn't enabled by Memories. This could be the reason why it doesn't work for the bigger file.

**Comment by invario** [comment]
> 1. Video files usually don't store the timezone. If only a timestamp (e.g. modified time) is present, the server's timezone is used. You might need to set the `TZ` environment variable if running in docker (i.e. your host settings may not be used)
I'm in a FreeBSD iocage jail, no docker here.

> 2. `CreateDate` always takes precedence. I'm actually not sure why `170511` shows the correct date. The only possible explanation is that this video has the timezone embedded while the other doesn't (the other place from where the timezone is extracted is the geolocation, but neither video has a tag). Something does seem different in the two files since exiftool could extract the dimensions from one but not the other.
Noted. Yeah, I disable geotags on my phone too.

> I just realised large file support isn't enabled by Memories. This could be the reason why it doesn't work for the bigger file.
Indeed, this might be it!  I reran my commands.   So for comparison, here is the output with largefilesupport:

```
# perl ./exiftool -api largefilesupport=1 -time:all /folder/20240516_*.mp4
======== /folder/20240516_165405.mp4
File Modification Date/Time     : 2024:05:16 18:05:28-04:00
File Access Date/Time           : 2024:05:17 16:25:20-04:00
File Inode Change Date/Time     : 2024:05:16 23:31:18-04:00
Create Date                     : 2024:05:16 20:58:58
Modify Date                     : 2024:05:16 20:58:58
Track Create Date               : 2024:05:16 22:05:27
Track Modify Date               : 2024:05:16 22:05:27
Media Create Date               : 2024:05:16 22:05:27
Media Modify Date               : 2024:05:16 22:05:27
======== /folder/20240516_170511.mp4
File Modification Date/Time     : 2024:05:16 17:07:42-04:00
File Access Date/Time           : 2024:05:17 16:25:20-04:00
File Inode Change Date/Time     : 2024:05:16 23:33:04-04:00
Create Date                     : 2024:05:16 21:07:42
Modify Date                     : 2024:05:16 21:07:42
Track Create Date               : 2024:05:16 21:07:42
Track Modify Date               : 2024:05:16 21:07:42
Media Create Date               : 2024:05:16 21:07:42
Media Modify Date               : 2024:05:16 21:07:42
======== /folder/20240516_172115.mp4
File Modification Date/Time     : 2024:05:16 17:25:47-04:00
File Access Date/Time           : 2024:05:17 16:25:20-04:00
File Inode Change Date/Time     : 2024:05:16 23:36:32-04:00
Create Date                     : 2024:05:16 21:25:46
Modify Date                     : 2024:05:16 21:25:46
Track Create Date               : 2024:05:16 21:25:47
Track Modify Date               : 2024:05:16 21:25:47
Media Create Date               : 2024:05:16 21:25:47
Media Modify Date               : 2024:05:16 21:25:47
    3 image files read
```


And here it is without largefilesupport:

```
# perl ./exiftool -time:all /folder/20240516_*.mp4
======== /folder/20240516_165405.mp4
File Modification Date/Time     : 2024:05:16 18:05:28-04:00
File Access Date/Time           : 2024:05:17 16:25:31-04:00
File Inode Change Date/Time     : 2024:05:16 23:31:18-04:00
======== /folder/20240516_170511.mp4
File Modification Date/Time     : 2024:05:16 17:07:42-04:00
File Access Date/Time           : 2024:05:17 16:25:31-04:00
File Inode Change Date/Time     : 2024:05:16 23:33:04-04:00
Create Date                     : 2024:05:16 21:07:42
Modify Date                     : 2024:05:16 21:07:42
Track Create Date               : 2024:05:16 21:07:42
Track Modify Date               : 2024:05:16 21:07:42
Media Create Date               : 2024:05:16 21:07:42
Media Modify Date               : 2024:05:16 21:07:42
======== /folder/20240516_172115.mp4
File Modification Date/Time     : 2024:05:16 17:25:47-04:00
File Access Date/Time           : 2024:05:17 16:25:31-04:00
File Inode Change Date/Time     : 2024:05:16 23:36:32-04:00
    3 image files read
```

This makes sense now looking at the tags extracted with and without the flag, and makes sense being that 2 of the files are 2GB and one file (the one being processed correctly) is under 2GB, which is the limit without largefilesupport being enabled.

**Comment by invario** [comment]
RESOLVED by implementing your fix and forcing a reindex of the folder:

![image](https://github.com/pulsejet/memories/assets/67800603/facb5b07-8873-4f4e-83f4-86ad344cee14)
![image](https://github.com/pulsejet/memories/assets/67800603/b1cc44fa-0048-4a61-9ec5-4f63b3ca481c)
![image](https://github.com/pulsejet/memories/assets/67800603/c4d784d0-925f-49c3-a96f-56cc8edfde75)
![image](https://github.com/pulsejet/memories/assets/67800603/cdf91dcc-5a08-41d5-9620-0bb7cf278f84)


Thank you!

**Comment by pulsejet** [comment]
Fantastic! Thanks for the quick test.
