### ISSUE TITLE
Grouping Albums

### ISSUE THREAD

**Issue by rightsaidfred99** [pulsejet/memories#1196]
**Is your feature request related to a problem? Please describe.**
I use Nextcloud to issue images to clients. The default functionality with Nextcloud is ok but not image centric. 
However looking at memories, it'd be nice to be able to group/organise albums. 

2024 / Project / Album Name
Or 2024 / Album Name

Currently if one were to use it (like in the demo) there is just a wall of albums making it difficult to organise long term

**Describe the solution you'd like**

Just being able to group albums

**Comment by pulsejet** [comment]
Subset of #523
