### ISSUE TITLE
Memories - Recognize: Metadata information not shared among multiple users

### ISSUE THREAD

**Issue by emaurice** [pulsejet/memories#1199]
I am running NextCloud 29.0.1 w/ memories and recognize.
My pictures are located on an local folder, outside of web root. I have enabled external storage to access the local machine directory with all my pictures.
Recognize is running and grouping pictures as expected for the admin of the NextCloud site (my account). I have renamed individuals with humane names (as opposed to individual #XXXX).

However, other users, while they can see Memories, the pictures, the timeline, etc. do not see the grouping of the individuals by memories. In other words, when going to individuals, they see grouped individuals without names.  Are metadata shared among multiple users?
 

**Describe the bug**

**To Reproduce**

**Screenshots**

**Platform:**

- Browser: [e.g. Chrome, Safari]
- Memories Version: [e.g. 4.1.0]
- Nextcloud Version: [e.g. 25.0.6]
- PHP Version: [e.g. 8.1]

**Additional context**

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

**Comment by pulsejet** [comment]
> Are metadata shared among multiple users?

No. See https://github.com/nextcloud/recognize/discussions/751
