### ISSUE TITLE
Merge changes upstream

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#12]
Any chance you could submit merge requests to the official nextcloud photo app for some of these features? 

I know you said that it shares some of the same codebase, but I'm not sure how far things have diverged.

The built in photos app is pretty unusable for reasons you already described.

**Comment by pulsejet** [comment]
No, I'm strongly against this. At least right now, I've two full time jobs and really don't have the time to contribute to something maintained by someone else and argue about every design decision I make. Maybe some day.

**Comment by meichthys** [comment]
I'm closing this since memories has come so far in the last few weeks. I have no desire to move back to Photos or to have changes merged back. Memories is better off by itself.

**Comment by pulsejet** [comment]
It's closed already, unless we got a GitHub bug haha.

**Comment by meichthys** [comment]
@pulsejet  Oops, i think i meant to indicate that we could close this: https://github.com/pulsejet/memories/issues/183

**Comment by pulsejet** [comment]
I'll leave that open for now. Something like a featured tag won't hurt if we can actually get it; visibility is hard to come by.
