### ISSUE TITLE
Triggers don't work with PostgresQL, nextcloud 29

### ISSUE THREAD

**Issue by cmigliorini** [pulsejet/memories#1203]
**Describe the bug**
Compatibility mode is active on NextCloud 29 using Postgres 13.15

**To Reproduce**
- upgrade to NC 29.0.1.1

**Screenshots**

**Platform:**

- OS: Ubuntu Jammy
- Browser: N/R
- Memories Version: 7.3.1
- Nextcloud Version: 29.0.1.1
- PHP Version: 8.3

**Additional context**
`occ maintenance:repair` yields

```
 - Repair steps for Memories
     - External table schema seem up to date
     - WARNING: Failed to create filecache trigger (compatibility mode will be used): An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "TRIGGER"
LINE 1: CREATE OR REPLACE TRIGGER memories_fcu_trg
                          ^
     - exiftool binary is configured: /data/homes/cloud.bigmillion.fr/nextcloud/apps/memories/bin-ext/exiftool-amd64-glibc
     - go-vod binary is configured: /data/homes/cloud.bigmillion.fr/nextcloud/apps/memories/bin-ext/go-vod-amd64
     - ffmpeg binary is configured: /usr/bin/ffmpeg
```
- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

**Comment by pulsejet** [comment]
#1106

**Comment by cmigliorini** [comment]
> #1106

Apologies, I _did_ check the _open_ tickets only
