### ISSUE TITLE
 Error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

### ISSUE THREAD

**Issue by VirginioMiranda** [pulsejet/memories#1205]
**Describe the bug**
I can't login into the Android app.If i disable certificate verification it works, but i dont want to use in this unsecure way.

**To Reproduce**
I install the latest version of the application from Google Play and when I try to login, the message " Error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found" appears.

**Platform:**

- OS: Kubuntu 24.04 LTS
- Browser: Firefox snap 125.0.2
- Memories Version: 1.12 google play
- Nextcloud Version: snap 27.1.9
- PHP Version: 8.2.18

**Additional context**
The certificate is self-signed. It works in all Nextcloud applications for Android and others, the only exception is with memories apk for Android.

- Any errors in the JS console? NO
- Any errors in the Nextcloud server logs? NO

**Comment by pulsejet** [comment]
> The certificate is self-signed. It works in all Nextcloud applications for Android 

Have you installed a trust anchor manually? Otherwise the above makes no sense.

**Comment by VirginioMiranda** [comment]
I'm very sorry, the DDNS service is down. I checked it now. It was an unfortunate coincidence when I installed the memories for android app from google play and the DDNS service went down. Please accept my apology. Sorry to waste your precious time.
