### ISSUE TITLE
Display map of photos

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#121]
Potential Solution: The nextcloud maps app displays the locations of photos, so we could just link to that.

On a side note, the metadata nextcloud app does display the geolocation of photos. The address is clickable which opens a small dialog with an openstreetmap view of the location the photo was taken.

**Comment by pulsejet** [comment]
Sounds good. Not sure what it'll take to get the sidebar to work right though.

**Comment by jacotec** [comment]
@pulsejet Sorry to jump into an already closed issue, but the NC Maps application is unfortunately horrible maintained and the performance is absolutely worse.

It currently does not work at all and even nearly crashes the server in case a user has more than a few hundred photos and nobody seems to care about: https://github.com/nextcloud/maps/issues/865
So I (and some others) have been forced to disable it to ensure a stable server operation.

Your app is an absolute boost in performance compared to Photos and if you see any chance to integrate a maps feature directly into Memories with your performance knowledge, it would be absolutely great!

**Comment by meichthys** [comment]
That being said, you may be interested in the screenshot here that seems to show metadata (and a map)!
https://github.com/pulsejet/memories/issues/68#issuecomment-1306440766

**Comment by jacotec** [comment]
> @jacotec I'm using the maps app with about 10k photos without much trouble. It does take about 10 seconds to load the thumbnails, but it doesn't seem to be that bad. 

Maybe it works somehow with 10k photos, but it definitely does not work at all with >50k. And it's not running on a Pi, it's a Dell R720 and NC has 10 vCPU and 16GB RAM assigned.

**Comment by jacotec** [comment]
> That being said, you may be interested in the screenshot here that seems to show metadata (and a map)! [#68 (comment)](https://github.com/pulsejet/memories/issues/68#issuecomment-1306440766)

Yap, I saw this ... but the map is the location of a single photo (although I extremely love it!). What we need is a real map with all the photos and a good reaction ... similar to what I have on my iPad in Apple Photos.

I was using another open source project for photos before, Picapport. Very responsive map display for >100k photos. But as we all have in the Nexcloud, it's useless to sync a second thing just for map display.

**Comment by jacotec** [comment]
> Of course there's no point reimplementing all the features from maps (that's _definitely_ out of scope), so we need to first make a list of which features are specifically the most useful and relevant.

From my side it should put my photos on the map, you should be able to see them, move, zoom ... and finally select a pile of them in the wanted location to scroll / switch through them. So basically what the "photos" section in the Maps app does ... or the maps feature in Apple Photos on the iPhone/iPad or in Picapport.

I don't need tracks, persons, items, dogs, cats, mice and all this stuff. I just need all my photos on a map with a great usability.


> Unfortunately 10 seconds is _horrible_ for 10k photos. Memories loads 40k photos in ~500ms which I still find a bit on the higher side. It's just that our expectations from open source tend to be lower :) 

No, it's not lower (on my side). You are more thankful that guys like you put so many time into Open Source projects ... so you're mostly not bothering them with "Hey, that could be faster / better". I like to make constructive proposals in issues, not telling people that it's crap (mostly ;-) )

> In an ideal world I could work on the maps app itself, but I don't believe waiting for 10 days for a code review and then getting comments on code or language style is a productive use of my time.

**Your** app proves which coding style is the right one! :-)

> Basically the whole point of building this app vs using something like Photoprism / Immich (which is really good btw) is to integrate everything into a single platform.

That's exactly the point why I jumped in here. I don't want to spin up another VM with some software, which needs work and maintenance and force you to open another web page just to have a working map view if everything else is in my Nextcloud.

**Comment by tacruc** [comment]
Hey I found time to work a bit on the performance of the photos feature in maps. 
The backend is still horrible.
But the frontend now handles bigger number of photos, quote smoothly.

There are further improvements in https://github.com/nextcloud/maps/pull/924
