### ISSUE TITLE
Memories Android app not able to connect to server - 405 Method not allowed on login

### ISSUE THREAD

**Issue by mwildbolz** [pulsejet/memories#1211]
**Describe the bug**
When installing the Memories Android App and entering the connection string, an error message appears:
"Login flow returned a 405 status Code. Check your rev..."

**To Reproduce**
Start app, enter connection string and click on "Continue to Login"

**Screenshots**
![Screenshot_20240601_104028_Memories](https://github.com/pulsejet/memories/assets/33372199/f67c3959-461f-4c13-96ef-182f9f70c791)

**Platform:**
- OS: Android
- Browser: Memories App
- Memories Version: 7.3.1
- Nextcloud Version: 29.0.0
- PHP Version: 8.2.19

**Additional context**
Nextcloud installation is working without problems, Memories via Web-Browser is working without problems on Android phone (in browser) as well as on windows clients (browser).
Seems to be a problem dedicated to the Android app.
Nextcloud is installed via docker container, behind nginx proxy as described on [Github Examples](https://github.com/nextcloud/docker/tree/master/.examples)

**Nextcloud (Apache) log:**
```
194.118.36.211 - - [01/Jun/2024:08:29:28 +0000] "GET /index.php/apps/memories/api/describe HTTP/1.1" 200 1652 "-" "Memories"
194.118.36.211 - - [01/Jun/2024:08:29:28 +0000] "GET /login/v2 HTTP/1.1" 405 1572 "-" "Memories"
```

**Comment by clepz** [comment]
same problem here. I use cloudflare tunnel. there is no problem with nextcloud connection (actually there is one but not important for now). I can connect memories on web browser. However can't access via mobile app if I use my domain. The android app connects with local ip address.

**Comment by clepz** [comment]
I resolved the issue by setting up Nextcloud correctly. The HTTPS structure was buggy, and something was misconfigured. I restarted the setup process and carefully configured each variable properly.

**Comment by mwildbolz** [comment]
Interestingly, yesterday it started working without any change on the nextcloud server.
Also the HTTPS configuration did not change in my case.

But, nevertheless, main thing is that it works now. Closing this topic...

**Comment by Elektroman2** [comment]
Key point is : add related values to config.php.
```
  'overwrite.cli.url' => 'https://<your.domain.here>',
  'overwritehost' => '<your.domain.here>',
  'overwriteprotocol' => 'https',
```


This info is from here: https://help.nextcloud.com/t/problem-desktop-client-login-flow-v2/78279/2
