### ISSUE TITLE
Unable to share photos selection (409 Parent node does not exist)

### ISSUE THREAD

**Issue by pktiuk** [pulsejet/memories#1213]
**Describe the bug**

I am not able to share photos selection using Memories

**To Reproduce**

1. Open Memories
2. Select some random photos
3. Press Share (select public link)
![obraz](https://github.com/pulsejet/memories/assets/45544416/26b4a0a8-ef31-49e6-a99e-ae06191fbcfc)

4. Watch error

**Platform:**

- OS:  Pop!_OS 22.04
- Browser: Firefox 126
- Memories Version:  7.3.1
- Nextcloud Version: 28.0.5 deployed with Nextcloud AIO
- PHP Version: 8.2.18

**Additional context**

- Any errors in the JS console?

![obraz](https://github.com/pulsejet/memories/assets/45544416/0c7db520-2017-407a-a97a-b5f8153e7ee3)

Response in 409 COPY errors looks like this:

```xml
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Conflict</s:exception>
  <s:message>The destination node is not found</s:message>
</d:error>
```

- Any errors in the Nextcloud server logs?

Nope

**Comment by pulsejet** [comment]
Is that the error in the 409 in the MKCOL too?

**Comment by pktiuk** [comment]
Hello @pulsejet ,

Sorry but I don't undersrand this question.

**Comment by pktiuk** [comment]
@pulsejet    
Oh, I see now

Response for MKCOL is different:

```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Conflict</s:exception>
  <s:message>Parent node does not exist</s:message>
</d:error>
```

**Comment by pulsejet** [comment]
Hmmm, do you have the photos app enabled and do albums work right in photos?

**Comment by pktiuk** [comment]
No, I disabled Photos app.

**Comment by pulsejet** [comment]
You need to enable it for this feature

**Comment by pktiuk** [comment]
Thank you @pulsejet,

Enabling Photos app fixed this issue.   
I think there should be a way to handle this problem by communicating the user that photos are required for some functionalities of memories. (I thought I don't need Photos because Memories are far superior in every aspect)

**Comment by pulsejet** [comment]
Albums do depend on Photos, and link sharing basically creates an album. The admin panel should already show a warning if Photos is disabled.
