### ISSUE TITLE
Live Photos will not play (empty response)

### ISSUE THREAD

**Issue by cromefire** [pulsejet/memories#1218]
**Describe the bug**
When trying to play live photos they don't play and the request that is generated for them comes back with an empty response.

**To Reproduce**
- Open a live photo from a Pixel 7 Pro
- Press play
- Issue crops up

**Screenshots**

**Platform:**

- OS: Linux
- Browser: Firefox
- Memories Version: 7.3.1
- Nextcloud Version: 29.0.1
- PHP Version: 8.2

**Additional context**

The request coming back from the server ha an empty response and a HTML content type:
<details>
<summary>Request headers</summary>

```
GET /apps/memories/api/video/livephoto/166746?etag=6633fbb235878&liveid=self__traileroffset%3D2042487&transcode=yqgi0kw6bdb0 HTTP/1.1
Host: [censored]
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0
Accept: video/webm,video/ogg,video/*;q=0.9,application/ogg;q=0.7,audio/*;q=0.6,*/*;q=0.5
Accept-Language: en-US,en;q=0.7,de;q=0.3
Accept-Encoding: gzip, deflate, br, zstd
DNT: 1
Sec-GPC: 1
Sec-Fetch-Dest: video
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
Range: bytes=0-
Connection: keep-alive
Cookie: [censored]
```

</details>

<details>
<summary>Response headers</summary>

```
HTTP/1.1 200 
strict-transport-security: max-age=31536000; includeSubDomains; preload
date: Tue, 04 Jun 2024 19:19:58 GMT
server: Apache/2.4.59 (Debian)
referrer-policy: no-referrer
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-robots-tag: noindex, nofollow
x-xss-protection: 1; mode=block
x-powered-by: PHP/8.2.19
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-cache, no-store, must-revalidate
pragma: no-cache
content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
x-request-id: GG8YCce2syvbwLZ3DIJK
feature-policy: autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
content-length: 0
content-type: text/html; charset=UTF-8
X-Firefox-Spdy: h2
```

</details>

The photos are located on external storage, but it had worked some time ago.

- Any errors in the JS console?

Yes:
```
HTTP “Content-Type” of “text/html” is not supported. Load of media resource https://[censored]/apps/memories/api/video/livephoto/166746?etag=6633fbb235878&liveid=self__traileroffset%3D2042487&transcode=yqgi0kw6bdb0 failed.
21:24:13.197 Cannot play media. No decoders for requested formats: text/html
```

- Any errors in the Nextcloud server logs?

No

**Comment by botsarenthuman** [comment]
Also see 
```
video.es.js:222 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.
```

and

```
 Cannot read properties of null (reading 'isFavourited')
```

in the console.

**Comment by pulsejet** [comment]
Sample file?

**Comment by cromefire** [comment]
I'll produce one, might need a day or so because I'll have to find time to make sure that no location metadata is included.

**Comment by vitorsemeano** [comment]
The same happens in my instance. Not sure is the same problem, but with vaapi transcoding this does not work. If I disable it, starts working.

I have a amd apu, probably is because of that.

Sample: 

https://github.com/pulsejet/memories/assets/4042283/f5dbade9-29eb-4601-aa07-340d9a57cb56

**Comment by cromefire** [comment]
![PXL_20240628_064947391.RAW-01.MP.COVER.jpg](https://github.com/pulsejet/memories/assets/26320625/53f1518f-ddfb-4c18-bd9c-8d8efc3f6fd7)

Here's a sample from me as well. I also have VAAPI enabled, but on an Intel iGPU and I know for a fact it can Transcode HEVC just fine, maybe something with the invocation is wrong.

When disabling VAAPI it works, but is unusably slow. I'll try to investigate and try some stuff in the container, but it has worked before...

**Comment by cromefire** [comment]
Okay the issue seemed to be VAAPI driver, so that's on me, would have loved though if the error logging would be a bit clearer like "failed to Transcode live photo" instead of it just magically not working.
