### ISSUE TITLE
add support of viewing 360 images via Photo Sphere Viewer

### ISSUE THREAD

**Issue by 1immortal** [pulsejet/memories#1223]
**Is your feature request related to a problem? Please describe.**
I have some 360 images that was shot by a Mijia sphere camera, and I would like to host and view them on the memories app.

**Describe the solution you'd like**
If possible, integration of this - https://apps.nextcloud.com/apps/files_photospheres - or some direct support inside the Memories interface/app

**Describe alternatives you've considered**
integration of this - https://photo-sphere-viewer.js.org/

**Additional context**
Thank you for the amazing tool!!!

**Comment by pulsejet** [comment]
Duplicate of #1036
