### ISSUE TITLE
Viewer: Nextcloud toolbar icons obfuscates Memories icons

### ISSUE THREAD

**Issue by Deevad** [pulsejet/memories#1232]
### Describe the bug

The icons while viewing an image ( edit, infos, etc ) are covered by the Nextcloud icons (Notifications, etc...) and impossible to click on them.

### Steps To Reproduce

1. Click on a photo thumbnail.
2. When the photo is in viewer mode, try to edit it or check the info on top-right.
3. You can't: the Netxcloud's icons are on the top.

### Platform

```markdown
- OS:Debian 12 Bookworm
- Browser:Firefox 115-12-0esr (64bit)
- Memories Version: 7.3.1
- Nextcloud Version:Nextcloud Hub 8 (29.0.2)
- Nextcloud AIO v9.0.1
```

### Screenshots

![2024-06-24_screenshot_022327_net](https://github.com/pulsejet/memories/assets/4021867/a45e047c-c900-45b4-9b5a-575eacab0d0e)  
_Screenshot of the bug: check on top-right, it's impossible to click on icons to edit the picture_

**Comment by pulsejet** [comment]
https://github.com/pulsejet/memories/issues/1104

**Comment by Deevad** [comment]
Thank you for the redirection and triaging this quickly the duplicate. :+1: 
  
I understand the Firefox ESR issue.
