### ISSUE TITLE
[Feature Request] Live Photos

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#124]
It would be really nice to have support for live photos. 
A good chunk of research about how to work with live photos can be found here: https://github.com/LycheeOrg/Lychee/issues/378#issuecomment-545428092

**Comment by meichthys** [comment]
I'm not sure about gphotos, but ios Live photos already are separated into different files, so perhaps we can hide the video file and only show it on mouseover. This would greatly improve the usability for iOS users since currently every pohot is duplicated in the interface:
![image](https://user-images.githubusercontent.com/10717998/199785884-b59ad226-23c1-40dc-9bbb-666d8fad7bfa.png)

**Comment by pulsejet** [comment]
Upgrade notes:
1. Run `occ memories:index --clear`
2. Only JPEG supported (but this is the most common anyway). Support for Apple, Google and Samsung only.

![chrome-capture-2022-10-22](https://user-images.githubusercontent.com/10709794/203382021-4a6a19a0-806e-4293-8837-7998a69690fb.gif)

[chrome-capture-2022-10-22.webm](https://user-images.githubusercontent.com/10709794/203381979-cc9c4275-8a49-433d-ba8a-eb35c416dfc4.webm)

**Comment by meichthys** [comment]
Wow. I didn't know this was coming. This made my day!

**Comment by pulsejet** [comment]
Demo has samples at the top now ✅

**Comment by meichthys** [comment]
@pulsejet Is the roadmap public?

**Comment by pulsejet** [comment]
> @pulsejet Is the roadmap public?

https://github.com/pulsejet/memories/milestones

Of course it might keep changing.

**Comment by meichthys** [comment]
Nice! So few project seem to use milestones so i didn't even think to look there 👍
