### ISSUE TITLE
Display "location" field in Albums view

### ISSUE THREAD

**Issue by jovanbulck** [pulsejet/memories#1253]
**Is your feature request related to a problem? Please describe.**
The form for creating or editing an album allows to set a free-text field labeled "location". This is useful to add a short description/note about the album contents (e.g., travel details and/or countries/locations the photos were taken). Currently, however, the "location" field appears to never be used and it is not displayed in the user interface when viewing an album.

**Describe the solution you'd like**
When opening an album, the free-text "location" field should be displayed in a smaller font under the album title and above the photos.

**Describe alternatives you've considered**
The separate Places view, but this only works if the photos contain GPS coordinates + does not allow grouping by album + cannot replace free-text field.

**Additional context**
* The "location" field is inherited from the Nextcloud Photos app and is stored in the database there.
* Arguably, "location" may be a confusing label, as it is a free-text field and is entirely unrelated to any GPS coordinates in the individual photos within the album. Maybe "description" would be a better name for the UI(?) (but at least the code should continue using "location" as this is determined by the Photos app..).
* The Photos app displays the "location" field with a :round_pushpin: icon, which may not be the best choice when treating/displaying this field as a generic "description" instead(?)
* Ideally, IMHO, would be to have two separate free-text fields "description/notes" _and_ "location", but this would require extending the database record used in the Photos app and/or simply keeping a "shadow" DB entry for Memories albums(?)
* Currently, Nextcloud Photos displays album "location" as follows:
![image](https://github.com/user-attachments/assets/bce5c90a-fe6a-479f-a5bb-4fc02915f7c1)
* I already implemented a proposal as part of #1245 , but opening a separate issue here to better keep track and discuss where needed. Currently looks as follows:
![image](https://github.com/user-attachments/assets/396eff02-ac8d-4ad8-9c53-409786ca8e33)

I'd be happy to incorporate any feedback!

Thank you for the fantastic app! :clap:

**Comment by pulsejet** [comment]
0390817f6e55c2b3d6b37b8703f9774b77723cf8
