### ISSUE TITLE
Display album collaborators

### ISSUE THREAD

**Issue by jovanbulck** [pulsejet/memories#1254]
**Is your feature request related to a problem? Please describe.**
Currently, Memories' Albums overview only clearly marks non-owned albums that are shared by others + it is cumbersome to see with which exact collaborators an album is shared. When having a lot of owned albums, this makes it hard to see which albums are private and which ones are shared and which users have access to specific shared albums.

**Describe the solution you'd like**
Memories' Albums overview page should clearly show whether owned albums are shared by others by appending a "Shared" keyword after the album title (ie  similar to how it's done for Google Photos and [nc-photos](https://gitlab.com/nkming2/nc-photos). Additionally, when opening an Album, Memories should show which exact collaborators have access (ie by showing their Nextcloud avatar and/or username).

**Describe alternatives you've considered**
Currently, this is only possibly by (1) opening the album; and (2) clicking on the "Share Album" button to see a list of collaborators.

**Additional context**
* I already implemented a proposal as part of #1245 (see also #1253) , but opening a separate issue here to better keep track and discuss where needed. Currently looks as follows:
![Screenshot from 2024-07-17 00-50-15](https://github.com/user-attachments/assets/e25375fb-390a-4ae1-98b3-35ffcc277e57)
*  Re the "Shared" keyword, not sure what is desired re translations, but I went for "Shared Album" for now as that is already in the translations currently; adding a more brief "Shared" translation keyword would probably be even more concise in the UI though.

I'd be happy to incorporate any feedback!

Thank you for the fantastic app! :clap:

**Comment by pulsejet** [comment]
0390817f6e55c2b3d6b37b8703f9774b77723cf8
