### ISSUE TITLE
"always load high resolution image" not working when using an anonymous access via shared link

### ISSUE THREAD

**Issue by akmail** [pulsejet/memories#1258]
### Describe the bug

when Memories is set to "always load high resolution images (not recommended)" it works fine for a user having access to the folder. But when the folder is shared via a read-only link to someone else, the setting is ignored, instead an upscaled preview is shown, only zooming in loads the original picture.

### Steps To Reproduce

activate setting "always load high resolution images (not recommended)"
share the folder via link
open it in a chrome incognoto tab: https://my.domain.tld/apps/memories/s/UNIQUE-SHARE-ID
the images don't have original resolution

### Platform

```markdown
- OS: MacOS
- Browser: Chrome
- Memories Version: 7.3.1
- Nextcloud Version:Nextcloud Hub 8 (29.0.4)
- PHP Version: not sure, docker instance
```

**Comment by akmail** [comment]
not much happening in this app, ugh?

**Comment by pulsejet** [comment]
The setting you're using is per-user. To make it global you need to enable the same setting in the Memories admin panel.

![{D816FAE4-FABD-4271-B16B-1F4756B0D823}](https://github.com/user-attachments/assets/9e4eb92c-1956-402a-9401-733e589264d1)
