### ISSUE TITLE
Error : Doctrine\DBAL\Query\QueryException: More than 1000 expressions in a list are not allowed on Oracle.

### ISSUE THREAD

**Issue by EVOTk** [pulsejet/memories#126]
Hello,
I'm have error in Nextcloud logs : Doctrine\DBAL\Query\QueryException: More than 1000 expressions in a list are not allowed on Oracle.

They are visible in admin/logging from the moment I consult Memories but they do not seem to prevent the normal functioning of Memories?

Nextcloud : 25.0.0
Nginx / Php 8.0
Memories : 4.3.8

![image](https://user-images.githubusercontent.com/45015615/198140224-1bf731ed-bf00-468d-b966-a3b3d8276f93.png)

![image](https://user-images.githubusercontent.com/45015615/198140854-3eef6fec-ca4e-4718-a9c8-475c23419d52.png)

```
Doctrine\DBAL\Query\QueryException: More than 1000 expressions in a list are not allowed on Oracle.

    /config/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 294:
    OC\DB\QueryBuilder\QueryBuilder->execute()

    /config/www/nextcloud/apps/memories/lib/Db/TimelineQueryDays.php - line 108:
    OC\DB\QueryBuilder\QueryBuilder->executeQuery()

    /config/www/nextcloud/apps/memories/lib/Controller/ApiController.php - line 686:
    OCA\Memories\Db\TimelineQuery->getDay()

    /config/www/nextcloud/apps/memories/lib/Controller/ApiController.php - line 109:
    OCA\Memories\Controller\ApiController->preloadDays()

    /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:
    OCA\Memories\Controller\ApiController->days()

    /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:
    OC\AppFramework\Http\Dispatcher->executeController()

    /config/www/nextcloud/lib/private/AppFramework/App.php - line 172:
    OC\AppFramework\Http\Dispatcher->dispatch()

    /config/www/nextcloud/lib/private/Route/Router.php - line 298:
    OC\AppFramework\App::main()

    /config/www/nextcloud/lib/base.php - line 1047:
    OC\Route\Router->match()

    /config/www/nextcloud/index.php - line 36:
    OC::handleRequest()
```

**Comment by pulsejet** [comment]
Is this new for 4.3.8 or you had this earlier too?

**Comment by EVOTk** [comment]
Sorry, but I won't be answering. I migrated tonight to NC 25. I was on NC25 before.

**Comment by pulsejet** [comment]
@EVOTk can you try the latest version?

**Comment by pulsejet** [comment]
Closing because this is likely fixed. Please reopen if you encounter the same error (for any new/other errors open a new issue).

**Comment by EVOTk** [comment]
Hello,
I am now in 4.4.1, I have no more errors! For me it's solved :)

Thanks a lot @pulsejet

**Comment by EVOTk** [comment]
Fun 🤣
