### ISSUE TITLE
Looks like it has been more than an hour since the last index job was run. (but it seems like it did run?)

### ISSUE THREAD

**Issue by andre1808** [pulsejet/memories#1261]
### Describe the bug

I've installed Nextcloud and Memories yesterday on my all-inkl Webserver. It seems to run fine (except for facial recognition, but I guess I can't make this work) and an odd error in the settings, which says "Looks like it has been more than an hour since the last index job was run. Make sure Nextcloud cron is configured correctly."

Cron however seems to run fine, but it shows "Some jobs have not been executed since vor 16 Stunden. Please consider switching to system cron." since I've installed and configured Memories.
When running the cron.php manually, it shows "status: success" however.

I've already tried to run ./occ memories:index and ./occ maintenance:repair
Neither fix the issue.

In the DB it also seems like it has run.

### Platform

```markdown
- OS: Win10
- Browser: Every Browser
- Memories Version: 7.3.1
- Nextcloud Version: 29.0.4
- PHP Version: 8.3.8
```

### Screenshots

![image](https://github.com/user-attachments/assets/8f83fa71-5810-4918-a189-88da96de499b)
![image](https://github.com/user-attachments/assets/d6348eb4-5a82-4297-b4bf-e49d641b9895)
![image](https://github.com/user-attachments/assets/b333097c-b9e4-4345-9855-581e6b05069b)
![image](https://github.com/user-attachments/assets/83d73fa1-bda1-44ae-b235-909f661caeb7)

**Comment by andre1808** [comment]
Update. I may have found a workaround:
I've created a php script in the nextcloud folder:
```
<?php 
	exec("/usr/bin/php83 cron.php 2>&1", $out, $result);
	echo "Returncode: " .$result ."<br>";
	echo "Ausgabe des Scripts: " ."<br>";
	echo "<pre>"; print_r($out);
?>
```

I'm calling this php script instead of the cron.php from my cronjobs and this seem to have fixed both issues (under Basic settings as well as within memories:
![image](https://github.com/user-attachments/assets/ea6a28f3-a06a-46c0-9ec9-dcd196593375)
![image](https://github.com/user-attachments/assets/f9219702-7699-4c7b-b908-e8f9589cedec)

**Comment by pulsejet** [comment]
Could be a transient issue, cause that should do the same thing. Regardless, good to hear it's resolved
