### ISSUE TITLE
Memories app triggers CSP Warning for https://binaries.webex.com

### ISSUE THREAD

**Issue by xundeenergie** [pulsejet/memories#1262]
### Describe the bug

I was just debugging a problem, so i saw this from memories app in dev-console in Firefox
![image](https://github.com/user-attachments/assets/6ee1da9a-e0d5-4dde-b648-c50cced9cfa4)

```
Warnungen zu Content-Security-Policy 2
Content-Security-Policy: Ignorieren von "https://binaries.webex.com/" innerhalb script-src-elem: 'strict-dynamic' angegeben
```

### Steps To Reproduce

1. Open dev-console
2. Open memories app in webfrontend
3. first warnings for Content-Security-Policy

### Platform

```markdown
- OS: Linux
- Browser: Firefox 128.0.2 (64-Bit) Flatpak
- Memories Version: 7.3.1
- Nextcloud Version: Nextcloud Hub 8 (29.0.4)
- PHP Version: 8.3
```

### Additional context

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

**Comment by pulsejet** [comment]
Something must be injecting a script into the page, either a nextcloud app or browser plug-in. Memories doesn't reach WebEx.

**Comment by xundeenergie** [comment]
Ok.... i did more investigation... and i is also seen in other apps too.
