### ISSUE TITLE
Demo lacks features (outdated version?)

### ISSUE THREAD

**Issue by MrRinkana** [pulsejet/memories#1277]
### Describe the bug

The demo https://demo.memories.gallery seems to be lacking some features:
* "On this day" is missing and  the tab empty even though there are images more than a year old
* Transcoding is missing

Could it be that the demo is running an old version of memories?

**Comment by pulsejet** [comment]
* On this day looks for images around this date (say Aug 27-Aug 31 for today), but there aren't any
* The demo runs in a free tier vm so it's too slow for any transcoding

**Comment by MrRinkana** [comment]
That makes a lot of sense, sorry for the noise!
the nc version is old thoe ;)
