### ISSUE TITLE
Android app: Video transcoding

### ISSUE THREAD

**Issue by asdfgugus** [pulsejet/memories#1278]
**Is your feature request related to a problem? Please describe.**
High resolution video can only be played at home, if bandwidth is not sufficient. Transcoding is not supported in the Android app. 

**Describe the solution you'd like**
Video transcoding, when using the Android app. 

**Describe alternatives you've considered**
Using the browser to play the video. From there I can use the video transcoding feature. 

**Additional context**
It is not a very important feature, but the Android app would be easier to use.

**Comment by pulsejet** [comment]
> Transcoding is not supported in the Android app.

It is.

**Comment by asdfgugus** [comment]
Maybe I missed something...
I use go-vod on an external host. When I play a video from the browser, I can adjust the resolution settings and even set it to auto. Furthermore, I can see that the video transcoding is running on my GPU with the nvidia-smi command. 
However, when I use the Android app, I can neither adjust the resolution settings, nor does it start a video transcoding process on my GPU. Do I need to configure something?

**Comment by asdfgugus** [comment]
@blackmore190: There is currently no option to manually adjust the playback quality in the Android app.

**Comment by blackmore190** [comment]
But how do I know, that the video is transcoded and not the original one played?

**Comment by asdfgugus** [comment]
@blackmore190: Do you use hardware transcoding? While playing the video you can check on the server, if the GPU is running a task. In my case, I used the nvidia-smi cli tool.

**Comment by siccovansas** [comment]
I was also wondering about this. Some extra questions:
- What quality setting does the Android app use: 'Auto' or the default quality set by the server?
- Why isn't there an option to change the quality setting manually in the Android app?
