### ISSUE TITLE
Folder previews of photos

### ISSUE THREAD

**Issue by Akruidenberg** [pulsejet/memories#128]
Is it possible to show previews of photo's when browsing folders? The nextcloud photo app has this feature.

**Comment by Akruidenberg** [comment]
Yes! That's exactly what i mean.

**Comment by Akruidenberg** [comment]
> Works fine for me, did you generate previews?

Yes. strange enough, the official photo app is working fine with previews in folders.

**Comment by pulsejet** [comment]
Stale
