### ISSUE TITLE
"On this day" suddenly empty

### ISSUE THREAD

**Issue by jakobroehrl** [pulsejet/memories#1289]
### Describe the bug

After the update to NC 30 and the activation of recognize (faces) the "on this day" view is completly empty. 
I deleted the faces and did a "occ memories:index --force" but the faces are still not there.

### Platform

```markdown
- OS:
- Browser:
- Memories Version:
- Nextcloud Version:
- PHP Version:
```

### Additional context

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

**Comment by jakobroehrl** [comment]
found the prob myself

**Comment by kinghat** [comment]
what was the reason your on this day widget was empty? mine has been empty for a while now. the one this day category in memories and photos is populated, though, not the widget.
