### ISSUE TITLE
No preview or display of high-resolution photos

### ISSUE THREAD

**Issue by EVOTk** [pulsejet/memories#131]
Hello,
No preview or display of high-resolution photos

Nextcloud : 25.0.0
Nginx / Php 8.0
Memories : 4.4.1
This problem was already present on the other versions of Memories, and also under Nextcloud 24.

![image](https://user-images.githubusercontent.com/45015615/198720673-edec1bf4-f5cb-42da-a7cb-06b263131492.png)

![image](https://user-images.githubusercontent.com/45015615/198721738-a742a008-be39-401b-b624-867b72e29d57.png)

Example info photo :

![image](https://user-images.githubusercontent.com/45015615/198721224-d7c22ccd-a326-4e8b-abaa-8f1e0b0f7812.png)
![image](https://user-images.githubusercontent.com/45015615/198721266-3e6d58a4-ce17-4301-ab86-4d581149fffb.png)
![image](https://user-images.githubusercontent.com/45015615/198721306-6111bb34-78ed-4bf3-a489-676a9b3dc955.png)
![image](https://user-images.githubusercontent.com/45015615/198721338-7816211d-f51c-4ca6-aa30-b49a28f8603f.png)

It is displayed correctly in the Nextcloud Android application: 
![image](https://user-images.githubusercontent.com/45015615/198722081-981f4e61-d996-41c8-a51b-456f5fe6642d.png)
![image](https://user-images.githubusercontent.com/45015615/198722057-ee6b35ed-6bab-4579-8299-11d7a0a2c596.png)

You can download a copy of a problematic photo here : https://www.swisstransfer.com/d/e8dc57c9-1fb9-4db6-9acb-22e42f10263a ( expire 27/11/2022 at 22:02 )

**Comment by pulsejet** [comment]
Do the photos get displayed in the Photos or Files apps (default Nextcloud)?

**Comment by EVOTk** [comment]
Ho ! 
I hadn't thought of that. I don't have the Photos app active. But indeed in "Files" from my PC, it doesn't show up either unlike the other photos.

So the place of this problem is in nextcloud/server I guess, it is possible to move an issue?

![image](https://user-images.githubusercontent.com/45015615/198740277-39a9de65-2be6-4408-9d0a-41135e599f51.png)

**Comment by pulsejet** [comment]
Nope you can't transfer issues between organizations :(
Btw if you've disabled Photos then you won't be able to use Albums support with NC25.

Closing.

**Comment by EVOTk** [comment]
Thanks for the information, I just created the issue on nextcloud/server and was just closing here :)

**Comment by EVOTk** [comment]
Hello,
for info, it's not a "bug". It's config issue.

https://github.com/nextcloud/server/issues/34877#issuecomment-1296175634
