### ISSUE TITLE
"Thumbs.db" file in directory prevents its visiblity in Memories (Solved)

### ISSUE THREAD

**Issue by shperrung** [pulsejet/memories#1312]
### Describe the bug

Certain directories aren't appearing in Memories after indexing and force re-index but they are available in main Nextcloud interface.
Owner is set "www-data:users", right for folders 755, rights for files 664.

### Steps To Reproduce

Create empty file named "Thumbs.db" in folder given to Memories. Do "...occ memories:index --force". This folder will disappear from Memories.

### Platform

```markdown
- OS: Debian 
- Browser: Mozilla, Chrome
- Memories Version: 7.4.1
- Nextcloud Version: AIO in docker ver. 29.0.7
- PHP Version:
```

### Additional context

- Any errors in the JS console? - No
- Any errors in the Nextcloud server logs? - No

**Comment by MrRinkana** [comment]
Close the issue if its solved! 
It might be helpful for future searchers to also state what fixed it in case you know how it was solved.
