### ISSUE TITLE
Support several sources of media

### ISSUE THREAD

**Issue by dronnikovigor** [pulsejet/memories#1333]
**Is your feature request related to a problem? Please describe.**
I'd like to have ability to select several sources of media.
E.g. I have following sctructure of files:
```
 /media
  /photos
    /library
    /unsorted
  /videos
  /movies
  /documents
 ...
```
Now I specify in Memories to scan `/media/photos/library`, but I'd also like to add `/media/videos` as a source.
If I specify `/media` it will scan all medias in all folders, that I don't need in my timeline. Also it's not convinient to add `.nomemories` to each new folder under root (eg. in `/media/movies` or `/media/documents`, it also adds visual garbage).

**Describe the solution you'd like**
In general settings (left downside) add ability to add list of folders to scan (now it's only one folder)

**Comment by eltos** [comment]
You could select `/media` as "Folders Path" and select `/media/photos/library` and `/media/videos` as "Timeline Path". For the latter, multiple folders are supported. This will ensure media from the other folders is not shown in the timeline. It will still be shown in the folders view though.

**Comment by dronnikovigor** [comment]
Oh, I see, makes sense
