### ISSUE TITLE
Uninstallation instructions missing

### ISSUE THREAD

**Issue by adrfantini** [pulsejet/memories#1337]
**Is your feature request related to a problem? Please describe.**
After trying out both Immich and Memories for a while, I decided to stick with the former for the time being.
I'd like to remove Memories and cleanup whatever data it has collected so far, but there's no indication in the manual on how to do that.

**Describe the solution you'd like**
A section in the manual that explains if it's enough to uninstall the extension or if additional cleanup steps must be taken, for example to delete the geolocalisation data.

**Additional context**
memories looked awesome and I really liked the seamless integration with nextcloud!
However in the end I chose to keep photos and other data completely separate, each with a different dedicated application.

**Comment by pulsejet** [comment]
https://memories.gallery/troubleshooting/#reset

**Comment by adrfantini** [comment]
> https://memories.gallery/troubleshooting/#reset

Understood.
Not the clearest and easiest to find to be honest, but it's there!

Thank you
