### ISSUE TITLE
can't change perl/exiftool path

### ISSUE THREAD

**Issue by MariusQuabeck** [pulsejet/memories#1338]
### Describe the bug

just migrated an AIO install from an amd64 host to arm64
memories app is still looking for an amd64 binary instead of an aarch64 one (which I've confirmed on a fresh AIO install where it exists and works)
How can I update the path?

<img width="883" alt="image" src="https://github.com/user-attachments/assets/47045fe4-800b-4a56-bcb9-48faab4ee023">

### Platform

```markdown
- OS: Ubuntu 24.04 server
- Browser: Chrome
- Memories Version: 7.4.1
- Nextcloud Version: Nextcloud Hub 8 (29.0.8)/Nextcloud AIO v9.8.0
- PHP Version:
```

**Comment by pulsejet** [comment]
See https://memories.gallery/troubleshooting/#instruction-set-change

**Comment by MariusQuabeck** [comment]
that worked, thank you!
