### ISSUE TITLE
Issues with photos on samba share / stream_copy_to_stream stalls

### ISSUE THREAD

**Issue by ssc85** [pulsejet/memories#134]
Hi,

I am using memories in nextcloud 25 in Freebsd / Truenas integration. My photos folder is added as an external storage (smb share) with access from two accounts.

The memories:index is generating a couple of errors like shown in #https://github.com/pulsejet/memories/issues/60 . Furthermore, the indexing stops after a couple of files and it looks like that the stream_copy_to_stream stalls (in function getExifFromStream(...)). I didn't find any reason for that, but even after 15 minutes the file was not processed. I put several debug messages and also tried to get the exif data of the referenced file via exiftool from cmd line - it worked without any issue in less than a second.

However, I avoid the issue (at least for my problem) by using the local exif processor (commented out the isLocal() check and used the getExifFromLocalPath(....) path). 

Is there any reason why we have to use the stream decoding for smb shares (sorry for the question, but I am really new to nextcloud and not familiar with the API/APP-integration at all)?

Best, Sebastian

**Comment by ssc85** [comment]
> Try mounting it as smb/cifs in the host and then pass through to the vm/container as local mount, that's how I do it, it's stable and super fast too. Can get very tricky with perms & mapping user ids under certain circumstances. Somehow samba is always prone to cause issues with anything 🤷‍♂️

I already thought of that, but - as you already outlined - it would be a mess with the permissions. The smb share is mounted in a user context because I access it from several other servers too. When mounting in the host, Nextcloud will write the upload data as www user which is not what I want (of course I can schedule a cron job fixing the permissions, but.....)

**Comment by ssc85** [comment]
Yes, that would be an easy "solution". However, in my setup I have different users owning different smb shares. Every user is able to mount the smb share by its own using its individual credentials. Mapping www-data to the uid could fit for one user, but it is not a fit-all solution. 

Currently the "solution" of treating the smb share as it were a "local storage" is working for me. But I am not sure about the drawbacks with that.

**Comment by pulsejet** [comment]
Please try with v4.5.2
