### ISSUE TITLE
exiftool / perl path for Freebsd does not match

### ISSUE THREAD

**Issue by ssc85** [pulsejet/memories#135]
In Freebsd / Truenas integration the perl path is /usr/local/bin/perl, which leads to an error using the exiftool shipped with memories (defined as /usr/bin/perl).

To avoid the issue (to not change the path after every plugin update again), I installed exiftool via the pkg manager and set memories.exiftool in config.php to point to /usr/local/bin/exiftool. This almost worked - except that memories tries to change the file permissions in getExiftool(...) by doing a chmod(...) which of course results in an permission denied error. 

Is it possible to skip the chmod(...) call when there is already a 0755 permission mask set? This will reduce the error messages dramatically.

**Comment by pulsejet** [comment]
The correct fix for this is to simply use the perl binary in PATH to execute exiftool.

**Comment by pulsejet** [comment]
Should be fixed in the next version. Reopen otherwise.

**Comment by pulsejet** [comment]
@ssc85 can you test with 4.5.3?

**Comment by ssc85** [comment]
@pulsejet thank you. It now works on FreeBSD.
