### ISSUE TITLE
Memories not going through subfolders

### ISSUE THREAD

**Issue by elr3m** [pulsejet/memories#136]
Hi there,

I am running Nextcloud 25 Stable, on Apache 2.4.38, with MariaDB and SMB mounted drive for the Data directory.
I have Auto-Upload activated on my smartphone and set to store pictures in subfolders for years and month.
</t>IE: photo taken on 2022-10-29, will be in the folder: Auto-Upload/2022/10/Pics.jpeg
I installed Memories 4.4.1 and updated yesterday to 4.5.1.
I ran ./occ memories:index right after the first install and ran it again after 4.5.1 update.

On either versions, Memories only show me something in the Timeline if I select a month folder (ie: a folder that has pics directly in it).
Nothing shows if I select Auto-Upload or Auto-Upload/YYYY.

My understanding was that Memories should look in subfolders, looking at the Github project page, it does say: 
"Photos from this directory will be displayed in the timeline, including any photos in nested subdirectories."

Am I doing something wrong? Do I need to put a single picture in each of the YYYY and MM folders to make it go through?

**Comment by pulsejet** [comment]
1/ Does the folders view work as expected?
2/ I'm assuming everything is on a single storage backend?
3/ Any errors in logs etc?

**Comment by elr3m** [comment]
1/ If I set Folders Path as Auto-Upload (or anything else), it does shows all folders and content
2/ Yes all on the same backend storage
3/ Not at all.

**Comment by pulsejet** [comment]
Okay, then this needs more debugging. Can you try creating a new folder in your root, set that to timeline path and upload some photos to it (nested). Does this have the same behavior.

Also if possible, try running this SQL and report the result. You need to replace `252525` by the file id of the Auto upload folder (make a query on `oc_filecache` for the folder name in `name`)

```sql
WITH RECURSIVE
    oc_cte_folders(fileid) AS(
    SELECT
        f.fileid
    FROM
        oc_filecache f
    WHERE
        f.fileid = 252525
    UNION ALL
SELECT
    f.fileid
FROM
    oc_filecache f
INNER JOIN oc_cte_folders c ON
    (
        f.parent = c.fileid AND f.mimetype = 2
    )
)
SELECT
    *
FROM
    oc_cte_folders
```

**Comment by elr3m** [comment]
Hi @pulsejet , 

Thank you for your answer.

I created a new folder called testingmemories at the root of my NC account.
Added 2021/03 and 2022/01 to it with their respective content, changed Memories "Timeline Path" and "Folders Path" to it as well and I am seeing the same behavior:
- "Nothing to show here" under Timeline
- Folders showing as expected under Folders

I tried to run the query, but it seems I am missing the oc_cte_folders table, I have not oc_cte_* tables.
That feels like a problem on my side :( 
Any idea on how to fix it?

**Comment by pulsejet** [comment]
I see.

> I tried to run the query, but it seems I am missing the oc_cte_folders table, I have not oc_cte_* tables. That feels like a problem on my side :( Any idea on how to fix it?

This isn't a table, it's a CTE defined just above the query. What error do you get? Also what version of mariadb is this?

**Comment by elr3m** [comment]
Sorry rather new to databases.

I get the following error:
`Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.oc_cte_folders(fileid) AS(     SELECT         f.fileid     FROM         sfo_...' at line 2`

MariaDB version: 10.3.36-0+deb10u2

**Comment by elr3m** [comment]
Here is the SQL full code I run:
```
WITH RECURSIVE
    nextcloud_staging.oc_cte_folders(fileid) AS (
    SELECT
        f.fileid
    FROM
        nextcloud_staging.oc_filecache f
    WHERE
        f.fileid = 23865765
    UNION ALL
SELECT
    f.fileid
FROM
   nextcloud_staging.oc_filecache f
INNER JOIN nextcloud_staging.oc_cte_folders c ON
    (
        f.parent = c.fileid AND f.mimetype = 2
    )
)
SELECT
    *
FROM
    nextcloud_staging.oc_cte_folders

```

From MySQLWorkbench

**Comment by pulsejet** [comment]
Why is there a `.` in your query before `oc_cte_folders(...`? Are you sure you copied the full query correctly?

**Comment by elr3m** [comment]
Answer question before you asked, see above post ;)

**Comment by pulsejet** [comment]
You don't need the database name before the CTE name. Try this:
```sql
WITH RECURSIVE
    oc_cte_folders(fileid) AS (
    SELECT
        f.fileid
    FROM
        nextcloud_staging.oc_filecache f
    WHERE
        f.fileid = 23865765
    UNION ALL
SELECT
    f.fileid
FROM
   nextcloud_staging.oc_filecache f
INNER JOIN oc_cte_folders c ON
    (
        f.parent = c.fileid AND f.mimetype = 2
    )
)
SELECT
    *
FROM
    oc_cte_folders
```

**Comment by pulsejet** [comment]
That is .. strange. How about this? In particular the mimetype.
```sql
SELECT * FROM nextcloud_staging.oc_filecache WHERE fileid=23865765
```

**Comment by pulsejet** [comment]
I have an idea what's likely wrong, but these queries should confirm it.

**Comment by pulsejet** [comment]
Perfect. I'll fix this tonight.

**Comment by elr3m** [comment]
Ah great, thank you!!!!!
Shall I update to 4.5.2 in the meantime?
Also I am impressed with your understanding of the issue based on that much information!

**Comment by pulsejet** [comment]
> Ah great, thank you!!!!! Shall I update to 4.5.2 in the meantime?

Sure! Of course it won't fix your issue yet ;)

> Also I am impressed with your understanding of the issue based on that much information!

Haha actually I was lazy and hardcoded the mimetype `2` for folders. Basically the CTE does a recursive walk over your folder structure, filtering out only folders from all children. The second query uses the correct mimetype from the `oc_mimetypes` table (which in your case is `4`) instead of just `2`.

**Comment by pulsejet** [comment]
@elr3m can you test with v4.5.3?

**Comment by elr3m** [comment]
@pulsejet Just did and it works beautifully now! As expected, great job!
