### ISSUE TITLE
Default photos app required to use albums

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#137]
I've disabled the default photos app since i strictly use Memories now (Thanks!).
It seems like I need to have the photos app installed in order to use albums in Memories. Is this correct?

**Comment by pulsejet** [comment]
Yes. I don't intend to reinvent the wheel here (and that also breaks compatibility). What could be done is have an option to hide the Photos tab, but I'll do that only if enough people want this. Don't want to offend anyone in the Photos team.

**Comment by meichthys** [comment]
That's fine. I just wanted to make sure that the photos app was required. There are ways to hide it using other apps. 👍

**Comment by pulsejet** [comment]
Didn't know that. Could you drop a name of one of these apps here for future reference?

**Comment by meichthys** [comment]
This one does it (and a LOT more): https://apps.nextcloud.com/apps/side_menu

**Comment by pulsejet** [comment]
Ah nice. I missed the comment by @illnesse
