### ISSUE TITLE
Face selection on mousedown?

### ISSUE THREAD

**Issue by illnesse** [pulsejet/memories#140]
Just a tiny thing i noticed, when selecting/deselecting faces i often miss some of them because if i move the mouse even just one pixel while clicking, the browser tries to drag the image and doesn't register the mouseup event (which triggers the selection via onclick or something i guess)

![image](https://user-images.githubusercontent.com/40355982/198972946-5b19754c-b725-48a6-9db3-bba1b67c90b5.png)

`pointer-events: none;` won't work since we actually want the click, but maybe we can trigger the selection on mousedown already?
It happens on mobile too, so that might need some extra touchstart magic or w/e

**Comment by pulsejet** [comment]
Perhaps https://html.spec.whatwg.org/multipage/dnd.html#the-draggable-attribute

**Comment by pulsejet** [comment]
5af495c4335f3046ed041fe95fda21b670f31c58

**Comment by pulsejet** [comment]
Unfortunately I have to revert this fix because it's causing strange bugs on iOS Safari :(
The good part is that selecting a lot of things is much easier now, so this isn't that big a problem, hopefully
