### ISSUE TITLE
Face count wrong when naming

### ISSUE THREAD

**Issue by mhzawadi** [pulsejet/memories#144]
I have just found this amazing app, got all my images indexed and gone to tidy up my people list. The number of images on the list is 4, clicking into to that person shows 4. But the count at the top of the page show a lot more

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/11944327/199188419-c0abeb5d-a88b-4262-89bc-8756a2c620d1.png">

<img width="215" alt="image" src="https://user-images.githubusercontent.com/11944327/199188674-f2ad5a60-9535-4368-8c7d-e596a0ee5d59.png">

**Comment by pulsejet** [comment]
That's not the count, that's the ID. Click the pencil at the right to edit it to a name.
