### ISSUE TITLE
[Feature Request] Zoom on photos

### ISSUE THREAD

**Issue by ereynier** [pulsejet/memories#149]
It could be great if you can add possibility to zoom with ctrl + mouse wheel or +/- buttons and with fingers (on smartphone) like google drive or google photos.

**Comment by marcosvfc** [comment]
That would be really nice, mostly in mobile devices! Also, if possible, re-enable the possibility to delete photos when in full screen.

**Comment by meichthys** [comment]
@marcosvfc I've added an issue to track the ability to delete photo from full view: #153

**Comment by pulsejet** [comment]
#162
