### ISSUE TITLE
Slow, unable to play videos and problem with the recognize app

### ISSUE THREAD

**Issue by sebastiencastermans** [pulsejet/memories#150]
Hi, seeing this application, I go crazy thinking "finally an app that makes a real gallery". But while digging I realize that all the videos are unplayable with the error message "Error loading {file name}". And when she manages to charge a little, I don't know how to look at her properly at all. 1, controls are different and not synchronized in full screen and small screen. 2, it charges for a super long time to be entitled to 2 seconds of videos every 20 seconds, no, it is not profitable. Then it would be nice if there was a "style" of a real gallery app like Google Photos or others and the photos and videos would show up with maybe a zoom effect and play or load instantly (necessarily, it depends on the upload speed of the server, I suspect that too!). And then looking quickly, I could see that there was an app on the App store, it would be great to have a "Nextcloud Gallery" app or something like that for Android :-). I "installed" the app from the server site but it's not crazy crazy. And finally, the Recognize app works quite well in the settings, I can name the different people it has already recognized but first you would have to know grouped because it recognized me twice and therefore I wrote twice my first name but the main problem is that when I go to the "People" tab of the "Memories" app, I have this error message which is displayed "Recognize app not enabled or not v3+" and therefore I have no one!

**Comment by meichthys** [comment]
It would also be helpful if we limit each github issue to a single problem. Some of the issues you mentioned are already covered in other filed issue. If you could add your input to those relevant issues, it may help get the features/issues added/fixed a bit quicker.

**Comment by sebastiencastermans** [comment]
> Could you add some text formatting please 🤡 @illnesse 

Yes, I will do that when I have time ;-)



> It would also be helpful if we limit each github issue to a single problem. Some of the issues you mentioned are already covered in other filed issues. If you could add your input to those relevant issues, it may help get the features/issues added/fixed a bit quicker. 🚀 @meichthys 

You are completely right! I'll take care of dispatching that. I was a little bit in a hurry when I typed all this 😬

**Comment by pulsejet** [comment]
This is likely not a problem with memories, but with nextcloud/viewer. Do the videos play well from the Files app?

Also please separate the rest into separate issues as already suggested.
