### ISSUE TITLE
Feature Request: Please add Editor Features from Photos App zu replace the Photos app

### ISSUE THREAD

**Issue by apg1980** [pulsejet/memories#151]

**Comment by meichthys** [comment]
I'm pretty sure this was possible in one of the previous versions. It could be a regression.

**Comment by pulsejet** [comment]
Just to be sure, are you testing with JPEG? The editing features only work with JPEG.

**Comment by meichthys** [comment]
@pulsejet  This seems to still be an issue in 4.6.2
I don't see the edit option in the viewer:
![image](https://user-images.githubusercontent.com/10717998/200363300-234cf9ab-43de-4012-bd63-6d7a1412de2c.png)

**Comment by pulsejet** [comment]
Also - can you edit the same photo in the Photos app?

**Comment by meichthys** [comment]
🤦‍♂️ Clearing the cache did the trick. Thanks @pulsejet

**Comment by pulsejet** [comment]
Great! Kinda strange you had to do that though ... the app upgrade is supposed to take care of that.

**Comment by pulsejet** [comment]
Btw I'd caution against the editor for now. See #174

**Comment by meichthys** [comment]
Ooo. Good to know. Thanks!
