### ISSUE TITLE
[Feature Request] Hide RAW

### ISSUE THREAD

**Issue by ereynier** [pulsejet/memories#152]
Maybe add a button in parameters to hide the RAWs from the timeline.

**Comment by pulsejet** [comment]
Is it not possible to use a `.nomedia` file?

**Comment by ereynier** [comment]
> Is it not possible to use a `.nomedia` file?

Yes it's a possibility. But if I could switch between show and hide it'll be better

**Comment by pulsejet** [comment]
Unfortunately, there's no way to achieve that without slowing down the queries significantly. Even if there is an option to hide the raw, showing them again would need you to re-run index. What you should be doing is put the RAW in a folder outside the timeline path.

**Comment by ollioddi** [comment]
PhotoPrism actually does this very well, as it "stacks" images together. Which means that the jpg will be shown, with the option to open a menu for the photo and find the raw in there. I think the benefit here is that its not placed separately but its easy to find if you actually need the RAW file.

My own raw files easily take up around 45 MB each, which really can slow things down.

Would a stacking method be possible to implement?

**Comment by llucax** [comment]
Also needing this very much. The stacking option seems the most sensible IMHO, or just showing on picture with some RAW icon to like live photos or videos have, to mark there is a RAW version of it too, then have an option in the details to access the raw for example.
