### ISSUE TITLE
Sidebar only opens correctly sometimes

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#155]
It seems like every other time, the sidebar won't open correctly. When opening a photo and choosing "Open Sidebar" it will display one of the following:

### Sidebar is not opened, but the menu changes to:
![image](https://user-images.githubusercontent.com/10717998/199791800-f590d51f-7994-48c6-8a0d-a05683540fdc.png)

### A blank area is created where the sidebar should appear:
![image](https://user-images.githubusercontent.com/10717998/199792578-08363e63-797a-4362-98de-72730f309e60.png)
Usually when this happens, the 'blank' sidebar will usually eventually close or the sidebar will appear after a few seconds.

### Sidebar is opened, but is not similar to the default nextcloud sidebar:
![image](https://user-images.githubusercontent.com/10717998/199792155-52a5fce9-8bfb-42c6-abf1-e5fb1b35c13b.png)
Default nextcloud sidebar usually looks like:
![image](https://user-images.githubusercontent.com/10717998/199792295-e64cc8c3-8acd-4ac3-bb37-6d48f78a026d.png)

### Additional Information
When opening an image i see the following in the browser console:
![image](https://user-images.githubusercontent.com/10717998/199795235-3c0490c8-e442-45ac-a982-45767ce74cfc.png)

**Comment by pulsejet** [comment]
Any pattern in this? Does this happen for certain kinds of files or files in certain locations, or files with certain kinds of names? Does anything look wrong with the PROPFIND URL in the console log?

**Comment by meichthys** [comment]
No specific pattern that i can tell, but i do notice that my file names have spaces in them. In the url the space is translated to `%2520`:
For example:
`/remote.php/dav/files/matt/Photos/22-10-30%252017-24-48%25209681.jpg`
Trying to access that path doesn't work, but if i add the space in place of `%2520`, then I can access the file.

**Comment by meichthys** [comment]
For what it's worth, i see the same sidebar issue in the default photos app.

**Comment by meichthys** [comment]
@illnesse Do you also see the 'double url encoding' when opening the sidebar?

**Comment by meichthys** [comment]
For the default photos app i see normal encoding (`/22-10-30%2014-00-28%209679.jpg`), but it still fails to PROPFIND the file
![image](https://user-images.githubusercontent.com/10717998/200035238-9462215b-7135-4bce-a468-38179603c7b1.png), but if i manually paste the encoded link into the browser, the image is displayed without issues.

**Comment by meichthys** [comment]
I think the recent sidebar changes has fixed this for me!
