### ISSUE TITLE
Unable to Favorite photos from sidebar

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#156]
Currently when trying to favorite a photo from the sidebar, a toast notification indicates that it's not possible:
![image](https://user-images.githubusercontent.com/10717998/199796474-f22faa5a-c56e-4664-915e-c712de60ef45.png)

Note: Favoriting photos from the timeline by selecting them then choosing "Favorite" from the selection menu works fine.

**Comment by pulsejet** [comment]
I can't repro this. Any logs?

**Comment by meichthys** [comment]
I do see this in the console logs:
![image](https://user-images.githubusercontent.com/10717998/200036424-690a133e-2565-4d91-8101-8f4eb86fd08e.png)

**Comment by pulsejet** [comment]
Are you on 25.0.1? I don't think this is a bug in memories.

**Comment by meichthys** [comment]
I'm currently on 25.0.1rc1 since i'm still on the beta channel, but when i get a newer version, I'll report back here.

**Comment by meichthys** [comment]
Works great! I really like the additions of the delete and favorite buttons in the new viewer!
