### ISSUE TITLE
Make it possible to view password protected folders via shared token

### ISSUE THREAD

**Issue by adminde** [pulsejet/memories#165]
This hopefully small feature request relates to the beautifully implemented feature #74.

Password protected shares are (at least for me) currently not be redirected to the authentication screen for
https://cloud.domain.com/apps/memories/s/{token}
as for e.g. files would've
https://cloud.domain.com/s/{token}
and the view is just shown with placeholder thumbnails

**Comment by pulsejet** [comment]
This is available in the new release @adminde

**Comment by adminde** [comment]
Dude you're awesome
Your work is strongly appreciated!
You really need add a donation paypal in the Readme or something similar 😉

**Comment by pulsejet** [comment]
> Dude you're awesome Your work is strongly appreciated!

Great to know it's useful 😄. Please do also report any more requests / bugs you come across.

> You really need add a donation paypal in the Readme or something similar 😉

Maybe I should 🤔. If I can get enough $ I could buy a real VPS to run the demo -- it's using an awfully slow free tier VM right now 👀
