### ISSUE TITLE
[Feature request] Show Meta information in the sidebar

### ISSUE THREAD

**Issue by jacotec** [pulsejet/memories#168]
When a photo is opened in Memories, the (i) button (sidebar) shows only Activity, Chat, Comments and Sharing:

![image](https://user-images.githubusercontent.com/3321655/200183100-bf9e1e66-5e3d-480f-a931-fb3122afb72a.png)

In many cases meta data is essential. To get these, you need to open the picture in the files app:

![image](https://user-images.githubusercontent.com/3321655/200183133-ed8a6980-1cb4-4d2a-9c3c-3129858c97eb.png)

These should be displayed directly in the sidebar in the Memories app without the need to open the picture in the files app.

**Comment by Akruidenberg** [comment]
Same as #68?

**Comment by pulsejet** [comment]
Duplicate
