### ISSUE TITLE
Wrong Face rectangle position with EXIF rotation

### ISSUE THREAD

**Issue by illnesse** [pulsejet/memories#170]
Got something fun for you if you are interested: https://github.com/nextcloud/recognize/issues/444 (#93)

Turns out the wrong position might actually be a wrong **rotation** coming from EXIF data, lemme know if you need files to test!

**Comment by pulsejet** [comment]
Makes a sense. Hopefully this isn't too hard to fix - we just need to store the rotation data in the db. Can you provide one or two test images?

**Comment by pulsejet** [comment]
Got it, thanks!

**Comment by pulsejet** [comment]
This is probably fixed by now
