### ISSUE TITLE
Add path to sidebar

### ISSUE THREAD

**Issue by illnesse** [pulsejet/memories#173]
Haven't had the time to debug this one yet, but i'm getting it often and i can reproduce it reliably

- Select a photo
- open "view in folder" in a new tab
- both tabs freeze for a couple seconds (maybe due to reflow? idk)

![image](https://user-images.githubusercontent.com/40355982/200399003-c9dc9d84-17d8-4999-8750-a1cb290f6763.png)
![image](https://user-images.githubusercontent.com/40355982/200399176-a04c0136-bb51-4bec-8e61-4f75938329a7.png)
![image](https://user-images.githubusercontent.com/40355982/200399252-da3250c8-01b0-4f4d-9014-38b50302ee3f.png)

this is probably not much help yet, i'll keep you posted

**Comment by pulsejet** [comment]
The view in folder button does basically nothing beside opening a new tab, so not sure where to begin 😄

Do you also see this if opening it from the new viewer?

**Comment by pulsejet** [comment]
Ah yes, that makes sense. The files app does do lazy loading, but it needs to load the entire thing to scroll to a particular file. Not much we can do there, but adding the full path to the sidebar makes sense.

**Comment by pulsejet** [comment]
I'm kinda stuck about the design for this. #68 shows how the sidebar looks. There seems no easy way to put a unix path in here without looking ugly ...

**Comment by pulsejet** [comment]
That looks nice! Should be straightforward to implement, we already have the path somewhere in Vue. I'll let you take this one: really need more people to get into the code ;)

Making it a bit smaller / monospace might also be interesting.

**Comment by pulsejet** [comment]
This is now available as an option
![image](https://github.com/pulsejet/memories/assets/10709794/bb8bd379-8628-4fe2-81b5-fbca923f1b11)
![image](https://github.com/pulsejet/memories/assets/10709794/64413001-8759-4ec8-8226-c1928393e629)
