### ISSUE TITLE
Saving a picture in the editor destroys all meta data

### ISSUE THREAD

**Issue by jacotec** [pulsejet/memories#174]
Thanks for bringing an editor feature into Memories! :-)

Unfortunately it has a serious issue: After modifying and saving a picture, all meta data is lost. That includes, apart from all the camera meta data and recording date, also the geo data.

Before editing:
<img width="389" alt="2022-11-07_20-54-05" src="https://user-images.githubusercontent.com/3321655/200402749-7cf8a18a-ff1a-4ec2-8c2e-83cf8fc2216c.png">

After editing:
<img width="385" alt="2022-11-07_20-53-34" src="https://user-images.githubusercontent.com/3321655/200402804-5e3194ae-d2c1-403e-9461-56d4df3bf90b.png">

**Comment by pulsejet** [comment]
Thanks for reporting this. Gonna pin this so people don't end up messing their files accidentally.

**Comment by pulsejet** [comment]
This might be worth reporting to @nextcloud/viewer too. Any files edited through the files / photos apps will still lose metadata.

**Comment by jacotec** [comment]
> This might be worth reporting to @nextcloud/viewer too. Any files edited through the files / photos apps will still lose metadata.

Done!
