### ISSUE TITLE
Some pictures are stretched when opening them

### ISSUE THREAD

**Issue by TtuxX** [pulsejet/memories#176]
Hi there @pulsejet :)

When I open some pictures from the timeline I see 3 strange things:
- On some pictures I cannot zoom (when I open the picture, I only get a "dezoom" mouse and clic action)
- All pictures appear to be zoomed-in a bit by default to fit screen; thus
- Pictures are getting deformed to match browser's window dimensions

Thank you in advance for your help and a big applause for all the updates and new features you are adding to the app :)

Best regards

**Comment by MoskiT87** [comment]
I can provide sample 
![Image](https://user-images.githubusercontent.com/66004695/200876950-c51f887a-19d7-4e79-b99b-a5cbf354c0ca.jpg)

**Comment by MoskiT87** [comment]
The image is stretched to fill the window

**Comment by TtuxX** [comment]
> You cannot zoom photos which are already smaller than your screen dimensions on desktop (this should still work on mobile). 

Would it still be possible to have the option to zoom in on desktop? 

This would be very convenient when you are multitasking and have several small windows displayed side by side along with your browser's window on a large screen.

Furthermore, I thing that having a powerful zooming effect with a mouse scroll is not really a problem as it's up to the user to zoom until the point he nearly gets pixels (but can be quite useful when you show a picture detail to somebody who is few meters away from your screen).

> But the pictures definitely shouldn't be stretched. Can you provide one or two sample images along with spec such as device, browser, resolution etc.?

I confirm that I have exactly the same image effects as @MoskiT87 (latest Firefox version on Mac).

**Comment by pulsejet** [comment]
> I can provide sample

I need an image file, not a screenshot.

**Comment by pulsejet** [comment]
> > You cannot zoom photos which are already smaller than your screen dimensions on desktop (this should still work on mobile).
> 
> Would it still be possible to have the option to zoom in on desktop?
> 
> This would be very convenient when you are multitasking and have several small windows displayed side by side along with your browser's window on a large screen.
> 
> Furthermore, I thing that having a powerful zooming effect with a mouse scroll is not really a problem as it's up to the user to zoom until the point he nearly gets pixels (but can be quite useful when you show a picture detail to somebody who is few meters away from your screen).

Basically the viewer library (PhotoSwipe) does not support this (at least out of the box), so it remains to be seen how this could be done.

**Comment by pulsejet** [comment]
You probably just need to run `occ memories index` or `occ memories index -f` to fix this. Basically this happens when the db is missing dimensions info about the image.
