### ISSUE TITLE
Possibility to reindex the pictures 

### ISSUE THREAD

**Issue by ThibautPlg** [pulsejet/memories#18]
Hello,
First of all, thanks for your work, the timeline is exactly what I was missing from the stock photo app, memories totally replaced it in my instance. 

I ran into a problem during my tests : the exif dates of some of my files were incorrect, the timeline feature make me realize that. (dates in 2036 something) 
I changed the dates using exiftool, and tried to re-run the `occ memories:index`, unfortunately it did not correct the dates in the database. 
```
==========================================
Checked 16025 files in 12.56 sec
1488 not valid media items
14537 skipped because unmodified
0 (re-)processed
==========================================
```
It looks like it did not even tried to re-process the files. 

I had to drop the content of the table and run `occ memories:index` to have a clean timeline. 

Could a command like `occ memories:refresh` be a thing ? 

Thanks,

**Comment by pulsejet** [comment]
Can be done as a flag to index.

Did you directly edit the files though? If the modified time gets updated (in the filecache, so basically if you update the file in nextcloud), then it should retrigger the exif read.

**Comment by ThibautPlg** [comment]
Yes I did directly edit the file. Indeed I did not tried to do an `occ files:scan`, maybe it would have triggered a normal behaviour. 

Also, should I add a cron execution regarding memories ?

**Comment by pulsejet** [comment]
I'd keep this issue open regardless; there might be other use cases for the refresh command.

You don't need a cron unless you're modifying the files directly regularly (also need to run scan then).

**Comment by pulsejet** [comment]
You can do this now with `--refresh` or `-f`

**Comment by TheWanderer1983** [comment]
When adding new photos do we need to rerun php ./occ memories:index or something similar?

**Comment by pulsejet** [comment]
@TheWanderer1983 No
