### ISSUE TITLE
Feature Request - Mobile Device App/Wrapper

### ISSUE THREAD

**Issue by Cebrain** [pulsejet/memories#180]
Hey,

i only found memories recently and it is really great. I was exactly looking for such solution.
The only feature i would really like to see, would be an mobile app to use memories. As i was searching, i couldnt find one?

I think a wrapper for the web page would be already enough.
The problem with the browser access on mobile is that not such tech savy people will experience problems.
Example, the back button closes sometimes the complete browser instead of going back. (Think this happens how nextcloud web is build) or picking a picture with a long press, opens the browser menu infront of the drop down menu.

**Comment by karpiq24** [comment]
Web app can be installed as an app, it works pretty well but I also have issues with back button closing app instead of going back.

**Comment by pulsejet** [comment]
> Web app can be installed as an app, it works pretty well but I also have issues with back button closing app instead of going back.

This should not be happening. When does this happen? Also I'm assuming you're on the latest version.

**Comment by karpiq24** [comment]
I just tested this and the back buttony works correctly every time. I guess it was happening on older version. Only one thing still mildly annoys me. I would love to be able to close navigation menu by clicking on the right side or by clicking back button.

**Comment by Cebrain** [comment]
I am also not 100% sure where it was i had the problem with the back button, but i have the same feeling/problem as @karpiq24 that i would like to see that the back button closes the navigation menu.

**Comment by pulsejet** [comment]
I agree the nav behavior is super annoying. In the next version, it'll close automatically on clicking something in it. Hopefully that's better.

I've thought about a mobile app, but it's more work than it'd seem at the surface. Basically to not be confusing, we also need to show the user's photos on the device that aren't uploaded yet in the same view. I've not written native mobile code for a long time, so not sure how easy/hard this is to achieve with modern APIs.

**Comment by pulsejet** [comment]
> picking a picture with a long press, opens the browser menu infront of the drop down menu.

I just noticed this comment. This should _definitely_ not be happening. Long press is supposed to select a photo. What browser / device is this?

**Comment by pulsejet** [comment]
Sounds like a bug with Firefox. I'll triage this later.

**Comment by dpeley** [comment]
I'd like to chime in just to +1 this idea, I'm looking every where for a Google photos replacement on android and have yet to find anything.

IMHO, if someone is able to create a decent looking android app that can link to your server app, it would bring a LOT more attention to your brilliant work for increased usability across the board.

**Comment by natrius** [comment]
I guess this is a PWA? Unfortunately i'm using OpenLauncher that does not support PWA right now :/ So a native app would really appreciated. Plus - https://github.com/meichthys/foss_photo_libraries here is listed that Memories does have an "Android App" and i do not consider a Web App an Android App tbh.  (Okay, probably thats why its rated just as 4 :) )

**Comment by meichthys** [comment]
> I guess this is a PWA? Unfortunately i'm using OpenLauncher that does not support PWA right now :/ So a native app would really appreciated. Plus - https://github.com/meichthys/foss_photo_libraries here is listed that Memories does have an "Android App" and i do not consider a Web App an Android App tbh.  (Okay, probably thats why its rated just as 4 :) )

The android app is rated a four because the Nextcloud app, which allows mobile uploads and viewing of photos. Just not the same interface as memories.

**Comment by Cebrain** [comment]
Want to add some thoughts about a dedicated app.

A benefit would be that you can choose a dedicated app on the phone as an photo picker. At the moment it is necessary to download an picture and then you can use it.

The local pictures (local photo app) and online pictures (memories) have nothing in common.
Its hard to explain to people if they delete a local photo for example they also need this todo in memories.
Another solution would be to delete the local copy of the photo but this is also not a good solution because of bandwith.

I know this is much work, but i think one big missing piece to replace GPhoto/GDrive.

**Comment by pulsejet** [comment]
Update on this, an Android app is now in early access: https://play.google.com/store/apps/details?id=gallery.memories
You do need the latest unstable version (v5.5.0-rc.2) on your server for this to work.

**Comment by pulsejet** [comment]
> Woah! This is an early Christmas present!

Haha!

> * Being able to see local photos alongside the nextcloud photos is such a big feature! (And i don't even see duplicates!?)

Indeed, this was the hardest part so I really hope it isn't going to break. Unlike other dedicated photo apps, you can do a lot more in Nextcloud like moving around files, renaming, sharing entire libraries etc. so establishing a 1-1 correlation between a file on the device and server turns out to be incredibly complicated (especially when Memories _deliberately_ does not handle automatic uploads).

> * Will there be a separate repository for the mobile app? It would be awesome if the APK file was available on github so we could install it directly or via tools like Obtainium.

It probably would make sense to have a separate repo just for the native app releases (i.e. APK uploads). The code itself would likely be in (this) monorepo. I don't expect the native parts to have very frequent updates once the API stabilizes, so the release cadence might be very different (well, hopefully).

**Comment by pulsejet** [comment]
> When do you plan to release v5.5.0 stable?

Probably next week. The server parts seem stable so it should be relatively low-risk.

**Comment by sesu-tech** [comment]
> Web app can be installed as an app, it works pretty well but I also have issues with back button closing app instead of going back.

The web app is disappointing in the sense that it doesn't work offline and can't work as a media file picker in apps when trying to attach photos. A native Android app will always feel more smooth and fluent as well.

**Comment by tclavier** [comment]
I thinks it's done : https://f-droid.org/fr/packages/gallery.memories/

Could you close this issue ?
