### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by mpodshivalin** [pulsejet/memories#182]
I've been looking for exactly this functionality for 5+ years. No other app that I've tried (standalone or as a Nextcloud plugin) can make a timeline which "normal" people can actually use :)
I'm sure many users feel the same, maybe it won't hurt to add donation options for this project? :)

**Comment by pulsejet** [comment]
First of all, thank you for considering supporting the project! I'm currently in the process of figuring out how this could be done best. There are a bunch of options, but hopefully GitHub sponsors can work out.

**Comment by pulsejet** [comment]
Added the link to readme ✔️

**Comment by pktiuk** [comment]
@pulsejet 

Could you check a [Polar](https://polar.sh) as a potential platform for funding selected issues?   
It could motivate some users to just vote with wallets on selected features. It could also incentivize external contributors to implement some features to get a bounty.

**Comment by pulsejet** [comment]
> Could you check a [Polar](https://polar.sh) as a potential platform for funding selected issues? It could motivate some users to just vote with wallets on selected features. It could also incentivize external contributors to implement some features to get a bounty.

I'll look into it, but solely for the second part of incentivizing external contributors.

I'm a bit wary / concerned about potential comments like "I donated $100 for this feature so why is it taking so long to implement", which I've seen happen **a lot** in crowdfunded software. The bottom line is (at least personally for me, since I live in a VHCOL area) $100 or even $1000 may be nowhere close to enabling me to work full-time on implementing the hypotethetical feature in the desired timeline, considering how complex and varied the requirements can be.

**Comment by pktiuk** [comment]
> I'm a bit wary / concerned about potential comments like "I donated $100 for this feature so why is it taking so long to implement", which I've seen happen a lot in crowdfunded software.

Polar has clear rules. Nothing is guaranteed, when you donate. And if an issue is not solved during a defined period of time (6 months maybe) you can just get a refund.

**Comment by pktiuk** [comment]
> I've many motivations of working on this project but money isn't one of them (this is also the reason I've never asked for sponsorship directly).

I understand you. I have similar motivation with my projects. I don't want a money, but I would use a help of some external contributors.

**Comment by pktiuk** [comment]
@pulsejet    
FYI, I just integrated polar with my repo: https://github.com/AntiMicroX/antimicrox    
And I really like the way it works. 

By default, you should mark in some way the issues which you allow to be sponsored  (by label `Funding` for example). And then the Polar bot applies a customized note at the bottom of the selected issue. You can also set     
You can check example issue here: `https://github.com/AntiMicroX/antimicrox/issues/648`.
