### ISSUE TITLE
Test versions are no longer available for Nextcloud 25

### ISSUE THREAD

**Issue by EVOTk** [pulsejet/memories#189]
Hello,

While 4.7.0.alpha.7 was available in the test channel for nextcloud 25, there is now nothing. Only for NC24 and below.

![image](https://user-images.githubusercontent.com/45015615/201488323-ec8fcc95-22e6-4aea-bc17-133db0e35707.png)

https://apps.nextcloud.com/apps/memories

Is this normal?

**Comment by pulsejet** [comment]
It's a bug in the app store. Whichever build completes last is the only one shown for nightly :/

**Comment by EVOTk** [comment]
Oh ok, I see! Nothing can be corrected by you so
