### ISSUE TITLE
404 on core/preview images

### ISSUE THREAD

**Issue by fuzunspm** [pulsejet/memories#19]
I'm getting 404 on all preview and original files through Memories. Default Photos app is working fine.

GET https://myserver.com/core/preview?fileId=818340&c=99e5d359a816ba856c2423ab13eb79c5&x=250&y=250&forceIcon=0&a=0 [HTTP/1.1 404 Not Found]

The issue is my server is not https://myserver.com but https://myserver.com/nextcloud

**Comment by pulsejet** [comment]
Thanks for reporting. Should be fixed with v1.0.5
