### ISSUE TITLE
 Command "memories:video-setup" is not defined.  

### ISSUE THREAD

**Issue by Cebrain** [pulsejet/memories#191]
When i try to run "memories:video-setup" i am getting an error.  Command "memories:video-setup" is not defined. 
I cant choose yes because it skips the dialog. I am on latest nextcloud and memories version.

```
docker exec -u www-data nextcloud php occ memories:video-setup
Command "memories:video-setup" is not defined.                                 
Do you want to run "memories:index" instead?  (yes/no) [no]:
```

**Comment by pulsejet** [comment]
What version are you on? Transcoding is available only on the alpha channel right now (should be stable soon)

**Comment by Cebrain** [comment]
Oh, i didnt know. I found this information in the documentation, because of that i thought it was already in stable.
I am on stable at the moment, so everything should be fine.

**Comment by pulsejet** [comment]
You were just a few hours early ;)
It's on the stable channel now. Give it a some time for the update to be available (the app store has some caching)
