### ISSUE TITLE
TrueNAS - Nohup "illegal option"

### ISSUE THREAD

**Issue by TtuxX** [pulsejet/memories#198]
Hi there ! :)

I am getting the following little issue with Nohup on TrueNAS (FreeBSD):

```
root@Nextcloud:~ # occ memories:video-setup
nohup: illegal option -- -
```

Best regards

**Comment by pulsejet** [comment]
Hmm. Does freebsd not let you do `nohup --version`?

For now you could fix this by disabling transcoding (I doubt it'll be usable without acceleration anyway). In your `config.php` add
```php
'memories.no_transcode' => true,
```

**Comment by TtuxX** [comment]
I enabled the option as you said but indeed I get `No compatible source was found for this media.` and cannot play videos.

Well, actually ```nohup``` in TrueNAS seems to be more than limited...

```
root@Nextcloud:~ # nohup --version
--version: Command not found.
```
...and the man page is pretty empty regarding arguments possibilities VS FreeBSD...

```
NOHUP(1)                FreeBSD General Commands Manual               NOHUP(1)

NAME
     nohup – invoke a utility immune to hangups

SYNOPSIS
     nohup [--] utility [arguments]

DESCRIPTION
     The nohup utility invokes utility with its arguments and at this time
     sets the signal SIGHUP to be ignored.  If the standard output is a
     terminal, the standard output is appended to the file nohup.out in the
     current directory.  If standard error is a terminal, it is directed to
     the same place as the standard output.

     Some shells may provide a builtin nohup command which is similar or
     identical to this utility.  Consult the builtin(1) manual page.

ENVIRONMENT
     The following variables are utilized by nohup:

     HOME  If the output file nohup.out cannot be created in the current
           directory, the nohup utility uses the directory named by HOME to
           create the file.

     PATH  Used to locate the requested utility if the name contains no ‘/’
           characters.

EXIT STATUS
     The nohup utility exits with one of the following values:

     126     The utility was found, but could not be invoked.

     127     The utility could not be found or an error occurred in nohup.

     Otherwise, the exit status of nohup will be that of utility.

SEE ALSO
     builtin(1), csh(1), signal(3)

STANDARDS
     The nohup utility is expected to be IEEE Std 1003.2 (“POSIX.2”)
     compatible.

BUGS
     Two or more instances of nohup can append to the same file, which makes
     for a confusing output.

FreeBSD 13.1-RELEASE-p2          July 19, 2001         FreeBSD 13.1-RELEASE-p2

```

**Comment by pulsejet** [comment]
> I enabled the option as you said but indeed I get `No compatible source was found for this media.` and cannot play videos.

Where did you get this error? Do the same videos work in the Files app?

**Comment by TtuxX** [comment]
- I get it in the main player, with the following error message in the Console:

`
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. 
Object { code: 4, message: "No compatible source was found for this media." }
memories-main.js:2:4931022
    n https://XXXX.XX/apps/memories/js/memories-main.js?v=e6f7da5b-959:2
    error https://XXXX.XX/apps/memories/js/memories-main.js?v=e6f7da5b-959:2
    error https://XXXX.XX/apps/memories/js/memories-main.js?v=e6f7da5b-959:2
    handleSrc_ https://XXXX.XX/apps/memories/js/memories-main.js?v=e6f7da5b-959:2
    n https://XXXX.XX/apps/memories/js/memories-main.js?v=e6f7da5b-959:2
`

![image](https://user-images.githubusercontent.com/6570830/201878720-d25c2946-653c-46d2-b76e-e5bde1f13acf.png)

- I confirm that the same video works in the Files app.

**Comment by pulsejet** [comment]
Please try with v4.7.2

**Comment by TtuxX** [comment]
It works perfectly fine. Thank you ! :)
