### ISSUE TITLE
4.7.1 not showing meta data in the EXIF tab

### ISSUE THREAD

**Issue by jacotec** [pulsejet/memories#199]
I was pretty excited when I saw the preview of the EXIF view some days ago. In 4.7.1 the EXIF tab is there ... but the EXIF data is missing.

Picture in the Memories view:

![image](https://user-images.githubusercontent.com/3321655/201722661-725232f8-48b4-4d3d-8e24-d4c9a3711495.png)

The same in the folder view:

![image](https://user-images.githubusercontent.com/3321655/201722701-a3113be6-b535-4d27-8a5a-1a11bf17edbe.png)

I re-did an occ memories:index but it told me it had nothing to do ... is this a bug or what's missing?

**Comment by pulsejet** [comment]
`occ memories:index -f`
Notice the `-f` flag

**Comment by pulsejet** [comment]
Btw what resolution is your display? Your sidebar is unexpectedly wide.

**Comment by jacotec** [comment]
> `occ memories:index -f` Notice the `-f` flag

Ah, thanks :-)

Reindex is running. Did I overlook that info somewhere?

**Comment by pulsejet** [comment]
> Reindex is running. Did I overlook that info somewhere?

[Changelog](https://github.com/pulsejet/memories/blob/master/CHANGELOG.md). Nextcloud really needs a way to display changelogs to admins on app update ...

**Comment by jacotec** [comment]
> Btw what resolution is your display? Your sidebar is unexpectedly wide.

1920 x 1200. Grabbed that area with SnagIt, my perfect favourite tool for all kinds of screenshots. Did not size it down. But the size above is pretty exactly the with of the sidebar on my monitor.

**Comment by jacotec** [comment]
> [Changelog](https://github.com/pulsejet/memories/blob/master/CHANGELOG.md). Nextcloud really needs a way to display changelogs to admins on app update ...

Stupidly I had a look in the description in the releases section in Github ... bad habit, but most people put them there. You maybe should mention and link your changelog doc in your readme.md ;-)

**Comment by pulsejet** [comment]
> 1920 x 1200.

Ah then it must be scaling. I run 125% scaling; should re-test UI everything at 100%. The entries are supposed to be more centered than that.

**Comment by jacotec** [comment]
> > 1920 x 1200.
> 
> Ah then it must be scaling. I run 125% scaling; should re-test UI everything at 100%. The entries are supposed to be more centered than that. #200

I have scaling set to 100%

**Comment by pulsejet** [comment]
> > [Changelog](https://github.com/pulsejet/memories/blob/master/CHANGELOG.md). Nextcloud really needs a way to display changelogs to admins on app update ...
> 
> Stupidly I had a look in the description in the releases section in Github ... bad habit, but most people put them there. You maybe should mention and link your changelog doc in your readme.md ;-)

Yeah I was just being lazy. Adding it to readme does seem like a good idea.

**Comment by pulsejet** [comment]
@jacotec does metadata work after index?

**Comment by pulsejet** [comment]
Reopen if issue persists

**Comment by meichthys** [comment]
> [Changelog](https://github.com/pulsejet/memories/blob/master/CHANGELOG.md). Nextcloud really needs a way to display changelogs to admins on app update ...

I'm not sure if this is what you're referring to, but most apps have a changelog tab that can be viewed on the apps page. I don't see it for memories though:
![image](https://user-images.githubusercontent.com/10717998/202202141-4e580041-6487-4306-9d92-3f943a8bb04d.png)

![image](https://user-images.githubusercontent.com/10717998/202202332-bd32adec-806a-461f-bf6b-3b0e7e4f61f5.png)

Also, it would probably be nice to put up a better cover photo like the one on the readme: https://github.com/pulsejet/memories/raw/master/appinfo/screenshot.jpg

**Comment by jacotec** [comment]
> @jacotec does metadata work after index?

@pulsejet Yap, sorry for the late reply. All fine after `memories:index -f`

**Comment by meichthys** [comment]
@pulsejet Yes, the app store shows the nice cover photo, but my instance does not even after clearing cache. If it shows for others, then it must be a reddis caching issue on my end 👍
