### ISSUE TITLE
Thank you for improving NC's Photos experience

### ISSUE THREAD

**Issue by TtuxX** [pulsejet/memories#20]
Hi there Varun,

Just wanted to drop a big "thank you" for improving Nextcloud Photos app and making it more "usable" (even if your app does not have dozen of features yet).

I have been using the Photos app for many years (ownCloud user since version 4 and continued later on following Nextcloud) and user experience of the Photo app has never been really great to me. Furthermore, its development has always been kind of slow.

I don't know yet how great to use your app will be in the future, but thank you for creating this new project! :)

Best regards

**Comment by pulsejet** [comment]
Great to hear that it is useful to you! I'm hoping for more integration with other apps if this gains more traction, e.g. parsing the location data together with the date/time for maps etc.
