### ISSUE TITLE
Video playback in timeline not working with external folder

### ISSUE THREAD

**Issue by keesfluitman** [pulsejet/memories#205]
At first my server was really busy after giving the command for video setup. After that, it almost instantly gave a [Object] [object] response and video playback isn't working.

Log:
`{"reqId":"ylwRhPwRX9ovGR56yVP7","level":0,"time":"2022-11-15T19:36:09+00:00","remoteAddr":"#REMOTEADDRESS","user":"#USER","app":"occweb","method":"POST","url":"/apps/occweb/cmd","message":"memories:video-setup","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36","version":"25.0.1.1","data":{"app":"occweb"}}`

`{"reqId":"ylwRhPwRX9ovGR56yVP7","level":3,"time":"2022-11-15T19:36:09+00:00","remoteAddr":"#REMOTEADDRESS","user":"#USER","app":"index","method":"POST","url":"/apps/occweb/cmd","message":"trim(): Argument #1 ($string) must be of type string, bool given in file '/config/www/nextcloud/apps/memories/lib/Command/VideoSetup.php' line 122","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36","version":"25.0.1.1","exception":{"Exception":"Exception","Message":"trim(): Argument #1 ($string) must be of type string, bool given in file '/config/www/nextcloud/apps/memories/lib/Command/VideoSetup.php' line 122","Code":0,"Trace":[{"file":"/config/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/config/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/config/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"TypeError","Message":"trim(): Argument #1 ($string) must be of type string, bool given","Code":0,"Trace":[{"file":"/config/www/nextcloud/apps/memories/lib/Command/VideoSetup.php","line":122,"function":"trim"},{"file":"/config/www/nextcloud/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OCA\\Memories\\Command\\VideoSetup","type":"->"},{"file":"/config/www/nextcloud/3rdparty/symfony/console/Application.php","line":1009,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/config/www/nextcloud/3rdparty/symfony/console/Application.php","line":273,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/config/www/nextcloud/3rdparty/symfony/console/Application.php","line":149,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/config/www/nextcloud/lib/private/Console/Application.php","line":213,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/config/www/nextcloud/apps/occweb/lib/Controller/OccController.php","line":59,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/config/www/nextcloud/apps/occweb/lib/Controller/OccController.php","line":75,"function":"run","class":"OCA\\OCCWeb\\Controller\\OccController","type":"->"},{"file":"/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"cmd","class":"OCA\\OCCWeb\\Controller\\OccController","type":"->"},{"file":"/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/config/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/config/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/config/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/config/www/nextcloud/apps/memories/lib/Command/VideoSetup.php","Line":122},"CustomMessage":"--"}}`

**Comment by keesfluitman** [comment]
sorry. it works fine from console (i did it from inside the web browser OCC app on my nextcloud webpage). Just can't enable transcoding, because it's too cpu heavy.
You can close this.

**Comment by pulsejet** [comment]
Are you on v4.7.2? There's a bug in previous versions that won't let you play without transcoding enabled.

**Comment by keesfluitman** [comment]
I'm on v4.7.2
Is there a way to reset to the initial setup as a user? Maybe that would help.
Because it is working for my other users, that have the videos in their respective Folders that aren't Folders imported with the external storage App.
I noticed also that in Settings in-App.
Timeline Path: /Pictures
Folders Path: //Pictures
So somehow it has only 1 forward Slash?
On my other user's App it says:
Timeline Path: //Photos
Folders Path: /

In Debug mode. The difference is, it does show the .mp4 file in the logs (nextcloud.log) if I play it from the 1 User. But it doesn't when played from the other, so something must be going wrong before that. 
I cleared my cache.
The only things that come are couple of folders with the message: "/appinfo/app.php is deprecated,
But I'd like to see if I can reset the whole setup for my user, is that possible? Or can I manually change the Timeline Path?

Lol.
I thought, last try. I changed the Timeline Path to a different one (a subfolder) and back to the Original Folder. And it just works.

**Comment by pulsejet** [comment]
Transcoding doesn't work with external storage. From the wiki:
> If you use external storage, transcoding might be very slow or not work at all. In this case, run setup again to disable it.

The random behavior is expected, since Nextcloud deletes the temp video file during transcoding.

> So somehow it has only 1 forward Slash?

This shouldn't be an issue. One or two slashes are equivalent.

**Comment by keesfluitman** [comment]
> Transcoding doesn't work with external storage. From the wiki:
> 
> > If you use external storage, transcoding might be very slow or not work at all. In this case, run setup again to disable it.
> 
> The random behavior is expected, since Nextcloud deletes the temp video file during transcoding.
> 
> > So somehow it has only 1 forward Slash?
> 
> This shouldn't be an issue. One or two slashes are equivalent.

Transcoding is already disabled. This is direct play.

**Comment by pulsejet** [comment]
Now I'm confused 😄 

1. Transcoding is diabled.
2. Does video well in Files app?
3. Does the same video not play in Memories?
4. If 2 and 3 are true, is there anything in browser JS console logs?

**Comment by keesfluitman** [comment]
2 & 3 is true. But only when Timeline Path is set to /Pictures
When it's set to /Pictures/Sub-Folder it plays in Memories Timeline too. (so no problem)
From memories-folder it always works.

Error is the same as shown when clicking a video.
memories-main.js?v=a101f9cd-14:2 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. jY {code: 4, message: 'No compatible source was found for this media.'}

So is there no way to reset all settings and do a clean setup?

**Comment by pulsejet** [comment]
> Error is the same as shown when clicking a video. memories-main.js?v=a101f9cd-14:2 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. jY {code: 4, message: 'No compatible source was found for this media.'}

By any chance is this an mkv or mov file? There's a hack I just put in that probably fix these.
Also are you on Firefox?

> So is there no way to reset all settings and do a clean setup, just uninstalling does not work. It saves the indeces/paths somewhere else.

There's nothing to "reset" really. You can clear the index by truncating the `oc_memories` table, but that won't make any difference to video playback.

**Comment by keesfluitman** [comment]
It's mp4. I tested on both firefox and chrome. The weird thing is, that it does work when i change to a subfolder within the pictures folder. 
I thought maybe with a fresh start it'd be able to reindex. Just to be sure. Ill try truncating the db

**Comment by pulsejet** [comment]
I see. I'd hold off to test with the next release for now. The way 4.7.2 loads non-transcoded videos is pretty much _wrong_ even it it mostly works. That might lead to unexpected results ...

**Comment by keesfluitman** [comment]
Ok. Ill wait. It's working for my other users and i dont necessarily need it yet anyway. Ill send a small donation. Nice work man.

**Comment by pulsejet** [comment]
Thank you!

**Comment by pulsejet** [comment]
Closing, fixed in v4.8.0.
