### ISSUE TITLE
After Update to 4.7.2, NC logs spaming by Error: OCA\Memories\Controller\DaysController 

### ISSUE THREAD

**Issue by EVOTk** [pulsejet/memories#207]
Hello,
After Update to 4.7.2, NC logs spaming by Error: OCA\Memories\Controller\DaysController 

I sometimes had thumbnails that didn't load the first time but otherwise, I didn't see anything special, Memories seems to work normally.

![image](https://user-images.githubusercontent.com/45015615/202034961-6a6d9a55-0896-490e-80b4-30fae3759111.png)

```
Error: OCA\Memories\Controller\DaysController::OCA\Memories\Controller\{closure}(): Argument #1 ($node) must be passed by reference, value given at /config/www/nextcloud/apps/memories/lib/Controller/FoldersTrait.php#45
    <<closure>>
    OC\Log\ErrorHandler::onError()
    /config/www/nextcloud/apps/memories/lib/Controller/FoldersTrait.php - line 45:
    array_map()
    /config/www/nextcloud/apps/memories/lib/Controller/DaysController.php - line 78:
    OCA\Memories\Controller\DaysController->getSubfoldersEntry()
    /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:
    OCA\Memories\Controller\DaysController->days()
    /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:
    OC\AppFramework\Http\Dispatcher->executeController()
    /config/www/nextcloud/lib/private/AppFramework/App.php - line 172:
    OC\AppFramework\Http\Dispatcher->dispatch()
    /config/www/nextcloud/lib/private/Route/Router.php - line 298:
    OC\AppFramework\App::main()
    /config/www/nextcloud/lib/base.php - line 1047:
    OC\Route\Router->match()
    /config/www/nextcloud/index.php - line 36:
    OC::handleRequest()
```

**Comment by EVOTk** [comment]
Mmmmm, I remember being in the Settings after the update. 

Also I remembered that in "Folder Path", there was no nothing but "/" but I can't put it back, do you think this is the cause?

![image](https://user-images.githubusercontent.com/45015615/202036474-2cbf113c-0059-4e25-9b27-30917ceb0637.png)

**Comment by EVOTk** [comment]
Hello,
I'm resolve manually : 

Before :
![image](https://user-images.githubusercontent.com/45015615/202041696-02d2c47d-94eb-45a6-b53d-50ae39a403df.png)
After : 
![image](https://user-images.githubusercontent.com/45015615/202041757-bfd29402-6422-4f64-a4e6-8f4a0c709448.png)

and it works as before, and I have no more errors in the NC logs! So there was this "/" before. I had to "break" it when I opened the settings.

However, I'm not sure I understand the difference between "Folder Path" and "Timeline Path".

Can you give me a use case? Because I think I'm not using it correctly.

**Comment by pulsejet** [comment]
> However, I'm not sure I understand the difference between "Folder Path" and "Timeline Path".
> 
> Can you give me a use case? Because I think I'm not using it correctly.

#85. The folder path is the root for your "Folders" tab. Timeline path is the root for the "Timeline" and everything else.
