### ISSUE TITLE
People only work when local storage set as root for timeline

### ISSUE THREAD

**Issue by gymnae** [pulsejet/memories#209]
I am uncertain if this is working as intended or a bug. I'm using a local folder as external storage, which is powered behind the scenes by rclone mounting an SFTP share. 
If a folder in an external storage is selected as root for the timeline, the faces sections remain empty. As soon as I switch to a local storage, it shows clusters again.

Interestingly, memories appears to pick up on face clusters which I have just deleted by resetting recognize.

**Comment by pulsejet** [comment]
There are two possibilities:
1. Memories will show clusters only for faces with photos in your timeline path. So these need to be recognized already.
2. The timeline path needs to be a *single storage* (this limitation is removed in v4.8). So you cannot set the path to a folder containing another mounted storage.
