### ISSUE TITLE
Error when run memories:index

### ISSUE THREAD

**Issue by aerir** [pulsejet/memories#21]
Following error thrown when I tried to run memories:index with www-data 

> FATAL: An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "fileid" does not exist
LINE 1: SELECT "fileid", "mtime"

Running latest Memories, Nextcloud 24.04, PHP 8.1.2, Postgresql 14.4

**Comment by pulsejet** [comment]
Your migrations don't seem to have run. Does the app open in the UI?

**Comment by aerir** [comment]
Yes I did, it was at v0.01. Before the PSQL support?

**Comment by pulsejet** [comment]
In that case you need to drop the `oc_memories` table manually and re-run the app migration.
https://github.com/pulsejet/memories/commit/829487cac749f351341c22ce1624f70cfcbf6942

**Comment by aerir** [comment]
Thanks, will give it a swing and update you later.

**Comment by vvrein** [comment]
Also met this issue, this helped for me.
```
$ php ./occ app:remove memories
psql> \c nextcloud
psql> DELETE FROM oc_appconfig WHERE appid='memories';
psql> DELETE FROM oc_migrations WHERE app='memories';
psql> drop index memories_path_index;
$ php ./occ app:install memories
```

**Comment by aerir** [comment]
> occ app:install memories

Can confirmed this fixed my issue too. Thanks!
