### ISSUE TITLE
can't start occ memories:index, exiftool fatal error

### ISSUE THREAD

**Issue by KoooDT** [pulsejet/memories#210]
when i run: occ memories:index
getting an error

```
WARN: Failed to create stay_open exiftool process
Exiftool timeout: [/Volume1/@apps/Nextcloud/webui/apps/memories/exiftest.jpg]
Couldn't read Exif data from test file: Could not read from Exiftool
FATAL: exiftool could not be executed or test failed
Make sure you have perl 5 installed in PATH
```

I can't figure out how to fix the error.

**Comment by pulsejet** [comment]
1. What kind of OS / setup is this?
2. As the error message says, do you have perl?

**Comment by KoooDT** [comment]
> 1. What kind of OS / setup is this?
[TOS 5](https://www.terra-master.com/ru/tos5)
I don't know what version of Linux it was built on

> 2. As the error message says, do you have perl?

```
perl -v
This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux
```

There is also another feature. 
If you upload photos using the web interface, all photos appear in the memories. 

Only processing of the current archive does not work

**Comment by pulsejet** [comment]
Okay.
1. Does the `/Volume1/@apps/Nextcloud/webui/apps/memories/exiftest.jpg` file exist?
2. Are there any `memories` options in `config.php`?
3. Does `perl /Volume1/@apps/Nextcloud/webui/apps/memories/exiftool-bin/exiftool/exiftool` work? (check the path exists 
first).
 
I assume you installed throught the app store and `www-data` or equivalent owns the memories directory.

**Comment by KoooDT** [comment]
Yes Nextcloud was installed through the app store

> 1. Does the /Volume1/@apps/Nextcloud/webui/apps/memories/exiftest.jpg file exist?
yes, sure

```
ls -lh /Volume1/@apps/Nextcloud/webui/apps/memories/exiftest.jpg
-rw-r--r-- 1 KoDT KoDT 3.6K Nov 16 20:19 /Volume1/@apps/Nextcloud/webui/apps/memories/exiftest.jpg
```

> 2. Are there any memories options in config.php?
for example, what should be checked? 

> 3. Does perl /Volume1/@apps/Nextcloud/webui/apps/memories/exiftool-bin/exiftool/exiftool work? (check the path exists
first).

yes, there is a path
```
# ls -lh /Volume1/@apps/Nextcloud/webui/apps/memories/exiftool-bin/exiftool/exiftool
-rw-r--r-- 1 KoDT KoDT 305K Nov 16 20:19 /Volume1/@apps/Nextcloud/webui/apps/memories/exiftool-bin/exiftool/exiftool
```

but the command is not working
```
# perl /Volume1/@apps/Nextcloud/webui/apps/memories/exiftool-bin/exiftool/exiftool
Can't locate File/Glob.pm in @INC (you may need to install the File::Glob module) 
(@INC contains: /Volume1/@apps/Nextcloud/webui/apps/memories/exiftool-bin/exiftool/lib /usr/lib/perl5/site_perl/5.26.1/x86_64-linux /usr/lib/perl5/site_perl/5.26.1 /usr/lib/perl5/5.26.1/x86_64-linux /usr/lib/perl5/5.26.1 .) at /Volume1/@apps/Nextcloud/webui/apps/memories/exiftool-bin/exiftool/exiftool line 981.
BEGIN failed--compilation aborted at /Volume1/@apps/Nextcloud/webui/apps/memories/exiftool-bin/exiftool/exiftool line 981.
Undefined subroutine &main::SetWindowTitle called at /Volume1/@apps/Nextcloud/webui/apps/memories/exiftool-bin/exiftool/exiftool line 355.
END failed--call queue aborted at /Volume1/@apps/Nextcloud/webui/apps/memories/exiftool-bin/exiftool/exiftool line 981.

```

**Comment by pulsejet** [comment]
Looks like your perl is broken. Maybe you need to reinstall it / add the missing packages.

**Comment by KoooDT** [comment]
Yes true. 
There is a full version Perl in the app store.
after installation i ran command and it works

```
# /Volume1/@apps/perl/bin/perl /Volume1/@apps/Nextcloud/webui/apps/memories/exiftool-bin/exiftool/exiftool
NAME
    exiftool - Read and write meta information in files

SYNOPSIS
  Reading
    exiftool [*OPTIONS*] [-*TAG*...] [--*TAG*...] *FILE*...
```

PATH variable now contains two references to perl applications..
Can I change the path to the PERL application somewhere in the config file?

**Comment by KoooDT** [comment]
maybe i write specify path to perl in config.php ?

**Comment by KoooDT** [comment]
thank you very much!
I was able to resolve this issue

**Comment by smailpouri** [comment]
Hi, 

I'm having the same issue.

> What kind of OS / setup is this?
Docker 4.14.1 on macOS Ventura 13.0.1 on Apple Macmini M1, linuxserver/nextcloud 

> As the error message says, do you have perl?
How do I check? 
I tried `docker exec -it nextcloud bash` then `perl -v` I get command not found


> Does the /Volume1/@apps/Nextcloud/webui/apps/memories/exiftest.jpg file exist?

Yes

>Are there any memories options in config.php?

I only have this:
```
  'memories.exiftool_no_local' => true,
  'memories.transcoder' => '/config/www/nextcloud/apps/memories/exiftool-bin/go-vod-aarch64',
  'memories.no_transcode' => false,
  'memories.qsv' => false,
```

>Does perl /Volume1/@apps/Nextcloud/webui/apps/memories/exiftool-bin/exiftool/exiftool work? (check the path exists
first).
I assume you installed through the app store and www-data or equivalent owns the memories directory.


memories directory is own by **root**. I have no idea why this version of nextcloud installs all apps as root.
the path is `/config/www/nextcloud/apps/memories/exiftool-bin/exiftool`

From the official nextcloud I could:
`docker exec -it nextcloud bash`
then
`apt-get update` and the name of the package. with this version from **linuxserver/nextcloud** I get **command not found.**

**Comment by pulsejet** [comment]
If the directory is owned by root, there's no way memories can set the executable flag on the binary (unless PHP is also running as root). This seems like a setup issue. A quick fix would be to `chown -R` the memories directory to whatever user PHP is running as, and remove `memories.exiftool_no_local` from the config. Otherwise you need to install perl in the container.

Since `linuxserver/nextcloud` is Alpine, you need to use `apk` instead of `apt-get` (debian only)

**Comment by Luncheon3462** [comment]
@pulsejet if the memories directory is owned by the user 'nextcloud' and group 'www-data' and if photos are located in /home/USERNAME/FOLDER/ will memories throw an error 'failed to index...' in the nextcloud log?
