### ISSUE TITLE
Transcoding: Default config not working without manually adding the ffmpeg paths in the NC config

### ISSUE THREAD

**Issue by jacotec** [pulsejet/memories#212]
After enabling the transcoding with occ memories:video-setup (leaving the QSV off as I don't HW acceleration) and restarting the server as recommended, transcoding always reported "transcoding failed".

I needed to add 'memories.ffmpeg_path' and 'memories.ffprobe_path' manually to the NC config.

ffmpeg path is standard (/usr/bin/ffmpeg and /usr/bin/ffprobe). System is Ubuntu 20.04 LTS.

Not sure if that's a glitch in the setup procedure ... just mentioning that in my case adding these lines manually was needed to get it working.

**Comment by pulsejet** [comment]
Maybe we need to do explicit detection for some reason. Does `which ffmpeg` return the correct path?

**Comment by jacotec** [comment]
> Does `which ffmpeg` return the correct path?

Yes, it does!
