### ISSUE TITLE
CrowdSec ban me in using Memories (http-crawl-non_statics)

### ISSUE THREAD

**Issue by EVOTk** [pulsejet/memories#218]
Hello,
This was not the case before, but now, regularly, when I go to Memories, then for example to People, then Crowdsec bans me for the reason [http-crawl-non_statics](https://hub.crowdsec.net/author/crowdsecurity/configurations/http-crawl-non_statics)

Do you have any idea why this happens? I didn't have this behavior before, and there was no change in crowdsec

thanks

**Comment by pulsejet** [comment]
We just make a lot of requests for the people tab; that isn't a bug. I never used Crowdsec, but there should be some configuration for the number of allowed requests.

**Comment by EVOTk** [comment]
Thank you for your answer, it's not related to the Memories update but to the increase of my content in Nextcloud/Memories.

ClowdSec does not manage well this large number of requests, with the help of CrowdSec team, for the moment the only "solution" which is a workaround, and not to use CrowdSec for Nextcloud. 

If like me you use SWAG as a reverse proxy, then you can "override" the reverse configuration with `access_log /config/log/nginx/access_nc.log;` for example.

Example :
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name nextcloud.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        # override access_log
        access_log /config/log/nginx/access_nc.log;
        include /config/nginx/resolver.conf;

        set $upstream_app <NC_IP>;
        set $upstream_port <NC_PORT>;
        set $upstream_proto https;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_max_temp_file_size 2048m;
    }

}
```

Don't forget to create the access_nc.log file with `touch config/log/nginx/access_nc.log`

Also if you use Fail2Ban in SWAG, don't forget to include this new log file in `config/fail2ban/jail.local` : 

Example: 
```
[...]

[nginx-http-auth]
enabled  = true
filter   = nginx-http-auth
port     = http,https
logpath  = /config/log/nginx/error.log
           /config/log/nginx/access_nc.log

[...]
```
