### ISSUE TITLE
occ memories:index scanning all files not just photos

### ISSUE THREAD

**Issue by TheWanderer1983** [pulsejet/memories#22]
Hello,

nextcloud 24, memories 1.0.7
I've just installed memories on my dietpi nextcloud install. 
I'm running the following command 
sudo -u www-data /usr/bin/php -f /var/www/nextcloud/occ memories:index

It is scanning all files for each user starting with file directory. I use nextcloud for more much than just photos so It would be great if it just started at  each /<user>/files/Photos and scanned that folder and each subfolder. Can this be done?

**Comment by pulsejet** [comment]
The intention is that all the image/video files _will_ be indexed, even though they might not show up in the timeline since it filters by the path. Unless you have hundreds of thousands of image files in other directories, you don't need to worry about it.

That said it should not be too hard to implement something like this; maybe just supply an option `--only-directory` or recognize `.nomedia` when indexing

**Comment by TheWanderer1983** [comment]
My concern isn't with what will show up but the time it is taking to create the index.
I use these folders for backups of systems also, so it's crawling through large amounts of files and including .directories and taking a long time to run. It would make sense not to waste time scanning folders that I'm not interested in. It would be great If I could tell it to scan only photos and videos directory in nextcloud of each nextcloud user and ignore all other folders.

**Comment by pulsejet** [comment]
I agree it isn't optimal. My thought right now is to restore the check for `.nomedia`, but only for the index command and as an option. Doing that for the post write listener would be more work -- you'd need to check for `.nomedia` in every parent directory.

**Comment by pulsejet** [comment]
With https://github.com/pulsejet/memories/commit/a5e04822ff0a1a7636c947b74c5ee2a52b9cd2ef, folders with `.nomedia` will not be indexed with the indexing command (but they will be indexed later anyway)

**Comment by pulsejet** [comment]
`.nomedia` also works for the hooks now https://github.com/pulsejet/memories/commit/91f329b7b8846a1a74c47b6221d14e6ec890101e.
Closing this. You might want to re-index with `occ memories:index --clear` after adding the `.nomedia` files to the appropriate directories.
