### ISSUE TITLE
German Localisation

### ISSUE THREAD

**Issue by Cryx73** [pulsejet/memories#223]
The App appears as "Erinnerungen" in Nextcloud menu if your Nextcloud/User Account ist set to german. Problem is that the german Word "Erinnerungen" has the same meaning as the english "Reminders" - I wonder if another german word like "Rückblicke" wouldn't be better. And "Erinnerungen" is used by much software things as the german term for Reminders - even on Nextcloud itself in calendar events.
I stumbled over this after I installed the app and was not able to find it by the name "Memories", but then I wonderd why there was an app called "Erinnerungen" with a camera icon. That said, "Erinnerungen" doesn't seem to be very suitable in german...

**Comment by pulsejet** [comment]
Translations are done by the community on transifex. Please feel free to contribute better translations there:
https://www.transifex.com/nextcloud/nextcloud/memories/
