### ISSUE TITLE
go-vod binary not detected

### ISSUE THREAD

**Issue by darguez** [pulsejet/memories#224]
After compiling go-vod in raspbian and copying the file to `/usr/bin`, the `memories:video-setup` still says there is no compatible binary file. I have also added the line `'memories.transcoding' => '/usr/bin/go-vod'` to NC `config.php` without success.

```
$ sudo -u www-data php /var/www/nextcloud/occ memories:video-setup

ffmpeg is installed
ffprobe is installed
Checking for go-vod binary
Compatible go-vod binary not found
You may build go-vod from source
...
```

What am I missing?

**Comment by pulsejet** [comment]
You need
```
'memories.transcoder' => '...',
```

not `transcoding`.

Btw I doubt transcoding will be useful at all on RPi

**Comment by pulsejet** [comment]
Also you don't need to run `video-setup` if you configure an alternative `go-vod` path.

**Comment by darguez** [comment]
Oh, thank you for the clarification, my mistake. So, If I understood well, by setting `memories.transcoder` variable, there is no need to run video-setup. In fact, I get the same message (`Compatible go-vod binary not found`) after fixing the typo, so I guess it doesn't matter.

BTW. Before I read your message I set the path of go-vod manually in `VideoSetup.php`and it worked (and created the correct variable `memories.transcoder` in `config.php`).

I know Raspberry may not be suitable to use with a transcoder, but I just wanted to try.

Thank you for your great app!

**Comment by pulsejet** [comment]
Added a fix which should help `video-setup` when using a custom path for `go-vod`. Hopefully one day rpi has a hardware h264 encoder 🤠
