### ISSUE TITLE
Video Transcoding Issue

### ISSUE THREAD

**Issue by AndreAle94** [pulsejet/memories#225]
Hello,

After enabling video transcoding I'm not able to play videos anymore. In the browser console, I can see that all transcoding requests are failing with http 500 response code.

The `go-vod.log` file contains the following error:
`ffmpeg-error: [swscaler @ 0x7fa13b9010] deprecated pixel format used, make sure you did set range correctly`

I tried with different videos, same error. I'm running Nextcloud on RPi4 with Docker.

FFMpeg:
`ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.3.1 (Alpine 10.3.1_git20211027) 20211027
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-libaom --enable-libopus --enable-libsoxr --enable-libwebp --enable-vaapi --enable-vdpau --enable-vulkan --disable-debug
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100`

---
About transcoding topic, have you already discussed about adding the ability to automatically transcode videos (in background) and just serve them instead of running the transcoding on the fly? I think this could be a good approach for people with cheap HW (like RPis) and lot of storage. Also, it could lighten servers that handle lot of users.

**Comment by pulsejet** [comment]
> The `go-vod.log` file contains the following error: `ffmpeg-error: [swscaler @ 0x7fa13b9010] deprecated pixel format used, make sure you did set range correctly`

This is not an error, just a warning. Maybe transcodes are simply timing out? There's a 5s timeout, and if you're running this on RPi I doubt it'll work. You could try running the command output in `go-vod.log` to see if that is working (probably need to change the output path a bit)

> About transcoding topic, have you already discussed about adding the ability to automatically transcode videos (in background) and just serve them instead of running the transcoding on the fly? I think this could be a good approach for people with cheap HW (like RPis) and lot of storage. Also, it could lighten servers that handle lot of users.

This is somewhat complicated (but do file a separate issue for it). Basically we need to decide _where_ to store the transcoded videos. Same directory? Preset directory? What happens when you delete the source video? Do we store just one quality or multiple? Different setups may have very diverse requirements.

**Comment by meichthys** [comment]
I'm also seeing something similar when trying to play videos:
GET `https://nextcloud.mydomain.com/apps/memories/api/video/transcode/slpkjhwpaj00/559980/360p-000000.ts` failed with 500
![image](https://user-images.githubusercontent.com/10717998/203141153-0eab367b-25de-43e3-ba31-3c26d7405656.png)

**Comment by pulsejet** [comment]
`/tmp/go-vod.log`

**Comment by AndreAle94** [comment]
First of all, thanks for the response. I just checked again with a different video file, in the browser console I can see the following failed request:

`GET https://<host>/apps/memories/api/video/transcode/m2sonh01jqh0/201372/720p-000000.ts`
with json body: `{"message":"Transcode failed"}`

Looking at `go-vod.log` I can see the following trace:

```
2022/11/21 19:23:35 m2sonh01jqh0-720p: /usr/bin/ffmpeg -loglevel warning -autorotate 0 -i <file-path> -copyts -vf scale=-2:720 -maxrate 2200000 -bufsize 4400000 -c:v libx264 -profile:v high -preset faster -level:v 4.0 -crf 24 -c:a aac -b:a 128k -avoid_negative_ts disabled -f hls -hls_time 3 -force_key_frames expr:gte(t,n_forced*3) -hls_segment_type mpegts -start_number 0 -hls_segment_filename /tmp/go-vod/m2sonh01jqh0-2409251266/720p-%06d.ts -
2022/11/21 19:23:35 ffmpeg-error: [swscaler @ 0x7f7eb91020] deprecated pixel format used, make sure you did set range correctly
2022/11/21 19:23:45 m2sonh01jqh0-720p: recv 720p-000000.ts
2022/11/21 19:23:53 m2sonh01jqh0-720p: recv 720p-000001.ts
2022/11/21 19:24:00 m2sonh01jqh0-720p: recv 720p-000002.ts
2022/11/21 19:24:07 m2sonh01jqh0-720p: recv 720p-000003.ts
2022/11/21 19:24:14 m2sonh01jqh0-720p: recv 720p-000004.ts
2022/11/21 19:24:16 m2sonh01jqh0-720p: recv 720p-000005.ts
```

After closing the viewer and reopening it with the same video, the stream started. It's probably related to the 5s timeout you have mentioned. Could you consider making it configurable?

**Comment by meichthys** [comment]
I'm seeing the following in `go-vod.log`:
```
2022/11/21 14:26:57 y93hy0cqhvc0: new manager for /mnt/ncdata/user/files/Photos/22-11-17 09-59-10 9750.mov
2022/11/21 14:26:57 y93hy0cqhvc0: destroying manager
2022/11/21 14:26:57 y93hy0cqhvc0-1080p: stopping stream
2022/11/21 14:26:57 y93hy0cqhvc0-480p: stopping stream
2022/11/21 14:26:57 y93hy0cqhvc0-720p: stopping stream
2022/11/21 14:26:57 y93hy0cqhvc0-1440p: stopping stream
2022/11/21 14:26:57 y93hy0cqhvc0-max: stopping stream
2022/11/21 14:26:57 y93hy0cqhvc0-2160p: stopping stream
2022/11/21 14:26:57 y93hy0cqhvc0-360p: stopping stream
2022/11/21 14:26:58 y93hy0cqhvc0: new manager for /mnt/ncdata/user/files/Photos/22-11-17 18-15-18 9751.mov
2022/11/21 14:26:58 y93hy0cqhvc0: destroying manager
2022/11/21 14:26:58 y93hy0cqhvc0-480p: stopping stream
2022/11/21 14:26:58 y93hy0cqhvc0-360p: stopping stream
2022/11/21 14:26:58 y93hy0cqhvc0-720p: stopping stream
2022/11/21 14:26:58 y93hy0cqhvc0-1080p: stopping stream
2022/11/21 14:26:58 y93hy0cqhvc0-max: stopping stream
2022/11/21 14:26:59 y93hy0cqhvc0-360p: stopping stream
2022/11/21 14:26:59 y93hy0cqhvc0-360p: ffmpeg -loglevel warning -autorotate 0 -i /mnt/ncdata/user/files/Photos/22-11-17 18-15-18 9751.mov -copyts -vf scale=-2:360 -maxrate 383333 -bufsize 766666 -c:v libx264 -profile:v high -preset faster -level:v 4.0 -crf 24 -c:a aac -b:a 64k -avoid_negative_ts disabled -f hls -hls_time 3 -force_key_frames expr:gte(t,n_forced*3) -hls_segment_type mpegts -start_number 0 -hls_segment_filename /tmp/go-vod/y93hy0cqhvc0-4278296809/360p-%06d.ts -
2022/11/21 14:26:59 ffmpeg-error: x264 [error]: high profile doesn't support a bit depth of 10
2022/11/21 14:26:59 ffmpeg-error: [libx264 @ 0x56476a3fa7c0] Error setting profile high.
2022/11/21 14:26:59 ffmpeg-error: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
2022/11/21 14:26:59 ffmpeg-error: [aac @ 0x56476a426e80] 2 frames left in the queue on closing
```

**Comment by pulsejet** [comment]
@AndreAle94 can you confirm it really is taking 5s to get the first chunk? E.g. just open a terminal at the side when you start the video playback and observe the output.
Basically if it takes >5s to encode the first chunk then live transcoding is going to be pretty useless, since each chunk is 3s to begin with. What kind of hardware is this?

@meichthys seems this is 10-bit HEVC you're transcoding. Could you provide a sample by any chance to be sure? I have a potential fix.

**Comment by pulsejet** [comment]
> @pulsejet here's a sample file. This is an iOS video prior to it being uploaded to Nextcloud, but I don't think next cloud manipulates the file after the upload so it should be the same. https://user-images.githubusercontent.com/10717998/203185869-8fc32cc3-ac00-4259-b68a-c7f4ac0f1778.MOV

Thanks! This transcodes fine with the latest go-vod update, so this should be fixed with v4.8.0

**Comment by meichthys** [comment]
Great news!

**Comment by AndreAle94** [comment]
> @AndreAle94 can you confirm it really is taking 5s to get the first chunk? E.g. just open a terminal at the side when you start the video playback and observe the output. Basically if it takes >5s to encode the first chunk then live transcoding is going to be pretty useless, since each chunk is 3s to begin with. What kind of hardware is this?
> 
Yes, I can confirm it's taking even more. I tried with a different video:
```
2022-11-22 20:35:30.391473576 +0100 720p-000000.ts
2022-11-22 20:35:45.311325143 +0100 720p-000001.ts
2022-11-22 20:35:59.147187460 +0100 720p-000002.ts
2022-11-22 20:36:11.043069056 +0100 720p-000003.ts
2022-11-22 20:36:21.914960824 +0100 720p-000004.ts
```
It's generating a new chunk every 10-15 seconds, definitely not fast enough for a realtime transcoding. I'm on a RPi4 and honestly I was expecting a similar performance. I think the only solution in this case is to pre-transcode all the videos and just serve the files instead of doing it on the fly.

**Comment by pulsejet** [comment]
Yeah, RPi is no-go for realtime transcoding (CPU just isn't enough in general). With 4.8, the timeout is 10s, so you might be able to transcode here and there but it's not gonna be usable.

As for pre-transcoding, you can open a separate feature request for that.
