### ISSUE TITLE
Clarify delete action when removing photos from person

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#229]
Currently, when removing photos from a person, it is not clear if you are deleting a photo entirely, or if you are just deleting the photo from the person (i.e removing the photo from the person).

Currently:
![image](https://user-images.githubusercontent.com/10717998/203195644-187b1bc7-863f-4b50-b731-8f5928eec907.png)

Perhaps we could have a different icon and/or a different tool-tip like "Remove from Person"
![image](https://user-images.githubusercontent.com/10717998/203195911-006e7bb7-853e-49f7-b47f-ea4ff4e9b5eb.png)

**Comment by pulsejet** [comment]
That _is_ the delete button, which deletes the photo altogether.
![image](https://user-images.githubusercontent.com/10709794/203196273-3e6b2c6d-9f91-4dd5-b139-4923e5200af0.png)
