### ISSUE TITLE
Console errors when playing videos

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#235]
I hope you don't mind me spamming issues. I'm just trying to be helpful!

I notice the following errors when playing videos:

```
Security Error: Content at https://nextcloud.mydomain.com/apps/memories/ may not load data from blob:https://nextcloud.mydomain.com/a169cc72-c30a-4bac-87f8-897bfd675845.
Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request. 
```

The video playback seems to work fine, but I wasn't sure if this is normal. Please feel free to close the issue if this is insignificant.

**Comment by pulsejet** [comment]
> I hope you don't mind me spamming issues. I'm just trying to be helpful!

It is helpful. Please don't stop :D

> I notice the following errors when playing videos:
> 
> ```
> Security Error: Content at https://nextcloud.mydomain.com/apps/memories/ may not load data from blob:https://nextcloud.mydomain.com/a169cc72-c30a-4bac-87f8-897bfd675845.
> Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request. 
> ```
> 
> The video playback seems to work fine, but I wasn't sure if this is normal. Please feel free to close the issue if this is insignificant.

I noticed this too, weird cause blob is allowed in the CSP. Let's keep this open.

**Comment by pulsejet** [comment]
This should _finally_ be fixed now.
