### ISSUE TITLE
Share icon not visible in Firefox and not usable in Safari (iOS)

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#236]
I'm assuming this has something to do with Safari having better OS integration, but i noticed that in Safari on MacOS, there is a nice 'Share' icon in the viewer which provides native MacOS share options:

<img width="268" alt="Screen Shot 2022-11-22 at 10 07 43 PM" src="https://user-images.githubusercontent.com/10717998/203462223-4ff5c29f-cd57-4aa9-aa82-f551cad8cefb.png">

Firefox doesn't display that share icon, while iOS Safari does display it but it is not clickable.

**Comment by pulsejet** [comment]
Firefox doesn't support the share API at all: https://caniuse.com/?search=navigator.share
Unfortunately there's nothing that can be done about this. As for iOS that's a bug but I can't reproduce it (sharing works for me).

**Comment by meichthys** [comment]
Ok thanks. Safari is working after a logout. Probably since cashing thing with Nextcloud.
