### ISSUE TITLE
View in Folder option often stalls Nextcloud

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#237]
With a library of about 10,000 photos, if i use the "View in Folder" menu option from the viewer, Nextcloud will basically halt. 
I'm fairly confident this isn't a Memories issue, and rather a Nextcloud Files issue (I think they recommend no more than 5k files in a directory). 

I'm not sure if there's a different way to display the file without having Nextcloud try to list the entire directory of photos, which inevitably will tax the system severely.

**Comment by pulsejet** [comment]
#173

**Comment by meichthys** [comment]
Yes look like a dupe. Adding the path to exif would be a nice alternative 👍
