### ISSUE TITLE
Index error with 4.8.1

### ISSUE THREAD

**Issue by HyCore** [pulsejet/memories#238]
Getting "Exiftool may have crashed" for film and big video file.
Doesn't know yet what will be the consequences.
![image](https://user-images.githubusercontent.com/48274082/203501839-bf99d54e-d631-4d20-a9b1-83bfedae97b3.png)

**Comment by HyCore** [comment]
oh, now it complelty crashed:
![image](https://user-images.githubusercontent.com/48274082/203506381-f3741098-7fad-4361-a1e1-bde29f00bbb2.png)

**Comment by pulsejet** [comment]
1. There's a timeout, which you're hitting in the first post. Should make that configurable.
2. The second one seems a bug introduced by #221. I should have paid more attention to this.
3. If you want to prevent indexing a directory, the best way is to add a `.nomedia` file in it.

**Comment by pulsejet** [comment]
At least the crash should be fixed with v4.8.2

**Comment by kotjarka** [comment]
After enabling reverse geocoding, trying to run `occ memories:index -f ` command, but it is soo slooow (after 16h running it reports 55%) and reports multiple exiftools crashes: 
`ERROR: Exiftool may have crashed, restarting process  [file]`
As a result i have now 1131 zombie processes.

Photo dir is outside of /nextcloud dir, but on the same storage (not remote).
Memories 4.11.0, Nextcloud Hub 3 (25.0.3)
