### ISSUE TITLE
Opening Memories overloaded my server

### ISSUE THREAD

**Issue by Christoph-Wagner** [pulsejet/memories#239]
As requested, an issue ;)

NC Version: Nextcloud Hub 3 25.0.1  
System:
Operating System: Linux 6.0.9-arch1-1 x86_64  
CPU: AMD EPYC 7401P 24-Core Processor (1 core)  
Memory: 1.93 GB  
Database: PostgreSQL 14.5 
PHP: 8.1.12

After installing memories and selecting my InstantUpload folder (5.6 GB of images), I ran `sudo occ memories:index`. After that was done, I continued. The first thing I saw was that the page was loading slowly, it took maybe a minute for the "Last year" thumb to show up. Then I clicked on an image and nothing happened. I checked the server logs via SSH, but my commands didn’t show up… until about 20 seconds later. Trying a reboot resulted in `Call to Reboot failed: Connection timed out`, and I finally managed to restart it with the serial console from my VPS provider.

Netdata monitoring showed high everything (100% CPU, high memory, high I/O), but I don’t know if it was from the crash or indexing.

The journal for php-fpm has 

> Nov 23 05:56:05 servername php-fpm[34766]: [WARNING] [pool nextcloud] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 32 children, there are 0 idle, and 13 total children

Repeating every second until `17 total children` which is when the reboot happened.

**Comment by pulsejet** [comment]
Thanks for filing the issue!

This most likely has to do with thumbnail generation. You can confirm this by checking if the high CPU usage is caused by `php-fpm` and not `postgres`. If you're spawning a lot of processes for thumbs, it will likely freeze up any server with 1 core.

The solution is to pre-generate previews: https://github.com/nextcloud/previewgenerator

**Comment by Christoph-Wagner** [comment]
Great tip, thanks. The chart looked similar: 
![image](https://user-images.githubusercontent.com/1609329/203716506-cf83f1d9-f27a-4ea4-893c-e64cd48cc5b6.png)

The difference is, that it did not take down my server, maybe memories is generating those previews more aggressively, might be worth having some sanity check (cores == 1) to lower the amount of processes or something. But that makes more sense to have tracked in a different issue if you are interested in it. I’m pretty happy, memories is now very smooth and much nicer than the NC Photo app :)

**Comment by pulsejet** [comment]
Great to know it works now!

> The difference is, that it did not take down my server, maybe memories is generating those previews more aggressively, might be worth having some sanity check (cores == 1) to lower the amount of processes or something.

Memories doesn't generate the previews, Nextcloud does. But even Nextcloud doens't have any control on the number of threads; this is just a misconfiguration. https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#tune-php-fpm

**Comment by Christoph-Wagner** [comment]
But then I wonder why I did not have the same issue with the nextcloud photo app? I’ve had crashes before (which I guess are explained now), but always just php-fpm going down, not the whole server.

**Comment by pulsejet** [comment]
I don't really know, but my best guess is
1. Memories might just be showing more in one view (note it also needs to preload things outside what you see)
2. The're just new photos for which previews weren't generated, and this wasn't the case for Photos.

Either way the correct solution is to use preview generator. Generating previews on the fly is going to be slow.
