### ISSUE TITLE
Broken albums with Photos v2.2.0

### ISSUE THREAD

**Issue by pulsejet** [pulsejet/memories#240]
Unfortunate, really
https://github.com/nextcloud/photos/commit/20e3e61ad577014e5f092a292c90a8476f630355

**Comment by Gymnae** [comment]
Maybe your app is getting too popular, seeing also their tagline for the photos app

**Comment by pulsejet** [comment]
Didn't notice that LMAO

**Comment by pulsejet** [comment]
https://github.com/pulsejet/memories/commit/7458478f937e1a8abc59c82ecb9dc998ba04d71c
