### ISSUE TITLE
Videos not showing up on timeline or in the Videos section

### ISSUE THREAD

**Issue by FabianGabor** [pulsejet/memories#241]
I have many videos however only a single one shows up in the Timeline and the Videos section. The rest of the videos only show up in the Folders section. All video files are playable in Nextcloud when viewed in Files or Photos.

![memories-videos-folder](https://user-images.githubusercontent.com/1741703/203565120-6f36b1d4-7b88-4298-a209-dc16328999ad.jpg)
![memories-videos-section](https://user-images.githubusercontent.com/1741703/203565139-bcfe23ee-4264-4be2-a555-9ac0b1bfb1c1.jpg)

This is the only video that shows up:
![video-that-shows-up](https://user-images.githubusercontent.com/1741703/203565155-bc6d049a-a9dc-4d31-8ccb-86596fbfeabf.jpg)

**Comment by pulsejet** [comment]
> All video files are playable in Nextcloud when viewed in Files or Photos.

1. Are they playable in Memories through the folders view? That's the important part
2. Can you provide a sample video for which this happens?

**Comment by FabianGabor** [comment]
1. Yes, they are playable.
2. Sample: https://user-images.githubusercontent.com/1741703/203612863-87c16cba-0603-4356-8f75-49a3e4a0e80c.mp4
3. Timeline path was empty. Only Folders Path was set. Setting timeline paths fixes the issue.

I think the first time setup should have set the timeline path as well but I don't remember seeing that option.

**Comment by pulsejet** [comment]
> 3. Timeline path was empty. Only Folders Path was set. Setting timeline paths fixes the issue.
> 
> I think the first time setup should have set the timeline path as well but I don't remember seeing that option.

This keeps getting stranger. Did you not get the welcome screen where you select the timeline root? That's essentially selecting the timeline path.

**Comment by FabianGabor** [comment]
I did get a setup screen to configure a path and I'm pretty sure it was only the Folders Path so that's why it was the only one set. I also ran the indexer as it was recommended.

**Comment by pulsejet** [comment]
Closing as it's unclear what needs fixing
