### ISSUE TITLE
Edit Button does not work in within memories

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [pulsejet/memories#242]
![image](https://user-images.githubusercontent.com/17781278/203573197-2f75b4a6-84d7-4ace-91dd-e167a7cddc63.png)

Outside of memories it works though.
NC: 25.0.1
Memories: 4.8.1

**Comment by pulsejet** [comment]
That's no information to work with. You've to figure out what's wrong with the path in the error and report back.

**Comment by MrLoverLoverMMMM** [comment]
I can certainly understand that.
However, unfortunately, the error appears only in the interface and not in the logs in the backend. However, I was able to find something in the browser console. Hopefully this helps.
![image](https://user-images.githubusercontent.com/17781278/203700759-69b1e910-734d-4533-bbd1-1dba71a8cf8d.png)

![image](https://user-images.githubusercontent.com/17781278/203700892-af6e24bf-9517-4d94-9dc1-2de6433b9843.png)


Domain and username are blacked out. Username and Domain only lowercase letters without numbers and specials.

**Comment by MrLoverLoverMMMM** [comment]
Path of the file in nextcloud:

/talk/filename...

**Comment by pulsejet** [comment]
I see, thanks for debugging this further. Is this e.g. shared storage or something. Basically this call is just getting the file, but the 404 error indicates it cannot be found.

**Comment by MrLoverLoverMMMM** [comment]
yes. It works at all apps, just not ant memories.
I can also open it at webdav. Seems though that your app is making 1 slash too much (...//Talk/..).
If i Change the path manually from https://www.blackout.at/nextcloud/remote.php/dav/files/blackout//Talk/20221123_152811.png to https://www.blackout.at/nextcloud/remote.php/dav/files/blackout/Talk/20221123_152811.png it works.
+ yes the files are all local, no external storage.

**Comment by pulsejet** [comment]
That is very unexpected. Double slashes don't cause a problem for me. Does opening the URL with double slash give a 404 in the browser? Also what browser is this?

**Comment by pulsejet** [comment]
You can try applying the linked patch https://github.com/pulsejet/memories/commit/4a80d94cb064ee1af0f8898e86debe4941b32967

**Comment by MrLoverLoverMMMM** [comment]
Yes
It does also not work in the browser with 2 slashes.
I use firefox  latest stable on windows and linux.
Can you pack the patch for me?

best regards

Patrick

**Comment by pulsejet** [comment]
Seems like a difference in HTTP server configuration.

You can just apply the patch directly (or wait for the next release). In `apps/memories`,
```
curl https://github.com/pulsejet/memories/commit/4a80d94cb064ee1af0f8898e86debe4941b32967.patch | patch -p1
```

**Comment by MrLoverLoverMMMM** [comment]
perfect, thanks :)

**Comment by stelioskat** [comment]
I am having a similar issue, although it is not due to the double slash path.

I noticed that going to `http://<path-to-nextcloud>/remote.php/dav/` redirects me to the dashboard. So I assume that is the problem, however I have no clue why this happens. Any suggestions? Thank you in advance

**Comment by pulsejet** [comment]
> I noticed that going to http://<path-to-nextcloud>/remote.php/dav/ redirects me to the dashboard.

Definitely indicates something is wrong with your Nextcloud instance configuration (not related to memories). Maybe an incorrect htaccess / nginx configuration. Try setting debug to true in `config.php`

**Comment by MrLoverLoverMMMM** [comment]
I use not nginx, I have apach2 and htaccess is correct.
Your patch was working.
When its gonna be released?

**Comment by stelioskat** [comment]
✅ Solved

For the record, my issue was that `.../index.php/...` was in my path. 
My setup is a bit special, as I am running Nextcloud in Oracle Arm-based Ampere A1 with Podman. 

To remove it I had to ensure that my condig.php included:
`htaccess.RewriteBase' => '/'` (Path depends on your configuration - maybe /nextcloud)

Then I had to update htaccess with the occ command:
`php occ maintenance:update:htaccess`
