### ISSUE TITLE
Add CHANGELOG to release tarballs

### ISSUE THREAD

**Issue by JonOfUs** [pulsejet/memories#244]
Hi there,
thanks for this great app!
Just a small proposal:
If the CHANGELOG.md file is added to the tarball, the Nextcloud appstore extracts the current changes from it and shows them in the app store and on the app install page in Nextcloud instances (screenshot below).
The corresponding documentation can be found [here](https://nextcloudappstore.readthedocs.io/en/latest/developer.html#changelog).

Adding CHANGELOG.md to the copy in bundle.sh should be enough since you already seem to use the keep a changelog syntax.

![image](https://user-images.githubusercontent.com/11487762/203630063-da0ed5fc-5771-4ec5-bd54-704b5bcb474c.png)

**Comment by pulsejet** [comment]
Couldn't find these docs. Thanks!

**Comment by amo13** [comment]
This is still not working for me. The changelog inside the nextcloud apps overview is always empty for memories.

**Comment by pohuing** [comment]
Same thing here. The issue might be the formatting of the version numbers, to cite the docs
> The regex for matching the line is `^## (\d+.\d+.\d+)`, the regex for nightlies is `^## [Unreleased]`
>The version has to be equal to the version in your info.xml. If the parser can’t find a changelog entry, it will be set to an empty string. Only the changelog for the current release will be imported.

That doesn't match our format of `## [v5.5.0] - 2023-10-06` Changing the format to just `## 5.5.0` would presumably allow the changelog to appear for version `5.5.0`.

Another issue is that this project does not release formatted changelogs for patch releases. For example the current release would have to have a changelog entry for version 5.5.3. Memories would have to either carry forward the changelog of the last minor release to every patch release, or start adding entries for every patch release.

**Comment by pohuing** [comment]
Also, I wouldn't blame anyone for getting this wrong. The documentation is in direct contraction with itself. The specified regex does not capture the specified format of "keep a changelog". And as far as I can tell [the code of nextcloud ](https://github.com/nextcloud/appstore/blob/84b720a1260858948028f47b7f5d49e9f9f74b35/nextcloudappstore/api/v1/release/parser.py#L317)also matches neither the specified nor "keep a changelog" . 

This is really baffling and I hope that I'm just misunderstanding something from the docs or the code.

**Comment by pohuing** [comment]
Actually ignore most things I said. The regex of the nextcloud code does match memories' version strings. So I guess it really is all down to the mismatch of the version number in `info.xml` with the numbers in `CHANGELOG.md`

**Comment by pulsejet** [comment]
Wow this is a disaster. I don't know what's the point of filtering out and showing the changelog of only one version. Regardless, let's try to keep the version numbers matching, but I don't this this ever worked either (no clue what's going on)

**Comment by pohuing** [comment]
![image](https://github.com/pulsejet/memories/assets/24683548/ed447012-042e-4b19-8a17-1c8655281e2e)
Ayy that worked 🎉

**Comment by pulsejet** [comment]
Yep. Still,

> I don't know what's the point of filtering out and showing the changelog of only one version.
