### ISSUE TITLE
occ memories:index very slow

### ISSUE THREAD

**Issue by invario** [pulsejet/memories#246]
Hello and first of all, thank you SO much for developing this! The demo looks very promising and I am looking forward to getting it up and running on my NC install.

So I installed the app via the NC app store and proceeded to run "occ memories:index"

It's currently up to 16.64% and I executed the command a good hour ago. I can see it is actively scanning through my files but it just seems very slow. Is this normal?

I have maybe 200-250 GB of images/photos. Not sure how many files exactly... I think around 24,000?

I am on NC 25.0.1 running in a TrueNAS Core 13 jail with FreeBSD 13.1.

Hardware is Ryzen 5 1600AF six core proc (12 threads), 24GB RAM and mirrored 6TB drives. The server's main function is to run NC.

Any input?

Also, I use Preview Generator and have previously generated all the previews in the following sizes:
squareSizes 256 1024
widthSizes 256 1920
heightSizes 256 1920

Thank you!!

**Comment by pulsejet** [comment]
Hi! In general it shouldn't be that slow (takes ~20 mins for 100GB / 25k Photos for me on a Pentium). But since you're running FreeBSD, it's possible you're not running exiftool in `stay_open` mode because of FreeBSD issues, so that'll be very slow. But this is a one time thing; you mostly don't need to run indexing again unless there's some major feature update that requires it.

**Comment by invario** [comment]
Thanks for the reply! Just finished processing.

Checked 81429 files of 7 users in 18031.074 sec
10710 not valid media items
270 .nomedia folders ignored
302 skipped because unmodified
70147 (re-)processed

Yikes. But also hurray to never having to do that again.

**Comment by pulsejet** [comment]
> Thanks for the reply! Just finished processing.
> 
> Checked 81429 files of 7 users in 18031.074 sec 10710 not valid media items 270 .nomedia folders ignored 302 skipped because unmodified 70147 (re-)processed
> 
> Yikes. But also hurray to never having to do that again.

Damn that took a lot of time! Maybe this could be parallelized; I'll think about it. Do keep an eye out for the changelog; as I mentioned sometimes you do need to run index again for bigger feature updates (basically whenever memories can utilize more metadata).

**Comment by invario** [comment]
Will do thanks again.
