### ISSUE TITLE
Segmentation Fault when running occ memories:index

### ISSUE THREAD

**Issue by Binary-System** [pulsejet/memories#247]
System:
Pi4, 2GB (590MB used), booted from USB HDD
Linux 5.15.76-v8+ aarch64

Nextcloud
24.0.5.1 installed via nextcloud pi project

When running 
sudo -u www-data /var/www/nextcloud/occ memories:index

the result is
Segmentation Fault

**Comment by pulsejet** [comment]
That's not enough information to do anything, so you have to debug this more.

**Comment by pulsejet** [comment]
Stale
