### ISSUE TITLE
Issues configuring video settings

### ISSUE THREAD

**Issue by psychobilly2022** [pulsejet/memories#248]
Just wanted to start off by saying that I love this app it is what nextcloud was missing all along. Everything seems to be running like a champ photos load up lightning fast the only problem I was having is that when I click on the video it won't play and it gives me an instruction to run the video set up OCC command. When I run the command it starts off well but it ends in an error which I have posted below. 

robert@nextcloud nextcloud]# sudo -u www-data php occ memories:video-setup
ffmpeg is installed
ffprobe is installed
Checking for go-vod binary
Trying go-vod from /mnt/usb-WDP/var/www/nextcloud/apps/memories/exiftool-bin/go-vod-amd64
go-vod is installed!

You can use transcoding and HLS streaming
This is recommended for better performance, but has implications if
you are using external storage or run Nextcloud on a slow system.

Read the following documentation carefully before continuing:
https://github.com/pulsejet/memories/wiki/Configuration

Do you want to enable transcoding and HLS? [Y/n]
An unhandled exception has been thrown:
TypeError: trim() expects parameter 1 to be string, bool given in /mnt/usb-WDP/var/www/nextcloud/apps/memories/lib/Command/VideoSetup.php:130
Stack trace:
#0 /mnt/usb-WDP/var/www/nextcloud/apps/memories/lib/Command/VideoSetup.php(130): trim()
#1 /mnt/usb-WDP/var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Memories\Command\VideoSetup->execute()
#2 /mnt/usb-WDP/var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#3 /mnt/usb-WDP/var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#4 /mnt/usb-WDP/var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#5 /mnt/usb-WDP/var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#6 /mnt/usb-WDP/var/www/nextcloud/console.php(100): OC\Console\Application->run()
#7 /mnt/usb-WDP/var/www/nextcloud/occ(11): require_once('/mnt/usb-WDP/va...')
#8 {main}

**Comment by pulsejet** [comment]
Docker? You need to use
```
docker exec -it <container> php occ memories:video-setup
```
The `-it` is critical.

**Comment by psychobilly2022** [comment]
Ah yes forgot to include the specs. Not Docker.

Server is:
Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz, 4 cores
16 gb ram
Ubuntu Linux 20.04.5
NextCloud 24.0.7 running off an external usb drive

Sorry if I am missing something this is my first time posting on GitHub let me know if you need any further info and thank you in advance for the help.

**Comment by pulsejet** [comment]
Got it. The issue you're getting basically means PHP can't read from the
console. How exactly are you running the command? Normal SSH?

**Comment by psychobilly2022** [comment]
Ah yes forgot to include the specs. Not Docker.

Server is:
Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz, 4 cores
16 gb ram
Ubuntu Linux 20.04.5
NextCloud 24.0.7 running off an external usb drive

Sorry if I am missing something this is my first time posting on GitHub let me know if you need any further info and thank you in advance for the help.
......

I figured it out.. sorry to waste your time, I decided to ssh directly into the server and the commend ran like a champ. Never had that issue before I've always been able to run and configure all commands from my Webmin console terminal.

**Comment by pulsejet** [comment]
Ah the webmin console. That's asking for trouble 😄
