### ISSUE TITLE
Timeline text slightly cutoff on mobile

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#249]
When viewing the timeline on an iPhone 12 mini, the text on the timeline is slightly cut off. This might not be an issue on larger devices.

![image](https://user-images.githubusercontent.com/10717998/203683524-82ea161f-1546-49d2-84f8-36ec0922c758.jpeg)

**Comment by pulsejet** [comment]
Safari has really horrible bugs

**Comment by meichthys** [comment]
It's probably not worth worrying about if it requires any significant work.

For reference it is also an issue on Firefox for iOS, but that's probably because Firefox uses WebKit anyway.

**Comment by pulsejet** [comment]
> It's probably not worth worrying about if it requires any significant work.

It shouldn't be hard to fix per se once I can reproduce it. But it's frustrating that Apple refuses to fix basic bugs in WebKit that have been filed since years.

> For reference it is also an issue on Firefox for iOS, but that's probably because Firefox uses WebKit anyway.

Yep, all browsers on iOS are wrappers around Safari 😢

**Comment by meichthys** [comment]
This doesn't seem to relevant anymore.

The timeline seems to be gone now, but that's not really a problem since it saves screen real estate on mobile to hide it. 👍
