### ISSUE TITLE
[Feature] Different sorting options in a folder

### ISSUE THREAD

**Issue by TheAnachronism** [pulsejet/memories#253]
I have a huge library of photos, that are all correctly named by number and by that have an intended order. I thought I could easily view all these photos with this app (or the photo app of Nextcloud, but that can't sort its images correctly either -.-).
Either I'm blind or there isn't an option to specify how files in a specific directory should be sorted.

Currently, it seems only to go after date, which means for images stripped of their metadata, it's basically random.
Is this possible to implement? Otherwise, I'll probably have to look for an alternative solution to view my library…

**Comment by pulsejet** [comment]
This is out of scope. Memories is not a file viewer, it's a photo app.
The solution to this problem is restore / create the date metadata on the files, then index them.
