### ISSUE TITLE
New photos don't get indexed

### ISSUE THREAD

**Issue by andreybavt** [pulsejet/memories#257]
I have a situation where newly added photos don't appear in Memories app.
I can see that in a native Photos app and also in the Folder view of Memories, but not in the timeline.

I'm running 
Nextcloud Hub 3 (25.0.1)
Memories 	4.8.2

**Comment by pulsejet** [comment]
> newly added photos

Do the photos show up if you run `occ memories:index` again (should be very fast)?

**Comment by andreybavt** [comment]
@pulsejet 
they did. Should I configure this command to be run regularly? Is there any way to make new photos appear as soon as they're uploaded (like in the Photos app)?

**Comment by pulsejet** [comment]
> Should I configure this command to be run regularly?

No, they should show up immediately. Can you provide more details about the setup? E.g. is this a shared storage / folder. When you ran `index` did it say some files were reprocessed?

**Comment by pulsejet** [comment]
Also you mentioned they show up in the memories folders view but not in the timeline? This definitely should not happen. Can you re-test by uploading some new images and confirm this is the actual behavior?

**Comment by andreybavt** [comment]
here's an output of the first `occ memories:index ` command:
```
Checked 345011 files of 5 users in 215.436 sec
12939 not valid media items
1 .nomedia folders ignored
332054 skipped because unmodified
17 (re-)processed
```

The photos aren't in the "shared" folder in terms of nextcloud, but my setup is a bit special because I'm running TrueNAS that mounts a certain storage pool to `/usr/local/www/nextcloud/data/<username>/files` when running nextcloud. So the whole data directory of my user is mounted.


I have automatic photo upload from my phone enabled, so I took a few more pictures and after they got uploaded they showed up immediately in Photos app and Memories Folders view, but not in Timeline.

I re-ran the indexing, and it doesn't seem to find anything:

```
Checked 345012 files of 5 users in 82.849 sec
12939 not valid media items
1 .nomedia folders ignored
332072 skipped because unmodified
0 (re-)processed
```

**Comment by pulsejet** [comment]
> I re-ran the indexing, and it doesn't seem to find anything:

And so did they show up in the timeline after this?

**Comment by andreybavt** [comment]
> > I re-ran the indexing, and it doesn't seem to find anything:
> 
> And so did they show up in the timeline after this?
> 
> Perhaps this is a browser cache issue? Can you try clearing cache / in a private window?

No, they actually didn't. I took 3 more pictures and re-ran indexing, I now get:
```
Checked 345015 files of 5 users in 83.248 sec
12939 not valid media items
1 .nomedia folders ignored
332075 skipped because unmodified
0 (re-)processed
```
So the "Checked" count makes sense: after first indexing I had `345011`, then `345012` after I took a test shot that still doesn't appear in the Timeline and now `345015` after 3 more shots that don't appear in the timeline neither. 

Doesn't seem like it's a browser cache issue, I cleared cache and also tried in incognito mode with "Disable cache" option checked and still get the same results (4 last pictures that I took are still missing)
![image](https://user-images.githubusercontent.com/7889985/204017923-0111906d-91ae-44ee-be9c-b9e2934206e2.png)

**Comment by pulsejet** [comment]
By any chance is the date on some photos incorrect? So in the folders view do they show up at the correct date? Then check the same date in the timeline.

**Comment by andreybavt** [comment]
The dates are all fine. I actually may have a clue:

I forgot to mention one thing, my Android app uploads photos to `/InstantUpload` which is a symlink:
```
root@nextcloud:/usr/local/www/nextcloud/data/andrey/files # ll InstantUpload
lrwxr-xr-x  1 www  www  12 Nov 19 13:47 InstantUpload@ -> photo/Mobile
```

in the Memories settings, I have this:
![image](https://user-images.githubusercontent.com/7889985/204019895-dad57965-43e7-4467-8eac-5cd71e71a469.png)


Technically newly uploaded photos are indeed in the `photo/Mobile/Camera/...` so I guess setting timeline path to `/photo` should be enough (but apparently it's not)

So if I explicitly add a new path to timeline:
![image](https://user-images.githubusercontent.com/7889985/204020228-74c8c92f-fde2-4719-ac1e-1e0da2d1653a.png)

the new photos do show up and if I take yet another one and auto-upload it it appears in the timeline without re-indexing.

I guess this is not the most common issue, but do you think this symlink setup can be fixed?

**Comment by pulsejet** [comment]
Ah that makes a more sense now. You really shouldn't be using symlinks with Nextcloud; they're not supported in any good way and create problems since you can't rely on the filecache being correct anymore. Closing as Memories doesn't handle the filesystem, so this is an upstream issue if any.

**Comment by major-mayer** [comment]
I've actually just experienced a similiar problem, but in my case it's definitely not a symlink that's being used.
In memories, my folder looks like this: 
![grafik](https://user-images.githubusercontent.com/17907799/216317920-77dffcdb-b4d3-43ea-badf-98eb94657b4e.png)
So as you can see, the only folder listed is the "01" from January. But I've already taken some photos in February and some of the last photos from January are also missing.

While files actually show, that there should be two subfolders: 
![grafik](https://user-images.githubusercontent.com/17907799/216318286-879a5bc3-9a9f-4897-9794-afc8fb009d59.png)

I've checked that no cache is in use and tested it with different browsers, but the problem persisted.

After running `occ memories:index` again, this problem was fixed.
The following output was produced.
```
==========================================
Checked 1249067 files of 21 users in 567.97 sec
128361 not valid media items
22 .nomedia folders ignored
1120615 skipped because unmodified
69 (re-)processed
====================================
```
