### ISSUE TITLE
Undefined array key "MIMEType"

### ISSUE THREAD

**Issue by leon1995** [pulsejet/memories#258]
I currently index all my files and my log is spammed with
`Undefined array key \"MIMEType\" at /var/www/html/custom_apps/memories/lib/Db/LivePhoto.php#23`

Do you have an idea what is going on? I am on nextcloud 25

**Comment by pulsejet** [comment]
Is anything showing up in Memories at all? If there's no mimetype, I doubt exiftool is even working.

**Comment by leon1995** [comment]
Not yet. I started a new run with `--clear` but it is still in the state of `Are you sure you want to clear the existing index? (y/N): y` since an hour. Is it normal, that deleting an existing, but always interrupted soon after the start, index takes that long?

**Comment by pulsejet** [comment]
No it seems it's stuck. Clearing the index should be instantaneous. Do you see the filenames when indexing? Also more details on your setup.

**Comment by leon1995** [comment]
No, no I dont see any filenames. but I notice that I have a very high cpu usage around 80%, when running the index command (RAM is around 4 GB).
I have nextcloud installed in docker on proxmox in an lxc contaienr with 4 cpus, 16 GB RAM

**Comment by pulsejet** [comment]
There are checks for this now
