### ISSUE TITLE
Download of photos from an album fails

### ISSUE THREAD

**Issue by jacotec** [pulsejet/memories#259]
Selecting 10 photos out of an album --> Download sends me a .tar file. Unfortunately this is completely empty.

Apart from no content in the archive, I'd prefer a .zip for maximum compatibility on all platforms. .tar is not an issue on my MacBook nor on my PCs as 7-zip is installed, but I'm not sure if a standard Windows user without any 3rd party packers can deal with it.

UPDATE: Seems to be a general issue. I've shared this album and another user has added the pictures into it. The pics are displayed, but I can't download any of them - even not in the detailed photo view via "..." --> "Download". It gives a "file not found" error:

<img width="719" alt="2022-11-25_18-23-59" src="https://user-images.githubusercontent.com/3321655/204032813-d8896800-ba46-44a9-9009-712b1eb02599.png">

UPDATE 2: The bug is even more generic. Logged in as the initial user who puts the photos into the album - download still fails with "file not found".

**Comment by pulsejet** [comment]
Thanks for filing. I believe this isn't implemented to begin with ...

**Comment by jacotec** [comment]
It should not be in the menu if it's not implemented ;-)

**Comment by Gymnae** [comment]
It would help if you'd use the template for bugs, @jacotec

**Comment by Gymnae** [comment]
Upstream bug: https://github.com/nextcloud/photos/issues/1394
