### ISSUE TITLE
[Feature Request] Share videos on mobile

### ISSUE THREAD

**Issue by philippgmk** [pulsejet/memories#261]
Hello.

Thank you for this app. I have been trying to find this functionality since a long time!

Currently I can share photos from the mobile webapp but there doesn't seem to be any way to share videos. Such a feature would be very helpful.

P.S. this is my first time posting on GitHub, so please let me know if I missed something.

**Comment by pulsejet** [comment]
I agree this is needed, but there's no easy way to do this. We probably need to transcode the video before sharing.
