### ISSUE TITLE
Download of images fails with error in OC_Util class

### ISSUE THREAD

**Issue by Gymnae** [pulsejet/memories#262]
When opening an image from the folder view, no matter if on a local storage or external, the following error pops up when attempting to download via the three dots menu. The same files download and open fine in the files.app

`Fatal error: Uncaught Error: Class "OC_Util" not found in /var/www/html/apps/files/ajax/download.php:31 Stack trace: #0 {main} thrown in /var/www/html/apps/files/ajax/download.php on line 31`

It also looks like it only renders the preview, not the real file

memories version: 4.8.2
nc: 25.0.1

**Comment by pulsejet** [comment]
This has nothing to do with memories; the download part is handled by the Files app. Did you change anything recently? Also can you download anything via the Photos app?

**Comment by Gymnae** [comment]
Interesting, I can replicate the Error in the Photos app. The photo downloads fine via the Files app, but not from the Folder view of Photos app. Photos also download fine from the "All Media" tab of the Photos app.

Example path generated by the Folder view of the Photos app and which fails:
https://cloud.domain.tld/remote.php/dav//Exchange/<topfolder>/<subfolder>/IMG_8393.jpeg

Example path generated by the Files app which works:
https://cloud.domain.tld/remote.php/dav/files/<username>/Exchange/<topfolder>/<subfolder>/IMG_8393.jpeg

It appears it's missing my username in the path generated by the Photos app. So maybe upstream bug?

**Comment by pulsejet** [comment]
Could you also check what's the path generated by memories when downloading?

**Comment by Gymnae** [comment]
Sure, this is a working link created by memories when downloading from the public link of a shared folder:
https://cloud.domain.tld/s/<shared_folder_name>/download?path=&files=22-11-26%2014-33-25%200850.jpg

This is failing link created by memories when attempting to download from a folder (while being logged):
https://cloud.domain.tld/apps/files/ajax/download.php?files=%5B%22%2F<folder name part 1>%2F<folder name part 2>%2F<foldername part 3>%2F%2F22-11-26+14-33-25+0850.jpg%22%5D&downloadStartSecret=<strtring>downloadStartSecret=<string>

The image lies in a folder with spaces, but the same error also happens when using a folder with no space in the name. 
memories appears to render only the preview when displaying the image, both via public link or when logged in.

**Comment by pulsejet** [comment]
Got it. I still think something has gone wrong with the Files app (the `OC_Util` is a Nextcloud class) but I'll try to investigate this further.
