### ISSUE TITLE
Share icon for Live Photo not clickable in mobile safari

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#263]
I haven't been able to test on desktop yet, but I am not able to click the share button when viewing a Live Photo (the share button is visible by tapping on it does nothing). It works fine for photos that are not live.

**Comment by pulsejet** [comment]
Sharing is broken altogether in <v4.9 (#254), but keep this open till it's confirmed fixed.

**Comment by pulsejet** [comment]
Actually this seems unrelated to the issue I referred ...
