### ISSUE TITLE
[Feature Request] Allow adding/editing Nextcloud tags

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#270]
Currently we have a way to view tags , but I don't see a way from within Memories to add/edit/remove Nextcloud tags.
This can be done in the files app within the sidebar by clicking the three dots next to the file name: 
![image](https://user-images.githubusercontent.com/10717998/204701905-ef25a017-29a7-4635-81c6-73d075412b27.png)

Perhaps Memories can implement this functionality?

**Comment by meichthys** [comment]
IMO, the three dot menu just for tags is a poor design choice, but if that's how Nextcloud does it, then Memories should probably implement it the same way for consistency (if you want to implement this at all).

**Comment by pulsejet** [comment]
![image](https://user-images.githubusercontent.com/10709794/223617834-e0c4be94-4a99-4c24-8b4b-cdc58cddcbf3.png)
