### ISSUE TITLE
[Feature Request] Keep tags sorted aphabetically

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#271]
New tags that are added seem to be added to the end of the tags list.

To reproduce:
- Open a photo in the Nextcloud files app
- Add a new unique tag to the photo
- Open Memories and navigate to Tags
The new tag will appear at the end of the list.

I thought maybe the tags would be re-sorted after indexing, but that doesn't seem to be the case.

If possible, it would be nice if the list of tags was always sorted alphabetically.

**Comment by pulsejet** [comment]
The problem is that the sorting is case sensitive.

**Comment by meichthys** [comment]
oh Lol. That makes sense!
