### ISSUE TITLE
Photos with EXIF metadata do not appear if first-time indexing hasn't been run

### ISSUE THREAD

**Issue by Thesola10** [pulsejet/memories#272]
Currently on my Nextcloud, I have photos stored in a setup similar to this:
```
Photos/
  A/
    1.jpg
    B/
      2.jpg
  C/
    3.jpg
  4.jpg
```

~~In the example above, `2.jpg` will never appear -- Memories doesn't appear to recurse deeper than a single level into directories. I would like it to index photos at any depth within the selected folder.~~

I was mistaken in my investigation. This doesn't appear to be a recursion issue, but rather an _indexing_ one.

**Comment by pulsejet** [comment]
It already does recourse till arbitrary depth. Do the photos appear in the folders view?

**Comment by Thesola10** [comment]
No, they don't beyond a single level

**Comment by pulsejet** [comment]
When you run `occ memories:index` are they being indexed at all? Should show up in the progress.

**Comment by Thesola10** [comment]
Oh, maybe it's only displaying pictures without EXIF data instead due to lack of indexing. That would make sense, although the out-of-box documentation should clarify the link between cause and symptom -- something like “Photos with EXIF metadata will not appear in Memories until `occ memories:index` is run” since, IIRC the welcome screen appears to suggest that indexing is optional in some cases.

**Comment by pulsejet** [comment]
Umm no, it won't show anything unless you run indexing (or you touched the file in some way). The README says very clearly that you need to run initial index in the installation instructions.

**Comment by Thesola10** [comment]
yep, that was it, sorry for the inconvenience!
