### ISSUE TITLE
Share memories doesn't respect share settings yet

### ISSUE THREAD

**Issue by ibes** [pulsejet/memories#273]
When I generate a share link memories offers me a different link that looks a lot nicer. 

But this gallery does not respect my choice to hide download option. 
Is there a plan to support that. 
- download or not
- expiration dates
- password protection

That would be a game changer

**Comment by pulsejet** [comment]
> * download or not

This should be possible. Just a note that there's no real way to prevent downloading; all we do is hide the button.

> * expiration dates
> * password protection

Both of these should work already, otherwise it's a bug (file a separate issue).

**Comment by ibes** [comment]
Yep, hiding the select feature and the download button would be exactly what I would do as a work around. 

I am aware that right click, „save as“ or more techy things will still work. 

just not pushing it onto people would be enough for me. 

And memories needs to do the link in the overlay and can’t just use the nativ function?
Like the link in the sidebar and in the overlay are not identical for me. 

New to NextCloud. 
Not new to PHP and webdevelopment. 
Likely should start reading the sourcecode. 

Thanks for the improved gallery ✨
