### ISSUE TITLE
[Feature Request] Share multiple photos publicly

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#274]
Currently I don't see a way to share a group of photos publicly. Ideally we should be able to do at least one of the following:
- Add photos to an album and generate a public link to the album
- Select multiple photos from timeline and share them as a single public link

Current Alternatives:
- Add photos to album, and share the album to an internal nextcloud user (not public)
- Add photos to a nextcloud files folder and share the folder (no way do do this via memories)

**Comment by HyCore** [comment]
i would really love to see something like that coming in the future ;D

**Comment by NablaMetal** [comment]
Nextcloud Photo already allow users to share publicly albums via a token generation but it's not possible to access the public album with memories for now.
I just disovered memories a couple days ago and with hardware transcoding enabled and face recognition, it is really nearly perfect.
