### ISSUE TITLE
4.8.2 Scrolling rolls back when viewing photos in folders.

### ISSUE THREAD

**Issue by funstuk** [pulsejet/memories#275]
Hello.
When viewing photos, scrolling returns to the beginning after clicking on the image preview.
This issue only appears in folders. In "Timeline" this problem is not observed. I have tested this on different browsers.
Also in the demo there is no such problem in the folders.

**Comment by pulsejet** [comment]
This was fixed in https://github.com/pulsejet/memories/commit/ec19d724c5d9cb591231ef4d1d9e090eed593143
Should be fixed in the next release.

**Comment by pulsejet** [comment]
@funstuk please check with v4.9.0

**Comment by funstuk** [comment]
@pulsejet This works great! 
I don't notice this problem anymore.
