### ISSUE TITLE
Some files are missing in album and folder views

### ISSUE THREAD

**Issue by darguez** [pulsejet/memories#278]
After realizing that some photos and videos were missing in album view from Memories, I checked the folder view and it seems some files are missing (8 out of 9 files actually). In Photo app, folder and album views shows the all the files correctly.

I'm using Memories v4.9.1 and NC 25.0.2

**Comment by pulsejet** [comment]
Did you run `occ memories:index`?

**Comment by darguez** [comment]
Yes, but not recently. How often do I need to run it?

**Comment by pulsejet** [comment]
In general you shouldn't ever need to run it, unless you're adding files externally. Is that the case? I'd say run it once regardless to be sure this isn't unrelated.

**Comment by etatus** [comment]
Ok, the occ command solved the problem. I didnt upload files externally (as far as I remember). Maybe missing files were uploaded directly from the dialog available in albums (from Photos app), but Im not sure.

If the issue happens again I'll let you know.

Thanks!!

**Comment by pulsejet** [comment]
Yeah, maybe try uploading a few files from different sources to see if any particular upload type has issues.
Closing this for now.
