### ISSUE TITLE
Most photos from folders with lots of items don't appear

### ISSUE THREAD

**Issue by pablordgez** [pulsejet/memories#279]
I noticed that some photos were missing, so I tried removing every directory and then added one at a time. First, I added a folder with 59 files, and they were all there, but then I tried a folder which has a bit over 4,000 photos and only 18 loaded (all the photos inside this folder are jpg, so it's not a format thing)

**Comment by pulsejet** [comment]
Did you run indexing?
```
occ memories:index
```

**Comment by pablordgez** [comment]
> Did you run indexing? Any errors there?
> 
> ```
> occ memories:index
> ```

I'm so dumb I actually didn't, I installed from Nextcloud app store so I didn't see the installation steps here and I don't know how I missed that when looking for a solution, sorry for wasting your time
