### ISSUE TITLE
FATAL: exiftool could not be executed or test failed

### ISSUE THREAD

**Issue by tbelway** [pulsejet/memories#284]
I saw another user had this same issue but it seems to have a different root cause.

When I attempt indexing I get:

```
occ memories:index                                                                                      
Checking database indices

MIME Type support:
  image/png: supported
  image/jpeg: supported
  image/heic: supported
  image/png: supported
  image/tiff: supported
  image/gif: supported
  image/bmp: supported
  image/x-dcraw: supported
  video/mpeg: supported
  video/webm: supported
  video/mp4: supported
  video/quicktime: supported
  video/x-matroska: supported

All file types are supported by your preview provider.

WARN: Failed to create stay_open exiftool process
Exiftool timeout: [/config/www/nextcloud/apps/memories/exiftest.jpg]
Couldn't read Exif data from test file: Could not read from Exiftool
FATAL: exiftool could not be executed or test failed
Make sure you have perl 5 installed in PATH
```

My setup:

- linuxserverio container with mariadb
- installed from appstore
- perl version 5
- path is fine
- test jpg exists
- no memories options in config.php
- permissions set to non-root (abc as per linuxserver.io php)

Perl version:
```
perl -v

This is perl 5, version 34, subversion 0 (v5.34.0) built for x86_64-linux-thread-multi

Copyright 1987-2021, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

Path demonstration:
```
root@nextcloud:/config/www/nextcloud/apps/memories/exiftool-bin/exiftool# perl exiftool | grep -A 1 DESCRIPTION
DESCRIPTION
    A command-line interface to Image::ExifTool, used for reading and
```

Test jpeg:
```
exiftool /config/www/nextcloud/apps/memories/exiftest.jpg                         
ExifTool Version Number         : 12.30
File Name                       : exiftest.jpg
Directory                       : /config/www/nextcloud/apps/memories
File Size                       : 3.6 KiB
File Modification Date/Time     : 2022:12:11 16:23:34-05:00
File Access Date/Time           : 2022:12:12 12:49:53-05:00
File Inode Change Date/Time     : 2022:12:12 11:08:17-05:00
File Permissions                : -rwxrwxrwx
```

I even confirmed permissions by running as the abc user:
```
sudo -H -u abc exiftool /config/www/nextcloud/apps/memories/exiftest.jpg 
ExifTool Version Number         : 12.30
File Name                       : exiftest.jpg
Directory                       : /config/www/nextcloud/apps/memories
File Size                       : 3.6 KiB
File Modification Date/Time     : 2022:12:11 16:23:34-05:00
File Access Date/Time           : 2022:12:12 12:49:53-05:00
File Inode Change Date/Time     : 2022:12:12 11:08:17-05:00
File Permissions                : -rwxrwxrwx
```

Getting desperate I rebuilt the container, went into the container environment and removed and reinstalled perl/exiftool, and chmod 777 the jpg to no avail.

I'm at my wits end troubleshooting this, hoping it's something simple...

**Comment by pulsejet** [comment]
Could you try adding a print statement near the following to see if the command it's using is correct?
https://github.com/pulsejet/memories/blob/9a0264941560c03f822e04eca010fa0eba9dc1f1/lib/Exif.php#L337

Secondly, it should just be using the bundled executables instead of the perl ones, so something else is at work here. This function is what you want to look at in general.

**Comment by tbelway** [comment]
I'm not sure how you want me to use the print function...

```
        // Fallback to perl script
        $path = __DIR__.'/../exiftool-bin/exiftool/exiftool';
        print (file_exists($path));
        if (file_exists($path)) {
            return ['perl', $path];
        }
```


root@nextcloud:/# occ memories:index
Checking database indices

MIME Type support:
  image/png: supported
  image/jpeg: supported
  image/heic: supported
  image/png: supported
  image/tiff: supported
  image/gif: supported
  image/bmp: supported
  image/x-dcraw: supported
  video/mpeg: supported
  video/webm: supported
  video/mp4: supported
  video/quicktime: supported
  video/x-matroska: supported

All file types are supported by your preview provider.

WARN: Failed to create stay_open exiftool process
Exiftool timeout: [/config/www/nextcloud/apps/memories/exiftest.jpg]
Couldn't read Exif data from test file: Could not read from Exiftool
FATAL: exiftool could not be executed or test failed
Make sure you have perl 5 installed in PATH

**Comment by pulsejet** [comment]
Hmm. Try adding this to your config to see if it changes anything. That should force using perl directly.
```php
'memories.exiftool_no_local' => true,
```

**Comment by tbelway** [comment]
I added the line to my config and restarted the container but still:

```
[nextcloud@nextcloud ~]$ podman restart nextcloud-app 
cb724773a671ae0a68fff046b53e8c543e6af483fb7102b87876a4d0fbd1d585
[nextcloud@nextcloud ~]$ podman exec -it nextcloud-app bash
root@nextcloud:/# occ memories:index
Checking database indices

MIME Type support:
  image/png: supported
  image/jpeg: supported
  image/heic: supported
  image/png: supported
  image/tiff: supported
  image/gif: supported
  image/bmp: supported
  image/x-dcraw: supported
  video/mpeg: supported
  video/webm: supported
  video/mp4: supported
  video/quicktime: supported
  video/x-matroska: supported

All file types are supported by your preview provider.

WARN: Failed to create stay_open exiftool process
Exiftool timeout: [/config/www/nextcloud/apps/memories/exiftest.jpg]
Couldn't read Exif data from test file: Could not read from Exiftool
FATAL: exiftool could not be executed or test failed
Make sure you have perl 5 installed in PATH
```

**Comment by vitis586** [comment]
So how does your config look now, when it is working? I am on this issue since yesterday but no luck. I thought that it is the path to the exiftool binaries, that is different than the one in config options. But only now I see that you spotted that too. EXIF is not showing up even in Nextcloud on web.

**Comment by tbelway** [comment]
Well the issue started after I ran the command:

`occ memories:video-setup`

though not until after I did a container reboot, and I can't replicate it again. I'll try playing with it again the weekend after next to see if I can replicate the issue and I'll report back if I can. It's strange, cuz the conf still looks like:

```
  'preview_max_memory' => 4096,
  'preview_max_filesize_image' => 256,
  'memories.ffmpeg_path' => '/usr/bin/ffmpeg',
  'memories.ffprobe_path' => '/usr/bin/ffprobe',
  'memories.no_transcode' => true,
  'memories.qsv' => false,
  'memories.exiftool_no_local' => true,
);
```

and seems to run after restarting the container after removing the lsat line now too...

**Comment by pulsejet** [comment]
For reference, config changes (including `video-setup`) are applied only after a container reboot.

**Comment by vitis586** [comment]
@pulsejet Yes, I am aware of that. Thanks!

I did a bit of testing. I deleted everything Memories related from the config. I tried running first the video-setup and also the index. The order does not matter in my case. Only change I noticed is that when I use `'memories.exiftool_no_local' => true,` I will get a version mismatch note.

```
Exiftool version check failed 12.50
 <==> 12.49
WARN: Failed to create stay_open exiftool process
Exiftool timeout: [/config/www/nextcloud/apps/memories/exiftest.jpg]
Couldn't read Exif data from test file: Could not read from Exiftool
FATAL: exiftool could not be executed or test failed
Make sure you have perl 5 installed in PATH
```

Whereas with `'memories.exiftool_no_local' => false,` I get the same as @tbelway used to get.

```
WARN: Failed to create stay_open exiftool process
Exiftool timeout: [/config/www/nextcloud/apps/memories/exiftest.jpg]
Couldn't read Exif data from test file: Could not read from Exiftool
FATAL: exiftool could not be executed or test failed
Make sure you have perl 5 installed in PATH
```

The EXIF tab in Memories in Nextcloud is showing only the filename. It might connected to this issue but I am not sure with that. Demo is not running at the moment so I don't know how is it supposed to look like. I noticed that log shows this error when I tried looking on the EXIF in Memories.

> [PHP] Chyba: Error: proc_open(): Exec failed: No such file or directory at /config/www/nextcloud/apps/memories/lib/Exif.php#413 at <<closure>>
> 
>  0. <<closure>>
>     OC\Log\ErrorHandler::onError()
>  1. /config/www/nextcloud/apps/memories/lib/Exif.php line 413
>     proc_open()
>  2. /config/www/nextcloud/apps/memories/lib/Exif.php line 130
>     OCA\Memories\Exif::getExifFromLocalPathWithSeparateProc()
>  3. /config/www/nextcloud/apps/memories/lib/Exif.php line 113
>     OCA\Memories\Exif::getExifFromLocalPath()
>  4. /config/www/nextcloud/apps/memories/lib/Db/TimelineWrite.php line 105
>     OCA\Memories\Exif::getExifFromFile()
>  5. /config/www/nextcloud/apps/memories/lib/Listeners/PostWriteListener.php line 83
>     OCA\Memories\Db\TimelineWrite->processFile()
>  6. /config/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php line 87
>     OCA\Memories\Listeners\PostWriteListener->handle()
>  7. /config/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 251
>     OC\EventDispatcher\ServiceEventListener->__invoke()
>  8. /config/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 73
>     Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
>  9. /config/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php line 88
>     Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
> 10. /config/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php line 100
>     OC\EventDispatcher\EventDispatcher->dispatch()
> 11. /config/www/nextcloud/lib/private/Files/Node/HookConnector.php line 118
>     OC\EventDispatcher\EventDispatcher->dispatchTyped()
> 12. /config/www/nextcloud/lib/private/legacy/OC_Hook.php line 106
>     OC\Files\Node\HookConnector->postWrite()
> 13. /config/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 471
>     OC_Hook::emit()
> 14. /config/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 398
>     OCA\DAV\Connector\Sabre\File->emitPostHooks()
> 15. /config/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 151
>     OCA\DAV\Connector\Sabre\File->put()
> 16. /config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 307
>     OCA\DAV\Connector\Sabre\Directory->createFile()
> 17. /config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 133
>     Sabre\DAV\Tree->copyNode()
> 18. /config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 163
>     Sabre\DAV\Tree->copy()
> 19. /config/www/nextcloud/apps/dav/lib/Upload/ChunkingPlugin.php line 94
>     Sabre\DAV\Tree->move()
> 20. /config/www/nextcloud/apps/dav/lib/Upload/ChunkingPlugin.php line 76
>     OCA\DAV\Upload\ChunkingPlugin->performMove()
> 21. /config/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
>     OCA\DAV\Upload\ChunkingPlugin->beforeMove()
> 22. /config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 603
>     Sabre\DAV\Server->emit()
> 23. /config/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
>     Sabre\DAV\CorePlugin->httpMove()
> 24. /config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
>     Sabre\DAV\Server->emit()
> 25. /config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
>     Sabre\DAV\Server->invokeMethod()
> 26. /config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
>     Sabre\DAV\Server->start()
> 27. /config/www/nextcloud/apps/dav/lib/Server.php line 360
>     Sabre\DAV\Server->exec()
> 28. /config/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
>     OCA\DAV\Server->exec()
> 29. /config/www/nextcloud/remote.php line 171
>     require_once("/config/www/nex ... p")

The `video-setup` command runs successfully and adds it's part to the config. The transcoding is not working for me, but I have not looked at that, so let's just focus on the photos part now.

**Comment by pulsejet** [comment]
@vitis586 can you try with 4.9.3? Remove the memories.exiftool* entries in config.php

**Comment by tbelway** [comment]
> For reference, config changes (including `video-setup`) are applied only after a container reboot.

Yup, I started the doc as per the doc :) that may have been a source of confusion initially since I rebooted it the next day or day after... 

@vitis586  if you're having the same issue I wonder what your config looks like... mind sharing it? Perhaps we can find something similar?

**Comment by vitis586** [comment]
@pulsejet Well. It seems that 4.9.3 made the indexing working! Only now I understand that the indexing shows the EXIF on web (from my understanding), because that is now also working and looks very good! Great job!

@tbelway I had it pretty much the same as you did. The only bonus line on my side was the path to exiftool binary that is in the documentation (System config options). I was then starting from zero many times.

Indexing works for me now. I will head further and have a look on transcoding.

**Comment by vitis586** [comment]
Literally as I hit send this popped up.. I let the indexing run in the morning and it did not finish. I think this is the reason.

```
42.00% scanning /Victoria/files/Viki/My Photos/Telefon Zaloha/2022/12/22-12-03 16-09-41 6331.mov
An unhandled exception has been thrown:
TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /config/www/nextcloud/apps/memories/lib/Db/TimelineWrite.php:126
Stack trace:
#0 /config/www/nextcloud/apps/memories/lib/Db/TimelineWrite.php(126): round()
#1 /config/www/nextcloud/apps/memories/lib/Command/Index.php(293): OCA\Memories\Db\TimelineWrite->processFile()
#2 /config/www/nextcloud/apps/memories/lib/Command/Index.php(275): OCA\Memories\Command\Index->parseFile()
#3 /config/www/nextcloud/apps/memories/lib/Command/Index.php(271): OCA\Memories\Command\Index->parseFolder()
#4 /config/www/nextcloud/apps/memories/lib/Command/Index.php(271): OCA\Memories\Command\Index->parseFolder()
#5 /config/www/nextcloud/apps/memories/lib/Command/Index.php(271): OCA\Memories\Command\Index->parseFolder()
#6 /config/www/nextcloud/apps/memories/lib/Command/Index.php(271): OCA\Memories\Command\Index->parseFolder()
#7 /config/www/nextcloud/apps/memories/lib/Command/Index.php(271): OCA\Memories\Command\Index->parseFolder()
#8 /config/www/nextcloud/apps/memories/lib/Command/Index.php(250): OCA\Memories\Command\Index->parseFolder()
#9 /config/www/nextcloud/apps/memories/lib/Command/Index.php(188): OCA\Memories\Command\Index->generateUserEntries()
#10 /config/www/nextcloud/lib/private/User/Manager.php(660): OCA\Memories\Command\Index->OCA\Memories\Command\{closure}()
#11 /config/www/nextcloud/apps/memories/lib/Command/Index.php(189): OC\User\Manager->callForSeenUsers()
#12 /config/www/nextcloud/apps/memories/lib/Command/Index.php(156): OCA\Memories\Command\Index->executeWithOpts()
#13 /config/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Memories\Command\Index->execute()
#14 /config/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#15 /config/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#16 /config/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#17 /config/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#18 /config/www/nextcloud/console.php(100): OC\Console\Application->run()
#19 /config/www/nextcloud/occ(11): require_once('...')
#20 {main}root@b019ce2f324a:/#
```

**Comment by pulsejet** [comment]
@vitis586 can you try manually applying these two patches: https://github.com/pulsejet/memories/commit/37a26b8c31f92c29881cb1176de53517a7013131 and https://github.com/pulsejet/memories/commit/70f3fbaea1893463d85d9e9e3699c6321f27cbb5

**Comment by vitis586** [comment]
I waited for the finish this time. And it finished! Turns out, that it is way more than 40000 photos.

```
==========================================
Checked 138971 files of 5 users in 4783.256 sec
11236 not valid media items
1 .nomedia folders ignored
85342 skipped because unmodified
42392 (re-)processed
==========================================
```
