### ISSUE TITLE
Pkill command not found for official Nextcloud docker image

### ISSUE THREAD

**Issue by major-mayer** [pulsejet/memories#286]
During the update of my Nextcloud FPM Docker image (from 24 to 25), the following error message appeared in the logs:
```
Update app memories from App Store
sh: 1: pkill: not found
 1/1 [============================] 100%sh: 1: pkill: not found
```

It seems like the Nextcloud Docker stable-fpm image doesn't provide this command.
I don't know if it's making any difference, Nextcloud and Memories seem to be working, I wanted to report it anyway.

**Comment by Emporea** [comment]
Saw the same when updating via cli.

```
sh: 1: pkill: not found
sh: 1: pkill: not found
memories 4.9.2 installed
sh: 1: pkill: not found
sh: 1: pkill: not found
sh: 1: pkill: not found
sh: 1: pkill: not found
memories enabled
```

I dont know yet if it has any consequences.
