### ISSUE TITLE
Multipreview does not work in Firefox

### ISSUE THREAD

**Issue by major-mayer** [pulsejet/memories#287]
I am using the version 4.9.2 of memories and was really excited about the multipreview functionality, espacially about the lower CPU load.
However, when browsing through the timeline or a folder, Memories still seems to be downloading the previews one by one.
![grafik](https://user-images.githubusercontent.com/17907799/207180494-26d8486b-f680-4edc-8f13-0c8d06433586.png)

Is there any additional work needed to get this feature running?

**Comment by pulsejet** [comment]
I can confirm multipreview isn't working on firefox. So the way it wors is a service worker intercepts all your image requests and aggregates them to send a single request to the server. Unfortunately service worker registration and behavior is rather unpredictable, but it does work ~90% of the time in Chrome (for me at least). But seems like firefox needs more work.

**Comment by pulsejet** [comment]
Yes, that's the way it works. So the service worker runs like a proxy between the browser and the server. The browser continues to make "traditional" requests (these are the ones that show up in the console), these are then intercepted by the sw, aggregated, and the response is unaggregated back to the individual original requests.

**Comment by major-mayer** [comment]
Ah that's very interesting, thanks for the explanation.

**Comment by major-mayer** [comment]
Hi @pulsejet 
Is this issue on your roadmap? Have you already found the reason for this to not work?

**Comment by pulsejet** [comment]
Still need to investigate this ...

**Comment by pulsejet** [comment]
I just tested this on firefox and multipreview is working as expected. There's just no indication in the console that this is happening.

Note that there is a bug in v4.10 that prevents the service worker from being registered. In this case, obviously, multipreview won't work. This will be fixed in v4.11

**Comment by major-mayer** [comment]
All right, thanks for the investigation. 
So I have no possibility to test if this is working for me or not other than monitoring the loading times / server load?

**Comment by pulsejet** [comment]
Yeah. Check the webserver logs basically; it should be multipreview instead of preview

Btw service workers usually don't kick in until you reload the page after the initial load (with cache enabled).

**Comment by major-mayer** [comment]
All right, I will test this as soon as version 4.11 is released

**Comment by major-mayer** [comment]
Yup, seems to be working. Thanks for your work :)
