### ISSUE TITLE
It's impossible to remove pictures from Albums

### ISSUE THREAD

**Issue by jacotec** [pulsejet/memories#288]
Running Memories 4.9.2, it's impossible to remove pictures from an Album. Whatever picture should be removed, gives an error and the picture stays in the album:

![image](https://user-images.githubusercontent.com/3321655/207317731-af372e24-971c-4602-a2e7-2f85bce6400b.png)

The only workaround is to remove the pictures in the Photos app (which shares the same albums) from the album (that feels a bit like working on an old 386 compared to memories ;-) )

**Comment by meichthys** [comment]
This seems to be working fine in v4.11 👍

**Comment by meichthys** [comment]
@jacotec  & @pulsejet  I'm thinking we can probably close this?

**Comment by pulsejet** [comment]
I guess so. If you can still repro, please reopen.
