### ISSUE TITLE
Required exif package name: libimage-exiftool-perl

### ISSUE THREAD

**Issue by RonaldBarnes** [pulsejet/memories#29]
Running KDEneon (KDE on Ubuntu 20.04.5 LTS), and I had to make a slight change to the install instructions:

2) Install exiftool (`sudo apt install exiftool`).

Had to be changed to:
2) Install exiftool (`sudo apt install libimage-exiftool-perl`).

**Comment by pulsejet** [comment]
Good point

**Comment by pulsejet** [comment]
Readme updated
