### ISSUE TITLE
QSV not working

### ISSUE THREAD

**Issue by MoskiT87** [pulsejet/memories#291]
Hi, I have an intel i3 9100 processor, it supports Intel® Quick Sync Video, but it doesn't work in transcoding.
[go-vod.log](https://github.com/pulsejet/memories/files/10229553/go-vod.log)
I installed ffmpeg with vaapi support

$ ffmpeg -filters | grep vaapi
 ... deinterlace_vaapi V->V       Deinterlacing of VAAPI surfaces
 ... denoise_vaapi     V->V       VAAPI VPP for de-noise
 ... procamp_vaapi     V->V       ProcAmp (color balance) adjustments for hue, saturation, brightness, contrast
 ... scale_vaapi       V->V       Scale to/from VAAPI surfaces.
 ... sharpness_vaapi   V->V       VAAPI VPP for sharpness
 ... transpose_vaapi   V->V       VAAPI VPP for transpose
$ ffmpeg -hwaccels 2>/dev/null | grep vaapi
vaapi
$ ffmpeg -encoders 2>/dev/null | grep vaapi
 V..... h264_vaapi           H.264/AVC (VAAPI) (codec h264)
 V..... hevc_vaapi           H.265/HEVC (VAAPI) (codec hevc)
 V..... mjpeg_vaapi          MJPEG (VAAPI) (codec mjpeg)
 V..... mpeg2_vaapi          MPEG-2 (VAAPI) (codec mpeg2video)
 V..... vp8_vaapi            VP8 (VAAPI) (codec vp8)
 V..... vp9_vaapi            VP9 (VAAPI) (codec vp9)

My OS Ubuntu Server 20.04

**Comment by pulsejet** [comment]
Version of `ffmpeg`? You probably need a newer one that whatever you have.

**Comment by MoskiT87** [comment]
> Version of `ffmpeg`? You probably need a newer one that whatever you have.
$ ffmpeg -V
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers  
Is the latest version enough?

**Comment by pulsejet** [comment]
Interesting. So the logs say that `force_original_aspect_ratio` doesn't exist but it [definitely should](https://ffmpeg.org/ffmpeg-filters.html#Output-mode). So it looks like the issue is with the way ffmpeg is compiled and / or the corresponding Intel drivers being used. I'd suggest trying a from-scratch build ([see](https://github.com/pulsejet/memories/wiki/QSV-Transcoding#building-drivers-and-ffmpeg-from-source)); it's easier than it might seem at first sight.

**Comment by MoskiT87** [comment]
> Interesting. So the logs say that `force_original_aspect_ratio` doesn't exist but it [definitely should](https://ffmpeg.org/ffmpeg-filters.html#Output-mode). So it looks like the issue is with the way ffmpeg is compiled and / or the corresponding Intel drivers being used. I'd suggest trying a from-scratch build ([see](https://github.com/pulsejet/memories/wiki/QSV-Transcoding#building-drivers-and-ffmpeg-from-source)); it's easier than it might seem at first sight.

Yes, it works, just ran the installation script on the system, thanks!
