### ISSUE TITLE
Download album not working

### ISSUE THREAD

**Issue by ereynier** [pulsejet/memories#292]
Tried to download an album with "Download album" button and nothing happened.
I tested with a new album with 1 photo in and same.

**Comment by pulsejet** [comment]
Anything in the JS console?

**Comment by ereynier** [comment]
```message: "Request failed with status code 500"
name: "AxiosError"```

**Comment by pulsejet** [comment]
I see. Which request is this? (check the network tab). Anything in the Nextcloud logs?

**Comment by ereynier** [comment]
Request is : `url/apps/memories/api/albums/download?name=zstzbxn/test`
Method: `POST`
content-length: `0`
A big message in logs with `"message":"OCA\\Memories\\Db\\TimelineQuery::getAlbumFiles(): Argument #1 ($albumId) must be of type int, string given, called in /config/www/nextcloud/apps/memories/lib/Controller/AlbumsController.php on line 76 in file '/config/www/nextcloud/apps/memories/lib/Db/TimelineQueryAlbums.php' line 203",` in.
I saved the full message if you want.
