### ISSUE TITLE
oc_memories is corrupted

### ISSUE THREAD

**Issue by jalin2** [pulsejet/memories#295]
Hi,
I get the following message:
"An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1712 Index oc_memories is corrupted"

A bit of background:
* When I installed memories the first time, indexing was fine and went smoothly.  I was able to view the timeline and all is working great
* Some days later when I tried to open memories it actually crashed my whole nextcloud instance.  Apologies but I don't have logs for this
* There was a bug in Recognize which couldn't complete classification of people so I thought maybe it's related to this memories crash.  So in the meantime I uninstalled memories until the recognize bug was fixed (was related to memory out of bounds)
* The recognize bug is fixed now.  Recognize is working smoothly.  I installed memories again.  However when I go to run the index step I get lots of messages related to the message above about corruption

Because I have a complicated history, I'm looking for a way just to start fresh.  Remove any previous index and index from scratch again.  Is there a way to do so?

**Comment by pulsejet** [comment]
MySQL? Try
```sql
OPTIMIZE TABLE oc_memories;
```

Alternatively, drop the `oc_memories*` tables and delete the memories migrations from the `oc_migrations` table. Then reinstall memories.

**Comment by jalin2** [comment]
Thanks, I tried the OPTIMIZE command but it gave the following:

MariaDB [nextcloud]> OPTIMIZE TABLE oc_memories;
+-----------------------+----------+----------+-------------------------------------------------------------------+
| Table                 | Op       | Msg_type | Msg_text                                                          |
+-----------------------+----------+----------+-------------------------------------------------------------------+
| nextcloud.oc_memories | optimize | note     | Table does not support optimize, doing recreate + analyze instead |
| nextcloud.oc_memories | optimize | error    | Can't open table                                                  |
| nextcloud.oc_memories | optimize | status   | Operation failed                                                  |
+-----------------------+----------+----------+-------------------------------------------------------------------+

I've dropped oc_memories* and also deleted the memories migrations from oc_migrations table.  However when I try to reinstall I'm met with the following error now:

An error occurred during the request. Unable to proceed.
Database error when running migration 400308Date20221026151748 for app memories An index with name 'memories_parent_mimetype' was already defined on table 'oc_filecache'.

**Comment by pulsejet** [comment]
Ah yes, you also need to drop that index from `oc_filecache` before running the migration.

**Comment by jalin2** [comment]
Is this an entry in the oc_filecache table which I need to delete?   Do I search for 'memories_parent_mimetype' for one of the columns to figure out which entry?

Apologies as I'm not familiar with the nextcloud db and I want to make sure I don't mess it up.

**Comment by pulsejet** [comment]
It's an index. 
```
DROP INDEX memories_parent_mimetype ON oc_filecache
```

**Comment by jalin2** [comment]
Thanks!  After dropping the index I'm about to reinstall and index again.  All is running!  Thanks @pulsejet
