### ISSUE TITLE
Support external storage

### ISSUE THREAD

**Issue by pulsejet** [pulsejet/memories#30]

**Comment by pulsejet** [comment]
@Aquariu please test with v1.1.0

**Comment by Aquariu** [comment]
Steps:

- Update app to 1.1.0
- Reload the browser tab where Memories was loaded

Result : 
"Internal error"
In the logs:
`ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE)
    /var/www/nextcloud/lib/composer/composer/ClassLoader.php - line 428:
    Composer\Autoload\includeFile()
    <<closure>>
    Composer\Autoload\ClassLoader->loadClass()
    <<closure>>
    spl_autoload_call()
    /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 114:
    ReflectionClass->__construct()
    /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 133:
    OC\AppFramework\Utility\SimpleContainer->resolve()
    /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 465:
    OC\AppFramework\Utility\SimpleContainer->query()
    /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 437:
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
    /var/www/nextcloud/lib/private/AppFramework/App.php - line 159:
    OC\AppFramework\DependencyInjection\DIContainer->query()
    /var/www/nextcloud/lib/private/Route/Router.php - line 298:
    OC\AppFramework\App::main()
    /var/www/nextcloud/lib/base.php - line 1023:
    OC\Route\Router->match()
    /var/www/nextcloud/index.php - line 36:
    OC::handleRequest()`

- Uninstall / reinstall the app / reload page leads to the same result
- 
- I tried (rather violently) to solve the issue by droping the table oc_memories from the db. Now on reinstall the app does not recreate it (don't know why) which leads to the same error, plus: `sudo -u www-data php occ memories:index` now doesn't want to run because the table oc_memories doesn't exist (of course!) 
`FATAL: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ownclouddb.oc_memories' doesn't exist`

- uninstall the app (again) Restart php process, restart db. didn't solve the database hole I dug myself in.
- the rest of the system is ok.

**Comment by pulsejet** [comment]
Argh, this is PHP7 stuff. I use 8.
Let me fix this -- suggest you standby till then

**Comment by pulsejet** [comment]
Okay, v1.1.1 should hopefully fix PHP7 support
@Aquariu 

BTW for future reference, if you do drop the table you don't need to restore an sql backup. Just remove all entires for the app in the `oc_migrations` table, and then the migrations will re-run when you reinstall the app. You also need to drop the memories path index in the `oc_filecache` table, or it will throw an error at first (will still run though, since the rest of the migration succeeds anyway)

**Comment by Aquariu** [comment]
Thanks for the tip ! So I was utterly wrong with my assumptions. Will try to keep that in mind.

With v1.1.1:
- App loads ok
- Folder view is ok
- Favorites and Videos appear on the left pannel
- Timeline is still not showing anything when External Storage is selected. In my case, my External storage is mounted on a Nextcloud folder called "Medias" in which there is a folder called "photos". So I have put '/photos' in the Timeline setting. Nothing shows. While other folders work correctly. I ALSO have a external storage called Photos with 

No visible error in the logs. (loglevel = 1)

See also newly created issue

**Comment by pulsejet** [comment]
Hmm that is strange. I'm assuming you can see the photos from the external storage in the folder view?
Two things to check:
1/ Try without the leading slash, i.e. just `photos/` in the timeline setting
2/ Note that this setting is case sensitive
3/ Also note you need to re-run index on v1.1.1+ for it to work properly (if you ran it for v1.0.7 and upgraded then that won't work)

@Aquariu

**Comment by pulsejet** [comment]
You _might_ also have to _clear_ the old index completely. Probably this takes a bit more time but:
```bash
./occ memories:index --clear
```

**Comment by Civlac** [comment]
I thought I'd comment that my fresh installed version 1.1.4 from the Nextcloud app store works flawlessly with photos stored on an external folder (local). I followed the notes in the Readme about setting the correct path, and it immediately populated.

When files were added outside of NC, I was required to visit the folder within NC, then trigger the memories:index command. I imagine this is expected behaviour however.

**Comment by Aquariu** [comment]
THank you very much for the responsiveness !


> You _might_ also have to _clear_ the old index completely. Probably this takes a bit more time but:
> 
> ```shell
> ./occ memories:index --clear
> ```

Steps:
- Update to 1.1.4
- Cleared and re-indexed:
`sudo -u www-data php occ memories:index --clear`
- Wait patiently (300+GB to index)
- clear recent browser cache
- ctl-Reload page
- Set `photos/` in Timeline config
- Click "update"


Result: Success \o/ (sort of... read below)

- Timeline shows.
- With a folder structure like this : Medias/photos/year/month (Medias being the root of the external storage, I had to put `/photos` for it to work. It also work with `photos` but not `photos/`. It looks to be in line with your previous comments.
- I reloaded the page without waiting for the index to finish and it showed the timeline only beginning in 2011 (from 2004 to 2011) while I have photos from 2004 to 2022.
- I rerun memories:index --clear, just to be safe and waited AGAIN. 
- My external storage is mounted by several users, index runs sequentially for all users. I don't know how feasible this is but maybe scanning external storages only once can be done ?
- Reload. \o/ Success ! Timeline now starts correctly from September 2022. There are hundreds of photos that are far older than September 2022 that are displayed at that position in the Timeline. I need to look into why the timestamps are wrong. But I don't believe that is something to do with your app.

I'll test more when I have time.

Cheers and thanks again :)

**Comment by Aquariu** [comment]
On those misplaced images, the exif data is correct (i.e. the date/time when the photos was actually taken). It looks like it is ignored by Memories which uses the nextcloud file timestamp.
However:
- Nextcloud will set the timestamp at the date of upload or sync
- If I manually copy files over the external storage and wait for indexing to complete, then the timestamp is the file creation date

I'm not sure if there is a way around that. Maybe you could also index the exif date data and use it first and then use the file date as a fallback. Maybe that's a lot of work. I don't know.

**Comment by pulsejet** [comment]
Well this isn't related to this issue, so closing this now!
