### ISSUE TITLE
Feature Request - Capitalize Every Word in 'rename person' modal

### ISSUE THREAD

**Issue by farhills** [pulsejet/memories#301]
I am most often accessing Memories from a mobile browser.  It would be handy if the 'rename person' modal defaulted to Capitalize Every Word in the mobile/tablet versions of the page.  

Memories v4.9.2
NC 25.0.2 (docker, linuxserver container)

![image](https://user-images.githubusercontent.com/83388006/208484910-dd9d4e3f-f092-46c8-a250-cadb70fdd1b1.png)

**Comment by pulsejet** [comment]
There are exceptions, such as `Leonardo da Vinci` or `Vincent van Gogh` or [danah michele boyd](http://www.danah.org/name.html).
