### ISSUE TITLE
Possible to run on Docker without NextCloud?

### ISSUE THREAD

**Issue by zodac** [pulsejet/memories#302]
Hey, I really like the look of this project, and would like to use it to host my own media. But I don't have a NextCloud, and don't really want to set one up.

Is it possible to run Memories without needing NextCloud?

**Comment by thomasverelst** [comment]
No and I guess it wouldn't make much sense neither, as it relies on Nextcloud for the file handling, uploads, account management, AI (w Recognize plugin) etc.  If you stick to the basic Nextcloud without extra apps there's barely any unnecessary stuff. Nextcloud can be quite tricky to set up well though so I see the appeal for a simpler setup/installation. I've documented my installation instructions using Nextcloud-AIO here: https://gist.github.com/thomasverelst/60403f22e7a9f5200b0dc43615c54720

**Comment by pulsejet** [comment]
Using the official or AIO docker image is the easiest way for now, since as correctly pointed out, memories does not (and does not intend to) run it's own file management.
