### ISSUE TITLE
Transcode failed

### ISSUE THREAD

**Issue by terrlinde** [pulsejet/memories#305]
Hi
First of all great app, keep up the good work!

I have difficulties to get videos playing at all though.

My setup: 
Intel Pentium Gold G5400T
4GB RAM
Ubuntu 20.04.1 LTS
NC24 running on Apache2

As what I could see is, that transcode is not running entirely, there are no logs in /tmp at all.
Only Logs I could gather are 500 codes from apache2
`192.168.x.x - - [21/Dec/2022:22:06:28 +0100] "GET /index.php/apps/memories/api/video/transcode/mw4l4jwomve0/1423730/max-000000.ts HTTP/1.1" 500 847 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"`
And the reply in browser debugger reads "Transcode failed"

Thanks in advance

**Comment by terrlinde** [comment]
I could gather some additional logs from browser debug (see attachment)
![BrowserConsole](https://user-images.githubusercontent.com/67971159/209473043-43072ace-8d4d-4f11-a86a-73005cd7e0b6.png)

Still no clue where to start looking. Maybe www-data user has not enough permissions to execute scripts server side. Hints appriciated.

**Comment by pulsejet** [comment]
Check the permissions on the `go-vod` executable in `exiftool-bin` in the memories directory. That should be executable by `www-data`. Secondly, try deleting `/tmp/go-vod` if that already exists (the logdir), since it may have incorrect permissions.

**Comment by terrlinde** [comment]
Hi
`go-vod-amd64` was the only one executable in the `exiftool-bin` directory. I added execute permissions to the aarch64 too, no changes. Made all the binaries executable, no changes.
Also still no logfiles in `/tmp`. `www-data` has write permission in `/tmp`, tested with touch.

**Comment by pohuing** [comment]
AppArmor logs are empty, but so are all other logs. There is a folder called go-vod in /tmp, but it too, is empty. Systemd is showing a running go-vod-amd64 process and no further related errors.

I managed to fix my issue by realizing that I don't actually have vaapi available and subsequently disabling it. The :video-setup wizard says I do, but using it causes the transcodes to silently fail.

> Checking for VAAPI (/dev/dri/renderD128)
VAAPI is available. Do you want to enable it? [Y/n]
n

**Comment by terrlinde** [comment]
> I managed to fix my issue by realizing that I don't actually have vaapi available and subsequently disabling it. The :video-setup wizard says I do, but using it causes the transcodes to silently fail.

As I tried this, instead loading videos there was a message displayed "Video transcoding not enabled, enable with setup command"

After updating the memories app to 4.13.1, Nextcloud to 25.0.5.1 and everything else, videos started playing.

Disabling VAAPI is no longer available as an option though.

Renabled memories:video-setup again, got this output:

```
This command will help you setup video streaming
It will check if ffmpeg and ffprobe are installed and go-vod (the transcoder) works
If you are running go-vod externally, feature detection will not work properly
In that case you will need to manually adjust the configuration file (add --print-config)
For details on hardware support: https://github.com/pulsejet/memories/wiki/HW-Transcoding

Press enter to continue or CTRL+C to abort

ffmpeg is installed
ffprobe is installed
Checking for go-vod binary
Trying go-vod from /var/www/ooo.terrlin.de/apps/memories/exiftool-bin/go-vod-amd64
go-vod is installed!

You can use transcoding and HLS streaming
This is recommended for better performance, but has implications if
you are using external storage or run Nextcloud on a slow system.

Read the following documentation carefully before continuing:
https://github.com/pulsejet/memories/wiki/Configuration

Do you want to enable transcoding and HLS? [Y/n]
y

Starting ffmpeg feature detection
This may take a while. Please be patient

Downloading test video file ... OK

Attempting to start go-vod ... OK
go-vod logs will be stored at: /tmp/oc7gmi84pqde.log

Testing transcoding with CPU ... FAIL
CPU transcoding failed with error HTTP status: 404
Check the log file of go-vod for more details (/tmp/oc7gmi84pqde.log)

Checking for VAAPI acceleration (/dev/dri/renderD128) ... OK
Checking for permissions on /dev/dri/renderD128 ... OK
Testing transcoding with VAAPI ... FAIL
VAAPI transcoding failed with error HTTP status: 404
Check the log file of go-vod for more details (/tmp/oc7gmi84pqde.log)
Testing transcoding with VAAPI (low_power) ... FAIL
VAAPI (low_power) transcoding failed with error HTTP status: 404
Check the log file of go-vod for more details (/tmp/oc7gmi84pqde.log)

Checking for NVIDIA acceleration with NVENC
Testing transcoding with NVENC (scale_npp) ... FAIL
Testing transcoding with NVENC (scale_cuda) ... FAIL
NVENC does not seem to be available

Feature detection completed

Transcoding and HLS are now enabled! Monitor the log file for any errors
You should restart the server for changes to take effect

```
Not etirely sure what to do with the warnings although videos are playing now.

**Comment by chiva** [comment]
Having the same output  as @terrlinde.

I have installed the following APKs to add compatibility with Intel QuickSync for transcoding.

`libva-utils libva-vdpau-driver libva-intel-driver intel-media-driver mesa-va-gallium`

Also added `libva-utils` just to be sure:
`apk add libva-utils --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/`

Having the same output as @terrlinde 
Is it expected? Should be fixed? Any way to ensure we are taking advantage of QuickSync?

**Comment by pulsejet** [comment]
Please ignore the output of video-setup. It's broken with 4.13 and is expected to be fixed in v5 (the command `video-setup` is removed entirely in favor of a web UI)

**Comment by pulsejet** [comment]
Stale
