### ISSUE TITLE
[Future request] Sharing single photo

### ISSUE THREAD

**Issue by PrzemekSkw** [pulsejet/memories#307]
It will great to add option to share single photo link for people that don't use my Nextcloud.

**Comment by HyCore** [comment]
yeh, one or multiple photo, like in google photo, without having to create an album

**Comment by EpochalEngineer** [comment]
In particular, sharing individual videos will be particularly useful, taking advantage of go-vod streaming

**Comment by pulsejet** [comment]
![image](https://user-images.githubusercontent.com/10709794/224450825-2ee31f63-de4f-4883-a263-0f42d0413452.png)
![image](https://user-images.githubusercontent.com/10709794/224450837-896633ae-c5dd-448a-90d3-76fd75fa025f.png)
