### ISSUE TITLE
Accents or spaces in folder name make Timeline fail

### ISSUE THREAD

**Issue by Aquariu** [pulsejet/memories#31]
In my configuration:
- NC24.0.5
- php7.4
- mariadb

After a 'occ memories:index' operation completed :
- A folder named "Vélo" with some photos in it, at the root of my files will not display in Timeline while it will work ok if I rename it "Velo" (changing 'é' in 'e') without reindexing everything
- A folder named "lespas" will display in Timeline and stop displaying if I rename it "léspas" (with an added 'é' instead of 'e') and reload the page.
- A folder named "foo bar" will not display anything in the timeline while "foobar" will display correctly

I haven't tested other combination yet.
EDIT : Interrestingly (or maybe not ?) if I select a correct folder name, and a subfolder has spaces and/or accents, its content is displayed correctly in the timeline. THe issue is valid only for top-level folder in the Timeline setting.

**Comment by pulsejet** [comment]
This is because of a sanitizer for the top path. This should be fixed to only remove offending stuff.
https://github.com/pulsejet/memories/blob/3ef562efe386570ce31a37290238c0aa6c33c34c/lib/Exif.php#L76
