### ISSUE TITLE
Some images do not load in Person (Face Recognition)

### ISSUE THREAD

**Issue by sirdrakeistda** [pulsejet/memories#310]
Steps to reproduce:
- open Person (Face Recognition)
- open one Person
- scroll in timeline
![Bildschirmfoto vom 2022-12-24 11-28-29](https://user-images.githubusercontent.com/35723909/209432091-6541ca14-46c7-44af-8830-b88a4a5c4305.png)

I don't think this is caused by a wrong preview setting. In that case it would use a placeholder image instead (this image should show the difference):
![Bildschirmfoto vom 2022-11-28 13-46-42](https://user-images.githubusercontent.com/35723909/209432137-1d7d66e5-dd0f-4485-b85a-7006b236761b.png)

Around 30% of the image do not get loaded and are not clickable. Realoading does not help and on different browser there are always the same images missing. It seems to happen only for not named clusters

**Comment by pulsejet** [comment]
Not related to #230? If related, can close this one.
Still trying to figure out #230, but it definitely has nothing to do with facerecognition.

**Comment by pulsejet** [comment]
Closing as stale. File a new issue if this still persists
