### ISSUE TITLE
Don't see video thumbnails

### ISSUE THREAD

**Issue by PrzemekSkw** [pulsejet/memories#311]
Hi, Memories don't show video thumbnails.

PS. Nectcloud app don't show thumbnails at all. Video or Photos after I install Memories (from December. I see thumbnails from time before but also not video, only photos).

Regards

**Comment by mptr** [comment]
This seems to be a configuration issue that has nothing todo with memories.
I managed to get video previews working, by adding this config:
```php
$CONFIG = array (
  'enable_previews' => true,
  'ffmpeg' => '/usr/bin/ffmpeg', // may need to lookup bin location using `which ffmpeg`
  'enabledPreviewProviders' => array(
    [...] // other entries you want to use
    'OC\\Preview\\Movie',
    'OC\\Preview\\MKV',
    'OC\\Preview\\MP4',
    'OC\\Preview\\AVI'
  )
);
```
Then rescan by running `occ preview:generate-all`
