### ISSUE TITLE
feat: delete currently shown picture with del-key

### ISSUE THREAD

**Issue by mptr** [pulsejet/memories#313]
I would appreciate a feature to allow deleting of the currently visible picture in `memories_viewer` by simply pressing the <kbd>DEL</kbd> or <kbd>&larr;</kbd> keys on my keyboard.

**Comment by ku8az** [comment]
Maybe it can be enhanced by another shortcut for adding a photo to some album/folder for easy images selection during e.g. a process of choosing photos to a photo book etc.

**Comment by pulsejet** [comment]
@ku8az please open a new issue as this isn't related.
