### ISSUE TITLE
QSV failing with "libva: /usr/lib/dri/iHD_drv_video.so init failed"

### ISSUE THREAD

**Issue by wtangofoxtrot** [pulsejet/memories#315]
Getting the following output in `/tmp/go-vod.log`  when I attempt to open a video on nextcloud
```
2022/12/29 05:29:50 Starting VOD server
2022/12/29 05:29:51 cpb2nf0yhyq0: new manager for /data/some-vid.MP4
2022/12/29 05:29:51 cpb2nf0yhyq0-1080p: stopping stream
2022/12/29 05:29:51 cpb2nf0yhyq0-1080p: /usr/bin/ffmpeg -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -autorotate 0 -i /data/some-vid.MP4 -copyts -vf format=nv12|vaapi,hwupload,scale_vaapi=w=1920:h=1080:force_original_aspect_ratio=decrease -maxrate 2760000 -bufsize 5520000 -c:v h264_vaapi -profile:v high -low_power 1 -global_quality 25 -c:a aac -ac 1 -b:a 128k -avoid_negative_ts disabled -f hls -hls_time 3 -force_key_frames expr:gte(t,n_forced*3) -hls_segment_type mpegts -start_number 0 -hls_segment_filename /tmp/go-vod/cpb2nf0yhyq0-2077078844/1080p-%06d.ts -
2022/12/29 05:29:51 ffmpeg-error: [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fe5ce6c0640] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1001
2022/12/29 05:29:51 ffmpeg-error: [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fe5ce6c0640] st: 0 edit list 1 Cannot find an index entry before timestamp: 1001.
2022/12/29 05:29:52 ffmpeg-error: Guessed Channel Layout for Input Stream #0.1 : stereo
2022/12/29 05:29:52 ffmpeg-error: [AVHWDeviceContext @ 0x7fe5d0989cc0] libva: /usr/lib/dri/iHD_drv_video.so init failed
2022/12/29 05:29:52 ffmpeg-error: [h264 @ 0x7fe5cc2a7940] Failed to create decode configuration: 13 (the requested VAEntryPoint is not supported).
2022/12/29 05:29:52 ffmpeg-error: [h264 @ 0x7fe5cc2a7940] Failed setup for format vaapi_vld: hwaccel initialisation returned error.
2022/12/29 05:29:52 ffmpeg-error: [h264_vaapi @ 0x7fe5cc2d3240] No usable encoding entrypoint found for profile VAProfileH264High (7).
2022/12/29 05:29:52 ffmpeg-error: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
2022/12/29 05:29:56 cpb2nf0yhyq0-360p: stopping stream
```

Setup:
- i7-6700k that supports qsv per [intel arc](https://ark.intel.com/content/www/us/en/ark/products/88195/intel-core-i76700k-processor-8m-cache-up-to-4-20-ghz.html) 
- gpu passed through via vfio to an ubuntu host (doing this for an nvidia card as well as that works fine with trans coding in Jellyfin, not been able to get it to work for nextcloud though so falling back to QSV)
- docker container using linuxserver/nextcloud (alpine) that was configured using https://github.com/pulsejet/memories/wiki/QSV-Transcoding

relevant docker-compose:
```
  app:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    volumes:
      - nextcloud_data:/data
      - nextcloud_config:/config
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=libva|libva-intel-driver|intel-media-driver|mesa-va-gallium
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
```
I have made the iGpu accessible by all within the container
```
$ docker exec -it nextcloud bash
root@33c5680f2750:/# ls -l /dev/dri
total 0
crwxrwxrwx 1 root  44 226,   0 Dec 28 22:09 card0
crwxrwxrwx 1 root 109 226, 128 Dec 28 22:09 renderD128
```
config.php has qsv enabled
```
root@33c5680f2750:/# cat /config/www/nextcloud/config/config.php | grep memories
  'memories.exiftool_no_local' => true,
  'memories.no_transcode' => false,
  'memories.ffmpeg_path' => '/usr/bin/ffmpeg',
  'memories.ffprobe_path' => '/usr/bin/ffprobe',
  'memories.transcoder' => '/config/www/nextcloud/apps/memories/exiftool-bin/go-vod-amd64',
  'memories.qsv' => true,
  'memories.nvenc' => false,
  'memories.tmp_path' => '/tmp',
```

Videos never playback unless i set them to Direct.

**Comment by pulsejet** [comment]
Can't be sure, but looks like the bundled va drivers don't support your iGPU (that doesn't make a lot of sense either). You can try [building from source](https://github.com/pulsejet/memories/wiki/QSV-Transcoding#docker-installations), but it might be more complicated on alpine.

Another possibility is a permissions issue. Does the user running php have access to the render128 card? (it needs to be in group with GID 109 inside the docker container; see [the docs](https://github.com/pulsejet/memories/wiki/QSV-Transcoding#docker-installations)).

It might be worth trying this out once with the official image instead of linuxserver (which runs alpine, that is known to have issues with transcoding)

**Comment by wtangofoxtrot** [comment]
@pulsejet did some digging, its possible the intel-media-drivers dont support my igpu per https://github.com/intel/media-driver/issues/1298#issuecomment-986237977 (7th gen but need 9th gen min per comment). For my 7th gen i need to use intel-vaapi-drivers instead but I dont see a package for that under https://pkgs.alpinelinux.org/packages?name=intel-*&branch=edge&repo=&arch=x86_64&maintainer=

**Comment by pulsejet** [comment]
Basically working with alpine sucks 🤡

**Comment by wtangofoxtrot** [comment]
ya gonna see if i can switch to the official debian image without borking anything and trying again

**Comment by wtangofoxtrot** [comment]
From that above thread looks like `intel-media-driver 22.2.2-2` fixes the error, I see alpine has it under https://pkgs.alpinelinux.org/packages?name=&branch=v3.17&repo=&arch=x86_64&maintainer= however `linuxserver/mods:universal-package-install` sitll uses v3.15 which has `intel-media-driver 21.4.1-r0`, anyone know if I can override the mod ? (manually specifying versions doesnt help as:
```      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=libva=2.16.0-r0|libva-intel-driver=2.4.1-r0|intel-media-driver=22.6.3-r0|mesa-va-gallium=22.2.5-r0
```
leads to:
```
**** Installing all mod packages ****

fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz

fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz

ERROR: unable to select packages:

  libva-2.13.0-r0:

    breaks: world[libva=2.16.0-r0]

    satisfies: mesa-va-gallium-21.2.6-r0[libva]

               ffmpeg-libs-4.4.1-r2[so:libva-drm.so.2]

               ffmpeg-libs-4.4.1-r2[so:libva.so.2]

               intel-media-driver-21.4.1-r0[so:libva.so.2]

  intel-media-driver-21.4.1-r0:

    breaks: world[intel-media-driver=22.6.3-r0]

  mesa-va-gallium-21.2.6-r0:

    breaks: world[mesa-va-gallium=22.2.5-r0]
```

**Comment by wtangofoxtrot** [comment]
> Basically working with alpine sucks 🤡

No kidding, I managed to switch over to the official apache docker image and qsv works like a charm now. Probably best to close this off as supporting apline might not be the best use of time.
