### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by beccon4** [pulsejet/memories#318]
To index videos also, I installed ffmpeg and added the entry for enabledPreviewProviders to the config.php as descibed here:

https://github.com/pulsejet/memories/wiki/File-Type-Support

This does not work and renders the Nextcloud instance unusable - due to an PHP syntax error.

It took me a while to figure out that

```
'enabledPreviewProviders' =>
  array (
    'OC\\Preview\\Movie',
    'OC\\Preview\\MKV',
    'OC\\Preview\\MP4',
    'OC\\Preview\\AVI',
  ),
```

actually works - at least marking mp4 webm  and mpeg as "supported".

I'm not so much into PHP but the code sequence in the documentation above looks strange to me. I use PHP 8.1

**Comment by pulsejet** [comment]
The docs are updated now. FYI https://www.php.net/manual/en/language.types.array.php
