### ISSUE TITLE
index creation leaks temp files

### ISSUE THREAD

**Issue by luxifr** [pulsejet/memories#319]
Hi,

idk how to dig into this but I have an issue on my installation, where `occ memories:index` creates temp files, it seems for files on external storage, which it then does not clean up after itself... I only found this out because they filled up my root fs eventually, making almost everything else on my machine come to a halt and it took me a while to find that out because I wasn't expecting that 😅

aaanyway, maybe I'm barking up the wrong tree here and it's on the remote storage implementation in nextcloud - idk... I'd consider myself a rather technical user but I'm not at all familiar with the NC architecture or codebase so if you can give me some pointers, I can help getting to the root of this... it's really bad though so it'd be nice to find a solution for this (also betcause that fs is on an SSD which gets absolutely tortured by this)

Cheers

**Comment by luxifr** [comment]
One more thing I found out is that it doesn't do this for all external storage... I've had the same data mounted via samba before, which is when it would leak temp files, but have now mounted it as "local" storage and the issue does *not* persist

**Comment by eltos** [comment]
I've noticed a similar behaviour for server side encryption where files are temporarily decrypted to `/tmp` (but cleaned up shortly after, see https://github.com/pulsejet/memories/issues/99#issuecomment-1306179562). However, it is related to NC server and not directly controlled by the app (at least in context of encryption).

**Comment by eltos** [comment]
If it helps: there is a [NC config option](https://docs.nextcloud.com/server/16/admin_manual/configuration_server/config_sample_php_parameters.html#all-other-configuration-options) in `config.php` called `tempdirectory`:
> Override where Nextcloud stores temporary files. Useful in situations where the system temporary directory is on a limited space ramdisk or is otherwise restricted, or if external storages which do not support streaming are in use.

**Comment by pulsejet** [comment]
Memories just uses the Nextcloud functions for accessing the files, so this might be a bug in Nextcloud. As @eltos suggested, try changing the temp directory.
