### ISSUE TITLE
Spaces in Timeline Path

### ISSUE THREAD

**Issue by Civlac** [pulsejet/memories#32]
It appears when the 'Timeline Path' specified includes spaces, no images are displayed. If the given path does not include spaces, it has no issues displaying images, including subfolders which have spaces.

Unfortunately my parent folder has spaces in the path, so I am unable to display any media in the Memories app.

I have attempted to add ' and " surrounding the path, however it did not work. Let me know if there is any more information I can provide to help troubleshoot if needed.

Ubuntu 22.04.1 LTS
Memories 1.1.4
NC 24.0.5
PHP 7.4.30

**Comment by pulsejet** [comment]
This is already fixed in https://github.com/pulsejet/memories/commit/8f5c4d061e4621fca5c2c1c39def35a1993571d4

Look for the next release!

**Comment by Civlac** [comment]
💖 Should've checked closed bug reports first 🤦‍♂️

Thanks!
