### ISSUE TITLE
Sidebar not displaying from album view

### ISSUE THREAD

**Issue by NablaMetal** [pulsejet/memories#320]
Nextcloud version: 25.0.2 docker Ubuntu 22.04
Memories version: 4.9.3
Browser: tested with latest chromium, latest firefox on windows and latest samsung browser on Android.

Description:
Side bar (little icon with a circled i) is not displaying anything when the image is loaded from an album. The sidebar does display properly when using same image from timeline view. I tested several images and several account on different browser with same result.

**Comment by pulsejet** [comment]
Known bug. Unfortunately no way to fix this unless the sidebar is fixed upstream to allow non-files DAV paths.

**Comment by pulsejet** [comment]
Partially completed.
Superceded by #464
