### ISSUE TITLE
[feature request] Keep subfolders structure when sharing with public link

### ISSUE THREAD

**Issue by aboulan** [pulsejet/memories#324]
Hello,
When sharing with public link a folder containing subfolders, it would be nice to keep the folder structure in the public view instead of having a flat timeline.

**Comment by Cl00e9ment** [comment]
I had the same thought!
I'm currently working on it. A PR will arrive soon.

**Comment by pulsejet** [comment]
Available with 6.0

**Comment by PeggyFree** [comment]
Excuse me to ask, I switched from the 5.x to the 6.0.1 , I had a message confirming the successful upadte, but I still see my public shares flat instead of seeing folders.

**Comment by Cl00e9ment** [comment]
There is a button on the top right of the page to switch between the timeline view and the folder view.

**Comment by PeggyFree** [comment]
Thank you for your answer. The folder/timeline button toggle finally appeared. I was waiting for this, thank you all.
