### ISSUE TITLE
[feature] index command checks for deleted files

### ISSUE THREAD

**Issue by luxifr** [pulsejet/memories#326]
My workflow is such that I have a Camera Roll folder where all of my mobile uploads end up in - that's photos I've taken, screenshots, basically everything that lands in my phone's Photos app. Now, I sort out things like screenshots into other folders on my Nextcloud, which have a `.nomedia` file. I also move some files into a folder I share with the family. 

However, I very frequently refresh the index so my memories page is always very current. The problem with that is that memories will often index pictures in my Camera Roll folder (which I want to be indexed and shown because I'm not sorting *all* of my pictures into dedicated folders) before I get to sit down and move them away and so they keep showing in my timeline even after I've moved them into a place where they'd be hidden. The only solution to this is to run `index --clean` which is kind of expensive.

```
==========================================
Checked 339811 files of 2 users in 41.524 sec
229862 not valid media items
7 .nomedia folders ignored
109942 skipped because unmodified
0 (re-)processed
==========================================
```

It would be great if the normal index run could just stat every indexed file and remove orphans from the database.

**Comment by pulsejet** [comment]
Good idea.

For now, what you can do is move the screenshots to a folder _outside_ the timeline path. Then they won't show up in your timeline regardless of whether they were/are indexed or not.

**Comment by luxifr** [comment]
That workaround doesn't work for me, sadly... For the screenshots, yes, but for instance I also have sorted folders under my timeline path for different topics where some photos I want in my timeline and some I don't... for those I don't I have a subfolder with a `.nomedia` file in it.

However, I found a way to evict those stale cache entries via the database (well, to be fair: chatgpt wrote this query for me, since I suck at SQL - I just told it what I wanted lol):
`delete a from oc_memories a where a.fileid in (select b.fileid from oc_filecache b where b.parent in (select b2.parent from oc_filecache b2 where b2.name = '.nomedia'));`

This obviously only works for files that went into a folder that itself has a `.nomedia` file, ie. it doesn't follow the logic of inheriting this from parent folders but for my use that is enough.

Some numbers for context:
my oc_filecache table was about 660k rows and my oc_memories table has about 64k rows... so... yeah - rebuilding the whole memories index takes over 6 hours. the query above takes less than a second xD

**Comment by pulsejet** [comment]
With v4.10, you can use `memories:index --cleanup` to remove stale entries (set up a cronjob if you like).
This will be a bit slower than normal indexing.
