### ISSUE TITLE
[Request] Allow translating the app

### ISSUE THREAD

**Issue by teemue** [pulsejet/memories#33]
To make this app even more accessible, an option for volunteers to translate it would be awesome! Like via transifex / weblate.

**Comment by pulsejet** [comment]
I agree. Not 100% sure how Nextcloud does translation, but it should not be too hard.

**Comment by pulsejet** [comment]
Almost there now: https://github.com/nextcloud/docker-ci/issues/416

**Comment by pulsejet** [comment]
Completed
