### ISSUE TITLE
Installation descriptions doesn't tell what to do with "occ memories:index"

### ISSUE THREAD

**Issue by marcijel1** [pulsejet/memories#331]
None of any descriptions tell what should I do with it.
"3. Run php ./occ memories:index to generate metadata indices for existing photos."
"If you just installed Memories, run: occ memories:index"
"Before you begin, make sure you run, occ memories:index"
-says the different pages

How to run occ memories:index?

I'm using the latest **snap** version of NextCloud on ubuntu 22.10

**Comment by pulsejet** [comment]
This is basic Nextcloud stuff; doesn't need to be in the docs. See https://help.nextcloud.com/t/using-occ-on-snap-nextcloud-installation/107129
