### ISSUE TITLE
All videos fail to play

### ISSUE THREAD

**Issue by loadncode** [pulsejet/memories#337]
I have transcoding turned off since I'm using an RPi and none of my videos will play in the Memories app. Some are in mp4 format and some webm (vp8 and vorbis codecs). Either way it makes no difference. This error is displayed on screen:
`The media could not be loaded, either because the server or network failed or because the format is not supported`
Other than that there is no error or other relevant info being generated in any log file.

This is despite the fact that my webm videos play without issue in the Files app and even if I download them and open them directly in firefox or chromium,

`occ memories:index` tells me this:
```
MIME Type support...
  video/mpeg: supported
  video/webm: supported
  video/mp4: supported
  video/quicktime: supported
  video/x-matroska: supported

```

**Comment by christianlupus** [comment]
Hello. There was a [discussion in the forum](https://help.nextcloud.com/t/how-to-debug-an-app/153726) that indicates a bug in the URL generation by the memories app. Can you confirm in the debugging console that the URL requested when opening a video contains `index.php/remote.php`? If yes, this might help the authors of the app to locate and fix the issue.

**Comment by pulsejet** [comment]
Can you try v4.10?

**Comment by loadncode** [comment]
I tried v3.10 as v4.10 isn't supported by my current Nextcloud version. Anyhow, it works, videos are now playing OK, thank you!
