### ISSUE TITLE
"Share" Icon Does Not Work / Does Nothing In Photo View

### ISSUE THREAD

**Issue by gohrner** [pulsejet/memories#339]
When displaying a photo full screen, the "Share" icon in the top right icon bar does not seem to do anyhing.

![image](https://user-images.githubusercontent.com/26199042/212542708-06c21320-b4a6-4185-94a1-0723d8d4dea8.png)

System Report:
Link: https://nextcloud.ohrner.net/s/KwZS4PBxy2SqaJc
Password: TLtqARpzEx

**Comment by pulsejet** [comment]
Which browser? Incognito?

**Comment by gohrner** [comment]
Chromium Version 108.0.5359.71 (Offizieller Build) Built on Ubuntu , running on neon 22.04 (64-Bit)

Interestingly, the share icon does not show up at all in an Incognito window - caching issue?

**Comment by gohrner** [comment]
JavaScript console in a regular browser window:

![image](https://user-images.githubusercontent.com/26199042/214327017-600b709b-690f-4406-841c-dfc1d1e46d22.png)
