### ISSUE TITLE
Scanning stalls every time on specific folder

### ISSUE THREAD

**Issue by RonaldBarnes** [pulsejet/memories#34]
When running `memories:index` or `memories:index --clear`, the process stalls every time it's run and always on the same folder:
```
...
Scanning folder /admin/files/Phone/Photos/2021/12
Scanning folder /admin/files/Phone/Photos/2022
Scanning folder /admin/files/Phone/Photos/2022/01
```
Only a few folders remain unindexed:
```
ls -l data/admin/files/Phone/Photos/2022
total 36
drwxr-xr-x 4 www-data www-data 4096 2022-02-26 16:31 01/
drwxr-xr-x 4 www-data www-data 4096 2022-02-28 20:16 02/
...
drwxr-xr-x 4 www-data www-data 4096 2022-09-13 18:37 09/
```
7442 records in oc_memories.

Setting `log:manage --level 0` shows no relevant messages in the logs.

NextCloud 24.0.5
PHP 7.4.3 (fpm)
Ubuntu 20.04
Memories 1.1.4

If further info needed, just ask. Thanks.

**Comment by pulsejet** [comment]
@RonaldBarnes please try with v1.1.5
It might still stall but should skip the file after 5 seconds or so.

**Comment by RonaldBarnes** [comment]
It worked:

```
==========================================
Checked 10790 files in 227.223 sec
2398 not valid media items
7465 skipped because unmodified
927 (re-)processed
==========================================
```
Thanks @pulsejet, this issue has been resolved.
