### ISSUE TITLE
Shift+click selection does not work

### ISSUE THREAD

**Issue by lmgarret** [pulsejet/memories#340]
Hello! It looks like on desktop web, multi selection using shift + click as described initially in #28 no longer works. 
Memories: 4.9.3. Nextcloud: 25.0.2.
Tested on Firefox 108.0.2 and Brave 1.46.140.
Drag selection on mobile still works (and is pretty smooth!)

Let me know if I can provide you with more info, thanks!

**Comment by pulsejet** [comment]
Does it work at the demo?
https://memories-demo.radialapps.com/apps/memories/

**Comment by lmgarret** [comment]
No it doesn't for both browsers :/ Also tried in private browsing with nearly no browser extension, didn't work as well

**Comment by thomasverelst** [comment]
Note that the shift + click is a bit counterintuitive; for the start of the selection, click on the checkbox (obvious). For the end of the selection, click on the **image** (not the checkbox!). This is similar to Nextcloud Files multi-selection. Did you try this?

**Comment by lmgarret** [comment]
> Note that the shift + click is a bit counterintuitive; for the start of the selection, click on the checkbox (obvious). For the end of the selection, click on the **image** (not the checkbox!). This is similar to Nextcloud Files multi-selection. Did you try this?

Oh right, that was the reason. It's actually working, thanks!
