### ISSUE TITLE
Unable to change Date/time: AxiosError: Request failed with status code 405

### ISSUE THREAD

**Issue by MayeulC** [pulsejet/memories#341]
When I select a picture (or multiple pictures), and then select edit Date/Time from the menu, then enter a new date in the popup, and select "Update Exif data", I get an error message at the top right of my browsing window:

> AxiosError: Request failed with status code 405

And nothing relevant gets printed in the nextcloud logs. I manually installed exiftool on this Debian box, but it didn't fix the issue.

**Comment by MayeulC** [comment]
Thanks for the pointer, it's as you say: a Yunohost 11 Instance on x64 bare metal. I will dig a bit more around the reverse proxy.

**Comment by MayeulC** [comment]
It looks like nginx returns 405 for PATCH requests:

```
 $ curl --request PATCH https://nextcloud.example.com
<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

That's a seldom used verb. [That site](https://gridpane.com/kb/making-nginx-accept-put-delete-and-patch-verbs/) says:
>  it’s considered to be a dangerous HTTP verb to have open. If a plugin or service you’re using requires PATCH to be open, you may want to talk directly with their development team and to discuss security concerns.

That may be something to discuss. I am not aware of what security issues it could entail. Meanwhile, I added the following change to my nginx config (I added the part with `PATCH`):

```nginx
location ~ / {
    if ($request_method ~ ^PUT$) {
        rewrite ^ /index.php$request_uri last;
    }
    if ($request_method ~ ^DELETE$) {
        rewrite ^ /index.php$request_uri last;
    }
    if ($request_method ~ ^PATCH$) {
        rewrite ^ /index.php$request_uri last;
    }
    try_files $uri / /index.php$request_uri;
  }
```

That fixed the issue. I'll discuss a bit further with yunohost maintainers, but I am not completely sure if that's the way to go.

**Comment by pulsejet** [comment]
Weird. I don't know why they'd block PATCH.
