### ISSUE TITLE
memories:video-setup fails

### ISSUE THREAD

**Issue by Draluy** [pulsejet/memories#345]
I use ubuntu and installed ffmeg.

After launching memories:video setup, I get this error:

`
TypeError: strpos(): Argument #1 ($haystack) must be of type string, null given in /var/www/html/custom_apps/memories/lib/Command/VideoSetup.php:67
Stack trace:
#0 /var/www/html/custom_apps/memories/lib/Command/VideoSetup.php(67): strpos(NULL, 'ffmpeg version')
#1 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Memories\Command\VideoSetup->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Memories\Command\VideoSetup), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/console.php(100): OC\Console\Application->run()
#7 /var/www/html/occ(11): require_once('/var/www/html/c...')

`

**Comment by loadncode** [comment]
Have you got ffmpeg installed? If not install it and try again.

**Comment by Draluy** [comment]
Yes, I have ffmpeg installed.

**Comment by pulsejet** [comment]
Try manually configuring the path to ffmpeg and ffprobe https://github.com/pulsejet/memories/wiki/System-config-options

**Comment by pulsejet** [comment]
You need to install ffmpeg and ffprobe inside the docker image, not on the host. The easiest way to do this would be to build a custom image. https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/full/apache/Dockerfile

**Comment by Draluy** [comment]
Ok, thanks. This is  a bit involved for me at the moment, I'll try later :)
