### ISSUE TITLE
'People' list not updating

### ISSUE THREAD

**Issue by phil-lipp** [pulsejet/memories#347]
Until recently I could follow the progress of the recognize app using memories by simply reloading the page whenever a run of recognize was done and the new faces / new images for existing faces would be shown almost immediately. However the list doesn't update any more. The recognize app is definitely working as I can still see the progress in the photos app. Is there a way to fix this or manually trigger the reloading of the list into memories?

In comparison the Photos app has already 630 images in the largest cluster, while memories' version of that cluster only has ~400 images.

**Comment by phil-lipp** [comment]
This query isn't using memories anymore, so that's even weirder. How about this:
```sql
SELECT 
  `rfc`.`id`, 
  `rfc`.`user_id`, 
  `rfc`.`title`, 
  COUNT(DISTINCT f.fileid) AS `count` 
FROM 
  `oc_recognize_face_clusters` `rfc` 
  INNER JOIN `oc_recognize_face_detections` `rfd` ON `rfc`.`id` = `rfd`.`cluster_id` 
  INNER JOIN `oc_filecache` `f` ON `f`.`fileid` = `rfd`.`file_id` 
GROUP BY 
  `rfc`.`id`
```

_Originally posted by @pulsejet in https://github.com/pulsejet/memories/issues/114#issuecomment-1295270656_

**Comment by phil-lipp** [comment]
Sorry for closing and reopening this, I accidentally clicked and "Close Issue" was automatically selected...
While trying to sort out the problem described above I found the following in issue #114 

              This query isn't using memories anymore, so that's even weirder. How about this:
```sql
SELECT 
  `rfc`.`id`, 
  `rfc`.`user_id`, 
  `rfc`.`title`, 
  COUNT(DISTINCT f.fileid) AS `count` 
FROM 
  `oc_recognize_face_clusters` `rfc` 
  INNER JOIN `oc_recognize_face_detections` `rfd` ON `rfc`.`id` = `rfd`.`cluster_id` 
  INNER JOIN `oc_filecache` `f` ON `f`.`fileid` = `rfd`.`file_id` 
GROUP BY 
  `rfc`.`id`
```

_Originally posted by @pulsejet in https://github.com/pulsejet/memories/issues/114#issuecomment-1295270656_
          

Running the query above gives me an output that's matching the Photos app. However why is Memories not using that result?

**Comment by pulsejet** [comment]
The probable reason for this is that not all of your photos in the cluster are in the timeline path. Photos shows everything in the cluster while memories only shows the ones in your timeline.

**Comment by phil-lipp** [comment]
> The probable reason for this is that not all of your photos in the cluster are in the timeline path. Photos shows everything in the cluster while memories only shows the ones in your timeline.

Oh wow, didn't know that! Setting a different timeline path in the settings 'fixed' it.
Thanks for the reply and hopefully this otherwise stupid issue helps other learn about it too

**Comment by pulsejet** [comment]
Not stupid; maybe this needs to be documented somewhere. I'll try to find a good place.
