### ISSUE TITLE
Strange sql bug in latest release

### ISSUE THREAD

**Issue by vvrein** [pulsejet/memories#35]
App: memories: 1.1.4
Nextcloud: 24.0.5
Database: PostgreSQL 14.5
PHP: 8.1.9

Got strange error in `logging` while opening the memories app:

```
OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[42803]: Grouping error: 7 ERROR:
column "f.etag" must appear in the GROUP BY clause or be used in an aggregate function LINE 1:
SELECT "m"."fileid", "f"."etag", "m"."isvideo", "vco"."categ... ^
```

Tried full reinstall as in https://github.com/pulsejet/memories/issues/21#issuecomment-1246634724, without any luck

**Comment by folosleg** [comment]
same here. timeline doesn't load.
let me know if any more details needed
cheers

**Comment by pulsejet** [comment]
Why the hell does every database have different sql behavior ...
Time to write tests

**Comment by vvrein** [comment]
Yay! Can confirm that upgrading to 1.1.5 fixes the issue with timeline opening.
Also, checked that:
 - photos opens
 - videos opens
 - photos deletable
 - photos downloadable
