### ISSUE TITLE
[Feature Request] Allow archiving files through folder view

### ISSUE THREAD

**Issue by Starcr0ss** [pulsejet/memories#350]
I would like the ability to use the archive feature in the folders menu for photos. I appreciate this feature existing within the timeline but it isn't quite as efficient when I am doing something like trying to clean up my timeline after importing a large batch of files. I understand one can just _move the files to the `.archive` folder_ but my server has some weird issue that prevents me from doing this (unrelated to the app).
Thank you for your consideration of this feature, and I appreciate your work on this great app.

**Comment by pulsejet** [comment]
The reason it is disabled in the folder view is that archiving files not in the timeline path might lead to unintended effects. But it might still be possible to achieve this reasonably ...
