### ISSUE TITLE
Rename QSV -> vaapi in documentation and settings

### ISSUE THREAD

**Issue by MayeulC** [pulsejet/memories#351]
Hello, I was confused for a moment: QSV and VA-API are different APIs. I am not sure what QSV stands for except that it's an Intel branding name; I think the QSV API is only available on Windows. Besides that, QSV is probably the equivalent of AMD UVD/VCE/VCN. That is, a physical accelerator. On Linux, the VA-API API is used, which is cross-vendor.

VA-API is available on a lot of different GPUs, from Intel to AMD, to ARM platforms and other video accelerators (also nvidia to an extent with various [software adapters](https://github.com/elFarto/nvidia-vaapi-driver): https://trac.ffmpeg.org/wiki/Hardware/VAAPI

Currently, it looks like the code doesn't properly check for VA-API nor QSV availability, but assumes it is available as long as a DRI node is available: https://github.com/pulsejet/memories/blob/62ae3c910a74b8a2ccef4ddda773954be59d9716/lib/Command/VideoSetup.php#L143

It's OK as a basic check, but it really shouldn't be called QSV as it doesn't have anything to do with QSV, and enabling QSV actually enables VA-API:

https://github.com/pulsejet/memories/blob/8f4d50a37749adf69a6fc3b8876807f4064f84ee/lib/Controller/VideoController.php#L218-L221

This got me confused as I have an AMD card in my server, and the documentation doesn't mention VA-API, only QSV. VA-API works perfectly for h.264 encoding and decoding and HEVC decoding on my server (Debian out of the box, without proprietary software, with only a few mesa-related packets installed). Edit: go-vod would need a tiny extra fix to be compatible with my GPU: https://github.com/pulsejet/go-vod/issues/4

As a side note, the device should probably be selectable: I'd have two if I had an iGPU as well.

**Comment by pulsejet** [comment]
I've updated the wiki page and text. For now the settings needs to stay `memories.qsv` for backward compat.

> Currently, it looks like the code doesn't properly check for VA-API nor QSV availability, but assumes it is available as long as a DRI node is available

I agree it needs a better check. I just have no idea how to do it.

> As a side note, the device should probably be selectable: I'd have two if I had an iGPU as well.

Separate issue.

**Comment by MayeulC** [comment]
Thanks for fixing this!

> I agree it needs a better check. I just have no idea how to do it.

I had a look at this, but didn't find anything obvious. `vainfo` is useful, but it's not actually required for transcoding to work, so it could be used to automatically adjust settings (like using `low_power` for iGPUs) if it's installed, without making it a hard dependency.
