### ISSUE TITLE
Use unix sockets or make go-vod port configurable

### ISSUE THREAD

**Issue by MayeulC** [pulsejet/memories#354]
I have two nextcloud instances on the same host (one personal, that I can break, try stuff on, and share with friends, and one for my family).

They run under different users for compartmentalization (in case there is an issue, misconfiguration, rogue script or intruder), which prevents a go-vod instance launched from a nextcloud install from reading files in the second one. An obvious fix is to launch two instances.

Currently, the port seems to be frozen:

https://github.com/pulsejet/memories/blob/8f4d50a37749adf69a6fc3b8876807f4064f84ee/lib/Controller/VideoController.php#L252

I suggest using a unix socket in the tmp path instead (moreover, permissions can be controlled to avoid data leaks, the interface doesn't seem to be authenticated for now).

An alternative would be to make the port configurable or random.

**Comment by pulsejet** [comment]
Using HTTP simplifies the communication a lot because of first class support in both PHP and golang. I'd stay away from unix sockets and make the port configurable instead.

**Comment by MayeulC** [comment]
I am not fond of granting any program that can communicate with go-vod the ability to exfiltrate data (video files at least, probably anything), but I can understand your reasons, and that sounds reasonable as a first approach.

Note that it doesn't seem too complex to adjust the code to support sockets: https://stackoverflow.com/a/51019379

I think you just need to add a line to:
https://github.com/pulsejet/memories/blob/8f4d50a37749adf69a6fc3b8876807f4064f84ee/lib/Controller/VideoController.php#L257-L260
with:
```php
curl_setopt($ch, CURLOPT_UNIX_SOCKET_PATH, "/some/path/my_socket");
```

It may actually be simpler to manage (what if something already listens on 47788?)

For the go part, `net` seem to support them: https://gist.github.com/teknoraver/5ffacb8757330715bcbcc90e6d46ac74#file-unixhttpd-go

That's the simplest example I could find. Unfortunately, I don't have time for a PR now (nor for a few months, most likely).

**Comment by pulsejet** [comment]
Ah, I didn't consider using curl for the socket operations. Interesting idea.

**Comment by pulsejet** [comment]
```php
  'memories.govod_port' => 47788,
```

**Comment by MayeulC** [comment]
Thanks for making configurable, I decided to try it today.

From the code, it seems like this is now `'memories.vod.bind' => '127.0.0.1:47788'`:

https://github.com/pulsejet/memories/blob/08ba3647deacf357a33e76e58815056cb00f8c56/lib/Controller/VideoController.php#L450-L451

Though migrating the config doesn't seem to have worked for me as it became `127.0.0.1:1`.

However, I'm a bit confused as it seems hardcoded in go-vod:

https://github.com/pulsejet/go-vod/blob/95cfe3fd57961d30734fd51a476de9e2e64d966e/main.go#L148

Moreover, I changed the port in the config, but the self-test routine seems to use the old port:

`CPU transcoding failed with error Curl: Failed to connect to 127.0.0.1 port 47788: Connection refused`.

It seems like the routine still uses the old config entry:
https://github.com/pulsejet/memories/blob/08ba3647deacf357a33e76e58815056cb00f8c56/lib/Controller/VideoController.php#L274

Searching the repository, I couldn't find where the `bind` variable was actually used, so I am a bit confused.

Looking at processes, go-vod doesn't seem to be launched.

**Comment by pulsejet** [comment]
Ahh this slipped through somehow. #477 

> However, I'm a bit confused as it seems hardcoded in go-vod

That is just the default

> Searching the repository, I couldn't find where the bind variable was actually used

https://github.com/pulsejet/memories/blob/08ba3647deacf357a33e76e58815056cb00f8c56/lib/Controller/VideoController.php#L396
