### ISSUE TITLE
Temp directory not cleared during index

### ISSUE THREAD

**Issue by pajades** [pulsejet/memories#355]
I'm running Nextcloud in a proxmox VM. Only 4 active users.
I have ~390 GB of photos on external storage.  
Memories version 4.10.0
Indexing for the first time will not get past ~6%
I get the following error OVER & OVER until the instance completely hangs and I have to reboot the server!

> PHP Notice: fwrite(): write of 4896 bytes failed with errno=28 no space left on device in /var/www/nextcloud/lib/private/log/file.php on line 89
> failed to create memories record: an exception occurred while executing a query: SQLSTATE(53100): Disk Full: 7 ERROR: could not extend file "base/16385/421058" no space left on device

When I exit the neverending cycle of error messages I get this:
![image](https://user-images.githubusercontent.com/60847505/213514557-d4f9786f-bb59-4ca4-90d0-6e6b3a626037.png)

My Nextcloud drives are nowhere near full, in fact they are pretty empty as all my data storage is in external devices...

On top of that, there seems to be an issue with exif data not being read for the files that _are_ indexed. (exiftools _is_ installed and up-to-date).  Though I suspect this might have to do with the indexing not completing/failing ungracefully...

**Comment by pulsejet** [comment]
Seems like PHP thinks you're running out of space on the drive where the log file is stored. As such, this isn't related to memories.

**Comment by pajades** [comment]
thanks for giving me a direction!  I have no clue about PHP...

**Comment by pulsejet** [comment]
I'd check where Nextcloud is trying to write the log file. That might, for instance, be a different drive that's running out of space.

**Comment by pajades** [comment]
Tracked this down to the /tmp directory.
As the indexing progresses, the /tmp directory fills up with image files to the point where there is no room left on the drive.   The system halts yielding an internal server error in the webui.   
Rebooting clears the /tmp directory, but then I have to start the indexing again.
I can, however,  purge the /tmp directory while the indexing progresses to prevent the "no space left on device" error, but man, is that tedious!

**Comment by pulsejet** [comment]
This is a bug. The temp directory should be cleaned regularly.
