### ISSUE TITLE
Live Photos not combined in Album View

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#357]
When viewing photos in an album, the jpg photos and the .mov video file component are not combined into a single live photo:

Memories v4.10.0 on Firefox

![image](https://user-images.githubusercontent.com/10717998/213497477-1cd5d598-54bf-40e3-a872-e757f722280e.png)

**Comment by pulsejet** [comment]
Umm are you sure this is memories? That looks like the Photos app: we don't show such a video logo.

**Comment by meichthys** [comment]
🤦‍♂️ Nope. it was Photos. The exact reason why i use memories! Thanks for all your work on this!
