### ISSUE TITLE
Error with Included Folders - ApiEceptions: Server responded with an HTTP 503

### ISSUE THREAD

**Issue by j3ffery17** [pulsejet/memories#359]
When I try to select and specify the included folders under Account in the Photos app for Android, I get a scrolling wait bar for about 30 seconds then get "ApiEceptions: Server responded with an HTTP 503" error. I am using external storage and was able to set Included folders at one time, however now not able to change. Current included folders are /Photos; /external_photos
Id like to restrict this to only /external_photos

**Comment by pulsejet** [comment]
Memories has no Android app. You're probably using something else.
