### ISSUE TITLE
Use exif data if available instead of file timestamp

### ISSUE THREAD

**Issue by Aquariu** [pulsejet/memories#36]
Although discussed in [https://github.com/pulsejet/memories/issues/30#issuecomment-1246648517
](url), it's a separate issue.

Nextcloud handles file timestamp in an inconsistent way depending on when/how the file got indexed or uploaded.
EXIF metadata on photos, instead, should be pretty stable from the moment the picture was taken.
The app could use the EXIF date/time data in its Timeline sorting function if it is available. of course, reverting to the file timestamp is fine if EXIF data is unavailable or invalid.

This probably should be labeled an Improvement request since it's not a bug really.

**Comment by pulsejet** [comment]
Memories does use Exif data (that's why you need exiftool).
Can you send an example of an offending image for which the Exif data isn't properly read?

**Comment by Sputnikchen** [comment]
Please use
`exiftool picture.jpg | grep Date`
to compare all Dates.
Example:
```
File Modification Date/Time     : 2021:11:03 22:08:05+01:00
File Access Date/Time           : 2022:09:16 11:50:32+02:00
File Inode Change Date/Time     : 2022:05:05 08:09:59+02:00
Modify Date                     : 2018:06:16 14:40:51
Date/Time Original              : 2018:06:16 14:40:51
Create Date                     : 2018:06:16 14:40:51
GPS Date Stamp                  : 2018:06:16
Create Date                     : 2018:06:16 14:40:51.835189
Date/Time Original              : 2018:06:16 14:40:51.835189
Modify Date                     : 2018:06:16 14:40:51.835189
GPS Date/Time                   : 2018:06:16 12:40:50Z
```

**Comment by Aquariu** [comment]
Here's the exif Date data for one file :

`
File Modification Date/Time     : 2022:09:16 16:25:00+02:00
File Access Date/Time           : 2022:09:16 16:25:01+02:00
File Inode Change Date/Time     : 2022:09:16 16:25:00+02:00
Modify Date                     : 2020:08:08 19:32:33
Date/Time Original              : 2020:08:08 19:32:33
Create Date                     : 2020:08:08 19:32:33
`
As you can see the file access/modification is 2022,while the Create and Modify date are 2020.
In the File app, the metadata for this file shows a 2020 date. which is why I raised the issue in the first place thinking that exif data was not used (I was wrong of course)

**Comment by Sputnikchen** [comment]
It's using "Date/Time Original"
I've changed all dates like above and it shows 2003:10:16

**Comment by pulsejet** [comment]
2003?

**Comment by Sputnikchen** [comment]
Yes
```
# exiftool picture.jpg | grep Date
File Modification Date/Time     : 2022:09:16 18:32:36+02:00
File Access Date/Time           : 2022:09:16 18:34:16+02:00
File Inode Change Date/Time     : 2022:09:16 18:34:15+02:00
Modify Date                     : 2001:10:16 14:40:21
Date/Time Original              : 2003:10:16 14:40:21
Create Date                     : 2002:10:16 14:40:21
Metadata Date                   : 2004:10:16 14:40:21
Digital Creation Date           : 2005:10:16
Date Created                    : 2006:10:16
Create Date                     : 2002:10:16 14:40:21.63
Date/Time Original              : 2003:10:16 14:40:21.63
Date/Time Created               : 2006:10:16 11:07:44
Digital Creation Date/Time      : 2005:10:16 11:07:44
```

**Comment by pulsejet** [comment]
Ah I see what you mean. I thought you were talking about OP's file haha.

Yes, it first dates in the order, if available, `Date/Time Original` --> `CreateDate` --> Unix Creation Time --> Unix Modified Time

Closing this issue.

**Comment by Aquariu** [comment]
Dear all,
I'm not sure why I didn't succeed in getting my point accross to you and why the topic was closed. If I did something wrong please explain.

Here's a picture where:

`21:32 drake@mackfixe ~ % exif IMG_20200808_190743.jpg | grep Date`
`Date et heure       |2020:08:08 19:07:43`
`Date et heure (origi|2020:08:08 19:07:43`
`Date et heure (numér|2020:08:08 19:07:43`

Exif Date and time in 2020

Linux date and time in 2022 : 
`21:33 drake@mackfixe ~ % ls -l | grep IMG `
`-rw-rw----  1 drake drake 602K sept. 11 23:25 IMG_20200808_190743.jpg`


This particular image is displayed at the very top of my Timeline while I assumed that it would be sorted along with the rest of the 2020 photos.
![IMG_20200808_190743](https://user-images.githubusercontent.com/22145986/190873794-def201e2-fd8e-48a7-84fe-73e7eb40a51c.jpg)

**Comment by pulsejet** [comment]
The exif data for the file seems fine to me. Can you try re-indexing with `occ memories:index -f`?

**Comment by Aquariu** [comment]
I did that and no change.
Another photo taken with another camera (another smartphone) with more exif data. This one is also sorted with the September the 11th 2022 photos instead of the August 2020.

```
% exiftool 20200807_155642.jpg | grep Date
File Modification Date/Time     : 2022:09:11 23:29:01+02:00
File Access Date/Time           : 2022:09:17 13:50:24+02:00
File Inode Change Date/Time     : 2022:09:19 05:00:09+02:00
Modify Date                     : 2020:08:07 15:56:42
Date/Time Original              : 2020:08:07 15:56:42
Create Date                     : 2020:08:07 15:56:42
Create Date                     : 2020:08:07 15:56:42.0477
Date/Time Original              : 2020:08:07 15:56:42.0477
Modify Date                     : 2020:08:07 15:56:42.0477
```

I also tried something new but not with the results I expected : 
- Go to a photo folder that is correctly sorted by Memories in 2007
- Download this photo folder from Nextcloud as zip archive
- Unzip on my desktop computer. Here's the resulting exif data
```
# exiftool IMGP1052.JPG | grep Date
File Modification Date/Time     : 2022:09:20 14:37:25+02:00
File Access Date/Time           : 2022:09:20 14:37:25+02:00
File Inode Change Date/Time     : 2022:09:20 14:37:25+02:00
Modify Date                     : 2007:01:25 01:56:47
Date/Time Original              : 2007:01:25 01:56:47
Create Date                     : 2007:01:25 01:56:47
Date                            : 2007:01:25
Manufacture Date                : Unknown (0)
```

- Delete the photos from NC folder
- Upload unzipped photos from my desktop to the same NC folder
Here's the photos sitting on external storage (SFTP):
```
% ls -l
total 12M
-rw-rw---- 1 drake drake 1,5M sept. 20 14:37 IMGP1052.JPG
```

Here's a screenshot with the "age" of the photos (16 years old) in Nextcloud.
![CaptureNextcloud](https://user-images.githubusercontent.com/22145986/191260551-b20fb815-63e1-4c46-a228-f72c46ad72db.PNG)


In contrast with the case above, the image I showed to you in hte post above is shown as September the 11, 2022 in the Nextcloud Files interface and not its original date.  I don't understand the difference between both cases.

- Reindex, restart php-fpm, clear browser recent history, clear cache, reload

Result: These are correctly sorted in the 2007 photos. 

I don't understand the difference between this and the photo uploaded above.

I tested something else:
- Created a folder named "test" at the root of my nextcloud, 
- uploaded the same 2007 photos in it.
- Uploaded one of those 2020 photos which cause problem because the Timeline sets it in 2022.
-  Set "test" as Timeline folder
Result : 
- photos from 2007 correctly set in 2007 in the Timeline
- Photo from 2020 correctly set in 2020 in the Timeline

So it probably has something to do with either External Storage, this specific external storage or the way Nextcloud indexes external storage. I will try to look into it.

THis shows that your sorting logic works correctly and that I have something I don't understand on my side. This issue can be closed and I apologize for making you reopen it.

But I will create another issue because photos of another folder named "testupload" are ALSO in the SAME  "test" Timeline display. If I create another folder named "testest" its content will also be displayed in the Timeline. if I set "tes" instead of "test" in the Timeline, all of these will still be displayed in the Timeline.

Kind regards,

Olivier

**Comment by pulsejet** [comment]
Hmm, this is strange; maybe a bug when using SFTP. When you do `occ memories:index -f`, did it display any errors at all?

**Comment by Aquariu** [comment]
> Hmm, this is strange; maybe a bug when using SFTP. When you do `occ memories:index -f`, did it display any errors at all?

No it didnt. I will try a "local" external storage and report.

**Comment by illnesse** [comment]
pretty sure you need to do a files:scan before memories:index after adjusting dates

**Comment by pulsejet** [comment]
Stale. Please file a new issue since pretty much everything has changed since.
