### ISSUE TITLE
[Wish] Default to "Direct" when playing videos, transcode only when necessary 

### ISSUE THREAD

**Issue by Gymnae** [pulsejet/memories#364]
While I like the ability to play virtually any video via transcoding, would it be viable to have the default as "Direct" and only fallback to transcoding if the client cannot play the video? 

This assumes that some kind of communication between the player and the viewport occurs.

Alternatively, could there be a setting to set the default behavior? I find that the default "Auto" settings transcodes videos, which could also be played directly and in their original quality, while the auto setting often is too grainy.

**Comment by pulsejet** [comment]
The quality is saved for subsequent videos, so if you choose direct once then all videos should play in direct henceforth.

**Comment by Gymnae** [comment]
I see that, what about first time visitors or mobile users? Could the default be direct?

**Comment by pulsejet** [comment]
Good point. That could be made a global config setting.

**Comment by pulsejet** [comment]
Supports `video_default_quality` now. See https://github.com/pulsejet/memories/wiki/System-config-options

**Comment by Gymnae** [comment]
Perfect, thank you again for being quick to react to change requests.

**Comment by Gymnae** [comment]
I just noticed that direct does not appear to work for shared albums, when a not logged-in user tries to play a video. Is that as intended because direct requires rights to access the file?

**Comment by pulsejet** [comment]
@Gymnae no, it should work the same. Do you get any error anywhere (JS console / network tab / nextcloud logs)?

**Comment by Gymnae** [comment]
> @Gymnae no, it should work the same. Do you get any error anywhere (JS console / network tab / nextcloud logs)?

It works again after I updated to the latest release, so all good :)
