### ISSUE TITLE
Error configure memories:video-setup

### ISSUE THREAD

**Issue by itProfi** [pulsejet/memories#369]
Hello! I have insal NextCloud from snap https://github.com/nextcloud-snap/nextcloud-snap
When i try `sudo nextcloud.occ memories:video-setup` i see `sh: 1: ffmpeg: not found
ffmpeg is not installed
sh: 1: ffprobe: not found
ffprobe is not installed
ffmpeg and ffprobe are required for video transcoding
Without transcoding, video playback may be slow and limited
Do you want to disable transcoding and HLS streaming? [y/N]`

Ffmpeg is installed: 
`root@nextcloud:~# locate ffmpeg
/usr/bin/ffmpeg
/usr/share/doc/ffmpeg
/usr/share/doc/ffmpeg/changelog.Debian.gz
/usr/share/doc/ffmpeg/copyright
/usr/share/ffmpeg
/usr/share/ffmpeg/ffprobe.xsd
/usr/share/ffmpeg/libvpx-1080p.ffpreset
/usr/share/ffmpeg/libvpx-1080p50_60.ffpreset
/usr/share/ffmpeg/libvpx-360p.ffpreset
/usr/share/ffmpeg/libvpx-720p.ffpreset
/usr/share/ffmpeg/libvpx-720p50_60.ffpreset
/usr/share/lintian/overrides/ffmpeg
/var/lib/dpkg/info/ffmpeg.list
/var/lib/dpkg/info/ffmpeg.md5sums
root@nextcloud:~# locate ffprobe
/usr/bin/ffprobe
/usr/share/ffmpeg/ffprobe.xsd
root@nextcloud:~#
`

What can i do?

**Comment by pulsejet** [comment]
Configure it manually
https://github.com/pulsejet/memories/wiki/System-config-options
