### ISSUE TITLE
[Feature Request] Sort albums by name

### ISSUE THREAD

**Issue by IndrekHaav** [pulsejet/memories#377]
Looks like right now albums are sorted by creation date, most recent to oldest.

I think it would make more sense to sort them by name. This would make finding a specific album easier once there's a lot of them. Also, with some attention to the naming scheme, one could have related albums together, chronologically (start album name with year), thematically (start album name with a keyword like "Trip", "Birthday", "Wedding", etc), or something else. Current sort order affords no such control.

Hopefully this is something that can be changed and isn't fixed by the Photos app.

**Comment by pulsejet** [comment]
![image](https://user-images.githubusercontent.com/10709794/223543857-079f5e66-1366-489c-b92b-b864da1d97f9.png)
