### ISSUE TITLE
SERVER EXECUTION ERROR

### ISSUE THREAD

**Issue by HHUBSS** [pulsejet/memories#385]
Whenever I setup memories, have done index and video-setup, I get an execution error like below.
![image](https://user-images.githubusercontent.com/89816305/215680049-371a526a-e5c0-4c1c-92d1-c8aad5eadef5.png)
 
I can't restart or stop the container. It says gateway timeout when I open the GUI. This is actually my 3rd time installing my nextcloud instance because of this. This time, I just removed the memories app from /app folder remove the "memories....." lines in config, restart my server and it works again.

![image](https://user-images.githubusercontent.com/89816305/215681093-1984f9fe-0a82-46f2-80ea-81b6755e970d.png)

What could be wrong with my setup?

OS: Unraid 6.11.5
Nextcloud: 25.0.3 (LSIO image)

**Comment by pulsejet** [comment]
You need to pull some logs from the server / nextcloud. Impossible to debug otherwise.
