### ISSUE TITLE
Google HEVC Live videos transcode

### ISSUE THREAD

**Issue by thermatk** [pulsejet/memories#388]
Following the great #373 fix (https://github.com/pulsejet/memories/commit/457ac16db18587adb0658b254d5a05267285d366), Google's motion photos are HEVC as well sometimes, including provided example, so need fix like for #234 (https://github.com/pulsejet/memories/commit/f5cfa095ce79ce28883c269ab0e3cfbecbe2d17d) to extend to them.

Unfortunately, couldn't understand the structure to make a PR, as far as I understood the code block with transcoding should just be generally applied to the blobs and try to transcode them all, if it really does nothing for H264 anyway:

https://github.com/pulsejet/memories/blob/cf5ebf199d7f9925a8296e93139f00b6fbf1e44e/lib/Controller/VideoController.php#L176-L183

**Comment by pulsejet** [comment]
Hmm. AFAIK Firefox has zero support for HEVC (https://caniuse.com/hevc), yet the video from the example plays for me in FF on Windows.

**Comment by vitis586** [comment]
Yes, Google has a complicated relationship with H.265. Still my Pixel is taking live photos with H.265 video in them. At least that is what I get when I hit export as video in the phone. When I also export the picture, the sizes of the picture plus video roughly adds up to same size as the original live photo.
![image](https://user-images.githubusercontent.com/55784861/218257550-90315008-b261-4a2a-bf51-74141753190e.png)

I created a folder on Gdrive with a sample. The *.MP.jpg is the orignal live photo.
https://drive.google.com/drive/folders/1k46sv2Y83ROOFOST7rNQmwH22rJ0IKeu?usp=sharing

**Comment by thermatk** [comment]
Here is a sample photo:
![PXL_20221203_164832006 MP](https://user-images.githubusercontent.com/2287483/218267049-dafc2450-1a8c-4bdf-a8cf-f30fc86ad502.jpg)

What I extract out of it matches what memories feeds to firefox byte-for-byte. And it's HEVC

Extraction code:
```
for i in PXL*.jpg; do \
  ofs=$(grep -F --byte-offset --only-matching --text ftypisom "$i"); \
  ofs=${ofs%:*}; \
  [[ $ofs ]] && dd "if=$i" "of=${i%.jpg}.mp4" bs=$((ofs-4)) skip=1; \
done
```

**Comment by thermatk** [comment]
yeah, it's true the other sample had H264 actually. So they made the switch in Android 12+, because both pictures come from the same Pixel and only recent are all HEVC, sorry.

**Comment by pulsejet** [comment]
> What I extract out of it matches what memories feeds to firefox byte-for-byte. And it's HEVC

Btw you can just do "Download Video" and it'll get the original video in the photo for you.

![image](https://user-images.githubusercontent.com/10709794/218269062-45cad265-9b97-4131-9a1d-955824db8ef3.png)
