### ISSUE TITLE
Since 1.1.5 no images displayed anymore

### ISSUE THREAD

**Issue by apg1980** [pulsejet/memories#39]
FIles are already indexed.
Path is given.
worked before.
nginx, php 8.1, mariadb, nextcloud 24 (latest)

**Comment by pulsejet** [comment]
Cannot reproduce here. Any logs? Try turning on the debug mode in Nextcloud and see the logs for the `days` call int he inspector.

**Comment by folosleg** [comment]
This one appears to be the case, when path is more than one folder deep.
Like /InstantUpload works fine, but /InstantUpload/Camera does not.
Hope it could be any help.

**Comment by pulsejet** [comment]
Ha! Now that I can reproduce. May be unrelated though -- @apg1980 can you confirm?

**Comment by pulsejet** [comment]
Please test with v1.1.6 @folosleg @apg1980

**Comment by apg1980** [comment]
> Please test with v1.1.6 @folosleg @apg1980

its working again, thank you

**Comment by pulsejet** [comment]
Perfect ✔️

**Comment by folosleg** [comment]
100%! thanks for the quick fix!
