### ISSUE TITLE
How to enable "You must enable "Mark person in preview" to use this feature"

### ISSUE THREAD

**Issue by vdheidenet** [pulsejet/memories#393]
Hi,

I'm lost, no newby, but no idea where to change this setting.

After face recognition some photos are linked to the wrong person.
In the preview there is a way to move this photo to another person.

The error message "You must enable "Mark person in preview" to use this feature"  pops up.

Ok, and now? Where? Not in settings? Nothing found in documentation.

Can someone please give me a hint where to enable this setting?

Thanks,
Marco

**Comment by pulsejet** [comment]
It's in the three dot menu after opening a face without selecting anything.
https://github.com/pulsejet/memories/issues/79#issuecomment-1283006285
