### ISSUE TITLE
Only newly uploaded photos are showing on new map.

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#401]
- I've re-indexed
- I've force-refreshed webpage (on firefox)

Memories:  4.11.0-beta.2
Nextcloud: 25.0.4 RC1

**Comment by pulsejet** [comment]
Did you do a forced re-index? (`occ memories -f`)?

**Comment by meichthys** [comment]
Oo i didn't know i had to use the Force! Thanks. (https://github.com/pulsejet/memories/issues/404 would be nice!)
![image](https://user-images.githubusercontent.com/10717998/218166338-f92d85b9-db45-4887-9432-502019ba7bea.png)
