### ISSUE TITLE
Error when update to 4.11.0 version

### ISSUE THREAD

**Issue by itProfi** [pulsejet/memories#407]
Today will try update from version 4.10.3 - and server will stop. When disable app, install from occ command line see
`root@nextcloud:~# sudo -u www-data /var/www/html/occ app:install memories
Error: Database error when running migration 400000Date20221015121115 for app memories
The column 'w' on table 'oc_memories' already exists.
`
And server will not work, until i disable app from command line..(
check:app will show:
`root@nextcloud:~# sudo -u www-data /var/www/html/occ integrity:check-app memories  - EXCEPTION:  - class: OC\IntegrityCheck\Exceptions\InvalidSignatureException  - message: Signature data not found.
`
When i delete tables 'oc_memories' and  'oc_memories_livephoto' an  try install app:
`
root@nextcloud:~# sudo -u www-data /var/www/html/occ app:install memories -vvv
Error: Database error when running migration 400000Date20221015121115 for app memories
Memories table does not exist
`

**Comment by pulsejet** [comment]
Looks like your database is messed up. Uninstall the app and run this SQL:

```sql
DROP TABLE IF EXISTS oc_memories;
DROP TABLE IF EXISTS oc_memories_livephoto;
DROP TABLE IF EXISTS oc_memories_mapclusters;
DROP TABLE IF EXISTS oc_memories_places;
DROP TABLE IF EXISTS oc_memories_planet;
DROP INDEX IF EXISTS memories_parent_mimetype ON oc_filecache;
DELETE FROM oc_migrations WHERE app='memories';
```

Then install the app again.

**Comment by itProfi** [comment]
Thanks! After that, i see:
`
root@nextcloud:~# sudo -u www-data /var/www/html/occ app:remove memories -vvv
memories disabled
memories 4.11.0 removed
root@nextcloud:~# sudo -u www-data /var/www/html/occ app:install memories -vvv
memories 4.11.0 installed
memories enabled
`
When i check app, i see:
`Error: file_get_contents(/var/www/html/apps/memories/appinfo/signature.json): Failed to open stream: No such file or directory at /var/www/html/lib/private/IntegrityCheck/Helpers/FileAccessHelper.php#44
`
`
root@nextcloud:~# sudo -u www-data /var/www/html/occ integrity:check-app memories
  - EXCEPTION:
    - class: OC\IntegrityCheck\Exceptions\InvalidSignatureException
    - message: Signature data not found.
   `

**Comment by pulsejet** [comment]
No idea why it is looking for the signature. Maybe it should be inside `custom_apps` instead of `apps`? Did you install from the Nextcloud store?

**Comment by darkobas** [comment]
> ```sql
> DROP INDEX IF EXISTS memories_parent_mimetype ON oc_filecache;
> ```
nextcloud_db=> DROP INDEX memories_parent_mimetype ON oc_filecache;
ERROR:  syntax error at or near "ON"
LINE 1: DROP INDEX memories_parent_mimetype ON oc_filecache;

**Comment by pulsejet** [comment]
What database is this? You can try removing the `IF EXISTS` clause

**Comment by darkobas2** [comment]
> What database is this? You can try removing the `IF EXISTS` clause

Postgress 14.6. yes i already tried it... After some more fiddling i was able to reinstall memories... It stopped complaining that this table exists

**Comment by pulsejet** [comment]
You probably need to delete `/tmp/go-vod`. It might have wrong permissions/ownership.
