### ISSUE TITLE
Will media on external storage be downloaded?

### ISSUE THREAD

**Issue by lukaszervudakis** [pulsejet/memories#410]
Hi, I'm using Nextcloud on my NAS and I'm sharing my media library with Nextcloud as an external storage. In the configuration steps, it says "Indexing may be slow, since all files must be downloaded from the storage.". Does this mean that all media files will be downloaded from my external storage to Nextcloud?

**Comment by pulsejet** [comment]
Yes, there's no way to get the exif data from a file without downloading it.

**Comment by lukaszervudakis** [comment]
Thanks.

Is there a occ comand to remove the downloaded files? Or is it enough to just remove the memories app?

**Comment by pulsejet** [comment]
They're cleaned up automatically. If not, they'll be in /tmp
