### ISSUE TITLE
Folder setup, no picttures found

### ISSUE THREAD

**Issue by andreapx** [pulsejet/memories#415]
When I first opened the app it asked me to choose a folder. I've selected the folder where I keep all my pictures, but it couldn't find any. I then selected to go on, but now I can't find the settings of this app where I can set the root folder.

**Comment by pulsejet** [comment]
Did you follow the installation instructions?

```
occ memories:index
```

The root folder setting is on the memories page bottom left.

**Comment by andreapx** [comment]
> Did you follow the installation instructions?
> 
> ```
> occ memories:index
> ```

Ah, dammit! I didn't notice them when I've installed it, thanks!

> 
> The root folder setting is on the memories page bottom left.

Thanks!
The root folder is setup as //InstantUpload, but the index process is scanning my whole storage (and it's taking veeeeery long since I have a lot of video files in other folders). Shouldn't it index just the selected folder?

**Comment by pulsejet** [comment]
It'll index the entire storage, but this is a one time process. If you want to exclude anything from indexing, but a `.nomedia` file at the top folder you want to exclude.

**Comment by andreapx** [comment]
Thanks!
I think that file with all the exclusion path would be nice.
