### ISSUE TITLE
Feature Request: Allow for update of geolocation

### ISSUE THREAD

**Issue by RikkiBC** [pulsejet/memories#418]
The new Maps integration is amazing! However it allowed me to find out that, oddly, some of my photos have 0,0 explicitly set as their lat,long.

I would love if there was a feature that allowed me to change their location. Simplest might be something like choosing the town name (confirmed by state, postcode, country etc. so that I don't accidentally choose the wrong country which has a town with the same name), and it updates the photo's lat,long to the centrepoint of that town, or to the closest point within the town boundary if the centrepoint is not within the town boundaries.

**Comment by NIronwolf** [comment]
I'd love to adjust the location of a lot of my photos as well or add the info in the first place to the photos from the DSLR with not GPS data.

**Comment by RikkiBC** [comment]
> This might be possible on the Nextcloud Maps app. If you right click on the map somewhere you will get a popup which has a "Place photos" option. You can then browse to select a photo.
> 
> I'm not sure if this actually updates the exif data on the photo, or if the maps app somehow keeps track of where you want that photo to show up.
> 
> Either way, it would be better if additional exif fields were exposed for modifying directly in Memories.

Alas, the last time I used the Nextcloud Maps app, it completely pinned my server unresponsive at 100% CPU usage, only solvable with a forced server restart, each time I tried to use it (I have well over 10,000 photos and I guess it couldn't handle it). Hence why I'm happy to see a more performant maps view in Memories - and would love to see features added here instead.

**Comment by vimodev** [comment]
It would also be great if it supported geotagging for videos, a lot of tools seemingly do not, whereas some do.

**Comment by pulsejet** [comment]
![image](https://user-images.githubusercontent.com/10709794/223798058-1cff8280-2f47-435f-b3cf-4607f3330355.png)

**Comment by pulsejet** [comment]
> It would also be great if it supported geotagging for videos, a lot of tools seemingly do not, whereas some do.

Seems to work for videos out of the box, at least as far as I tested

**Comment by NIronwolf** [comment]
Oh, is there also a way to REMOVE the GPS data?

**Comment by pulsejet** [comment]
> Oh, is there also a way to REMOVE the GPS data?

Now there is

![image](https://user-images.githubusercontent.com/10709794/223826803-d01a5a0d-8cb3-402f-8a4c-c01ca707930e.png)

**Comment by whitemanthedj** [comment]
Whenever I add a photo with a negative longitude, it seems to replace it with the positive value. Is there a negative dropped somewhere? When adding the values, there is also an asterisk (guessing there is a problem somewhere with the negative)

![image](https://user-images.githubusercontent.com/44525898/229430117-6e066475-0470-42d7-b713-906a90895b53.png)

**Comment by pulsejet** [comment]
@whitemanthedj this is fixed in v4.13
