### ISSUE TITLE
Ignore locations with zero GPS Latitude/Longitude...

### ISSUE THREAD

**Issue by matiasdelellis** [pulsejet/memories#420]
I guess a picture is worth a thousand words.. 😅 
![imagen](https://user-images.githubusercontent.com/733715/219002240-f667b422-e96a-478b-b8f9-e679ddbb04fc.png)

```
SELECT Count(*)
FROM `oc_memories`
WHERE `lat` = 0

Count(*)
199
```

But as a small explanation, the oc memories table considers nulls, but some phones (I guess just old phones because google infers the location with anything.), when it does not find the gps, write 0.0, which also should also be ignored.

Thanks again for all the work. I hope I have time to get involved in my integrations. 😃

**Comment by pulsejet** [comment]
We just need to filter these out in `Exif` itself. If it's `0,0`, it makes no sense to keep anywhere.

**Comment by pulsejet** [comment]
Should be fixed in the next version. You'll need to run `occ memories:index -f`.

**Comment by pulsejet** [comment]
Note: if you don't want to re-index, you can just run the follow SQL to set the wrong values to NULL (tested on mysql)
```sql
UPDATE oc_memories
SET lat=NULL,lon=NULL
WHERE lat > -0.0001 AND lat < 0.0001
  AND lon > -0.0001 AND lon < 0.0001
```
