### ISSUE TITLE
[Docker] [ARM64] [ALPINE] Failed to create stay_open exiftool process

### ISSUE THREAD

**Issue by ErikSteiner** [pulsejet/memories#423]
Hardware: Raspberry Pi 4 Model B
OS: Ubuntu 22.10 (GNU/Linux 5.19.0-1013-raspi aarch64)

Hi there, I use the docker image `nextcloud:25.0.3-fpm-alpine` and would like to use the Memories App. I managed to pull the necessary files from [GitHub](https://github.com/nextcloud/docker/tree/c1a52325422d08def6aa9d30028e04a96432abf0/25/fpm-alpine), in order to build the image by myself, so I can add `exiftool` to the image. I use Portainer, and it worked out very well, however `exiftool` is installed to the following location `/usr/bin/exiftool` and I assume that Memories is not able to detect it.

If I run `docker exec -u www-data -it nextcloud-app php occ memories:index -f`, I get the following output:
```
Checking database indices

MIME Type support:
  image/png: supported
  image/jpeg: supported
  image/heic: not supported
  image/png: supported
  image/tiff: not supported
  image/gif: supported
  image/bmp: supported
  image/x-dcraw: not supported
  video/mpeg: not supported
  video/webm: not supported
  video/mp4: not supported
  video/quicktime: not supported
  video/x-matroska: not supported

Some file types are not supported by your preview provider.
Please see https://github.com/pulsejet/memories/wiki/File-Type-Support

WARN: Failed to create stay_open exiftool process
Exiftool timeout: [/var/www/html/custom_apps/memories/exiftest.jpg]
Couldn't read Exif data from test file: Could not read from Exiftool
FATAL: exiftool could not be executed or test failed
Make sure you have perl 5 installed in PATH
```

Is there anything that I am missing?

[Dockerfile](https://github.com/pulsejet/memories/files/10753115/Dockerfile.txt)

__EDIT:__
From analyzing your code, I see that the official docker image does not need Exiftool, as the binary location is set up within the Memories App: `/var/www/html/custom_apps/memories/exiftool-bin/`

In `config.php` `'memories.exiftool'` is set to `'/var/www/html/custom_apps/memories/exiftool-bin/exiftool-aarch64-musl'`

If I log into the container and `cd /var/www/html/custom_apps/memories/exiftool-bin/exiftool` and execute `exiftool ../../exiftest.jpg`, I am able to parse the image.

**Comment by pulsejet** [comment]
Seems like a bug, but not sure how to debug this. You could try logging what output PHP is getting after running exiftool.

**Comment by ErikSteiner** [comment]
From my first look at the Nextcloud.log, when debug is enabled, it seems like I need a debugging tool like XDebug. That puts a bit of a hurdle in here to be able to debug it. I'll have to read up on that first.
Would it be possible for you to send me the command that causes this message at that point, and I'll run it in the container? [Failed to create stay_open exiftool process](https://github.com/pulsejet/memories/blob/fc122196952258a07ceb59fe9f15a92e3f51935f/lib/Exif.php).

**Comment by ErikSteiner** [comment]
Is it possible that the wrong version of exiftool is delivered? Something similar happened with the app Recognize: ["I seem to have not considered ARM64 users may be running Alpine as well"](https://github.com/nextcloud/recognize/issues/688#issuecomment-1436038918). With this [commit 30602dc](https://github.com/nextcloud/recognize/commit/30602dcfa972257f4fae1534fb2419ef319acdb9).

**Comment by pulsejet** [comment]
The shipped binary that it was trying to use was arm musl, so it should work fine. Did you try running the shipped binary?

**Comment by ErikSteiner** [comment]
OK, I guess, that this is something useful:
```
/var/www/html/custom_apps/memories/exiftool-bin # ./exiftool-aarch64-musl -ver
/tmp/par-726f6f74/cache-exiftool-12.50/exiftool-aarch64-musl: exec of /tmp/par-726f6f74/cache-exiftool-12.50/exiftool-aarch64-musl (custom Perl interpreter) failed (errno=13)
```

**Comment by outadoc** [comment]
Same issue here, same error message when trying to run the binary manually from within the image. I'm running the linuxserver Nextcloud image.

**Comment by pulsejet** [comment]
This seems like some permissions issue. Can you try deleting `/tmp/par-*` directory?

**Comment by thtwice** [comment]
Hi, same problem here on a docker image based on debian.
Perl is installed and if I try to run `./var/www/html/custom_apps/memories/exiftool-bin/exiftool-aarch64-glibc /var/www/html/custom_apps/memories/exiftest.jpg` i get this the same error as @ErikSteiner : `/tmp/par-726f6f74/cache-exiftool-12.50/exiftool-aarch64-glibc: exec of /tmp/par-726f6f74/cache-exiftool-12.50/exiftool-aarch64-glibc (custom Perl interpreter) failed (errno=13)`

Tried removing the /tmp/par-* directories but behavior stayed the same.

**Comment by tincanfury** [comment]
I've enabled "use system perl", however I still get,

```
root@dc78d8b48107:/# occ memories:index
WARN: Failed to create stay_open exiftool process
sh: perl: not found
failed to run exiftool: perl /config/www/nextcloud/apps/memories/exiftool-bin/exiftool/exiftool -ver
```

**Comment by tincanfury** [comment]
@pulsejet in the Docker container or the main system?

main system:
```
$ perl --version

This is perl 5, version 34, subversion 0 (v5.34.0) built for x86_64-linux-gnu-thread-multi
(with 57 registered patches, see perl -V for more detail)

Copyright 1987-2021, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

**Comment by pulsejet** [comment]
@tincanfury in the container.

**Comment by major-mayer** [comment]
Is it expected that those `exiftool` binaries have no execute permission by default? 
I know that i can change this using chmod, but will it survive an upgrade?
(I am using Nextcloud in Docker as a non-root user if that's relevant.)

```
I have no name!@eedd9c00afd1:/var/www/html/custom_apps/memories/exiftool-bin$ ls -al
total 31072
drwxr-xr-x 3 1100 1100       9 Apr 29 23:01 .
drwxr-xr-x 9 1100 1100      14 Apr 29 23:01 ..
drwxr-xr-x 6 1100 1100      17 Apr 29 23:01 exiftool
-rw-r--r-- 1 1100 1100 7288895 Apr 29 23:02 exiftool-aarch64-glibc
-rw-r--r-- 1 1100 1100 9648446 Apr 29 23:02 exiftool-aarch64-musl
-rw-r--r-- 1 1100 1100 7597448 Apr 29 23:02 exiftool-amd64-glibc
-rw-r--r-- 1 1100 1100 9171510 Apr 29 23:02 exiftool-amd64-musl
-rw-r--r-- 1 1100 1100 4718592 Apr 29 23:02 go-vod-aarch64
-rwxr-xr-x 1 1100 1100 5038080 Apr 29 23:02 go-vod-amd64
```

**Comment by pulsejet** [comment]
> Is it expected that those `exiftool` binaries have no execute permission by default?

They don't need to be executable. The binaries are copied to `/tmp` (with a different name) and chmod to be executable there and then only the temp binaries are used.

**Comment by tincanfury** [comment]
I guess I'm still not clear on why the binary won't run on a docker image running on Ubuntu, nor why I would need to install Perl every time I update the docker image.

**Comment by pulsejet** [comment]
@tincanfury you mention you're on x86 but the package doesn't bundle 32 bit binaries. So you need perl to run exiftool.

You don't install perl every time you, just use a custom Dockerfile with docker compose (`build: ` instead of `image:`)

**Comment by tincanfury** [comment]
`Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-70-generic x86_64)`

**Comment by tincanfury** [comment]
not sure if this is of any help,
`# ldd /config/www/nextcloud/apps/memories/exiftool-bin/exiftool-amd64-musl 
        /lib/ld-musl-x86_64.so.1 (0x7fbac4ff6000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7fbac4ff6000)`
or,
`# ldd /config/www/nextcloud/apps/memories/exiftool-bin/exiftool-amd64-glibc 
        /lib64/ld-linux-x86-64.so.2 (0x7ff47a8e9000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7ff47a8e9000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7ff47a8e9000)`

**Comment by pulsejet** [comment]
Okay, seems like the linuxserver image?

What do you get for `docker exec -it <nc-container> </path/to/nextcloud/apps/memories/exiftool-bin/exiftool-amd64-musl> -ver`?

**Comment by tincanfury** [comment]
> Okay, seems like the linuxserver image?
yes
 
> What do you get for `docker exec -it <nc-container> </path/to/nextcloud/apps/memories/exiftool-bin/exiftool-amd64-musl> -ver`?

$docker exec -it nextcloud /config/www/nextcloud/apps/memories/exiftool-bin/exiftool-amd64-musl -ver
OCI runtime exec failed: exec failed: unable to start container process: exec: "/config/www/nextcloud/apps/memories/exiftool-bin/exiftool-amd64-musl": permission denied: unknown

**Comment by pulsejet** [comment]
I'd say lets wait and see for the next release keeping this open. Turned a few knows for the musl builds.

**Comment by tincanfury** [comment]
was able to get direct access to my working installation and checked to see what the difference was between my working and non-working installation. The non-working installation I had set it up with /tmp as tmpfs, where as my working installation I did not. This was the key to figuring out that in order for tmpfs to allow the file to execute I needed to have it set up as,
    tmpfs:
      - /tmp:exec
in the docker compose file.

Now I no longer get the error under EXIF Extraction, I am able to run the exiftool command from the /tmp location, and indexing is now working.

**Comment by pulsejet** [comment]
Ha, great catch! This definitely needs to go to the docs.

**Comment by outadoc** [comment]
> was able to get direct access to my working installation and checked to see what the difference was between my working and non-working installation. The non-working installation I had set it up with /tmp as tmpfs, where as my working installation I did not. This was the key to figuring out that in order for tmpfs to allow the file to execute I needed to have it set up as, tmpfs: - /tmp:exec in the docker compose file.

Thank you!! This worked. The reason I had a `tmpfs` set up in this way is because that is what is recommended [by the docs of Recognize (right in the README)](https://github.com/nextcloud/recognize/tree/eb78169ae151048e554720790c7153445ba09686#tmp).

I think we won't be the only ones to have followed this advice, so mentioning it in this project's setup documentation might be a good idea indeed.

For the record, my docker-compose file used to look like this:

```yaml
    volumes:
      - nextcloud-data:/config
      - /mnt/data/Cloud:/data
      - type: tmpfs
        target: /tmp
```

and this fixes the issue:

```yaml
    volumes:
      - nextcloud-data:/config
      - /mnt/data/Cloud:/data
    tmpfs:
      - /tmp:exec
```

**Comment by pulsejet** [comment]
It's there in the docs already: https://memories.gallery/troubleshooting/#usage-of-tmpfs

**Comment by tincanfury** [comment]
> Thank you!! This worked. 

now I need to figure out how you get your code clips to be highlighted like that 🤦‍♂️

**Comment by pulsejet** [comment]
> now I need to figure out how you get my code clips to be highlighted like yours 🤦‍♂️

Just put them inside three backticks followed by the language name.

````markdown
```yaml
    volumes:
      - nextcloud-data:/config
      - /mnt/data/Cloud:/data
    tmpfs:
      - /tmp:exec
```
````

**Comment by PierrePetit** [comment]
Hello !

I just had the issue, while installing memories on my docker container (image: lscr.io/linuxserver/nextcloud:26.0.2).
The solution was to run
```bash
docker exec --user root nextcloud apk add perl
```
And restart the container.

I guess I didn't think about it because it is not mentioned in the requirements of the docs :
https://memories.gallery/install/#requirements

It might be obvious for most people, but not for me 😞 
Maybe it could be added to the requirements 😇 

Thanks !

**Comment by pulsejet** [comment]
It's not a requirement. Did you turn on "Use system perl" in the admin panel?

**Comment by pulsejet** [comment]
> Ah, yes ! I guess it's not required, only recommended, to have full functionalities, you're right.

Not exactly. The thing is: Memories comes bundled with perl for Linux on `amd64` and `aarch64`. So the cases where you should need `perl` installed are:
1. 32-bit arch, e.g.. x86 or an old RPi
2. BSD
3. A misconfiguration (e.g. `tmpfs` as described above)

Since this is a very small fraction of users (also neither case is well supported), it should _just work_ for most people (which is why `perl` isn't a _requirement_. In any case, the admin panel is quite descriptive with helpful information for what's happening.

**Comment by PierrePetit** [comment]
The command 
```bash
uname -a
```
returns : 
```bash
Linux 25d4fe456b61 6.2.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct  6 10:23:26 UTC 2 x86_64 GNU/Linux
```
So Definitely not 1.

The image used is based on alpine, so not 2. either.

I tried with and without the following in my docker-compose : 
```yaml
tmpfs:
   - /tmp:exec
```
With :  
![image](https://github.com/pulsejet/memories/assets/4937633/0acfa8da-7da1-4b7d-9a61-f33cdfb9eebd)

Without : 
![image](https://github.com/pulsejet/memories/assets/4937633/2a875774-356b-4a38-a425-de2450d30a05)

Using system perl (after reinstalling the container):
![image](https://github.com/pulsejet/memories/assets/4937633/a66a3543-3899-4da2-9c8d-60b9d5ec6b7a)

Could it be a permissions issue ? 

I have to go, i'll check your response tomorrow. 
Thanks a lot for helping ! 😄

**Comment by pulsejet** [comment]
Well the problem in this case is it's trying to use the debian binary (`glibc`) of exiftool while you're on alpine (`musl`). By any chance did you change the docker image at any point?

Try this ([from](https://memories.gallery/troubleshooting/#moving-from-x86-to-arm-or-vice-versa)):
```bash
occ config:system:delete memories.exiftool
occ config:system:delete memories.vod.path
occ maintenance:repair
```

Or if this doesn't work, maybe set the binary explicitly
```bash
occ config:system:set memories.exiftool "/config/www/nextcloud/custom_apps/memories/exiftool-bin/exiftool-amd64-musl"
```

(or just manually edit `config.php` to set these values)

**Comment by PierrePetit** [comment]
Good guess, I did change from the nextcloud image to the linuxserver one. I kept the config files when I migrated, so that's probably the issue.

I ran the first 3 commands, and now have (still with the tmpfs config) :

![image](https://github.com/pulsejet/memories/assets/4937633/01a38f31-aed9-4675-86d8-817a17f477dd)

Here is my whole config.php for reference : 
```php
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/config/www/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/config/www/nextcloud/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => '************',
  'passwordsalt' => '************',
  'secret' => '************',
  'trusted_domains' => 
  array (
    0 => '172.16.0.2:8083',
    1 => '************.net',
    2 => 'nextcloud',
  ),
  'social_login_auto_redirect' => true,
  'datadirectory' => '/config/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '26.0.7.0',
  'overwrite.cli.url' => 'https://************.net',
  'dbname' => 'nextcloud',
  'dbhost' => 'nextcloud-mariadb',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => '************',
  'installed' => true,
  'filelocking.enabled' => true,
  'overwritehost' => '************.net',
  'overwriteprotocol' => 'https',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'default_phone_region' => 'FR',
  'redis' => 
  array (
    'host' => 'redis',
    'password' => '************',
    'port' => 6379,
  ),
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'trusted_proxies' => 
  array (
    0 => 'swag',
  ),
  'forwarded_for_headers' => 
  array (
    0 => 'HTTP_X_FORWARDED_FOR',
  ),
  'maintenance' => false,
  'loglevel' => 0,
  'encryption.key_storage_migrated' => false,
  'theme' => '',
  'debug' => true,
  'trashbin_retention_obligation' => '30, 35',
  'app_install_overwrite' => 
  array (
    0 => 'documentserver_community',
    1 => 'user_saml',
  ),
  'memories.vod.ffmpeg' => '/usr/bin/ffmpeg',
  'memories.vod.ffprobe' => '/usr/bin/ffprobe',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'smtp************.net',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'service',
  'mail_domain' => '**********.net',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpname' => '************@************.net',
  'mail_smtppassword' => '***********',
  'memories.gis_type' => 1,
  'memories.exiftool' => '/config/www/nextcloud/custom_apps/memories/exiftool-bin/exiftool-amd64-musl',
  'memories.vod.path' => '/config/www/nextcloud/custom_apps/memories/exiftool-bin/go-vod-amd64',
);
```

**Comment by pulsejet** [comment]
@PierrePetit it should work now, you can ignore the Perl warning :)

**Comment by PierrePetit** [comment]
Thanks a lot for your help !

**Comment by GitKalle** [comment]
For FreeBSD users they run the Nextcloud instance in a jail. The same problem occurs in the jail, when the `/tmp` folder is not mounted as executable. What I've done to solve the problem, see [post](https://www.truenas.com/community/threads/howto-set-up-tmpfs-in-a-jail-for-transcoding-or-zoneminder.60842/post-581331) for more information. I also mount the `/tmp` folder as a tmpfs.

1. Stop the jail
2. Delete jail `/tmp` contents, leaving it empty
3. Edit the fstab for the relevant jail and add the line: (in contrast to the linked post, I delete the option `noexec`)
`tmpfs <full path to jail root from the host>/tmp tmpfs rw,nosuid,size=4G,mode=01777 0 0` (adjust `size=4G` accordingly)
4. Start jail.
