### ISSUE TITLE
occ memories:places-setup -> polygon not supported?

### ISSUE THREAD

**Issue by scubao** [pulsejet/memories#427]
Hi,

I very much like nextcloud + memories and tried to setup the reverse geocoding now.
Tried with MariaDB first, then PostgresQL, same result unfortunately.

Import into the Database works, but the index afterwards fails.

ab81b9f3346:/var/www# occ memories:index -f
Checking database indices

In AbstractPlatform.php line 398:
                                                                                                              
  Unknown database type polygon requested, Doctrine\DBAL\Platforms\PostgreSQL100Platform may not support it.  

Memories	4.11.0
-
Art: pgsql
Version: PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
-
PHP
Version: 8.1.14
-
Version
[Nextcloud Hub 3](https://nextcloud.com/) (25.0.3)

Anybody seen this?

**Comment by pulsejet** [comment]
By any chance did you change the database table prefix? Or are tables still prefixed with `oc`

**Comment by scubao** [comment]
I guess so, haven't changed anything but will have a look and report back here.

**Comment by scubao** [comment]
Hi, checked the tables within the nextcloud database - no prefix at all. eg:

nextcloud | public | accounts | BASE TABLE | NULL | NULL | NULL | NULL | NULL | YES | NO | NULL
nextcloud | public | accounts_data | BASE TABLE | NULL | NULL | NULL | NULL | NULL | YES | NO | NULL
nextcloud | public | activity | BASE TABLE | NULL | NULL | NULL | NULL | NULL | YES | NO | NULL
nextcloud | public | activity_mq | BASE TABLE | NULL | NULL | NULL | NULL | NULL | YES | NO | NULL
nextcloud | public | addressbookchanges | BASE TABLE | NULL | NULL | NULL | NULL | NULL | YES | NO | NULL
nextcloud | public | addressbooks | BASE TABLE | NULL | NULL | NULL | NULL | NULL | YES | NO | NULL
nextcloud | public | appconfig | BASE TABLE | NULL | NULL | NULL | NULL | NULL | YES | NO | NULL
nextcloud | public | authorized_groups | BASE TABLE | NULL | NULL | NULL | NULL | NULL | YES | NO | NULL

**Comment by pulsejet** [comment]
Memories will refuse to setup the planet table if no prefix is configured starting the next version. As a result, this will no longer be an issue.
