### ISSUE TITLE
People View

### ISSUE THREAD

**Issue by jakobroehrl** [pulsejet/memories#43]
In NC 25 there is a People View I like very much, this is generated by https://apps.nextcloud.com/apps/recognize
Maybe showing it in memories would by neat:

![grafik](https://user-images.githubusercontent.com/24530680/190568030-b7b33b5a-0bf7-49c7-8277-3b9f697e12a2.png)

**Comment by pulsejet** [comment]
This is definitely useful. It might take a _lot_ of time to implement though since unfortunately I'm working alone and nobody else is contributing to this repo yet.
