### ISSUE TITLE
Not recognising JPGs/JPEGs

### ISSUE THREAD

**Issue by gecoz** [pulsejet/memories#431]
I recently downloaded Memories onto my Nextcloud instance but, when following the setup and providing it with a folder containing 22.1GB of photos (recognised by Nextcloud Photos 2.0) the message "Nothing to show here" has popped up and no images have been processed by the application. I don't currently have access to the Nextcloud terminal (and therefore couldn't complete all of the ideal setup steps outlined in Github), though I believe this shouldn't be the issue stopping the application from reading my image files. I have redownloaded the application but this issue still persists.

**Comment by pulsejet** [comment]
> couldn't complete all of the ideal setup steps outlined in Github

The installation steps aren't optional; it won't work unless you follow them.
