### ISSUE TITLE
Planet geometry table doesn't have prefix

### ISSUE THREAD

**Issue by IndrekHaav** [pulsejet/memories#432]
I was poking around in my NC database and noticed that the `memories_planet_geometry` table doesn't have the same `oc_` prefix as all the other tables. An oversight, I assume?

**Comment by pulsejet** [comment]
Intentional. This table uses database specific extensions that mess with the ORM if they have the same prefix. Incidentally it also means this doesn't work if you have no prefix for the other tables (#427).
