### ISSUE TITLE
Reverse Image preview concern?

### ISSUE THREAD

**Issue by Dulanic** [pulsejet/memories#433]
I am really confused why this is happening. I am trying memories for the first time, and I added HEIC suppport etc... and its working great. But it is saying the basic images (jpg, png, bmp) at not supposerted? Very confusing and I have no idea where to even start with this. I trying adding them to enabledPreviewProviders but it did nothing.

Nextcloud can load them without issue, but memories says it cannot be displayed.

```
root@bd4c15e5af0f:/# occ memories:index
Checking database indices

MIME Type support:
  image/png: not supported
  image/jpeg: not supported
  image/heic: supported
  image/png: not supported
  image/tiff: supported
  image/gif: not supported
  image/bmp: not supported
  image/x-dcraw: not supported
  video/mpeg: supported
  video/webm: supported
  video/mp4: supported
  video/quicktime: supported
  video/x-matroska: supported

Some file types are not supported by your preview provider.
Please see https://github.com/pulsejet/memories/wiki/File-Type-Support

Scanned /redacted/files
Scanned /redacted/files
==========================================
Checked 153603 files of 2 users in 86.407 sec
151278 not valid media items
0 .nomedia folders ignored
2325 skipped because unmodified
0 (re-)processed
==========================================
```

![image](https://user-images.githubusercontent.com/2948206/220397948-412e007f-15eb-4741-a1d8-25a434dfd7f7.png)

**Comment by pulsejet** [comment]
https://github.com/pulsejet/memories/wiki/File-Type-Support

Do you have `OC\\Preview\\Image` in `enabledPreviewProviders`?

**Comment by Dulanic** [comment]
I am going to facepalm this one. LOL totally my bad! I don't know how I missed that. I just read the "enabled by default".
