### ISSUE TITLE
Unable to find memories on docker linuxserver/nextcloud

### ISSUE THREAD

**Issue by noahcub** [pulsejet/memories#434]
I can't find the app memories on the Nextcloud App Store. Is  still available?

**Comment by pulsejet** [comment]
Yes, maybe it's a cache issue. Nextcloud caches the list of apps.

**Comment by noahcub** [comment]
ok, thanks. How can I flush the cache list?
I execute occ maintenance:repair and the app isn't available in my server.

**Comment by pulsejet** [comment]
Are you looking in the right section? It should be in multimedia. Also it's not a featured app.

**Comment by noahcub** [comment]
Oh yes, I'm looking in multimedia and ins't available. Maybe it's a problem in my nextcloud store. I will reinstall nextcloud docker and find it again.

**Comment by pulsejet** [comment]
Very strange. Calling the Nextcloud store API directly does seem to include memories in the response: https://apps.nextcloud.com/api/v1/platform/25.0.0/apps.json

**Comment by noahcub** [comment]
I can't solve it, and I decided reinstall nextcloud official docker.
Now everything works perfectly.
I close the issue.
