### ISSUE TITLE
Database issue when trying to run (User Error).

### ISSUE THREAD

**Issue by JoshuaPettus** [pulsejet/memories#435]
NC25, PostgreSQL 15.2, PHP-8.1, Nginx

This is definitely on me.  A while ago I had tried memories and removed it.    I was having some sort of database issue and didn't want to bother fixing it at the time.  I noticed removing the app did not clear the memories tables out of the database so I manually removed them (May have not been a good idea).     Anyway I'm installing the current version and wanted to try again.  It gave me an error that the memories table didn't exist.  So I created it and added the columns it wanted (little strange as It should have done that automatically I'd expect).   Now after indexing the images I open the app in NC and I get

`An exception occurred while executing a query: SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: bigint = character varying
LINE 28: ..."m" INNER JOIN "oc_filecache" "f" ON "f"."fileid" = "m"."fil...
^
HINT: No operator matches the given name and argument types. You might need to add explicit type casts.`

Clearly it is not happy.  Is there a way to clean the slate?  Simply removing the app doesn't seem to do it.

**Comment by JoshuaPettus** [comment]
Never mind,  I found the FAQ, sorry didn't know you had one.  Apparently I didn't remove enough.  In anycase  I noticed in the FAQ

> DROP INDEX IF EXISTS memories_parent_mimetype ON oc_filecache;

So you know the ON isn't part of pgsql syntax.  I think I got it just by removing "ON oc_filecache"

**Comment by JoshuaPettus** [comment]
Actually reopening 

When generating the index, I get 

```
Could not scan folder /joshuapettus/files/Media/Pictures/2023: An exception occurred while executing a quer││ F ▄▄▄▄▄▄▄▄▄▄▄5.11 Gi│U ■■■■■■■■■■■■■■  49M││    1525 redis-se /usr/bin/re redis  9.0M ▄▗▗▄▄  0.4  │
y: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "memories_planet_geometry" does not exist          │├─────────────────────├─www────────────1.9G─┤│     161 kworker/             root     0B ▗▄▄▖▄  0.4  │
LINE 1: SELECT DISTINCT(osm_id) FROM "memories_planet_geometry" WHER..
```
It's strange as It didn't generate that table

**Comment by pulsejet** [comment]
Just run occ memories:places-setup

If you don't download the planet it'll disable reverse geocoding.

**Comment by JoshuaPettus** [comment]
Lol, download the planet is indeed quite as extreme as it sounds.  It's running now, I guess it will take at least a few hours.  But now it seems the rest of the images will now import as well.  It seems if your images have geocoding data, and you didn't run places-setup, it can't index them (or any other photos past that point alphabetically). It will skip the rest of the folder.  Don't know if that's the way you want it.
