### ISSUE TITLE
Can't rename person with 'z' in name

### ISSUE THREAD

**Issue by sirdrakeistda** [pulsejet/memories#437]
Setup:
- Nextcloud 25.0.3
- Debian
- memories version 4.11.0
- facerecognition version: 0.9.11

Steps to reproduce:
- Open image in timeline
- open sidebar
- click on people (facerecognition must be installed)
- rename person with a 'z' in the name

Expected:
- names with 'z' are allowed

actual behavior:
- instead of typing a 'z' in the edit, it zooms in the image

**Comment by sirdrakeistda** [comment]
You won't have the people tab, it you don't use facerecognition

Am 23. Februar 2023 19:39:30 MEZ schrieb MeIchthys ***@***.***>:

**Comment by meichthys** [comment]
@sirdrakeistda Nextcloud Recognize will enable the people tab.
I don't have face recognition yet:
![image](https://user-images.githubusercontent.com/10717998/221003476-9c378efd-ffe6-477f-aea4-1758a7a1d476.png)
And i still have the people tab in Memories:
![image](https://user-images.githubusercontent.com/10717998/221003546-0e88f192-2396-4d9d-9887-5ca502ab89a6.png)

**Comment by rhatguy** [comment]
Same issue with my install.  Seems like the "z" key is being picked up by the zoom functionality instead of being passed to the name box.

**Comment by meichthys** [comment]
Interesting. Is this browser related? I'm using Firefox.

**Comment by meichthys** [comment]
@sirdrakeistda Ah. Gotchya! I'm definitely going to have to check out FaceRecognition 👍
