### ISSUE TITLE
Timeline path for shared folder

### ISSUE THREAD

**Issue by valterbarreira** [pulsejet/memories#44]
I have Nextcloud in Yunohost, and the folder i want to set in timeline, is a shared folder between two users.
The folder is called Fotos and the path that is configured as a "local external storage" is /home/yunohost.multimedia/share/Picture.

I have set the path as Fotos, /Fotos , Fotos/ and also /home/yunohost.multimedia/share/Picture, but no photos appear in timeline.
What i'm doing wrong?

**Comment by Sputnikchen** [comment]
I store my pictures at the same host, but an external directory which is in ../../Fotos/ (relative to nextcloud) mounted at /Fotos/
./occ memories:index says:
[...]
Scanning folder /myname/files/Fotos/2015/01
Scanning folder /myname/files/Fotos/2015/02
Scanning folder /myname/files/Fotos/2015/03
[...]
But it only works if I'm in a folder.

**Comment by pulsejet** [comment]
Please read the README carefully.

If your external storage is mounted as `/external` in Nextcloud, you need to put your images in another subdirectory inside external, say `/external/Photos`. Then you configure the timeline path as `/Photos/`, which will show photos from here.

If you're sharing the same external storage between users you also need a cron job for the index command. Also note that using the Nextcloud folder "sharing" feature for sharing timeline photos _will not work_.

**Comment by pulsejet** [comment]
Note: For v2, just configure the path to the mountpoint. You also no longer need the cron job.

**Comment by valterbarreira** [comment]
So i've set /home/yunohost.multimedia/share/Picture as path and nothing appear. Do i have to run the php ./occ memories:index command on these folder?

**Comment by pulsejet** [comment]
You need to set to to your Nextcloud Mount point, so I doubt that's right.

For example if the storage is mounted as `/external` in your Nextcloud home, then set the timeline path to that

**Comment by valterbarreira** [comment]
The path of the folder is mounted as Fotos, and i've set the timeline path as /Fotos/ but gives an error that there's no photos, do i have to run the index command on these folder?

**Comment by valterbarreira** [comment]
I have run the index command and it's working now. Thank you for this great app.
