### ISSUE TITLE
Error when indexing: Failed to create memories record: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4353836' for key 'oc_memories.memories_fileid_index'

### ISSUE THREAD

**Issue by wonx** [pulsejet/memories#440]
Hi, 

I'm getting these errors when indexing new files.

`Failed to create memories record: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4353836' for key 'oc_memories.memories_fileid_index'`

I think it's because memories was doing the initial index in a folder, which contained lots of non-relevant images. So I stopped the indexing, i added a `.nomedia` file in that folder, and restarted the indexing. Now, when reaching that point, I get this error for most records.

I guess there are some records in the DB that could be deleted to correct this?

**Comment by pulsejet** [comment]
Shouldn't be happening, since it updates existing entries...
Try `occ memories:index --clear`

**Comment by wonx** [comment]
After running the memories:index again, I think I'm not seeing that error anymore. Give me a few minutes to confirm, but it was probably a false alarm.

**Comment by wonx** [comment]
Ok, I get it now. When I closed the indexer doing Ctrl+C, it didn't really killed them and it continued in the background. So I found that there were already 3 or 4 indexers working at the same time, probably creating these conflicts.
