### ISSUE TITLE
Reverse Geocoding - How to Import Boundary Dataset to MySQL and memories:places-setup is not working

### ISSUE THREAD

**Issue by kevinkuan1969** [pulsejet/memories#443]
Nextcloud 25.0.3
MySQL - 8.0.32
PHP - 8.1.14

Quite new to Memories and started to play around for about 3 weeks. 
It is one of the best with good performance application so far in Nextcloud for me.

All the setup and configurations are done and work perfectly except the reverse geocoding to display the places.

So far the steps to develop boundary dataset as below:

 - download planet.osm.pbf using wget 

# Install GDAL and OSMIUM
 sudo apt install -y gdal-bin osmium-tool python3 python3-pip

# Install geo python deps
python3 -m pip install shapely joblib tqdm

# Extract boundaries from planet
osmium tags-filter planet.osm.pbf wra/boundary=administrative -o boundaries.osm.pbf

# Convert boundaries to CSV format
mkdir -p csv && cd csv
ogr2ogr -f "CSV" -lco SEPARATOR="TAB" -lco GEOMETRY=AS_WKT -overwrite -makevalid boundaries.csv ../boundaries.osm.pbf
cd ..

# This will create multipolygons.csv that contains the data we need. To create the SQL file:
python3 dump-geo.py

# Create zip file
zip -9 planet_coarse_boundaries.zip planet_coarse_boundaries.txt

The next step i presume is to import the zip file to Mysql but no idea on how to do it.
Someone can help to guide especially the SQL syntax and to which table? Currently the tables for Memories are:

- oc_memories                           
- oc_memories_livephoto            
- oc_memories_mapclusters       
- oc_memories_places                
- oc_memories_planet

The last issue is memories:places-setup and not successful with the error as below:

Attempting to set up reverse geocoding
MySQL-like support detected!
No MySQL-like support detected
No Postgres native geometry support detected
No supported GIS type detected

Hope someone can help and thanks in advance.

**Comment by pulsejet** [comment]
Okay, so you don't need to do all this; the planet boundary database is already available. All you are missing is this patch: https://github.com/pulsejet/memories/commit/dd84e31eb96fdb45de235fa7696798de4f84ca26

Apply this and run `places-setup` and you're good to go.

**Comment by kevinkuan1969** [comment]
Thanks @pulsejet for your great and prompt help.
Everything works well as below:
![image](https://user-images.githubusercontent.com/80019930/221396219-a704334e-db8d-4551-9c65-7d0bebb021f7.png)

But discovered some error from the Log as below.


![image](https://user-images.githubusercontent.com/80019930/221396200-979e0e94-a0fd-4e75-a73d-4819715df380.png)

**Comment by pulsejet** [comment]
This is fixed in v4.11.1+

**Comment by kevinkuan1969** [comment]
Noted and thanks
