### ISSUE TITLE
Renaming persons to already existing name causes issues 

### ISSUE THREAD

**Issue by phil-lipp** [pulsejet/memories#447]
To reproduce just give a cluster the name of an existing cluster.
For me (weirdly) one of the two is happening:
- the first cluster disappears and is replaced with the newly named cluster
- both cluster disappear

This behaviour is quite destructive as there's a deleted cluster is lost form good and there's no easy way for a classification rerun on only the lost face recognitions.
Marcel Klehr already pushed a fix for this in the Photos app, but that probably doesn't apply to memories

See https://github.com/nextcloud/recognize/issues/695 for more info.

**Comment by pulsejet** [comment]
The same fix applies. We use the recognize WebDAV api for these operations.

**Comment by SolidTux** [comment]
This actually happened to me again just now. Did some recent update reintroduce this bug?

**Comment by phil-lipp** [comment]
> This actually happened to me again just now. Did some recent update reintroduce this bug?

Yeah had the same happening yesterday.
Especially when using the Enter key after typing in a name for a cluster is tricky, cause if it registers the key twice then the cluster is just gone...
