### ISSUE TITLE
Indexing Error in v4.11.+ (relation "memories_planet_geometry" does not exist)

### ISSUE THREAD

**Issue by martin-nohava** [pulsejet/memories#448]
Hi, thank you for amazing gallery app!

Unfortunately in recent versions after updating from v4.10.3 (to v4.10.+) I get following error when uploading new images to my Nextcloud instance.

```
Could not scan folder /<user_folder>: An exception occurred while executing a query: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "memories_planet_geometry" does not exist
LINE 1: SELECT DISTINCT(osm_id) FROM "memories_planet_geometry" WHER...
```

After this error occurs, the folder is skipped and no more images are added to the Memories. I assume this problem is related to not having the planet boundary dataset downloaded (`occ memories:places-setup`), but it was not required in previous versions. It looks like reverse-geocoding feature could be still _enabled_ even when dataset is not downloaded.

Is it still possible to use Memories without downloading the dataset? (I would much prefer that.)

(Possibly related #435)

Thanks

**Comment by pulsejet** [comment]
I'm a bit confused here. You can do one of two things basically:
1. Turn on reverse geocoding. For this you need the planet DB downloaded. Just run places-setup and it'll do this for you (upgrade memories to 4.11.1+ before you do this).
2. Turn off reverse geocoding. For this you just need to set `memories.gis_type` to `0` in `config.php`

**Comment by pulsejet** [comment]
Oops, closed by mistake

**Comment by pulsejet** [comment]
> Is it still possible to use Memories without downloading the dataset?

Curious about this. Why? The dataset isn't a lot of overhead; it's just slow to insert sometimes.

**Comment by martin-nohava** [comment]
Thank you so much for pointing me in the right direction,

> Turn off reverse geocoding. For this you just need to set memories.gis_type to 0 in config.php

this option was at the very end of my `config.php` configuration file and was set to value `2`. This was probably automatically added during an update and I didn't notice. My mistake, I thought this variable was not configured (`-1`).

> Curious about this. Why? The dataset isn't a lot of overhead; it's just slow to insert sometimes.

I don't necessarily need this feature and I try to keep it simple for my users. Also I assumed that world dataset would by quite large and could slow down my database, but if it isn't big overhead I may try it out. :)

Thank you again, closing.
