### ISSUE TITLE
[Likely User Issue] Transcode failed: Transcoder returned 408

### ISSUE THREAD

**Issue by vimodev** [pulsejet/memories#449]
It seems that `www-data` is missing permissions on my iGPU in an LXC container. I find this strange since I used the exact same process as on my other LXC container for Plex to grant its `plex` user permissions.

I strongly suspect that `www-data` permissions are the issue though, since if I manually start the `go-vod-amd64` executable with `root`, transcoding seems to work fine. EDIT: however even with root it does not seem to use the GPU.

```
root@nextcloud:~# ls -l /dev/dri
total 0
drw-rw---- 2 root root         80 Dec 19 08:28 by-path
crw-rw---- 1 root video  226,   0 Dec 19 08:28 card0
crw-rw---- 1 root syslog 226, 128 Dec 19 08:28 renderD128
```

```
root@nextcloud:~# members video
www-data
root@nextcloud:~# members syslog
syslog www-data
```

```
root@nextcloud:~# sudo -u www-data vainfo
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.7 (libva 2.6.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Desktop - 2.4.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointEncSlice
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD
```

But notably

```
root@nextcloud:~# sudo -u www-data intel_gpu_top
Failed to initialize PMU! (Permission denied)
```

Whereas running it as `root` works.

Any ideas?

**Comment by pulsejet** [comment]
So I'm not sure why you're getting the permissions errors, but here's a few points:

1. If you run go-vod manually, you'll need to pass it the appropriate env variables. The reason it won't use VAAPI when you run it as root is because you're missing `VAAPI=1`. Take a look at this function:https://github.com/pulsejet/memories/blob/4cdb575d6330207b0f9ac151ba52f7b1de1028ea/lib/Controller/VideoController.php#L226

2. You should delete `/tmp/go-vod` if you run it as different users. The permissions on this directory are sticky. Then try looking for `/tmp/govod/<instance-id>.log`, which would be the output of `go-vod` when it's run through PHP. This might be useful.
3. There does seem to be some permissions issue, maybe the group membership didn't apply for some reason?

**Comment by vimodev** [comment]
Yeah I'm starting to suspect it isn't the `/dev/dri` permissions, since if I run `sudo -u www-data ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -i test.mp4 -vcodec libx264 -crf 20 output.mp4` manually, it works fine and I can see in `intel_gpu_top` that the gpu is being used. I'm going to look into those other things you mentioned.

**Comment by vimodev** [comment]
Interestingly, the configured `memories.tmp_path` is never even created? Even when removing the configuration value, so that the code defaults to `/tmp/go-vod/`, that directory is never even created. However since I get the `Transcoder returned 408` log message, looking at https://github.com/pulsejet/memories/blob/79b6978bb9a3257493f35cd069082b2ed69603f9/lib/Controller/VideoController.php#L90  means that https://github.com/pulsejet/memories/blob/4cdb575d6330207b0f9ac151ba52f7b1de1028ea/lib/Controller/VideoController.php#L226 must have returned a value, before getting to the line where it creates the directory? Looking at the function the only point where it returns a value before creating the directory is https://github.com/pulsejet/memories/blob/4cdb575d6330207b0f9ac151ba52f7b1de1028ea/lib/Controller/VideoController.php#L233

So `private function getUpstreamInternal($client, $path, $profile)` must have returned `408`. Any idea as to why it might have done so? I'm afraid I don't quite understand what these functions do.

**Comment by pulsejet** [comment]
If the temp dir isn't created, it will likely throw 408. Did you start the go-vod process manually by any chance? Try killing it, then remove any relevant `/tmp` folders and then play a video.
