### ISSUE TITLE
Option to display/hide hidden folders

### ISSUE THREAD

**Issue by TtuxX** [pulsejet/memories#45]
Hi there @pulsejet :)

I hope you are doing fine.

Just one suggestion: It would be great if you could place a "Show hidden files" option like there is in the Files app (even at the same location in the Settings menu at the bottom, it would be awesome).

Currently my folder view in the Memories app is showing "useless" hidden folders:

![image](https://user-images.githubusercontent.com/6570830/190611807-84e53768-1524-4ade-8ec3-e231747269b9.png)

Thznk you very much in advance !

**Comment by pulsejet** [comment]
Good point
