### ISSUE TITLE
Can't Remove from person or Move to another person ONE photo

### ISSUE THREAD

**Issue by lehboi** [pulsejet/memories#451]
New release 4.11.2 of Memories has a good feature Mark person in preview, then move selected photos to another person or remove selected photo from person. Thanks!
However, it only moves or removes two or more selected photos. I can't move or remove one selected photo.

**Comment by pulsejet** [comment]
Is there any error? Anything in the Nextcloud logs?

**Comment by lehboi** [comment]
Sorry, I didn't report details.
The situation is "those two menu items don't appear when only one photo is selected, they only appear when more than one photo are selected".
Thanks!

**Comment by pulsejet** [comment]
The drop down menu has a scrollbar; you just need to scroll down.

**Comment by lehboi** [comment]
Ah, great!
I don't see the scrollbar but I can scroll the menu now.
Thank you very much!
