### ISSUE TITLE
MP4 videos shown at incorrect date in Timeline view

### ISSUE THREAD

**Issue by ericnotthered** [pulsejet/memories#452]
MP4 files do not show up in the timeline correctly.  

Memories correctly shows the date created time stamp (i.e., 30 Sept 2022) in the EXIF tab of the Details panel.

![image](https://user-images.githubusercontent.com/22112690/222204368-2a421763-5f77-488b-9a32-eb7e40c71e72.png)

However, the  video shows up in the timeline at a date that seems to align with the "FileDateCreated" - in this case, 14 Feb 2023.

![image](https://user-images.githubusercontent.com/22112690/222204580-32e78c7b-72e8-4f56-a691-09fc13bd0260.png)

**Comment by pulsejet** [comment]
Can you provide a sample file?

**Comment by ericnotthered** [comment]
Thanks for the response.  

Here's an example: https://user-images.githubusercontent.com/22112690/222611861-a9f36daa-ded5-4688-bd21-b9dccbb0f454.mp4

The "Media Created" date is 2022/09/30.  The "File Created" and "File Modified" dates are 9pm Feb 13, 2023.  The video shows up on Feb 14th; presumably because of the time zone (Italy).

**Comment by pulsejet** [comment]
I believe you simply run into #405 

All you need to do is either run `occ memories:index -f` (to force `-f` reindexing) or simply delete the file and restore it from the Nextcloud trash (that should re-index that file).

**Comment by pulsejet** [comment]
BTW your preview generation doesn't seem correctly configured. Take a look at https://github.com/pulsejet/memories/wiki/File-Type-Support#videos

**Comment by ericnotthered** [comment]
Thanks!  I had re-indexed after previously enabling video, but I wasn't aware that I needed to use the "-f" flag.  The videos are now appearing where expected.

Regarding my preview generation:  I'm running Nextcloud as a TrueCharts Scale App, so the config.php is managed by Kubernetics.  It offers "Movie" support, but does not give options for adding MP4 or MKV to the config.php per your link.  However, during the re-index it indicates that mpeg, webm, mp4, quicktime and x-matroska are supported.  

I appreciate your assistance.  Memories is a great app.
