### ISSUE TITLE
Error after index run

### ISSUE THREAD

**Issue by cryd-s** [pulsejet/memories#453]
Hi there,

my memories doesnt refresh after adding a new foto and if i do a `mermories:index`

i got this error

> Could not scan folder /admin/files/Photos/2023/03: An exception occurred while executing a query: SQLSTATE[42P01: Undefined table: 7 FEHLER:  Relation »memories_planet_geometry« existiert nichtLINE 1: SELECT DISTINCT(osm_id) FROM "memories_planet_geometry" WHER...                                     ^]

if i delete the folder manually it works but if there is a new photo the same error occurs

**Comment by pulsejet** [comment]
1. Did you do `occ memories:places-setup`?
2. Did you use `occWeb`? (do not)

**Comment by cryd-s** [comment]
oh yes i use occweb in which directory should i use the occ command in normal ssh?

**Comment by pulsejet** [comment]
Yes

**Comment by cryd-s** [comment]
damn problem fixed by using normal ssh - thanks a lot
