### ISSUE TITLE
Cover photo is a removed photo

### ISSUE THREAD

**Issue by lehboi** [pulsejet/memories#458]
After Recognize added photos to several people, Memories chose a cover photo that is not relating to the person. I scanned through photos of the person and removed wrong photos. However the cover photo is still the now removed photo.
Please check, Thanks!

**Comment by pulsejet** [comment]
Clear the browser cache or wait for a few days for it to expire.

**Comment by lehboi** [comment]
Yes, it works.

**Comment by pulsejet** [comment]
Fixed with https://github.com/pulsejet/memories/pull/1071
