### ISSUE TITLE
Integration with Nextcloud mobile apps no different than Photos

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#459]
The wiki states the following when comparing features in Photos not in Memories
```
Integration with Nextcloud mobile apps. Unfortunately Nextcloud does not provide a way to integrate thrid party apps into the native apps.
```

I don't think this should be listed there since Memories CAN be used in conjunction with the mobile app for auto-uploads/viewing photos, etc.

I could be wrong, but I don't think Photos 'integrates' with the nextcloud mobile apps any more than Memories does.

**Comment by pulsejet** [comment]
Good point, the native apps don't really support anything other than a list of photos. So this statement made more sense earlier than now.

**Comment by pulsejet** [comment]
Updated
