### ISSUE TITLE
Installation on yunohost nextcloud instance : memcache dependencie

### ISSUE THREAD

**Issue by wadouk** [pulsejet/memories#46]
Hi,

I try to install but lock on an error
```
root@xxx:~# sudo -u nextcloud php /var/www/nextcloud/occ memories:index
An unhandled exception has been thrown:
OC\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)

```

Any other dependencie or configuration missing ?
Thanks

Nextcloud 22.2.10
Memories 1.1.6

**Comment by pulsejet** [comment]
Well .. do you have APCu then? I don't think this is related to this app.

**Comment by wadouk** [comment]
Doesn't know of this dependency. Dosn't understand exactly the subject. Have to dig more because all the config is done by yunohost. Don't even know there was a cache.

**Comment by wadouk** [comment]
I have editer a php.ini conf specific of apc/apcu
like here https://help.nextcloud.com/t/memcache-not-available-for-local-cache/76893/5
but found on yunohost install that there is a file 
/etc/php/7.3/cli/conf.d/25-apcu_bc.ini

``` diff 25-apcu_bc.ini
; priority=25
extension=apc.so
+ apc.enabled=1
+ apc.enable_cli=1
```

but when run 
``` shell
sudo -u nextcloud php7.3 /var/www/nextcloud/occ memories:index
```
 I get,
``` log
An unhandled exception has been thrown:
ParseError: syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/nextcloud/apps/memories/lib/Command/Index.php:54
```

need to reload something of run some option to the syntax could be understand ?

**Comment by pulsejet** [comment]
Ah, PHP 7.3 isn't supported. Please upgrade to 7.4 or higher.
