### ISSUE TITLE
Green photos with marking enabled in the preview

### ISSUE THREAD

**Issue by EVOTk** [pulsejet/memories#463]
Green photos with marking enabled in the preview

When I activate the option of marking in the overview is that I go down to the bottom of the page of a photo of a person, then when I go up the page, some photos are complement green.

The clearing of the cache did not solve, I also have this problem in a private tab.
On the other hand, with Chrome, it does not seem to happen.

If I click on a "green" photo, it is correctly displayed in full screen

----

Firefox 110.0.1 ( same in private tab )
> I could not reproduce the problem in Chrome 111.0.5563.64

NC 25.0.4
Memories 4.11.2

---

![image](https://user-images.githubusercontent.com/45015615/224031437-256835f7-bf2f-4bac-b84e-594c28c24cf3.png)

After re-scroll down and up : 
![image](https://user-images.githubusercontent.com/45015615/224033191-2130c604-92ec-46e1-af2b-30c13f945f67.png)

If I continue to browse the page, then some of the views that were green become normal, and others become green.

**Comment by pulsejet** [comment]
I'd wait for 4.12, where photo rendering has been significantly reworked. Maybe this just got fixed as a side effect.

**Comment by EVOTk** [comment]
Thanks for your answer :) Can't wait for this new version :D :D

**Comment by EVOTk** [comment]
Hello ! 
After update on 4.12, the bug is still present.

![image](https://user-images.githubusercontent.com/45015615/224513246-1f329012-c7c9-4c00-98b6-a011b72e3d8c.png)

However, I find it harder to reproduce on this new version.

Ps : Thanks for the possibility to edit GPS coordinates! ❤️

**Comment by EVOTk** [comment]
Mmmm , It seems that I can reproduce like this: 

Open Firefox ( in private mode or not )
Open Memories
Clic on Peoples
Select one people
Enable "Mark people in preview"
Use the timeline to go back to the earliest date.
Then use the mouse wheel to move up the timeline
