### ISSUE TITLE
Clear selection "X" over menu on mobile.

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#467]
**Describe the bug**
The x to clear the current selection is overlayed over the hamburger menu on mobile.

**To Reproduce**
Open mobile web app and select a photo

**Screenshots**
![image](https://user-images.githubusercontent.com/10717998/224469551-601864e9-dfca-4062-9072-8bd0c59f14f3.jpeg)

**Platform (please complete the following information):**

- OS: iOS 
- Browser safari
- Version 4.12

**Important: Are all of the following are true?**

[x] I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
[x] I am NOT using `OCCWeb` to run `occ` commands
[x] The problem persists after clearing browser cache

**Comment by pulsejet** [comment]
Hmm something is off here .. why don't you have the top bar of Nextcloud? Any custom config?
