### ISSUE TITLE
Support Google Motion Photo MVIMG variants

### ISSUE THREAD

**Issue by EpochalEngineer** [pulsejet/memories#468]
The [current Live Photo implementation](https://github.com/pulsejet/memories/blob/27d027cabdcb1d187bb1fd81a6944acabd05efb9/lib/Db/LivePhoto.php#L42) supports the [MP.jpg variant](https://github.com/nextcloud/photos/issues/365#issuecomment-982014436) which has duplicate Directory Item fields in EXIF. Other variants utilize "Micro Video Offset" as described [here](https://medium.com/android-news/working-with-motion-photos-da0aa49b50c).

At a glance it seems that it would be simple to update this to support the MVIMG variant. A new if/case statement could just reference the [MP.jpg variant implementation](https://github.com/pulsejet/memories/blob/27d027cabdcb1d187bb1fd81a6944acabd05efb9/lib/Db/LivePhoto.php#L43) by checking for the existence of "Micro Video" or "Micro Video Version" (and maybe checking if it's 1) instead of looking for "MotionPhoto" and then using "Micro Video Offset" directly for the $videoOffset. EDIT: this field matches the "Size" field, so "Micro Video Offset" may actually be the video length and should be used in the same way as "DirectoryItemLength" actually.

[Here is a sample MVIMG variant image](https://drive.google.com/file/d/18zxE_Z5nN9WVA1pGINnVxpKDYX5taQmK/view?usp=sharing) which is displayed correctly in Google Photos. And [one from the same phone without motion](https://drive.google.com/file/d/13AvfIKQYyQJsQxhf5PInaO_g9jzjS0Rj/view?usp=drivesdk)

**Comment by pulsejet** [comment]
Thanks for the insights and samples.
