### ISSUE TITLE
Add search bar to faces grid

### ISSUE THREAD

**Issue by lippoliv** [pulsejet/memories#469]
**Is your feature request related to a problem? Please describe.**
Faces are sorted by most pictures, which is interesting to see. But if I search for pictures for a specific person, I'm frustrated, because there is no search bar.

**Describe the solution you'd like**
Add a search bar to the faces grid, a search bar like #177

**Describe alternatives you've considered**
Integrate to the NC global search also would be interesting. Maybe even better?

**Additional context**

**Comment by pulsejet** [comment]
Search in general needs a lot more thought.

**Comment by pulsejet** [comment]
Superceded by #674
