### ISSUE TITLE
Share multiple photos using multi-select in timeline

### ISSUE THREAD

**Issue by unseen-junkyard** [pulsejet/memories#472]
As of Memories 4.12, going to a single photo on the timeline presents an option to share, but when using multi-select there is no such option as seen here:

![photo](https://user-images.githubusercontent.com/2944562/224509083-66dd7b91-60b8-4e86-b9b4-a21865e83f5c.png)

It is currently required to add the selection of photos to be shared to an album before sharing is possible. I suggest adding the share option to the multi-select menu so that multiple photos can be shared simultaneously without the need for an album.

**Comment by HyCore** [comment]
this would be really great indeed

**Comment by diroots** [comment]
isn't it (not only) the purpose of albums? multi-select photos > add to album, and then share the album.

**Comment by frederikb96** [comment]
> isn't it (not only) the purpose of albums? multi-select photos > add to album, and then share the album.

If you e.g. use memories in the browser on your phone, the share button for single photos also enables the sharing to other apps, like messaging apps and it automatically provides the option to provide the real picture (with different compression options) and not only a link.

So you can basically use the memories app in your mobile browser as an android photo like app. For this use case, it is indeed interesting to have the possibility to share multiple photos directly via the share function :)
