### ISSUE TITLE
Manually add photos to a cluster

### ISSUE THREAD

**Issue by lehboi** [pulsejet/memories#475]
I believe that there are many photos not sorted into any people cluster, or accidentally removed from a cluster.

I think about an unsorted cluster which shows all unsorted photos; user can browse, pick photos with familiar face then move to the right cluster.

**Comment by zanish** [comment]
I would also like something like this. Alternative to the "unclustered" or unsorted cluster just showing all recognized faces in a photo and allow me to assign it to a person/cluster much like google photos allows.
Something like this: https://petapixel.com/2019/11/29/google-photos-now-lets-you-manually-tag-faces/

**Comment by luxzg** [comment]
+1 to viewing unclustered faces. I have ~14000 unclustered entries, while I'm sure many are just trash (group photos, random people in background) there's certainly hundreds of useful faces in there.

I'm unfamiliar with how NC & Memories are coded, but simplest would probably be adding a virtual "person" with `title=unclustered`, with no thumbnail, and doing something like `select file_id from oc_recognize_face_detections where cluster_id is null`.

I'd love to see this happening ☺️

**Comment by EVOTk** [comment]
I am also very interested in this!

**Comment by EVOTk** [comment]
This is great news :)

**Comment by EVOTk** [comment]
Hello :)

https://github.com/nextcloud/recognize/releases/tag/v4.2.0

![image](https://github.com/pulsejet/memories/assets/45015615/bde2ff1d-0a20-44c8-9018-ad2fd109fba3)

**Comment by luxzg** [comment]
Awww, 5.2 releases, but this was pushed to 5.3 :'( in a way, good thing I'm on vacation so wouldn't be able to use it anyway, hopefully 5.3 is out soon(ish). Cheers!

**Comment by luxzg** [comment]
@EVOTk try this for me, I'm so excited! Memories 5.2.1 released! Make sure you have Recognize 4.2.0 as well

And pulsejet - you're just amazing 😍 can't wait to try it myself! Many MANY thanks for your time and effort!

**Comment by EVOTk** [comment]
I have a few little interface bugs, but I'm glad to have this feature!
