### ISSUE TITLE
video-setup says "Testing transcoding with NVENC is OK" but it is not true

### ISSUE THREAD

**Issue by EVOTk** [pulsejet/memories#476]
**Describe the bug**
After occ memories:video-setup : 
video-setup says "Testing transcoding with NVENC is OK" but it is not true

**To Reproduce**
Run `occ memories:video-setup`
After "Checking for NVIDIA acceleration with NVENC"
The console tells me that my system is NVENC compatible and wants to activate it. But this is not true.

**Screenshots**
![image](https://user-images.githubusercontent.com/45015615/224570488-e675e938-418a-4517-aeaf-6b1e7db4548d.png)

**Platform (please complete the following information):**

- OS: OMV6
- Browser : Not applicable
- NC : 25.0.4 in Docker
- Memories : 4.12.0

- Hardware Info : CPU i3-10100T with iGPU UHD630, no GPU card

**Additional context**

**Important: Are all of the following are true?**

- [X] I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
- [X] I am NOT using `OCCWeb` to run `occ` commands
- [x] The problem persists after clearing browser cache

**Comment by pulsejet** [comment]
This was fixed in https://github.com/pulsejet/memories/commit/95c50c905d6a0f77198e28c3f300b0ce755606b9

Should work right in the next patch.

**Comment by EVOTk** [comment]
Thanks a lot for answering :) ( and for the fix )
