### ISSUE TITLE
Use multi-threading to speed up indexing

### ISSUE THREAD

**Issue by remz1337** [pulsejet/memories#481]
I'm just deploying Memories now and since the indexing has been running for a couple of minutes due to leveraging a single thread, I figured I would put a feature request :)

Maybe some possible implementations:

- Split the files in batch and process in a thread pool
- Process each nextcloud user in a separate thread (not gain if a single user, but probably easier to implement)

Thanks for the awesome app

**Comment by pulsejet** [comment]
This is unlikely to be worth the effort and maintenance. Indexing is a one-time process and takes a few hours at most, which isn't very bad. PHP doesn't support threads in any reasonable way either.

> Process each nextcloud user in a separate thread (not gain if a single user, but probably easier to implement)

This should be quite easy. Probably worth implementing.

**Comment by pulsejet** [comment]
This has been possible for a while now:
```bash
bash -c 'for i in {1..4}; do (occ memories:index &); done'
```
