### ISSUE TITLE
Filename sort order

### ISSUE THREAD

**Issue by BillBardon** [pulsejet/memories#486]
**Describe the solution you'd like**
Would like the ability to select, at the folder level, display images sorted in filename order.

**Additional context**
A timeline view works for images shot in camera. The EXIF date and the image file's timestamp both identify when the shot was taken. For scanned images, it's not so great. 

I have hundreds of photos of my ancestors, in physical photo albums that date back to 1903. However, they have been scanned a few hundred a day. Their file timestamp and EXIF date bear no relevance to the images. If or until I manually assign a date in each images's EXIF tags, the best order to display them is in the order they were scanned, which would correspond to the serialized filename itself - Scan_00001, Scan_00002, etc. I would welcome any way of doing this, whether it's a config file option, a settings preference or a folder property.

Thanks for sharing your very useful app!

**Comment by pulsejet** [comment]
Duplicate of #253 

So the thing is: Memories works with dates and dates only. The date is fundamental to the entire design, which is a good trade off since most photos do have dates. So using anything else while retaining performance and simplicity is basically impossible.

What you need is a pipeline to fix the metadata on the files. Might be worth looking into exiftool for this (the memories UI can already set dates in bulk, but you'll need to do this manually).

Unless I'm missing something though, the files should already be in correct order. Since Scan_00002 has to be scanned after Scan_00001, the date / modification time of the former should be after the latter. So the order should be correct anyway.

**Comment by BillBardon** [comment]
I expected them to display in scanned order, but they don't. By filename, the first few are like Scan_0008, Scan_0010, Scan_0001, Scan_0018, and so on. I've looked at original EXIF dates in the scanned images and dates are sequential with filenames.

Anyway, I built a script with exiftool and just forced all the dates to be sequential, in reverse order to filename so that the first scan is the first (newest) image displayed in Memories. A little manual work, but gets me the result I need.

**Comment by invario** [comment]
So I'm running into this issue a bit in a different way though. When my family sends photos/videos to me on LINE (chat program), sometimes I save it to my phone. My phone is setup to sync everything up to NC.

There's no EXIF data in any of these files unfortunately.

I'm familiar enough with EXIFTOOL to know how to do this by hand... I did this for all my files for the initial index with Memories.  But doing this piecemeal for my saved files becomes a bit tedious.

There's no way to add an option or something wherein it operates normally like it already is using EXIF dates and if (and ONLY if) there's no EXIF data to utilize the modified timestamp on the file?

**Comment by pulsejet** [comment]
@invario there's already the current behavior unless I misunderstood.

If you've exif date it uses that. Otherwise fall back to creation date. Otherwise fall back to modified time.

**Comment by invario** [comment]
> @invario there's already the current behavior unless I misunderstood.
> 
> If you've exif date it uses that. Otherwise fall back to creation date. Otherwise fall back to modified time.

Hmm that's strange. I'm going to verify some files but I think that didn't happen for a recent match of files that synced up from my phone.

**Comment by invario** [comment]
What EXIF dates tags does Memories utilize and in what order? I'm writing a quick bash script to go through all of my files to fix everything.  Thanks!
