### ISSUE TITLE
[Feature Request]  Allow adding user defined tags

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#487]
**Is your feature request related to a problem? Please describe.**
This is an extension to this issue: https://github.com/pulsejet/memories/issues/270

**Describe the solution you'd like**
We can add existing collaborative tags, but there is no current way (within memories) to create a new tag.

**Describe alternatives you've considered**
The current alternative is to create a collaborative tag outside of memories and then add it to a photo from within memories.

**Additional context**
I'm envisioning the ability to enter any new tag in the current tag field and Memories could automatically create that tag and assign it to the photo:
![image](https://user-images.githubusercontent.com/10717998/225202744-a8b7e772-e679-482f-a9d9-cd47e41e8e51.png)

**Comment by jtackaberry** [comment]
Feeling extraordinarily dumb not being able to figure out how to actually tag photos in Memories after fiddling for 5 minutes, some Googling brought me here, and all I can say is "yes please."

Absent a means of creating new tags from within Memories (obviously preferred), some sort of link to where within Nextcloud one can seed a new tag, or a blurb explaining how to create them (perhaps hidden behind a help/info button in the Collaborative Tags heading) would improve discoverability (presumably) without much effort.

**Comment by DasNaCl** [comment]
@jtackaberry As a follow up for you and anyone coming here from search engines:

If you have existing tags, you can do the following to add tags in Memories:
1. Open timeline view, click on image you want to tag.
2. To the left of the "X" button in the top-right corner are 3 dots, click that.
3. Click "Edit metadata"
4. A modal popups with a text-box under heading "Collaborative Tags" where you can enter tags.
  - to enter a tag: type a prefix, a suggestion will popup that matches the tag. Hit enter or click on it
  - remove tags with backspace
5. Make sure to scroll to the bottom of the modal window, there is a red "Save" button. Click on it when you are done.

If you don't have existing tags, do as follows:
1. Open ordinary Files view.
2. Select a file, hit the 3 dots to right if you are in list-view.
3. Click on "Details"
4. In the window to the right, you may see tabs "Activity", "Sharing", "Versions". At the top right is an "X", to the left of that, another 3 dots. Click on these.
5. Click on "Tags"
6. A textbox appears where you can enter/assign tags. To add new tags, simply type the name of the tag and hit "return".
  - you can add a bunch of tags by simply writing something (may contain spaces) and hitting return, consecutively
  - to get rid of assigned tags (e.g. if your selected file should not have these tags but you wanted to create the tags to be assignable in Memories) just hit backspace
7. Go back to memories and now you can assign tags (may need to close & reopen page)


This has been my current workaround. It sounds clumsier than it actually is.

**Comment by pulsejet** [comment]
![image](https://github.com/pulsejet/memories/assets/10709794/b877116d-e7f6-4d98-a01b-2da1a68707cf)
