### ISSUE TITLE
Nextcloud 26 compatibility

### ISSUE THREAD

**Issue by jakobroehrl** [pulsejet/memories#489]

**Comment by tstdin** [comment]
![image](https://user-images.githubusercontent.com/25065143/226897214-c369efb1-32c2-4c91-8fff-341118cb4465.png)

**Comment by elpraga** [comment]
Thank you @pulsejet for your great work! Memories is a trully great app to organise a large collection of photos?

Are you planning to release a version that is compatible (and recognised as such by the updater) with Nextcloud 26? Or at least can you confim that it will continue working if enabled as untested app? 

Memories is one of the apps that make me hold the update ATM, I wouldn't like to be without it!

**Comment by pulsejet** [comment]
My dev environment is running Nextcloud 27, so you should be okay on 26

**Comment by rhatguy** [comment]
I have memories installed on Nextcloud 26 and it works great.

**Comment by EVOTk** [comment]
No issue on NC26
