### ISSUE TITLE
Group folders

### ISSUE THREAD

**Issue by escoand** [pulsejet/memories#49]
I've all my photos in a group folder shared for every user. This share is "mounted" as `Bilder` in my user account. I can also see the got scanned as `/<myname>/files/Bilder/...`. In the filesystem they reside in `.../nextcloud/data/__groupfolders/1/...`. But what is the correct parameter to show all these files in the UI?

**Comment by pulsejet** [comment]
Do you see it in the Folders view?
You can't use a shared folder for your timeline, since it displays only photos owned by you. If you need that you'll have to use an external storage.

**Comment by escoand** [comment]
Yes, in the folder view it's viewed. The group folders is a nice feature to share files between multiple users but no user "owns" the files, it belongs to everybody.

**Comment by escoand** [comment]
It's working now, thanks.

**Comment by whitestrake** [comment]
I've just installed this with the new v5 release and run the index command. It seems to index every individual user but does not index the `__groupfolders`.

The `occ:memories index` command has a `--folder` flag but that's relative to a user. I'm not sure how to get existing photos in a group folder to appear in the UI; it's working for all user's photos otherwise.

**Comment by pulsejet** [comment]
I forgot how these work, so this needs to be re-checked.

**Comment by pulsejet** [comment]
@whitestrake group folders seem to work fine for me. There's no special handling required since they are mounted as a folder inside the user's directory and are processed normally. E.g. in the first post on this thread, you'd specify `--folder Bilder` if you just want to index the group folder.

**Comment by whitestrake** [comment]
@pulsejet, that doesn't seem to be the case for my installation.

To clarify, I mean these group folders: https://apps.nextcloud.com/apps/groupfolders

This app creates folders which are not inside any individual user's directories.

**Comment by pulsejet** [comment]
Indexing is a background process, it'll take time when you add in new things.
