### ISSUE TITLE
Remove People(Recognize) from the sidebar option

### ISSUE THREAD

**Issue by MikeDuncan1** [pulsejet/memories#494]
**Is your feature request related to a problem? Please describe.**
I am using both recognize and face recognition.  I look at recognize for generic object tagging only and face recognition as the one that actually does face recognition properly.  I know that your app detects if one or both are installed and adds them appropriately in the sidebar.

**Describe the solution you'd like**
I would like to be able to turn the 2 people sidebar additions on and off in the backend with a switch so I can get rid of People(Recognize).  

**Describe alternatives you've considered**
Where is this done in your code?  If I need to manually alter the script I could do that alternately but then I would have to redo it with each update.

**Comment by pulsejet** [comment]
You'll be able to use the settings option to turn it off in the next release.

**Comment by MikeDuncan1** [comment]
Thank you so much :)
