### ISSUE TITLE
video-setup can't detect Nvidia HW scalers scale_npp and scale_cuda

### ISSUE THREAD

**Issue by shperrung** [pulsejet/memories#496]
Updates memories to 4.12.2 and 4.12.3 broke my Nvidia HW transcoding.
Since the last my [issue request](https://github.com/pulsejet/memories/issues/428#issuecomment-1449096029)  you implemented GPU check and differentiation of ffmpeg convert command.

**Steps to reproduce** 
Try to pass `occ memories:video-setup` again after Memories update.

**Screenshots**
```
shperrung@omv6:~$ docker exec -it -u www-data nextcloud-app-1 ./occ memories:video-setup
ffmpeg is installed
ffprobe is installed
Checking for go-vod binary
Trying go-vod from /var/www/html/custom_apps/memories/exiftool-bin/go-vod-amd64
go-vod is installed!

You can use transcoding and HLS streaming
This is recommended for better performance, but has implications if
you are using external storage or run Nextcloud on a slow system.

Read the following documentation carefully before continuing:
https://github.com/pulsejet/memories/wiki/Configuration

Do you want to enable transcoding and HLS? [Y/n]
y

Starting ffmpeg feature detection
This may take a while. Please be patient

Downloading test video file ... OK

Attempting to start go-vod ... OK
go-vod logs will be stored at: /tmp/go-vod/oct00g34j6d9.log

Testing transcoding with CPU ... OK

Checking for VAAPI acceleration (/dev/dri/renderD128) ... NOT FOUND

Checking for NVIDIA acceleration with NVENC
Testing transcoding with NVENC (scale_npp) ... FAIL
Testing transcoding with NVENC (scale_cuda) ... FAIL
NVENC does not seem to be available

Feature detection completed

Transcoding and HLS are now enabled! Monitor the log file for any errors
You should restart the server for changes to take effect
```

**ffmpeg is on place**

```
shperrung@omv6:~$ docker exec -it -u www-data nextcloud-app-1 /usr/local/bin/ffmpeg                                                                             ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)                                configuration: --disable-debug --disable-doc --disable-ffplay --enable-cuda --enable-cuvid --enable-fontconfig --enable-gpl --enable-libaom --enable-libaribb24 --enable-libass --enable-libbluray --enable-libfdk_aac --enable-libfreetype --enable-libkvazaar --enable-libmp3lame --enable-libnpp --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libsrt --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-libzmq --enable-nonfree --enable-nvenc --enable-cuda-sdk --enable-openssl --enable-postproc --enable-shared --enable-small --enable-version3 --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec -I/usr/local/cuda/include/' --extra-ldflags='-L/opt/ffmpeg/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib32/' --extra-libs=-ldl --extra-libs=-lpthread --prefix=/opt/ffmpeg
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

```
[oct00g34j6d9.log](https://github.com/pulsejet/memories/files/11008090/oct00g34j6d9.log)

**Platform (please complete the following information):**
Host system: Debian 11
Memories ver. 4.12.2 and 4.12.3
Nextcloud is running in docker: nextcloud-apache 25.0.3 with manually built **ffmpeg** supporting nvidia stuff including "scale_cuda" and "scale_npp" (I didn't update it). HW transcode worked fine earlier version than 4.12.2

**Additional context**

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
- I am NOT using `OCCWeb` to run `occ` commands
- The problem persists after clearing browser cache

**Comment by shperrung** [comment]
How can I downgrade Memories to 4.11.2? I need it working.

I suggest that check "scale_cuda" vs. "scale_npp" doesn't work. I know that you don't have Nvidia GPU for testing. Let you return back "video-setup" procedure as it was in 4.11.2 but just use only the one scaler "scale_cuda" instead "scale_npp".

**Comment by remz1337** [comment]
Same issue here

**Comment by pulsejet** [comment]
This has nothing to do with NVENC; seems like you're running two instances of go-vod somehow and PHP can't kill it.

I'll suggest just manually configuring go-vod, the `config.php` options are at https://github.com/pulsejet/memories/wiki/System-config-options#transcoding

Even better, just use an external transcode,
https://github.com/pulsejet/memories/wiki/HW-Transcoding#external-transcoder-recommended

**Comment by remz1337** [comment]
I can confirm that manually adding back:
```
  'memories.vod.nvenc' => false,  // Transcode with NVIDIA NVENC
  'memories.vod.nvenc.temporal_aq' => false,
  'memories.vod.nvenc.scale' => 'npp', // npp or cuda
```

in the config fixes the issue.

1. Reboot server
2. Manually edit config
3. Reboot again
4. run `occ memories:video-setup`

The setup was then able to detect NVENC and configure correctly.

Still a bit weird. Should be documented somewhere in the wiki if this is the expected user experience

**Comment by pulsejet** [comment]
The only thing video-setup does is configure these options for you. So you don't really need to run it if you do that manually.

**Comment by shperrung** [comment]
I confirm, that it is working with that add to config.php:

```'memories.vod.disable' => false,                                                'memories.video_default_quality' => '0',                                        'memories.vod.nvenc' => true,                  'memories.vod.nvenc.temporal_aq' => true,
'memories.vod.nvenc.scale' => 'cuda',
```
In result:
`2023/03/19 00:02:47 lya20m7ngqj0-480p: /usr/local/bin/ffmpeg -loglevel warning -ss 21.000000 -hwaccel cuda -autorotate 0 -i /photo/photostore/2022/12/20221231_190000_65AC8860.mp4 -copyts -vf format=nv12|cuda,hwupload,scale_cuda=force_original_aspect_ratio=decrease:passthrough=0:w=640:h=480 -maxrate 2400000 -bufsize 4800000 -c:v h264_nvenc -profile:v main -preset p6 -tune ll -rc vbr -rc-lookahead 30 -cq 24 -temporal-aq 1 -c:a aac -ac 1 -b:a 128k -avoid_negative_ts disabled -f hls -hls_time 3 -force_key_frames expr:gte(t,n_forced*3) -hls_segment_type mpegts -start_number 7 -hls_segment_filename /var/www/html/vod/oct00g34j6d9/lya20m7ngqj0-1375708011/480p-%06d.ts`
