### ISSUE TITLE
Disable video not configured: run occ memories:video-setup prompt

### ISSUE THREAD

**Issue by jeremija** [pulsejet/memories#497]
Is there any way to disable the prompt to run video setup when viewing video? I'm hosting nextcloud on an old PC that doesn't have transcoding abilities and I've already answered no when I ran video setup, yet I started seeing this after a recent upgrade. Thanks

![Screenshot_20230318_195247_Chrome](https://user-images.githubusercontent.com/1489493/226130483-be544573-5277-4c7d-90c7-3360ac7399f8.jpg)

**Comment by pulsejet** [comment]
1. Run video-setup again
2. Restart your server
3. Refresh your browser
