### ISSUE TITLE
Bug - Android Firefox Long Press Picture opens Firefox Menu instead of picking mode

### ISSUE THREAD

**Issue by Cebrain** [pulsejet/memories#498]
**Describe the bug**
When i use the Android Firefox Long Press Picture opens Firefox Menu (Open in tab, share link, etc) instead of memories menu (no picking mode)
As i know this worked already before.

**To Reproduce**
With 2 different smartphones and installation

**Platform (please complete the following information):**

- OS: Android 13
- Browser Firefox 111.0
- Version 25.0.4 and Memories 4.12.3

**Additional context**
I had this problem some months ago and suddenly it appears again

**Comment by pulsejet** [comment]
Behavior with Chrome?

**Comment by Cebrain** [comment]
I remembered correctly, i mentioned this problem in another issue ^^
https://github.com/pulsejet/memories/issues/180#issuecomment-1311779073

As i remember it was working some days later.

Will test chrome

**Comment by Cebrain** [comment]
> Behavior with Chrome?

Works fine in chromium engine (tested with brave)

**Comment by Cebrain** [comment]
thx
