### ISSUE TITLE
l10n: Singular and plural

### ISSUE THREAD

**Issue by Valdnet** [pulsejet/memories#50]
Add singular and plural for the following text string:
https://github.com/pulsejet/memories/blob/704eda1d2d066efc55a0ad108ec0c1b46c93edfa/src/components/Timeline.vue#L86

**Comment by pulsejet** [comment]
Do other languages not have an equivalent?

**Comment by Valdnet** [comment]
In some languages "selected" is declined singular and plural, e.g .:
```
1 wybrany
2 wybrane
5 wybranych
```

See the [Translations](https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html) documentation.

**Comment by pulsejet** [comment]
TIL
