### ISSUE TITLE
Strange behavior with folder sharing, and face detection

### ISSUE THREAD

**Issue by EVOTk** [pulsejet/memories#500]
**Describe the bug**
I have ( User A ) currently sharing with another user ( User B ) some photo folders.

Since we sometimes have the same people on the photo, so the name sound duplicate, I made an issue to be able to better organize this: https://github.com/pulsejet/memories/issues/462

But now I have another problem. In the detections of user B, I find the photos of user A (which are shared).

Why is there this behavior now? Is it Memories or Recognize that has changed its way of proceed?

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/45015615/226143182-45c670b6-78c9-48ea-bcaa-d3ebd2a04538.png)

**Platform (please complete the following information):**

Nextcloud : 25.0.5
Nginx / Php 8.1
Memories : 4.12.3

**Additional context**

**Important: Are all of the following are true?**

- [X] I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
- [X] I am NOT using `OCCWeb` to run `occ` commands
- [X] The problem persists after clearing browser cache

**Comment by EVOTk** [comment]
Mmmmm, I have my answer I think  : https://github.com/nextcloud/recognize/releases/tag/v3.6.0

![image](https://user-images.githubusercontent.com/45015615/226143578-bb4307b4-c7be-4da6-a427-0ecac5cbdb52.png)

**Comment by EVOTk** [comment]
I think about it ..... Since Recognize now also identifies shared folders, ... maybe it would be better to hide the "faces" from other users?

The fact that you want to merge the faces is not really interesting anymore, I think it would be more interesting to hide the other users detection by default, and to make them visible when needed.

**Comment by pulsejet** [comment]
Recognize behavior changed, so we'll need to adapt. I'm kinda apprehensive if this'll break anything in group folders or external mounts, but that's not our problem anymore.

**Comment by pulsejet** [comment]
This might create other problems: https://github.com/nextcloud/recognize/discussions/751

**Comment by EVOTk** [comment]
Thanks a lot for this answer :)
