### ISSUE TITLE
See local pictures and videos that are not uploaded yet like Google Photos

### ISSUE THREAD

**Issue by MikeDuncan1** [pulsejet/memories#508]
**Is your feature request related to a problem? Please describe.**
I cannot see local files that are not uploaded yet

**Describe the solution you'd like**
For local pictures and videos to be displayed somehow in the app so I don't have to look at another app before things are uploaded like google photos

**Describe alternatives you've considered**
Using a local gallery app, which is fine, but not as convenient.

**Additional context**
I just want memories to be like google photos when it comes to this.  I understand that maybe it is impossible but it would be nice.

**Comment by Cebrain** [comment]
I think in the end a App for the smartphone would be necessary.
At the moment the local pictures (local photo app) and online pictures (memories) have nothing in common.

I created an feature request for an dedicated app some time ago, but it means much work and time. 
https://github.com/pulsejet/memories/issues/508

**Comment by pulsejet** [comment]
Closing in favor of #180
