### ISSUE TITLE
Wiki: Imaginary as alternative preview generator

### ISSUE THREAD

**Issue by tstdin** [pulsejet/memories#510]
**Is your feature request related to a problem? Please describe.**
I had a tough time with the suggested [Preview Generator](https://github.com/rullzer/previewgenerator) and ended up with Imaginary. Since then, the overall experience improved significantly.

**Describe the solution you'd like**
Mention also the Imaginary for preview generation in the [wiki](https://github.com/pulsejet/memories/wiki/Configuration), so people can find out about other options.

**Describe alternatives you've considered**
n/a

**Additional context**
[DockerHub](https://hub.docker.com/r/nextcloud/aio-imaginary)
[Speed up Nextcloud preview generation with imaginary](https://okxo.de/speed-up-nextcloud-preview-generation-with-imaginary/)

**Comment by ikamaletdinov** [comment]
@tstdin Unfortunately still not working properly with HEIC images (toooo sloooow)
