### ISSUE TITLE
Make "Places" hierarchical

### ISSUE THREAD

**Issue by llucax** [pulsejet/memories#511]
**Is your feature request related to a problem? Please describe.**

I love the "Places" feature (and the app in general!), but it is hard to find a particular place, or sometimes even to know what a place to the level of a neighborhood in a city really was located.

**Describe the solution you'd like**

 I would be nice if there is a mode to see "Places" in a hierarchical way like folder, where the top-level folders is the country (or maybe continent?), then the region, then the city and finally the neighborhood.

**Describe alternatives you've considered**

None really, just navigate the long list of places the best I can.

**Additional context**

I have a large collection, with tens of thousands of photos, distributed in more than 200 places (as shown by "Places", they are not really more than 200 but with the different levels of "zoom" from the country to neighborhood it adds up). Maybe for smaller collections this is not a problem.

**Comment by luxzg** [comment]
This is awesome suggestion! I'm a new user and had been looking at Places and thinking about something like "merge" option, similar to People.

But this feature/enhancement request is so much better and way more logical! Two thumbs up from me, hope it gets implemented, would put Places to a whole new level.

**Comment by llucax** [comment]
Amazing! Thanks!
