### ISSUE TITLE
Failed to create memories record: An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 1264 Out

### ISSUE THREAD

**Issue by tincanfury** [pulsejet/memories#518]
**Describe the bug**
When runnning,
`# occ memories:index`
It scans most of my photos fine, but several of them pop up with this error:
```
Scanning /<user>/files/Photos/2015/2015-01-24/2015012412563701.jpg
Failed to create memories record: An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 1264 Out
```

**To Reproduce**
`# occ memories:index`

**Screenshots**

**Platform (please complete the following information):**

- OS: [OMV (Debian)](https://www.openmediavault.org/)
- Version 	4.12.3 on Nextcloud Hub 3 (25.0.5)

**Additional context**

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration). YES
- I am NOT using `OCCWeb` to run `occ` commands CORRECT
- The problem persists after clearing browser cache N/A

**Comment by tincanfury** [comment]
is the -f,
`occ memories:index -f`
still necessary? The log shows it, but the main page does not.

**Comment by pulsejet** [comment]
Can you provide a sample file?

`-f` is not necessary unless you want to reindex everything.

**Comment by invario** [comment]
Just threw the same error while attempting to reindex everything with -f.

TrueNAS Core 13, running NC 25.0.5 in a jail
PHP 8.1.12
MySQL Ver 8.0.30

`Could not scan folder /LOGIN/files/Photos Archive/2011/2011-05-20 - Place1: An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 1264 Out of r

Could not scan folder /LOGIN/files/Photos Archive/2011/Photos from phone - 02-15-2011 to 11-08-2011: An exception occurred while executing a query: SQLSTATE[22003]: Numeric value ou

Could not scan folder /LOGIN/files/Photos Archive/2012/2012-01-27 to 2012-01-29 - Stowe Mountain Ski Trip: An exception occurred while executing a query: SQLSTATE[22003]: Numeric va

Could not scan folder /LOGIN/files/Photos Archive/2012/Photos from phone - 11-09-2011 to 06-30-2012: An exception occurred while executing a query: SQLSTATE[22003]: Numeric value ou
`

The indexing continues despite these errors.

It should be noted that the folders are external SMB mounts. Also, is it possible that the full path is too long?

**Comment by pulsejet** [comment]
This should be fixed now, reopen otherwise

**Comment by badsmoke** [comment]
the errors still occur with me, have the latest version

```
Fehler	memories	Failed to index file /username/files/Photos/2009/dezember/berlin/PICT1001.JPG: An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'mtime' at row 1		vor 18 Minuten
Fehler	memories	Failed to index file /username/files/Photos/2009/dezember/berlin/PICT0998.JPG: An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'mtime' at row 1		vor 18 Minuten
Fehler	memories	Failed to index file /username/files/Photos/2009/dezember/berlin/PICT0997.JPG: An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'mtime' at row 1		vor 18 Minuten
Fehler	memories	Failed to index file /username/files/Photos/2009/dezember/berlin/PICT0996.JPG: An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'mtime' at row 1		vor 18 Minuten
Fehler	memories	Failed to index file /username/files/Photos/2009/dezember/berlin/PICT0995.JPG: An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'mtime' at row 1		vor 18 Minuten
Fehler	memories	Failed to index file /username/files/Photos/2009/dezember/berlin/PICT0991.JPG: An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'mtime' at row 1
```
