### ISSUE TITLE
Foo and Foobar folder are both displayed in the "Foo" Timeline

### ISSUE THREAD

**Issue by Aquariu** [pulsejet/memories#52]
I tested this only in Nextcloud normal storage and not External Storage to not create additionnal headaches.

Steps:
- Create a folder named Foo
- Create a FooBar folder
- Put some pictures in both
- Index
- set "Foo" in the Timeline setting

Result : 
- Pictures of Foo and FooBar are displayed in the Timeline

Additionnal information:
- Set Timeline folder as"Fo"
--> Pictures of Foo and Foobar are still displayed.

**Comment by pulsejet** [comment]
Just add a slash to the end of the configured path (`/Foo/` instead of `/Foo`) and it should work

Leave this open though.

**Comment by Aquariu** [comment]
In confirm that a trailing / solves this.
