### ISSUE TITLE
Can not add shared photos to an album

### ISSUE THREAD

**Issue by MarkWieczorek** [pulsejet/memories#524]
**Describe the bug**
A folder of images was shared to my account. After selecting several photos, and choosing to "add to album", I received the error "Failed to add filenamexxx to album". 

**To Reproduce**
* Share a folder of images to a user.
* Ask that user to select some of the shared photos and to add them to an album.

**Platform (please complete the following information):**

- OS: Ubuntu Linux 22.04.2
- NextCloud 25.0.5
- Memories
- Version 4.12.5

**Additional context**
Adding photos to an album works normally if that they are not shared photos.

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
- I am NOT using `OCCWeb` to run `occ` commands
- The problem persists after clearing browser cache

Yes.

**Comment by pulsejet** [comment]
When the folder is shared, does the user have resharing permissions?

**Comment by MarkWieczorek** [comment]
Yes. The folders authorize the following: editing, creating, deleting, resharing, downloading.

**Comment by pulsejet** [comment]
This is a bigger problem in upstream: https://github.com/nextcloud/photos/pull/1718
Nothing we can do here
