### ISSUE TITLE
No cover-image/thumbnail for people in "People"

### ISSUE THREAD

**Issue by MarkWieczorek** [pulsejet/memories#525]
**Describe the bug**
After installing recognize, memories correctly recognizes faces and groups photos together. However, when you click on the "People" sidebar, each person has the same default picture icon as the cover image.

<img width="186" alt="Untitled" src="https://user-images.githubusercontent.com/8697285/227803704-b1fc4317-8562-4b90-b6da-eeaab31a5291.png">

I note that if I use the Nextcloud "Photos" app instead, that each person in the "People" page correctly have cover images.

**To Reproduce**
* Install recognize, and process all your photos.
* Click on "People" and you will see that each item uses the default "picture" icon as the cover image

**Platform (please complete the following information):**

* OS: Ubuntu Linux 22.04.2
*  NextCloud 25.0.5
* Memories
* Version 4.12.5

**Additional context**

I recently updated to the most recent version of Memories 4.12.5. Before this (presumably 4.12.4) no image was shown at all for the cover image.

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
- I am NOT using `OCCWeb` to run `occ` commands
- The problem persists after clearing browser cache

Yes.

**Comment by pulsejet** [comment]
Are there any errors in
1. JS console
2. Network tab of the browser inspector
3. Nextcloud logs

**Comment by pulsejet** [comment]
Also do you have the PHP Imagemagick extension?

**Comment by MarkWieczorek** [comment]
Installing "php-imagick" indeed solves this problem. Thanks! 

php-imagick was not enable on my preconfigured system, most likely because there is some security issue related to this software: https://github.com/nextcloud/server/issues/13099
