### ISSUE TITLE
Person name in "People" is not shown for shared images

### ISSUE THREAD

**Issue by MarkWieczorek** [pulsejet/memories#526]
**Describe the bug**
I have added people names to the groups of photos that were generated by recognize and that are shown when clicking "People" in the sidebar:

<img width="190" alt="Untitled-1" src="https://user-images.githubusercontent.com/8697285/227804360-82cc48fe-143d-4060-8edf-b18e34164f92.png">

However, if I share my folder of images with another user, when they click on "People", the person names are not displayed:

<img width="187" alt="Untitled 2" src="https://user-images.githubusercontent.com/8697285/227804410-95dd1c24-1c5f-4ff6-85e0-66f2c8ebdff9.png">

**To Reproduce**
* Use recognize to process your photos.
* Add a name to each unique grouping of photos.
* Share the folder with your images to another user.
* Ask that user to click on "People", and they will see that there are no people names.

**Platform (please complete the following information):**

- OS: Ubuntu Linux 22.04.2
- NextCloud 25.0.5
- Memories Version 4.12.5

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
- I am NOT using `OCCWeb` to run `occ` commands
- The problem persists after clearing browser cache

Yes

**Comment by pulsejet** [comment]
This is correct behavior. Each user has their own clusters regardless of whether the file is shared or not, so they manage their own clusters.

This is actually a result of a recent change in recognize. It used to have detections only for the owner earlier, but that meant only the owner could manage the library. Now each user's face library is independent.

**Comment by pulsejet** [comment]
More context

#500
https://github.com/nextcloud/recognize/discussions/751

**Comment by MarkWieczorek** [comment]
Thanks for the info. I now understand what is happening now, but I still think that there is a problem.
* In the account with the shared files, I do in fact find the 2 separate groups of photos made by the individuals. For example, there is a group of photos of me from my account, and a second group of photos of me from the other account. These can not be merged.
* However, I added a name to each group of photos in "People". That name is shown at the bottom of the cover image in my account, but not in the bottom of the cover image in the shared account. (see the above screenshots).

In my opinion, the person name of the group of photos should be shown in the other shared account.

**Comment by pulsejet** [comment]
As I said, this is recognize behavior, nothing to do with memories really. Probably worth further discussion at https://github.com/nextcloud/recognize/discussions/751
