### ISSUE TITLE
Upgraded to 2.0 and now no photos show

### ISSUE THREAD

**Issue by TheWanderer1983** [pulsejet/memories#53]
Was working great on last release. Today I upgraded memories to latest version and upgraded previewgenerator. Photos show fine in the photos app but in memories timeline i see no photos and this error at to right "No photos to show here".

 Preview Generator 5.1.0
 Memories 2.0.0
 Nextcloud 24.0.4

**Comment by pulsejet** [comment]
Did you re-run `occ memories:index`? See the changelog.

**Comment by TheWanderer1983** [comment]
No I didn't. I'm running it now.

**Comment by pulsejet** [comment]
Hopefully that should fix it. v2 completely changes the timeline logic to support external storage. Please report back.

**Comment by TheWanderer1983** [comment]
That did the trick. Thank you.
