### ISSUE TITLE
Archiving: General Failure

### ISSUE THREAD

**Issue by Dulanic** [pulsejet/memories#531]
**Describe the bug**
When archiving photos, sometimes I get an a error on screen.

**To Reproduce**
Archive photos, not sure the real trigger through.

**Screenshots**
![image](https://user-images.githubusercontent.com/2948206/228282950-6dccb36d-d7be-450f-b2be-ac5f535ad270.png)

**Platform (please complete the following information):**

- OS: Nextcloud is run in docker on a ubuntu server,
- Browser Edge 111.0.1661.54
- Version [e.g. 4.1.0]

**Additional context**
Somewhat random, if I rerun the archive it sometimes works, sometimes doesn't. But if I keep retrying, it will work. Only possible insight is maybe memories is accessing the file at the time? One thing is these photos are on "external storage" in nextcloud. I keep all my photos in a local directory for use using multiple access methods, so I mount it is a external storage location.

![image](https://user-images.githubusercontent.com/2948206/228284049-fb49110d-b13c-4874-bbf6-4b685ed36f94.png)

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration). 
- Yes
- I am NOT using `OCCWeb` to run `occ` commands
- Yes
- The problem persists after clearing browser cache
- Yes

**Comment by schnillerman** [comment]
Please give issue more meaningful heading (e.g., _Archiving: General Failure_)

**Comment by pulsejet** [comment]
Archiving logic is revamped with 6.1 and should fix these
