### ISSUE TITLE
Google Motion Photos not playing correctly

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#532]
**Describe the bug**
Google motion photos are not playing. When clicking the "Play Live Photo" button in the viewer, it appears that a few frames are played (or maybe it is just the "[make animation less annoying](https://github.com/pulsejet/memories/commit/1ef3f576b027aaddd8722da24b469ae9ecaff621)" fix that you implemented that is making it look like it's trying to play).

**To Reproduce**
- Upload google motion photo - MP.jpg variant (Taken on Pixel 7 using Google Camera app with motion photo option turned on)
- Try to play motion photo

Sample Google Motion Photo:
![example](https://user-images.githubusercontent.com/10717998/228286412-5a66ab43-91a7-4474-91e1-da73c50f6abf.jpg)

**Platform (please complete the following information):**

- OS: Windows/Linux

- Browser Firefox/Chrome
- Version v4.13.0a1

**Additional context**
If i upload the photo to Google drive, the motion photo plays normally, so I know the motion portion photo is not corrupted.
Previous issues that may be relevant:
- https://github.com/pulsejet/memories/issues/373
- https://github.com/pulsejet/memories/issues/388
- https://github.com/pulsejet/memories/issues/468

**Important: Are all of the following are true?**

[x] I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
[x] I am NOT using `OCCWeb` to run `occ` commands
[x] The problem persists after clearing browser cache

**Comment by thermatk** [comment]
can confirm, only a strange flash of frames in Firefox, it might have something to do with wrong transcoding settings

**Comment by pulsejet** [comment]
Turns out it's a bug in go-vod. It seems to select the wrong stream to encode for some reason. Should be fixed with go-vod 0.0.35
