### ISSUE TITLE
Longitude coordinate not saved properly

### ISSUE THREAD

**Issue by mentalblock** [pulsejet/memories#533]
**Describe the bug**
When using the Gelocation feature, it appears that if the longitude is a negative number, it saves as a positive number. This results in the location being on the other side of the world.

**To Reproduce**
Perform a location search for Geolocation feature. In my case, I typed `joshua tree`. This photo was taken in Joshua Tree, California. I selected the first result from the search.

The form correctly filled out coordinates as "34.126526, -116.320935". I hit `save` and all is well. I then reopen the image and look at its map location and it is written in Chinese and the pin is in a city in China. The metadata shows that the longitude is "116.320935".

I tried removing the metadata, saving, and repeating the process to no avail.

**Screenshots**
![image](https://user-images.githubusercontent.com/1371873/228394220-7a13c963-de93-47f2-a263-66d10c5f8a0e.png)

The screenshot was obtained by selecting the result which filled in the coordinates as "34.126526, -116.320935". ( Then I did another search for `joshua tree` to make the scenario more clear.)

After saving and reviewing the image, I see this as the pin on the map.

![image](https://user-images.githubusercontent.com/1371873/228395051-ac105cb8-7342-44da-b375-dfcd2936f231.png)

I then take a look at the gelocation data:
![image](https://user-images.githubusercontent.com/1371873/228395123-a5772339-fe1d-4e66-9687-e3aa28d26b54.png)

**Platform (please complete the following information):**

- OS:
```
system: `"x86_64-linux"`
host os: `Linux 5.15.90, NixOS, 23.05 (Stoat), 23.05.20230130.2caf4ef`
```
- Browser: firefox
- Version: 4.12.5

**Additional context**
Using Postgres

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
- I am NOT using `OCCWeb` to run `occ` commands
- The problem persists after clearing browser cache

All true

**Comment by pulsejet** [comment]
This was fixed in https://github.com/pulsejet/memories/commit/9e7a6a0bd128e0fb00f5774df2732562964323a4
Look for the next release ;)

**Comment by mentalblock** [comment]
Thank you for the quick response and all the hard work.
