### ISSUE TITLE
Feature request: Make it easier to start selecting multiple photos/videos on mobile browser

### ISSUE THREAD

**Issue by RikkiBC** [pulsejet/memories#536]
**Is your feature request related to a problem? Please describe.**

When multi-selecting photos on a Mobile Browser, long-pressing a photo is extremely hit-or-miss. No matter what, the browser context menu will pop up, but only about half the time will the photo be selected. So I'll need to try again.

Once a photo is selected, the checkboxes appear for easy tapping on other photos from there. This issue/feature request is for the first photo being selected.

**Describe the solution you'd like**

It would be amazing if, when viewing on mobile, the checkboxes were already visible for checking a picture before one of the pictures has been selected.

There may be an alternative option, e.g a menu option for "select photos" or similar? Though having the little checkboxes already available (even if only clickable/tappable in the top corner of the thumbnail) to _start_ selecting pictures would be best, or at least in my opinion.

**Comment by pulsejet** [comment]
Firefox?

**Comment by RikkiBC** [comment]
Ah, yes indeed Firefox. Not sure if it's better on other browsers but I'd prefer to keep using Firefox if possible.

**Comment by pulsejet** [comment]
Likely duplicate of #498

**Comment by RikkiBC** [comment]
Ah yes, looks like it! That's closed with a commit which I guess will be in a future release?

**Comment by pulsejet** [comment]
Yup

**Comment by RikkiBC** [comment]
All good I'll wait for the release, thanks for already being on this one!
