### ISSUE TITLE
Display only one photo when both RAW (NEF) and JPG present in a directory

### ISSUE THREAD

**Issue by privettoli** [pulsejet/memories#537]
**Implementation Todos**

- [x] O(n) filtering for deduplication / hidden
- [x] Stack over ANY match (then move to end)
- [x] Allow disabling stacking
- [x] Mark RAW on timeline frame
- [x] Mark Stack on timeline frame
- [x] Download stack files
- [x] Auto archive stack with main
- [x] Auto delete stack with main (warn)
- [x] Auto move stack with main
- [x] Warn when editing image with stack (also metadata)

**Is your feature request related to a problem? Please describe.**
When I open my memories timeline, there's a bunch of duplicates because I store both NEF and JPEG in the same directories.

**Describe the solution you'd like**
Allow a feature to be enabled in settings that would hide NEF photos with the same name (I know it's not ideal but this would be sufficient) when it's in the same directory. Allow to choose which format should be used for preview. When one photo is deleted but has both NEF and JPEG, allow to choose whether to delete both or just one.

**Describe alternatives you've considered**
Moving NEF files out into another directory that is not indexed by memories. I would not prefer this approach because I'd need to migrate existing files and store new photos I upload in separate directories too.

**Additional context**
<img width="1436" alt="Screenshot 2023-04-04 at 9 49 05 AM" src="https://user-images.githubusercontent.com/3314620/229861606-5a415739-f932-4d52-a832-5b28e4ec5b86.png">

**Comment by privettoli** [comment]
Samples:
NEF https://papenko.one/s/SimmxZTGPjf4iix
JPG https://papenko.one/s/ALf2aX2mi72LyeF

**Comment by llucax** [comment]
I see this issue is assigned to milestone 6.1, what is exactly the difference with #152 (which doesn't have a milestone assigned)?

**Comment by pulsejet** [comment]
![image](https://github.com/pulsejet/memories/assets/10709794/c77bccee-dabc-4a4c-b0b3-3dd2a01a1051)
![image](https://github.com/pulsejet/memories/assets/10709794/db279df1-7017-4141-a9ca-d1bb09bb4717)
![image](https://github.com/pulsejet/memories/assets/10709794/6269445b-d8a1-4fb6-8689-69e1b5fd3b42)
