### ISSUE TITLE
Please stop changing the description of the project so often.

### ISSUE THREAD

**Issue by roliverio** [pulsejet/memories#538]
Would be nice to have a unified, consistent project description that changes **only** when a new feature that is worth of mentioning is added, and not constantly changing the wording on each feature or adding minor info about the existent ones, the translation team has updated the translation of the app summary no less than 60 times in the last 6 months.

Please move these to a CHANGELOG that requires translation, otherwise, please refrain from updating the project description with something that is not worth of mentioning, or, a simple tense change.

Sincerely, and loving your work.

The l10n team.

**Comment by pulsejet** [comment]
Noted.

Would it make sense to just remove the readme from the translations altogether (assuming this is even possible)? Most of the documentation and debugging info is in English anyway (which is intended, to avoid confusion).

**Comment by roliverio** [comment]
I don't mind translating the Readme, is useful, and provides a good informational summary of the app's functionality, but changing it often makes no sense, IMHO. That's why i emphasize on changing it each time a new feature, or a significant change to one is added.

Not a rant, rather a simple recommendation, and, i do like this app a lot.

Thanks!

**Comment by pulsejet** [comment]
No worries, I have zero familiarity with how translations work; so just wanted to confirm the current behavior is sensible. Thanks for your hard work on the translations!

Closing this; will avoid unnecessary changes in the future (and refer PRs here).

Btw, does updating the sponsor list in the readme require the text to be translated again? In that case I'll move that section somewhere else.

**Comment by roliverio** [comment]
No, the changes are always coming from: appinfo/info.xml.

So, the sponsorship summary or the README file itself is not the source of the change.

Thanks again!
