### ISSUE TITLE
Ignore EXIF or binary blocks with invalid dates of 0000-00-00

### ISSUE THREAD

**Issue by invario** [pulsejet/memories#539]
So I've run into a little issue wherein media files (MP4 specifically) are being tagged with dates of 0000-00-00. 

For example, two files saved from LINE (chat app) on Android result in the following when running "exiftool -G -AllDates filename"

No results for JPG

For an MP4:
```
[QuickTime]     Create Date                     : 0000:00:00 00:00:00
[QuickTime]     Modify Date                     : 0000:00:00 00:00:00
```

I've learned from searching that it is impossible to delete this tag because it's a binary data chunk in the file. In fact, trying to delete it with exiftool results in exactly this (all zeros ) I can of course set it to a valid date (which I can do manually by using CreateDate<FileModifyDate) but I have to do this by hand every single time I save a video from LINE. I'm going to assume that this may happen in other software as well?

I think right now Memories interprets 0000-00-00 to be a date of 1903-12-31 or somewhere thereabouts. I mention my difficulties here:
https://github.com/pulsejet/memories/issues/486#issuecomment-1481527381

Would it be possible to have Memories completely ignore the invalid dates of 0000-00-00 and therefore fallback to an alternate more valid date (like from the file creation or modification date)?

Thank you for your continued work!

**Comment by pulsejet** [comment]
Hmm, these should already be ignored, so this is a bug
https://github.com/pulsejet/memories/blob/405deeea4b616c8be003d1a0d0db86f32223cbca/lib/Exif.php#L120-L135
