### ISSUE TITLE
Have Ability To Exclude External Storage

### ISSUE THREAD

**Issue by tiongsengis** [pulsejet/memories#540]
**Is your feature request related to a problem? Please describe.**
My office defines external storage to map to conventional terabytes filing system. 
The Memories scanning processes exhausted my servers especially it multiplies based on individual accounts. 
It has being runs for day endlessly,

**Describe the solution you'd like**
Only require cloud content published in Nextcloud, exclude External Storage.
Need manual option in Memories to include or exclude External Storage.

**Describe alternatives you've considered**
I do not have alternative but have to uninstalled Memories before the scan drain my filing system.

**Additional context**
N.A.

**Comment by vitis586** [comment]
I placed a `.nomedia` file into the root of my external storage and also set the root for Memories to my personal folder. Have you tried that?

Nextcloud also supports `.noimage` although the use is not very well documented anywhere really.

See:
https://github.com/nextcloud/recognize/pull/457
https://github.com/nextcloud/photos/issues/234

**Comment by pulsejet** [comment]
As @vitis586, you need to use a `.nomedia` file.
