### ISSUE TITLE
Transcoding failed: Transcoder not found; start 

### ISSUE THREAD

**Issue by ZOKOB** [pulsejet/memories#541]
hello I am using Nextcloud Hub 4 (26.0.0 Build:2023-04-03T23:24:56+00:00 snap version with latest memories version.
however when I want to play a video I get this error message:

https://ibb.co/RTRNMqb

in the logs I have this:

"Memories error2023-04-05T07:06:13+0200
Transcoding failed: Transcoder not found; start occ memorabilia video setup! (/var/snap/nextcloud/33908/nextcloud/extra-apps/memories/exiftool-bin/go-vod-amd64)"

do you know how to solve the problem?

Thanking you in advance, I wish you a pleasant day.

cordially remy

**Comment by pulsejet** [comment]
Run `occ memories video-setup`

e.g. `sudo nextcloud.occ memories video-setup`

https://help.nextcloud.com/t/using-occ-on-snap-nextcloud-installation/107129

**Comment by ZOKOB** [comment]
Thank you ! 
It's good now ! 
Have nice day
