### ISSUE TITLE
Hardware Transcoding fails with HTTP error 404

### ISSUE THREAD

**Issue by Azel04** [pulsejet/memories#544]
**Describe the bug**
Hardware Transcoding does not work.
When i try to set it up with occ memories:video-setup it gives me HTTP error 404

**To Reproduce**
run occ memories:video-setup

**Screenshots**
![immagine](https://user-images.githubusercontent.com/75199595/230198042-1a41f4c4-4aeb-4de1-86bd-86a4ae91fe99.png)

**Platform (please complete the following information):**

- OS: Ubuntu Server 22.04 LTS

- Version 4.13.1

**Additional context**
Downgrading to 4.13.0 fixes the problem
SPECS:
Intel Core i5 6400 (iGPU for transcoding)
8GB RAM
Nextcloud 26.0.0 (Native install)
Data is on a separate HDD (configured as main drive in Nextcloud)

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration). YES
- I am NOT using `OCCWeb` to run `occ` commands YES
- The problem persists after clearing browser cache YES

**Comment by pulsejet** [comment]
Anything in go-vod logs?

**Comment by Azel04** [comment]
`&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/ocibm23o4q47 ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/06 06:34:38 Starting VOD server
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/ocibm23o4q47 ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/06 06:34:40 Starting VOD server
2023/04/06 06:34:41 test: new manager for /tmp/sample.mp4O7MqAm
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/ocibm23o4q47 ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:true VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/06 06:34:42 Starting VOD server
2023/04/06 06:34:43 test: new manager for /tmp/sample.mp4O7MqAm
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/ocibm23o4q47 ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:true VAAPILowPower:true NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/06 06:34:44 Starting VOD server
2023/04/06 06:34:45 test: new manager for /tmp/sample.mp4O7MqAm
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/ocibm23o4q47 ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:true NVENCTemporalAQ:false NVENCScale:npp}
2023/04/06 06:34:46 Starting VOD server
2023/04/06 06:34:47 test: new manager for /tmp/sample.mp4O7MqAm
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/ocibm23o4q47 ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:true NVENCTemporalAQ:false NVENCScale:cuda}
2023/04/06 06:34:48 Starting VOD server
2023/04/06 06:34:49 test: new manager for /tmp/sample.mp4O7MqAm
`

This was in the logs after I tried it again today with the same result.
It's 8:35AM right now where I live and the logs don't go further than 6:34 which i do not understand

**Comment by XTREEMMAK** [comment]
+1 here as well.
Did a fresh install and just trying to get CPU transcoding to work as I'm running Nextcloud in a VM with no GPU.

In /tmp, I do see a go-vod folder was created. I don't have a transcode folder though everytime I try to do a video, and Nextcloud returns:

Transcode failed: Transcoder returned 408

in the logs.

**Comment by XTREEMMAK** [comment]
Here's one for an actual file I was trying.

```
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/ocawrp9vl9ft ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/07 20:21:21 Starting VOD server
2023/04/07 20:21:22 btasr3h1k3b0: new manager for /mnt/GIMLI-Homes/XTREEMMAK/Photos/2023/2023 - MEGACON/20230401_150905.mp4
2023/04/07 20:21:22 btasr3h1k3b0-1080p: stopping stream
2023/04/07 20:21:22 btasr3h1k3b0-1080p: /usr/bin/ffmpeg -loglevel warning -autorotate 0 -i /mnt/GIMLI-Homes/XTREEMMAK/Photos/2023/2023 - MEGACON/20230401_150905.mp4 -copyts -vf format=nv12,scale=force_original_aspect_ratio=decrease:w=1920:h=1080 -profile:v main -maxrate 7200000 -bufsize 14400000 -map 0:v:0 -c:v libx264 -preset faster -crf 24 -map 0:a:0? -c:a aac -ac 1 -avoid_negative_ts disabled -f hls -hls_time 3 -force_key_frames expr:gte(t,n_forced*3) -hls_segment_type mpegts -start_number 0 -hls_segment_filename /tmp/go-vod/ocawrp9vl9ft/btasr3h1k3b0-824022874/1080p-%06d.ts -
2023/04/07 20:21:38 btasr3h1k3b0-1080p: recv 1080p-000000.ts
2023/04/07 20:21:38 btasr3h1k3b0-1080p: recv 1080p-000001.ts
2023/04/07 20:22:27 btasr3h1k3b0-1080p: stopping stream
2023/04/07 20:23:27 btasr3h1k3b0: destroying manager
2023/04/07 20:23:27 btasr3h1k3b0-720p: stopping stream
2023/04/07 20:23:27 btasr3h1k3b0-1080p: stopping stream
2023/04/07 20:23:27 btasr3h1k3b0-1440p: stopping stream
2023/04/07 20:23:27 btasr3h1k3b0-2160p: stopping stream
2023/04/07 20:23:27 btasr3h1k3b0-max: stopping stream
2023/04/07 20:23:27 btasr3h1k3b0-360p: stopping stream
2023/04/07 20:23:27 btasr3h1k3b0-480p: stopping stream
```

**Comment by XTREEMMAK** [comment]
Just an update on this,
Not sure why the "occ memories:video-setup" still fails at CPU Transcoding, but I just checked a few more videos and some of my older ones ARE indeed transcoding.

It seems the ones that are failing are videos encoded in HEVC HDR10 that were recorded on my phone. So seems I either switch to AVC, Direct Play those videos, or just wait for support to mature I guess. Still wanted to note my findings at least.

**Comment by Gymnae** [comment]
Might have a comparable problem. I get an 404 when setting up video and the log contains the following:
```
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/ocl5kp6n4i2h ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/08 10:35:29 Starting VOD server
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/ocl5kp6n4i2h ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/08 10:35:31 Starting VOD server
2023/04/08 10:35:32 test: new manager for /tmp/sample.mp4ffzOW0
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/ocl5kp6n4i2h ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:true NVENCTemporalAQ:false NVENCScale:npp}
2023/04/08 10:35:33 Starting VOD server
2023/04/08 10:35:34 test: new manager for /tmp/sample.mp4ffzOW0
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/ocl5kp6n4i2h ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:true NVENCTemporalAQ:false NVENCScale:cuda}
2023/04/08 10:35:35 Starting VOD server
2023/04/08 10:35:36 test: new manager for /tmp/sample.mp4ffzOW0
```
It appears that transcoding is "kind of" working. Live Photos from Apple devices won't play on mobile Safari, Chromium based browsers but will play on Desktop Safari in macOS.

Chromium throws the following errors:

```
service-worker.js:2 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://cloud.domain.tld/apps/memories/js/memories-main.js.LICENSE.txt","status":404}]
    at v._handleInstall (https://cloud.domain.tld/apps/memories/service-worker.js:2:68885)
    at async v._handle (https://cloud.domain.tld/apps/memories/service-worker.js:2:68294)
    at async v._getResponse (https://cloud.domain.tld/apps/memories/service-worker.js:2:67376)


service-worker.js:2 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://cloud.domain.tld/apps/memories/js/memories-main.js.LICENSE.txt","status":404}]
    at v._handleInstall (https://cloud.domain.tld/apps/memories/service-worker.js:2:68885)
    at async v._handle (https://cloud.domain.tld/apps/memories/service-worker.js:2:68294)
    at async v._getResponse (https://cloud.domain.tld/apps/memories/service-worker.js:2:67376)

 GET https://cloud.domain.tld/apps/memories/api/image/preview/3091186?c=319e07ddac934bdc710742d162004069&x=512&y=512&a=1 500 memories-main.js?v=8046de54-46:2         



memories-main.js?v=8046de54-46:2 Failed to load XImg 
r {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}
code
: 
"ERR_BAD_RESPONSE"
config
: 
{transitional: {…}, transformRequest: Array(1), transformResponse: Array(1), timeout: 0, adapter: ƒ, …}
message
: 
"Request failed with status code 500"
name
: 
"AxiosError"
request
: 
XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
response
: 
{data: Blob, status: 500, statusText: '', headers: {…}, config: {…}, …}
[[Prototype]]
: 
Error
```

**Comment by Gymnae** [comment]
Actually, in addition to my earlier comments, it seems that live photos won't play in Safari on Desktop. It only worked for those cached from when I turned off transcoding with memories:video-setup

Desktop Safari now throws the following errors:
```
[Error] Failed to load resource: the server responded with a status of 404 () (memories-main.js.map, line 0)

[Error] Unhandled Promise Rejection: NotSupportedError: The operation is not supported.

[Error] Failed to load resource: the server responded with a status of 404 () (memories-vendors-node_modules_nextcloud_vue_dist_Components_NcCheckboxRadioSwitch_js.js.map, line 0)

[Error] Failed to load resource: the server responded with a status of 404 () (memories-vendors-node_modules_nextcloud_vue_dist_Components_NcAppSettingsDialog_js.js.map, line 0)

[Error] Failed to load resource: the server responded with a status of 404 () (memories-vendors-node_modules_nextcloud_vue_dist_Components_NcBreadcrumb_js.js.map, line 0)

[Error] Failed to load resource: the server responded with a status of 404 () (memories-node_modules_nextcloud_vue_dist_Components_NcAppSettingsSection_js.js.map, line 0)

[Error] Failed to load resource: the server responded with a status of 404 () (memories-vendors-node_modules_nextcloud_vue_dist_Components_NcBreadcrumbs_js.js.map, line 0)

[Error] Failed to load resource: the server responded with a status of 404 () (memories-vendors-node_modules_nextcloud_vue_dist_Components_NcAppNavigationItem_js.js.map, line 0)
```

**Comment by pulsejet** [comment]
So I'm starting to think that feature detection and auto-starting the transcoder is more trouble than it is worth. Maybe the better idea is to make transcoding optional and the only way to set it up is to run it manually say using docker compose or systemd.

For now, I'd suggest forgetting about `video-setup` and configuring an external go-vod instance. [This](https://github.com/pulsejet/memories/wiki/HW-Transcoding#external-transcoder-recommended) and [this](https://github.com/pulsejet/memories/wiki/System-config-options) will be useful.

**Comment by Gymnae** [comment]
My server has AMD EPYC CPUs (I'm renting a share of it) without any HW acceleration for transcoding, would this approach work for me? I need to run all on the CPU in software.
And my main concern is to have live photos working (again) because the rest seems fine, all videos play in all browsers.

**Comment by jb8628** [comment]
I'm also seeing this issue. Using nextcloud AIO ([https://github.com/nextcloud/all-in-one]), which makes configuring external go-vod that bit more complicated.

Many thanks for all your doing. This is a big step forward in terms of managing self-hosted photos.

**Comment by Skydiver84de** [comment]
Can it be a proxy related error? I got the same 404 erros running nextcloud behind traefik (which is defined as trusted proxy). However adding `'memories.vod.vaapi' => true,` to config.php worked out of the box.

I am using linuxserver nextcloud docker on unraid and added /dev/dri for an intel internal gpu as described in the docs...

**Comment by vitis586** [comment]
I think that it is not proxy related. I am getting those 404s too on my testing node and that one is running just locally without proxy. The sample gets downloaded as I saw it in the tmp folder, but still something is 404.
I too managed to get transcoding running via CPU and GPU. I am now working on the external decoder as it is recommended.

**Comment by pulsejet** [comment]
Stale
