### ISSUE TITLE
[Mobile] Refresh timeline on pull down

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#547]
**Is your feature request related to a problem? Please describe.**
I find myself constantly trying to pull/swipe down to refresh the memories mobile web app.
I often take a photo on my phone, use nextcloud app to sync it up, and then wait for it to show up in Memories so i can share it.

**Describe the solution you'd like**
Pulling/Swiping down on the timeline could refresh the page (or better yet, just load any new images)

**Describe alternatives you've considered**
I currently just manually refresh the page by navigating away from memories to a different nextcloud app, then back to the memories web app. Alternatively i can force-close the memories web app and restart it.

**Additional context**
When using Memories as a web app, the default browser refresh button is not  readily accessible since the browser menus are hidden.

**Comment by MikeDuncan1** [comment]
I'm going to throw it out there that _automatically_ updating every 10 seconds or something like that would be ideal to me, but yes, I end up closing memories every other time I open it so I can get it to update :)
