### ISSUE TITLE
Horizontal Timeline does not offer all years back into photo history

### ISSUE THREAD

**Issue by TDannhauer** [pulsejet/memories#548]
**Describe the bug**
I have photos going back a quarter century. This is correctly reflected in the vertical timeline.

However, it is not correctly reflected in the top row horizontally timeline. here it ends with "16 years ago"

I think that worked before I upgraded to NC 26

**To Reproduce**
* Have lots of photos
* Check weether the horizontal timeline offers all the years you have in photos ( and which are offered in the vertical timeline.)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6716033/230633187-a54fcea1-b4e7-4e5e-847d-e54bf1153ffb.png)

**Platform (please complete the following information):**

- OS: Win10
- Browser Firefox
- Version 111.0.1

**Additional context**

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
- I am NOT using `OCCWeb` to run `occ` commands
- The problem persists after clearing browser cache

**Comment by pulsejet** [comment]
Do you have photos around today's date? The horizontal timeline only shows photos around this day x years ago.

**Comment by TDannhauer** [comment]
Yes I have photos from now() till now()-23years.

from 1year ago till 16years ago it works as intended but not further back.

**Comment by pulsejet** [comment]
It's not about the year but the date. E.g. On April 6 2023, the horizontal timeline will show photos from April 5 2001 but not April 1 2001.

**Comment by TDannhauer** [comment]
Understood. I‘m not talking about which Fotoclubs shown in wich group, but why are the photos of the 17th year ago not grouped and offered as „17 years ago“? This is perfectly working with „16 years ago“ and less

**Comment by pulsejet** [comment]
Exactly, my question is if you do have photos in the applicable date range (approx around today's date) 17 years ago. Just having photos from 17 years ago won't make them show up there.

**Comment by TDannhauer** [comment]
Aaah maybe I understood that timeline wrong: I thought it was grouping year wise.

Do I understand you right that is is basically a “today 17 year ago”? :)so If I have photos of end of April 17 years ago they won’t be presented since we have the 7th?

**Comment by pulsejet** [comment]
Yes, exactly :)

**Comment by TDannhauer** [comment]
Thanks, then it is not an issue :)
