### ISSUE TITLE
Following a shared folder link as logged-in user breaks the URL

### ISSUE THREAD

**Issue by Gymnae** [pulsejet/memories#550]
**Describe the bug**
1. Have a shared folder public link, like this: `https://cloud.domain.tld/apps/memories/s/share_name`
2. Click on link while being logged-in as a normal user / admin 
3. See how URL is transformed to: `https://cloud.domain.tld/apps/memories/folders//toplevelfolder/sublevelfolder/share_name`
4. memories adds one slash (/) too many behind "folders"

**Platform (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version latest

**Comment by Gymnae** [comment]
Some more about that:

1. It doesn't affect users who are only accessing a folder shared with them
2. It affects the sharing user - in my case I'm sharing a folder from local external storage

**Comment by Wordsmith9091** [comment]
I'm new to Github and bug reporting so I hope this is helpful and not unnecessarily redundant ... 

Just adding that I'm continuing to see behavior reported here as of version 5.4.1.

**Comment by pulsejet** [comment]
@Wordsmith9091 there turned out to be some corner cases that are hopefully now fixed on master. Try this patch: https://github.com/pulsejet/memories/commit/4122f592b6115d61c5a66440c5d544e9c8316755 (you'll need to reboot the server if you apply this)

**Comment by Wordsmith9091** [comment]
Great! It looks like this works. Thanks!
