### ISSUE TITLE
Date deleted after updating geolocation (without other EXIF data present)

### ISSUE THREAD

**Issue by whitemanthedj** [pulsejet/memories#551]
**Describe the bug**
Whenever I update the geolocation of a photo without any EXIF data (tested against camera metadata), the date gets set to today rather than the original date that the photo was taken. I have verified on other photos that have camera models or other EXIF data that the bug is not present.

**To Reproduce**
1. Set a photo's geolocation via the Memories UI that previously did not have one (without a camera model or other exif data present prior).
2. Verify that the date has updated to today.

**Screenshots**
Below is an example of the date getting removed on a picture without the camera model after the geolocation is set.
![picture_EXIF](https://user-images.githubusercontent.com/44525898/230690508-4a453d6d-9ae2-45fb-a43e-5cb1c63ff066.png)
![picture_date_removed](https://user-images.githubusercontent.com/44525898/230690506-c904998f-0ca2-4c42-955e-523daa875a70.png)

Below is an example of the date remaining on a picture with a camera model after the geolocation is set.
![picture_EXIF_withCamera](https://user-images.githubusercontent.com/44525898/230691233-d4c369f7-5083-403b-aa8c-131cd95de4a2.png)
![picture_date_NOT_removed_withCamera](https://user-images.githubusercontent.com/44525898/230691250-3a57e5d9-7569-45f1-a938-7762d48f458b.png)

**Platform (please complete the following information):**

    - Windows client, Nextcloud hosted on Ubuntu
    - Chrome
- Version [e.g. 4.1.0]
    - 4.13.1

**Additional context**
Add any other context about the problem here: Refreshing does not change the outcome, the date is permanently changed until I manually change it back. Wish I had more time to pick up php or I would would offer to help, but never used it before.

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
- I am NOT using `OCCWeb` to run `occ` commands
- The problem persists after clearing browser cache

**Comment by pulsejet** [comment]
If the photo has no exif date, then it'll use the modified time of the file as the date. When you update the photo the "modified" timestamp is (correctly) updated to the current time. So the time is reset to today.

**Comment by whitemanthedj** [comment]
Thanks for the quick reply @pulsejet! Is there a way to add the modification date to the exif data (especially in bulk?) or prevent that it from updating? 

I have also tried to set the date via the sidebar UI before changing the location and it still results in the timestamp getting updated unless I change the time to a different time and then back again

**Comment by pulsejet** [comment]
Converting the modification date to the exif date would be a good feature to have (open a seperate issue). Currently you can do that quite easily with exiftool. Probably something like `exiftool "-datetimeoriginal<filemodifydate" DIR`.

> or prevent that it from updating?

This would be incorrect. If the file is updated, the modified time has to change.

> I have also tried to set the date via the sidebar UI before changing the location and it still results in the timestamp getting updated unless I change the time to a different time and then back again

It's simply skipping the update because you didn't change anything.

**Comment by whitemanthedj** [comment]
Sweet, thanks yea, I was just trying to describe the behavior that I saw. Will open another feature and use the exiftool command in the meantime!

Thanks again, I am loving this app.
