### ISSUE TITLE
Option to default to closed navigation for shares

### ISSUE THREAD

**Issue by Gymnae** [pulsejet/memories#553]
**Is your feature request related to a problem? Please describe.**
When opening a shared folder or album, I might not have much else in my memories install, so I don't need to see the navigation.

**Describe the solution you'd like**
Being able to define as part of sharing or global setting whether to have the navigation collapsed or open by default.

**Comment by pulsejet** [comment]
Very good point. I think it makes sense to collapse it by default when opening any share.
