### ISSUE TITLE
Missing images with shared folders

### ISSUE THREAD

**Issue by RobTranquillo** [pulsejet/memories#554]
**Describe the bug**

Nextcloud vanilla installation inside an LXC container with Debian. Not much NC plugins. No external storage.
Set an folder `/memories-root/` as base folder for memories image stream in my user account (root). All worked fine.
Now share that folder with another person in the same instance, because both should be able to upload images. Using NC folder share for that. But now, only the seconds person images are appear in Memories. 

```
Checking database indices

MIME Type support:
  image/png: supported
  image/jpeg: supported
  image/heic: not supported
  image/png: supported
  image/tiff: not supported
  image/gif: supported
  image/bmp: supported
  image/x-dcraw: not supported
  video/mpeg: supported
  video/webm: supported
  video/mp4: supported
  video/quicktime: supported
  video/x-matroska: supported
  video/MP2T: supported

Some file types are not supported by your preview provider.
Please see https://github.com/pulsejet/memories/wiki/File-Type-Support

Scanning files for P3ggy
[...]
Scanning /P3ggy/files/memories_root/urlaub/20230324_102622.jpg
Scanning /P3ggy/files/memories_root/urlaub/20230324_102627.jpg
Scanning /P3ggy/files/memories_root/urlaub/20230330_071034.jpg
Could not scan folder /P3ggy/files/memories_root/urlaub: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.memories_planet_geometry' doesn't exist
Scanned all files for P3ggy

Scanning files for root
[...]

Scanning /root/files/memories_root/urlaub/20230324_102622.jpg
Scanning /root/files/memories_root/urlaub/20230324_102627.jpg
Scanning /root/files/memories_root/urlaub/20230330_071034.jpg
Could not scan folder /root/files/memories_root/urlaub: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.memories_planet_geometry' doesn't exist
Scanned all files for root

==========================================
Checked 576 files of 5 users in 1.185 sec
248 not valid media items
0 .nomedia folders ignored
328 skipped because unmodified
0 (re-)processed
==========================================


In the output while the reindexing I see `nextcloud.memories_planet_geometr` what reminds me, that some weeks ago I did the `places-setup` but aboard it while the process of downloading the planet file.
```

**To Reproduce**
I don't know. At first it worked with the shared folder, but now it doesn't.

**Platform (please complete the following information):**

- OS: debian 10.11
- Version Memories 4.13.1
- Version NC: 25.5

**Additional context**

We do it like described for some weeks and it worked. But today I recognized, that hundreds of my (user: root) last images and videos are missing and mostly the media from the second person are viewable in the stream.  Some single images from me appear, I have no clue why.

Most recently I tried uploading a 20gb video over bad wifi, which was unsuccessful. Another video of 80mb was successfully uploaded but the playback is broken, no image appears and only a few seconds of audio, then it stops. But I don't know if these video problems are related to the missing images problem. 

I do reindexing a couple of times and restart the whole server container. With no luck.   

We use mostly Nextcloud Android App to upload the images. Images uploaded via Webbrowser (lubuntu/FF) also not appear.

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
- I am NOT using `OCCWeb` to run `occ` commands
- The problem persists after clearing browser cache

Yes

**Thank you for any help and thank you for that fantastic app.**

**Comment by pulsejet** [comment]
Two different things going on here.

1. Check your files in Nextcloud. If they aren't uploading correctly, then it has nothing to do with Memories. You might need to tweak your PHP/Apache/FPM configuration.
2. You need to let `occ memories:places-setup` complete.

**Comment by RobTranquillo** [comment]
Thanks for your answer.  It worked! :-)

I have two points to contribute to the improvement:
- places-setup should include the approximate amount of memory expected for the planetfile. 
- the operator "-f" or "--clear" for memories:index 
 is nowhere in the docs, but maybe it was the one that helped. It could be mentioned publicly.
