### ISSUE TITLE
Wrong timezone parsing of media without Exif data

### ISSUE THREAD

**Issue by penguinsam** [pulsejet/memories#556]
**Describe the bug**
Showing wrong date in timeline of media without Exif data

**To Reproduce**
Upload media without Exif data and with modify date/time has timezone offset

**Screenshots**
Media below will be shown under 2020-12-18 in Memories.

`stat IMG_0045.JPG 
  File: IMG_0045.JPG
  Size: 283740    	Blocks: 560        IO Block: 4096   regular file
Device: 49h/73d	Inode: 99894       Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/     sam)   Gid: ( 1001/  family)
Access: 2023-04-09 06:25:16.877742920 +0800
Modify: 2020-12-19 01:27:06.000000000 +0800
Change: 2023-04-09 06:25:12.077573233 +0800
 Birth: -`

**Platform (please complete the following information):**

- OS: Linux
- Browser: Vivaldi
- Version: 5.7.2921.65

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration): YES
- I am NOT using `OCCWeb` to run `occ` commands: YES
- The problem persists after clearing browser cache: YES

**Comment by pulsejet** [comment]
The modification time has no concept of timezone; it's just a unix epoch. So the only thing possible is to use the system timezone.

**Comment by pulsejet** [comment]
Closing this for now

**Comment by invario** [comment]
Hi, forgive me but does this mean there's no way around the incorrect time being displayed?

For example, here's the info for a file I saved this today 5/26 @ 8:59AM local time. I am in the US/EDT timezone, and the offset should be -4 hrs currently.
![image](https://github.com/pulsejet/memories/assets/67800603/5f337dda-46f9-49a5-b4d2-3f40db9da425)
Exiftool on the file shows:
`File Modification Date/Time     : 2023:05:26 08:59:08-04:00`

And my system local date currently shows:
`Fri May 26 15:00:24 EDT 2023
`

There's no way to compensate for the timezone difference to display the correct time of 8:59 versus 12:59 being shown?

**Comment by pulsejet** [comment]
Are you running Docker? You might be missing some environment variables or PHP config. Basically PHP needs to see the system timezone correctly.

**Comment by invario** [comment]
> Are you running Docker? You might be missing some environment variables or PHP config. Basically PHP needs to see the system timezone correctly.

Running it in a FreeBSD jail.
My php.ini currently has this line:
`date.timezone = "America/New_York"`
and php -i shows the following:
```
date

date/time support => enabled
timelib version => 2021.17
"Olson" Timezone Database Version => 2022.4
Timezone Database => internal
Default timezone => America/New_York

Directive => Local Value => Master Value
date.default_latitude => 31.7667 => 31.7667
date.default_longitude => 35.2333 => 35.2333
date.sunrise_zenith => 90.833333 => 90.833333
date.sunset_zenith => 90.833333 => 90.833333
date.timezone => America/New_York => America/New_York
```

**Comment by pulsejet** [comment]
Possibly regression. Can you open a new issue with this and a sample file?

**Comment by invario** [comment]
Ok. I'll make another thread and find a sample file. But the files don't have tags really anyway:

```
[ExifTool]      ExifTool Version Number         : 12.42
[File]          File Name                       : 1685105948040.jpg
[File]          Directory                       : .
[File]          File Size                       : 196 kB
[File]          File Modification Date/Time     : 2023:05:26 08:59:08-04:00
[File]          File Access Date/Time           : 2023:05:27 16:40:32-04:00
[File]          File Inode Change Date/Time     : 2023:05:26 14:48:03-04:00
[File]          File Permissions                : -rw-r--r--
[File]          File Type                       : JPEG
[File]          File Type Extension             : jpg
[File]          MIME Type                       : image/jpeg
[File]          Exif Byte Order                 : Big-endian (Motorola, MM)
[File]          Image Width                     : 1108
[File]          Image Height                    : 1477
[File]          Encoding Process                : Baseline DCT, Huffman coding
[File]          Bits Per Sample                 : 8
[File]          Color Components                : 3
[File]          Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
[EXIF]          Light Source                    : Unknown
[EXIF]          Orientation                     : Unknown (0)
[JFIF]          JFIF Version                    : 1.01
[JFIF]          Resolution Unit                 : None
[JFIF]          X Resolution                    : 1
[JFIF]          Y Resolution                    : 1
[ICC_Profile]   Profile CMM Type                :
[ICC_Profile]   Profile Version                 : 4.3.0
[ICC_Profile]   Profile Class                   : Display Device Profile
[ICC_Profile]   Color Space Data                : RGB
[ICC_Profile]   Profile Connection Space        : XYZ
[ICC_Profile]   Profile Date Time               : 0000:00:00 00:00:00
[ICC_Profile]   Profile File Signature          : acsp
[ICC_Profile]   Primary Platform                : Unknown ()
[ICC_Profile]   CMM Flags                       : Not Embedded, Independent
[ICC_Profile]   Device Manufacturer             :
[ICC_Profile]   Device Model                    :
[ICC_Profile]   Device Attributes               : Reflective, Glossy, Positive,
Color
[ICC_Profile]   Rendering Intent                : Media-Relative Colorimetric
[ICC_Profile]   Connection Space Illuminant     : 0.9642 1 0.82491
[ICC_Profile]   Profile Creator                 :
[ICC_Profile]   Profile ID                      : 0
[ICC_Profile]   Profile Description             : sRGB
[ICC_Profile]   Red Matrix Column               : 0.43607 0.22249 0.01392
[ICC_Profile]   Green Matrix Column             : 0.38515 0.71687 0.09708
[ICC_Profile]   Blue Matrix Column              : 0.14307 0.06061 0.7141
[ICC_Profile]   Red Tone Reproduction Curve     : (Binary data 40 bytes, use -b
option to extract)
[ICC_Profile]   Green Tone Reproduction Curve   : (Binary data 40 bytes, use -b
option to extract)
[ICC_Profile]   Blue Tone Reproduction Curve    : (Binary data 40 bytes, use -b
option to extract)
[ICC_Profile]   Media White Point               : 0.9642 1 0.82491
[ICC_Profile]   Profile Copyright               : Google Inc. 2016
[Composite]     Image Size                      : 1108x1477
[Composite]     Megapixels                      : 1.6
```
