### ISSUE TITLE
Allow for changing the default cover photo for albums

### ISSUE THREAD

**Issue by XTREEMMAK** [pulsejet/memories#557]
**Is your feature request related to a problem? Please describe.**
Currently, you are not able to change the cover photo of any of the albums. The app simply selects a photo at random to act as the cover for any album. While the title of the album is listed, in some cases, it makes things difficult to spot an album from glancing at the screen. Having a picture you know by heart that is associated with that album would make things a lot easier for usability.

**Describe the solution you'd like**
A  way to select a photo of choice from within the album as the specified album cover. 

**Describe alternatives you've considered**
Haven't considered any alternative at the moment. If it is really that important to me now, I guess I could spin up a custom front end with say something like Ghost and link it back to a memories album, but I'd rather not lol.

**Additional context**
I believe part of this problem is also related to Nextcloud Photos. Since Memories relies on Photos for albums, I think part of the solution might be Photos' implementation of custom album covers first (which honestly might take some work off Memories development I guess?). I could be wrong though and who's to say that Memories cant handle its own implementation of album covers separate from Photos? It might even handle it better.

As an example of seeing this in action, I believe Google Photos already does this, but another example would be Synology Photos.

**Comment by g3n35i5** [comment]
Might me related to #125

**Comment by pulsejet** [comment]
Fixed with https://github.com/pulsejet/memories/pull/1071
