### ISSUE TITLE
share URLs should be meaningful

### ISSUE THREAD

**Issue by tomchiverton** [pulsejet/memories#561]
I'm always frustrated when I go to publicly share a folder, but there's no way to give it a name that is meaningful.

**Describe the solution you'd like**
Instead of a URL that is impossible to read over the phone, such as https://nextcloud.falkensweb.com/apps/memories/a/A8PUIysKhgG6vknNdzc0mociXGWgT9XX a URL such as https://nextcloud.falkensweb.com/apps/memories/albums/lego

**Describe alternatives you've considered**
Custom rules in Apache/Nginx config - not user editable

**Additional context**

**Comment by Gymnae** [comment]
This works perfectly fine: https://apps.nextcloud.com/apps/sharerenamer
I use it to rename the name of shared folders, albums might work too
But it works also for all other shares

**Comment by tomchiverton** [comment]
>These URLs are public; the meaningless token is a security feature. If they were readable, someone could easily guess them.

That'd be my choice to make though. Some words on the share page could make this obvious.

**Comment by tomchiverton** [comment]
> This works perfectly fine: https://apps.nextcloud.com/apps/sharerenamer I use it to rename the name of shared folders, albums appear to not work with this trick 

Supporting ShareRenamer for album shares would cover my use case fine

**Comment by tomchiverton** [comment]
Ta; https://github.com/nextcloud/photos/issues/1734
