### ISSUE TITLE
Moving files fails with error message when automated tagging is active

### ISSUE THREAD

**Issue by Gymnae** [pulsejet/memories#568]
**Describe the bug**
When using the automated tagging app to add a collaborative tag automatically, memories throws an error that it fails to move the file, while it actually moves the file successfully. The tag is applied, but the action does not propagate to activities - nextcloud does not recognize, that the file is moved

When moving the file out of the folder subject to automated tagging, the operation works without error and the action propagates through nextcloud

The error message thrown: 
OCP\Files\NotFoundException

Moving the file in the files app to the folder subject to automated tagging works without a problem and the action propagates throughout nextcloud

This is how the tag flow looks:
<img width="975" alt="Screenshot 2023-04-14 at 17 49 53" src="https://user-images.githubusercontent.com/6195487/232092802-3e23a130-d2a7-4ca6-b1c4-ac5be5242506.png">

the same collaborative tag is applied to the folder where files are moved into

Steps to reproduce:

1. Install the automated tagging app
2. Tag a folder memories has access to with a collaborative tag
3. Set up a flow to automatic tag files in the folder with the same tag (see screenshot)
4. Move images/videos in memories to this folder
5. See error

**Comment by pulsejet** [comment]
I'm very confused. Are you talking about moving files with the "Move to folder" menu in memories?

**Comment by Gymnae** [comment]
Yes, the error appears only then. Moving files in the files app does not produce this error

**Comment by Gymnae** [comment]
Is actually an upstream bug:
https://github.com/nextcloud/files_automatedtagging/issues/728
