### ISSUE TITLE
exiftool could not be executed or test failed

### ISSUE THREAD

**Issue by estevez-dev** [pulsejet/memories#570]
**Describe the bug**
EXIF data is empty and can't be edited

**To Reproduce**
Run `occ memories:index`:
`docker compose exec -u www-data nextcloud php occ memories:index`
See the results:
```
WARN: Failed to create stay_open exiftool process
Exiftool timeout: [/var/www/html/custom_apps/memories/exiftest.jpg]
Couldn't read Exif data from test file: Could not read from Exiftool
FATAL: exiftool could not be executed or test failed
Make sure you have perl 5 installed in PATH
```

**Platform (please complete the following information):**

- OS: Docker image based on `nextcloud:apache`
- Browser Google Chrome
- Version 4.13.1

**Additional context**
I've tried installing `exiftool` inside a container with:
```
apt-get update && apt-get install libimage-exiftool-perl
```
The issue still exist.
```
docker compose exec nextcloud perl -v
```
Returns:
```
This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-gnu-thread-multi
(with 47 registered patches, see perl -V for more detail)
```

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
- I am NOT using `OCCWeb` to run `occ` commands
- The problem persists after clearing browser cache

**Comment by estevez-dev** [comment]
So I realized that the binary of exiftool is shipped with Memories. I've checked the binary and it is in place. Also, the path seems correct in `config.php`:
```
'memories.exiftool' => '/var/www/html/custom_apps/memories/exiftool-bin/exiftool-amd64-glibc',
```

**Comment by estevez-dev** [comment]
So the issue was in a tmpfs value mounted to `/tmp` in the Nextcloud container:
```
    volumes:
      - type: tmpfs
        target: /tmp
```
Once I removed this volume everything starts working. Not even sure if I need a tmpfs volume when I have a Redis.

**Comment by MrRinkana** [comment]
Sorry for the bump but how did you figure that out?
I'm having the same issue but my /tmp is not tmpfs..

**Comment by pulsejet** [comment]
https://memories.gallery/troubleshooting/#usage-of-tmpfs
