### ISSUE TITLE
Ordering in albums shared via public link broken

### ISSUE THREAD

**Issue by BWibo** [pulsejet/memories#576]
**Describe the bug**
Images in an album, that is shared via a public link, are not ordered by time.

I have a album that is shared with me. When I view the album logged in, it is displayed with image ordered as in the timeline.
When I log out and view the album via the public link, the ordering is messed up. I'm not 100% sure, but it seems like file are ordered according to addition to the album. Both me and the person that shared the album with me have added photos to the album.

**To Reproduce**
1. **UserA**: Create an album
2. **UserA**: Add some pictures. Do multiple adds in an unordered way.
3. **UserA**: Share album with UserB
4. **UserB**: Add some pictures to the shared album of UserA.
5. **UserA**: Share the album via public link
6. View the link -> Files are not ordered by time

**Platform (please complete the following information):**

- OS: Ubuntu 22 on Raspberry Pi4 (ARM)
- Firefox, and Brave (chromium) tested
- Nextcloud `26.0.0-fpm`, Memories: `5.0.3`

**Important: Are all of the following are true?**
- All true.

**Comment by pulsejet** [comment]
Are you sharing the album through Memories? If you share it through "Photos" then it'll have incorrect ordering.

**Comment by BWibo** [comment]
Thx for the feedback.
It's possible that the link was accidentially created through Photos. I'll test and get back to you.

By the way. Many thanks for the great work!

**Comment by BWibo** [comment]
My bad, the link was from Photos! 
One final question before closing this question:

Is the Photos app required to be activated, or is installed and disabled sufficient?
If it has to be active, is there a way to hide the app from the UI?

**Comment by pulsejet** [comment]
It's required if you want album support.
See https://github.com/pulsejet/memories/issues/137 :)
