### ISSUE TITLE
VA-API device (/dev/dri/renderD128) not found 

### ISSUE THREAD

**Issue by EVOTk** [pulsejet/memories#577]
**Describe the bug**
In Admin Panel of Memories : 
VA-API device (/dev/dri/renderD128) not found 

**To Reproduce**
Look Screenshots

**Screenshots**
![image](https://user-images.githubusercontent.com/45015615/232445025-bc7ac197-b89e-4603-bfd2-c59ff42221a6.png)

![image](https://user-images.githubusercontent.com/45015615/232445359-cbe11d23-8355-44e5-bcb6-1ee856339f89.png)

![image](https://user-images.githubusercontent.com/45015615/232445924-21750a49-d5a5-4c1a-bfe2-074094a2aaf1.png)

**Platform (please complete the following information):**
OS: OMV6 / Debian 11 / Docker Linuxserver
Memories : 5.0.3
Browser : Firefox 
Version 112

**Additional context**
The hardware transcoding works well. But there is a message saying that /dev/dri is not available.

**Important: Are all of the following are true?**

- [X] I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
- [X] I am NOT using `OCCWeb` to run `occ` commands
- [X] The problem persists after clearing browser cache

**Comment by SuperSandro2000** [comment]
Can you make another hotfix with this? I just ran into this problem and it took me multiple errors to find this issue and commit.

**Comment by pulsejet** [comment]
Tomorrow ;)

**Comment by Samalbert977** [comment]
Hi, I am facing the same issue on bare metal. Everything else on the memories admin page is green except this setting.

Memories version: 8.0.1
Nextcloud version: 33.0.5
OS: Ubuntu 24.04.4 LTS


Tried all the step mentioned in this page [https://memories.gallery/hw-transcoding/#bare-metal], including the testing step - which works but the memories admin page says that the device is not found

**Comment by BentiGorlich** [comment]
I also have this issue on bare metal. I'm also certain that it used to work. I tried the configuration and running the sample command also worked. I tried it with chmod 666 but that didn't change anything
