### ISSUE TITLE
Use the .nomedia to not index / unindex

### ISSUE THREAD

**Issue by ereynier** [pulsejet/memories#58]
I tried to add empty files named ".nomedia" to unindex some photos from the timeline (previewgenerator use it for example) but it doesn't worked. It could be good to implement that feature.

**Comment by pulsejet** [comment]
If you added the `.nomedia` file after indexing you need to run `occ memories:index --clear`

The path matching of memories is lexical, which means there is no better way to do this while maintaining the same performance.

**Comment by ereynier** [comment]
ok, so if I change the date of some photos the changes gonna be erased ?

**Comment by ereynier** [comment]
Nice, Thanks you
