### ISSUE TITLE
building Docker image for hardware accel - ffmpeg binary not found

### ISSUE THREAD

**Issue by WGandy** [pulsejet/memories#582]
Using docker-compose but having issues with ffmpeg binary not being found. It took me a bit till dawned that the nextcloud image being pulled doesn't have ffmpeg and other goodies installed in it and it would be best to build from a Dockerfile. So I put the Nextcloud "Full" Dockerfile in my root nextcloud docker compose folder and switched image to "Build" in the compose file. It seems to build correctly but I'm still getting the error. 
I also see a line in the memories hardware acceleration page that suggests that a file called start.sh is needed?  I copied the contents to a file with that name and put it in the root folder and used "docker compose --pull" and then "docker compose up" but I'm still having this same error. The path for ffmpeg in the admin page is simply "ffmpeg". I've tried changing it to usr/local/bin/ffmpeg etc but no fix to the error. 
What am I missing, and if I'm missing something, then it should be documented? 
Thanks,

**Comment by pulsejet** [comment]
Try running `which ffmpeg` inside the container. That should say the path if it's installed correctly.

**Comment by WGandy** [comment]
So, there should be ffmpeg running in the nextcloud container AND in the go-vod container?

**Comment by WGandy** [comment]
AHA! As expected, ffmpeg was installed in /usr/bin/. I tried placing that path manually on the admin page previously but it didn't find it. I just tried it again and walla, it found it.  Not sure what I changed that would affect that. 

But go-vod is now failing.  cURL error 7: Failed to connect to go-vod port 47788
AND
VA-API device /dev/dri/renderD128 not found.

**Comment by pulsejet** [comment]
If you are running go-vod externally, then that container needs ffmpeg too. For the curl error, either go-vod isn't running or you didn't configure the "connect" url correctly.

**Comment by WGandy** [comment]
"connection address" in the admin page? Or something else? I do indeed have go-vod as a separate container in my docker compose file.

**Comment by pulsejet** [comment]
Connection address, yes. Check the hardware acceleration wiki page.

**Comment by WGandy** [comment]
removing this line from my config.php appears to have fixed the issue with vod failing.  
'memories.vod.connect' => 'go-vod:47788',

in the admin page, I can see that the address is now '127.0.0.1:47788' instead of 'go-vod:47788'

But I'm still seeing the va-api error. I have both intel quicksync and an nvidia card in the server. I would like to experiment to see which works better.

**Comment by WGandy** [comment]
I'm not sure that I understand why go-vod has to bottom out at 127.0.0.1. Can't it be reached by its container name over a docker network?

**Comment by WGandy** [comment]
So, based on the admin page, it appears that I have ffmpeg and go-vod working. VA-API is still giving me the error and I don't know that nvidia has drivers installed or not. 

But, regardless of whether I have go-vod enabled or not, videos are not playable in Memories. I get a message at the top "The media could not be loaded, either because the server or network failed or because the format is not supported." I do get a "preview" image of the video but it won't play. And most of the videos I'm testing are mp4 files (with an h.264 encoding, I believe) and should be quite playable. In fact, they play from the files tab of nextcloud but not in Memories.

**Comment by revr3nd** [comment]
Nvidia support still have to custom compile ffmpeg to include nvenc.
At some point, the Dockerfile.nvidia was removed, and the regular Dockerfile was changed to build on top of the ffmpeg docker image. The ffmpeg image does not include nvenc support.

Below is the Dockerfile.nvidia I have written to compile ffmpeg with nvenc support:
`FROM nvidia/cuda:11.8.0-base-ubuntu20.04
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all

WORKDIR /app
ENV DEBIAN_FRONTEND=noninteractive

#Install ffmpeg dependencies
RUN set -e; \
    apt-get update ;\
    apt-get install -y \
      sudo curl wget \
      autoconf libtool libdrm-dev xorg xorg-dev openbox \
      libx11-dev libgl1-mesa-glx libgl1-mesa-dev \
      xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev \
      libxkbcommon-x11-dev libxcb-dri3-dev \
      cmake git nasm build-essential \
      libx264-dev \
      libffmpeg-nvenc-dev clang

#Install codec headers
RUN set -e ;\
    git clone --branch sdk/11.1 https://git.videolan.org/git/ffmpeg/nv-codec-headers.git ;\
    cd /app/nv-codec-headers ;\
    make install

#Compile ffmpeg
RUN set -e ;\
    git clone --depth 1 --branch n5.1.3 https://github.com/FFmpeg/FFmpeg ;\
    cd /app/FFmpeg ;\
    ./configure \
        --enable-nonfree \
        --enable-gpl \
        --enable-libx264 \
        --enable-nvenc \
        --enable-ffnvcodec \
        --enable-cuda-llvm ;\
    make -j"$(nproc)" ;\
    make install ;\
    ldconfig

COPY run.sh /go-vod.sh

EXPOSE 47788

ENTRYPOINT ["/go-vod.sh"]
`

**Comment by pulsejet** [comment]
I don't have NVENC to test, but the image readme does say that it is supported https://hub.docker.com/r/linuxserver/ffmpeg

**Comment by revr3nd** [comment]
Doing a quick compare of build options. It looks like the lscr build does not include the CUDA nor NPP scalers, which is why it doesn't work.

the lscr ffmpeg image uses the following build options:
```
--disable-debug
--disable-doc
--disable-ffplay
--enable-cuvid
--enable-ffprobe
--enable-gpl
--enable-libaom
--enable-libass
--enable-libfdk_aac
--enable-libfreetype
--enable-libkvazaar
--enable-libmp3lame
--enable-libopencore-amrnb
--enable-libopencore-amrwb
--enable-libopenjpeg
--enable-libopus
--enable-libsvtav1
--enable-libtheora
--enable-libv4l2
--enable-libvidstab
--enable-libvmaf
--enable-libvorbis
--enable-libvpl
--enable-libvpx
--enable-libwebp
--enable-libx264
--enable-libx265
--enable-libxml2
--enable-libxvid
--enable-nonfree
--enable-nvdec
--enable-nvenc
--enable-opencl
--enable-openssl
--enable-stripping
--enable-vaapi
--enable-vdpau
--enable-version3
```

This is quite a bit more than what go-vod needs, but more critically go-vod requires either --enable-cuda-llvm or --enable-libnpp to work with the CUDA or NPP scalers. This is why it still requires custom compiling.

Recommendation would be to either pivot away from a hardware scalers when using nvenc and just use the software scale filter, or stick with the custom compile path.

**Comment by pulsejet** [comment]
Okay! I see two paths ahead:
1. We need to find out if there's a reason why the ffmpeg isn't built with either scaler. Does this have to do with licencing? In that case, is there another image which _does_ ship with these / can we build and ship one legally?
1. (less ideal) If we can't, this Dockerfile should be put back to the repo and update the docs with instructions. This'll be more effort for those using NVENC, unfortunately.

**Comment by pulsejet** [comment]
> Recommendation would be to either pivot away from a hardware scalers when using nvenc and just use the software scale filter, or stick with the custom compile path.

I don't want to compromise on performance in any way unless there are more reasons to do this. The cost of set up is less important than user experience.

**Comment by pulsejet** [comment]
Maybe there's another way
https://docs.nvidia.com/video-technologies/video-codec-sdk/12.0/ffmpeg-with-nvidia-gpu/index.html#hwaccel-transcode-with-scaling

**Comment by revr3nd** [comment]
I can help test this, but I'm not sure the complete configuration string to feed ffmpeg.

It looks like we need to add two parameters here and remove some others, but the example to feed it is rather complex
Remove: ``` scale_cuda=force_original_aspect_ratio=decrease:passthrough=0:w={{width}}:h={{height}} ```
Add: ``` -hwaccel_output_format cuda -resize 1280x720 ```

I've attempted to do with with an example stream, but getting an error.
Original command (from go-vod debug): ``` /usr/local/bin/ffmpeg -loglevel warning -hwaccel cuda -i /config/PXL_20231028_170147025.mp4 -copyts -fflags +genpts -vf "format=nv12|cuda,hwupload,scale_cuda=force_original_aspect_ratio=decrease:passthrough=0:w=854:h=854" -map "0:v:0" "-c:v" h264_nvenc -preset p6 -tune ll -rc vbr -rc-lookahead 30 -cq 24 -temporal-aq 1 -map "0:a:0?" "-c:a" aac -ac 1 -start_number 0 -avoid_negative_ts disabled -f hls -hls_flags split_by_time -hls_time 3 -hls_segment_type mpegts -hls_segment_filename /tmp/go-vod/ugq9xqdhkc00-2219585827/480p-%06d.ts -g 177 -keyint_min 177 - ```
Tested command: ``` docker run --rm -it -v $(pwd):/config linuxserver/ffmpeg ffmpeg -loglevel warning -hwaccel cuda -i /config/PXL_20231028_170147025.mp4 -copyts -fflags +genpts -vf "format=nv12|cuda,hwupload," -map "0:v:0" "-c:v" h264_nvenc -preset p6 -tune ll -rc vbr -rc-lookahead 30 -cq 24 -temporal-aq 1 -map "0:a:0?" "-c:a" aac -ac 1 -start_number 0 -avoid_negative_ts disabled -f hls -hls_flags split_by_time -hls_time 3 -hls_segment_type mpegts -hls_segment_filename /tmp/go-vod/ugq9xqdhkc00-2219585827/480p-%06d.ts -g 177 -keyint_min 177 -hwaccel_output_format cuda -resize 1280x720 - ```

I'm getting the below error:
```
[AVFormatContext @ 0x55629ee06180] Unable to choose an output format for 'ffmpeg'; use a standard extension for the filename or specify the format manually.
[out#0 @ 0x55629edbf5c0] Error initializing the muxer for ffmpeg: Invalid argument
Error opening output file ffmpeg.
Error opening output files: Invalid argument
```

**Comment by pulsejet** [comment]
I think you don't need the ffmpeg at the start of the command (right after `linuxserver/ffmpeg`)

1. Also I don't think the filters are needed at all in this case
2. you could just try encoding to mp4 for the test
3. The resize is an input command

Maybe this:

```
docker run --rm -it -v $(pwd):/config linuxserver/ffmpeg -loglevel warning -hwaccel cuda -hwaccel_output_format cuda -resize 1280x720 -i /config/PXL_20231028_170147025.mp4 -copyts -fflags +genpts -map "0:v:0" "-c:v" h264_nvenc -preset p6 -tune ll -rc vbr -rc-lookahead 30 -cq 24 -temporal-aq 1 -map "0:a:0?" "-c:a" aac -ac 1 -g 177 -keyint_min 177 out.mp4
```

**Comment by revr3nd** [comment]
Thank you, we have progress! Had to revert back to ffmpeg 5.1.2 as the latest requires newer drivers.

New command: ``` docker run --rm -it -v $(pwd):/config --runtime=nvidia linuxserver/ffmpeg:5.1.2 -loglevel warning -hwaccel cuda -hwaccel_output_format cuda -resize 1280x720 -i /config/PXL_20231028_170147025.mp4 -copyts -fflags +genpts -map "0:v:0" "-c:v" h264_nvenc -preset p6 -tune ll -rc vbr -rc-lookahead 30 -cq 24 -temporal-aq 1 -map "0:a:0?" "-c:a" aac -ac 1 -g 177 -keyint_min 177 /config/out.mp4 ```

Output:
```
Codec AVOption tune (The metric that the encoder tunes for. Automatically chosen by the encoder by default) specified for output file #0 (/config/out.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
[h264_nvenc @ 0x55fa5e4ac740] [Eval @ 0x7ffc71559da0] Undefined constant or missing '(' in 'p6'
[h264_nvenc @ 0x55fa5e4ac740] Unable to parse option value "p6"
[h264_nvenc @ 0x55fa5e4ac740] Error setting option preset to value p6.
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```

**Comment by pulsejet** [comment]
Okay no presets. Let's remove tune too.

```
docker run --rm -it -v $(pwd):/config --runtime=nvidia linuxserver/ffmpeg:5.1.2 -loglevel warning -hwaccel cuda -hwaccel_output_format cuda -resize 1280x720 -i /config/PXL_20231028_170147025.mp4 -copyts -fflags +genpts -map "0:v:0" "-c:v" h264_nvenc -rc vbr -rc-lookahead 30 -cq 24 -temporal-aq 1 -map "0:a:0?" "-c:a" aac -ac 1 -g 177 -keyint_min 177 /config/out.mp4
```

**Comment by revr3nd** [comment]
Process starts up, and I get several thousands lines with errors:
```
[h264 @ 0x563fae29d000] No decoder surfaces left
[h264 @ 0x563fae36c280] No decoder surfaces left
[h264 @ 0x563fae43b500] No decoder surfaces left
[h264 @ 0x563fadd95f40] No decoder surfaces left
[h264 @ 0x563fade91340] No decoder surfaces left
[h264 @ 0x563fadf60600] No decoder surfaces left
[h264 @ 0x563fae02f880] No decoder surfaces left
[h264 @ 0x563fae0feb00] No decoder surfaces left
Error while decoding stream #0:2: Invalid data found when processing input
[h264 @ 0x563fae1cdd80] No decoder surfaces left
Error while decoding stream #0:2: Invalid data found when processing input
[h264 @ 0x563fae29d000] No decoder surfaces left
Error while decoding stream #0:2: Invalid data found when processing input
[h264 @ 0x563fae36c280] No decoder surfaces left
Error while decoding stream #0:2: Invalid data found when processing input
[h264 @ 0x563fae43b500] No decoder surfaces left
Error while decoding stream #0:2: Invalid data found when processing input
[h264 @ 0x563fadd95f40] No decoder surfaces left
Error while decoding stream #0:2: Invalid data found when processing input
[h264 @ 0x563fade91340] No decoder surfaces left
Error while decoding stream #0:2: Invalid data found when processing input
[h264 @ 0x563fadf60600] No decoder surfaces left
Error while decoding stream #0:2: Invalid data found when processing input
[h264 @ 0x563fae02f880] No decoder surfaces left
Error while decoding stream #0:2: Invalid data found when processing input
[h264 @ 0x563fae0feb00] No decoder surfaces left
Error while decoding stream #0:2: Invalid data found when processing input
[h264 @ 0x563fae1cdd80] No decoder surfaces left
Error while decoding stream #0:2: Invalid data found when processing input
[h264 @ 0x563fae29d000] No decoder surfaces left
Error while decoding stream #0:2: Invalid data found when processing input
[h264 @ 0x563fae36c280] No decoder surfaces left
Error while decoding stream #0:2: Invalid data found when processing input
.... repeats on
```

**Comment by pulsejet** [comment]
Does it generate the output file at all? This _might_ be fine, seems like an input issue

**Comment by revr3nd** [comment]
```
ls -lh
total 434M
-rw-r--r-- 1 root root 1.7M Nov 18 09:40 out.mp4
-rw-r--r-- 1 root root 432M Nov 18 09:15 PXL_20231028_170147025.mp4
```
Downloading the file it looks like it's only a few frames of video at the very start (less than a second), then video freezes but audio continues to play out the rest of the video.

**Comment by pulsejet** [comment]
Are the first few frames of the video resized at all?

Another attempt:

```
docker run --rm -it -v $(pwd):/config --runtime=nvidia linuxserver/ffmpeg:5.1.2 -loglevel warning -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 8 -resize 1280x720 -i /config/PXL_20231028_170147025.mp4 -copyts -fflags +genpts -map "0:v:0" "-c:v" h264_nvenc -rc vbr -rc-lookahead 30 -cq 24 -temporal-aq 1 -map "0:a:0?" "-c:a" aac -ac 1 -g 177 -keyint_min 177 /config/out.mp4
```

**Comment by revr3nd** [comment]
Got some new warnings at the start, but video is still 1920x1080 resolution in the out.ts file

```
-vsync is deprecated. Use -fps_mode
Passing a number to -vsync is deprecated, use a string argument as described in the manual.
File '/config/out.mp4' already exists. Overwrite? [y/N] y
[h264 @ 0x5609e20be4c0] No decoder surfaces left
[h264 @ 0x5609e218d740] No decoder surfaces left
[h264 @ 0x5609e225c9c0] No decoder surfaces left
[h264 @ 0x5609e232bc40] No decoder surfaces left
[h264 @ 0x5609e1c86680] No decoder surfaces left
[h264 @ 0x5609e1d81a80] No decoder surfaces left
[h264 @ 0x5609e1e50d40] No decoder surfaces left
[h264 @ 0x5609e1f1ffc0] No decoder surfaces left
```

New output file is slightly larger, but viewing it looks the exact same as before. Freezes at the same frame
```
ls -lh
total 434M
-rw-r--r-- 1 root root 2.0M Nov 18 09:47 out.mp4
-rw-r--r-- 1 root root 432M Nov 18 09:15 PXL_20231028_170147025.mp4
```

![image](https://github.com/pulsejet/memories/assets/42450691/163658e0-3fe1-47e6-a699-568343f7b0ae)

**Comment by pulsejet** [comment]
Hmm :(

I guess the only thing to get is increase `extra_hw_frames` or newer drivers / ffmpeg. I'm surprised this doesn't just work given it's in nvidia's docs

**Comment by pulsejet** [comment]
Also try changing hwaccel_output_format to auto

**Comment by pulsejet** [comment]
Apparently this worked for someone ...

```
docker run --rm -it -v $(pwd):/config --runtime=nvidia linuxserver/ffmpeg:5.1.2 -loglevel warning -resize 1280x720 -i /config/PXL_20231028_170147025.mp4 -copyts -fflags +genpts -map "0:v:0" "-c:v" h264_nvenc -rc vbr -rc-lookahead 30 -cq 24 -temporal-aq 1 -map "0:a:0?" "-c:a" aac -ac 1 -g 177 -keyint_min 177 /config/out.mp4
```

**Comment by revr3nd** [comment]
Updating hwaccel_output_format to auto results in error: Unrecognised hwaccel output format: auto

When removing the hwaccel_output_format option all together, it does successfully transcode, but is still in 1920x1080 resolution
``` docker run --rm -it -v $(pwd):/config --runtime=nvidia linuxserver/ffmpeg:5.1.2 -loglevel warning -hwaccel cuda -extra_hw_frames 8 -resize 1280x720 -i /config/PXL_20231021_235146488.TS.mp4 -copyts -fflags +genpts -map "0:v:0" "-c:v" h264_nvenc -rc vbr -rc-lookahead 30 -cq 24 -temporal-aq 1 -map "0:a:0?" "-c:a" aac -ac 1 -g 177 -keyint_min 177 /config/out.mp4 ```

When keeping the hwaccel_output_format, and setting output bitrate to 5M, I still get the decoder errors and video stops after the first several frames
``` docker run --rm -it -v $(pwd):/config --runtime=nvidia linuxserver/ffmpeg:5.1.2 -loglevel warning -hwaccel cuda -hwaccel_output_format cuda -extra_hw_frames 8 -resize 1280x720 -i /config/PXL_20231021_235146488.TS.mp4 -copyts -fflags +genpts -map "0:v:0" "-c:v" h264_nvenc -rc vbr -rc-lookahead 30 -cq 24 -temporal-aq 1 -map "0:a:0?" "-c:a" aac -ac 1 -g 177 -keyint_min 177 -b:v 5M /config/out.mp4 ```


When removing hwaccel_output_format, and setting output bitrate to 5M, the job completes without error and is complete, but still 1920x1080 resolution
``` docker run --rm -it -v $(pwd):/config --runtime=nvidia linuxserver/ffmpeg:5.1.2 -loglevel warning -hwaccel cuda -extra_hw_frames 8 -resize 1280x720 -i /config/PXL_20231021_235146488.TS.mp4 -copyts -fflags +genpts -map "0:v:0" "-c:v" h264_nvenc -rc vbr -rc-lookahead 30 -cq 24 -temporal-aq 1 -map "0:a:0?" "-c:a" aac -ac 1 -g 177 -keyint_min 177 -b:v 5M /config/out.mp4 ```

I see more the logic going on here now and will start tryign to play with options to see what works. I am just a bit lost on all of these other parameters being fed for the encoder

**Comment by pulsejet** [comment]
Okay, thanks for the efforts!

So specifying the format doesn't work, someone else mentioned this in a reddit thread too.

> I am just a bit lost on all of these other parameters being fed for the encoder

You can get rid of them. If we can get the simplest command to resize a video without the scalers, then that can be built upon

**Comment by revr3nd** [comment]
Broken down testing to the simplest possible ``` docker run --rm -it -v $(pwd):/config --runtime=nvidia linuxserver/ffmpeg:5.1.2 -vsync 0 -hwaccel cuda -resize 1280x720 -i /config/PXL_20231021_235146488.TS.mp4 -c:a copy -c:v h264_nvenc -b:v 4M /config/out.mp4 ```

Still retains full resolution. So I'm wondering if that function is broken due to compile options used.

I also attempted to use the jellyfin version, but it errors out entirely when attempting to use the cuda hwaccel due to failing to load libcuda.so.1

**Comment by pulsejet** [comment]
> Still retains full resolution.

Argh NVIDIA.

> due to failing to load libcuda.so.1

Did you pass the nvidia runtime in? I thought this lib comes from the runtime

**Comment by revr3nd** [comment]
Yeah, turns out the jellyfin/ffmpeg is 4 years old. Have to load the full jellyfin container. Still messing with it

**Comment by revr3nd** [comment]
Ok, I rebuilt go-vod using jellyfin as the base image, and it works right out of the box.

The dockerfile just needs to set up symlinks to the ffmpeg binaries

```
FROM jellyfin/jellyfin:latest

COPY run.sh /go-vod.sh

RUN set -ex ;\
    ln -s /usr/lib/jellyfin-ffmpeg/ffmpeg /usr/local/bin/ffmpeg ;\
    ln -s /usr/lib/jellyfin-ffmpeg/ffprobe /usr/local/bin/ffprobe

EXPOSE 47788

ENTRYPOINT ["/go-vod.sh"]
```

**Comment by pulsejet** [comment]
> and it works right out of the box

Great news!!

do you mean with the `scale_cuda` / `scale_npp` or `resize`?

**Comment by revr3nd** [comment]
Jellyfin includes scale_cuda and not scale_npp (from articles I've seen is that npp is depreciated)

Here's the settings used for me that work best:
``` 2023/11/18 19:07:01 &{Version:0.2.3 Configured:true VersionMonitor:true Bind::47788 FFmpeg:/usr/local/bin/ffmpeg FFprobe:/usr/local/bin/ffprobe TempDir:/tmp/go-vod ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 QF:24 VAAPI:false VAAPILowPower:false NVENC:true NVENCTemporalAQ:true NVENCScale:cuda UseTranspose:false UseGopSize:true} ```

Here's a ffmpeg command issued as part of transcoding with scale down:
``` 2023/11/18 19:16:35 t6f6r5c1uc00-480p: /usr/local/bin/ffmpeg -loglevel warning -hwaccel cuda -i /mnt/ncdata/admin/files/Photos/Camera/2023/09/PXL_20230909_175822904.mp4 -copyts -fflags +genpts -vf "format=nv12|cuda,hwupload,scale_cuda=force_original_aspect_ratio=decrease:passthrough=0:w=854:h=854" -map "0:v:0" "-c:v" h264_nvenc -preset p6 -tune ll -rc vbr -rc-lookahead 30 -cq 24 -temporal-aq 1 -map "0:a:0?" "-c:a" aac -ac 1 -start_number 0 -avoid_negative_ts disabled -f hls -hls_flags split_by_time -hls_time 3 -hls_segment_type mpegts -hls_segment_filename /tmp/go-vod/t6f6r5c1uc00-956113781/480p-%06d.ts -g 177 -keyint_min 177 - ```

**Comment by pulsejet** [comment]
Okay, great. I'll attempt to build a lean image for this ffmpeg that still works.

> Jellyfin includes scale_cuda and not scale_npp (from articles I've seen is that npp is depreciated)

`npp` is actually the newer / more powerful one from what I understand, but it's got license incompatibilties. Let's make `scale_cuda` the default instead of npp and remove the "recommended" tag

**Comment by pulsejet** [comment]
`scale_cuda` is default now

**Comment by pulsejet** [comment]
@revr3nd can you see if this build works? This does work on VA-API on my side, so this should fix everything if it works with scale_cuda (default now)

Of course we'll probably need a separate build for arm now since that doesn't use jellyfin-ffmpeg I think.

```Dockerfile
FROM jellyfin/jellyfin:latest as base

RUN rm -rf /jellyfin && \
    ln -s /usr/lib/jellyfin-ffmpeg/ffmpeg /usr/local/bin/ffmpeg && \
    ln -s /usr/lib/jellyfin-ffmpeg/ffprobe /usr/local/bin/ffprobe

FROM scratch

COPY --from=base / /
COPY run.sh /go-vod.sh

EXPOSE 47788
ENTRYPOINT ["/go-vod.sh"]
```

**Comment by revr3nd** [comment]
Build runs without issue.

When attempting to transcode, get an error 'Cannot load libcuda.so.1'. I do not get this error when running on the build on top of jellyfin.

```
2023/11/18 20:00:09 pw9g3oqqysl0-480p: /usr/local/bin/ffmpeg -loglevel warning -hwaccel cuda -i /mnt/ncdata/admin/files/Photos/Camera/2023/10/PXL_20231028_170147025.mp4 -copyts -fflags +genpts -vf "format=nv12|cuda,hwupload,scale_cuda=force_original_aspect_ratio=decrease:passthrough=0:w=854:h=854" -map "0:v:0" "-c:v" h264_nvenc -preset p6 -tune ll -rc vbr -rc-lookahead 30 -cq 24 -temporal-aq 1 -map "0:a:0?" "-c:a" aac -ac 1 -start_number 0 -avoid_negative_ts disabled -f hls -hls_flags split_by_time -hls_time 3 -hls_segment_type mpegts -hls_segment_filename /tmp/go-vod/pw9g3oqqysl0-2219585827/480p-%06d.ts -g 177 -keyint_min 177 -
2023/11/18 20:00:09 ffmpeg-error: [AVHWDeviceContext @ 0x5598e53a9680] Cannot load libcuda.so.1
2023/11/18 20:00:09 ffmpeg-error: [AVHWDeviceContext @ 0x5598e53a9680] Could not dynamically load CUDA
2023/11/18 20:00:09 ffmpeg-error: Device creation failed: -1.
2023/11/18 20:00:09 ffmpeg-error: [h264 @ 0x5598e53ad640] No device available for decoder: device type cuda needed for codec h264.
2023/11/18 20:00:09 ffmpeg-error: Device setup failed for decoder on input stream #0:2 : Operation not permitted
2023/11/18 20:00:09 pw9g3oqqysl0-480p: ffmpeg exited with status: 1
2023/11/18 20:00:09 pw9g3oqqysl0-720p: stopping stream
```

Doing a search, it doesn't look like the new build includes the libcuda files. On jellyfin, these are found in /usr/lib, but I do not see the same on the slim build of go-vod.

```
docker exec -it jellyfin find /usr/lib | grep libcuda
/usr/lib/x86_64-linux-gnu/libcudadebugger.so.525.125.06
/usr/lib/x86_64-linux-gnu/libcuda.so.525.125.06
/usr/lib/x86_64-linux-gnu/libcuda.so
/usr/lib/x86_64-linux-gnu/libcuda.so.1
/usr/lib/x86_64-linux-gnu/libcudadebugger.so.1
```

```
docker exec -it nextcloud-go-vod-1 find /usr/lib/ | grep libcuda
```

**Comment by pulsejet** [comment]
I'm guessing this has to do with env variables. Will keep digging, thanks for the help! (might need bit more again)

**Comment by pulsejet** [comment]
@revr3nd can you try one more time with this? I realised we're missing the driver cap env variable, which will prevent anything from the runtime being available.

```Dockerfile
FROM jellyfin/jellyfin:latest as base

RUN rm -rf /jellyfin && \
    ln -s /usr/lib/jellyfin-ffmpeg/ffmpeg /usr/local/bin/ffmpeg && \
    ln -s /usr/lib/jellyfin-ffmpeg/ffprobe /usr/local/bin/ffprobe

FROM scratch

ENV NVIDIA_DRIVER_CAPABILITIES="compute,video,utility"

COPY --from=base / /
COPY run.sh /go-vod.sh

EXPOSE 47788
ENTRYPOINT ["/go-vod.sh"]
```

**Comment by revr3nd** [comment]
Thsi oen does appear to work, but I also had to update my docker compose config for go-vod to present the GPU via the newer deploy format. Was still getting the cuds error when trying to just use the runtime parameter. Below is my reference compose for go-vod:

```
  go-vod:
    image: go-vod:slim-0.2.3
    restart: unless-stopped
    depends_on:
      - web
    environment:
      - NEXTCLOUD_HOST=http://web:${APACHE_PORT}
      - NEXTCLOUD_ALLOW_INSECURE=1
    volumes:
      - ${NC_DATA_DIR}:/mnt/ncdata:ro
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [video]
              count: all
              driver: nvidia
```

**Comment by pulsejet** [comment]
Ok, great! Would we need just `capabilities: [video]` or potentially `capabilities: [compute,video,utility]`? That seems to be what jellyfin uses

**Comment by pulsejet** [comment]
Hold on, maybe it's because you haven't defined `NVIDIA_VISIBLE_DEVICES=all` in the environment variables? See http://127.0.0.1:8000/hw-transcoding/#external-transcoder

**Comment by pulsejet** [comment]
FYI, the go-vod image is based on Jellyfin's ffmpeg now. `NVIDIA_VISIBLE_DEVICES=all` must be specified as an environment variable.

**Comment by pulsejet** [comment]
This is old
