### ISSUE TITLE
Error Installing Memories App: Tablespace already exists

### ISSUE THREAD

**Issue by Mabashi8** [pulsejet/memories#583]
I am receiving the following error when trying to download and enable the memories app:
An error occurred during the request. Unable to proceed.
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1005 Can't create table `NextCloud`.`oc_memories` (errno: 184 "Tablespace already exists")

For some background I had some issues on my unraid server and had to restore app data from a few weeks ago which caused issues with the memories app so I tried to remove all traces of the memories app from nextcloud and the database.

**Comment by vitis586** [comment]
Did you try dropping the tables? You can find the details on this in the FAQ at the very bottom. https://github.com/pulsejet/memories/wiki/FAQ

**Comment by Mabashi8** [comment]
I have dropped all those tables and entries already. It seems like the app cannot recreate them when I try to reinstall memories.

**Comment by pulsejet** [comment]
The tablespace error indicates something wasn't dropped from the database ...

**Comment by Mabashi8** [comment]
I ran the recommended SQL commands and am still getting the same error when trying to reinstall the app. There were no records to delete since I had already removed them earlier.

![image](https://user-images.githubusercontent.com/94807272/232952422-e05a5b14-437a-4443-be3c-25ae68ebdf15.png)

![image](https://user-images.githubusercontent.com/94807272/232952516-177eec65-33e0-4c24-8140-dcb3594b9a57.png)

**Comment by Mabashi8** [comment]
The tables and entries have all been deleted. I was using adminer and was already in the nextcloud DB when I ran those commands.

**Comment by pulsejet** [comment]
The error indicates there's some trace of the tables somewhere in some orphan form. Not sure how to proceed here...
https://stackoverflow.com/questions/15694168/error-tablespace-for-table-xxx-exists-please-discard-the-tablespace-before-imp

**Comment by Mabashi8** [comment]
Thanks, that helped me resolve the issue by deleting the remaining .ibd files!

**Comment by pulsejet** [comment]
Very weird really. You probably hit a bug in MySQL haha.
