### ISSUE TITLE
Video Transcoding not working Docker - VOD server "Unrecognized option 'show_entries'."

### ISSUE THREAD

**Issue by Cebrain** [pulsejet/memories#585]
**Describe the bug**
I tried to get the video transcoding working on the new 5.0.3 memories version.
It was working fine on last release 4.* 
I use a custom nextcloud docker image with ffmpeg included.

I also tried the setup with an external VOD Docker image and with that it was working fine.
Still want to use the internal ffmpeg for the moment ;)

**To Reproduce**
Error on every video

**Platform (please complete the following information):**

- OS: Docker
- Browser Firefox
- Version 5.0.3

**Additional context**
config.php:

`  
   ...
  'ffmpeg' => '/usr/bin/ffmpeg',
  'preview_max_x' => 1440,
  'preview_max_y' => 2560,
  'preview_max_memory' => 4096,
  'preview_max_filesize_image' => 256,
  'preview_imaginary_url' => 'http://nextcloud-imaginary:9000',
  'memories.exiftool' => '/var/www/html/custom_apps/memories/lib/../exiftool-bin/exiftool-amd64-glibc',
  'memories.gis_type' => 1,
  'memories.vod.path' => '/var/www/html/custom_apps/memories/exiftool-bin/go-vod-amd64',
  'memories.vod.tempdir' => '/tmp/memories',
  'memories.vod.ffmpeg' => '/usr/bin/ffmpeg',
  'memories.vod.ffprobe' => '/usr/bin/ffmpeg',
  'memories.vod.disable' => false,
);

`

Log:

```
&{Configured:true Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffmpeg TempDir:/tmp/memories/occpy53sbnk7 ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
&{Configured:true Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffmpeg TempDir:/tmp/memories/occpy53sbnk7 ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/18 16:04:55 Starting VOD server
2023/04/18 16:04:56 Unrecognized option 'show_entries'.
Error splitting the argument list: Option not found

2023/04/18 16:04:56 Error creating manager exit status 1
2023/04/18 16:04:56 Unrecognized option 'show_entries'.
Error splitting the argument list: Option not found

2023/04/18 16:04:56 Error creating manager exit status 1
```

**Comment by Cebrain** [comment]
The settings above are the default settings with disabled external transcoder.
As ununderstand the paths above are for the local instance.
When i enabled the external VOD setup i only edited the ip and it was working

**Comment by pulsejet** [comment]
Ummm your ffprobe config is pointing to ffmpeg

**Comment by Cebrain** [comment]
> Ummm your ffprobe config is pointing to ffmpeg

Lol you are right, feeling really stupid now.
Still it is not working for me at the moment, but log is new.

New Log:
2023/04/18 21:58:32 Starting VOD server
2023/04/18 21:58:42 Error starting serverlisten tcp: lookup go-vod on 127.0.0.11:53: read udp 127.0.0.1:59843->127.0.0.11:53: i/o timeout
&{Configured:true Bind:go-vod:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/memories/occpy53sbnk7 ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
&{Configured:true Bind:go-vod:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/memories/occpy53sbnk7 ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/18 21:59:18 Starting VOD server

```

  'ffmpeg' => '/usr/bin/ffmpeg',
  'preview_max_x' => 1440,
  'preview_max_y' => 2560,
  'preview_max_memory' => 4096,
  'preview_max_filesize_image' => 256,
  'preview_imaginary_url' => 'http://nextcloud-imaginary:9000',
  'memories.exiftool' => '/var/www/html/custom_apps/memories/lib/../exiftool-bin/exiftool-amd64-glibc',
  'memories.gis_type' => 1,
  'memories.vod.path' => '/var/www/html/custom_apps/memories/exiftool-bin/go-vod-amd64',
  'memories.vod.tempdir' => '/tmp/memories',
  'memories.vod.ffmpeg' => '/usr/bin/ffmpeg',
  'memories.vod.ffprobe' => '/usr/bin/ffprobe',
  'memories.vod.bind' => 'go-vod:47788',
  'memories.vod.connect' => 'go-vod:47788',
  'memories.vod.disable' => false,
);

```

**Comment by Cebrain** [comment]
Got it fixed!!!

I needed to delete the part
  'memories.vod.bind' => 'go-vod:47788',
  'memories.vod.connect' => 'go-vod:47788',

I think it was still trying to get to the external resolver, disable the setting wasnt enough.
Is this possible?

Working PHP Config:
`  'ffmpeg' => '/usr/bin/ffmpeg',
  'preview_max_x' => 1440,
  'preview_max_y' => 2560,
  'preview_max_memory' => 4096,
  'preview_max_filesize_image' => 256,
  'preview_imaginary_url' => 'http://nextcloud-imaginary:9000',
  'memories.exiftool' => '/var/www/html/custom_apps/memories/lib/../exiftool-bin/exiftool-amd64-glibc',
  'memories.gis_type' => 1,
  'memories.vod.path' => '/var/www/html/custom_apps/memories/exiftool-bin/go-vod-amd64',
  'memories.vod.tempdir' => '/tmp/memories',
  'memories.vod.ffmpeg' => '/usr/bin/ffmpeg',
  'memories.vod.ffprobe' => '/usr/bin/ffprobe',
  'memories.vod.disable' => false,
);
`

**Comment by pulsejet** [comment]
That's intentional behavior. There are other cases where you would want to change the bind/connect ports besides external transcoder, e.g. if you have multiple nextcloud instances.

**Comment by Cebrain** [comment]
Ok, could you maybe set an reset button for the settings? 
As i see it now, the ip config is now back to localhost "127.0.0.1:47788" but the setting is not in the config.php, this confused me a little bit. But i think default values are not written in the config.php

Another problem i noticed, if you change this ip part to something wrong. 
The settings instance tries to connect to the "wrong" setting. As it looks like for me, it is not possible to change any setting afterwards till you wait to the timeout. 
Maybe Solution: Create an "Test" Button to check if everything is fine and not automatically?

**Comment by WGandy** [comment]
@Cebrain > Can you clarify which features are working for you now?

**Comment by Cebrain** [comment]
> @Cebrain > Can you clarify which features are working for you now?

Sure, nothing special. 
Video Streaming & Video Transcoding on the same nextcloud/docker instance is now working fine. I dont need an external transcoder

**Comment by WGandy** [comment]
Ok, so just hardware (CPU) transcoding? 

I'm working to get either quicksync or nvenc going on my instance. I thought the go-vod was the best way to do that but it almost seems that installing an nvenc capable ffmpeg in the nextcloud container might be easier/more predictable??

btw, I discovered that my go-vod folder was not the latest (about 2 weeks old) and have since then rebuilt the nextcloud and go-vod containers but still can't seem to get transcoding working in any form.

Lastly, I want to say thanks to the Memories devs. This is a nice looking app for Nextcloud and I appreciate the work that's gone into it.

**Comment by Cebrain** [comment]
> Ok, so just hardware (CPU) transcoding?

Yep only CPU transcoding, i dont go the internal VOD route, because i dont have hardware gpu transcoding.
I think i would go the VOD route when i need to customize my nextcloud docker to much. 

Did you added all paths to the medie files in the VOD container?

**Comment by WGandy** [comment]
> Did you added all paths to the medie files in the VOD container?

Uh. Where is that? 
I just went to look at the m1k1o/go-transcode that go-vod was inspired by and it does indeed show a media-dir in the config file. But where is the config file for go-vod?

**Comment by pulsejet** [comment]
@WGandy go-vod is configured by memories dynamically, so it doesn't have a config file anymore. Just configure it from the memories admin dashboard.

**Comment by Cebrain** [comment]
> > Did you added all paths to the medie files in the VOD container?
> 
> Uh. Where is that? I just went to look at the m1k1o/go-transcode that go-vod was inspired by and it does indeed show a media-dir in the config file. But where is the config file for go-vod?

As pulsejet wrote, you need to add the exact same media path mount points in nextcloud also into the VOD container.
Normally this is the www nextcloud folder.
I needed to additionally add the external storage paths.

**Comment by Cebrain** [comment]
@pulsejet 
Do you want to keep this issue open for the feature request or should i close it?

> Ok, could you maybe set an reset button for the settings? As i see it now, the ip config is now back to localhost "127.0.0.1:47788" but the setting is not in the config.php, this confused me a little bit. But i think default values are not written in the config.php
> 
> Another problem i noticed, if you change this ip part to something wrong. The settings instance tries to connect to the "wrong" setting. As it looks like for me, it is not possible to change any setting afterwards till you wait to the timeout. Maybe Solution: Create an "Test" Button to check if everything is fine and not automatically?

**Comment by pulsejet** [comment]
This thread is confusing. Can you open a new feature req and close this (this will likely get lost).
