### ISSUE TITLE
Error "No photos to show here"

### ISSUE THREAD

**Issue by uSyzex** [pulsejet/memories#59]
Hi,

Everything worked like a charm before but now I have an error "No photos to show here" with every folder. 

I tried multiple path and none works. 
I tried to reinstall, reboot Nextcloud instance too. 

How can I provide logs ?

Regards,

**Comment by jakobroehrl** [comment]
Could you run
occ memories:index --clear

**Comment by uSyzex** [comment]
> Could you run occ memories:index --clear

It worked. 

Thank you very much!
