### ISSUE TITLE
Option to configure/disable autoplay for live photos

### ISSUE THREAD

**Issue by schlop** [pulsejet/memories#591]
**Describe the solution you'd like**
An option in config.php or the memories settings to disable the autoplay of live photos in the single image view. I hope this would be easy to implement and seems to be an extension of what's already in the code since #330.

**Describe alternatives you've considered**
Always use the slide show mode to view photos if live view is not wanted, but this is not practical for sorting through photos. The nuclear option would be to remove all .mov files from memories and convert HEICs to JPGs.

**Additional context**
It's amazing to have live photo support in memories and I do love to play the short live video for some images. However, when looking and sorting through a large number of live photos it can be a bit tiering to watch the videos all the time. This is especially true for landscape pictures where the video is often just a jittering version of the photo. It would be great if I could disable the autoplay and just view the live view of photos by clicking the button that was introduced based on #483.

Also wanted to say thank you for this amazing project. Moved my entire photo library to memories and am blown away by the design and the level of polish!

**Comment by pulsejet** [comment]
![image](https://github.com/pulsejet/memories/assets/10709794/fa97af9e-8207-4159-8bd3-b86a10ab9c2e)
