### ISSUE TITLE
404 error in nginx access.log for /apps/memories/js/memories-node_modules_nextcloud_vue_dist_Components_NcNoteCard_js.js.map

### ISSUE THREAD

**Issue by invario** [pulsejet/memories#593]
`10.0.0.10 - MYSERVERADDRESS.com [19/Apr/2023:18:02:57 -0400] "GET /apps/memories/js/memories-node_modules_nextcloud_vue_dist_Components_NcNoteCard_js.js.map?v=fce34ecd7bfa96bc891c HTTP/2.0" 404 3904 "-" "Mozilla/5.0 (Linux; Android 13; SM-S916U1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Mobile Safari/537.36" "-"rt=0.028 ut=0.028 cs=-
`

**Platform (please complete the following information):**
NC 26
Memories 5.0.4
Chrome Mobile or Desktop
nginx 1.22.0
PHP 8.1.12

Just started popping up on a recent update of Memories. Bug possibly?

Update: Just noticed I started getting these too:
```
10.0.0.11 - MYSERVERADDRESS.com [19/Apr/2023:18:11:51 -0400] "GET /apps/memories/js/memories-main.js.LICENSE.txt HTTP/2.0" 404 3904 "
-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"rt=0.027 ut=0.027
 cs=-

10.0.0.11 - MYSERVERADDRESS.com [19/Apr/2023:19:31:31 -0400] "GET /apps/memories/memories-node_modules_nextcloud_vue_dist_Components_
NcAppSettingsSection_js.js HTTP/2.0" 404 3905 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" "-"rt=0.045 ut=0.044 cs=-

```

**Comment by pulsejet** [comment]
Can you open the settings page in memories? (not the admin). If yes you can just ignore this for now.

**Comment by invario** [comment]
This? 
![image](https://user-images.githubusercontent.com/67800603/233223105-f0df5d78-d792-45ba-9b98-1bf38e3b0f76.png)


Yes.

**Comment by pulsejet** [comment]
The map generally gets requested when you open the js console. As long as nothing is broken, this is just webpack etc at work.

**Comment by invario** [comment]
Thank you!
