### ISSUE TITLE
Exec of Exif binary fails

### ISSUE THREAD

**Issue by JFingerle** [pulsejet/memories#599]
**Describe the bug**
Execution of the Exif binary fails with error message "Exec failed: No such file or directory".

_nextcloud.log:_
```
{"reqId":"pdeSKCHmzYoHyCp6Xl9Q","level":3,"time":"2023-04-22T14:50:01+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"proc_open(): Exec failed: No such file or directory at /var/www/html/custom_apps/memories/lib/Exif.php#339","userAgent":"--","version":"26.0.0.11","data":{"app":"PHP"}}
```

_Config_
```
  'memories.exiftool' => '/var/www/html/custom_apps/memories/exiftool-bin/exiftool-amd64-glibc',
  'memories.exiftool_no_local' => false,
```
- The binary set via "memories.exiftool" does exist and is executable. I can execute it without problems from within the container (using "docker exec -u www-data -it nextcloud bash" first).

_Nextcloud admin page of "memories"_
```
exiftool binary exists and is usable (12.58).

Path to packaged exiftool binary
/var/www/html/custom_apps/memories/exiftool-bin/exiftool-amd64-glibc

perl binary exists and is usable (v5.32.1). You need perl only if the packaged exiftool binary does not work for some reason.
```

**Platform (please complete the following information):**

- Browser: Chromium 111.0.5563.64
- Docker setup on x86_64 (amd64) machine running Debian 11
- Docker image "26-fpm" (a03b970d51c8). Setup via docker-compose.
- Nextcloud version 26.0.0
- Memories version 5.0.5

**Comment by pulsejet** [comment]
Do you have any issues with indexing? The admin page seems to say everything is fine.

**Comment by JFingerle** [comment]
@pulsejet Indexing seems to work fine. I can see my photos in the timeline (correctly ordered) and can also browse them using the "folders" section.

**Comment by pulsejet** [comment]
How often do you get this? Do you get it every time when you run index?

**Comment by JFingerle** [comment]
The error message appears in "nextcloud.log" exactly every 20 minutes. It does not appear if I run "occ memories:index".

**Comment by pulsejet** [comment]
Sounds like your cronjob can't use the binary for some reason. Is cron correctly setup for nextcloud? E.g. it's running with the correct user and has a /tmp directory.

**Comment by JFingerle** [comment]
That was it  :+1: :100: 

The error occured because i was using the docker image "nextcloud:fpm" for the nextcloud container but "nextcloud:fpm-alpine" for the cron container.

Originally I was using "nextcloud:fpm-alpine" for both of my "nextcloud" and "nextcloud-cron" containers. But when I setup "memories" I had to change to "nextcloud:fpm" (based on Debian) for the "nextcloud" container to enable VA-API (installation of the required packages as described in [the docs](https://github.com/pulsejet/memories/wiki/HW-Transcoding) did not work). That is why my setup had the fpm/fpm-alpine mixup.

Thank you very much!
