### ISSUE TITLE
I am seeing two of each photo in timeline

### ISSUE THREAD

**Issue by prairietree** [pulsejet/memories#600]
I installed Memories app a day or two ago. I am liking many components of it so far. However, I have one issue that might be my fault. In the time line I am seeing two of most of my files. Could that be caused by running occ memories:index twice?

I ran occ memories:index and got a bunch of errors about not being able to index because of some locks. So I ran it again. That time I got no errors. Do you think that might be why am seeing two of each in the timeline?

In the timeline the last couple of months are not duplicated and not that many photos but when I get back a few months they all seem to be duplicated.

Thanks for your help.

**Comment by pulsejet** [comment]
Try running `occ memories:index --clear`
Also check if the folders view also shows duplicates.

**Comment by pulsejet** [comment]
It's possible that your folder structure itself has some issue in the DB. Try checking if the duplicates have different fileid (the file ID is the last number in the URL when you click on the file and the viewer opens)

**Comment by prairietree** [comment]
I am running the clear option now. It looks like it is indexing it after clearing it, so I guess I will not have to rerun the index?

Do not see duplicates in the folders view.

They do have different last numbers in the url.

**Comment by prairietree** [comment]
My bad. There might really be duplicates. I will have to look at it later because I cannot see what folder it is finding the pictures in. Sorry.

**Comment by beckenc** [comment]
> I am running the clear option now. It looks like it is indexing it after clearing it, so I guess I will not have to rerun the index?
> 
> Do not see duplicates in the folders view.
> 
> They do have different last numbers in the url.

Similar Problem here. I see all People filtered Photos (recognize) twice. Different File IDs in the URL (referring to the same folder/file).

I've installed memories and recognize from scratch (dropping DB Tables included) bit without any success...

Snay Idea of how to fix this at my installation?

**Comment by pulsejet** [comment]
> Different File IDs in the URL (referring to the same folder/file).

There's your clue. You can try to figure out which files have duplicate fileids (check the `oc_filecache` table), and why. If there's no apparent reason the last resort would be to rebuild the filecache from scratch but this is a destructive action (you'd lose tags etc)
