### ISSUE TITLE
Admin settings: Request failed with status code 500

### ISSUE THREAD

**Issue by invario** [pulsejet/memories#601]
`{"message":"Request failed with status code 500","name":"AxiosError","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"FormData":null},"headers":{"Accept":"application/json, text/plain, */*","requesttoken":"Vysy73y7Ngo32Yyjey/DylHY0mwPyn3cMPHmYKudAjA=:FkVAvAnMdUF5oM2aMGGKvzbsvClF+UytCZCKMID4KUE="},"method":"get","url":"/apps/memories/api/system-status"},"code":"ERR_BAD_RESPONSE","status":500}`

The above pops up on the top when opening the admin settings for Memories.

![Screenshot_20230422_222515_Chrome](https://user-images.githubusercontent.com/67800603/233816296-e62daa9e-1135-43c3-be97-c54aabcc6ee7.jpg)

Screenshot of error above. I haven't checked on a desktop browser yet. This is Android Chrome.

nginx error log as follows:
`{"reqId":"UijExBOm7n0OefqgSJXn","level":3,"time":"2023-04-22T22:27:42-04:00","remoteAddr":"192.168.0.74","user":"USERNAME","app":"index","method":"GET","url":"/apps/memories/api/system-status","message":"Path cannot be empty in file '/usr/local/www/nextcloud/apps/memories/lib/Service/BinExt.php' line 35","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36","version":"26.0.1.1","exception":{"Exception":"Exception","Message":"Path cannot be empty in file '/usr/local/www/nextcloud/apps/memories/lib/Service/BinExt.php' line 35","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/local/www/nextcloud/lib/base.php","line":1056,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/local/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"ValueError","Message":"Path cannot be empty","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/apps/memories/lib/Service/BinExt.php","line":35,"function":"copy"},{"file":"/usr/local/www/nextcloud/apps/memories/lib/Service/BinExt.php","line":97,"function":"getTempBin","class":"OCA\\Memories\\Service\\BinExt","type":"::"},{"file":"/usr/local/www/nextcloud/apps/memories/lib/Controller/OtherController.php","line":125,"function":"getExiftoolPBin","class":"OCA\\Memories\\Service\\BinExt","type":"::"},{"file":"/usr/local/www/nextcloud/apps/memories/lib/UtilController.php","line":20,"function":"OCA\\Memories\\Controller\\{closure}","class":"OCA\\Memories\\Controller\\OtherController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/usr/local/www/nextcloud/apps/memories/lib/Controller/OtherController.php","line":193,"function":"guardEx","class":"OCA\\Memories\\Util","type":"::"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getSystemStatus","class":"OCA\\Memories\\Controller\\OtherController","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/local/www/nextcloud/lib/base.php","line":1056,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/local/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/local/www/nextcloud/apps/memories/lib/Service/BinExt.php","Line":35},"CustomMessage":"--"}}`

**Platform (please complete the following information):**
NC 26.0.1 (just updated)
Memories 5.0.5 (just updated)
Chrome Mobile or Desktop
nginx 1.22.0
PHP 8.1.12

Troubleshooting steps taken:
Removed all Memories related entries from config.php and removed (uninstalled) Memories app from NC and reinstalled it.

**Comment by invario** [comment]
Adding the following lines into config.php seems to have resolved the problem and if I put the path of my system's exiftool, it gives an error about it being the incorrect version so I have to enable the setting to use Perl:

```
  'memories.exiftool' => '/usr/local/www/nextcloud/apps/memories/exiftool-bin/exiftool-amd64-glibc',
  'memories.exiftool_no_local' => true,

```

![image](https://user-images.githubusercontent.com/67800603/234083839-d552073a-a018-4ef7-a173-2e2df10b7d82.png)
Regardless, for whatever reason, the "memories.exiftool" path isn't detecting properly and is defaulting to a blank.  Is "memories.exiftool" a required line in the NC config.php? I searched documentation and didn't see any mention. I also would've thought a remove/reinstall of the app would've created all the necessary config.php entries.

Thanks for your work!!

**Comment by pulsejet** [comment]
Btw what kind of platform is this? There are bundled binaries for ARM and x86_64 for both glibc and musl, so you must be running neither of these?

**Comment by pulsejet** [comment]
Ahh BSD. That explains it.
