### ISSUE TITLE
Precise coordinates for location

### ISSUE THREAD

**Issue by vitis586** [pulsejet/memories#604]
**Is your feature request related to a problem? Please describe.**
I recently found out that Android is implicitly not attaching location to EXIF when uploaded to Nextcloud so I was fixing this with exiftool. I had to add some locations manualy and even though I had precise location from Google Photos, the location ended up somewhere else. I realised that when you put in a precise location, Nominatim suggests you the closest POI. Some pictures and videos from national parks end up quite far from it's orginal location.

For example, I have a picture that was taken at -1.401840,34.972100. Nominatim returns road E176 which has a center at -1.3556765,34.9518871 and that is what will be used as a location for that photo. 

Link to Nominatim result: https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=36837958&class=highway

**Describe the solution you'd like**
Can there be an option to use the exact coordinates that I put in?

I imagine that I put in the coordinates into the field and it offers me to use them directly or use point from Nominatim. 

Most of the photos we take are not exactly on some point that is represented in Nominatim database but they get geocoded well enough. For example to street/city/country. This would be the case with the precise coordinates. 

**Describe alternatives you've considered**

**Additional context**

**Comment by florianwgnr** [comment]
Maybe an integration of https://github.com/gino0631/nextcloud-metadata might be worth to look at. When opening a photo within Nextcloud files, the "Metadata"-Tab is displayed in the sidebar:
![grafik](https://user-images.githubusercontent.com/39341393/233838167-2b48be04-6434-452d-bdde-055b4b46c7e5.png)

When using memories, metadata is not displayed:
![grafik](https://user-images.githubusercontent.com/39341393/233838191-1ecf6ce0-843c-446b-a7bf-66e1c293923e.png)

Metadata also displays the exact GPS coordinates.

**Comment by vitis586** [comment]
That is a cool app for Nextcloud and might be a fine addition to Memories. But it does not really solve my issue. I am quite happy with the level of information that Memories show right now. My problem is in the way that the current location editor interprets my input. Metadata also show just the raw GPS coordinates and not geolocated whereas I would like to keep it geolocated (as it is more usefull) but I want to have the option to save the exact location and not the location of the closest POI that Nominatim finds.

**Comment by florianwgnr** [comment]
Okay, I think I got you now. But something else I'd like to add: You wrote, that Android is implicitly not attaching location to EXIF when uploaded to Nextcloud.

I also experienced this issue, but ONLY when sharing photos from my gallery to Nextcloud! If I instead upload the photos from within the Nextcloud app or use the Auto-Upload feature, location data is attached to the pictures.

**Comment by vitis586** [comment]
The EXIF problem might not be same across all phones and only applies to Android right now. See https://github.com/nextcloud/android/issues/6248 for more.

I put the "problem" into a video in case that I did not describe it clearly. https://www.youtube.com/watch?v=CRv2jfEfy_M
You can see that I put in a different location (-1.401840,34.972100) than the one that would be then written to the EXIF (-1.3556765,34.9518871).
