### ISSUE TITLE
Favoriting a photo causes timeline's photos to disappear, and resets to most recent date.

### ISSUE THREAD

**Issue by Emporea** [pulsejet/memories#608]
Whenever I try to favorite a photo in the Memories app and click the close button (X), all the other photos in the timeline disappear, leaving only the "On this day" function visible.

However, when I tried to scroll on the website, I was taken back to the beginning of the timeline,so the top of the page.

Edit:
Just some more infos

NC: 26.0.1
memories: 5.0.5
Preview Generator installed.
Recognize installed, not not active.

**Comment by pulsejet** [comment]
I'm a bit confused when you say "app". Do you mean the web app?

Also can you check if there is anything in the JS console?

**Comment by pulsejet** [comment]
Maybe a browser cache issue?

**Comment by pulsejet** [comment]
Closing as stale. File a new issue if this persists in latest versions.
