### ISSUE TITLE
wrong crop

### ISSUE THREAD

**Issue by forgi007** [pulsejet/memories#609]
**Describe the bug**
In photo edit, adjust with Custom ratio, the saved image is cropped differently as in the editor. I just cut a bit from all the edges (like cutting around an A4 paper). The error always happens both in firefox and chrome. It seems there is a workaround: if First I save the image without any change, then edit again (the same image) doing the crop and save: the crop is as expected.

**To Reproduce**
Install memories
Edit a photo
Adjust
Custom
cut a bit from each size
save

**Screenshots**
if you can not reproduce it, then I will make a gif to show each step.

**Platform (please complete the following information):**
OS: Ubuntu 22.04.2 LTS (nextcloud server)
Browser: firefox and chromium (as client on Debian 11)
Version: 5.0.5 (on Nextcloud 26.0.1)

**Additional context**
Nothing relevant

**Important: Are all of the following are true?**
I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).
I am NOT using OCCWeb to run occ commands
The problem persists after clearing browser cache

Yes

**Comment by pulsejet** [comment]
Can you provide a sample image for which this happens?

**Comment by pulsejet** [comment]
I'm guessing this has to do with orientation. But I need a sample to check.

**Comment by forgi007** [comment]
Here is the bug: ![crop_bug](https://user-images.githubusercontent.com/13077110/234118266-e4033338-7903-4e0d-8a20-71d9db2fd4d4.gif). Plus another pic for testing: ![20230424_231657](https://user-images.githubusercontent.com/13077110/234119335-a8329fb0-e813-4b4a-9610-eee3e640c177.jpg).

I have noticed that I have the cropping problem only if I upload the picture with the nextcloud android app's 'automatic upload' function. I have also tried to index another picture (with `occ memories:index`) before doing the crop, but it has not solved the issue.
I have tried to reproduce the error with a picture uploaded from the nextcloud.files app, but I could not: cropping works fine on pictures added via files app.

**Comment by forgi007** [comment]
I have also tried `occ files:scan myuser` after having a new pic uploaded by the nextcloud android app and I still have the issue.

Lets try with another pic, uploaded the same way, via [sharing](https://forgi007.freeddns.org/nextcloud/index.php/apps/memories/s/jWsLgWYESnH7Y8s) from memories app

**Comment by pulsejet** [comment]
Don't worry, it's a bug ;)
