### ISSUE TITLE
Live photo broken after deleting and re-adding file

### ISSUE THREAD

**Issue by schlop** [pulsejet/memories#610]
**Describe the bug**
If an image gets deleted from nextcloud and is later re-uploaded it is displayed in memories as expected but the live view is broken (incorrect linking of image and video files).

**To Reproduce**
1. Upload photo.jpg and photo.mov to nextcloud
2. Look at the photo in memories. The image loads (photo.jpg) and the live photo video (photo.mov) plays as expected.
3. Delete the photo in memories. It disappears from the timeline.
4. Re-upload photo.jpg and photo.mov to nextcloud
5. Look at the photo in memories. The file loads (photo.jpg) but the live photo video (photo.mov) is not playing anymore.

**Platform (please complete the following information):**

- OS: MacOS 13
- Browser: Chrome
- Version: 5.0.5

**Additional context**
It appears that memories is requesting the video file from the wrong path after re-uploading. Maybe the database entry that links photo.jpg and photo.mov is not getting wiped once photo.jpg and photo.mov are deleted from nextcloud?

I have no errors in the console after the first upload of photo.jpg and photo.mov. After the re-upload of photo.jpg and photo.mov I get the following message in the console indicating an incorrect path and a subsequent 404.

```
GET https://...removed_nextcloud_url_for_privacy.../apps/memories/api/video/livephoto/597239?etag=8d9f63724329c511c358c0b00b721856&liveid=3AEB1DD8-7102-44D3-BBB9-6608CD5B92E2&transcode=y7c3x2453q00 404
Uncaught (in promise) DOMException: Failed to load because no supported source was found.
```

I have tired all sorts of things to fix this including occ memories:index -f but could never reestablish the proper linking between photo.jpg and photo.mov after having removed the initial upload.

**Comment by pulsejet** [comment]
Does the "Download Video" button also give any error? (JS console and nextcloud logs)
![image](https://user-images.githubusercontent.com/10709794/234102902-cecf7315-106e-4b4b-8d96-73ec41a3e3df.png)

**Comment by schlop** [comment]
Clicking the 'Download Video' button results in the following JSON to be displayed:

``
{"message":"Not found (live video file)"}
``

It seems that the linking of image and photo is incorrect after re-uploading. That also means that when deleting a re-uploaded non-working live photo again (2. deletion), only the image file gets removed and not the video.

**Comment by pulsejet** [comment]
Looks like some stale entries in your live photo table. This might be worth checking in the background job. Try running this sql:
```sql
DELETE m
FROM oc_memories_livephoto AS m
LEFT JOIN oc_filecache f ON f.fileid=m.fileid
WHERE f.fileid IS NULL
```

**Comment by schlop** [comment]
Running the SQL query fixed the issue. Many thanks.

Do you plan on adding this query as a background job in a future release? Or should I just run it via cron on my instance?

**Comment by pulsejet** [comment]
It'll be in a background job in the next release.
