### ISSUE TITLE
Editing metadata automatically updates date/time to today's date

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#612]
**Describe the bug**
Perhaps this is by design, but currently if any metadata is updated, the date/time is also updated to the current date.

**To Reproduce**
- Open photo that has not been modified
- Choose "Edit Metadata"
- Add a description to photo
- Click Save
- Note that date/time has also been updated

**Comment by pulsejet** [comment]
This will happen if the photo does not have a exif date to begin with, and is using the modified time for the date. In that case, it is correct behavior to update the modified time since "modify" the file.

**Comment by pulsejet** [comment]
Yeah, that's not the real date, it's actually a bug that was resolved with https://github.com/pulsejet/memories/commit/0e5f058af9ac08f240acf78acbd7c8c6f1e28a95. The video doesn't contain any date in this case.

**Comment by pulsejet** [comment]
Yup. I believe if you just "touch" the date (there needs to be a star beside it), that should still persist it then.

**Comment by pulsejet** [comment]
@meichthys I just realised the aforementioned commit already is in v5. You might want to run `occ memories:index -f`, it'll reset the dates for these videos to the modified time.
