### ISSUE TITLE
Memories stop showing my photos

### ISSUE THREAD

**Issue by PrzemekSkw** [pulsejet/memories#619]
**Describe the bug**
I noticed that I don't see photos in Memories. Only videos from my smartphone. Last photo is from march. I see new photos and movies in Photos of Nextcloud.

**Screenshots**
![Screenshot_2023-04-28-07-49-01-45_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/25219988/235065033-7a004b24-f1c8-4a44-bfd6-cdeff48150d6.jpg)

**Platform (please complete the following information):**

- OS: Debian 11
- Browser: Brave or firefox
- Version: Brave 1.50.114, Chromium 112.0.5615.49

**Additional context**
I see photos and videos in Nextcloud but don't see thumbnails of photos in Nextcloud Photos. When I scroll down page everything is gone from Photos page.

- Any errors in the JS console?  Don't know what it is.
- Any errors in the Nextcloud server logs?
No

Regards.

**Comment by pulsejet** [comment]
What's the output of `occ memories:index`?

**Comment by PrzemekSkw** [comment]
```
dietpi@DietPi:~$ cd .config/appdata/nextcloud/www/nextcloud/       dietpi@DietPi:~/.config/appdata/nextcloud/www/nextcloud$ php occ memories:index                                                       This version of Nextcloud requires at least PHP 8.0<br/>You are currently running 7.4.33. Please update your PHP version.dietpi@DietPi:~/.config/appdata/nextcloud/www/nextcloud$
```
