### ISSUE TITLE
Poor video perfomance in memories > than photos v2

### ISSUE THREAD

**Issue by ash32152** [pulsejet/memories#620]
Hey :)

Just wanted to see if anyone else has a similar experience. I get poor video playback in memories v5 (transcoding disabled) where it'll buffer even on a 9 second video, yet the same videos play fine via the photos app which is disappointing as memories is superior in every other way.

It's probably something to do with my config, I have the below set as per the documentation in config.php;
 'enable_previews' => true,
  'enabledPreviewProviders' => 
  array (
    1 => 'OC\\Preview\\HEIC',
    2 => 'OC\\Preview\\TIFF',
    3 => 'OC\\Preview\\MKV',
    4 => 'OC\\Preview\\MP4',
    5 => 'OC\\Preview\\AVI',
    20 => 'OC\\Preview\\Movie',
    21 => 'OC\\Preview\\Image',
  ),

with transcoding on it's better, but given access will majority be on LAN, I don't really want to increase CPU count just for this (no dedicated GFX).

files are stored on SSDs, although I don't think it's related to storage/network given photos is fine, guess they use different backend player but guess it's down to configuration.

Thanks!

**Comment by pulsejet** [comment]
Please follow the issue template while filling bugs.

This issue has been addressed already and will likely be fixed in the next patch.

**Comment by hxchtiewei** [comment]
> Please follow the issue template while filling bugs.
> 
> This issue has been addressed already and will likely be fixed in the next patch.

v5.1.0 also has this problem, will this issue be fixed in v5.2?

**Comment by pulsejet** [comment]
@hxchtiewei are you using transcoding?
Also you should try the alpha version. It should be good unless you're using NVENC.
