### ISSUE TITLE
Video streaming wrong content length

### ISSUE THREAD

**Issue by robertmx** [pulsejet/memories#622]
**Describe the bug**
When Streaming Videos with Firefox or Chromium, the chunked transfer http response's content length is not consistent with the response.

**To Reproduce**
Stream any video and observe ERR_CONTENT_LENGTH_MISMATCH errors in Chromium. 

**Platform:**

- OS: Linux
- Browser: Firefox and Chromium
- Memories Version: 5.0.5
- Nextcloud Version: 25.0.6
- PHP Version: 8.1

**Additional context**
Might be related to #592 ??

**Comment by pulsejet** [comment]
Hmm that's strange, this should've been fixed with 5.0.5...

1. Does this happen for each chunk?
2. Also I don't get this error for some reason (even when the content length is actually incorrect); do you have any extra flags for the browser?
3. Any chance you could find an example, i.e. how exactly the content length header differs from the actual byte count?

**Comment by invario** [comment]
Getting this now, possibly related to this report?  Not sure how I didn't pick this up sooner. Occurs when opening any MP4 video file. I tried with transcoding enabled as well as disabled (via admin settings).  Video does continue to play fine though.

`2023/04/28 16:44:21 [error] 3480#102053: *3223 FastCGI sent in stderr: "PHP message: {"reqId":"sbQIcfdpYfzR4xFGnPPW","level":3,"time":"2023-04-28T16:44:21-04:00","remoteAddr":"10.0.0.11","user":"USERNAME","app":"index","method":"GET","url":"/apps/memories/api/stream/3251741?numChunks=12","message":"fread(): Argument #2 ($length) must be of type int, float given in file '/usr/local/www/nextcloud/apps/memories/lib/Controller/DownloadController.php' line 210","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36","version":"26.0.1.1","exception":{"Exception":"Exception","Message":"fread(): Argument #2 ($length) must be of type int, float given in file '/usr/local/www/nextcloud/apps/memories/lib/Controller/DownloadController.php' line 210","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main"," while reading upstream, client: 10.0.0.11, server: MYSERVERADDRESS.com, request: "GET /apps/memories/api/stream/3251741?numChunks=12 HTTP/2.0", upstream: "fastcgi://unix:/var/run/nextcloud-php-fpm.sock:", host: "MYSERVERADDRESS.com"`

Immediately followed by my previously reported error in #597 
`2023/04/28 16:46:06 [error] 3480#102053: *3223 upstream prematurely closed FastCGI request while reading upstream, client: 10.0.0.11, server: MYSERVERADDRESS.com, request: "GET /apps/memories/api/stream/3252147?numChunks=21 HTTP/2.0", upstream: "fastcgi://unix:/var/run/nextcloud-php-fpm.sock:", host: "MYSERVERADDRESS.com"
`

**Platform (please complete the following information):**
NC 26.0.1 inside iocage jail - FreeBSD 13.1-RELEASE-p7 (host is TrueNAS Core 13)
Memories 5.0.5
Chrome Mobile or Desktop
nginx 1.22.0
PHP 8.1.12

**Comment by pulsejet** [comment]
Can you test with v5.1.0?

**Comment by invario** [comment]
Initial testing looks good! but I have to make sure when I get home and can monitor the logs realtime more closely.

**Comment by robertmx** [comment]
I tested on 5.1.0 and can confirm, that the problem seems fixed. There are no more browser errors (see initial report) and the reverse Proxy in front of nextcloud does not complain about errors while reading the response from the backend anymore.
BTW: Memories is just awesome, lightyears ahead of the official photos app. Great work.

**Comment by robertmx** [comment]
Just to give a little more context for future reference if needed:

- I only tested MP4 videos without transcoding, all of them 1080p and somewhat large (up to 600MB).
- The first chunk size seemed to be correct (on 5.0.5), all subsequent chunks were wrong, resulting in video stutter or a complete stop of the video stream.
- Somewhat comparable to invario's setup, there is a reverse proxy (apache2 mod_proxy) between nextcloud and the internet. ON 5.0.5 the proxy reported errors on incomplete responses from the backend, not observed on 5.1.0.

**Comment by pulsejet** [comment]
Can we close this then?

**Comment by invario** [comment]
Looks good on my end!
