### ISSUE TITLE
Raw 500 error message displayed while loading the memories settings page

### ISSUE THREAD

**Issue by geeerr** [pulsejet/memories#625]
**Describe the bug**

When opening the Memories settings page, I get a popup/toast with the following error message:

> {"message":"Request failed with status code 500","name":"AxiosError","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"FormData":null},"headers":{"Accept":"application/json, text/plain, */*","requesttoken":"XetSLVyEVcmYVUGhF0gYpWd8qDPuPeQyUAwVPVxkdts=:arsZVz+1YrrBJSmTQSppyyYRyUufTpV4PmBeUDIVDrw="},"method":"get","url":"/index.php/apps/memories/api/system-status"},"code":"ERR_BAD_RESPONSE","status":500}

![Memories_ERR500](https://user-images.githubusercontent.com/132052150/235294645-d13161a8-7d68-47e0-b283-800da2006d1a.png)

**To Reproduce**

Just load the Memories settings page.

**Platform:**

- OS: linux
- Browser: Chrome/Edge
- Memories Version: 5.0.5
- Nextcloud Version: 25.0.6
- PHP Version: 8.1.18

**Additional context**
Problem started to appear installing the version with the new memories settings section. Not sure it is related, but the transcoding which used to work is now broken.

- Any errors in the JS console?

> memories-main.js?v=ccfa391c-1:2     GET https://myhost.com/index.php/apps/memories/api/system-status 500
(anonymous) @ memories-main.js?v=ccfa391c-1:2
e.exports @ memories-main.js?v=ccfa391c-1:2
e.exports @ memories-main.js?v=ccfa391c-1:2
u.request @ memories-main.js?v=ccfa391c-1:2
o.forEach.u.<computed> @ memories-main.js?v=ccfa391c-1:2
(anonymous) @ memories-main.js?v=ccfa391c-1:2
refreshStatus @ memories-src_components_admin_AdminMain_vue.js?v=8a66646f9dc3c394ee35:1
mounted @ memories-src_components_admin_AdminMain_vue.js?v=8a66646f9dc3c394ee35:1
Xn @ memories-main.js?v=ccfa391c-1:2
un @ memories-main.js?v=ccfa391c-1:2
insert @ memories-main.js?v=ccfa391c-1:2
_ @ memories-main.js?v=ccfa391c-1:2
Wi.nodeOps @ memories-main.js?v=ccfa391c-1:2
e._update @ memories-main.js?v=ccfa391c-1:2
o @ memories-main.js?v=ccfa391c-1:2
e.get @ memories-main.js?v=ccfa391c-1:2
e @ memories-main.js?v=ccfa391c-1:2
(anonymous) @ memories-main.js?v=ccfa391c-1:2
sr.$mount @ memories-main.js?v=ccfa391c-1:2
sr.$mount @ memories-main.js?v=ccfa391c-1:2
e._init @ memories-main.js?v=ccfa391c-1:2
sr @ memories-main.js?v=ccfa391c-1:2
(anonymous) @ memories-main.js?v=ccfa391c-1:2
Promise.then (async)
(anonymous) @ memories-main.js?v=ccfa391c-1:2
(anonymous) @ memories-main.js?v=ccfa391c-1:2
(anonymous) @ memories-main.js?v=ccfa391c-1:2

- Any errors in the Nextcloud server logs?

> {"reqId":"VjY2e8fBEWGHt1OW6h1n","level":3,"time":"2023-04-28T16:39:26+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"Dummy","app":"index","method":"GET","url":"/index.php/apps/memories/api/system-status","message":"Path cannot be empty in file '/srv/www/htdocs/nextcloud/apps/memories/lib/Service/BinExt.php' line 35","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36","version":"25.0.6.1","exception":{"Exception":"Exception","Message":"Path cannot be empty in file '/srv/www/htdocs/nextcloud/apps/memories/lib/Service/BinExt.php' line 35","Code":0,"Trace":[{"file":"/srv/www/htdocs/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/srv/www/htdocs/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/srv/www/htdocs/nextcloud/lib/base.php","line":1048,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/srv/www/htdocs/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"ValueError","Message":"Path cannot be empty","Code":0,"Trace":[{"file":"/srv/www/htdocs/nextcloud/apps/memories/lib/Service/BinExt.php","line":35,"function":"copy"},{"file":"/srv/www/htdocs/nextcloud/apps/memories/lib/Service/BinExt.php","line":97,"function":"getTempBin","class":"OCA\\Memories\\Service\\BinExt","type":"::"},{"file":"/srv/www/htdocs/nextcloud/apps/memories/lib/Controller/OtherController.php","line":125,"function":"getExiftoolPBin","class":"OCA\\Memories\\Service\\BinExt","type":"::"},{"file":"/srv/www/htdocs/nextcloud/apps/memories/lib/UtilController.php","line":20,"function":"OCA\\Memories\\Controller\\{closure}","class":"OCA\\Memories\\Controller\\OtherController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/srv/www/htdocs/nextcloud/apps/memories/lib/Controller/OtherController.php","line":193,"function":"guardEx","class":"OCA\\Memories\\Util","type":"::"},{"file":"/srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"getSystemStatus","class":"OCA\\Memories\\Controller\\OtherController","type":"->"},{"file":"/srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/srv/www/htdocs/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/srv/www/htdocs/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/srv/www/htdocs/nextcloud/lib/base.php","line":1048,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/srv/www/htdocs/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/srv/www/htdocs/nextcloud/apps/memories/lib/Service/BinExt.php","Line":35},"CustomMessage":"--"}}

**Comment by invario** [comment]
Try this #601

**Comment by geeerr** [comment]
Thanks for the tip. I forgot to remove the "is:open" filter while looking up for similar issues, my apologies about that.

However, even when I correctly configure the path to the exiftool (and I know this one can be run under the appropriate account), I'm still getting the error.

**Comment by invario** [comment]
You manually added the lines into config.php? Hmm...

**Comment by geeerr** [comment]
> You manually added the lines into config.php?

I did. The path shows up in the configuration page.

apache logs the 500 as:

xxx.xxx.xxx.xxx - - [29/Apr/2023:17:16:06 +0200] "GET /index.php/apps/memories/api/system-status HTTP/2.0" 500 1443

**Comment by invario** [comment]
I'm out of ideas.  I just tested it myself and if I comment out the line to configure memories.exiftool I reproduce the error.  Uncommenting the line definitely fixes it.

All I can suggest is to triplecheck your config.php again, sorry.

**Comment by pulsejet** [comment]
This has fixed in the next version anyway, so gonna close this as duplicate.
