### ISSUE TITLE
ffmpeg transcoding failing with "Unrecognized option 'rc" with nvenc vod 

### ISSUE THREAD

**Issue by OCT0PUSCRIME** [pulsejet/memories#626]
Describe the bug
I am unable to get hardware transcoding to work with nvenc
This is a bare metal install on a debian LXC container with proxmox and the GPU passed through. Config works with other programs (Jellyfin)

To Reproduce
Error on every video

Platform (please complete the following information):

    OS: Debian
    Browser Firefox
    Version 5.0.3

Additional context
config.php:

`
...
  'memories.exiftool' => '/var/www/nextcloud/apps/memories/exiftool-bin/exiftool-amd64-glibc$
  'memories.vod.path' => '/var/www/nextcloud/apps/memories/exiftool-bin/go-vod-amd64',
  'memories.vod.ffmpeg' => '/usr/bin/ffmpeg',
  'memories.vod.ffprobe' => '/usr/bin/ffprobe',
  'memories.vod.disable' => false,
  'memories.gis_type' => 2,
  'memories.vod.nvenc' => true,
  'memories.vod.nvenc.scale' => 'cuda',
  'memories.vod.nvenc.temporal_aq' => true,
);

`

Log:

`2023/04/29 10:34:31 x987fr1us9j0-max: /usr/bin/ffmpeg -loglevel warning -hwaccel cuda -autorotate 0 -i /nextcloud/[USER]/files/Media/2023/04/VID_20230424_182910.mp4 -copyts -vf format=nv12|cuda,hwupload,scale_cuda=force_original_aspect_ratio=decrease:passthrough=0 -profile:v main -map 0:v:0 -c:v h264_nvenc -preset p6 -tune ll **-rc** vbr -rc-lookahead 30 -cq 24 -temporal-aq 1 -map 0:a:0? -c:a aac -ac 1 -avoid_negative_ts disabled -f hls -hls_time 3 -force_key_frames expr:gte(t,n_forced*3) -hls_segment_type mpegts -start_number 0 -hls_segment_filename /tmp/go-vod/62d4e84c2b7e7/x987fr1us9j0-1973312721/max-%06d.ts -
2023/04/29 10:34:31 ffmpeg-error: Unrecognized option 'rc'.
2023/04/29 10:34:31 ffmpeg-error: Error splitting the argument list: Option not found
2023/04/29 10:34:31 x987fr1us9j0-max: ffmpeg exited with status: 1`

I thought the issue might be with my FFmpeg install so I compiled my own FFmpeg with CUDA and confirmed it is working. Unfortunately, if I try to get Memories to use my own FFmpeg I get this error:

`ffmpeg failed test: failed to detect version, found ffmpeg version N-110417-g41dd50ad0d Copyright (c) 2000-2023 the FFmpeg developers built with gcc 8 (Debian 8.3.0-6) configuration: --pkg-config-flags=--static --prefix=/opt/ffmpeg --bindir=/opt/ffmpeg/bin --extra-cflags=-I/opt/ffmpeg_build/include --extra-ldflags=-L/opt/ffmpeg_build/lib --enable-cuda-nvcc --enable-cuvid --enable-libnpp --extra-cflags=-I/usr/local/cuda/include/ --extra-ldflags=-L/usr/local/cuda/lib64/ --enable-nvenc --enable-libass --disable-debug --enable-libvorbis --enable-libvpx --enable-opencl --enable-gpl --cpu=native --enable-libfdk-aac --enable-libx264 --enable-libx265 --enable-openssl --enable-librtmp --extra-libs='-lpthread -lm -lz' --enable-nonfree libavutil 58. 6.100 / 58. 6.100 libavcodec 60. 10.100 / 60. 10.100 libavformat 60. 5.100 / 60. 5.100 libavdevice 60. 2.100 / 60. 2.100 libavfilter 9. 6.100 / 9. 6.100 libswscale 7. 2.100 / 7. 2.100 libswresample 4. 11.100 / 4. 11.100 libpostproc 57. 2.100 / 57. 2.100 .`

I confirmed my compiled FFmpeg works on the same video manually via command line:

`ffmpeg -y -hwaccel cuda -hwaccel_output_format cuda -i test.mp4 -c:a copy -c:v h264_nvenc testoutput.mp4`

but if I try to pass through additional arguments, including the -rc argument, I still get Unrecognized option 'rc'.

I am having trouble finding this option on any FFmpeg documentation.

Transcoding works via CPU if I disable nvenc in memories.

**Comment by pulsejet** [comment]
I've no idea what it's doing either. Maybe you could try recompiling go-vod with that option removed? It should be in `stream.go`

For the ffmpeg detection error you can just ignore it.

**Comment by OCT0PUSCRIME** [comment]
My mistake, I did not attempt running a test in NextCloud with my own compiled FFmpeg when I got that detection error and must have passed in the arguments incorrectly when I ran the manual test. It appears when I use my own compiled FFmpeg and ignore the FFmpeg detection error this is actually working.

**Comment by ChildLearningClub** [comment]
I'm getting this same error. I downloaded go-vod from github and built it, and I believe I passed in the GPU to the container correctly?
```
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
I get a printout from within the container when running nvidia-smi. Normal transcoding works with the external go-vod connected, but gives the 'ffmpeg-error: Unrecognized option 'rc' when NVENC acceleration enabled.

**Comment by OCT0PUSCRIME** [comment]
It's been awhile since I had this issue. I don't really remember what I did to fix it, but I am no longer using my own compiled ffmpeg. I have jellyfin-ffmpeg6 installed and memories pointing at that. You can install jellyfin-ffmpeg6 without installing jellyfin itself. Maybe that will solve your issue.

**Comment by ChildLearningClub** [comment]
Thank you @OCT0PUSCRIME for the quick reply. I will have to figure out how to do that.
