### ISSUE TITLE
[Documentation] VA-API examples

### ISSUE THREAD

**Issue by luxzg** [pulsejet/memories#628]
**Describe the bug**
I propose a little documentation update
[https://github.com/pulsejet/memories/wiki/HW-Transcoding#va-api](https://github.com/pulsejet/memories/wiki/HW-Transcoding#va-api)

In my case I'm using Ubuntu, and after:
`apt-get install -y intel-media-va-driver-non-free ffmpeg`
I had to fix permissions, as the configuration page alerted me, but neither conf page nor docs said which permissions it needed.
Seems right ones are:
`chmod 666 /dev/dri/renderD128`
(I did `chmod o+r /dev/dri/renderD128` which lit up the config page as green/usable but I still had errors)

Likewise an example for testing in command line would've been helpful. I've solved the permission issue because the following test confirmed that running as www-data still didn't work with just `o+r`:
```
# test as root
ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i 'testfile.mp4' -vcodec h264_vaapi output-root.mp4
# test as apache / www-data
sudo -u www-data ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i 'testfile.mp4' -vcodec h264_vaapi output-www-data.mp4

# If both output same and the result file is same then test is successful.
```

I still have some additional issues depending on format being played, but this moved me in the right direction, and I'm sure adding few lines in documentation would help others too :) Thanks!

**To Reproduce**
On VA-API compatible system, install non-free Intel driver as instructed.
Check config page inside Nextcloud admin settings, it will have red error complaining about permissions.
Change render to `o+r`
Refresh config page, it will show green for VA_API now (which is also WRONG)
Videos still have errors playing
Test in CLI with root works, but running as `www-data` throws error `no va display found for device /dev/dri/renderd128` indicating permissions aren't good enough for ffmpeg to run transcode.
Change render permissions to `666`
Video can now transcode in CLI, and play in browser

**Screenshots**

**Platform:**

- OS: Windows 11
- Browser: Chrome
- Memories Version: 5.1.0
- Nextcloud Version: 26.0.0
- PHP Version: 8.1

**Additional context**

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

**Comment by flurmind** [comment]
Hi, I have a same problem when I use this method to install the drivers:
```
environment:
- DOCKER_MODS=linuxserver/mods:universal-package-install
- INSTALL_PACKAGES=libva|libva-intel-driver|intel-media-driver|mesa-va-gallium
```
How can I add a script start.sh to the startup in docker container linuxserver/nextcloud?

**Comment by pulsejet** [comment]
Updated, thanks @luxzg!
https://memories.gallery/hw-transcoding/#va-api
