### ISSUE TITLE
Album is not in sidebar

### ISSUE THREAD

**Issue by chrislimk** [pulsejet/memories#629]
---

**Describe the bug**
Albums is missing from the sidebar and I could not find any reference on how to enable it or if something is broken.

**To Reproduce**
I don't have another setup to test this out yet. 

**Screenshots**
<img width="2207" alt="Screenshot 2023-05-03 at 2 22 41 AM" src="https://user-images.githubusercontent.com/51529193/235753565-d14028fc-82e4-454f-add0-246a46c1d88d.png">

**Platform:**

- OS: MacOS
- Browser: Safari
- Memories Version: 5.1.0
- Nextcloud Version: 26.0.1
- PHP Version:  8.1

**Additional context**
Only installed memories and disabled Photos

**Comment by EVOTk** [comment]
Hello, 
Albums need Photos App is enable
