### ISSUE TITLE
Some folders got skipped during occ memories:index

### ISSUE THREAD

**Issue by bankjaneo** [pulsejet/memories#63]
I have 2 instances of Nextcloud 24.0.5 with Memories 2.1.3 and have a problem with some folder not get indexed and always display message "No photos to show here" when accessed.

I tried ran occ memories:index and noticed that folders that have problem got skipped and no log show why. Below is result of occ memories:index from one of my instances. You can notice that **/bankja/files/Public** got skipped while another instance the folder that got skipped is **/username/files/Payments**

````
Scanning folder /bankja/files
Scanning folder /bankja/files/Documents
Scanning folder /bankja/files/Photos
Scanning folder /bankja/files/Photos/Bankja_12
Scanning folder /bankja/files/Photos/Bankja_12/2022
Scanning folder /bankja/files/Photos/Bankja_12/2022/07
Scanning folder /bankja/files/Photos/Bankja_12/2022/08
Scanning folder /bankja/files/Photos/Bankja_12/2022/09
Scanning folder /bankja/files/Photos/Bankja_12/2022/10
Skipping folder /bankja/files/Public
Scanning folder /bankja/files/ValheimPlus
==========================================
Checked 138 files in 0.05 sec
7 not valid media items
131 skipped because unmodified
0 (re-)processed
==========================================
````

Thank you.

**Comment by pulsejet** [comment]
That's because of a `.nomedia` file in the folder.

**Comment by bankjaneo** [comment]
Oh... I completely forgot about that. .nomedia from old days. Thank you so much.
