### ISSUE TITLE
Error downloading geo 

### ISSUE THREAD

**Issue by lordraiden** [pulsejet/memories#631]
**Describe the bug**

I get this error when I click on update geo

![imagen](https://user-images.githubusercontent.com/17175395/235896681-66ddc060-2b14-46c8-a0fd-87569767ee55.png)

A new tab is opened with this url http://10.10.40.160/apps/memories/api/occ/places-setup but is blank and nothing happens

unlink(/tmp/planet_coarse_boundaries.zip): No such file or directory at /var/www/html/custom_apps/memories/lib/Service/Places.php

If I run the command  occ memories:places-setup 
i get this errrors

![imagen](https://user-images.githubusercontent.com/17175395/235897809-e1ebcb4c-abce-41e6-bf8c-c336d23984f0.png)

**Platform:**

Docker
[Nextcloud Hub 4](https://nextcloud.com/) (26.0.1)
Memories 5.1.0

**Comment by pulsejet** [comment]
Can you try doing it inside the container like `docker exec -it Nextcloud bash` then `sudo -u #82 php occ memories:places-setup`?

**Comment by lordraiden** [comment]
> Can you try doing it inside the container like `docker exec -it Nextcloud bash` then `sudo -u #82 php occ memories:places-setup`?

![imagen](https://user-images.githubusercontent.com/17175395/236031273-a5a57b1c-5f86-40fc-978e-d46f250a6e6f.png)


At the end this command worked

docker exec -u 82 -it Nextcloud php occ memories:places-setup
