### ISSUE TITLE
Emojis in folder names break folder content view 

### ISSUE THREAD

**Issue by Dobli** [pulsejet/memories#635]
**Describe the bug**
When you have folders that contain emojis in their names, it is not possible to view their content in memories folder view.
Instead it is empty and an error message is displayed, hinting that the folder cannot be found.

**To Reproduce**
- Create a new folder that contains an emoji in its name e.g. `🎂 Birthday`
- Add some images to the folder
- Try to open it in the folder view

**Screenshots**
![error](https://user-images.githubusercontent.com/5928062/236633384-9588ece0-0542-44cf-8080-89ddd3132484.png)

**Platform:**

- OS: Linux / Android
- Browser: Firefox
- Memories Version: 5.1.0
- Nextcloud Version: 26.0.1
- PHP Version: 8.1.18

**Additional context**
The path that is displayed within the error message does not contain the emoji, so instead of `/user/photos/🎂Birthday` it hints that it cannot find the content of `/user/photos/Birthday`. So it seems to strip the emoji before trying to retrieve the folder.

**Comment by EVOTk** [comment]
Same issue for me 
![image](https://user-images.githubusercontent.com/45015615/236640753-971fe5a8-d21e-4898-9ccb-8264c7d64db2.png)

**Comment by tstdin** [comment]
Not only emojis, but also `+` sign (and probably other special characters).

**Comment by Dobli** [comment]
Wow, cool to see it fixed this quickly 👍
