### ISSUE TITLE
Memories Config - Transcoding - Reset Settings

### ISSUE THREAD

**Issue by Cebrain** [pulsejet/memories#637]
**Is your feature request related to a problem? Please describe.**
https://github.com/pulsejet/memories/issues/585#issuecomment-1513746963
If you missconfigure the settings and want to get back to default you need to edit manually edit the config and remove the parts from the config file. 

**Describe the solution you'd like**
A reset button or Default Config Button would be great.

**Comment by pulsejet** [comment]
Admin panel with 5.0
