### ISSUE TITLE
No geolocation data from Google Pixel 7 Pro phones

### ISSUE THREAD

**Issue by ChojinDSL** [pulsejet/memories#639]
**Describe the bug**
With my old Samsung Galaxy Note 8, the memories app was correctly able to interpret the gps exif data in the photos. 
With the photos from my Google Pixel 7 Pro, the location metadata stays empty. Opening the same photo on my phone in the google photos app, I can see that location is stored.

**To Reproduce**
Take a photo on my Google Pixel 7 Pro (geotagging is enabled)
Upload to nextcloud via autoupload, then view the photo in the memories app.

**Screenshots**
![image](https://user-images.githubusercontent.com/1926396/236664755-542c69c6-0a02-437b-b2bc-923bdf94c8ef.png)

**Platform:**

- OS: [Debian Bookworm]
- Browser: [Firefox]
- Memories Version: [5.1.0]
- Nextcloud Version: [25.0.6]
- PHP Version: [8.0.28]

**Comment by pulsejet** [comment]
This is likely because the photos aren't being uploaded with the location to begin with. New Android versions restrict location access for apps; you might need to add some permissions for the Nextcloud app.

**Comment by pulsejet** [comment]
You can try downloading the file locally from Nextcloud and check if it has the location data.

**Comment by pulsejet** [comment]
https://github.com/nextcloud/android/issues/6248#issuecomment-1510383027

**Comment by ChojinDSL** [comment]
> [nextcloud/android#6248 (comment)](https://github.com/nextcloud/android/issues/6248#issuecomment-1510383027)

Thanks, that was indeed the issue! Did another test photo and location is now properly set.

Never in a million years would I have thought of that, since I assumed that simply the file gets uploaded and therefore it should be identical.

Live and learn.
