### ISSUE TITLE
Cannot enable Memories app - Alpine Linux, Busybox?

### ISSUE THREAD

**Issue by archont00** [pulsejet/memories#642]
**Describe the bug**

When I download and try to enable Memories app via Nextcloud Admin GUI, it fails with the following error message in nextcloud.log:

```
{"reqId":"kSXRACAVK6v9d1dB9vGU","level":3,"time":"2023-05-08 19:54:11","remoteAddr":"172.17.26.1","user":"XXX","app":"PHP","method":"POST","url":"/settings/apps/enable","message":"[snuffleupagus][0.0.0.0][disabled_function][drop] Aborted execution on call of the function 'shell_exec', because its argument '$command' content (ps -ef | grep go-vod-ocwgkowh3q4h | grep -v grep | awk '{print $2}') matched a rule at /nextcloud/apps2/memories/lib/Util.php#461","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0","version":"25.0.6.1","data":{"app":"PHP"}}
```

**Platform:**

- OS: Host OS Ubuntu Server 22.04, Docker image ghcr.io/hoellen/nextcloud:25
- Browser: Firefox
- Memories Version: 5.1.0
- Nextcloud Version: 25.0.6
- PHP Version: 8.1.18

**Additional context**
The docker image runs Alpine Linux, the shell is BusyBox v1.35.0.

The bug appears at /nextcloud/apps2/memories/lib/Util.php#461

```
$pids = shell_exec("ps -ef | grep {$name} | grep -v grep | awk '{print $2}'");
```

So, one problem is that in BusyBox, the PID is at the first position, rather than at the second, e.g.:
```
/nextcloud/apps2/memories $ ps -ef | grep supervise
   19 nextclou  0:00 s6-supervise cron
   20 nextclou  0:00 s6-supervise nginx
   21 nextclou  0:00 s6-supervise php
10565 nextclou  0:00 grep supervise

/nextcloud/apps2/memories $ ps -ef | grep 'supervise' | grep -v grep | awk '{print $1}'
19
20
21
```

Yet, even after modifying the beformentioned line to:
```
$pids = shell_exec("ps -ef | grep {$name} | grep -v grep | awk '{print $1}'");
```
does not work. The error in nextcloud.log is the same.

**Comment by pulsejet** [comment]
I believe this is happening due to `snuffleupagus` disallowing `shell_exec` for security reasons. We could possibly handle the ps format here, but the former will need some other configuration.

**Comment by archont00** [comment]
I cannot do much on my own re. PHP - any hints how to configure Snuffleupagus module to let the `shell_exec` in Memories work? (I know how to patch files & rebuild a docker image, at least.)

Regarding the `ps -ef` command. I believe syntax like e.g. `ps -e -o comm -o pid` would be better.

**Comment by archont00** [comment]
Okay, it was not that hard eventually. In the Docker image `ghcr.io/hoellen/nextcloud:25`, I have added this line to the configuration for Snuffleupagus to allow running any (!) shell_exec:

```
$ grep "memories" /usr/local/etc/php/conf.d/nextcloud-php8.rules 
sp.disable_function.function("shell_exec").param("command").filename("/nextcloud/apps2/memories/lib/Util.php").allow();
```

Closing this issue as it is related to docker image rather than memories app itself.
