### ISSUE TITLE
Bigger Scroll Bar on Webapp

### ISSUE THREAD

**Issue by stickyfran** [pulsejet/memories#644]
First of all, thanks for this ❣️. Memories is great and my family love it.

it would be nice for the Scroll bar to be a little bit big. Just a little bit. It's way too small compared to any other app

It would also help to do not auto hide until longer time. For example in Google Photos is about 4-5 seconds while in Memories is about 2-3.
 
I know it's a small thing but it would greatly improve app usage.

PD: About the Size of the scrollbar. It seems to be a 50% bigger on similar apps. Already compared on a big s22 ultra and smaller android devices and on multiple browser
PD2: Also it would be great to be able to Hide the specific DAY sorting of photos like in Google Photos app.
Phone screens are not so big and is not necesary to arrange Photos by day. Monthly should be ok

**Comment by pulsejet** [comment]
Good catch. The size is already adjusted a bit for the next version; hopefully it's better now.

> Also it would be great to be able to Hide the specific DAY sorting of photos like in Google Photos app.

That's surprising. I have day sorting in Google Photos on all phones except in albums 🤔

**Comment by stickyfran** [comment]
Thanks!

oh i got what happened
i always use GPhotos zoomed out, that's why my photos are sorted by Month. That's a nice feature

**Comment by pulsejet** [comment]
Ha! Never knew about that.
