### ISSUE TITLE
occ memories:places-setup do not work with no table prefix

### ISSUE THREAD

**Issue by diroots** [pulsejet/memories#648]
**Describe the bug**
occ memories places:setup do not work with a nextcloud installation with empty table prefix. 

our installation is done with this parameter in config.php :  `'dbtableprefix' => '',`

when launching occ memories places:setup, we get this result : 

```
server:/path/to/nextcloud# occ memories:places-setup
Attempting to set up reverse geocoding

In Places.php line 42:
                                                                                     
  Database table prefix is not set. Cannot use database extensions (dbtableprefix).  
                                                                                     

memories:places-setup
```

it's a bit like https://github.com/pulsejet/memories/issues/632, except my nc installation is with empty table prefix, and i cannot change it,... 

**To Reproduce**
- install nextcloud with empty table prefix
- install memories
- run `occ memories:places-setup`

**Platform:**

- OS: Ubuntu 20.04 LTS, docker image
- Browser: not applicable
- Memories Version: [5.1.0]
- Nextcloud Version: [25.0.6]
- PHP Version: [8.0]

**Additional context**

- Any errors in the JS console? not applicable
- Any errors in the Nextcloud server logs?

**Comment by diroots** [comment]
also i don't get the purpose of this check : https://github.com/pulsejet/memories/blob/master/lib/Service/Places.php#L41

as when checking where is used this $prefix variable the the whole app, it's only called there : 

```
root@server:/path/to/nextcloud/html/custom_apps/memories# grep -nR --exclude-dir=exiftool-bin '$prefix'
lib/Service/Places.php:40:        $prefix = $this->config->getSystemValue('dbtableprefix', '') ?: '';
lib/Service/Places.php:41://        if ('' === $prefix) {
root@server:/path/to/nextcloud/html/custom_apps/memories# 

```

so it's defined, then checked for not being empty, but then it's not used anywhere. 

why is this check needed, then? 
and it should be tested that it is defined correctly, but it can be empty, as nextcloud install can have prefix empty (https://github.com/nextcloud/server/blob/master/config/config.sample.php#L145).

**Comment by pulsejet** [comment]
The sample config has been corrected now: [38321](https://github.com/nextcloud/server/pull/38321)

**Comment by diroots** [comment]
but what happens with a nc instance already set up without prefix (running for years)? we cannot install memories? like there is no other choice?

**Comment by akhil1508** [comment]
>  Putting nextcloud's tables inside a prefix allows placing the geometry table in a separate memories_ namespace, which Doctrine then ignores.

@pulsejet In an installation which had `dbtableprefix => 'oc_'`, I could see tables like `oc_memories_places` and `oc_memories`. How does Doctrine ignore these?

**Comment by pulsejet** [comment]
> but what happens with a nc instance already set up without prefix (running for years)? we cannot install memories? like there is no other choice?

Places is an optional feature, so you should be able to use everything else just fine. If you really need places support, you'll need to manually migrate the DB to a non blank prefix (basically rename all tables to have this prefix, then update config.php)

**Comment by pulsejet** [comment]
@bendschs that seems unrelated. You might need to upgrade / set some options in your DB. What DB is this anyway?

**Comment by bendschs** [comment]
it's MariaDB 10.5.8. reading over various issues regarding the planet database it seems almost like this feature is still a bit experimental (not to be taken as criticism)?

thanks for the amazing work you have done at this point, it's really quite impressive how much progress you made with this app, it's already so much better than the official photos app.

**Comment by pulsejet** [comment]
> it's MariaDB 10.5.8. reading over various issues regarding the planet database it seems almost like this feature is still a bit experimental (not to be taken as criticism)?

It's quite stable actually. Two issues that are common:
1. Memory limits: batch insertions are faster but they end up creating some trouble on low memory systems.
2. This (#648) issue, which nothing can be done about (it's a Doctrine limitation). Fortunately, any Nextcloud setup from the last five years or so likely shouldn't have trouble.

Regarding the error you got (first time I'm seeing this), it's likely a database configuration mismatch; what's happening here is MariaDB is refusing to create the spatial index. A couple of things to try:
1. `occ maintenance:repair`
2. You could verify some db/table settings
    - You are using InnoDB
    - Row format is `dynamic`
    - Collation is `utf8mb4_general_ci`

> thanks for the amazing work you have done at this point, it's really quite impressive how much progress you made with this app, it's already so much better than the official photos app.

🎉

**Comment by bendschs** [comment]
Thank you for the immediate reply.
I've noticed, that my collation is utf8mb4_bin instead of  utf8mb4_general_ci.
do you think it would make a difference changing the collation to utf8mb4_general_ci for all the tables?

row format is dynamic and i am usind InnoDB.

**Comment by pulsejet** [comment]
> Thank you for the immediate reply. I've noticed, that my collation is utf8mb4_bin instead of utf8mb4_general_ci. do you think it would make a difference changing the collation to utf8mb4_general_ci for all the tables?

Nope, seems unlikely. Out of ideas at this point, a couple of pointers:
1. Check for `innodb_large_prefix`, the table should be created with it on, I believe.
2. How are you deploying the DB? A fresh Docker install seems to work so might be worth checking the difference in the config.
3. You could try commenting out the index in `lib/Service/Places.php` lines 433 - 437 to make sure that the spatial index is throwing the error and not something else. Also reduce the size of `varchar` above, but this should make no difference likely, because they aren't indexed.

**Comment by pulsejet** [comment]
> Also reduce the size of `varchar` above, but this should make no difference likely, because they aren't indexed.

I realised there _is_ an index on this (the pkey) so this is definitely worth trying. Try reducing the `varchar(255)` to `varchar(128)` or 64.

**Comment by pulsejet** [comment]
@bendschs this change: https://github.com/pulsejet/memories/commit/5cffbf2197b482196dfb256ff29bc54d0bdb89d1

**Comment by bendschs** [comment]
> 

that did the trick, thank you so much 🙏

**Comment by rhyst** [comment]
Just in case it is relevant for anyone searching I also had the `Database table prefix is not set` message despite a relatively modern nextcloud installation. I checked the database and could see all the tables were actually prefixed with `oc_`. I checked my `config.php` and it was missing a `dbtableprefix` entry so I added one:

```
'dbtableprefix' => 'oc_',
```
 
And `places-setup` now works. Not sure how I ended up without that config item but with prefixes.

**Comment by Glandos** [comment]
I have an old installation (migrated from ownCloud actually), and this hit me.

If there's no workaround, maybe it's good to have an entry in the FAQ?

**Comment by pulsejet** [comment]
> If there's no workaround, maybe it's good to have an entry in the FAQ?

I've added an entry to the docs. https://memories.gallery/troubleshooting/#database-table-prefix

Technically the workaround is to rename all tables to have a prefix. Theoretically this is easy but I've not tried it.

**Comment by e-minguez** [comment]
Will this work? https://help.nextcloud.com/t/rename-database-and-prefixes/28296/4 (I mean, running the opposite, adding the prefix)

**Comment by pulsejet** [comment]
Yeah, it should theoretically work. Strongly suggest having backups.

**Comment by lbrunkho** [comment]
> Just in case it is relevant for anyone searching I also had the `Database table prefix is not set` message despite a relatively modern nextcloud installation. I checked the database and could see all the tables were actually prefixed with `oc_`. I checked my `config.php` and it was missing a `dbtableprefix` entry so I added one:
> 
> ```
> 'dbtableprefix' => 'oc_',
> ```
> 
> And `places-setup` now works. Not sure how I ended up without that config item but with prefixes.

I am using a docker deployment with the linuxserver.io image and this was the same case for me. I checked the tables in mariadb and saw that they all had `oc_` prefixed to them. Added the above mentioned line to my config and I'm off to the races.

**Comment by arnowelzel** [comment]
It may also help to not use SQL insert statements but to do LOAD DATA instead. However this requires configuration on the database server and _may_ be a security issue if the server is allowed to read files without any restriction.

**Comment by arnowelzel** [comment]
Even with `occ memories:places-setup --transaction-size=5` the job fails at around 70% :-(. I had to reduce the transaction size to 2 to finally get all data inserted. But so far the database runs native on Ubuntu 24.05 LTS with 6 cores and 24 GB of RAM assigned to InnoDB and always worked fine so far.
