### ISSUE TITLE
Can't switch Direct/HLS on Safari

### ISSUE THREAD

**Issue by pulsejet** [pulsejet/memories#650]
Reported at https://github.com/pulsejet/memories/issues/598#issuecomment-1550613653

**Comment by ChildLearningClub** [comment]
This extends to Safari on Mac as well not just the iOS Safari.

**Comment by ChildLearningClub** [comment]
This may also be related, but the live videos do not play on Safari or iOS Safari either. Windows everything works great!

**Comment by relink2013** [comment]
I can confirm this. The videos do transcode, but the icon is missing. So there is no way to change the quality or switch to direct. 

This is also the case in Orion as well. Orion is also based on WebKit and is often a version or two ahead of safari.
