### ISSUE TITLE
"Failed to Delete" image from Memories

### ISSUE THREAD

**Issue by danbt** [pulsejet/memories#655]
I'm having an issue where when I try to delete images/videos via the PWA on Android and the web interface, it just says "Failed to delete <filename>

Where can I find additional logs?

Any ideas?

**Comment by pulsejet** [comment]
JS console and/or Nextcloud logs

**Comment by tincanfury** [comment]
I'm having the same issue from the web interface, I get the "Failed to delete" error, nothing in the Nextcloud logs. Same thing when I try and move files.

**Comment by praet0ri4n** [comment]
Thanks for pointing out the console log. In my case there was a problem having the session open for too long without page refresh. At delete attempts and other work the log wrote about CSRF token mismatch and that it could not fetch a new one.
Simply reloaded the page and deleting worked again.
