### ISSUE TITLE
Only newly added photos present in Map view

### ISSUE THREAD

**Issue by dzacball** [pulsejet/memories#657]
- I have old photos (imported long back from google)
- These old photos don't appear in Map and Places view. Newly added photos DO appear.
- All photos (both new & old) do appear in Timeline view
- All photos DO appear in NextCloud Maps app

Can you help me sort this out ? Am I missing a magic command ?
Many thanks for reading this.

**Comment by pulsejet** [comment]
`occ memories:index -f` or `occ memories:index --clear`

**Comment by dzacball** [comment]
Thanks a lot! That worked.

**Comment by pulsejet** [comment]
Great!
