### ISSUE TITLE
Reverse Geocoding planet data is incomplete.

### ISSUE THREAD

**Issue by d8sychain** [pulsejet/memories#659]
NC: 26.0.1
DB: MariaDB 10.5.12
Memories: 5.1.0

On the Memories admin page, it shows "Database is populated with 276443 geometries. Looks like the planet data is incomplete."

When I try to run occ memories:places-setup I get an error at the same point every time.

<img width="1298" alt="error" src="https://github.com/pulsejet/memories/assets/43706802/6e20f311-674a-4ab6-b03f-0244457cbd94">

**Comment by pulsejet** [comment]
Possible that the DB isn't configured with `utf8mb4` encoding...

**Comment by d8sychain** [comment]
The DB wasn't configured with utf8mb4 encoding.

I configured the DB and re-ran occ memories:places-setup, and it worked without any issues, Thanks!

I didn't see anywhere in the Memories documentation that utf8mb4 was needed. Just a suggestion, add a note to the docs and on the Memories admin page, and/or add a check before places-setup runs.
