### ISSUE TITLE
Recognize thumbnail not updated after removing photo

### ISSUE THREAD

**Issue by Andreaux** [pulsejet/memories#661]
**Describe the bug**
Using Memories along Recognize, if a photo is removed from a person and that photo was used for the thumbnail for the person, the person still looks like the thumbnail before removing the photo from the person and there's no way to update the thumbnail or pick another picture as the thumbnail.

**To Reproduce**
1. Recognize clusters a couple of persons
2. Pick a cluster that has a face that doesn't belong in the cluster AND Memories picked that picture as the thumbnail
3. Remove the offending picture from the cluster using "Remove from this person".
4. The thumbnail remains the other person

**Screenshots**
![Screenshot 2023-05-23 at 19 37 04](https://github.com/pulsejet/memories/assets/1387888/3f193522-aa0f-40b7-8f1c-912c6c83b04a)
![Screenshot 2023-05-23 at 19 38 00](https://github.com/pulsejet/memories/assets/1387888/6fc31d30-d122-4fbb-93be-a8928bcd8a7f)

**Platform:**
- OS: Ubuntu (official Nextcloud Docker image)
- Browser: Chrome
- Memories Version: 5.1.0
- Nextcloud Version: 26.0.1
- PHP Version: 8.1.18

**Comment by pulsejet** [comment]
Indeed this is a bug that affects all clusters (tags, faces etc.). Essentially the preview image is being cached for one day, so it'll update the next day.

**Comment by Andreaux** [comment]
Actually, this should pretty much turn into a feature request :) To be able to manually pick the index photo if you wish. That would be great.

**Comment by pulsejet** [comment]
#125 ;)

**Comment by pulsejet** [comment]
Fixed with #1071
