### ISSUE TITLE
Always Load Full Size Image does not work in public link

### ISSUE THREAD

**Issue by rhyst** [pulsejet/memories#662]
**Describe the bug**

I have the "Always load full size image" setting on. In my folders and albums this correctly loads the full image as soon as I click on them. If I create a public share link to an album or gallery and try the same thing then the full image does not load. 

**To Reproduce**
- Ensure you have toggled the "Always load full size image" setting on
- Create an folder with pictures in memories
- Create a public share link to that folder
- In another browser or private browsing visit the public share link
- Click on an image and note that it does not load the full size image

**Screenshots**

**Platform:**

- OS: Windows
- Browser: Firefox
- Memories Version: 5.1.0
- Nextcloud Version: 26.0.1
- PHP Version: 8.1.19

**Additional context**
The "Load full image on zoom" appears to work in public shares.

- Any errors in the JS console? 

```
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. [globals.js:59:15](webpack:///nextcloud/core/src/globals.js)
InvalidStateError: A mutation operation was attempted on a database that did not allow muta
```

- Any errors in the Nextcloud server logs? No

**Comment by pulsejet** [comment]
This is expected, since the "always load full image" is a user-specific setting (and public links by definition have no user). It could be possible to add a global default for this, but I'd be very careful here: this could cause huge CPU load e.g. if someone is using HEIF. The better solution here is to just increase the max preview size.

**Comment by rhyst** [comment]
My use case is a single user instance where I occasionally share links with a friend to share photos from a trip or something so for me the global setting would be useful. 

If its not something you want to add, would it be possible for me to patch my own instance to do this? I am comfortable with php and js so would be happy to do this if you could point me at the relevant files.

I'm curious as to what about the setting causes CPU load? I would expect it to replace the preview link with a link directly to the original file which doesn't seem like something that should cause the server issues. But I am probably missing a lot.

**Comment by rhyst** [comment]
Also is this something you would accept a PR for?

**Comment by pulsejet** [comment]
> If its not something you want to add, would it be possible for me to patch my own instance to do this? I am comfortable with php and js so would be happy to do this if you could point me at the relevant files.

`src/viewer/PsImage.ts`. Or just change `highSrcCond` in `Viewer.vue`.
 
> I'm curious as to what about the setting causes CPU load? I would expect it to replace the preview link with a link directly to the original file which doesn't seem like something that should cause the server issues. But I am probably missing a lot.

If you're using an image format that the browser doesn't support (say HEIC), then it needs to be transcoded on the fly server-side. This can be very slow and expensive for large images even on very good hardware (>5s for 64MP on a EPYC).

> Also is this something you would accept a PR for?

Sure. Simplest would be a global admin level setting to always enable this option for all links and users. You probably want to look at `SystemConfigDefault.php`, `OtherController::getUserConfig`, `static-config.ts` and the typings.

Note: we _need_ to first load the larger preview before the full image for the aforementioned delay. This is the current behavior anyway.
