### ISSUE TITLE
Support for shared folders

### ISSUE THREAD

**Issue by nefh** [pulsejet/memories#664]
Hi!
I have following home NC setup:

1. One global account for my complete photo library with the structure
2. Multiple supporting accounts for family and separate groups of friends
3. Folders which are interesting for each group are being shared towards certain supporting account.
4. The supporting accounts do not have any photos on they own, every folder they see is shared folder from main account.

Memories is only asking for root folder, which is empty for each supporting account. Therefore my friends can not use your app at all.

Could you provide support also for shared folders?

**Comment by pulsejet** [comment]
It's already supported, just point Memories to the shared folder, or the folder containing the shared folders.
Also please follow the issue template.
