### ISSUE TITLE
Tag thumbnails uses photos from other users

### ISSUE THREAD

**Issue by KentaEl** [pulsejet/memories#665]
In the tag section some of the thumbnails for tags are photos from other accounts. There are no open shares between the accounts. 

The tags are auto generated from Recognise, tag thumbnails in the normal Photos are not leaked. 

It seems to me to be a pretty serious privacy leak. 

- Browser: Safari on iOS and iPadOS
- Memories Version: 5.1.0
- NextcloudPi Version: 1.52.0

**Comment by KentaEl** [comment]
Yeah, and on different devices. None of the users are admins.

**Comment by pulsejet** [comment]
Okay, do you see the thumbs from the other user if you login in a private window?

**Comment by KentaEl** [comment]
No! So probably cached images in the browser?

**Comment by pulsejet** [comment]
Yeah. Cache busting is kinda incomplete at the moment.

**Comment by KentaEl** [comment]
Okay, so I take it that it’s fine as long as the users use different devices?

**Comment by pulsejet** [comment]
Yes
