### ISSUE TITLE
Sharing original file does not work for certain file types (HEIC images and HEVC MP4)

### ISSUE THREAD

**Issue by invario** [pulsejet/memories#667]
**Platform (please complete the following information):**
NC 26.0.1 inside iocage jail - FreeBSD 13.1-RELEASE-p7 (host is TrueNAS Core 13)
Memories 5.1.0
Chrome Mobile or Desktop, FireFox Desktop or Mobile
nginx 1.22.0
PHP 8.1.12

**On Chrome Desktop or Mobile:**
JPG files work just fine as do non-HEVC MP4 files.  When I attempt to share an image that is HEIC or an HEVC MP4 and select "Original file", nothing pops up, no errors, nothing at all. Tested in Chrome Mobile (Android).  Choosing one of the other options (Reduced file size, High Res) works fine. 

**On FireFox Desktop:**
File sharing does not work at all for any images or videos. The only option presented is to share Public Link

**On FireFox Mobile:**
For any images or videos, the options are all listed, but none of them work. They all say "Cannot share this type of data"
![image](https://github.com/pulsejet/memories/assets/67800603/f3e4d5b2-f265-4aa6-817f-d6f7cd52f7e0)

**Comment by pulsejet** [comment]
Unfortunately there's nothing that can be done. Browsers simply forbid sharing certain types of content for no apparent reason.

**Comment by invario** [comment]
Bummer ... But thank you nonetheless!
