### ISSUE TITLE
After installation and configuration: Memories initialization page shown

### ISSUE THREAD

**Issue by schnillerman** [pulsejet/memories#670]
**Describe the bug**
After following the installation and configuration instructions, the initialization screen (run occ indexing command and select root folder) keeps being shown instead of the memories timeline.

**To Reproduce**

1. Install memories
2. Activate memories
3. Set root indexing directory to _/Photos_ in _Administration > memories_
4. Successfully run `docker exec -it --user www-data nextcloud php occ memories:index` (indexing output shows correct user and files being indexed)
5. Go to nextcloud memories app page

**Screenshots**
Can't get beyond this screen:
![Screenshot_20230529_234310_Chrome](https://github.com/pulsejet/memories/assets/17252473/fb61c704-c636-44a7-bd3e-244d03c9983d)

Index setting:
![Screenshot_20230529_235003_Chrome](https://github.com/pulsejet/memories/assets/17252473/3e6ad5ef-7145-4b49-a008-4ff0ac3cadde)

**Platform:**

- OS: linux/docker
- Browser: Chrome
- Memories Version: 5.1.0
- Nextcloud Version: 26.0.1
- PHP Version: 8.1.19

**Comment by pulsejet** [comment]
What happens when you click the blue button?

**Comment by schnillerman** [comment]
I can choose a folder. But choosing _Photos_ doesn't do anything.

**Comment by pulsejet** [comment]
Anything in JS console?

**Comment by pulsejet** [comment]
I'll also suggest trying the latest unstable version (v5.2.0-alpha.3)

**Comment by schnillerman** [comment]
> I'll also suggest trying the latest unstable version (v5.2.0-alpha.3)

Thanks, will try.

**Comment by schnillerman** [comment]
> Anything in JS console?

I'll update this as soon as I can check.

**Comment by pulsejet** [comment]
> > Anything in JS console?
> 
> I'll need to find out how to access the JS console in docker.

The JS console is in your browser.

**Comment by schnillerman** [comment]
> ies%2F".

Sorry for being slow - I posted the console content in https://github.com/pulsejet/memories/issues/670#issuecomment-1568354429

**Comment by schnillerman** [comment]
I removed the app with the official reset instructions and re-installed with occ. This took 15-20 minutes (!!!) - running a fresh, empty nextcloud on my Synology DS918+ docker.

After that, it seems to work.

Right now executing

- `occ memories:places-setup` (taking a while, 3% after 4 minutes
- `occ memories:index`
