### ISSUE TITLE
Metadata Date doesn't work for some months

### ISSUE THREAD

**Issue by daufinsyd** [pulsejet/memories#671]
**Describe the bug**
Hi, I want to change the metadata date of some pics to April but whatever I as month number, I never can get April but only March or May (as seen in the screenshots).

Actually none of these month are choosable:
February, April, June, September, November

**To Reproduce**
- Change metada date of some pics.

**Screenshots**
Works
![image](https://github.com/pulsejet/memories/assets/1218113/0e9c9b5e-9cd8-4964-8f93-5fb7fba23d08)
Doesn't work
![image](https://github.com/pulsejet/memories/assets/1218113/8d007730-f861-4f81-a03c-176fb6f1bc5f)
Works
![image](https://github.com/pulsejet/memories/assets/1218113/95d6b881-a445-4652-9def-862594c46847)
Doesn't work
![image](https://github.com/pulsejet/memories/assets/1218113/045d835e-0750-487d-ac75-c8a85fdedfe8)

**Platform:**

- OS: MacOS
- Browser: Firefox
- Memories Version: 5.1.0
- Nextcloud 26.0.2
- PHP Version: 8.1

**Additional context**

- Any errors in the JS console? No
- Any errors in the Nextcloud server logs? No

**Comment by pulsejet** [comment]
1. Are you positive there's nothing in the JS console? 
2. What happens if you change the time _after_ changing the date to April?
3. What happens if trying to edit a single photo?

**Comment by daufinsyd** [comment]
Here is what I did

1. Open the JS console 
2. Select an image
3. click on the 3 dots
4. delete the JS logs
5. click on Edit Metadata
6. Change the month multiple times
There is nothing "Get notification data" and "polling interval updated to 3000".

Now it seems that as you suggested only one picture was faulty (when selecting the others there was no issue).

I hence try to force the metadata on this faulty image and now it does work.
I can't find a pattern (eg not only even months were concerned) and the 24th is not the latest day of the month.

Tho if entering 31 (or even more) it does changes the month (4. 31 = 1 mai ; 4. 32 = 2 mai ; 4. 0 = 31 march) but I saw another ticket about this issue.

I think we can close the issue if you're ok with that, since I'm not able to reproduce the issue anymore. Thank you for your time and sorry for not being able to provide more info

**Comment by siccovansas** [comment]
I have to same issue. I just took a new picture and put in on Nextcloud. As seen in the video I can't change the month to:

- February
- April
- June
- September
- November

[Screencast from 31-10-23 14:10:04.webm](https://github.com/pulsejet/memories/assets/696839/6d41643c-de8a-43aa-aa81-12719fd006ef)

**Comment by pulsejet** [comment]
Thanks @siccovansas that was super helpful. This should be fixed now.
