### ISSUE TITLE
Make it possible to add exif data on the right sidebar with the Metadata app

### ISSUE THREAD

**Issue by Akruidenberg** [pulsejet/memories#68]
Nextcloud has an metadata app to display metadata of an photo on the right sidebar. Is to possible to integrate this function into memories? 
Also, integration with an map in the sidebar would also be nice.

**Comment by pulsejet** [comment]
Not sure this is even possible. Sidebar needs the files app to work right.

For the map "integration", this would be basically a link unless I'm missing something.

**Comment by meichthys** [comment]
Yes, i believe the map option would be a link - That's how the default photos app handles it.

**Comment by meichthys** [comment]
I'll create a separate issue for the maps feature request since it's somewhat unrelated to this issue.

**Comment by pulsejet** [comment]
Metadata can now be edited with v4.9.0
