### ISSUE TITLE
The column 'w' on table 'oc_memories' already exists.

### ISSUE THREAD

**Issue by SidM01** [pulsejet/memories#683]
I tried to install Memories, if I look under apps it's installed. However, if I want to activate it, the hint comes up "The column 'w' on table 'oc_memories' already exists." and the app remains disabled. Unfortunately I can't do anything with the error message.

[Here](https://github.com/pulsejet/memories/issues/106) @xtream1101 describes the same error.
What do you mean by "You probably need to drop the memories table and remove the related migrations entries in oc_memories first"
Where should I look?

- OS: Unraid Docker
- Browser: Chrome
- Memories Version: 5.1.0 via the nextcloud app page
- Nextcloud Version: 26.0.2
- PHP Version: 8.2.6
- MySQL: 10.11.3

**Comment by pulsejet** [comment]
https://memories.gallery/troubleshooting/#reset

**Comment by SidM01** [comment]
Hello,

After a long search I found the reset as you posted last night.

I then executed all the commands and then tried again to install memories (also using occ app:install memories)
Unfortunately I still get the same error message.
![1203F282-631A-49BB-9474-09D3ECA80E2A](https://github.com/pulsejet/memories/assets/85868103/43dbbcde-9062-4b66-8488-111d4fa6e8b1)

**Comment by pulsejet** [comment]
Migrations we're revamped in 5.x. this shouldn't happen anymore
