### ISSUE TITLE
Old video files with wrong metadata

### ISSUE THREAD

**Issue by duckdany** [pulsejet/memories#687]
**Describe the bug**
After upload old video files with correct metadata memories shows them with the upload date. Nextcloud Photos app shows them with the correct date and time. If I edit the videos metadata in memories, then memories will show with the correct date, but Photos shows them with modification (today) date and time.

**To Reproduce**
Upload an old video (2017 and 2018)

**Screenshots**
-

**Platform:**

- OS: [e.g. iOS] raspberry pi OS
- Browser: [e.g. Chrome, Safari] Safari macOS, Firefox Windows
- Memories Version: [e.g. 4.1.0] 5.1.0
- Nextcloud Version: [e.g. 25.0.6] 26.0.2
- PHP Version: [e.g. 8.1] 8.2.6

**Additional context**
I tried to change the metadata on desktop and then reuploaded the videos, but the same bug came up.

- Any errors in the JS console? NO
- Any errors in the Nextcloud server logs? NO

**Comment by pulsejet** [comment]
Do you have a sample?

**Comment by duckdany** [comment]
Yes, of course. How can I share it with you!
Thanks!

**Comment by pulsejet** [comment]
E.g. a google drive link perhaps. If you don't want to share it publicly, you can DM me at Discord.

**Comment by duckdany** [comment]
https://1drv.ms/v/s!AnzGnZCcRCbJj88F7Ctl6SP9mvHK2A?e=PJJ8Rk

This is one of my videos that not has the problem.

**Comment by pulsejet** [comment]
> This is one of my videos that not has the problem.

Does this video **not** have the problem? Need a sample video which has the problem ...

**Comment by pulsejet** [comment]
Hmm this is a mess ... were these videos modified earlier with some other tool? `Creation Date` is not a standard QuickTime tag AFAIK.

```
File Modification Date/Time     : 2023:06:10 10:16:17-07:00
File Access Date/Time           : 2023:06:10 10:18:34-07:00
File Inode Change Date/Time     : 2023:06:10 10:18:34-07:00
Create Date                     : 2023:06:09 03:47:24
Modify Date                     : 2023:06:09 03:47:24
Track Create Date               : 2023:06:09 03:47:24
Track Modify Date               : 2023:06:09 03:47:24
Media Create Date               : 2023:06:09 03:47:24
Media Modify Date               : 2023:06:09 03:47:24
Creation Date                   : 2017:12:08 06:16:39
```

**Comment by duckdany** [comment]
> > This is one of my videos that not has the problem.
> 
> Does this video **not** have the problem? Need a sample video which has the problem ...

Sorry. I don’t know why I wrote that. Sorry. This video has the problem too. In memories the date is when I upload it. In photos it has a correct date. If I edit metadata in memories, in photos it will be shown today.

**Comment by duckdany** [comment]
> Hmm this is a mess ... were these videos modified earlier with some other tool? `Creation Date` is not a standard QuickTime tag AFAIK.
> 
> ```
> File Modification Date/Time     : 2023:06:10 10:16:17-07:00
> File Access Date/Time           : 2023:06:10 10:18:34-07:00
> File Inode Change Date/Time     : 2023:06:10 10:18:34-07:00
> Create Date                     : 2023:06:09 03:47:24
> Modify Date                     : 2023:06:09 03:47:24
> Track Create Date               : 2023:06:09 03:47:24
> Track Modify Date               : 2023:06:09 03:47:24
> Media Create Date               : 2023:06:09 03:47:24
> Media Modify Date               : 2023:06:09 03:47:24
> Creation Date                   : 2017:12:08 06:16:39
> ```

What is the standard quicktime tag? I imported all my media files from onedrive to icloud once. 
I checked these videos in onedrive, icloud and they are at the correct date and time.
I don’t know what happend. So I think I lost the date. How could I modify them so? Thank you!

**Comment by pulsejet** [comment]
The `Create Date` is the usual tag. Does that time ring any bells? E.g. did you download this particular file from somewhere on Jun 9 at 4AM?

**Comment by duckdany** [comment]
> The `Create Date` is the usual tag. Does that time ring any bells? E.g. did you download this particular file from somewhere on Jun 9 at 4AM?

I just downloaded from icloud to upload to my new nextcloud server. But I imported them from onedrive to icloud firstly in 2018. 

I uploaded this video to onedrive now and it is at 2017. I don’t know how can I modify them to be good in nextcloud

**Comment by pulsejet** [comment]
The two tags should definitely not be inconsistent, so something messed with the videos. AFAIK Google does this to save space, maybe Apple too.

You can copy over the tag into the correct field with exiftool

```bash
exiftool "-CreateDate<CreationDate" <filename-or-directory>
```

**Comment by pulsejet** [comment]
Note you need to reindex after doing this.

occ files:scan

occ memories:index

**Comment by ThowZzy** [comment]
Hello, I have a same issue, I think I have some videos that did not have any metadata for the date, but something like RSYNC added the current date to it, so I now have really old videos and photos dated to today. And when I try to change this date in Memories, it doesn't change to the date I set and gets updated to the current date and time.
