### ISSUE TITLE
Nextcloud 27 compatibility

### ISSUE THREAD

**Issue by xkill** [pulsejet/memories#693]

**Comment by EVOTk** [comment]
memories is compatible with NC27

**Comment by hxchtiewei** [comment]
I have the issue described in #620 
v5.1.0 & NC27

**Comment by BWibo** [comment]
I would like to do some testing with the Alpha version. How can I install an Alpha version?
Is this documented anywhere? I'm not exactly sure where to copy what stuff (entire repo, some compiled files+folders?)
Thx in advance.

**Comment by BWibo** [comment]
Ah my bad, I found it. Enabling the Unstable channel does the trick to show alpha versions in the app store.
Still might be worth mentioning this in the docs to make it easier for people to do beta testing.

![grafik](https://github.com/pulsejet/memories/assets/7643434/08443f05-7b7a-4f06-99c0-a5b5db5c2121)

**Comment by BWibo** [comment]
Yes, me too. Trial and error sometimes helps. :-)

**Comment by AndyXheli** [comment]
Hi @pulsejet Just wnated to see if theres a release date in mind for NC 27 ?

**Comment by pulsejet** [comment]
@AndyXheli as soon as I get home basically 😄 I'm traveling, and for another couple of weeks.

**Comment by AndyXheli** [comment]
Enjoy your time!! 🙂

**Comment by pulsejet** [comment]
5.2.0
