### ISSUE TITLE
Add an option to hide Nextcloud photos

### ISSUE THREAD

**Issue by quentinus95** [pulsejet/memories#694]
**Is your feature request related to a problem? Please describe.**
Following my experimentation, I have found Memories to be more feature complete and reliable than Nextcloud photos. Because the Memories albums feature requires Nextcloud photos to be installed, it creates confusion for users where “to find their photos, they should go into Memories and _not_ into photos”.

**Describe the solution you'd like**
Having an option in Memories administration to hide Nextcloud photos would allow hiding Nextcloud photos, thus removing confusion. Minimum viable features would include:
- ability to hide Nextcloud photos from all navigation pages

Nice to have but maybe hard to maintain:
- redirect features that target the Nextcloud photos pages to Memories

**Describe alternatives you've considered**
Using custom CSS selectors is an option, but there are always edge cases (e.g., different menus on mobile and desktop) that won't prevent photos from being displayed. There are third-party add-ons to customize the menu, but they are often not as well maintained as Memories.

**Additional context**
Because Memories is a replacement app for Nextcloud photos, maybe having this configuration button to enable the replacement of the original application would make sense.

**Comment by EVOTk** [comment]
Hello,
You can use Custom Menu for this :)

https://apps.nextcloud.com/apps/side_menu

**Comment by quentinus95** [comment]
Thanks for your answer! I listed this in the alternatives I have considered. However, for instance for `side_menu`, it is one more dependency for just a simple use case of hiding an item in the menu. Because the aim of Memories is to replace Nextcloud photos with a better alternative, maybe it should provide an option for this (plus it could handle some additional edge cases, redirections, integration replacements, etc.).

**Comment by Gymnae** [comment]
That would be an offensive move towards the first party apps, if technically even possible.

The option to remove "clutter" is something the Nextcloud devs could integrate. But since this app relies on functionality Photos delivers and because Photos is deeply integrated into Nextcloud, @EVOTk's solution is probably the best. I'm using that route and it works. 

For certain users I made Memories the default app, and it improved their experience considerably.

**Comment by quentinus95** [comment]
Because the app is a Nextcloud photos replacement, I would not be chocked if it provided the optional feature of actually, literally replacing it. Also, it would be more grandma compliant.

**Comment by Gymnae** [comment]
As stated above, grandma compliance can be achieved with side_menu. Just configure her account with memories as default app, hide photos app. Done.

If you have multiple users wanting to simply consume your media, then create a public share to an album or folder, slap a password on that share, give it a proper name with the custom share name app and spread the link and password.

Replacing the Photos app is not something this app can or should do. Even if possible, it might only lead to private APIs with the 1st party and degraded 3rd party integration.

**Comment by pulsejet** [comment]
> That would be an offensive move towards the first party apps, if technically even possible.

This.

1. The Photos app continues to be developed actively by the Nextcloud team, and I don't want to undermine their efforts.
2. This is even more important considering this app directly utilizes features from Photos, e.g. Albums.

Hiding the Photos app doesn't have anything to do with this app (it's a cosmetic UI change that's global to Nextcloud). So `side_menu` is indeed the right way here.

**Comment by quentinus95** [comment]
Thanks, I'll consider this alternative

**Comment by matiasdelellis** [comment]
Hi, A small contribution... 😉 
It caught my attention that this is never implemented, but it is true that there is no "nice" way to do it.

So, here's an alternative that I use...

A little patch:
```
diff --git a/lib/Listeners/BeforeTemplateListener.php b/lib/Listeners/BeforeTemplateListener.php
index fd8f20b7..373556fe 100644
--- a/lib/Listeners/BeforeTemplateListener.php
+++ b/lib/Listeners/BeforeTemplateListener.php
@@ -37,6 +37,8 @@ class BeforeTemplateListener implements IEventListener
 
     public function handle(Event $event): void
     {
+        \OCP\Util::addScript(Application::APPNAME, 'memories-hide-photos');
+
         if (null !== $this->session->get(PostLogoutListener::CLEAR_CACHE_KEY)) {
             $this->session->remove(PostLogoutListener::CLEAR_CACHE_KEY);
             \OCP\Util::addScript(Application::APPNAME, 'memories-hooks-clear-cache');
```

... and a little script.
```
[matias@nube js]$ cat memories-hide-photos.js
document.addEventListener('DOMContentLoaded', () => {
    setTimeout(() => {
        document.querySelector('[data-app-id="photos"]').style.display = "none";
    }, 500);
});
```

That's all my friends, but don't expect it to be officially added. 😜

**Comment by matiasdelellis** [comment]
Maybe we have to use `setInterval` due the menu is dynamically reconstructed, for example, when you rotate the mobile screen.

```
document.addEventListener('DOMContentLoaded', () => {
    setInterval(() => {
        document.querySelector('[data-app-id="photos"]').style.display = "none";
    }, 500);
});
```
And note that `document.querySelector('[data-app-id="photos"]')` may be null during that reconstruction.. 🤔 

Nothing serious... I just wanted to write as easy as possible. 😅

**Comment by matiasdelellis** [comment]
Well, small application that only adds that script and nothing else.. 😅 

[hide-photos.tar.gz](https://github.com/pulsejet/memories/files/12466350/hide-photos.tar.gz)

So you don't have to edit any application.... 🤔 😉

**Comment by matiasdelellis** [comment]
Sorry for the spam... But there was a much easier way.. 🤦🏻‍♂️ 😅 

```
.app-menu-entry[data-app-id="photos"] {
    display: none !important;
}
```

So, new version with that..
[hide-photos.tar.gz](https://github.com/pulsejet/memories/files/12470123/hide-photos.tar.gz)


It's still ugly, but not that ugly.. 😅 😉

**Comment by MrRinkana** [comment]
Note for users that are also looking to deduplicate their app bar, the code provided by @matiasdelellis ([this](https://github.com/pulsejet/memories/issues/694#issuecomment-1698246226)) can be simply put into the custom css app if you already are using it, such that you don't have to maintain another app trough updates.

**Comment by pulsejet** [comment]
Just a note: this'll only hide Photos on desktop. For mobile you'll need something like (at least on 28)

```css
.app-menu-entry[data-app-id="photos"], .app-menu-popover-entry:has(a[href*="apps/photos"]) {
    display: none !important;
}
```

**Comment by MrRinkana** [comment]
It seems the `data-app-id="photos"` has been removed with nc 30? At least it stopped working for me as I updated from 29 to 30.0.4...

Using this works however:

```css
.app-menu-entry:has(a[href*="apps/photos"]), .app-menu-popover-entry:has(a[href*="apps/photos"]) {
    display: none !important;
}
```

_(Added in custom css app)_
