### ISSUE TITLE
Wrong display name when sharing albums

### ISSUE THREAD

**Issue by quentinus95** [pulsejet/memories#695]
**Describe the bug**
I'm allowing myself to describe this as a bug but feel free to re-qualify as a feature request if you do not agree. When sharing an album, Memories shows a selection list that displays what I believe to be the user identifier while I would expect the display name (and a fallback to the identifier if empty). The current displayed text in the list matches the identifier I see in the URL of the profile of a user, instead of the display name that is displayed in the top banner of that profile.

This creates issues when the user identifier is generated, and is a random string. Note as a mitigation that entering the display name of a user does filter the list properly. You still see the identifier, though.

**To Reproduce**
Open an album and click on the share button, click to enter the name of a user, the list contains identifiers instead of display names.

**Platform:**

- OS: Nextcloud Docker
- Browser: Recent chrome
- Memories Version: 5.1
- Nextcloud Version: 26
- PHP Version: N/A

**Comment by pulsejet** [comment]
Fixed in next release.
