### ISSUE TITLE
Folders with special characters in name giving "Folder Not Found" Error

### ISSUE THREAD

**Issue by ChildLearningClub** [pulsejet/memories#696]
**Describe the bug**

any folders with special characters [Example: | or other languages 納骨] are giving the error "Folder Not Found" where they show up in the Photos app

**To Reproduce**

create a folder with special characters and then attempt to open that folder in the Memories app

**Screenshots**

**Platform:**

- OS: Windows
- Browser: Brave
- Memories Version: 5.1.0
- Nextcloud Version: 27
- PHP Version: 8.2.7

**Additional context**

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

**Comment by pulsejet** [comment]
Fixed in 5.2. You can upgrade to the alpha if you like; haven't had enough time to test for a stable release yet.

**Comment by ChildLearningClub** [comment]
Okay, thank you Varun.
