### ISSUE TITLE
metadata editing leaves a duplicate photo around

### ISSUE THREAD

**Issue by eleith** [pulsejet/memories#699]
**Describe the bug**

after editing metadata only, i'm left with copies of every image in the form of `image_name.jpg_origional` thus duplicating storage memory of all photos that were edited

**To Reproduce**

1. batch edit metadata of a few files
2. notice that duplicates of each photo exists of the form `photo_name.jpg_original`

**Platform:**

- OS: linux
- Browser: firefox
- Memories Version:  v5.1.0
- Nextcloud Version: 26.0.2
- PHP Version: 8.1

**Additional context**

i'm not positive this is coming from memories, but rather it happens after editing metadata. i also have recognize and image preview plugins installed. currently have not been able to narrow down what is creating these files, but rather what actions lead to these being created.

my guess is these are temporary copies that are intended to be cleaned up once editing is successful. however, they don't seem to ever be cleaned up.

even if i delete the original file, the duplicate still stays around...

**Comment by pulsejet** [comment]
I noticed this too, not really sure where it's coming from. Could be the file versions app, but this definitely needs investigation.

**Comment by eleith** [comment]
the [versions app ](https://docs.nextcloud.com/server/26/user_manual/en/files/version_control.html) should only be creating folders in `data/[user]/files` so i wouldn't expect a full copy of a photo to be placed right next to it.

**Comment by eleith** [comment]
i'm seeing this on a externally mounted drive (just another folder outside of nextcloud). i wonder if this happens on internal nextcloud folders...

**Comment by rhatguy** [comment]
Doesn't exiftool normally create files with the _original suffix if you don't tell it to overwrite the original?

https://exiftool.org/forum/index.php?topic=5514.0

**Comment by eleith** [comment]
thanks @rhatguy

i can confirm that changing

https://github.com/pulsejet/memories/blob/master/lib/Exif.php#L15

to

```php
    private const EXIFTOOL_ARGS = ['-delete_original!', '-api', 'QuickTimeUTC=1', '-n', '-U', '-json', '--b'];
```

results in no original copies being left around. please note the exclamation mark as part of the flag. without it, exiftool will prompt for confirmation.

**Comment by pulsejet** [comment]
Huh. These args are only used for reads... The setExif call is definitely missing this argument though.

**Comment by eleith** [comment]
@pulsejet i tried a few more times and i'm seeing the same results, adding the flag results in no extra files being created.

but if these are indeed used only for reads, then this outcome is confusing...

**Comment by pulsejet** [comment]
A guess: the flag is deleting the `_original` files during the re-scan, that is triggered post-edit.
