### ISSUE TITLE
Hybrid cron Background Transcoding and Current on The Fly Transcoding 

### ISSUE THREAD

**Issue by ChildLearningClub** [pulsejet/memories#700]
**Is your feature request related to a problem? Please describe.**

Many systems lack the ability to quickly transcode video, but given time, transcoding can be performed as a background job on the server.

**Describe the solution you'd like**

A server side cron job that will automatically transcode videos. Optionally in settings this can be set to all uploaded videos or possible just ones that are added to an album or that are shared? The transcoded video would be a copy in a separate folder and if it exists would be what would be served up to the user when playing back the video. The ffmpeg transcoding quality could be set to the default transcoding qualify set by the Nextcloud user in the memories backend, and only if the user viewing the video chooses something other then that default will the video switch over to on the fly transcoding. Of course pre-transcoded videos could be created for multiple video quality settings, but that may be excessive? I would image that the Nextcloud user would set the default transcoding settings to appropriately match their bandwidth. 

When it comes to downloading however it would pull/download the original or an available transcoded copy as an option to the user.

Storage is generally not as big an issue as bandwidth and hardware I believe, so having this ability I think would really boost the user experience.   

**Additional context**

I ran into a similar issue with Piwigo and had created a script that I will share below if it is at all helpful in getting something started. I'm actually pretty proud of it, since I really only had a basic idea of what I was doing :). Anyway, it worked well, and I would like it if others could benefit from it. 

My /etc/crontab

```
# PIWIGO INOTIFY WATCH ON BOOT:
@reboot         root    sleep 60; /media/drive/container-volumes/piwigo/piwigo.sh
```

piwigo.sh

```
#!/bin/bash

# PIWIGO VIDEO CONVERSION SCRIPT

inotifywait -m /media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/upload/* -e create -e moved_to |
while read path action file; do
sleep 600 && cd /media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/upload/ \
&& find ./ -type f \( -iname '*.mp4' -o -iname '*.mov' -o -iname '*.m4v' \) -mmin +1 -exec cp -pn --parents \{\} /media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/Originals \; \
&& find ./ -type f -mtime -1 \( -iname '*.mp4' -o -iname '*.mov' -o -iname '*.m4v' \) -mmin +1 -exec mv -n {} /media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/Originals/temp \; \
&& cd /media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/Originals/ \
&& find ./ -type f -iname '*.mov' -exec bash -c 'ffmpeg -i "/media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/Originals/{}" -c:v libx264 -c:a aac -crf 28 -vf scale=-2:1080 -movflags faststart -preset slow -n "/media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/upload/{}"' \; \
&& find ./ -type f -iname '*.mp4' -exec bash -c 'ffmpeg -i "/media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/Originals/{}" -c:v libx264 -c:a aac -crf 28 -vf scale=-2:1080 -movflags faststart -preset slow -n "/media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/upload/{}"' \; \
&& find ./ -type f -iname '*.m4v' -exec bash -c 'ffmpeg -i "/media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/Originals/{}" -c:v libx264 -c:a aac -crf 28 -vf scale=-2:1080 -movflags faststart -preset slow -n "/media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/upload/{}"' \; \
; chown -R www-data:www-data /media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/ \
&& docker exec --user www-data nextcloud php occ files:scan --path=/nextcloud_user/files/Piwigo/; done
done
```

and similar clean up script:

My /etc/crontab

```
# PIWIGO CLEANING SCRIPT:
0 4     * * *   root    /media/drive/container-volumes/piwigo/piwigo-clean.sh
```

piwigo-clean.sh

```
#!/bin/bash

# PIWIGO CLEANING SCRIPT


cd /media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/upload/ \
&& find ./ -type f \( -iname '*.mp4' -o -iname '*.mov' -o -iname '*.m4v' \) -mmin +1 -exec cp -pn --parents \{\} /media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/Originals \; \
&& find ./ -type f -mtime -1 \( -iname '*.mp4' -o -iname '*.mov' -o -iname '*.m4v' \) -mmin +1 -exec mv -n {} /media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/Originals/temp \; \
&& cd /media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/Originals/ \
&& find ./ -type f -iname '*.mov' -exec bash -c 'ffmpeg -i "/media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/Originals/{}" -c:a copy -crf 28 -vf scale=-2:1080 -movflags faststart -preset slow -n "/media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/upload/{}"' \; \
&& find ./ -type f -iname '*.mp4' -exec bash -c 'ffmpeg -i "/media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/Originals/{}" -c:v libx264 -c:a aac -crf 28 -vf scale=-2:1080 -movflags faststart -preset slow -n "/media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/upload/{}"' \; \
&& find ./ -type f -iname '*.m4v' -exec bash -c 'ffmpeg -i "/media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/Originals/{}" -c:v libx264 -c:a aac -crf 28 -vf scale=-2:1080 -movflags faststart -preset slow -n "/media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/upload/{}"' \; \
; chown -R www-data:www-data /media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/ \
&& docker exec --user www-data nextcloud php occ files:scan --path=/nextcloud_user/files/Piwigo/ \
&& find /media/drive/container-volumes/nextcloud/data/nextcloud_user/files/Piwigo/Originals/temp/ -type f -mtime +1 -exec rm -f {} \; \
&& docker exec --user www-data nextcloud php occ files:scan --path=/nextcloud_user/files/Piwigo/
```
 

[PiGAllery2](https://github.com/bpatrik/pigallery2) might also be a good reference as I think something is implement in there to do just this.

**Comment by pulsejet** [comment]
#232 

This would be a great addition, but probably not that easy to implement. Might also need to think about how to store these transcodes. They should, for example, be deleted if the original is deleted.

**Comment by ChildLearningClub** [comment]
I searched to try and make sure not to create a duplicate and didn’t see #232, my apologies, I will close this. Yes, those are some very valid points.

 If I’m not mistaken I think Piwigo does something like this for different photo resolutions, and adds a string to the end of the image file name and then must have them linked within the database. But yes, that alone would take some work to do and is only part of what would be required to implement it :(

**Comment by pulsejet** [comment]
This brings an intersting thought to mind: I wonder if Nextcloud clears the previews if an _image_ is deleted; I doubt this is the case.

**Comment by ChildLearningClub** [comment]
Yeah, good point, I think you are probably correct that they are not cleared.
