### ISSUE TITLE
Select range of photos with shift key

### ISSUE THREAD

**Issue by tincanfury** [pulsejet/memories#704]
**Describe the solution you'd like**
It would be great to be able to select a range of photos by selecting the first photo and then shift-selecting a second photo and having the interface select all the photos in-between.

**Comment by pulsejet** [comment]
This is already implemented. Click on a select icon, then shift+click inside **the body** of another photo **after** it. (not on the select icon)

**Comment by tincanfury** [comment]
wasn't working for me on 26.0.1, upgraded to 26.0.3 after submitting this, and it started working, sorta. It does seem to be finicky, I need to play with it a little more to see if I can figure out what gets it to work, and when is it that it fails.

**Comment by pulsejet** [comment]
You could be trying to select too much at once. Can't do more than 100 or so in one click (but there's no cap on how many clicks)

**Comment by tincanfury** [comment]
ok. playing around it is working now, and like you said shift+click inside the body of the other photo, and not the selection icon. I was probably trying to use the selection icon previously and not just clicking inside the body.

Question: why the functional difference between the selection icon vs the thumbnail body? Is there some other operational functionality when pressing the shift button while clicking?

**Comment by quentinus95** [comment]
I faced this issue as well when I used Memories for the first time. I now tend to tell anyone using it about this behavior. Maybe it could be nice that clicking on the image body or the checkbox both works, as I see I'm not the only one making that mistake.

**Comment by pulsejet** [comment]
> I faced this issue as well when I used Memories for the first time. I now tend to tell anyone using it about this behavior. Maybe it could be nice that clicking on the image body or the checkbox both works, as I see I'm not the only one making that mistake.

This is the behavior now.
