### ISSUE TITLE
Albums can't load (500): SQL exception

### ISSUE THREAD

**Issue by timdahlmanns** [pulsejet/memories#705]
**Describe the bug**
Albums request fails with 500 (`apps/memories/api/clusters/albums?t=3`)
```json
{"message":"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 'nextcloud.pa.name' isn't in GROUP BY"}
```

**To Reproduce**
- Open the album view in memories

**Platform:**

- OS: Nextcloud server runs in an aarch64 kubernetes cluster with external mariadb galera database
- Browser: Firefox
- Memories Version: 5.1.0
- Nextcloud Version: 26.0.3
- PHP Version: 8.2.7

**Comment by pulsejet** [comment]
It won't work with `ONLY_FULL_GROUP_BY` set in the SQL mode

**Comment by timdahlmanns** [comment]
Thx, fixed it :+1:
