### ISSUE TITLE
Longitude sign lost from coordinates

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#706]
**Describe the bug**
Similar to #533 , the longitude value is supposed to be negative, but it is saved as positive after being uploaded from my Pixel7 via the Nextcloud mobile app.

**To Reproduce**
Upload 

**Screenshots**
![image](https://github.com/pulsejet/memories/assets/10717998/02885114-59ca-4391-a30e-a1290f4c762d)
![image](https://github.com/pulsejet/memories/assets/10717998/0d113040-d378-469b-9b0d-fcb899bad4cf)

**Comment by pulsejet** [comment]
Are you on the latest alpha?

**Comment by pulsejet** [comment]
Seems like something not related to memories; the image contains these coordinates

![image](https://github.com/pulsejet/memories/assets/10709794/877af984-9248-419b-8f7d-c659261568c2)
