### ISSUE TITLE
Feature Request: Batch Rotate

### ISSUE THREAD

**Issue by jtrees** [pulsejet/memories#707]
**Is your feature request related to a problem? Please describe.**
Sometimes there are lots of files that need to be rotated. Currently doing this in the app is tedious and time-consuming.

**Describe the solution you'd like**
1. Select all photos that need rotating.
2. Select "Rotate" entry in menu.
3. Choose rotation details (e.g. 90deg clockwise).
4. Confirm.
5. Celebrate!

**Describe alternatives you've considered**
Declare the feature out-of-scope. Suggest that users do this locally with other tools.

**Additional context**
- I don't know if rotation is best performed via meta-data or actual image manipulation.
- Perhaps some kind of backup scheme should be considered (e.g. keep original files lying around somewhere else).
- In any case, the default behaviour should be to (seemingly) replace the existing files without requiring the user to manually specify a new file name.

**Comment by randyheydon** [comment]
This looks like it was implemented with 8c16eecc11614c8ef568c422bfaa1d965ab8f2bf.  I think this request can be closed.

**Comment by jtrees** [comment]
Ooh, nice. I just tried it out. Thanks!
