### ISSUE TITLE
go-vod external transcoder does not match

### ISSUE THREAD

**Issue by guydelarea** [pulsejet/memories#709]
**Describe the bug**
go-vod failed test: version does not match 0.1.7 <==> 0.1.1.

**To Reproduce**
Install go-vod as shown https://github.com/pulsejet/memories/wiki/HW-Transcoding

**Screenshots**
![image](https://github.com/pulsejet/memories/assets/87260011/a93666f5-eb77-463d-995d-e7f7dd7e8bbd)

**Platform:**

- OS: ubuntu-server-22.04
- Browser: Chrome
- Memories Version: 5.10
- Nextcloud Version:  26.0.1
- PHP Version: 8.1.19
- go-vod docker image build from go-vod github.

**Additional context**
i tried to build go-vod from tag 0.1.1 (https://github.com/pulsejet/go-vod/tree/0.1.1) but it still does not work.

go-vod logs:
`&{Configured:true Bind::47788 FFmpeg:/usr/local/bin/ffmpeg FFprobe:/usr/local/bin/ffprobe TempDir:/tmp/go-vod ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 S ││ treamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}`

**Comment by pulsejet** [comment]
> **Additional context** i tried to build go-vod from tag 0.1.1 (https://github.com/pulsejet/go-vod/tree/0.1.1) but it still does not work.

Not clear. Do you get a different error in admin or the transcoding didn't work?

**Comment by guydelarea** [comment]
did a fresh install and for some reason all is working now with 0.1.1 :)
still has a problem with Hardware Transcoding using CUDA but i think it is not related to here.
