### ISSUE TITLE
Merging faces modal empty

### ISSUE THREAD

**Issue by illnesse** [pulsejet/memories#71]
![image](https://user-images.githubusercontent.com/40355982/196140885-aec15204-5d0f-480d-893b-c9d133d5ab52.png)

Well it's not empty but the dom elements inside are 0x0 since last app update

![image](https://user-images.githubusercontent.com/40355982/196141479-3fb583eb-8977-4e2f-96dd-bf12578886ca.png)
![image](https://user-images.githubusercontent.com/40355982/196141612-9d630b2f-4e49-4862-bd04-c8f3d242050f.png)

**Comment by pulsejet** [comment]
Version?

**Comment by illnesse** [comment]
Sorry,  4.3.0-alpha.2 via app store

![image](https://user-images.githubusercontent.com/40355982/196203265-634b788f-091b-416d-bdbc-33d47dfa72ef.png)

yep, that white glitchy mess is the names

**Comment by pulsejet** [comment]
Hmm, what kind of perf issue do you have? Does loading the list (like the gray placeholders) take time or loading the preview photos?
