### ISSUE TITLE
Multiple bugs after upgrading to 5.2

### ISSUE THREAD

**Issue by florianwgnr** [pulsejet/memories#715]
**Describe the bug**
After upgrading to v5.2, the following bugs appear: 

1. Nextcloud Admin configuration cannot be openend. `Error: ReflectionException: Method OCA\Memories\Controller\OtherController::getSystemStatus() does not exist`
2. Shared folders like `asdf.de/apps/memories/s/8imi29AS7irHX `can be opened (images are displayed), but a `Failed to load configuration`-error is thrown. While looking at the network requests, `asdf.de/apps/memories/api/config `is requested but not found (404)

**To Reproduce**
- open admin or open shared links with Firefox or Edge

**Screenshots**
Admin-Bug:
![grafik](https://github.com/pulsejet/memories/assets/39341393/0e468520-510f-4ae9-9bcd-72fdc067876b)

Shared-folder bug:
![grafik](https://github.com/pulsejet/memories/assets/39341393/2f98b256-9205-45dc-86d0-ec07b1168092)

**Platform:**

- OS: every
- Browser: Firefox, Edge
- Memories Version: 5.2
- Nextcloud Version: 26.0.3
- PHP Version: 8.2.7

**Additional context**

- Any errors in the JS console?
![grafik](https://github.com/pulsejet/memories/assets/39341393/dd1ce421-766e-4525-867f-49340b1199e4)
 
- Any errors in the Nextcloud server logs?
![grafik](https://github.com/pulsejet/memories/assets/39341393/b8b603ee-047a-47ad-8f47-d65a9aa898b3)

**Comment by chrissi55** [comment]
Same here, see also here
-> https://help.nextcloud.com/t/after-update-to-5-2-0-get-template-error-missing-admin-php/165293

The app is completely disfunctional after update from 5.1.0 to 5.2.0

**Comment by pulsejet** [comment]
@florianwgnr @chrissi55 did you try restarting the Nextcloud server?

**Comment by florianwgnr** [comment]
> @florianwgnr @chrissi55 did you try restarting the Nextcloud server? You need an opcache bust.

Rebooting my nextcloud-container solved the issue, thanks! Maybe you could add this to your release notes as every other update worked without opcache bust.

**Comment by pulsejet** [comment]
This just happens sometimes, nothing specific to this release. Maybe worth adding a note to troubleshooting.

**Comment by chrissi55** [comment]
sadly in my case it didn't solve the prob.
I had to restore my corrupted db / memories table from dump file and re-updated via 5.1.0 zip from github -> to 5.2.0 via occ command later and THEN after a reboot i was able to come back to game again!!
Not that easy as expected.

**Comment by pulsejet** [comment]
You likely ran into multiple issues. The issue you described above is exactly that of opcache busting (some methods that exist cannot be found, since they are cached).

 Closing this.
