### ISSUE TITLE
Faces list performance

### ISSUE THREAD

**Issue by illnesse** [pulsejet/memories#72]
You obviously seem to have an eye on performance, maybe give the faces list some love too? It takes quite a while to load and behaves rather sluggish when done. It would probably involve writing thumbnail files for the faces to avoid transform css (and loading a rather large image for each cluster, i have 300+ so far, still going), so maybe that would be better handled in recognize? Or maybe use canvas to only draw the specific region of an image? Still not as fast as thumbnail files and not cache-able i guess.

**Comment by pulsejet** [comment]
I need to pin point the issue here. Is the list loading slow or scrolling is janky? In other words, I want to make sure this isn't to do with SQL.

Also out of curiosity, what's the timeline loading time like with so many photos?

**Comment by pulsejet** [comment]
6MB holy moly. No wonder it's slow.

**Comment by illnesse** [comment]
Still slow without the large ones, it just adds up if you have a few hundred clusters i guess. 

Btw what do you suggest re: 6mb previews, I believe my previewgenerator limits are set to max 512, should i set a global preview limit too? I'd still like to be able to view the full resolution files though

**Comment by pulsejet** [comment]
Perhaps this is best done server-side with imagemagick. That's guaranteed to give the best quality, since the face might be a small part of the image, so we can't use a smaller preview.

**Comment by pulsejet** [comment]
Using imagick now, so hopefully better in the next release. I'll keep you posted.

Btw just noticed your Google Photos comment. The goal of this is exactly that, so great to hear that :D

**Comment by illnesse** [comment]
Great, I'm going to build and test tomorrow. As for replacing Google photos, only thing I actually miss is albums. Once that's implemented, Memories should totally be the default photos app for nextcloud imo.

**Comment by illnesse** [comment]
Amazing, that fixed it, it's super fast and merging clusters works like a charm now. 
Maybe add some background-clip: content-box; & object-fit: cover; like in the timeline?

**Comment by pulsejet** [comment]
> I just noticed some faces appear to be a little stretched/squeezed vertically (the actual image),
> doesn't bother me, but let me know if you need an example source image.

Screenshot?

**Comment by pulsejet** [comment]
Wait maybe I got it wrong. Do you mean the server-sent image is stretched?

**Comment by illnesse** [comment]
> Wait maybe I got it wrong. Do you mean the server-sent image is stretched?

yes, some examples: 
![image](https://user-images.githubusercontent.com/40355982/196471916-e1abb454-61a5-4915-a168-cd552cc8d22f.png)
![image](https://user-images.githubusercontent.com/40355982/196472259-cd010dac-c982-4376-a82d-e74495eab8e1.png)
![image](https://user-images.githubusercontent.com/40355982/196472364-c4de1d94-2f56-4464-b591-196260c81967.png)
![image](https://user-images.githubusercontent.com/40355982/196472887-a448d7a3-0b46-4614-9f71-b38389a2e711.png)

**Comment by pulsejet** [comment]
Should be fixed now. We need to `scale` images, not `resize`.

**Comment by illnesse** [comment]
how to i regenerate the previews to test your fix?

**Comment by illnesse** [comment]
Yes, wonderful
![image](https://user-images.githubusercontent.com/40355982/196475103-d119ebd9-322d-4b00-8d71-9dfe6c362c31.png)

i think we can close this ❤️

**Comment by pulsejet** [comment]
Excellent 💯
Btw I also want to hear about any feature requests you might have (regardless of how big/small/doable).
