### ISSUE TITLE
Could not find resource memories/js/memories-main.js to load

### ISSUE THREAD

**Issue by teclab-at** [pulsejet/memories#726]
**Describe the bug**
No pictures are shown - page content is empty. Admin page not shown - page content is empty.

**To Reproduce**
-

**Screenshots**
-

**Platform:**

- OS: Ubuntu 22
- Browser: Chrome
- Memories Version: b6d1025c14eed003edaa2d9ec095128fb977a75d
- Nextcloud Version: stable27 7ac99a60d1ef5a6b80072e522705e1a04b5ea565
- PHP Version: 8.1.2-1ubuntu2.13

**Additional context**

- Any errors in the JS console?

- Any errors in the Nextcloud server logs?
"Could not find resource memories/js/memories-main.js to load"
"Could not find resource memories/js/memories-admin.js to load"

**Comment by pulsejet** [comment]
Did you build? See the readme

**Comment by pulsejet** [comment]
What version of node is this?
Also why are you building from source? Are you trying to develop?

**Comment by teclab-at** [comment]
Sorry for late reply, seems that I missed the notification mail.

No I am not developing, it was a desperate measure trying to get it working.
In the meantime I think I better understand how stuff works and finally got all running.

Again, sorry for the noise.
