### ISSUE TITLE
Undefined array key "MIMEType" at /var/www/nextcloud/apps/memories/lib/Exif.php#124

### ISSUE THREAD

**Issue by AndyXheli** [pulsejet/memories#727]
**Describe the bug**
Error under logs

**To Reproduce**
N/A

**Screenshots**

**Platform:**

- Win 11
- Browser: [e.g. Chrome, Safari]
- Chrome
- Memories Version: [e.g. 4.1.0]
- 5.2.1
- Nextcloud Version: [e.g. 25.0.6]
- 27.0.0
- PHP Version: [e.g. 8.1]
8.1
**Additional context**

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?
{"reqId":"ZVzuejQUUKPQ1WlCssdq","level":3,"time":"2023-07-07T08:23:57-05:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key \"MIMEType\" at /var/www/nextcloud/apps/memories/lib/Exif.php#124","userAgent":"--","version":"27.0.0.8","data":{"app":"PHP"},"id":"64a813626359e"}

**Comment by sbranden** [comment]
I also get the error in my logs.
Error | PHP | Undefined array key "MIMEType" at /var/www/nextcloud/apps/memories/lib/Exif.php#124

I just installed nextcloud and started playing with it:

Platform:
OS: Ubuntu 22.04
Browser: Chrome
Memories Version: 5.2.1
Nextcloud Version: 27.0.0
PHP Version: 8.2

**Comment by sbranden** [comment]
@pulsejet, looks to be a common issue.  any idea what is wrong?

**Comment by DuneJeeper** [comment]
Same. I can't add anything to memories using correct paths.

**Comment by pulsejet** [comment]
Does this happen for every file?

**Comment by AndyXheli** [comment]
No I don't think it happens for all files

**Comment by pulsejet** [comment]
I see. Any way to narrow it down would help

**Comment by AndyXheli** [comment]
I'll keep an eye on it and see if i notice anything.

**Comment by pulsejet** [comment]
This has guards now
