### ISSUE TITLE
Dynamic Albums

### ISSUE THREAD

**Issue by rafny** [pulsejet/memories#728]
This is a feature request to add dynamic albums that can be created via certain filters such as date, locations, tag, file size/dimension...
Perhaps it can be built with the NC Flow feature, but the eventual goal would be to create a Dynamic Album (called Smart Albums???), set-up the filtering logic and have that album automatically populate the photos and videos that fit that criteria.

**Comment by pulsejet** [comment]
Duplicate of #352
