### ISSUE TITLE
Make it possible to view folders via shared token

### ISSUE THREAD

**Issue by adminde** [pulsejet/memories#74]
An awesome feature of the old Gallery app, that I horrendously miss, was the possibility to share (e.g. password protected) directories directly via the Galleries app, like https://cloud.domain.com/apps/gallery/s/{token}. Just being able to send a link with photos to people without an account. Sharing the directory like this disabled all sidebar navigation and just displayed the directories' thumbnails ready to be viewed in the old tile view.

If the TimelineQuery architecture allows this, having the possibility to just share a folder like 
  https://cloud.domain.com/apps/memories/s/{token} (with authentication)
instead of
  https://cloud.domain.com/apps/memories/folders/{path}
would be absolutely great and immediately boost the nextcloud/memories combination to be my favorite photos sharing platform (again) by far.

If I can help in any way by trying to reverse engineer the Gallery app routing architecture or something like this, I'd gladly try to do so, if this brings me my missing feature back :)

**Comment by pulsejet** [comment]
Interesting idea. Perhaps this could be clubbed with some album integration.

**Comment by pulsejet** [comment]
Fully implemented now 💯

![image](https://user-images.githubusercontent.com/10709794/198815504-9112929d-d65a-4396-abb0-4f1ab4abb99e.png)
![image](https://user-images.githubusercontent.com/10709794/198815512-3d4428b0-a87a-49e7-b8ac-e32bdfbcbbd0.png)
![image](https://user-images.githubusercontent.com/10709794/198815522-209ce3b7-4ae3-41dd-a792-3e1d7738e48e.png)

**Comment by pulsejet** [comment]
Thanks for the idea @adminde

**Comment by adminde** [comment]
This was incredibly fast
Thanks a lot!
