### ISSUE TITLE
Server Error after editing image

### ISSUE THREAD

**Issue by WayneBooth** [pulsejet/memories#744]
**Describe the bug**
Attempting to save an image that has been cropped causes a message "Error Saving Image"

**To Reproduce**
In either http or https contexts
Load an image from the Memories timeline
Enter the image editor and crop
Hit "Save" and specify a different filename on the dialog.
Git "Save" on the dialog.
See the message (top right)

**Platform:**

OS: Ubuntu 22.04
Chromium Version 114.0.5735.198 (Official Build) (64-bit)"
Nextcloud version: 27.0.0 : 2023-06-12T14:58:06+00:00
Memories version: 5.2.1
PHP Version: 8.1
image store on External Storage (local on Linux)

**Additional context**
While "inspecting" the page

PUT http://nextcloud.int/nextcloud/index.php/apps/memories/api/image/edit/206096 500 (Internal Server Error)
(anonymous) @ memories-main.js?v=db1bdc5f-0:2
e.exports @ memories-main.js?v=db1bdc5f-0:2
e.exports @ memories-main.js?v=db1bdc5f-0:2
p.request @ memories-main.js?v=db1bdc5f-0:2
(anonymous) @ memories-main.js?v=db1bdc5f-0:2
(anonymous) @ memories-main.js?v=db1bdc5f-0:2
onSave @ memories-main.js?v=db1bdc5f-0:2
handleSave @ memories-vendors-node_modules_filerobot-image-editor_lib_index_js.js?v=d52060561abf82a531b2:21253
setTimeout (async)
startSaving @ memories-vendors-node_modules_filerobot-image-editor_lib_index_js.js?v=d52060561abf82a531b2:21253
validateInfoThenSave @ memories-vendors-node_modules_filerobot-image-editor_lib_index_js.js?v=d52060561abf82a531b2:21253
Nb @ memories-vendors-node_modules_filerobot-image-editor_lib_index_js.js?v=d52060561abf82a531b2:24625
Tb @ memories-vendors-node_modules_filerobot-image-editor_lib_index_js.js?v=d52060561abf82a531b2:24625
Ub @ memories-vendors-node_modules_filerobot-image-editor_lib_index_js.js?v=d52060561abf82a531b2:24626
nf @ memories-vendors-node_modules_filerobot-image-editor_lib_index_js.js?v=d52060561abf82a531b2:24676
se @ memories-vendors-node_modules_filerobot-image-editor_lib_index_js.js?v=d52060561abf82a531b2:24677
(anonymous) @ memories-vendors-node_modules_filerobot-image-editor_lib_index_js.js?v=d52060561abf82a531b2:24688
Rk @ memories-vendors-node_modules_filerobot-image-editor_lib_index_js.js?v=d52060561abf82a531b2:24845
Jb @ memories-vendors-node_modules_filerobot-image-editor_lib_index_js.js?v=d52060561abf82a531b2:24623
hd @ memories-vendors-node_modules_filerobot-image-editor_lib_index_js.js?v=d52060561abf82a531b2:24680
fd @ memories-vendors-node_modules_filerobot-image-editor_lib_index_js.js?v=d52060561abf82a531b2:24645
ed @ memories-vendors-node_modules_filerobot-image-editor_lib_index_js.js?v=d52060561abf82a531b2:24644

{
    "message": "Request failed with status code 500",
    "name": "AxiosError",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "FormData": null
        },
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json",
            "requesttoken": "MRakJQmEfVALFS0bgRYCVbM18Ws9HrxZUOit37kwfKI=:WXKXEV3UCX8gPkxC6343G/dellt5es1vYt7Mq4lgH8Y="
        },
        "method": "put",
        "url": "/nextcloud/index.php/apps/memories/api/image/edit/206096",
        "data": "{\"name\":\"IMG_20230718_130124_1.jpg\",\"width\":1822,\"height\":2429,\"quality\":0.92,\"extension\":\"jpeg\",\"state\":{\"imgSrc\":\"blob:http://nextcloud.int/5cac4195-960b-4b15-b4cc-395d9cd5d12b\",\"finetunes\":[],\"finetunesProps\":{},\"filter\":null,\"adjustments\":{\"crop\":{\"x\":0.2909809436193981,\"y\":0.2696869003811277,\"width\":0.5839203355675298,\"height\":0.5839203246155868},\"isFlippedX\":false,\"isFlippedY\":false,\"rotation\":0},\"annotations\":{},\"resize\":{},\"shownImageDimensions\":{\"width\":456.53999999999996,\"height\":608.7199999999999,\"scaledBy\":1}}}"
    },
    "code": "ERR_BAD_RESPONSE",
    "status": 500
}

**Comment by pulsejet** [comment]
Anything in Nextcloud logs?

**Comment by WayneBooth** [comment]
Sorry, forgot to say. No message are being logged.
Since then i have updated loglevel to 0, but one one message is logged

{"reqId":"B6gJLegg4IGU7iQif7J1","level":0,"time":"2023-07-19T11:27:18+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"OC_Image->fixOrientation() Orientation: 6","userAgent":"--","version":"27.0.0.8","data":{"app":"core"}}

**Comment by WayneBooth** [comment]
closed in error

**Comment by WayneBooth** [comment]
Missing details from yesterdays "browser inspect" (not sure why this didn't copy)

The interesting bit:
{"message":"negative or zero image size `' @ error\/image.c\/CloneImage\/794"}

Full object copy:

o {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}
code
: 
"ERR_BAD_RESPONSE"
config
: 
{transitional: {…}, transformRequest: Array(1), transformResponse: Array(1), timeout: 0, adapter: ƒ, …}
message
: 
"Request failed with status code 500"
name
: 
"AxiosError"
request
: 
XMLHttpRequest
onabort
: 
ƒ ()
onerror
: 
ƒ ()
onload
: 
null
onloadend
: 
ƒ x()
onloadstart
: 
null
onprogress
: 
null
onreadystatechange
: 
null
ontimeout
: 
ƒ ()
readyState
: 
4
response
: 
"{\"message\":\"negative or zero image size `' @ error\\/image.c\\/CloneImage\\/794\"}"
responseText
: 
"{\"message\":\"negative or zero image size `' @ error\\/image.c\\/CloneImage\\/794\"}"
responseType
: 
""
responseURL
: 
"https://nextcloud.int/nextcloud/index.php/apps/memories/api/image/edit/206136"
responseXML
: 
null
status
: 
500
statusText
: 
""
timeout
: 
0
upload
: 
XMLHttpRequestUpload
onabort
: 
null
onerror
: 
null
onload
: 
null
onloadend
: 
null
onloadstart
: 
null
onprogress
: 
null
ontimeout
: 
null
[[Prototype]]
: 
XMLHttpRequestUpload
withCredentials
: 
false
[[Prototype]]
: 
XMLHttpRequest
response
: 
config
: 
{transitional: {…}, transformRequest: Array(1), transformResponse: Array(1), timeout: 0, adapter: ƒ, …}
data
: 
message
: 
"negative or zero image size `' @ error/image.c/CloneImage/794"
[[Prototype]]
: 
Object
headers
: 
cache-control
: 
"no-cache, no-store, must-revalidate"
content-length
: 
"78"
content-security-policy
: 
"default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'"
content-type
: 
"application/json; charset=utf-8"
date
: 
"Wed, 19 Jul 2023 17:13:18 GMT"
expires
: 
"Thu, 19 Nov 1981 08:52:00 GMT"
feature-policy
: 
"autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'"
pragma
: 
"no-cache"
referrer-policy
: 
"no-referrer"
server
: 
"Apache/2.4.52 (Ubuntu)"
strict-transport-security
: 
"max-age=15552000; includeSubDomain"
x-content-type-options
: 
"nosniff"
x-frame-options
: 
"SAMEORIGIN"
x-permitted-cross-domain-policies
: 
"none"
x-request-id
: 
"VA0rzPEnZu2HROpx4QAa"
x-robots-tag
: 
"noindex, nofollow"
x-xss-protection
: 
"1; mode=block"
[[Prototype]]
: 
Object
request
: 
XMLHttpRequest
onabort
: 
ƒ ()
onerror
: 
ƒ ()
onload
: 
null
onloadend
: 
ƒ x()
onloadstart
: 
null
onprogress
: 
null
onreadystatechange
: 
null
ontimeout
: 
ƒ ()
readyState
: 
4
response
: 
"{\"message\":\"negative or zero image size `' @ error\\/image.c\\/CloneImage\\/794\"}"
responseText
: 
"{\"message\":\"negative or zero image size `' @ error\\/image.c\\/CloneImage\\/794\"}"
responseType
: 
""
responseURL
: 
"https://nextcloud.int/nextcloud/index.php/apps/memories/api/image/edit/206136"
responseXML
: 
null
status
: 
500
statusText
: 
""
timeout
: 
0
upload
: 
XMLHttpRequestUpload {onloadstart: null, onprogress: null, onabort: null, onerror: null, onload: null, …}
withCredentials
: 
false
[[Prototype]]
: 
XMLHttpRequest
status
: 
500
statusText
: 
""
[[Prototype]]
: 
Object
constructor
: 
ƒ Object()
hasOwnProperty
: 
ƒ hasOwnProperty()
isPrototypeOf
: 
ƒ isPrototypeOf()
propertyIsEnumerable
: 
ƒ propertyIsEnumerable()
toLocaleString
: 
ƒ toLocaleString()
toString
: 
ƒ toString()
valueOf
: 
ƒ valueOf()
__defineGetter__
: 
ƒ __defineGetter__()
__defineSetter__
: 
ƒ __defineSetter__()
__lookupGetter__
: 
ƒ __lookupGetter__()
__lookupSetter__
: 
ƒ __lookupSetter__()
__proto__
: 
(...)
get __proto__
: 
ƒ __proto__()
set __proto__
: 
ƒ __proto__()
[[Prototype]]
: 
Error
constructor
: 
ƒ o(e,t,n,r,o)
toJSON
: 
ƒ ()
isAxiosError
: 
true
[[Prototype]]
: 
Object

**Comment by pulsejet** [comment]
Does this happen with every image or just some specific ones?

**Comment by WayneBooth** [comment]
This has happened for all images I've tried.

**Comment by pulsejet** [comment]
Stale + this is a bug in Imagick we can't do anything about
