### ISSUE TITLE
Enable search for albums based on their title

### ISSUE THREAD

**Issue by quentinus95** [pulsejet/memories#746]
**Is your feature request related to a problem? Please describe.**
There are a lot of open tickets regarding search, but a lot are asking for search related to tags or images content. One (maybe) low-hanging fruit would be to have search based on the albums title (in the albums page).

Let's consider you have dozens (if not hundreds) of albums and want to quickly find a specific picture in an album you already have in mind. It is then almost impossible to find it (especially on mobile where you cannot use the browser search feature when “installing Memories as an app”).

Note that this is an issue for grandma adoption.

**Describe the solution you'd like**
When using the search feature of Nextcloud, I would expect the albums list to be filtered (and/or the search results to show the matching albums).

**Describe alternatives you've considered**
Using browser search feature, but it is not doable on mobile.

As always, thank you for your awesome work on this project. If I can do any non-code contribution work to improve this feature request, please let me know.

**Comment by meonkeys** [comment]
Seems like #674 covers this.

**Comment by jsddsfoh** [comment]
I was happy to read "Basic search functionality" in changelog from v7.1.0.
But unfortunately it's "only" albumname and place based.
I would love to see a foldername based search, as i organize my photos in folders :)
