### ISSUE TITLE
Exiftool binary not executable after using Recognize

### ISSUE THREAD

**Issue by kaibagley** [pulsejet/memories#754]
**Describe the bug**
After installing (and uninstalling) Recognize, my Exiftool binary is no longer executable. 
**Platform:**
- OS: Ubuntu Server 22.04
- Browser: Firefox 115
- Memories Version: 5.2.1
- Nextcloud Version: 27 (AIO 6.4.0)
- PHP Version: 8.1?

**Additional context**
Alongside this, in my `nextcloud-aio-nextcloud` docker logs, I get `WARN: Failed to create stay_open exiftool process` once every now and then.

Thanks!

**Comment by derbrummbaer** [comment]
Hi All,

have the same problem coming back from holiday.
Looks like they changed tmpfs option in AIO container configuration during last two weeks

`    restart: unless-stopped
    networks:
      - nextcloud-aio
    tmpfs:
      - /tmp`

This breaks execution of files in /tmp

**Comment by pulsejet** [comment]
Can you open an issue at the AIO repo? See https://memories.gallery/troubleshooting/#usage-of-tmpfs

**Comment by derbrummbaer** [comment]
Just found a pull request
[](https://github.com/nextcloud/all-in-one/pull/3047)

**Comment by szaimen** [comment]
This is now released with v7.0.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by kaibagley** [comment]
Fixes it for me! Thanks so much!

**Comment by Boop0p** [comment]
> This is now released with v7.0.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

Thanks for the update. Any guesses for a rough timeline on when it might end up in the stable channel? I'd like the fix but I'd also like to stick to stable. Cheers :)

**Comment by szaimen** [comment]
Probably this thursday will be the release

**Comment by Boop0p** [comment]
Sooner than I expected, grand! Cheers :)

**Comment by kaibagley** [comment]
I forgot to close this now that it is in stable
