### ISSUE TITLE
PHP errors after upgrading AIO

### ISSUE THREAD

**Issue by Byter3** [pulsejet/memories#755]
**Describe the bug**
Visibly only annoying glitches in the UI while loading the full resolution image

**To Reproduce**
Updated Nextcloud AIO to V6.4.0

**Platform:**

- Browser: [e.g. Chrome, Safari]
- Memories Version: [e.g. 4.1.0]
- Nextcloud Version: Nextcloud AIO 27.0.0
- PHP Version: 8.1.21

Logs:

`
[PHP] Error: proc_open(): Exec failed: Permission denied at /var/www/html/custom_apps/memories/lib/Exif.php#355

at 2023-07-31T04:20:05+00:00
`

`
[PHP] Error: Undefined array key "MIMEType" at /var/www/html/custom_apps/memories/lib/Exif.php#124

PUT /remote.php/dav/files/*/iPhone%20Photos/2023/07/23-07-30%2016-24-00%205947.heic
from 66.*.126 by Eva at 2023-07-31T02:29:55+00:00
`

`
[PHP] Error: proc_open(): Exec failed: Permission denied at /var/www/html/custom_apps/memories/lib/Exif.php#414

PUT /remote.php/dav/files/*/iPhone%20Photos/2023/07/23-07-30%2016-24-00%205947.heic
from 66.*.126 by Eva at 2023-07-31T02:29:55+00:00
`

`
[PHP] Error: Undefined array key "MIMEType" at /var/www/html/custom_apps/memories/lib/Exif.php#124

PUT /remote.php/dav/files/*/iPhone%20Photos/2023/07/23-07-29%2016-09-05%205939.heic
from 66.*.126 by * at 2023-07-31T02:29:54+00:00
`

**Comment by xogizmft32** [comment]
same error when use exiftool.
and can't view motion photo(android)

**Comment by danyboypremier** [comment]
Reference there #754

**Comment by xogizmft32** [comment]
After AIO upgrade to 7.0.0 beta

- view/change exif data : ok
- view video : ok
- view android motion photo : doesn't work

OS: Android 10
Browser: Chrome
Memories Version: 5.3.0-alpha.1
Nextcloud Version:
  Nextcloud Hub 5 (27.0.2), Nextcloud AIO v7.0.0
PHP Version: 8.1.22

**Comment by pulsejet** [comment]
> * view android motion photo : doesn't work

This has nothing to do with AIO. Can you file a bug with a sample image?

**Comment by xogizmft32** [comment]
> > * view android motion photo : doesn't work
> 
> This has nothing to do with AIO. Can you file a bug with a sample image?

image that new uploaded work fine.
only image that uploaded before v7.0.0 beta has an error.
so i re-indexing all image, now work fine.
(error : only image that uploaded before v7.0.0. beta
 solution: re-indexing)

**Comment by pulsejet** [comment]
That should right, anything before AIO v7 will have to be reindexed.

Closing this.
