### ISSUE TITLE
Memories Reverse Geocoding "Failed to search for location with Nominatim." when updating pictures

### ISSUE THREAD

**Issue by Kybeer** [pulsejet/memories#758]
**Describe the bug**

I'm on Nextcloud 26.0.4 and Memories 5.2.1

Tagging my pictures works for a while (say, editing 40-60 pictures), but then after a while I get "Failed to search for location with Nominatim."

All checks in Memories are OK as seen on the screen shots.

https://imgur.com/sx6TY4e

https://imgur.com/wAow412

If I manually download the geoip db again from the web ui, it works for a while, and then stops again..

Everything else works as expected in Nextcloud and Memories.

**To Reproduce**
Try tagging many pictures in a row.

**Screenshots**

https://imgur.com/htEO5NN

**Platform:**

- OS: Nextcloud running in Podman container, on RHEL 8.8
- Browser: Firefox & Edge - same issue
- Memories Version: [e.g. 5.2.1]
- Nextcloud Version: [e.g. 26.0.4]
- PHP Version: [e.g. 8.2.8]

**Additional context**

- Any errors in the JS console?
- Any errors in the Nextcloud server logs? No

**Comment by Kybeer** [comment]
Could it be related to some throttling?
https://stackoverflow.com/questions/33935119/how-many-calls-i-can-make-to-osms-nominatim-instance

**Comment by pulsejet** [comment]
Yeah, it's throttling. Not much we can do about it. You could, for instance, use OSM or Google to find the coordinates and put them in the search box. That should still work.

**Comment by Kybeer** [comment]
Great, thanks a lot for the quick reply! Let's close this topic.
