### ISSUE TITLE
Photos leaked to other users when browsing tags and places

### ISSUE THREAD

**Issue by dukey** [pulsejet/memories#761]
**Describe the bug**

Thumbnails for tags and places can leak photos to other users when the tag or place is present for two users.

For example, if there is a tag called bottle, and User_A has a photo tagged with "bottle" and User_B also has a photos with the tag "bottle:, and the thumbnail for the tag is from User_A's photos, user B will see User_A's photo for the tag "bottle" when viewing tags.  The same issue occurres for two places that are the same.

**To Reproduce**

**Screenshots**

**Platform:**

- OS: [e.g. iOS]  Fedora 28
- Browser: [e.g. Chrome, Safari] Firefox 
- Memories Version: [e.g. 4.1.0] 5.2.1
- Nextcloud Version: [e.g. 25.0.6] 27.0.1
- PHP Version: [e.g. 8.1] 8.2.8

**Additional context**

- Any errors in the JS console? No
- Any errors in the Nextcloud server logs? No

**Comment by dukey** [comment]
Additional note:  The nextcloud photos app does not display photos from other users.

**Comment by pulsejet** [comment]
#665?

**Comment by dukey** [comment]
When I did a quick browse and search of bugs, I must have been vision impaired.

#665  is the same issue.  In fact, as I had logged in with both firefox and chrome, the browser cache caused the issue.  As soon as private browsing was used, there was no issue.

Sorry for the inconvenience.
