### ISSUE TITLE
Albums view disappeared after upgrade

### ISSUE THREAD

**Issue by tobiaslangner** [pulsejet/memories#762]
**Describe the bug**
After upgrading Memories to v5.2.1 and in the same process upgrading Nextcloud from v25 to v27 (through v26) I can no longer find the "Albums" view in Memories. Furthermore, old Album links shared with friends now result in "Page not found" instead of showing the Album. 

Neither Memories nor Nextcloud upgrade showed any errors and I followed the recommended steps. Unfortunately, I only discovered the issue after the ugprades, so I can't pinpoint whether the Nextcloud or Memories upgrade was ultimately responsible.

I ran `occ memories:index` in the hope that it might fix things but it did not.

**To Reproduce**
Unclear, see above.

**Screenshots**
![image](https://github.com/pulsejet/memories/assets/6542746/55d9e1c8-d8f6-48ea-b977-ea882574a52c) Albums is missing.

**Platform:**

- OS: [e.g. iOS] Ubuntu
- Browser: [e.g. Chrome, Safari] Chrome
- Memories Version: [e.g. 4.1.0] 5.2.1
- Nextcloud Version: [e.g. 25.0.6] 27.0.1
- PHP Version: [e.g. 8.1]

**Additional context**

- Any errors in the JS console?
No.

- Any errors in the Nextcloud server logs?
Nothing related.

**Comment by tobiaslangner** [comment]
To add to that: On the mobile version of Memories I still see the "Albums" tab but it does not contain any albums, and I am definitely sure that I had created some before.

If I try to create an album in the mobile view, it shows the notifications `Failed to create <album` and `Failed to update properties of <album> with {"location": "...", "collaborators":[}.`.

Here is the respective section from the [nextcloud.log](https://github.com/pulsejet/memories/files/12251367/nextcloud.log) with potentially sensitive stuff removed.

**Comment by pulsejet** [comment]
Enable the Nextcloud photos app

**Comment by tobiaslangner** [comment]
Thanks, that indeed fixed it... I recall vaguely that I disabled the Photos app a few weeks ago as I thought that I now have Memories...

It would be nice if Memories showed an error if Photos is disabled, since it seems to crucially depend on it?

**Comment by pulsejet** [comment]
The admin interface would show a warning starting the next version: https://github.com/pulsejet/memories/commit/28634a3f300db07f5c962a1c4a193d8f3c7c81c5

**Comment by tobiaslangner** [comment]
Excellent, thank you!
