### ISSUE TITLE
Large images, high pixels do not generate previews thumbnails (16320x12240, 200MP), but can still be open to view

### ISSUE THREAD

**Issue by ph-256** [pulsejet/memories#763]
**Describe the bug**
I followed the config.sample.php about the 'preview_max_x' and 'preview_max_y' and it says that if I want set it as no limit to set it as 'null' and so I did, but it seems like that still it does not work, I still do not get previews for 200MP images 16320x12240 or 20000x10000, but I can still see them if I click on them, they do load after a couple of seconds when clicked only no previews.

**To Reproduce**
just upload a 200MP image 
https://www.lizardq.com/cdn/samples/Church-200MP/Church-200MP.jpg

**Screenshots**
[Screenshot 1](https://i.imgur.com/XMHsJkZ.png)
[Screenshot 2](https://i.imgur.com/rP7uHli.png)

**Platform:**
- Browser: Chrome
- Memories Version: 5.2.1
- Nextcloud Version: 27.0.1
- PHP Version: 8.2.8

**Additional context**
[These are my current settings at config.php about the memories and previews](https://i.imgur.com/qVLVfgl.png)
Also, my docker container for nextcloud uses as much ram as it wants

**Comment by pulsejet** [comment]
Sample needed

**Comment by ph-256** [comment]
> Sample needed

the church i posted [this](https://www.lizardq.com/cdn/samples/Church-200MP/Church-200MP.jpg)

**Comment by pulsejet** [comment]
My instance can generate the previews so seems like a config issue.
![image](https://github.com/pulsejet/memories/assets/10709794/8c66f642-da35-466c-a5ad-28cc6bb91e3e)

1. There should be some errors in the Nextcloud logs when trying to view the preview.
1. What is your PHP memory limit set to? (`php -i | grep "memory_limit"`). You may need to increase that.
1. Can you try setting the limits explicitly instead of setting to null? My limits looks like this: 
![image](https://github.com/pulsejet/memories/assets/10709794/b2748c6a-9375-4349-9c42-00e9eb034d8d)

**Comment by ChildLearningClub** [comment]
Same result as @pulsejet. 

Uploaded [Church-200MP.jpg](https://www.lizardq.com/cdn/samples/Church-200MP/Church-200MP.jpg) to Nextcloud, no preview generated. 

Checked Nextcloud's logs Level info:  "_**_Info: Image size of 20000x10000 would exceed allowed memory limit of 256. You may increase the preview_max_memory in your config.php if you need previews of this image._**_"

Checked config.php for any configuration relative to:  preview_max_memory, 'preview_max_x' => 2048, or 'preview_max_y' => 2048, ( None of which were configured )

Opened Admin settings Memories and changed "**Max memory for preview generation (MB)**" from the default 128 to 1024 as @pulsejet has pictured above.

Went back to the folder with the image, thumbnail generated.

**Comment by ph-256** [comment]
The issue was solved. I made my php memory_limit to 1024M and the previews for the large pixel images were generated when I went into memories, guess my PHP memory was not enough when it was 512MB (I found it from the `Nextcloud GUI / Administration settings / System / PHP`),
to change/override the for the PHP I had to set `memory_limit=1024M` at `user/appdata/nextcloud/php/php-local.ini`
