### ISSUE TITLE
Add option "Set as album cover" for images inside albums.

### ISSUE THREAD

**Issue by luckkmaxx** [pulsejet/memories#764]
**Is your feature request related to a problem? Please describe.**
When you create an album, the cover is taken randomly which many times is the worst one from the album.

**Describe the solution you'd like**
Adding this option will let users to identify better their albums, and set a more relevant image that matches the album title

**Comment by AxelTheGerman** [comment]
Wondering how the cover is chosen and how much work it would be to allow the user to change it

**Comment by yajo** [comment]
Duplicate of #557?

**Comment by pulsejet** [comment]
Fixed with https://github.com/pulsejet/memories/pull/1071
