### ISSUE TITLE
Images are showing as doubled

### ISSUE THREAD

**Issue by RikkiBC** [pulsejet/memories#768]
**Describe the bug**

When opening photos, photos are doubled. Apart from the image centred in the middle of the screen, there's a duplicate image behind it, centred at the top of the screen.

**To Reproduce**

Open an image in Memories. Especially a landscape rather than portrait image, which makes it easier to see.

It intermittently *doesn't* occur, though I can't see a pattern around this.

**Screenshots**

![Screenshot_20230810_095346_Samsung Internet](https://github.com/pulsejet/memories/assets/57303982/db7d6889-b063-48b7-ae2d-844c62fc472b)

**Platform:**

- OS: [e.g. iOS] Android and Linux (Ubuntu).
- Browser: [e.g. Chrome, Safari] Reproduced on mobile (Fennec and Samsung Internet) and on Desktop (Firefox)
- Memories Version: [e.g. 4.1.0] 5.2.1
- Nextcloud Version: [e.g. 25.0.6] 26.0.4 AIO
- PHP Version: [e.g. 8.1] 8.1.21

**Additional context**

- Any errors in the Nextcloud server logs?

Not sure if this is related?

```
[PHP] Error: proc_open(): Exec failed: Permission denied at /var/www/html/custom_apps/memories/lib/Exif.php#355

at 2023-08-09T23:44:31+00:00
```

**Comment by RikkiBC** [comment]
This has been happening for a little while (maybe a week or two?) so I was surprised to see no one else logging an issue about this.

Maybe it's something specific to my setup? Running AIO on an ARM-architecture-based VM, if that helps at all?

**Comment by szaimen** [comment]
Hi, can you upgrade to v7.0.0 Beta and check if that resolves things? See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by pulsejet** [comment]
This can happen if EXIF decoding fails, so upgrading AIO might fix the problem. Try running `occ memories:index` after you upgrade.

**Comment by prurigro** [comment]
I've been able to fix this issue for individual images by clicking the edit button and then saving them (without making any changes). Glad to hear there's a more general fix coming!

**Comment by pulsejet** [comment]
@RikkiBC I haven't been able to repro this at all. Can you trying doing a complete re-index with `occ memories:index -f`? That should fix any files that were improperly indexed.

**Comment by RikkiBC** [comment]
Hi, sorry I didn't get back to this, my notifications were a bit stuffed.

The issue stopped happening on *new* images after an AIO upgrade a couple weeks ago. However old images are still affected.

I'll try a re-index and see if that affects the older affected images when I have time over the coming day or two.

**Comment by RikkiBC** [comment]
Hi @pulsejet - I ran the force re-index (`occ memories:index -f`) command. Took a little white to get through my photos as, between my three users, I have a few hundred GB of files hah.

Between the Nextcloud/Memories update a few weeks ago stopping it from happening on new images, and the force re-index of all photos, it looks like this has fixed the issues on the older images that were experiencing this. Thank you.

**Comment by pulsejet** [comment]
That's great, we can close this then
