### ISSUE TITLE
Add possibility to combine tags to find photos more precisely

### ISSUE THREAD

**Issue by johnSamilin** [pulsejet/memories#769]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't select photos by multiple tags. For example, I added a bunch of tags to my photos: Plants, Trip to Greece, My home, etc (yeah, I got a little carried away). And I'd like to select only plants that I saw in Greece (or like, some another circumstances)

**Describe the solution you'd like**
In Tags section, I'd expect to see a list of tags. I could click on them and combine in SQL-like request: "include tags Plants, Trip to Greece, My home" or "include tags Plants, exclude tags Trip to Greece". This should play nice with ORM

**Comment by pulsejet** [comment]
Basically subset of search #674
