### ISSUE TITLE
Rerun reverse geocoding

### ISSUE THREAD

**Issue by jacksbox** [pulsejet/memories#772]
**Describe the bug**
My ssh connection broke while running the `places-setup` occ command. 
Only ~3000 of 6000 images got processed and are visible on the map.
Is there a command to process the rest of my images - or do I need to run the whole `places-setup` command again? 
(I thought it would maybe automatically pick up the unprocessed images while indexing via cron, but no, after 12h nothing happend there)

**Comment by pulsejet** [comment]
Try `occ memories:places-setup --recalculate`

**Comment by jacksbox** [comment]
@pulsejet running now, thanks a lot :)
(will write again if it did not work as expected, but otherwise this can be closed)

Is there a place where all commands and options are listed? I searched for something like before opening this issue, but could not find anything

**Comment by pulsejet** [comment]
That is a good point, this needs to be documented. Let's keep this open for now.
