### ISSUE TITLE
Recognize: Unassigned faces have duplicates of each image with the same square drawn

### ISSUE THREAD

**Issue by prurigro** [pulsejet/memories#773]
**Describe the bug**

In the unassigned faces section of the "People" category, each image is present multiple times for each person. Images with a bunch of people will have 30+ copies, with each of the people highlighted a bunch of times. You can't select the same image twice when assigning a particular person, so to clear them you need to select one of the photos, choose the person, select the next photo, choose the same person, etc.

I'd initially created an [issue in the recognize repo](https://github.com/nextcloud/recognize/issues/923), and one of the contributors there confirmed that the issue was present for them, but that it only happens in memories and not the same (currently unreleased) unassigned faces feature in the photos app.

**To Reproduce**

I'm not exactly sure what factors are needed to reproduce, but a number of people in the issue I linked were observing the same issue (including one of the recognize devs).

**Screenshots**

![image](https://github.com/pulsejet/memories/assets/1149238/e99041d9-6dd1-4bb1-ac35-e7496573d3fa)

**Platform:**

- OS: Linux, Windows, MacOS
- Browser: Firefox
- Memories Version: 5.2.1
- Nextcloud Version: 27.0.2
- PHP Version: 8.1.21

**Comment by pulsejet** [comment]
To anyone experiencing this issue, you can apply this patch until v5.3 is out: https://github.com/pulsejet/memories/commit/b513650892b241ac4ee6b3960a90a1b26ef515a5.patch

**Comment by prurigro** [comment]
Amazing- that did the trick! Thanks so much!
