### ISSUE TITLE
FFMPEG height not divisible by 2 (1920x1079)

### ISSUE THREAD

**Issue by werto165** [pulsejet/memories#775]
**Describe the bug**

Trying to play video with transcoding, it times out and I get this in the /tmp/go-vod logs. 

2023/08/17 00:53:04 f4xqk8z7qt70-1080p: /usr/bin/ffmpeg -loglevel warning -ss 36.000000 -i /var/www/html/data/GH010153.MP4 -copyts -vf format=nv12,scale=force_original_aspect_ratio=decrease:>
2023/08/17 00:53:05 ffmpeg-error: [libx264 @ 0x56530d641500] height not divisible by 2 (1920x1079)
2023/08/17 00:53:05 ffmpeg-error: Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

**To Reproduce**
playing a go pro video with transcoding on cpu at 1080p (720p works) 

**Screenshots**

**Platform:**

- OS: Windows + Android
- Browser: Chrome
- Memories Version: 5.2.1
- Nextcloud Version: 27.0.2
- PHP Version: 8.2.8

**Additional context**

https://gist.github.com/jjehannet/bd85f1a40dbbb0d9eeddae5b0ccc8b14 

I'm not sure where the ffmpeg cli code is done within the source code, so I don't know if this "fix" would work .

- Any errors in the JS console?
 {"message":"Transcoder returned 408"}
- Any errors in the Nextcloud server logs?

**Comment by pulsejet** [comment]
Try v5.3.0-alpha.1, should be fixed there.

**Comment by werto165** [comment]
I'll wait for the release, not sure how to install it with the way my docker is setup with permissions and all
