### ISSUE TITLE
Add possibility to skip subfolders of path

### ISSUE THREAD

**Issue by lettore** [pulsejet/memories#777]
New to Memories, great app, but I have a folder with some mixed content, photo of work, photo of me and video. I want to see only 2 subfolders of path, it's possible to add a menu for deselecting some folders in path? Or more simple use a file .nomemories to skip subfolders.

**Comment by pulsejet** [comment]
You need `.nomedia`

**Comment by lettore** [comment]
.nomedia it's not obviously possibile because it affects also others apps in Nextcloud. Selecting multiple folders can work, thanks for the hint. However this is just a filter, will not skip memories for doing the scan of files outside the selected path. This can be a pain if you have thousands of files to scan that you simply don't need to be seen in memories.
