### ISSUE TITLE
Latest Release Shows 5.3.0 in GH Releases, Advertized as 5.4.0 in Nextcloud

### ISSUE THREAD

**Issue by edm00se** [pulsejet/memories#778]
I'm not seeing this reported in issues so far.

**Describe the bug**
In my nextcloud instance's apps updates screen I'm prompted to update my memories plugin, saying I'll be going from 5.2.1 to 5.4.0. Checking the git repo here shows the latest published release is in fact 5.3.0. Both reference the latest updated version ~"1 hour ago" as of this typing; I'm suspecting a typo.

**To Reproduce**

- observe update prompt and version level for apps, memories
- observe the latest release in source GitHub repo

**Screenshots**

app update prompt:
![image](https://github.com/pulsejet/memories/assets/622118/66e1fb69-e8c4-4462-9638-7a46f2d0f925)

latest GitHub release:
![image](https://github.com/pulsejet/memories/assets/622118/c08cd011-c39b-434d-a686-7ff9e1e18ef3)

latest listed release in Nextcloud app store shows 5.4.0 in link, hyperlink points to 5.3.0:
![image](https://github.com/pulsejet/memories/assets/622118/1492cb1f-d037-462c-b028-1dc892ba045e)

**Platform:**
N/A

**Additional context**
N/A

**Comment by edm00se** [comment]
For clarity, this issue was opened to make sure it was communicated, ideally as early as possible.

**Comment by pulsejet** [comment]
Thanks a lot for catching this early (typo indeed). We can't go back in versions so I've published a new one `v5.4.1` that should be uniform now to prevent any confusion.
