### ISSUE TITLE
Overlay (info/favorite) buttons don't work

### ISSUE THREAD

**Issue by rmu1987** [pulsejet/memories#779]
**Describe the bug**
When viewing a photo in Memories i click on the "Info" or "Favorite" button and nothing happens.
Other buttons (Share, Delete, Edit and the 3 dots) are working properly.

**To Reproduce**
- Open a photo and click the info or favorite button

**Platform:**

- OS: MacOS (viewing webinterface) & Docker (running official Nextcloud image)
- Browser: Firefox, Chrome and Safari
- Memories Version: 5.4.1
- Nextcloud Version: 27.0.2
- PHP Version: 8.2.9

**Additional context**
- Any errors in the JS console?
No errors when loading the photo or clicking the buttons.

- Any errors in the Nextcloud server logs?
No errors when loading the photo or clicking the buttons.

**Comment by pulsejet** [comment]
Try a server reboot + private window. Seems like a caching issue.
Can you reproduce the issue on the demo? https://demo.memories.gallery/apps/memories/#v/19375/6352

**Comment by rmu1987** [comment]
Hello, thanks for your reply!

I did a server reboot & after that tried Firefox and Chrome Private Window, the same issue.
I also tried your mentioned URL (the demo site) there the sidebar (when pushing info) is showing fine! 

I'm using Memories for couple of versions already but the info and favorite button did not work from the start unfortunately.

Also when i use the Nextcloud Files app and click the same picture and push the show sidebar button it shown a sidebar, but ofcourse a different one than i could see on your demo site.

**Comment by pulsejet** [comment]
> * No errors when loading the photo or clicking the buttons.

Any errors _before_ clicking it, e.g. as soon as the page loads?

**Comment by rmu1987** [comment]
> > * No errors when loading the photo or clicking the buttons.
> 
> Any errors _before_ clicking it, e.g. as soon as the page loads?

When i click on the Memories app i directly see:
"Source map error: Error: request failed with status 404
Resource URL: https://DOMAIN/custom_apps/memories/js/memories-main.js?v=041e067e-3
Source Map URL: /apps/memories/js/memories-main.js.map"

The mentioned URL is working fine when i access it directly in my browser. I see the content of the memories-main.js then.

When opening a picture and click the info button and wait for a long time i get:

Source map error: Error: request failed with status 404
Resource URL: https://DOMAIN/custom_apps/memories/js/memories-main.js?v=041e067e-3
Source Map URL: /apps/memories/js/memories-main.js.map
Source map error: Error: request failed with status 404
Resource URL: https://DOMAIN/custom_apps/memories/js/memories-vendors-node_modules_nextcloud_vue_dist_Components_NcAppSettingsDialog_js.js?v=f1a7e65e65dbf0bbe714
Source Map URL: /apps/memories/js/memories-vendors-node_modules_nextcloud_vue_dist_Components_NcAppSettingsDialog_js.js.map
Source map error: Error: request failed with status 404
Resource URL: https://DOMAIN/custom_apps/memories/js/memories-vendors-node_modules_nextcloud_vue_dist_Components_NcCheckboxRadioSwitch_js.js?v=635ddcec79f0c32d4a9c
Source Map URL: /apps/memories/js/memories-vendors-node_modules_nextcloud_vue_dist_Components_NcCheckboxRadioSwitch_js.js.map
Source map error: Error: request failed with status 404
Resource URL: https://DOMAIN/custom_apps/memories/js/memories-vendors-node_modules_nextcloud_vue_dist_Components_NcAppNavigationItem_js.js?v=4ec248ed0b4d54e42ac8
Source Map URL: /apps/memories/js/memories-vendors-node_modules_nextcloud_vue_dist_Components_NcAppNavigationItem_js.js.map

DOMAIN is my own domain where Nextcloud is running ofcourse.

**Comment by rmu1987** [comment]
> That indicates another app or some configuration is interfering with memories...

I disabled all apps (except for: File Sharing, Memories, Two-factor authentication) and started a new private browser session.

When loading Memories i got an error in the web console:
![Screenshot 2023-08-23 at 10 09 26](https://github.com/pulsejet/memories/assets/68034778/0bdfbc0b-a367-4f93-befd-38e0e43826cf)

When i try to click the info or favorite button there is still nothing happening unfortunately.

**Comment by rmu1987** [comment]
When i want to delete a picture; the button works (i get a "loading" gif (3 dots)) and when i wait for a long time i get a Gateway Timeout in the console for:
XHRSEARCH https://DOMAIN/remote.php/dav/ [HTTP/2 504 Gateway Timeout 90052ms]

Deleting files/photos in the "Files" app on Nextcloud is working fine.

**Comment by pulsejet** [comment]
Can you compare the URLs of the two requests?

**Comment by rmu1987** [comment]
Anything i can check for your investigation?

**Comment by pulsejet** [comment]
I can't reproduce this is why way, so not sure how to proceed. What you could try is a fresh docker container of Nextcloud and see if you can reproduce the issue there. If not, copying over the original configuration one-by-one might uncover where it fails.

**Comment by rmu1987** [comment]
Tested in a test environment, the problem was related to the IPS in my firewall.
Disabled the IPS and everything works fine.

Thanks!
