### ISSUE TITLE
Can't share pictures from an album

### ISSUE THREAD

**Issue by ThowZzy** [pulsejet/memories#780]
**Describe the bug**
Sharing a picture does not work when sharing from an album.

**To Reproduce**
Go to an album and share a picture from the memories app, nothing happens and errors are thrown in console.

**Screenshots**
![image](https://github.com/pulsejet/memories/assets/61882536/998e7f51-2942-43e3-ad67-ada48c8bad89)
![image](https://github.com/pulsejet/memories/assets/61882536/c97f7790-be5f-4622-bff6-c36b90d7d9a5)

**Platform:**

- OS: Raspberry os
- Browser: Firefox & Edge
- Memories Version: 5.4.1
- Nextcloud Version: 27.0.2
- PHP Version: 8.2

**Additional context**

- Any errors in the JS console? yes
- Any errors in the Nextcloud server logs? no

**Comment by ThowZzy** [comment]
Seems like I can't share albums too :

![image](https://github.com/pulsejet/memories/assets/61882536/a3149a49-9f78-479d-be15-e27ef42c02d6)

![image](https://github.com/pulsejet/memories/assets/61882536/048c71e7-ea06-4b14-a93e-7ccde0b601bf)

**Comment by ThowZzy** [comment]
It might be a bug with my version of Nextcloud because same error in the default photo app. Might need to search a bit more

**Comment by ThowZzy** [comment]
After testing I think:
The bug is from Memories when sharing a public link only, since this option works for me on the photos app.

**Comment by pulsejet** [comment]
The network tab of the browser should have more information:
1. The URL that fails.
2. The exact response to the failed request

**Comment by ThowZzy** [comment]
I think it was on my end, it is solved. Some bugs might come from a user that has a displayname with a special character ("<") and spaces, but that probably comes from nextcloud itself.
