### ISSUE TITLE
Albums feature how to use

### ISSUE THREAD

**Issue by soliloquies** [pulsejet/memories#782]
**Create a new album, I add the name and location**
After still don't have anything.

so, the feature how to use? 

please help me!

**Comment by pulsejet** [comment]
Go to your timeline. Select some photos. Add to album in the top right corner three dot menu

**Comment by soliloquies** [comment]
thanks,

in other folders pictures or videos can add albums. 

not in the main timeline.

**Comment by pulsejet** [comment]
Not sure what you mean. Are you getting any error?
