### ISSUE TITLE
Memories thinks that "recognize" is not installed

### ISSUE THREAD

**Issue by Ra72xx** [pulsejet/memories#789]
**Describe the bug**
Despite "Recognize" being installed and working, "Memories" lists it as not available. Even 'occ app:list' shows "Recognize", so I wonder why "Memories" thinks it is not installed.
During testing "Recognize" I did deactivate it recently for some time because of a bug, it was recognized before, I don't know if this is related.
Error logs do not give any hint.

**To Reproduce**
Install "Memories" and "Recognize"

**Screenshots**
![grafik](https://github.com/pulsejet/memories/assets/3582007/a6ee2984-b121-4a89-9815-bc615add5255)

**Platform:**

- OS: Ubuntu 23.04
- Browser: Firefox
- Memories Version: 5.4.1
- Nextcloud Version: 27.0.1
- PHP Version: 8.1

**Additional context**

**Comment by pulsejet** [comment]
1. What version of recognize?
2. Have you enabled face recognition of recognize in admin settings?

**Comment by Ra72xx** [comment]
1. 4.3.2
2. No, because I'd rather try to use face_recognition for that. Don't use any face recognition right now, however.

**Comment by pulsejet** [comment]
> 2. No, because I'd rather try to use face_recognition for that. Don't use any face recognition right now, however.

That message will show up in that case. The wording could use some improvement.

**Comment by Ra72xx** [comment]
This would be my recommendation in this case, as the current wording is misleading/wrong. Thanks for the quick feedback.
