### ISSUE TITLE
Newer Videos and Live Images Files not working in Firefox

### ISSUE THREAD

**Issue by kaugummiheld** [pulsejet/memories#790]
**Describe the bug**

I'm using a managed Nextcloud instance (26.0.5) and have installed Memories via the app store. Unfortunately ffmpeg is not available there so I don't have video thumbnails.

I have dumped all of my smartphone pictures and videos into the cloud. Since I'm using Firefox on my machine I've noticed that older videos and live images are handled perfectly fine within Memories, while at some point in my timeline they stopped working. Live images are showing only the still picture. For videos the player is starting and sound is playing but no picture is shown. 

I've tried with Firefox on the win PC of a colleague and with Firefox Focus on my Android Phone - same behavior. 
*But* it seems to work with Chrome (at least for my Android Phone).

**To Reproduce**
* open Memories within Firefox
* search for a live image or video and click on it
* live image: still image, video: only sound is played
* do the same with an older file: it works normally
* do the same with Chrome: it works normally for all files

**Platform:**

- OS: Linux 6.1, Windows 10 & Android
- Browser: Firefox 116.0.2 (Linux), Firefox 116.0.3 (Windows), Firefox Focus 116.3.0 (Android) or Chrome 116.0.5845.93 (Android)
- Memories Version: 5.4.1
- Nextcloud Version: 26.0.5
- PHP Version: 8.2.8

**Additional context**
- Any errors in the JS console? -> I probably don't have access
- Any errors in the Nextcloud server logs? -> No

Has anybody an idea why this is happening? 
I'm providing each to example files here: ![Link To Shared Nextcloud Folder](https://maglit.me/chiunutious)

**Comment by pulsejet** [comment]
Do you have transcoding set up? Your live photos are probably encoded as HEVC, which isn't supported by Firefox (https://caniuse.com/hevc) so you need a transcoder to convert them to AVC.

**Comment by kaugummiheld** [comment]
I'm not sure that I'm able to do that; because, as I said, it's a managed instance where ffmpeg cannot be installed. However, I have access to a occ command line by the hoster. 

Am I able to do anything? The Memories setting page looks like this: 
![memories](https://github.com/pulsejet/memories/assets/61326100/8a16d063-4ed1-456a-b4e6-cb4911bb1f25)

**Comment by pulsejet** [comment]
Nope. Unfortunately this is a browser limitation that we can do nothing about. So the only solution would be to either install ffmpeg or use Chrome (or another browser that supports HEVC)

**Comment by kaugummiheld** [comment]
Well, I see. Thank you for your time and effort!
I'm closing this issue then.
