### ISSUE TITLE
[Feature] Close Viewer by clicking in blank area outside of photo

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#796]
**Is your feature request related to a problem? Please describe.**
Currently the only way to close the viewer is to click the `X` at the top right of the viewer.
On Mobile, we can also swipe up or down on the photo to return to the timeline.

**Describe the solution you'd like**
It would be nice to be able to have a slightly easier way to close the viewer on desktop. Many photo viewers allow the user to click/tap into the black area around the photo to close the viewer. This would probably work with Memories, however we may want to ignore clicks/taps too close to the right/left arrow buttons (Perhaps the right 5% and left 5% would be ignored)

**Describe alternatives you've considered**
It's not an issue to click the top right 'X', it's just very slightly inconvenient when jumping back and forth between the timeline and viewer.

**Comment by pulsejet** [comment]
I'm not entirely sure this would be intuitive. Google Photos just goes next and back on clicking in the black space.

> Currently the only way to close the viewer is to click the `X` at the top right of the viewer.

On desktop I just use the escape key. Would that work?
