### ISSUE TITLE
Provide a search facility on Exif data like title, description 

### ISSUE THREAD

**Issue by gzh1960** [pulsejet/memories#797]
**Is your feature request related to a problem? Please describe.** 
Congrats on an amazing app. No
A clear and concise description of what the problem is. 
It would be nice to search on Exif data like titles and descriptions. I don't always need to tag a photo but I may edit the title or description metadata. At a later time I would like to search for either the title or parts of description.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Only way I have found today to achieve the search is to put it in the Nextcloud comments.

**Additional context**
Add any other context or screenshots about the feature request here. None

**Comment by pulsejet** [comment]
#674
