### ISSUE TITLE
Nextcloud 25 albums integration

### ISSUE THREAD

**Issue by pulsejet** [pulsejet/memories#80]
Nextcloud 25 Photos has support for albums. Integrating the same framework should be useful. Incremental implementation.

TODOs:
- [x] API: Album query (can't be a transform - no directory restriction)
- [x] UI: Albums list view [webdav]
- [x] UI: Separate shared albums list view [webdav]
- [x] UI: Album timeline view [query]
- [x] UI: Album selection modal [port if possible]
- [x] UI: Add selection to album [selection modal][webdav]
- [x] UI: Delete selection from album [webdav]
- [x] UI: Delete album [webdav]
- [x] UI: Create album from add
- [x] UI: Create album modal from albums
- [x] UI: Edit album modal from albums
- [x] UI: Add collaborator [port]
- [x] UI: Check permissions when showing album controls (shared)
- [x] UI: Add to shared album
- [x] UI: Show album as shared in add list
- [x] UI: Show preview for shared album files
- [x] UI: Opening Shared Album file

**Comment by Akruidenberg** [comment]
Is it possible to create albums from subfolders with this? Would be nice to automate this sort of things.

**Comment by pulsejet** [comment]
I've been thinking the same thing. Broadly there are two kinds of shared "albums" one might implement:
1/ "Collaborative" albums where individual photos are owned by individual users. They take space in their quota, for example.
2/ "Shared" albums where one user owns everything, but others can upload to it.

The former is NC25 and the latter is basically a shared folder. So we'll eventually want conversion between the two, for example:

1/ Converting the "shared" folder ("album") to a "collaborative" album (the same way you "share" an album in something like Google Photos)
2/ Converting a "collaborative" album to "shared". Basically entails copying over all files in the album to your own quota; this ensures that if someone deletes the original files then you still have them.

Of course this is a lot of work and I'll probably never get there without more help.
