### ISSUE TITLE
Nvidia Hardware Transcoding HLS Issue + Fix

### ISSUE THREAD

**Issue by Civlac** [pulsejet/memories#800]
**The bug**
NVENC accelerated transcoding succeeds, but the client's video will not play since the files are not sliced at all.
When a video is requested from the client, transcoding begins, however it creates a single .ts file. Due to the size of transcoding an entire video, the browser appears to timeout, and sends a request for a lower resolution, repeating the process.

**To Reproduce**
Enable NVENC accelerated encoding. Temporal AQ is disabled, using the CUDA scaler.
Play a video through memories with a quality setting making use of transcoding.
Check the size of the .ts file created (/tmp/go-vod/*/*.ts). 

**To Fix**
After pulling the command from the log file (/tmp/go-vod/*.log), I was able to recreate the issue (successfully transcode the file, but only output a single .ts file. FFmpeg reported EXT-X-TARGETDURATION:246 once complete). I added `-hls_flags split_by_time` to the command, and it correctly created multiple .ts files in the output directory, and FFmpeg logged EXT-X-TARGETDURATION:3.
CPU transcoding worked from the beginning, and I had no issue transcoding files with libx264 and the split_by_time flag.

**Platform:**
- Browser: Chrome
- Memories Version: 5.4.1
- Nextcloud Version: 27.0.2
- PHP Version: 8.1.22
- GPU: Nvidia GTX 1070
- GPU Driver Version: 535.104.05

**Additional info**
Unsure if this is a separate bug, but the NPP scaler throws the following error:
```
Starting VOD server
2rtzftsh43n0: new manager for /storage/144959.mp4
2rtzftsh43n0-max: stopping stream
2rtzftsh43n0-max: /usr/local/bin/ffmpeg -loglevel warning -hwaccel cuda -i /storage/144959.mp4 -copyts -vf format=nv12|cuda,hwupload,scale_npp=force_original_aspect_ratio=decrease:passthrough=0 -profile:v main -map 0:v:0 -c:v h264_nvenc -preset p6 -tune ll -rc vbr -rc-lookahead 30 -cq 24 -map 0:a:0? -c:a aac -ac 1 -avoid_negative_ts disabled -f hls -hls_time 3 -force_key_frames expr:gte(t,n_forced*3) -hls_segment_type mpegts -start_number 0 -hls_segment_filename /tmp/go-vod/f7sd834jksdf/2rtzftsh43n0-783131264/max-%06d.ts -
ffmpeg-error: Error applying option 'passthrough' to filter 'scale_npp': Option not found
ffmpeg-error: [vost#0:0/h264_nvenc @ 0x5636b308ee00] Error initializing a simple filtergraph
ffmpeg-error: Error opening output file -.
ffmpeg-error: Error opening output files: Option not found
2rtzftsh43n0-max: ffmpeg exited with status: 8
```

Removing the `:passthrough=0` from the command appears to let it run. Again, this results in a single large .ts file unless `-hls_flags split_by_time` is added. Please let me know if this NPP filter is due to a forgotten flag when building FFmpeg.

Additionally, do we want the browser making requests to the server for lower resolution videos, even if the end user has selected a specific resolution? As discovered, if a user requests a 1080p video, but it is not supplied, why does it request for the 720p video?

**Comment by Civlac** [comment]
So I built Memories from git to try out your changes, and they appear to all be functional. CUDA & NPP scalers are creating segments, and the folder scrollbar works lovely on desktop and android. 👍

Despite the HW accel transcoding pumping out segments faster, I'm still having issues with playback.

You say it shouldn't be requesting the other playlists, but it seems it still is. The video is set to only 720p, and the Memories default playback setting is direct.

![image](https://github.com/pulsejet/memories/assets/42948607/e9a85038-e231-49e1-8179-ee170287d592)



```
VIDEOJS: WARN: Problem encountered with playlist 2-720p.m3u8. Excessive main segment downloading detected. Switching to playlist 0-360p.m3u8.
(anonymous) @ video.es.js:218
log.warn @ video.es.js:391
excludePlaylist @ video.es.js:47380
checkSegmentDownloads_ @ video.es.js:48279
updateend @ video.es.js:48125
data.dispatcher @ video.es.js:2144
trigger @ video.es.js:2275
trigger @ video.es.js:2621
handleAppendsDone_ @ video.es.js:42802
checkAppendsDone_ @ video.es.js:42707
(anonymous) @ video.es.js:43144
shiftQueue @ video.es.js:43082
(anonymous) @ video.es.js:43254
```

And FFmpeg is definitely being invoked to render all these other resolutions, as seen in `nvtop` in Ubuntu, and the fact all the browser requests have response data.

For some reason, it appears the video will play for the first few seconds, but then freeze & buffer, despite the console showing 200 response status for all the following *.ts files of the requested resolution...
This does not happen with CPU transcoding.

**Comment by pulsejet** [comment]
Disclaimer: I d

**Comment by pulsejet** [comment]
Disclaimer: I don't have a NVIDIA card so can't really test anything.

Guessing from having to specify `split_by_time`, I think forcing keyframes isn't working as it should be. Can you try this patch on go-vod and see what happens?

```patch
diff --git a/stream.go b/stream.go
index 5c09ee6..42efc14 100644
--- a/stream.go
+++ b/stream.go
@@ -519,7 +519,8 @@ func (s *Stream) transcode(startId int) {
 		"-hls_time", fmt.Sprintf("%d", s.c.ChunkSize),
 		"-hls_segment_type", "mpegts",
 		"-hls_segment_filename", s.getTsPath(-1),
-		"-force_key_frames", fmt.Sprintf("expr:gte(t,n_forced*%d)", s.c.ChunkSize),
+		"-g:v:0", fmt.Sprintf("%d", s.c.ChunkSize*s.m.probe.FrameRate),
+		"-keyint_min:v:0", fmt.Sprintf("%d", s.c.ChunkSize*s.m.probe.FrameRate),
 		"-start_number", fmt.Sprintf("%d", startId),
 		"-",
 	}...)
```

**Comment by pulsejet** [comment]
BTW can you share the `720p.m3u8` being generated (see the preview tab) and the sizes of the `ts` files being downloaded (collapse the side bar and possibly need to add columns)

**Comment by Civlac** [comment]
Took me a minute to figure it out, but I was able to clone go-vod, manually make the edits, and build it. Once I directed Memories to use my custom library, videos are successfully loading on the client. 👍👍

Here's the `720p.m3u8`:
```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-TARGETDURATION:3
#EXTINF:3.000, nodesc
720p-000000.ts
#EXTINF:3.000, nodesc
720p-000001.ts
#EXTINF:3.000, nodesc
720p-000002.ts
#EXTINF:3.000, nodesc
720p-000003.ts
#EXTINF:3.000, nodesc
720p-000004.ts
#EXTINF:3.000, nodesc
720p-000005.ts
#EXTINF:3.000, nodesc
720p-000006.ts
#EXTINF:3.000, nodesc
720p-000007.ts
#EXTINF:3.000, nodesc
720p-000008.ts
#EXTINF:3.000, nodesc
720p-000009.ts
#EXTINF:3.000, nodesc
720p-000010.ts
#EXTINF:3.000, nodesc
720p-000011.ts
#EXTINF:3.000, nodesc
720p-000012.ts
#EXTINF:3.000, nodesc
720p-000013.ts
#EXTINF:3.000, nodesc
720p-000014.ts
#EXTINF:3.000, nodesc
720p-000015.ts
#EXTINF:1.758, nodesc
720p-000016.ts
#EXT-X-ENDLIST
```

**Comment by pulsejet** [comment]
So can you confirm,
1. `force_key_frames` works on CPU transcoding
2. `force_key_frames` does NOT work correctly with NVENC
3. Specifying `-g` and `-keyint_min` works correctly with NVENC

**Comment by Civlac** [comment]
I built an additional copy of go-vod without any changes, just to confirm enabling external transcoder doesn't impact the outcome.
My compiled go-vod has the exact same functionality as the included `go-vod-amd64` when placed in the `exiftool-bin` folder and updated in the memories settings page.
The modified go-vod bin then works for both NVENC and CPU transcoding. 🎉

**Comment by pulsejet** [comment]
![image](https://github.com/pulsejet/memories/assets/10709794/71e84262-868b-4cd7-b950-c19acbae39c3)
