### ISSUE TITLE
HEIF don't work and PNG is duplicated

### ISSUE THREAD

**Issue by JanisPlayer** [pulsejet/memories#811]
I noticed that .HEIF is missing, but .HEIC works. This is likely because it's missing, as indicated in [Application.php](https://github.com/pulsejet/memories/blob/fd7ac71d96ba53438a4837d41d9f6e9c7696de84/lib/AppInfo/Application.php#L51).

Additionally, there's a small error in [base.ts](https://github.com/pulsejet/memories/blob/fd7ac71d96ba53438a4837d41d9f6e9c7696de84/src/services/dav/base.ts#L25C1-L25C1), with PNG being duplicated.

Oh, by the way, I wanted to inquire whether it would be possible to add WebP to Application.php. I've already tested to see if it works. I just wanted to ask if there were any specific reasons why it hasn't been added yet.

~~When an image is named image.jpeg but is actually stored in a different format like .heif or .svg, it can logically lead to problems. I noticed this due to a bug in Instagram, which doesn't save images with the correct file extension, resulting in faulty loading when using the Zoom with Original File function. This could be resolved by examining the file more closely rather than relying solely on the file name and then providing the correct but harmless file extension, allowing the images to be treated normally again.~~

~~However, this is more of an issue caused by "well-programmed" apps like Instagram or user errors. It's not a significant concern because the harmless format is ultimately used. So, it's just a feature.~~

https://github.com/pulsejet/memories/pull/812
I have at least added the formats to the PR, if it is accepted I will open the and they can decide.
And that with the idea yes is nice to have but not absolutely necessary if yes everything is stored correctly, therefore that is crossed out.

**Comment by pulsejet** [comment]
> Additionally, there's a small error in [base.ts](https://github.com/pulsejet/memories/blob/fd7ac71d96ba53438a4837d41d9f6e9c7696de84/src/services/dav/base.ts#L25C1-L25C1), with PNG being duplicated.

Good catch; this is dead code.
 
> Oh, by the way, I wanted to inquire whether it would be possible to add WebP to Application.php. I've already tested to see if it works. I just wanted to ask if there were any specific reasons why it hasn't been added yet.

No reason particularly. Just that the format isn't widely used for Photos (I don't know if it even supports EXIF headers / manipulation)
