### ISSUE TITLE
Where are albums stored?

### ISSUE THREAD

**Issue by knowlesee73** [pulsejet/memories#818]
**Describe the bug**
I have set the Photos directory in Nextcloud Photos to the directory of choice but creating albums does not show up in the files. I moved my storage directories around to a different hard drive and none of the albums transferred to the new target.  When I look through the MariDB tables for Photos - it shows the location as blank.  Does Nextcloud treat albums as actual folders/files and I am missing a configuration somewhere perhaps?

**To Reproduce**
-Open Memories or Photos
-Go to Albums
-Add a new Album
-Save details
-Add photos to Album
-Album shows up with added pictures in Memories and Nextcloud, but there is nothing in the designated folder for Albums

**Screenshots**
![image](https://github.com/pulsejet/memories/assets/68411659/75193179-847e-4f34-ae91-f2f74036a863)

**Platform:**

- OS: Windows 11
- Browser: Chrome
- Memories Version: 5.4.1
- Nextcloud Version: 17.0.2
- PHP Version: 8.2.9

**Additional context**
I am running Nextcloud and supporting software in Docker/Portainer on a 4 core Intel Celeron Jasper Lake CPU with Ubuntu Server 22.04 using the LinuxServer-Nextcloud image

- Any errors in the JS console?  None that are relevant to the issue
- Any errors in the Nextcloud server logs?  None that are relevant to the issue

**Comment by pulsejet** [comment]
You want the `oc_photos_albums_files` table.
