### ISSUE TITLE
Configure & display EXIF data in slideshow mode

### ISSUE THREAD

**Issue by Rem-V** [pulsejet/memories#819]
**Is your feature request related to a problem? Please describe.**
I am looking for an option to add a photo description in slideshow mode since a long time, but did not find an easy way to achieve it with nextcloud

**Describe the solution you'd like**
I like the way photos are displayed with EXIF metadata on bottom left, when clicking on them in memories app

It could be nice if EXIF metadata could be also displayed in slideshow mode (especially title/description, but could also be configurable ?)

![photo](https://github.com/pulsejet/memories/assets/17928806/2aa568d6-e6c2-434e-a98c-9814828a6afb)

![slideshow](https://github.com/pulsejet/memories/assets/17928806/27d6790a-c056-4172-ba88-beafa0148cf2)

**Comment by pulsejet** [comment]
This should be low effort, adding to the next milestone
