### ISSUE TITLE
Allow user to specify directory for go-vod temp binary

### ISSUE THREAD

**Issue by asaparov** [pulsejet/memories#821]
**Is your feature request related to a problem? Please describe.**
A lot of distributions and containers have `/tmp` mounted with `noexec` for security reasons. Unless the user remove `noexec`, video transcoding will fail.

**Describe the solution you'd like**
Perhaps allow the user to specify the directory where the video transcoding can be done. This could be taken further by allowing transcoded video files to persist in a user-specified directory rather than being done on-demand (perhaps as a user option), and so the transcoding only needs to be done the first time the video is served, rather than every time.

**Comment by pulsejet** [comment]
You need `memories.vod.tempdir`. See https://memories.gallery/system-config/

**Comment by asaparov** [comment]
Also, if `memories.vod.tempdir` is specified as a non-temporary directory, would the transcoded files persist across multiple playbacks? Or does go-vod still transcode each time the video is played back?

**Comment by pulsejet** [comment]
> Also, if `memories.vod.tempdir` is specified as a non-temporary directory, would the transcoded files persist across multiple playbacks? Or does go-vod still transcode each time the video is played back?

go-vod always transcodes on the fly

**Comment by pulsejet** [comment]
You can use `memories.exiftool.tmp` now
