### ISSUE TITLE
Wrong LIVE photo orientation

### ISSUE THREAD

**Issue by ThowZzy** [pulsejet/memories#822]
**Describe the bug**
When playing live photos in portrait orientation, the orientation is wrong, they are flipped to the left.

**To Reproduce**
Play a live photo in portrait mode.

**Screenshots**

![Screenshot_2](https://github.com/pulsejet/memories/assets/61882536/5429c70f-a76a-4180-8445-1e6b3a905069)
![Screenshot_1](https://github.com/pulsejet/memories/assets/61882536/57ff252e-9de8-4bb2-b382-0ffd3e149422)

**Platform:**

- OS: Debian
- Browser: Firefox
- Memories Version: 5.4.1
- Nextcloud Version: 26.0.6
- PHP Version: 8.2

**Additional context**
I have a i5 7500 with VA-API enabled and quicksync support.
I also have "Enable streaming transpose workaround" checked because it fixes regular videos. (This option doesnt affect live photos at all).

- Any errors in the JS console? no
- Any errors in the Nextcloud server logs? no

**Comment by pulsejet** [comment]
Please provide a sample

**Comment by ThowZzy** [comment]
> Please provide a sample

https://nextcloud.thowzzy.be/index.php/apps/memories/s/QGzcP3Ek2Aiii86

**Comment by ThowZzy** [comment]
> @pulsejet I think this is a general bug with video playback and is not only live photos. I have observed the same behavior when playing videos recorded in portrait mode. These are also rotated to the left and played in landscape.

I don't personally see this behavior I have a portrait "real" video in HEVC 4k also and its in the good orientation

**Comment by langseb** [comment]
> > @pulsejet I think this is a general bug with video playback and is not only live photos. I have observed the same behavior when playing videos recorded in portrait mode. These are also rotated to the left and played in landscape.
> 
> I don't personally see this behavior I have a portrait "real" video in HEVC 4k also and its in the good orientation

To test this I toked a short video with iPhone 13 .mov FullHD. Preview was generated in portrait mode but playback starts in landscape.

But I was also able to drill down that this is only connected to the transcoding.

If I disable Video Transcoding the orientation is correct. Also with the playback of live photos!

**Comment by ThowZzy** [comment]
Yes for my initial issue it is related to the transcoding (i can't stream HEVC from my non-safari browser)

**Comment by ThowZzy** [comment]
> > > @pulsejet I think this is a general bug with video playback and is not only live photos. I have observed the same behavior when playing videos recorded in portrait mode. These are also rotated to the left and played in landscape.
> > 
> > 
> > I don't personally see this behavior I have a portrait "real" video in HEVC 4k also and its in the good orientation
> 
> To test this I toked a short video with iPhone 13 .mov FullHD. Preview was generated in portrait mode but playback starts in landscape.
> 
> But I was also able to drill down that this is only connected to the transcoding.
> 
> If I disable Video Transcoding the orientation is correct. Also with the playback of live photos!
> 
> --> Further testing has shown that the problem only occurs when hardware acceleration is active. In my case VA-API acceleration was active. After deactivation all videos are displayed in the correct orientation.

I just recorded two videos in portrait 4K one 2sec and one 5sec and still they are in the right orientation, so that's weird.
I only have the issue with live videos.

**Comment by ThowZzy** [comment]
@pulsejet Could the transpose workaround not be applied to live photos? I suspect that would be it

**Comment by pulsejet** [comment]
> Can you confirm you have "Enable streaming transpose workaround" checked ? I don't think your issue is the same

Try this @langseb

> @pulsejet Could the transpose workaround not be applied to live photos? I suspect that would be it

That's exactly what's needed. I suspect the bug arises from the inability of go-vod to detect rotation in this case. I'm still traveling for a couple more weeks so this might take time to fix unless someone is willing to contribute a fix.

**Comment by ThowZzy** [comment]
> > Can you confirm you have "Enable streaming transpose workaround" checked ? I don't think your issue is the same
> 
> Try this @langseb
> 
> > @pulsejet Could the transpose workaround not be applied to live photos? I suspect that would be it
> 
> That's exactly what's needed. I suspect the bug arises from the inability of go-vod to detect rotation in this case. I'm still traveling for a couple more weeks so this might take time to fix unless someone is willing to contribute a fix.

Thank you, I can wait :). I might look but I probably don't have the required knowledge

**Comment by ThowZzy** [comment]
Just updating my case:
Since I now switched from firefox to Ungoogled Chromium, I don't need to transcode my HEVC videos anymore (live photos also). So it's working better like this.

But it's still an issue if people wants to keep transcoding.

**Comment by mipro98** [comment]
I also noticed this behavior in my instance. It's especially annoying since nowadays more and more of generic phone videos get captured in portrait mode. The generated preview however is correct but as soon as playback is started, the orientation is wrong.

If it helps, I extracted a HLS segment of the transcoded video with wrong orientation and `ffprobe`d it for reference:

<details>
<summary>Original video (correctly rotated when played without transcoding or via VLC etc.):</summary>

```diff
$> ffprobe IMG_6913.mov 

ffprobe version n6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13.2.1 (GCC) 20230801
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpl --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'IMG_6913.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2023-09-23T21:02:15.000000Z
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 12 Pro
    com.apple.quicktime.software: 16.6
    com.apple.quicktime.creationdate: 2023-09-18T10:44:49+0200
    com.apple.photos.originating.signature: ATwlz+KBaylp+tnEsFoo8wl2g5HN
  Duration: 00:00:22.39, start: 0.000000, bitrate: 37721 kb/s
  Stream #0:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 94 kb/s (default)
    Metadata:
      creation_time   : 2023-09-23T21:02:15.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 3840x2160, 37551 kb/s, 59.95 fps, 59.94 tbr, 600 tbn (default)
    Metadata:
      creation_time   : 2023-09-23T21:02:15.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : H.264
    Side data:
+      displaymatrix: rotation of -90.00 degrees
  Stream #0:2[0x3](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2023-09-23T21:02:15.000000Z
      handler_name    : Core Media Metadata
  Stream #0:3[0x4](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2023-09-23T21:02:15.000000Z
      handler_name    : Core Media Metadata
  Stream #0:4[0x5](und): Data: none (mebx / 0x7862656D), 69 kb/s (default)
    Metadata:
      creation_time   : 2023-09-23T21:02:15.000000Z
      handler_name    : Core Media Metadata
```
</details>

<details>
<summary>Transcoded fragment (extracted from go-vod /tmp directory)</summary>

```
$> ffprobe max-000006.ts 

ffprobe version n6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13.2.1 (GCC) 20230801
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpl --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[h264 @ 0x55dcab157ec0] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x55dcab157ec0] decode_slice_header error
[h264 @ 0x55dcab157ec0] no frame!
Input #0, mpegts, from 'max-000006.ts':
  Duration: 00:00:02.98, start: 19.395467, bitrate: 51176 kb/s
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 3840x2160, 59.94 fps, 59.94 tbr, 90k tbn
  Stream #0:1[0x101](und): Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, mono, fltp, 72 kb/s
```
</details>


According to the logs, transcoding is done via following `ffmpeg` command:

```bash
/usr/local/bin/ffmpeg -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i /var/www/html/data/User/files/some/path/IMG_6913.mov -copyts -vf format=nv12|vaapi,hwupload,scale_vaapi=force_original_aspect_ratio=decrease:format=nv12 -profile:v main -map 0:v:0 -c:v h264_vaapi -global_quality 25 -map 0:a:0? -c:a aac -ac 1 -avoid_negative_ts disabled -f hls -hls_flags split_by_time -hls_time 3 -hls_segment_type mpegts -hls_segment_filename /tmp/go-vod/fxqz8cd0voj0-139466352/max-%06d.ts -force_key_frames expr:gte(t,n_forced*3) -start_number 0 -
```
