### ISSUE TITLE
Memories uses file creation date for image instead of creation date from metadata

### ISSUE THREAD

**Issue by pktiuk** [pulsejet/memories#824]
**Describe the bug**
Memories uses date of file creation to put things on timeline instead a `Date created` from file metadata

**To Reproduce**
Just download file, do something with it (for example rotate) and upload. Now it will be treated as a picture done now.

**Screenshots**

File explorer
![image](https://github.com/pulsejet/memories/assets/45544416/2c387eaa-a7a4-4d94-8131-1f443f11a169)
vs memories
![image](https://github.com/pulsejet/memories/assets/45544416/3910cdbd-a8ee-4a4e-b364-4da213106a0c)

**Platform:**

- Memories Version: 5.4.1
- Nextcloud Version: 27.1.0

**Comment by pktiuk** [comment]
I think a regular file creation date should be a fallback option.

**Comment by pulsejet** [comment]
> **To Reproduce** Just download file, do something with it (for example rotate) and upload. Now it will be treated as a picture done now.

If your file has EXIF data, then whatever tool you're using to edit it is removing the EXIF. The EXIF date is used for sorting; everything else is filesystem dependent and unreliable. Do the rotation using memories itself (or use a better software) to preserve the metadata.

Please provide a sample file where the metadata app shows the correct date but memories doesn't.

**Comment by pktiuk** [comment]
My bad exif binary was broken, because I migrated from arm machine to x86.

**Comment by pulsejet** [comment]
Ahh, I see. FYI, https://memories.gallery/troubleshooting/#moving-from-x86-to-arm-or-vice-versa

**Comment by pktiuk** [comment]
I still had some issues with my photos, and it appeared that some of them have `GPSDateTime`, but not `CreateDate`. I tackled it in the PR: https://github.com/pulsejet/memories/pull/827
