### ISSUE TITLE
Hidden folders are shown in timeline

### ISSUE THREAD

**Issue by Emporea** [pulsejet/memories#825]
Currently, when a folder contains a ".nomemories" file, it's hidden as expected, also the preview generator works as intended, generating previews for the content. However, there's a slight issue with indexing.

The problem is that "Memories" doesn't generate an index for folders with ".nomemories" files. Even if you enable the "show hidden folders" option in settings, the folder with ".nomemories" remains unindexed.

I understand that opinions on this may differ, but I believe it could be really helpful if the "Memories" app could also index folders with ".nomemories" files. This would make it easier for users to manage and access their content, even when they choose to hide specific memories.

If you're not keen on indexing all ".nomemories" folders, perhaps you could consider introducing a new file extension like ".nomemoriesbutindexplease" (50% joke) to explicitly indicate the need for indexing.

**Comment by pulsejet** [comment]
You're confusing two different things. The purpose of these files is to prevent indexing to begin with. If you want to index a folder but hide it, just start the folder name with a dot and it'll be hidden.

**Comment by pulsejet** [comment]
Ah, so you're trying to hide something from the timeline but be able to view it in the folders view? That would indeed need a new solution; for now the only thing you can do is specify multiple timeline folders excluding the ones you want to hide

**Comment by pulsejet** [comment]
Actually it's an interesting question whether hidden folders should show up in the timeline at all. I'm inclining towards no, so maybe this can be classified as a bug.

**Comment by pulsejet** [comment]
That seems to make sense. I can't see a use case where showing hidden folders in the timeline makes sense (then they're not really "hidden")
