### ISSUE TITLE
Wrong index on panoramic photos

### ISSUE THREAD

**Issue by Pinipon88** [pulsejet/memories#826]
**Describe the bug**
When indexing the photos I've found that the panoramic photos (previously on GPhotos, and processed with exiftool-scripts-for-takeout) are not indexed properly as they are brought to the upload date instead of the photo-taken date, it happens just for the panoramic photos, not on normal photos or videos.

**Platform:**

- OS: Umbrel OS
- Browser: Brave
- Memories Version: 5.4.1
- Nextcloud Version: 25.0.1

**Comment by pulsejet** [comment]
Please provide a sample.

**Comment by Pinipon88** [comment]
I've realised that the problem was when changing the exif information, it seems that the script doesn't process that well, it's not a problem of Memories, sorry.

**Comment by pulsejet** [comment]
Is this script the one memories comes with, or something else?
