### ISSUE TITLE
People Page emtpy

### ISSUE THREAD

**Issue by illnesse** [pulsejet/memories#83]
![image](https://user-images.githubusercontent.com/40355982/196739633-a1be5bae-8eaa-423a-bcd6-5c305fd5614b.png)

My NAS (which is the external storage for all photos) went down some time ago, after remount & rebooting the nextcloud container the People tab in Memories was empty. 
I tried running files:scan and memories:index (index needed a full rebuild apparently), still nada. Might be a recognize problem as it was spitting lots of div by zero errors during that time

**Comment by pulsejet** [comment]
Does the Photos app show them?

**Comment by illnesse** [comment]
I started from scratch, somehow my clusters got messed up. They still showed in Photos (albeit grey) but not in Memories. So i emptied the tables, rebuilt recognize with zero safety and started classifying from scratch, it's now 10 minutes in, 3 clusters showing in Photos, 0 in Memories.

memories/api/faces: []

**Comment by illnesse** [comment]
```
Checked 86145 files in 33.12 sec
3753 not valid media items
```
btw, any idea what those 3753 items are? it should be all images & videos

**Comment by pulsejet** [comment]
> I started from scratch, somehow my clusters got messed up. They still showed in Photos (albeit grey) but not in Memories. So i emptied the tables, rebuilt recognize with zero safety and started classifying from scratch, it's now 10 minutes in, 3 clusters showing in Photos, 0 in Memories.
> 
> `memories/api/faces` response: `[]`

Are these clusters for photos in your `Timeline Path`? Memories only shows Photos/faces from there (so you'll have more in Photos).

> ```
> Checked 86145 files in 33.12 sec
> 3753 not valid media items
> ```
> 
> btw, any idea what those 3753 items are? it should be all images & videos

Anything outside MIMEs defined in https://github.com/pulsejet/memories/blob/master/lib/AppInfo/Application.php

**Comment by illnesse** [comment]
> Are these clusters for photos in your `Timeline Path`? Memories only shows Photos/faces from there (so you'll have more in Photos).

Nope it's all within the path i specified, used to work fine yesterday

> Anything outside MIMEs defined in https://github.com/pulsejet/memories/blob/master/lib/AppInfo/Application.php

It's all jpg png gif mp4 etc, maybe i'll add some debug code to spit out the "invalid" paths & filenames

**Comment by pulsejet** [comment]
> Nope it's all within the path i specified, used to work fine yesterday

That is strange. Any chance you could get a SQL/CSV dump of a portion of the tables? In particular the last parts of `oc_filecache`, `oc_memories`, `oc_recognize_face_detections` and `oc_recognize_face_clusters`

> > Anything outside MIMEs defined in https://github.com/pulsejet/memories/blob/master/lib/AppInfo/Application.php
> 
> It's all jpg png mp4 etc, maybe i'll add some debug code to spit out the "invalid" paths & filenames

Adding `var_dump($file->getPath());` to `TimelineWrite::processFile` should do the trick (just before it returns for invalid file type).

**Comment by illnesse** [comment]
Ok the invalid ones were mostly webm, wmv, avi etc, all good

[sqldumps.zip](https://github.com/pulsejet/memories/files/9824695/sqldumps.zip)

**Comment by illnesse** [comment]
> Are these clusters for photos in your `Timeline Path`?

Actually, i just double checked, the 3 clusters it found so far are from music album covers, **not** in the timeline path. So i'll just let it classify everything over night, then check again tomorrow. Don't worry about it 😄

**Comment by pulsejet** [comment]
Yeah, I guess recognize still has a stability issue. I broke it a couple of times too :(

**Comment by pulsejet** [comment]
> ... is it a performance thing?

Nah. Does preview work for these? If yes then we can flip them back on.

**Comment by illnesse** [comment]
bmp, webm, m4v, mov, mkv and gif seem to work (don't have any ogg video to test)
avi & wmv show thumbnails but it only download the file on click, (although i guess that's up to the supported MIME types in the browser, maybe with vlc plugins or something similar you can actually view them in the browser)

**Comment by illnesse** [comment]
Also, clusters are back :)

**Comment by pulsejet** [comment]
Awesome.

> bmp, webm, m4v, mov, mkv and gif seem to work (don't have any ogg video to test) avi & wmv show thumbnails but it only downloads the file on click

Let's enable these then. Why do you have a bmp haha?

**Comment by illnesse** [comment]
memes from the 90s 👴🏻
