### ISSUE TITLE
504 error when adding collaborators to album

### ISSUE THREAD

**Issue by mhzawadi** [pulsejet/memories#831]
**Describe the bug**
Sharing an album with a user throws an error

**To Reproduce**
- make new album
- add some photos
- share with a user
- get an error

**Screenshots**
![Screenshot 2023-09-23 at 21 47 47](https://github.com/pulsejet/memories/assets/11944327/2c967012-b5f2-4a0f-9f36-2ce6921b63fb)

**Platform:**

- OS: Mac OS 13.5.2 (22G91)
- Browser: Vivaldi
- Memories Version: 5.4.1
- Nextcloud Version: 27.1.1
- PHP Version: 8.1

**Additional context**
This only happens with 1 user, always this user

- Any errors in the JS console?
```
memories-main.js?v=26ec5042-47:2 Error: Invalid response: 504 
    at o (memories-main.js?v=26ec5042-47:2:1268609)
    at t.handleResponseCode (memories-main.js?v=26ec5042-47:2:1268860)
    at memories-main.js?v=26ec5042-47:2:1244734
    at memories-main.js?v=26ec5042-47:2:1244191
    at Object.next (memories-main.js?v=26ec5042-47:2:1244296)
    at a (memories-main.js?v=26ec5042-47:2:1243010)
Ir @ memories-main.js?v=26ec5042-47:2
await in Ir (async)
handleSetCollaborators @ memories-main.js?v=26ec5042-47:2
click @ memories-main.js?v=26ec5042-47:2
bn @ memories-main.js?v=26ec5042-47:2
n @ memories-main.js?v=26ec5042-47:2
click @ memories-main.js?v=26ec5042-47:2
bn @ memories-main.js?v=26ec5042-47:2
n @ memories-main.js?v=26ec5042-47:2
o._wrapper @ memories-main.js?v=26ec5042-47:2
```
- Any errors in the Nextcloud server logs?
No other errors I can find

**Comment by mhzawadi** [comment]
have confirmed this only happens with 1 user on my system and they do have memories setup

**Comment by pulsejet** [comment]
Any more details, e.g. is this a big album or anything special about this user?

Just a note: this is a bug with the Photos albums backend rather than Memories, so it'll need to be fixed [upstream](https://github.com/nextcloud/photos).

**Comment by mhzawadi** [comment]
Hi @pulsejet 

I have opened a bug report upstream - https://github.com/nextcloud/photos/issues/2065
This happens with a new empty album, I have checked the user account and cant find anything special about them. If you think of anything I can check Im the admin for the server

**Comment by mhzawadi** [comment]
dont use `&` in user names 😞
