### ISSUE TITLE
Add hwtranscoding container to AIOs community containers to make configuration for them easier

### ISSUE THREAD

**Issue by szaimen** [pulsejet/memories#834]
Hi, I just wanted to mention that AiO has this now: https://github.com/nextcloud/all-in-one/tree/main/community-containers#how-to-add-containers. So the community could potentially add the hwtranscoding container 
 as additional container there. Feel free to ping me if you should need help on this!

**Comment by szaimen** [comment]
Hi, I may leave this here as an example:

```json
{
    "aio_services_v1": [
        {
            "container_name": "nextcloud-aio-memories",
            "display_name": "Transcoding container for memories",
            "documentation": "https://github.com/nextcloud/all-in-one/tree/main/community-containers/memories",
            "image": "pulsejet/aio-memories",
            "image_tag": "v1",
            "internal_port": "47788",
            "restart": "unless-stopped",
            "environment": [
                "TZ=%TIMEZONE%"
            ],
            "volumes": [
                {
                    "source": "%NEXTCLOUD_DATADIR%",
                    "destination": "/mnt/ncdata",
                    "writeable": false
                }
            ],
            "devices": [
                "/dev/dri"
            ],
            "aio_variables": [
                "nextcloud_enable_dri_device=true"
            ],
            "nextcloud_exec_commands": [
                "php /var/www/html/occ app:install memories",
                "php /var/www/html/occ config:system:set memories.vod.external --value true --type bool",
                "php /var/www/html/occ config:system:set memories.vod.connect --value nextcloud-aio-memories:47788"
            ]
        }
    ]
}
```

**Comment by szaimen** [comment]
If you need help for publishing this on docker hub, see e.g. https://github.com/szaimen/aio-fail2ban/blob/main/.github/workflows/docker-build.yml as an example.

**Comment by pulsejet** [comment]
BTW one thing that still needs to be figured out is if we can legally ship pre-built docker images that use `non-free` and `gpl` ffmpeg binaries.

**Comment by szaimen** [comment]
> Very cool, loved how you've automated the system config with `occ`. Will reach out if I've any questions when I get to this.

Thanks! And yes, please do :)

> BTW one thing that still needs to be figured out is if we can legally ship pre-built docker images that use `non-free` and `gpl` ffmpeg binaries.

True, I cannot answer this unfortunatrly.

**Comment by szaimen** [comment]
@pulsejet Now that v6.0.0 is out, would you mind opening the PR in the AIO repo?

**Comment by pulsejet** [comment]
Will do. Drowned in work atm.

**Comment by szaimen** [comment]
> Will do. Drowned in work atm.

All good! Take your time :)

**Comment by szaimen** [comment]
Do you want me to create the PR for you?

**Comment by pulsejet** [comment]
Help's always welcome 😅 
I almost started on this a couple days ago but testing anything docker isn't very straightforward for me because my entire dev setup has to run in a container.

**Comment by szaimen** [comment]
See https://github.com/nextcloud/all-in-one/pull/3736

**Comment by pulsejet** [comment]
This seems to work fine and I don't think we need any change in Memories is needed, so gonna roll it forward to the next version.

**Comment by pulsejet** [comment]
Still needs docs

**Comment by pulsejet** [comment]
v7.7.0 is stable 🎉
