### ISSUE TITLE
"Fetching a new token" infinite loop in console

### ISSUE THREAD

**Issue by d3relict** [pulsejet/memories#835]
**Describe the bug**
After some time in idle, i get a line on console: `OC.requestToken changed ...`, which seems to be the result of a CSRF token update (seemingly fine). Immediately after this, if i try to open media, or just browse the timeline, i'll get an infinite loop of console logs:
```
GET https://.../index.php/apps/memories/api/days/19486%2C19485%2C19484%2C19483%2C19482%2C19481%2C19480%2C19479%2C19478%2C19477%2C19476%2C19475%2C19474%2C19473%2C19472%2C19471 412 (Precondition failed)
Request to https://.../index.php/apps/memories/api/days/19486%2C19485%2C19484%2C19483%2C19482%2C19481%2C19480%2C19479%2C19478%2C19477%2C19476%2C19475%2C19474%2C19473%2C19472%2C19471 failed because of a CSRF mismatch. Fetching a new token
```
I can only recover from this by refreshing the page.

**To Reproduce**
Open the timeline of Memories, wait until the `OC.requestToken changed` line appears in console, and then try to navigate the page.

**Screenshots**
N/A (does not seem necessary)

**Platform:**

- OS: Windows
- Browser: Chome x64 latest
- Memories Version: 5.4.1
- Nextcloud Version: 27.1.1
- PHP Version: 8.1.2

**Additional context**
NextCloud is hosted on Apache2, accessed via an Nginx reverse proxy (with certbot).

- Any errors in the JS console? only those stated above
- Any errors in the Nextcloud server logs? nothing obvious

**Comment by amirulasri** [comment]
Same here, still no fixes. It loops until refresh the page, when navigating to Albums, its stops from working and just showing 3 dots infinite loading.

![Screenshot 2023-11-24 225408](https://github.com/pulsejet/memories/assets/60568867/d55c1f02-52fc-42bc-b6d8-69558a17a1fa)

**Comment by pulsejet** [comment]
I've not been able to reproduce this on any machine or version of nextcloud. Can you debug further?
1. Is the request to `/csrftoken` being made? (check JS network tab).
2. Does this request return a token/
3. Does the next request carry this (correct) token?
4. Is the user getting logged out automatically due to inactivity?

**Comment by farhills** [comment]
I left the memories main landing page open ~2h (I got busy with work).  After clicking 'Albums', nothing loads. The browser console is getting spammed with the following errors.  It looks like the a GET is failing with HTTP 412.

I don't know anything about webdev, so if there's something more you need to track this down, please give me detailed instructions for what to get.

![Capture](https://github.com/pulsejet/memories/assets/83388006/b41b03d6-40b4-4482-9d41-f71008f96869)

Expanding the errors.  The async call repeats many more times for each, and the number of errors is counting up continuously
![image](https://github.com/pulsejet/memories/assets/83388006/3bb998f6-aea4-4c20-995a-82b046b83202)

![image](https://github.com/pulsejet/memories/assets/83388006/32b970f8-8f52-4226-8971-f54a7c1adf7c)


```Request URL:
https://xxx/apps/memories/api/clusters/albums
Request Method:
GET
Status Code:
412 Precondition Failed
Remote Address:
xxx
Referrer Policy:
no-referrer
Cache-Control:
no-cache, no-store, must-revalidate
Content-Length:
31
Content-Security-Policy:
default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
Content-Type:
application/json; charset=utf-8
Date:
Fri, 24 Nov 2023 21:46:07 GMT
Expires:
Thu, 19 Nov 1981 08:52:00 GMT
Feature-Policy:
autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
Pragma:
no-cache
Referrer-Policy:
no-referrer
Server:
nginx
Strict-Transport-Security:
max-age=15768000; includeSubDomains;
X-Content-Type-Options:
nosniff
X-Download-Options:
noopen
X-Frame-Options:
SAMEORIGIN
X-Permitted-Cross-Domain-Policies:
none
X-Request-Id:
vu5lisJHM8EfMnSAryxv
X-Robots-Tag:
noindex, nofollow
X-Robots-Tag:
noindex, nofollow
X-Xss-Protection:
1; mode=block
:authority:
xxx
:method:
GET
:path:
/apps/memories/api/clusters/albums
:scheme:
https
Accept:
application/json, text/plain, */*
Accept-Encoding:
gzip, deflate, br
Accept-Language:
en-US,en;q=0.9
Cookie:
__Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=xxx; oc_sessionPassphrase=xxx; nc_token=xxx nc_session_id=xxx
Dnt:
1
Requesttoken:
xxx=
Sec-Ch-Ua:
"Brave";v="119", "Chromium";v="119", "Not?A_Brand";v="24"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"Windows"
Sec-Fetch-Dest:
empty
Sec-Fetch-Mode:
cors
Sec-Fetch-Site:
same-origin
Sec-Gpc:
1
User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36```

The NC server log is full of errors relating to files with missing/corrupted EXIF data.  I'm aware of these files, they were recovered from a failed SD card, some of the files were in pretty bad shape.  These are coming up at the same time, not sure if related?  I can email you the file if you want to play with it.
![image](https://github.com/pulsejet/memories/assets/83388006/7c6f4dca-0112-4bc3-ba9e-775312950596)

**Comment by pulsejet** [comment]
The corrupted files have nothing to do with this. My question is, are there any requests to `/csrftoken` in the network tab?

The way it works is:
1. The CSRF token expires
2. Memories sends a request for anything and gets a 412 error (indicating CSRF failed)
3. Now `@nextcloud/axios` sends a request to `/csrftoken` to fetch a new token
4. This new token is now used in subsequent requests

The question is, whether step 3 is happening and the new token is used in the later requests

**Comment by pulsejet** [comment]
```
Requesttoken:
xxx=
```
need to check the real value here, and whether it makes sense

**Comment by farhills** [comment]
Ran it again.  The timeout is about 15 minutes.

Leaving it on the main page, the first sign of a problem is the heartbeat fail.

I'm not a programmer (unless VBA counts), so no idea if the token makes sense or not.  On each of the repeated requests, the token is the same value `ZD+...TyCg `

If you need something specific, please screencap what you'd want to see in the browser so I can get it.

![image](https://github.com/pulsejet/memories/assets/83388006/4ed97c3a-4011-438e-81f3-689bfc8c08c6)

Contents of the failed heartbeat:
```
Request URL:
https://myurl.com/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json
Request Method:
PUT
Status Code:
412 Precondition Failed
Remote Address:
ip:443
Referrer Policy:
no-referrer
Cache-Control:
no-cache, no-store, must-revalidate
Content-Length:
31
Content-Security-Policy:
default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
Content-Type:
application/json; charset=utf-8
Date:
Fri, 24 Nov 2023 22:45:26 GMT
Expires:
Thu, 19 Nov 1981 08:52:00 GMT
Feature-Policy:
autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
Pragma:
no-cache
Referrer-Policy:
no-referrer
Server:
nginx
Strict-Transport-Security:
max-age=15768000; includeSubDomains;
X-Content-Type-Options:
nosniff
X-Download-Options:
noopen
X-Frame-Options:
SAMEORIGIN
X-Permitted-Cross-Domain-Policies:
none
X-Request-Id:
BGQFD9JsD7xn8w1c9Uif
X-Robots-Tag:
noindex, nofollow
X-Robots-Tag:
noindex, nofollow
X-Xss-Protection:
1; mode=block
:authority:
myurl.com
:method:
PUT
:path:
/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json
:scheme:
https
Accept:
application/json, text/plain, */*
Accept-Encoding:
gzip, deflate, br
Accept-Language:
en-US,en;q=0.9
Content-Length:
19
Content-Type:
application/json
Cookie:
__Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=farhills; oc_sessionPassphrase=xxx=xxx; nc_token=xxx; nc_session_id=xxx
Dnt:
1
Origin:
https://myurl.com
Requesttoken:
ZD+xxx=:Lxxx=
Sec-Ch-Ua:
"Brave";v="119", "Chromium";v="119", "Not?A_Brand";v="24"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"Windows"
Sec-Fetch-Dest:
empty
Sec-Fetch-Mode:
cors
Sec-Fetch-Site:
same-origin
Sec-Gpc:
1
User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
```

Navigating to  'Albums' initiates the filed request loop:
![image](https://github.com/pulsejet/memories/assets/83388006/29b06186-561c-4c8a-a410-f460308e602b)

csrftoken:
![image](https://github.com/pulsejet/memories/assets/83388006/c870b101-ebca-4d92-a95a-dccb237d0806)

albums:
![image](https://github.com/pulsejet/memories/assets/83388006/d805d784-508d-4f1a-bf12-4caa9a4969fd)

**Comment by pulsejet** [comment]
> On each of the repeated requests, the token is the same value ZD+...TyCg 

This is the problem. The token should be a new value every time. I think your http server is caching the `/csrftoken` return value

**Comment by pulsejet** [comment]
Hold on, you need to look at the "Response", this is the request header

**Comment by amirulasri** [comment]
Its true. Csrf token keeps same value and because of that, the csrf check fails.

Csrf Respone
![image](https://github.com/pulsejet/memories/assets/60568867/0f4c8abf-5240-49c6-b2e8-07cabf0fd967)

Another request
![image](https://github.com/pulsejet/memories/assets/60568867/611612af-8e28-4527-96ec-a44c161f27b4)

There is a way how to ensure that the token changes? Or if it is a cache, how to avoid it causing the requested token to be the same but without reloading the whole page?

**Comment by pulsejet** [comment]
I think you need to check your web server settings. The `/csrftoken` route should be excluded from caching in any way.

**Comment by amirulasri** [comment]
Still same, in cloudflare, I have already added /csrftoken to Cache Rules and bypass the cache
![image](https://github.com/pulsejet/memories/assets/60568867/df96cff2-be11-4223-bded-75c9c49e8cb5)

Next, enabling Development Mode also not fix the problem
![image](https://github.com/pulsejet/memories/assets/60568867/54bc4300-955c-4615-813c-7f86b74b08fb)

Even purge all caches, still same
![image](https://github.com/pulsejet/memories/assets/60568867/949a080c-1d73-46eb-b765-a15e0283ec57)

Maybe the last option is, disabling cache in web server configuration. Have a idea how syntax will looks like?? Im using Nginx as a web server

**Comment by pulsejet** [comment]
Does directly navigating to `/csrftoken` and refreshing produce the same token every time?

**Comment by amirulasri** [comment]
Yeah I got it. It returns same token until I hard refresh the web browser like CTRL + SHIFT + R
After that, token it will be different. And no errors after that.

But when I reload by just pressing reload button. Or using CTRL + R, the token will be same again

I have tried clear cache but problem still same

I trace it by using
`await fetch("https://nextcloud.example.com/csrftoken").then(response => response.json());`

On normal refresh
![image](https://github.com/pulsejet/memories/assets/60568867/17b0195d-5aa6-4e04-961e-cfe80c6830c7)

On hard refresh
![image](https://github.com/pulsejet/memories/assets/60568867/84a3a170-8b0b-49ac-9c33-fbad52fd4be4)

On Cloudflare I have already exclude /csrftoken from caching. When configuring web server by adding `location /csrftoken`, it just return http error 404.

**Comment by amirulasri** [comment]
> Does directly navigating to `/csrftoken` and refreshing produce the same token every time?

When navigating directly, the token not same and its difference every time I refresh it. But in memories. It returns the same token until I do the hard refresh. Clear cache also not help.

**Comment by pulsejet** [comment]
Can you try leaving open a different app, e.g. files, and see if that has the same or different behavior?

**Comment by amirulasri** [comment]
> Can you try leaving open a different app, e.g. files, and see if that has the same or different behavior?

At memories, it returns the same token
![image](https://github.com/pulsejet/memories/assets/60568867/25ddcdc7-7fd7-4822-97f3-fce7c171d537)

But in other apps like files, photos, it returns token with different value. I mean, its normal.
![image](https://github.com/pulsejet/memories/assets/60568867/5452f1c3-819f-48f7-91bf-624a0667986c)

I leave page opened at different apps. No errors because of token can return the differents value.

**Comment by pulsejet** [comment]
Okay we're getting somewhere now, thanks for debugging this further.

1. Can you try the same with memories _in a private window_?
2. If that works correctly, try unregistering the service worker in the application tab (maybe get a screenshot first). Also are there any service worker errors in the console?

**Comment by pulsejet** [comment]
Finally I could reproduce the error now. Thanks @amirulasri

**Comment by pulsejet** [comment]
Everyone here, please try v6.1.4

@amirulasri can you verify if this resolves the issue? You'll need to refresh a couple of times and possibly unregister the existing the service worker (hopefully not though). Unfortunately I discovered the service worker logic was completely broken and might not auto-update the worker.

**Comment by farhills** [comment]
Looking good here!  The site has been open, idle, for over an hour, no issues.  CSRF tokens are coming back with new values.

Hopefully @amirulasri can confirm the same.

Cheers!

**Comment by amirulasri** [comment]
> Hopefully @amirulasri can confirm the same.

> @amirulasri can you verify if this resolves the issue?

@farhills Yeah, already tested and no errors even I leave page opened or wait until new log `OC.requestToken` displayed

Tested!, no more csrf mismatch error loops. Thanks!!! @pulsejet

**Comment by pulsejet** [comment]
Great! Thanks for your help debugging this
