### ISSUE TITLE
Bulk updating Geo Location Metadata also changes the photo date to today's date more times than not.

### ISSUE THREAD

**Issue by Rudder2** [pulsejet/memories#838]
**Describe the bug**
Bulk updating Metadata with Geo Location sometimes updates the photo's with today's date.

**To Reproduce**
1. Select many photos
2. Select Edit Metadata
3. Change Geo Location to what you want.
4. Click Save
5. It happens sometimes.

**Screenshots**

**Platform:**

- OS: Ubuntu 22.04
- Browser: Brave version 1.58.131
- Memories Version: 5.4.1
- Nextcloud Version: 27.1.1
- PHP Version: 8.2.10

**Additional context**

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

**Comment by pulsejet** [comment]
Do the photos have the date/time in the metadata? If not, you're probably just using the modified time, which will change when you touch the file.

**Comment by aronkvh** [comment]
For me, it doesn't add the location and when I manually set the date back, it changes it to the current date instead. Doesn't happen with every photo

**Comment by pulsejet** [comment]
> Would it be possible for memories to indicate somehow which date it is using (either creation date or modified date)?

It's really hard to say where the date is coming from, since exiftool uses multiple sources to get the date, e.g. the filesystem. One way about this might be to make a check while setting the EXIF if any date tags are found; if not then pre-emptively set the EXIF tag to the best known date.

**Comment by pulsejet** [comment]
A prompt will now show if you're gonna destructively edit the date

![image](https://github.com/pulsejet/memories/assets/10709794/182e6fc2-ee1c-4016-a180-53d3b45d239f)
