### ISSUE TITLE
Live photos disappeared

### ISSUE THREAD

**Issue by Byter3** [pulsejet/memories#842]
Live photo support for live photos taken with Android (Samsung Galaxy S21 Ultra disappeared) after upgrading to the latest version.

**Comment by pulsejet** [comment]
1. Need sample
2. Are you using HEIC?

**Comment by Byter3** [comment]
Sent a sample on Discord

**Comment by pulsejet** [comment]
Samsung HEIC support was only added with https://github.com/pulsejet/memories/commit/20d049f1602f7f4c72fb07887650a47e42add7bb, so it should land with v5.5 stable

**Comment by pulsejet** [comment]
Just a note: the live videos in HEIC are HEVC, so you do need a functional `go-vod` transcoder for anything to work.
