### ISSUE TITLE
Albums without Photos App enabled?

### ISSUE THREAD

**Issue by simonspa** [pulsejet/memories#843]
**Is your feature request related to a problem? Please describe.**

It is a suboptimal user experience when two different photo apps are enabled. Memories is the clear winner in performance, feature set, usability over the NC Photos app. Yet, the latter cannot be disabled without losing the Albums feature since Memories uses Photo's API for albums (I guess?)

**Describe the solution you'd like**

It would be great to have the possibility to entirely disable the NC Photos app but still continue to have a fully-featured Memories app.

**Describe alternatives you've considered**

The NC Photos app could be hidden from the user interface, but this would require changes in the server as well as the admin UI.

**Comment by pulsejet** [comment]
See #694. The reliance on the Photos app is largely to not reinvent the wheel.
As such, having both apps enabled shouldn't affect performance, so hiding the photos app would probably do what you want.

**Comment by simonspa** [comment]
Alright, thanks!
Looks like I need to polish up my search skills on GH issues :)
