### ISSUE TITLE
Cannot find server on Android 

### ISSUE THREAD

**Issue by aronkvh** [pulsejet/memories#846]
**Describe the bug**
When I open the app I downloaded from Google Play and enter my server address it shows a toast with `"End of input at character 0 of" every time I tap "Continue to login".
`

**Platform:**
Android 12, Memories 0.5.5

**Comment by pulsejet** [comment]
1. What version of Nextcloud is this?
2. Can you go to `http://<your-nextcloud>/index.php/apps/memories/api/describe` and post the output (redact any sensitive info)
3. If possible, could you DM me (on Discord / email) your server URL?

**Comment by aronkvh** [comment]
1. Nextcloud is Hub 6 (27.1.1)
2. {"version":"5.5.0","baseUrl":"http:\/\/url.com\/index.php\/apps\/memories\/","loginFlowUrl":"http:\/\/url.com\/index.php\/login\/v2","uid":null}

**Comment by pulsejet** [comment]
So the problem is that your Nextcloud is using HTTPS but `api/describe` returns HTTP due to some missing reverse proxy config. You need to add to `config.php`:
```
'overwriteprotocol' => 'https',
```

**Comment by aronkvh** [comment]
> So the problem is that your Nextcloud is using HTTPS but `api/describe` returns HTTP due to some missing reverse proxy config. You need to add to `config.php`:
> 
> ```
> 'overwriteprotocol' => 'https',
> ```

That was the issue, I can log in now. Thanks for the help.
A dialog or accordion or just a link when an error comes up would help figure out what's wrong.

**Comment by pulsejet** [comment]
> A dialog or accordion or just a link when an error comes up would help figure out what's wrong.

Yup, this will be the case with the next version of the Android app :)
