### ISSUE TITLE
Errors in logs after autoupload photo/video

### ISSUE THREAD

**Issue by dronnikovigor** [pulsejet/memories#849]
**Describe the bug**
I'm using official android Nextcloud app to autoupload photos/videos. After updating to a new version on Memories I keep getting errors in Nextcloud logs after uploading each file:
<html>
<body>

Error | PHP | Trying to access array offset on value of type null at /var/www/html/custom_apps/memories/lib/Db/TimelineWrite.php#145
-- | -- | --

</body>
</html>
Autoupload is set to /MEDIA/PHOTOS/Upload/... and Memories are set to /MEDIA/PHOTOS/Library folder  

   
  
**To Reproduce**
1. Setup autoupload in Nextcloud App
2. Make photo and let application upload it.
3. Check error in Nextcloud logs

**Screenshots**
![image](https://github.com/pulsejet/memories/assets/4175117/ad1744a4-e522-453b-8ef2-278654f16614)

**Platform:**

- OS: Nextcloud android app
- Memories Version: 5.5.1
- Nextcloud Version: 27.1.2
- PHP Version: 8.1.23

**- Any errors in the JS console?** - No

**Comment by pulsejet** [comment]
Ah yes

**Comment by pulsejet** [comment]
Decided to make a quick release cause probably nobody upgraded to 5.5.2 yet. Thanks for the report
