### ISSUE TITLE
hide specific folders on the folders tab (show only scanned folders)

### ISSUE THREAD

**Issue by Akruidenberg** [pulsejet/memories#85]
It would be nice to add an option to show only folders which are scanned by memories itself. Maybe we set an root folder like the time line for this? Now, every server is show in the folders view, which is not family friendly :)

**Comment by pulsejet** [comment]
Showing only the scanned folders is basically impossible in any sane way. But setting a root folder for the folders view sounds like a good idea (useful for me too, in fact).
