### ISSUE TITLE
Memories (Android App) Initial Config

### ISSUE THREAD

**Issue by sunnyd24** [pulsejet/memories#855]
**Describe the bug**
@pulsejet Great work on this app, I have been looking forward to the release of this app!

A minor bug found after configuration of the app setup, pressing back goes to the start of app configuration steps again ("you are now logged in to the server", choose "set up automatic upload" or "continue"). 

**To Reproduce**
1. Install android app v1.2
2. Add server "https://this.is.my.details" address
3. Skip automatic upload
4. Grant access to media
5. Choose local folders to show on timeline, and press finish.
6. Shows Memories app home page with photos/memories
7. Pressing "back button" on phone takes you back to step 3 above.

**Screenshots**

**Platform:**

- OS: Android 13
- Browser: Edge/Chrome
- Memories Version: 5.5.3
- Nextcloud Version: 27.1.0
- PHP Version: as bundled with AIO v7.2.1

**Additional context**
n/a

- Any errors in the JS console?
- n/a
- Any errors in the Nextcloud server logs?
- n/a

**Comment by pulsejet** [comment]
Haha nice catch
