### ISSUE TITLE
Include image orientation in "Edit Metadata" menu

### ISSUE THREAD

**Issue by randyheydon** [pulsejet/memories#856]
I'll take a photo with my phone, the orientation is incorrect, and I discover it only after the photo is loaded in Memories.  I would like to be able to quickly correct orientation of such photos.  The current workflow is to use the Edit interface to rotate such images with ImageMagick, but that process [is lossy](https://www.imagemagick.org/Usage/photos/#orient) and computationally intensive (also, it doesn't work for me because I use [the Nextcloud snap](https://snapcraft.io/nextcloud) which doesn't include ImageMagick or ffmpeg).

I would rather be able to fix rotation by changing the Exif.Image.Orientation tag, which is fast and lossless, but Memories does not currently expose that in the "Edit Metadata" menu.  I currently have to download the images, edit with exiftool or exiv2, and re-upload.

I propose adding a drop-down menu allowing selection of the four rotation-only [Exif orientations](http://sylvana.net/jpegcrop/exif_orientation.html) (1, 3, 6, and 8), and maybe a "Mirrored" checkbox to expose the other four orientations (2, 4, 5, and 7).

**Comment by pulsejet** [comment]
Implemented with https://github.com/pulsejet/memories/commit/8c16eecc11614c8ef568c422bfaa1d965ab8f2bf
