### ISSUE TITLE
Android app error on initial sign in

### ISSUE THREAD

**Issue by tsmoneta** [pulsejet/memories#857]
**Describe the bug**

In the Android app, following installation, enter the server URL and hit the 'Continue to Logon' button. Get:

Failed to fetch server info.
https://nextcloud:54443/nextcloud/index.php/apps/memories/api/describe

**To Reproduce**

1. Install app from Play Store
2. Launch app
3. Enter Nextcloud server URL: https://nextcloud:54443/nextcloud
4. Tap 'Continue to Logon' button

**Screenshots**
![image](https://github.com/pulsejet/memories/assets/131212002/a44cb05d-7ac7-43ef-bbae-dcf091c34f12)

**Platform:**

- OS: Android 13
- Browser: Chrome
- Memories Version: 5.5.3 (server), 1.2 (Android app)
- Nextcloud Version: 27.1.2
- PHP Version: 8.2.11

**Additional context**

Manually entering the error message URL in Chrome responds:
"version":"5.5.3","baseUrl":"https:\/\/nextcloud:54443\/nextcloud\/index.php\/apps\/memories\/","loginFlowUrl":"https:\/\/nextcloud:54443\/nextcloud\/index.php\/login\/v2","uid":"mmoneta"}

All other Android Nextcloud apps work, including 'Photos (for Nextcloud)' which is also a Nextcloud Memories app.

- Any errors in the JS console?
N/A

- Any errors in the Nextcloud server logs?
No

**Comment by pulsejet** [comment]
By any chance is this a self signed cert?

**Comment by pulsejet** [comment]
Interesting. Probably related to #853 regardless

**Comment by tsmoneta** [comment]
Confirmed as fixed by #853

**Comment by yurividal** [comment]
> Confirmed as fixed by #853

Sorry @tsmoneta for resurrecting an old post. Just wanted to know if memories works 100% with your seld-signed cert. I'm facing an issue where I am able to login and upload photos but I can't download any photos from my memories app. The logs shoe that doenloadmanager is rejecting download due to untrusted cert.

**Comment by tsmoneta** [comment]
You should open that as a new issue.

**Comment by yurividal** [comment]
> You should open that as a new issue.

I already did. I only reached out to try to do some more investigation and understand if the issue is indeed related to the certs.
