### ISSUE TITLE
404 Errors in Console and MOV Files Not Playing in Browser

### ISSUE THREAD

**Issue by n0one42** [pulsejet/memories#862]
**Describe the bug**
I am encountering several issues with the Memories app on my Nextcloud instance, which is hosted on a freshly installed Ubuntu Server with PHP version 8.2.11. The issues primarily occur on a macOS machine using the Safari browser. On Safari, I experience numerous console errors related to `memories-vendors-node_modules_next_vue_dist_Components` that result in a 404 status. Furthermore, MOV videos created from HEIC images on my iPhone (which are automatically uploaded as JPG with the corresponding mov) are not playable within the Safari browser, although they work fine on the Memories demo page. Also the generated MOV videos are playable inside the default Nextcloud photos app and through the Files Browser.

On Firefox, these console errors are not present, but I still cannot play the MOV videos either in the default Photos app or the Files folder on Nextcloud, despite them working on the Memories demo page. I would still focus on Safari first to exclude my Firefox plugins as an source of error.

**To Reproduce**
1. Fresh installation of Nextcloud version 27.1.2 on Ubuntu Server with PHP 8.2.11.
2. Installed Memories version 5.5.3 and Recognize version 5.0.1 (which is a requirement for Memories).
3. Configured based on the documentation and also enabled hardware transcoding.
4. Uploaded HEIC images from my iPhone, which are automatically converted to JPG and MOV.
5. Attempted to play the videos / picture with live video within Safari on macOS like it does on the memories demo page.

**Screenshots**
![image](https://github.com/pulsejet/memories/assets/116060421/3158401e-59e5-46d5-b2ce-0acaa201bce8)
![image](https://github.com/pulsejet/memories/assets/116060421/e3478bc5-cde1-4944-bb71-a9ca5fe65eee)
![image](https://github.com/pulsejet/memories/assets/116060421/0302a839-548e-48fa-8722-0442b8bf9192)
![image](https://github.com/pulsejet/memories/assets/116060421/e0b98149-34db-45f4-b354-025afdff62ad)
![image](https://github.com/pulsejet/memories/assets/116060421/28f69b88-bfac-464a-9a09-88ec455c12a1)
![image](https://github.com/pulsejet/memories/assets/116060421/20f552d8-6afd-44af-a52c-d7c3cf13f67d)
![image](https://github.com/pulsejet/memories/assets/116060421/bd1c9e4c-39ad-43eb-8a7b-dd0bf2e46af0)
![image](https://github.com/pulsejet/memories/assets/116060421/d46e21a6-9a6e-4481-a3d5-e53cbacab339)
![image](https://github.com/pulsejet/memories/assets/116060421/38f593fd-5af9-40b7-96f9-b5205f58a1b4)
![image](https://github.com/pulsejet/memories/assets/116060421/3f6c51dc-28a2-4189-80e3-924676ad23dc)
![image](https://github.com/pulsejet/memories/assets/116060421/8adffcc5-6ddd-4c6e-9771-50b7a5131b91)
![image](https://github.com/pulsejet/memories/assets/116060421/702669b8-01a5-4a6e-a6c2-41f2caf358d3)
![image](https://github.com/pulsejet/memories/assets/116060421/1d8183d8-0ce2-4476-964e-f63e939949bb)
![image](https://github.com/pulsejet/memories/assets/116060421/c6163ce0-f808-4c97-9393-ded15b0616d3)
![image](https://github.com/pulsejet/memories/assets/116060421/25a892c7-81a7-420f-87ce-c2e96ad59775)
![image](https://github.com/pulsejet/memories/assets/116060421/e7233d11-ce00-4abd-a602-6ce075a208e2)

Note: Under Firefox I get also "Uncaught (in promise) DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable." 

**Platform:**

- Nextcloud version: 27.1.2
- Memories App version: 5.5.3
- Recognize Version: 5.0.1 (required for Memories)
- Server OS: Ubuntu Server with PHP 8.2.11
- Client OS: macOS
- Browser: Safari, Firefox

**Additional context**
- On Firefox, the console errors do not occur, but MOV files are still not playable in any app or folder.
- The HEIC images from my iPhone are automatically uploaded as JPG, and the corresponding MOV files for live previews are also uploaded.

Would appreciate any guidance on how to resolve these issues. Thank you!

**Comment by n0one42** [comment]
Sorry for the confusion earlier.

1. **Transcoding**: I have now disabled transcoding entirely by setting `Memories --> Video Streaming --> Enable Transcoding` to `off`.

   - **Outcome**: After disabling transcoding, live videos are now playable on Safari. However, they still do not work on Firefox.

2. **Browser Testing**: 
   - I visited the Memories demo site [here](https://demo.memories.gallery/apps/memories/folders/Photos/live) to validate that the issue is not browser-specific. Both Safari and Firefox function as expected on this demo site.
   - I also tested media types on [this sandbox](https://codesandbox.io/s/happy-platform-nwsg4u?file=%2Findex.html) and can confirm that "video/quicktime" and "video/mp4" are playable in both Safari and Firefox.

3. **Transcoder Issues**: Despite turning off transcoding, I continue to experience issues:
   - Live videos only work on Safari but not Firefox.
   - I've tested both VA-API and NVENC separately, confirming they should function based on tests with ffmpeg and nvidia-smi monitoring / VAAPI commands.

4. **Browser-Specific Errors**:
   - In Safari, despite the videos now playing, I still encounter 404 errors related to Memories components that don't appear in Firefox.
   - In Firefox, I receive a "Uncaught (in promise) DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable," even though live videos are playable on the Memories demo page.

The only error inside the logs which I get is:
"OCP\AppFramework\Db\DoesNotExistException: Did expect one result but found none when executing: query "SELECT * FROM `*PREFIX*files_versions` WHERE (`file_id` = :dcValue1) AND (`timestamp` = :dcValue2)"; "

Would appreciate further guidance on how to resolve these issues. Thank you!

**Comment by pulsejet** [comment]
So if i understand right:

|                 | Memories (Safari) | Memories (Firefox) | Files (Safari) | Files (Firefox) |
|-----------------|-------------------|--------------------|----------------|-----------------|
| Transcoding Off | ✅                 | ❌                  | ✅              | ❌               |
| Transcoding On  | ❌                 | ❌                  | ✅              | ❌               |

> Please provide some samples

**This** is the most important part.

**Comment by n0one42** [comment]
Thank you for your response. I completely reinstalled the vm and did test everything step by step. It come out that as soon as I enable the NVENC, it starts to breaks it inside memories.
```shell
ffmpeg -encoders | grep nvenc
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
 V....D h264_nvenc           NVIDIA NVENC H.264 encoder (codec h264)
 V..... nvenc                NVIDIA NVENC H.264 encoder (codec h264)
 V..... nvenc_h264           NVIDIA NVENC H.264 encoder (codec h264)
 V..... nvenc_hevc           NVIDIA NVENC hevc encoder (codec hevc)
 V....D hevc_nvenc           NVIDIA NVENC hevc encoder (codec hevc)
 ```
 I generated a video with 
 `ffmpeg -t 2 -f lavfi -i testsrc=size=1920x1080:rate=30 -an -c:v h264_nvenc output.mp4`
 and tested it again with
 `ffmpeg -i output.mp4 -vcodec h264_nvenc -acodec copy output2.mp4`
And I can see, it uses my gpu. Also nvidia-smi shows this.

**Comment by pulsejet** [comment]
> I have no log entries inside nextcloud.

Are you testing this for the same file that you generated? Also the logs go to `go-vod` for transcoding, not Nextcloud (e.g. `/tmp/go-vod/<instance-id>.log` or something)

**Comment by n0one42** [comment]
What do you exactly mean with the "Are you testing this for the same file that you generated?"
Also I had not enabled the "external transcoder go-vod"
I just enabled the HW Acceleration of Nvidia.

However, I uploaded with NVENC and / go-vod disabled some pictures and it worked as expected.
Even after enabling NVENC and go-vod, I am still able to play the old ones which were uploaded with this disabled.
But everything new live photos which I upload are not playable while NVENC is enabled but they are still playable inside Photos app.

This is pretty annoying and time consumptive

**Comment by pulsejet** [comment]
Try the CUDA scaler

![image](https://github.com/pulsejet/memories/assets/10709794/18c4bc1d-1a1b-43f9-9539-478679f83f9f)

**Comment by n0one42** [comment]
okey, at least for live photos it seams to work now.
I uploaded a 17 sec video (.mov) and it only plays like the first 2-3 seconds. Also I get this error:
```bash
2023/10/16 11:59:29 wdc4dk9h5q00-2160p: /usr/bin/ffmpeg -loglevel warning -hwaccel cuda -i /xxx/files/Photos/Test/23-09-16 23-08-42 9475.mov -copyts -vf format=nv12|cuda,hwupload,scale_cuda=force_original_aspect_ratio=decrease:passthrough=0:w=3840:h=3840 -profile:v main -maxrate 9666666 -bufsize 19333332 -map 0:v:0 -c:v h264_nvenc -preset p6 -tune ll -rc vbr -rc-lookahead 30 -cq 24 -map 0:a:0? -c:a aac -ac 1 -start_number 0 -avoid_negative_ts disabled -f hls -hls_flags split_by_time -hls_time 3 -hls_segment_type mpegts -hls_segment_filename /tmp/go-vod/ocqflifiaizy/wdc4dk9h5q00-2241657798/2160p-%06d.ts -force_key_frames expr:gte(t,n_forced*3) -
2023/10/16 11:59:34 wdc4dk9h5q00-1440p: stopping stream
2023/10/16 11:59:34 wdc4dk9h5q00-1440p: /usr/bin/ffmpeg -loglevel warning -hwaccel cuda -i /xxx/files/Photos/Test/23-09-16 23-08-42 9475.mov -copyts -vf format=nv12|cuda,hwupload,scale_cuda=force_original_aspect_ratio=decrease:passthrough=0:w=2560:h=2560 -profile:v main -maxrate 5800000 -bufsize 11600000 -map 0:v:0 -c:v h264_nvenc -preset p6 -tune ll -rc vbr -rc-lookahead 30 -cq 24 -map 0:a:0? -c:a aac -ac 1 -start_number 0 -avoid_negative_ts disabled -f hls -hls_flags split_by_time -hls_time 3 -hls_segment_type mpegts -hls_segment_filename /tmp/go-vod/ocqflifiaizy/wdc4dk9h5q00-2241657798/1440p-%06d.ts -force_key_frames expr:gte(t,n_forced*3) -
2023/10/16 11:59:34 wdc4dk9h5q00-2160p: recv 2160p-000000.ts
2023/10/16 11:59:34 ffmpeg-error: [hevc @ 0x5633ce658140] decoder->cvdl->cuvidCreateDecoder(&decoder->decoder, params) failed -> CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023/10/16 11:59:34 ffmpeg-error: [hevc @ 0x5633ce658140] Failed setup for format cuda: hwaccel initialisation returned error.
2023/10/16 11:59:35 ffmpeg-error: [AVHWDeviceContext @ 0x5633cdfdd640] cu->cuMemAlloc(&data, size) failed -> CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023/10/16 11:59:35 ffmpeg-error: Error while filtering: Cannot allocate memory
2023/10/16 11:59:35 ffmpeg-error: Failed to inject frame into filter network: Cannot allocate memory
2023/10/16 11:59:35 ffmpeg-error: Error while processing the decoded data for stream #0:0
2023/10/16 11:59:35 ffmpeg-error: [aac @ 0x5633cdf80640] 2 frames left in the queue on closing
2023/10/16 11:59:35 wdc4dk9h5q00-1440p: ffmpeg exited with status: 1
2023/10/16 11:59:35 wdc4dk9h5q00-1080p: stopping stream
2023/10/16 11:59:35 wdc4dk9h5q00-1080p: /usr/bin/ffmpeg -loglevel warning -hwaccel cuda -i /xxxfiles/Photos/Test/23-09-16 23-08-42 9475.mov -copyts -vf format=nv12|cuda,hwupload,scale_cuda=force_original_aspect_ratio=decrease:passthrough=0:w=1920:h=1920 -profile:v main -maxrate 3480000 -bufsize 6960000 -map 0:v:0 -c:v h264_nvenc -preset p6 -tune ll -rc vbr -rc-lookahead 30 -cq 24 -map 0:a:0? -c:a aac -ac 1 -start_number 0 -avoid_negative_ts disabled -f hls -hls_flags split_by_time -hls_time 3 -hls_segment_type mpegts -hls_segment_filename /tmp/go-vod/ocqflifiaizy/wdc4dk9h5q00-2241657798/1080p-%06d.ts -force_key_frames expr:gte(t,n_forced*3) -
2023/10/16 11:59:36 ffmpeg-error: [hevc @ 0x564327612200] decoder->cvdl->cuvidCreateDecoder(&decoder->decoder, params) failed -> CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023/10/16 11:59:36 ffmpeg-error: [hevc @ 0x564327612200] Failed setup for format cuda: hwaccel initialisation returned error.
2023/10/16 11:59:37 wdc4dk9h5q00-2160p: recv 2160p-000001.ts
2023/10/16 11:59:39 wdc4dk9h5q00-1080p: recv 1080p-000000.ts
2023/10/16 11:59:40 wdc4dk9h5q00-1080p: recv 1080p-000001.ts
2023/10/16 11:59:41 wdc4dk9h5q00-2160p: recv 2160p-000002.ts
2023/10/16 11:59:42 wdc4dk9h5q00-1080p: recv 1080p-000002.ts
2023/10/16 11:59:44 wdc4dk9h5q00-1080p: recv 1080p-000003.ts
2023/10/16 11:59:44 wdc4dk9h5q00-1080p: resuming transcoding
2023/10/16 11:59:45 wdc4dk9h5q00-2160p: recv 2160p-000003.ts
```
And inside Nextcloud logs:


Error | memories | Transcode failed: Transcoder returned 408

**Comment by pulsejet** [comment]
Maybe the GOP size workaround
![image](https://github.com/pulsejet/memories/assets/10709794/8cb4b69e-0e1f-41fc-a00f-62dc6bfc5e32)

**Comment by n0one42** [comment]
I have build now my own ffmpeg with the `scale_npp` and it seams to work better even if I still have to use "GOP size workaround" to bring it to work correctly.
On first run of transcoding from 4k to 2k, it still hangs for a short time because he is not done with the receiving of the data but at least it works better and after playing again, it works. In my opinion the Quadro P600 should be capable of doing it without interruptions but anyway. I think, I invested enough time in this and will stop here.
No errors anymore inside the logs:
```bash
2023/10/16 18:37:48 wz3xmd73jpc0-1440p: /usr/bin/ffmpeg -loglevel warning -hwaccel cuda -i /xxx/files/Photos/Test/23-09-16 23-08-42 9475.mov -copyts -vf format=nv12|cuda,hwupload,scale_npp=force_original_aspect_ratio=decrease:w=2560:h=2560 -profile:v main -maxrate 5800000 -bufsize 11600000 -map 0:v:0 -c:v h264_nvenc -preset p6 -tune ll -rc vbr -rc-lookahead 30 -cq 24 -map 0:a:0? -c:a aac -ac 1 -start_number 0 -avoid_negative_ts disabled -f hls -hls_flags split_by_time -hls_time 3 -hls_segment_type mpegts -hls_segment_filename /tmp/go-vod/ocqflifiaizy/wz3xmd73jpc0-2241657798/1440p-%06d.ts -g 87 -keyint_min 87 -
2023/10/16 18:37:52 wz3xmd73jpc0-1440p: recv 1440p-000000.ts
2023/10/16 18:37:53 wz3xmd73jpc0-1440p: recv 1440p-000001.ts
2023/10/16 18:37:56 wz3xmd73jpc0-1440p: recv 1440p-000002.ts
2023/10/16 18:37:58 wz3xmd73jpc0-1440p: recv 1440p-000003.ts
2023/10/16 18:38:00 wz3xmd73jpc0-1440p: recv 1440p-000004.ts
2023/10/16 18:38:00 wz3xmd73jpc0-1440p: resuming transcoding
2023/10/16 18:38:01 wz3xmd73jpc0-1440p: recv 1440p-000005.ts
```

```bash
for i in encoders decoders filters; do
    echo $i:; ffmpeg -hide_banner -${i} | egrep -i "npp|cuvid|nvenc|cuda|nvdec"
done
encoders:
 V....D av1_nvenc            NVIDIA NVENC av1 encoder (codec av1)
 V....D h264_nvenc           NVIDIA NVENC H.264 encoder (codec h264)
 V....D hevc_nvenc           NVIDIA NVENC hevc encoder (codec hevc)
decoders:
 V..... av1_cuvid            Nvidia CUVID AV1 decoder (codec av1)
 V..... h264_cuvid           Nvidia CUVID H264 decoder (codec h264)
 V..... hevc_cuvid           Nvidia CUVID HEVC decoder (codec hevc)
 V..... mjpeg_cuvid          Nvidia CUVID MJPEG decoder (codec mjpeg)
 V..... mpeg1_cuvid          Nvidia CUVID MPEG1VIDEO decoder (codec mpeg1video)
 V..... mpeg2_cuvid          Nvidia CUVID MPEG2VIDEO decoder (codec mpeg2video)
 V..... mpeg4_cuvid          Nvidia CUVID MPEG4 decoder (codec mpeg4)
 V..... vc1_cuvid            Nvidia CUVID VC1 decoder (codec vc1)
 V..... vp8_cuvid            Nvidia CUVID VP8 decoder (codec vp8)
 V..... vp9_cuvid            Nvidia CUVID VP9 decoder (codec vp9)
filters:
 ... bilateral_cuda    V->V       GPU accelerated bilateral filter
 T.. bwdif_cuda        V->V       Deinterlace CUDA frames
 ... chromakey_cuda    V->V       GPU accelerated chromakey filter
 ... colorspace_cuda   V->V       CUDA accelerated video color converter
 ... hwupload_cuda     V->V       Upload a system memory frame to a CUDA device.
 ... overlay_cuda      VV->V      Overlay one video on top of another using CUDA
 ... scale_cuda        V->V       GPU accelerated video resizer
 ... scale_npp         V->V       NVIDIA Performance Primitives video scaling and format conversion
 ... scale2ref_npp     VV->VV     NVIDIA Performance Primitives video scaling and format conversion to the given reference.
 ... sharpen_npp       V->V       NVIDIA Performance Primitives video sharpening filter.
 ... thumbnail_cuda    V->V       Select the most representative frame in a given sequence of consecutive frames.
 ... transpose_npp     V->V       NVIDIA Performance Primitives video transpose
 T.. yadif_cuda        V->V       Deinterlace CUDA frames
 ```

**Comment by pulsejet** [comment]
> On first run of transcoding from 4k to 2k, it still hangs for a short time because he is not done with the receiving of the data

This is likely because it times out during the wait to "warm up" ffmpeg. Maybe we need a configurable timeout ...

**Comment by n0one42** [comment]
> > On first run of transcoding from 4k to 2k, it still hangs for a short time because he is not done with the receiving of the data
> 
> This is likely because it times out during the wait to "warm up" ffmpeg. Maybe we need a configurable timeout ...

Ah okey. Will you implement this maybe in the next releases or such?

**Comment by pulsejet** [comment]
Probably

**Comment by n0one42** [comment]
> Probably

Okey. Thank you for the help and I hope, you can implement this in the future also.
