### ISSUE TITLE
Use memories without geometry database

### ISSUE THREAD

**Issue by SKB-CGN** [pulsejet/memories#869]
Hi,
would it be possible, to use memories without the planet geometry database entries?

When I upload a bunch of pictures, the app logs a lot of errors.

I do not want to use it because my backup of the SQL database is a lot bigger, than without.

Thanks!

**Comment by pulsejet** [comment]
> would it be possible, to use memories without the planet geometry database entries?

Sure, just drop the table and remove the config entry:
```
occ config:system:delete memories.gis_type 
```

> the app logs a lot of errors.

It might be a bug, could help if you could share this.

**Comment by SKB-CGN** [comment]
Thanks for the command. That helped a lot. I think, the warnings are gone now.
I will close the issue, as your answer was helping me!
