### ISSUE TITLE
Android app uses Nextcloud logo even if a custom logo has been set

### ISSUE THREAD

**Issue by RikkiBC** [pulsejet/memories#871]
**Describe the bug**
I have a custom logo set in Nextcloud theming, however the Android app continues to use the default blue Nextcloud logo.

**To Reproduce**
1. Go to Admin Settings --> Theming.
2. Set a new logo.

Expected result:
Logo used in Android app.

Actual result:
Blue Nextcloud logo still used instead.

**Platform:**

- OS: Android
- Browser or App: App
- App version: 1.4
- Memories Version: 5.5.3
- Nextcloud Version: 27.1.2
- PHP Version: 8.1.2.4

**Additional context**
Might need some thought on how to do this? The Web interface has a white logo by default as it has a coloured bar to sit on, regardless of light or dark mode. The app has the blue icon on either the white or black background depending on light or dark mode. So, simply pulling the default white logo would result in it being invisible in light mode...

**Comment by pulsejet** [comment]
Note: there are some extra considerations involved here. See https://memories.gallery/config/#header-logo
