### ISSUE TITLE
Request: Release Android app on F-Droid

### ISSUE THREAD

**Issue by jtrees** [pulsejet/memories#872]
**Is your feature request related to a problem? Please describe.**
I have a Google-free phone and would like to try the app.

**Describe the solution you'd like**
A release of the app in the official F-Droid repository.

**Describe alternatives you've considered**
You could also host your own F-Droid repo but I think you'd gain much more exposure by using the official repo and users (like myself) can enjoy the peace of mind that the app passed F-Droid's rigorous vetting process before getting added.

**Additional context**
https://f-droid.org/

**Comment by pulsejet** [comment]
Duplicate of #852

**Comment by jtrees** [comment]
Ah, there it is. I was convinced I'd seen it before but didn't find it in my search because it's spelled out as "FDroid" instead of "F-Droid" there.

Thanks!
