### ISSUE TITLE
Issue using go-vod in any configuration

### ISSUE THREAD

**Issue by alekslyse** [pulsejet/memories#876]
I am not sure if this is a bug or me, but I have tried to install go-vod on an own vm, in docker, used the builtin in memories, and alse used a custom image, but still I just get a 404 error when running the occ memories:video-setup. I tried the binaries and compiling myself.

I also tried to run kill on ffmpeg and go-vod, plus removed the temp files. 

This is the output of the script:

`This command will help you setup video streaming
It will check if ffmpeg and ffprobe are installed and go-vod (the transcoder) works
If you are running go-vod externally, feature detection will not work properly
In that case you will need to manually adjust the configuration file (add --print-config)
For details on hardware support: https://github.com/pulsejet/memories/wiki/HW-Transcoding

Press enter to continue or CTRL+C to abort

ffmpeg is installed
ffprobe is installed
Checking for go-vod binary
Trying go-vod from /var/www/html/custom_apps/memories/exiftool-bin/go-vod-amd64
go-vod is installed!

You can use transcoding and HLS streaming
This is recommended for better performance, but has implications if
you are using external storage or run Nextcloud on a slow system.

Read the following documentation carefully before continuing:
https://github.com/pulsejet/memories/wiki/Configuration

Do you want to enable transcoding and HLS? [Y/n]

Starting ffmpeg feature detection
This may take a while. Please be patient

Downloading test video file ... OK

Attempting to start go-vod ... OK
go-vod logs will be stored at: /tmp/go-vod/oclr8used30z.log

Testing transcoding with CPU ... FAIL
CPU transcoding failed with error HTTP status: 404
Check the log file of go-vod for more details (/tmp/go-vod/oclr8used30z.log)

Checking for VAAPI acceleration (/dev/dri/renderD128) ... OK
Checking for permissions on /dev/dri/renderD128 ... OK
Testing transcoding with VAAPI ... FAIL
VAAPI transcoding failed with error HTTP status: 404
Check the log file of go-vod for more details (/tmp/go-vod/oclr8used30z.log)
Testing transcoding with VAAPI (low_power) ... FAIL
VAAPI (low_power) transcoding failed with error HTTP status: 404
Check the log file of go-vod for more details (/tmp/go-vod/oclr8used30z.log)

Checking for NVIDIA acceleration with NVENC
Testing transcoding with NVENC (scale_npp) ... FAIL
Testing transcoding with NVENC (scale_cuda) ... FAIL
NVENC does not seem to be available

Feature detection completed

Transcoding and HLS are now enabled! Monitor the log file for any errors
You should restart the server for changes to take effect`

And this is the log from go-vod

`&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/oclr8used30z ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/09 12:12:29 Starting VOD server
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/oclr8used30z ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/09 12:12:31 Starting VOD server
2023/04/09 12:12:33 test: new manager for /tmp/sample.mp40Myrjv
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/oclr8used30z ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:true VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/09 12:12:34 Starting VOD server
2023/04/09 12:12:35 test: new manager for /tmp/sample.mp40Myrjv
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/oclr8used30z ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:true VAAPILowPower:true NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/09 12:12:36 Starting VOD server
2023/04/09 12:12:37 test: new manager for /tmp/sample.mp40Myrjv
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/oclr8used30z ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:true NVENCTemporalAQ:false NVENCScale:npp}
2023/04/09 12:12:38 Starting VOD server
2023/04/09 12:12:39 test: new manager for /tmp/sample.mp40Myrjv
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/oclr8used30z ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:true NVENCTemporalAQ:false NVENCScale:cuda}
2023/04/09 12:12:40 Starting VOD server
2023/04/09 12:12:41 test: new manager for /tmp/sample.mp40Myrjv
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/oclr8used30z ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/09 12:18:09 Starting VOD server
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/oclr8used30z ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/09 12:18:11 Starting VOD server
2023/04/09 12:18:13 test: new manager for /tmp/sample.mp4XzXQjh
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/oclr8used30z ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:true VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/09 12:18:14 Starting VOD server
2023/04/09 12:18:15 test: new manager for /tmp/sample.mp4XzXQjh
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/oclr8used30z ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:true VAAPILowPower:true NVENC:false NVENCTemporalAQ:false NVENCScale:npp}
2023/04/09 12:18:16 Starting VOD server
2023/04/09 12:18:17 test: new manager for /tmp/sample.mp4XzXQjh
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/oclr8used30z ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:true NVENCTemporalAQ:false NVENCScale:npp}
2023/04/09 12:18:18 Starting VOD server
2023/04/09 12:18:19 test: new manager for /tmp/sample.mp4XzXQjh
&{Bind:127.0.0.1:47788 FFmpeg:/usr/bin/ffmpeg FFprobe:/usr/bin/ffprobe TempDir:/tmp/go-vod/oclr8used30z ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:true NVENCTemporalAQ:false NVENCScale:cuda}
2023/04/09 12:18:20 Starting VOD server
2023/04/09 12:18:21 test: new manager for /tmp/sample.mp4XzXQjh`

**Comment by pulsejet** [comment]
This is old, `video-setup` doesn't even exist anymore.
