### ISSUE TITLE
Shared public link at group folders not working!

### ISSUE THREAD

**Issue by GitWidi** [pulsejet/memories#879]
**Describe the bug**
Shared public link for a folder at a group folder seems not working!

**To Reproduce**
I create a shared public link (read only mode) at a folder containing pictures on a group folder and got the following URL: 
https://cloud.dav-rottenburg.de/index.php/apps/memories/s/dpinwomZqaoFTtd

1. Login to the Nextcloud using an existing account.
    - Switch to app Memories
    - Navigate via "Folders" to a folder on one of the group folders.
    - Click the button "Share folder"
    - Click the button "Create link"
    - Click on "Share link" to copy the URL to the clipboard.
1. Use a second browser without Nextcloud login
    - Paste the URL from the clipboard.

**Expected behaviour**
The album view of the app Memories which shows the images in this shared folder.
The access to this folder is allowed, as shown by public access to the same page via the app Files: 
https://cloud.dav-rottenburg.de/index.php/s/dpinwomZqaoFTtd

**Screenshots**
First attempt to open the shared link:
![grafik](https://github.com/pulsejet/memories/assets/4623128/d123d14a-b2a9-437d-af98-3625843aa7e8)

The access via app Files:
![grafik](https://github.com/pulsejet/memories/assets/4623128/7fef2e6f-3d13-4b1a-b012-628cf8d1b171)

**Platform:**

- OS Server: Debian Linux 4.4.320 x86_64 (IONOS Hosting)
- OS Client: MS Windows 10 Enterpise (22H2) or Windows 11 Home
- Browser: Edge 118.0, Chrome 118.0
- Memories Version: 5.5.3
- Nextcloud Version: 27.1.2
- PHP Version: 8.1

**Additional context**
***Nextcloud server logging:***
[index] Error: Exception: OCA\Memories\Util::getAnyMedia(): Return value must be of type OCP\Files\Node, null returned in file '/homepages/0/d22585709/htdocs/cloud/apps/memories/lib/Util.php' line 296 at <<closure>>

0. /homepages/0/d22585709/htdocs/cloud/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /homepages/0/d22585709/htdocs/cloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
2. /homepages/0/d22585709/htdocs/cloud/lib/base.php line 1068
   OC\Route\Router->match()
3. /homepages/0/d22585709/htdocs/cloud/index.php line 36
   OC::handleRequest()

Caused by:

TypeError: OCA\Memories\Util::getAnyMedia(): Return value must be of type OCP\Files\Node, null returned at <<closure>>

0. /homepages/0/d22585709/htdocs/cloud/apps/memories/lib/Util.php line 253
   OCA\Memories\Util::getAnyMedia()
1. /homepages/0/d22585709/htdocs/cloud/apps/memories/lib/Controller/PublicController.php line 131
   OCA\Memories\Util::addOgMetadata()
2. /homepages/0/d22585709/htdocs/cloud/lib/private/AppFramework/Http/Dispatcher.php line 230
   OCA\Memories\Controller\PublicController->showShare()
3. /homepages/0/d22585709/htdocs/cloud/lib/private/AppFramework/Http/Dispatcher.php line 137
   OC\AppFramework\Http\Dispatcher->executeController()
4. /homepages/0/d22585709/htdocs/cloud/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
5. /homepages/0/d22585709/htdocs/cloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
6. /homepages/0/d22585709/htdocs/cloud/lib/base.php line 1068
   OC\Route\Router->match()
7. /homepages/0/d22585709/htdocs/cloud/index.php line 36
   OC::handleRequest()

GET /index.php/apps/memories/s/dpinwomZqaoFTtd
from 80.150.130.202 at 2023-10-18T06:40:12+00:00

`{"reqId":"ZS99yx5JonycQM0mIViNoQAAABU","level":3,"time":"2023-10-18T06:40:12+00:00","remoteAddr":"80.150.130.202","user":"--","app":"index","method":"GET","url":"/index.php/apps/memories/s/dpinwomZqaoFTtd","message":"OCA\\Memories\\Util::getAnyMedia(): Return value must be of type OCP\\Files\\Node, null returned in file '/homepages/0/d22585709/htdocs/cloud/apps/memories/lib/Util.php' line 296","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46","version":"27.1.2.1","exception":{"Exception":"Exception","Message":"OCA\\Memories\\Util::getAnyMedia(): Return value must be of type OCP\\Files\\Node, null returned in file '/homepages/0/d22585709/htdocs/cloud/apps/memories/lib/Util.php' line 296","Code":0,"Trace":[{"file":"/homepages/0/d22585709/htdocs/cloud/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/homepages/0/d22585709/htdocs/cloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/homepages/0/d22585709/htdocs/cloud/lib/base.php","line":1068,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/homepages/0/d22585709/htdocs/cloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/homepages/0/d22585709/htdocs/cloud/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"TypeError","Message":"OCA\\Memories\\Util::getAnyMedia(): Return value must be of type OCP\\Files\\Node, null returned","Code":0,"Trace":[{"file":"/homepages/0/d22585709/htdocs/cloud/apps/memories/lib/Util.php","line":253,"function":"getAnyMedia","class":"OCA\\Memories\\Util","type":"::"},{"file":"/homepages/0/d22585709/htdocs/cloud/apps/memories/lib/Controller/PublicController.php","line":131,"function":"addOgMetadata","class":"OCA\\Memories\\Util","type":"::"},{"file":"/homepages/0/d22585709/htdocs/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"showShare","class":"OCA\\Memories\\Controller\\PublicController","type":"->"},{"file":"/homepages/0/d22585709/htdocs/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/homepages/0/d22585709/htdocs/cloud/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/homepages/0/d22585709/htdocs/cloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/homepages/0/d22585709/htdocs/cloud/lib/base.php","line":1068,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/homepages/0/d22585709/htdocs/cloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/homepages/0/d22585709/htdocs/cloud/apps/memories/lib/Util.php","Line":296},"CustomMessage":"--"},"id":"652f7dd4b650e"}`

**Comment by pulsejet** [comment]
This is fixed on master. For now, you can go to `lib/Util.php` and add a question mark before `Node`
https://github.com/pulsejet/memories/blob/db93202b087cb5881ba96314d12cf8324f169be7/lib/Util.php#L287C72-L287C72

Change
```php
public static function getAnyMedia(\OCP\Files\Folder $folder): Node
```

to 

```php
public static function getAnyMedia(\OCP\Files\Folder $folder): ?Node
```

**Comment by pulsejet** [comment]
Please reopen if still broken in 6.x
