### ISSUE TITLE
How to test the v4.3.0?

### ISSUE THREAD

**Issue by jakobroehrl** [pulsejet/memories#88]
It's not available in the app store: https://apps.nextcloud.com/apps/memories
![grafik](https://user-images.githubusercontent.com/24530680/197169324-343b747b-54f9-45a9-a391-250b1da464c6.png)

Btw: Very nice app and awesome progress here!

**Comment by pulsejet** [comment]
There's some bug with the app store that shows only one nightly at a time. You need to grab it from the release assets https://github.com/pulsejet/memories/releases
