### ISSUE TITLE
NixOS - exiftool error in logs but actual indexing seems to operate normally

### ISSUE THREAD

**Issue by firecat53** [pulsejet/memories#884]
**Describe the bug**

There is a recurring error in the nextcloud-cron.service logs  and an error message on the memories configuration page that does not seem to affect the actual indexing by memories. All photos are recognized and indexed without any errors. It doesn't happen on every run, but does happen regularly every 20 min (every 4th run).

Logs:
```
Oct 25 09:34:11 homeserver systemd[1]: Starting nextcloud-cron.service...
Oct 25 09:34:11 homeserver systemd[1]: nextcloud-cron.service: Deactivated successfully.
Oct 25 09:34:11 homeserver systemd[1]: Finished nextcloud-cron.service.
Oct 25 09:39:14 homeserver systemd[1]: Starting nextcloud-cron.service...
Oct 25 09:39:15 homeserver Nextcloud[3714819]: {"reqId":"QCzrTT0gkspvICIZVJ7R","level":3,"time":"2023-10-25T16:39:15+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"proc_open(): Exec failed: No such file or directory at /var/lib/nextcloud/store-apps/memories/lib/Exif.php#385","userAgent":"--","version":"27.1.2.1","data":{"app":"PHP"}}
Oct 25 09:39:15 homeserver php[3714818]: WARN: Failed to create stay_open exiftool process
Oct 25 09:39:15 homeserver php[3714820]: sh: line 1: perl: command not found
Oct 25 09:39:15 homeserver Nextcloud[3714818]: {"reqId":"fGdW3kAE1jKoCgVW8OzK","level":3,"time":"2023-10-25T16:39:15+00:00","remoteAddr":"","user":"--","app":"memories","method":"","url":"--","message":"Memories: Indexing exception: failed to run exiftool: perl /var/lib/nextcloud/store-apps/memories/exiftool-bin/exiftool/exiftool -ver","userAgent":"--","version":"27.1.2.1","data":{"app":"memories"}}
Oct 25 09:39:15 homeserver systemd[1]: nextcloud-cron.service: Deactivated successfully.
Oct 25 09:39:15 homeserver systemd[1]: Finished nextcloud-cron.service.
```
![Screenshot from 2023-10-25 at 09_46_06 961860943](https://github.com/pulsejet/memories/assets/568113/e1fb49eb-3cdf-4601-9476-18e8900d507c)

**To Reproduce**

- Install Nextcloud via NixOS. Install memories from the app store.

NixOS config:
```
# Nextcloud
{
  config,
  lib,
  pkgs,
  sops,
  ...
}:{
  sops.secrets.nextcloud-admin-password = {
    mode = "0440";
    owner = config.users.users.nextcloud.name;
    group = config.users.users.nextcloud.group;
  };
  users.users.nextcloud.extraGroups = ["render" "users"];
 
  environment.systemPackages = with pkgs; [
    unstable.exiftool
    ffmpeg
    nodejs_18
  ];

  # Allow using /dev/dri for Memories
  systemd.services.phpfpm-nextcloud.serviceConfig = {
    PrivateDevices = lib.mkForce false;
  };

  services.nginx.virtualHosts."nc.lan.domain.com".listen = [ { addr = "127.0.0.1"; port = 8180; } ];

  services.nextcloud = {
    enable = true;
    package = pkgs.nextcloud27;
    hostName = "nc.lan.domain.com";
    database.createLocally = true;
    configureRedis = true;
    appstoreEnable = true;
    config = {
      adminuser = "firecat53";
      adminpassFile = "${config.sops.secrets.nextcloud-admin-password.path}";
      dbtype = "mysql";
      defaultPhoneRegion = "US";
      trustedProxies = ["127.0.0.1"];
    };
    extraOptions = {
      mail_smtpmode = "sendmail";
      mail_sendmailmode = "pipe";
      mysql.utf8mb4 = true;
    };
    phpOptions = {
      "opcache.interned_strings_buffer" = "16";
      "upload_max_filesize" = "10G";
      "post_max_size" = "10G";
      "memory_limit" = "8G";
    };
  };

  services.traefik.dynamicConfigOptions.http.routers.nextcloud = {
    rule = "Host(`nc.lan.domain.com`)";
    service = "nextcloud";
    middlewares = ["headers"];
    entrypoints = ["websecure"];
    tls = {
      certResolver = "le";
    };
  };
  services.traefik.dynamicConfigOptions.http.services.nextcloud = {
    loadBalancer = {
      servers = [
        {
          url = "http://localhost:8180";
        }
      ];
    };
  };
}
```
**Screenshots**

See above.

**Platform:**

- OS: NixOS 23.05
- Browser: Firefox
- Memories Version: 5.5.3
- Nextcloud Version: 27.1.2
- PHP Version: 8.1

**Additional context**

>> - You are using the latest version of the app.

Nextcloud Version 27.1.2 on NixOS. Memories version 5.5.3
 
>> - You tried and can replicate the bug.

Yes.

>> - You have followed the [configuration steps](https://memories.gallery/config/).

Yes. Applicable memories config.php items:

```
'memories.vod.ffmpeg' => '/run/current-system/sw/bin/ffmpeg',
'memories.vod.ffprobe' => '/run/current-system/sw/bin/ffprobe',
'memories.vod.disable' => false,
'memories.vod.vaapi' => true,
'memories.vod.vaapi.low_power' => true,
'memories.exiftool' => '/run/current-system/sw/bin/exiftool',
'memories.exiftool_no_local' => true,
'memories.gis_type' => 1,
```
>> - You have looked at the [troubleshooting](https://memories.gallery/troubleshooting/) documentation.

Yes. The only closely related item was regarding the execute permissions on /tmp.
```
# findmnt /tmp
TARGET SOURCE FSTYPE OPTIONS
/tmp   tmpfs  tmpfs  rw,nodev,size=16308872k

drwxrwxrwt   7 root      root   220 Oct 25 09:29 tmp
```
>> - You have searched the [open issues](https://github.com/pulsejet/memories/issues)

Yes. No relevant issues.

Thanks so much!

**Comment by pulsejet** [comment]
Your `cron.php` job can't access perl for some reason. Any idea why this could be?

**Comment by Shawn8901** [comment]
NixOS does not really follow FHS behavior and does not expose PATH to all binaries and scripts etc. So the cron.php is not really able to pick up systems perl from /usr/bin/ or so.
One needs to make perl available manually.
The issue was crossposted on nixos discourse, as i am providing a possible solution, i wanted to share it here too for others to find.
But in general its a downstream issue.

**Comment by pulsejet** [comment]
This should go to the documentation in the troubleshooting section. Can you suggest what exactly is the fix or make a PR to update the docs?

**Comment by Shawn8901** [comment]
oh yeah i basically forgot the crosslink... :laughing: 

https://discourse.nixos.org/t/nextcloud-memories-app-exiftool-errors/34591/3

When someones does use the nixos modules for setting up, so something like [this](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/nixos/modules/services/web-apps/nextcloud.nix#L1014):

```nix
  services.nextcloud.enable = true;
```

That will build a sytemd timer that will invoke the `cron.php` and this will need perl on the path.
It could be archived like [this](https://github.com/Shawn8901/nix-configuration/blob/5598850f70de45d1caafa33b26cdb1d3906c06cd/machines/tank/configuration.nix#L380)

```nix
  systemd.services.nextcloud-cron = {
    path = [pkgs.perl];
  };
```

I did also create a PR for that https://github.com/pulsejet/memories/pull/900

@firecat53 can you please double check if that`s also fixing the issue on your side?

**Comment by firecat53** [comment]
Yep, that was it! I forgot that the cron.php service needed access. I wonder if I added `path = [pkgs.perl pkgs.exiftool pkgs.ffmpeg];` to phpfpm-nextcloud.service if I would then be able to uncheck the `use system perl` option. I'll have to experiment when I have a chance.

Thanks @Shawn8901! Just that one line cleared the journal errors and the error on the memories admin page. I'll update the Discource issue as well.

**Comment by Shawn8901** [comment]
>  if I would then be able to uncheck the `use system perl` option. 
I tried that but memories does complain about the version of `exiftool` in that case, nixpkgs has [12.68](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=exiftool) in unstable and [12.55](https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=exiftool) on stable, but memories wants to have [12.60](https://github.com/pulsejet/memories/blob/93c0d2860be916f0fb611a7c39475d7a28b16a18/lib/Service/BinExt.php#L11), so you possibly need to patch that then on downstream (possibly you can archive that when using declarative installation via a derivation with `extraApps`, but haven`t tried so).

**Comment by pulsejet** [comment]
That's weird, memories doesn't use the system installed exiftool in any way. The "system perl" option uses `perl` to execute the exiftool that's already bundled inside Memories. In other words, you should _never_ need to install exiftool from a pacakge manager.

**Comment by Shawn8901** [comment]
Yeah, that make sense 🙂 Thanks for your support.


I want to add just context for the idea itself; with setting `memories.exiftool` to the systems exiftool one can at least try to do so. Firecat tried that by setting it to `/run/current-system/sw/bin/exiftool` and having that in `environment.systemPackages` . I am also kind of not sure what's the purpose of it, if not setting to an external exiftool.

On nixos that replacement behavior is quite common, as we don't have a FHS, we also do not have a linker at /lib, so we can not run "alien" compiled dynamic binaries. We either have to patch binaries that are shipped by upstream projects, or replace them by own compiled ones.

**Comment by firecat53** [comment]
After some playing, I'm still having a [couple of issues](https://discourse.nixos.org/t/nextcloud-memories-app-exiftool-errors/34591/6?u=firecat53), namely that the video thumbnailing doesn't seem to be working anymore. I feel like I'm missing something dumb... Thanks!

**Comment by pulsejet** [comment]
For future reference:
1. Use admin panel for configuration, it'll tell you what to do usually
2. https://memories.gallery/system-config/

**Comment by firecat53** [comment]
Yep, I do until it doesn't work because of Nix 😁. The path definitions have to be managed by Nix because they will change as updates occur to ffmpeg and/or exiftool.

**Comment by SuperSandro2000** [comment]
I think for this to work correctly you need to have perl in systemPackages and the cron service because the web ui and the cron job use different PATH settings which is not that great to be honest but I think it could be a problem on our side.
