### ISSUE TITLE
Lock up after using for too long

### ISSUE THREAD

**Issue by Jeefongithub** [pulsejet/memories#885]
**Describe the bug**

Unsure exactly what the bug is but if using Memories for too long (5+ minutes) or scrolling through too many photos the app will lock up and no longer load menus, thumbnails or options. 

**To Reproduce**

Easiest ways I've found is to scroll timeline from beginning. After a couple hundred photos thumbnails will no longer load and photos can no longer be selected

I've also found it happen when editing too many metadata entries. For example if changing too many dates/times on photos behavior will lock up after a few minutes

Finally happens when using recognize to assign more to 10 photos at a time to a person
![Screenshot from 2023-10-26 01-17-27](https://github.com/pulsejet/memories/assets/53583661/50f74b39-bc6d-432d-a9ff-a15cc5f104d2)

**Screenshots**

Screenshot below is when trying to assign multiple images to a person with recognize. Since behavior for image previews in timeline is similar i it simulates both scenarios. (top photos edited out for privacy)

**Platform:**

- OS: [e.g. iOS] Debian 12
- Browser: [e.g. Chrome, Safari] Firefox 115.4
- Memories Version: [e.g. 4.1.0] 6.0 but also experienced in 5.5.3
- Nextcloud Version: [e.g. 25.0.6] 27.1.3 RC2
- PHP Version: [e.g. 8.1] 8.2

**Additional context**

- Any errors in the JS console?
-
export of console logs. website url edited for privacy
[console-export-2023-10-26_1-45-42.txt](https://github.com/pulsejet/memories/files/13173367/console-export-2023-10-26_1-45-42.txt)

- Any errors in the Nextcloud server logs?

Unsure if related but these are the only nextcloud error logs (this is from gui admin log area. Can check on server if needed)

  | Movie  preview generation failed Output: ffmpeg version 4.3.6-0+deb11u1  Copyright (c) 2000-2023 the FFmpeg developers   built with gcc 10 (Debian 10.2.1-6)   configuration: --prefix=/usr --extra-version=0+deb11u1  --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu  --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl  --disable-stripping --enable-avresample --disable-filter=resample  --enable-gnutls --enable-ladspa --enable-libaom --enable-libass  --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio  --enable-libcodec2 --enable-libdav1d --enable-libflite  --enable-libfontconfig --enable-libfreetype --enable-libfribidi  --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame  --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt  --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg  --enable-librubberband --enable-libshine --enable-libsnappy  --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh  --enable-libtheora --enable-libtwolame --enable-libvidstab  --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp  --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq  --enable-libzvbi --enable-lv2 --enable-omx --enable-openal  --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx  --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883  --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared   libavutil      56. 51.100 / 56. 51.100   libavcodec     58. 91.100 / 58. 91.100   libavformat    58. 45.100 / 58. 45.100   libavdevice    58. 10.100 / 58. 10.100   libavfilter     7. 85.100 /  7. 85.100   libavresample   4.  0.  0 /  4.  0.  0   libswscale      5.  7.100 /  5.  7.100   libswresample   3.  7.100 /  3.  7.100   libpostproc    55.  7.100 / 55.  7.100 [matroska,webm @ 0x557c1aa6b2c0] Format matroska,webm detected only with  low score of 1, misdetection possible! [matroska,webm @ 0x557c1aa6b2c0] 0x00 at pos 0 (0x0) invalid as first  byte of an EBML number [matroska,webm @ 0x557c1aa6b2c0] EBML header parsing failed /(FILEPATH removed for privacy) Invalid data found when  processing input
-- | --

**Comment by pulsejet** [comment]
Your CSRF token seems to be expiring for some reason. Possibly a misconfiguration or upstream bug.

**Comment by Jeefongithub** [comment]
Can confirm issue is still present with 6.1.0

I'm not a coder so if i use poor terminology forgive me but I think the issue might relate from having multiple tabs open at the same time causing cross-tab communication issues. I haven't replicated the issue with a single instance open but at the same time i might not have given it enough time for troubleshooting

**Comment by pulsejet** [comment]
As I said, this is not a bug in Memories, need to investigate when this happens; it's coming from `@nextcloud/axios`

**Comment by Jeefongithub** [comment]
sorry about that. I'll close this ticket and work with nextcloud separately

**Comment by pulsejet** [comment]
It turns out this was an error on Memories side. Hopefully it's fixed in v6.1.4. Can you validate @Jeefongithub?

**Comment by Jeefongithub** [comment]
Thanks for looking back into this. I updated to 6.1.4 and so far everything is looking good. I updated to 6.1.5 today and it's looking good as well. I'll test for a couple more days to verify

**Comment by pulsejet** [comment]
Okay, great! Just reopen the issue if the issue pops up again
