### ISSUE TITLE
Mobile timeline layout bugs

### ISSUE THREAD

**Issue by illnesse** [pulsejet/memories#89]
![image](https://user-images.githubusercontent.com/40355982/197359919-9fc8f7a2-4c31-4455-bef2-856af67cfa5a.png)
![image](https://user-images.githubusercontent.com/40355982/197359995-41a09f0b-5a07-4ed1-9037-86cbcb5210ba.png)
![image](https://user-images.githubusercontent.com/40355982/197360033-2ecc87bd-0b2f-4acd-829b-708af8708cb3.png)

Don't remember really but i think i moved some faces before this

**Comment by pulsejet** [comment]
Does the issue persist if you refresh the page?

**Comment by illnesse** [comment]
Nope it's just a temp glitch after moving faces i guess, not sure if it happens after deleting too

**Comment by pulsejet** [comment]
Should be fixed now then. Reopen if you see this again.
