### ISSUE TITLE
Duplicate and conflicting localisations 

### ISSUE THREAD

**Issue by eltos** [pulsejet/memories#894]
**Describe the bug**
In [Transifex](https://app.transifex.com/nextcloud/nextcloud/memories) some languages are duplicated. Usually the idea is to allow regional specific variants, e.g. `en_uk`/`en_us`, for certain words, but having the common translations in the region unspecific language (`en`).

For german (and maybe others) however, the reverse is the case:
- German (`de`) - 77%
- German in Germany (`de_de`) - 100%

This has several issues
- If your local does not identically match the region specific one, it will fall back to the untranslated string  
  Examples include "German in Austria" (`de_at`), or even informal German ("Du", `de`) instead of formal German ("Sie", `de_de`). These do not match `de_de`, so `de` is used and – since that is missing translations – it then falls back to English.
- Duplicate work for maintaining two identical translations
- Conflicts (e.g. "timeline" translates to "Zeitleiste" in `de_de`, but "Verlauf" (meaning history or trend) in `de`

I propose to move all `de_de` translations, which appear to be properly maintained, to `de` and delete the `de_de` variant making sure there is only one German translation (for the time being), so contributing translators don't get confused which one to use.

If at some point a need for regional specific localisations arises (or you want to support the formal and informal variant for german), one can add the variant again. It would then be helpful to have a prominent statement for new translators explaining the above and hinting them to use the regional variants **only** for certain strings which are actually specific for that region (or in the case of formal german, **only** those that actually address the user as "Du" vs. "Sie").

**To Reproduce**
- In user settings, set language to "German (Du)", that is `de`
  - In the menu, the timeline is titled "Verlauf"
  - Delete a file, promt shows "Move 1 element to trash?"
- In user settings, set language to "German (Sie)", that is `de_de`
  - In the menu, the timeline is titled "Zeitleiste"
  - Delete a file, promt shows "1 Element in den Papierkorb verschieben?"

**Screenshots**

**Platform:**

This issue is not related to a specific platform, but for completion:
- OS: Android
- Browser: Firefox
- Memories Version: 5.5.3
- Nextcloud Version: 27.1.2
- PHP Version: 8.2.6

**Additional context**
For the special case of German, see discussions at https://help.nextcloud.com/t/zwei-deutsche-ubersetzungen-ist-das-notwendig/96023/5 and some further explanation at https://help.nextcloud.com/t/language-code-vs-locale-confusion/158415/3

/cc @rakekniven @Siggi0904 as language maintainers for `de_de` and `de` on transifex

**Comment by eltos** [comment]
Being a native, I can offer you to assist with the migration of German localisation, especially resolving conflicts, or correcting the formal/informal variants (Du/Sie).

**Comment by pulsejet** [comment]
I'm entirely unfamiliar with how translations work. Would this involve some config change on the side of Memories?

**Comment by eltos** [comment]
> We had that topic in the past and a long discussion at help forum. Technically we did not succeed (Transifex is not supporting this procedure as well). In the end we ended in keeping both languages with differenent teams.

Transifex has nothing to do with the string resolution, this is done in Nextcloud (obviously improperly). For android it's handled properly by the framework, see [here](https://developer.android.com/guide/topics/resources/localization#avoid-creating-more-resource-files-and-text-strings-than-you-need). Desktop client and iOS are not applicable to memories app.

Alright, I realise I might have opened up a discussion that has already been completed, and is not specific to memories, but seams to rewire a fix in Nextcloud core.
I neither want to re-open that discussion, nor am I going to help maintain duplications, so I'll step back here. Nevertheless, thank you for the explanations and I'm really sorry for having wasted your time.

**Comment by eltos** [comment]
> The germans are to difficult :-)

From a technical point of view, there is absolutely no difference between Formal/Informal German "dialects" and the various region specific localizations like UK/US English, Brazilian/Portugal Portuguese or the 17 different variants of Spanish (I wonder who is maintaining these duplicates). It's a matter of proper implementation. But let's leave it at that.

At least, I have now copied over the reviewed strings from memories `de_de` resources to the missing/conflicting ones in `de` and adjusted them to use "Du". That's not a sustainable way IMHO, but solves what I opened the issue for in the first place, and is what I offered to do.

**Comment by eltos** [comment]
@rakekniven 
PS: maybe it would be a good idea, for `de`, to only review the strings actually containing "Du" phrases and leave the others identical ones unreviewed. This would allow you to use the [file-upload feature of Transifex](https://help.transifex.com/en/articles/6318456-uploading-translations) to easily copy over all the not "Du"/"Sie" specific strings from `de_de` to `de` while not overwriting the reviewed ones which differ for formal/informal. At least at first glance, it looks a bit of a simpler workflow to do that once before each release, compared to the "synchronized editing with two browser windows" that you describe in the wiki. Just my two cents.
