### ISSUE TITLE
Broken reverse sorting order on 6.x

### ISSUE THREAD

**Issue by pulsejet** [pulsejet/memories#895]
1. Headers are correctly sorted
2. Photos are not

Reported by `@dxbi` on Discord:
https://discord.com/channels/1100157156742926406/1100158171621904567/1168241987095384075

**Comment by AxelTheGerman** [comment]
Hey, I also noticed this and additionally I think there are a few other related issues:
- when toggling "Sort albums oldest-first" setting, it reorders the album for me as logged in user but not for the public view in my incognito window
- With "Sort albums oldest-first" pictures are grouped by month whereas with the setting off they seem to be grouped by days

**Comment by pulsejet** [comment]
> when toggling "Sort albums oldest-first" setting, it reorders the album for me as logged in user but not for the public view in my incognito window

Should be fixed in the next release

> With "Sort albums oldest-first" pictures are grouped by month whereas with the setting off they seem to be grouped by days

This is intentional

**Comment by philiprenich** [comment]
> > With "Sort albums oldest-first" pictures are grouped by month whereas with the setting off they seem to be grouped by days

> This is intentional

With this setting for me, the months are sorted oldest first, but the photos within each month are sorted newest first.

**Comment by pulsejet** [comment]
The fix isn't released yet, it's just on master
