### ISSUE TITLE
Deleting large numbers of photos is very slow.

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#897]
**Describe the bug**
After clicking the delete button on a large selection of photos (over about 100), the delete prompt is severely delayed.

**To Reproduce**
1. Select a large number of photos (shift-click isn't reliable for large spans of photos)
2. Click the delete button
3. Wait a few full minutes before delete prompt shows up

**Additional context**
Related to this, it can be difficult to select large numbers of photos since the shift-click selection doesn't work if photos between the beginning and the end of the selection are not loaded (i.e. select first photo, scroll in timeline, then try selecting photo).

**Comment by pulsejet** [comment]
Hmm, it does make a few DAV calls to check the permissions but this should be quite fast. On my instance I tried selecting ~300 photos, the delete dialog appears in a couple hundred ms.

Is the files app extremely slow for you? Or do you have folders with a huge number of files in them? (though that isn't supposed to really affect this)

**Comment by pulsejet** [comment]
The JS network tab / console might have hints as to what's happening

**Comment by pulsejet** [comment]
Interesting. Nextcloud is stateless so this isn't supposed to happen ... if this happens again try rebooting one component at a time, e.g. database, PHP server, web server ... that could point to what happenede
