### ISSUE TITLE
Feature: Allow searching for photos with multiple specific people.

### ISSUE THREAD

**Issue by PriceChild** [pulsejet/memories#899]
**Is your feature request related to a problem? Please describe.**
I would like to filter my collection for photos with specific people.

For example "photos with my partner and my niece", so that I can then use them for a collage.

**Describe the solution you'd like**
Search functionality that lets you multi-select multiple people/faces, then only shows photos which contain both of those people.

An option to include or exclude photos that contain other people.

**Describe alternatives you've considered**
Searching for one person, then manually looking through the result.

**Additional context**
I'm assuming this belongs here rather than Recognize?

Also, Memories is fantastic. It should be the default Nextcloud media app!

**Comment by pulsejet** [comment]
Under the umbrella of https://github.com/pulsejet/memories/issues/674 :)

**Comment by PriceChild** [comment]
Sorry I didn't see those earlier. Yes this looks like a duplicate of #868
