### ISSUE TITLE
proc_open() error after upgrading

### ISSUE THREAD

**Issue by teemue** [pulsejet/memories#90]
After upgrading from 4.2.2 to 4.3.2:

Error: proc_open(): Exec failed: Permission denied at /var/www/html/custom_apps/memories/lib/Exif.php#149

Error: proc_open(): Exec failed: Permission denied at /var/www/html/custom_apps/memories/lib/Exif.php#468

**Comment by pulsejet** [comment]
What kind of system is this? Also I assumed you installed through the app store?

**Comment by teemue** [comment]
Dockerized Nextcloud. I upgraded memories via app store. Exiftool is installed.

**Comment by pulsejet** [comment]
Official image? How is/var/www/html mounted?

**Comment by pulsejet** [comment]
Can you also check if your `config.php` contains a `memories.exiftool` entry?

**Comment by teemue** [comment]
> Official image? How is/var/www/html mounted?

Yes, it's official.

/var/www/html is mounted as a docker volume.


config.php contains
'memories.exiftool_no_local' => true,

**Comment by pulsejet** [comment]
Can you try `sudo -u www-data chmod 777 /var/www/html/apps/memories/exiftool-bin/exiftool/exiftool` inside the container?

If that doesn't work, just `chmod 777 /var/www/html/apps/memories/exiftool-bin/exiftool/exiftool`.

> Sounds like issue #48

Not really. Exiftool is bundled with memories starting v4.3

**Comment by pulsejet** [comment]
> Memories is in custom_apps folder and I chmoded exiftool there. Now it works.

Did you chmod as www-data or root? I want to know because the permissions should've been right to begin with, and whether we can change them in php. What's the output of `ls -larth /var/www/html/apps/memories/exiftool-bin`? =

**Comment by teemue** [comment]
> > Memories is in custom_apps folder and I chmoded exiftool there. Now it works.
> 
> Did you chmod as www-data or root? I want to know because the permissions should've been right to begin with, and whether we can change them in php. What's the output of `ls -larth /var/www/html/apps/memories/exiftool-bin`?

As a www-data.

`www-data@86f51a801a1a:~/html$ ls -larth /var/www/html/custom_apps/memories/exiftool
-bin
total 32M
drwxr-xr-x 6 www-data www-data 4.0K Oct 22 20:20 exiftool
drwxr-xr-x 3 www-data www-data 4.0K Oct 22 20:20 .
drwxr-xr-x 9 www-data www-data 4.0K Oct 22 20:20 ..
-rw-r--r-- 1 www-data www-data 6.9M Oct 22 20:20 exiftool-aarch64-glibc
-rw-r--r-- 1 www-data www-data 8.5M Oct 22 20:20 exiftool-aarch64-musl
-rw-r--r-- 1 www-data www-data 7.2M Oct 22 20:20 exiftool-amd64-glibc
-rw-r--r-- 1 www-data www-data 8.6M Oct 22 20:20 exiftool-amd64-musl`

**Comment by pulsejet** [comment]
Interesting. Looks like we just need to set the executable bit. Thanks for reporting this!

**Comment by pulsejet** [comment]
Fixed in https://github.com/pulsejet/memories/commit/d8fea76992e8a2490dec3c3bc4f78777d345c3e9
Please let me know if the error shows up again in the next version upgrade.

**Comment by pulsejet** [comment]
@teemue please test with v4.3.3 and reopen the issue if this happens again. Thanks!

**Comment by teemue** [comment]
> @teemue please test with v4.3.3 and reopen the issue if this happens again. Thanks!

Tested:  no problems. Thank you!
