### ISSUE TITLE
Allow sharing of multiple pictures in android app

### ISSUE THREAD

**Issue by matthias-k** [pulsejet/memories#901]
**Is your feature request related to a problem? Please describe.**
Often I want to share multiple pictures e.g. with my family in a messaging app. I would love to use gallery for this, especially with the android app, because in the android app I have both my not-yet-uploaded photos (if I'm on the road with bad connection) as well as the pictures which, e.g., my partner took.

While it's quite convenient to share a single picture from the app, I don't see any share-button when selecting multiple images.

**Describe the solution you'd like**
When selecting multiple images (or videos) in the android app, somewhere (e.g. in the context menu) a share button should appear which allows to send the selected images via other apps such as Signal, WhatsApp, Mail etc. Preferably as in the case of single-image-sharing with an option to share reduced resolutions, but I would be already happy if I can only share the originals.

**Describe alternatives you've considered**
* I could download the images and then share the downloaded images, but this is more complicated and requires cleaning the downloads up afterwards
* I could create an album for the selected images and share the album, but that also requires more work and I would like to share the images themselves without other people having to access my nextcloud instance

**Additional context**
The feature would be especially helpful in the android app because this one also shows local images. It would allow me to get mostly rid of the google photos app, which I'm right now still using for sharing.

**Comment by pulsejet** [comment]
Agree this is needed 100%
