### ISSUE TITLE
Keep transcoded data (go-vod)

### ISSUE THREAD

**Issue by craiq** [pulsejet/memories#907]
**Is your feature request related to a problem? Please describe.**
My problem is, that my CPU is not that strong and it takes some time to transcode a video, especially in higher resolutions. Probably also the access to my storage is not fast enough. When I check the tmp folder with go-vod, I can see that cache files are created, but deleted quite fast, after another video is played.

**Describe the solution you'd like**
So my hope was, that when I run the transcoding it will be stored for maybe a month after last use or until a certain amount data is created and then deleting the oldest. Everytime a video is played it will stream the transcoded files directly, without the need of a new transcoding

**Describe alternatives you've considered**
Alternative is to wait / invest in stronger hardware

**Comment by pulsejet** [comment]
Related (could say duplicate) #232

**Comment by craiq** [comment]
continue in #232
