### ISSUE TITLE
Adjust previews so marked person is visible 

### ISSUE THREAD

**Issue by illnesse** [pulsejet/memories#91]
Example: marked person isn't visible in preview, only in full view, but then there's no green rectangle and you can't be sure which face is being referenced: 

![Screenshot_20221022-230725](https://user-images.githubusercontent.com/40355982/197362542-c0f4843d-1660-4b08-95a1-bf545a26900d.png)

Basically we need to make sure the green rectangle is visible in previews, sounds like a lot of fun math 😅 not sure how I'd do it, maybe something like this..

- check if all 4 corners are in view
- if not -> adjust view so they are (with some min padding to the edge)
- if green rectangle/face is cut off in photo -> do more math idk 🙋

**Comment by pulsejet** [comment]
Did you run `occ memories:index -f` after upgrading to v4.3? Or is this on mobile?

**Comment by illnesse** [comment]
Screenshot is from mobile, what does the -f do? I haven't ran index for a while

**Comment by pulsejet** [comment]
Makes sense. Not sure how this could be fixed though; let's see.

You need to run index after the 4.3 update because exiftool also stores the image size now (needed for the tiled layout). `-f` forces a re-run and indexes all images.

**Comment by illnesse** [comment]
Ok it's doing its thing now.
I got this:
`Exiftool not found: /var/www/nextcloud/apps/memories/lib/../exiftool-bin/exiftool/exiftool`           
`Exiftool not found: /var/www/nextcloud/apps/memories/lib/../exiftool-bin/exiftool-amd64-glibc`
But guess it found it elsewhere 
Also a few random `Exiftool may have crashed, restarting process` but seems fine

**Comment by pulsejet** [comment]
Weird. Are you running off git or installed from the app store?

**Comment by illnesse** [comment]
git
```
whereis exiftool
exiftool: /usr/bin/exiftool
```

**Comment by pulsejet** [comment]
Then you need to run `make exiftool` to download exiftool first. Memories ships with it's own version now.

**Comment by illnesse** [comment]
Thanks, better now, ill test the layout when it's done indexing 👍🏼

**Comment by illnesse** [comment]
That fixed it

**Comment by sirdrakeistda** [comment]
> Just to make sure, mobile always has the square layout right? So this issue actually still exists on mobile. But low priority imo, as long as desktop works
Can you show an image how it should look? I've never seen a green rectangle, neither on desktop or mobile.

**Comment by sirdrakeistda** [comment]
There is no box for me in the upper right. There is the option to merge or remove persons. The only checkbox I see is the checkbox for every image. Activating this does not show a rectangle for me.

**Comment by pulsejet** [comment]
@sirdrakeistda To be sure, is this activated? https://github.com/pulsejet/memories/issues/79#issuecomment-1283006285
Also you need to refresh the page after ticking that.

**Comment by sirdrakeistda** [comment]
I'm confused at the moment. Are memories and recognize two different apps? I only installed recognize (because only this app was suggested in the photo app).
https://github.com/nextcloud/recognize/issues/429#issuecomment-1293874772

**Comment by pulsejet** [comment]
> Are memories and recognize two different apps?

Umm yeah.

**Comment by pulsejet** [comment]
Thumbs aren't cropped anymore 🎉
