### ISSUE TITLE
Less strict hasRemote check

### ISSUE THREAD

**Issue by tuxArg** [pulsejet/memories#913]
Hi,

I'll try to describe my problem. My nextcloud instance automatically reduces image and video quality, so all resulting files have different size than original media. When using the android app, all media get duplicated because they aren't detected as being the same.
I've read the code and there's a AUID and BUID checked. The first checking filename+size. The second, ImageUniqueID exif tag (can't find any image with that tag). So, I would like if there's the possibility to check just basename (maybe +timestamp) for hasRemote boolean var.

Thanks

**Comment by pulsejet** [comment]
1. BUID uses basename+size when no `ImageUniqueID` is present https://github.com/pulsejet/memories/blob/98429bfdbbfc736f6aa92124ab0d733f25f1f130/lib/Exif.php#L306-L314
2. BUID is  computed only once on upload.

So if you've using auto upload, unless the resizing happens synchronously, the BUID on the device and the server should always match and de-duplicate files. If the resizing is synchronous then that app would be incompatible with Memories.

Just using basename isn't good enough because shared libraries may have multiple images from different cameras having the same basename, e.g. with sequential naming and the timestamp may not exist (also it may change).

**Comment by tuxArg** [comment]
Hi @pulsejet, thanks for your comment. 
I can see that both uses filesize (as long as ImageUniqueID tag is missing). But, let me ask you if you know how does the app knows the server filesize? Maybe I could run a script to fake it to the original filesize?
If I understand correctly what you say if I can make resizing happens async (like 1 day after or how long?), then memories would get the original filesize. Is that per device or is it stored in server db?

Thanks

**Comment by pulsejet** [comment]
>  But, let me ask you if you know how does the app knows the server filesize?

It doesn't. The server sends the AUID and BUID for each file, which the client compares with the local files.

> If I understand correctly what you say if I can make resizing happens async (like 1 day after or how long?), then memories would get the original filesize.

I expect so. No need for a delay, it just shouldn't happen immediately after upload _before_ memories can index the file.

> Is that per device or is it stored in server db?

The BUID is computed and stored in the server DB upon first upload. This then remains stored unless you run `occ memories:index --clear`, even if you rename or edit the file

**Comment by tuxArg** [comment]
I think I understood. I forgot to tell you that this resizing is not an app, just an external script that runs a few minutes after upload, resizes the file, and runs `occ files:scan -p file` at the end. I think that this files:scan is the problem here and Memories is treating it as a new file (even if it has the same filename). I'm not sure how to do this rescan otherwise, if I omit it then filesizes and quota would be wrong.

**Comment by pulsejet** [comment]
> I think that this files:scan is the problem here and Memories is treating it as a new file (even if it has the same filename).

Ah I see. If this is the case then this is a bad idea, it'll also break things like tags etc. if the script doesn't run in time. You probably want to use the Nextcloud / WebDAV API to edit the files instead of directly modifying them on disk.

**Comment by tuxArg** [comment]
@pulsejet good idea about using webdav! Although, I have tested it and it really was what you mention first. Files were being modified before memories indexed them. So, I think I have worked it out. I have to manually run `occ memories:index` before resizing and it will not be replaced its buid. Just one question about this. I can't find a way to index just one file, only whole folders. Is that really safe for already indexed files or I will be messing up again running it for the same folder upon uploading each file?

**Comment by pulsejet** [comment]
Index only works on files that have changed so you might be fine. You can specify a user and a folder to index though which might be much more efficient. Either way, I still recommend using webdav if you can.

See https://memories.gallery/occ-commands/#occ-memoriesindex

**Comment by tuxArg** [comment]
@pulsejet thanks a lot for your suggestion. It was really helpful. I don't think I can use dav because there's no such thing as a super user that could modify files from any user.
Just in case anyone reads this looking for a similar solution. There's some race between triggers that run postwrite, I don't know if it's deterministic. But before modifying the media file on the filesystem, I decided to check on the oc_memories table if the file exists and run `occ memories:index --skip-cleanup --user="user" --folder="folder"` if it doesn't. That way buid is calculated before and saved. It is also useful to save original filesize somewhere (as exif tag would work) if you need to rebuild the index for whatever reason.
Tested for a few hours and over 500 files, all buid were correctly saved with the original filesize.

**Comment by pulsejet** [comment]
Awesome! I'm hoping to find time at some point to document how the native sync works; will probably mention this thread there.
