### ISSUE TITLE
Share function in Memories Android App doesn't copy the full path into clipboard

### ISSUE THREAD

**Issue by stoneubi** [pulsejet/memories#914]
Systemsetup: Latest NC Version 27.1.3, latest Memories app in Nextcloud and latest android version installed on smartphone. 

**Describe the bug**
Android app: during the process of creating a shareable link the link will be copied to the clipboard of android. If you paste the link into any other app to share it only a number is visable and not the link

**To Reproduce**
1. Open Nextcloud App and create a new folder under pictures 
2. Copy some pictures to this newly created folder 
3. Open Memories App on smartphone and select dicover -> folders
4. Open the folder and select the share button
5. Select create link -> a message will pop up informing that the link was copied to the clipboard
6. Select any other app on the smartphone and pase the clipboard information in -> only a number will be shown

Thank you and best regards
Stoneubi

**Comment by pulsejet** [comment]
I can't repro this but it might already be fixed on master.

**Comment by stoneubi** [comment]
275928

https://github.com/pulsejet/memories/assets/32926093/29ea5144-775b-4717-9b9e-fab8c531c669

Please see the actual status as an example.

Maybe this is fixed. I will test once the update is available.

Thank you

**Comment by pulsejet** [comment]
From my understanding, it's simply not copying anything. The number is probably already in your clipboard.

**Comment by stoneubi** [comment]
No not really. During my tests I found out that my clipboard is empty and after copying the link this number is in the clipboard.

**Comment by pulsejet** [comment]
Please check with v6.1.0 and the latest android app version (1.6)

**Comment by stoneubi** [comment]
Perfect, now it works. 

Thank you so much for this mind-blowing app.

It should definitely re-place the default photos app in nextcloud.

**Comment by pulsejet** [comment]
Great!
