### ISSUE TITLE
Changing date of a picture sets it to the current time

### ISSUE THREAD

**Issue by ZeroKun265** [pulsejet/memories#915]
**Describe the bug**
When changing the date of an image it sets the date to be the current date instead of the one set by the user, seems to be similar to issue #612  

**To Reproduce**
- Edit a picture's date (by either the details tab or the edit metadata option)
- Save the update
- If needed refresh the index
- See it is nwo at the top with the current date

**Platform:**

- OS: Rocky Linux 9.2 on the server, Arch Linux on the client
- Browser: Chrome
- Memories Version: 6.0.1
- Nextcloud Version: Nextcloud Hub 6 (27.1.2)
- PHP Version: 8.1.24

- Any errors in the JS console? 
`NcSelectTags.js:2 Loading systemtags failed TypeError: Cannot read properties of undefined (reading 'd:status')
    at l (NcSelectTags.js:2:185646)
    at NcSelectTags.js:2:187642
    at async a.created (NcSelectTags.js:2:187109)`

This pops up when editing metadata, but not when editing only the date from the "info" section

- Any errors in the Nextcloud server logs?
Some errors about indexing but for files that are not only unrelated, but from another user

**Comment by pulsejet** [comment]
Please provide a sample file

**Comment by ZeroKun265** [comment]
https://www.mediafire.com/file/a7ggmyg8mz276xr/Photos.zip/file
In the mediafire link there are 2 pictures
no_change.jpg doesn't change the date when modified but it doesn't go to the  current date
current_date.jpg instead has it's date set to the current date

**Comment by ZeroKun265** [comment]
Wait i just realized, could the issue be that the pictures are owned by my own user(zerokun265)? while other files are owned tape(some are owned by root as well idk why)?

**Comment by pulsejet** [comment]
I cannot this reproduce on master so suggest to wait and test with the next release.

**Comment by ZeroKun265** [comment]
On master do both files change their date when edited? If so then I'll wait for an update to come and come back to it

**Comment by pulsejet** [comment]
Please check with v6.1.0

**Comment by ZeroKun265** [comment]
Seems to still be here.
Tried on my phone since it's already late where I live, I can get some better testing in tomorrow.
Still, tries to change the date of the flower picture and it got reset to right now, the second one instead sees no change in date like before.

All I did was go to "apps", click update then refresh the nextcloud page, tomorrow I'll see if there are any logs or if refreshing the db fixes it(idk, random things), let me know if there is something you want me to test or if I did something wrong in updating

**Comment by pulsejet** [comment]
The apps page should tell you the version of memories.

> As an experiment, can you try editing the image twice and see if that changes anything? Also do you see a "missing date" prompt when you try to edit the date?

Also this.

**Comment by pulsejet** [comment]
I just tried again and I can definitely edit both files just fine. So if you still have this issue it could be a permissions thing. Maybe also try uploading the file *through the nextcloud interface* to a different folder, then try editing that file.

**Comment by ZeroKun265** [comment]
Ok so i tried with both types of pictures and when reuploading them using nextcloud everything works fine.
Permissions for "broken" files: `-rw-r--r--. 1 zerokun265 zerokun265    200499 Oct 24 11:48  IMG-20220111-WA0011.jpg`
Permissions for working files: `-rw-r--r--.  1 33 tape 120165 Nov 16 13:49  IMG_20220309_164640.jpg`

I'm guessing i just need to change the permissions
Running `chown -R --reference=path/to/good/file Photos/` fixed the issue..
Damn i'm dumb
