### ISSUE TITLE
TypeError: stripos(): Argument #1 ($haystack) must be of type string, null given in /config/www/nextcloud/apps/memories/lib/Exif.php:418

### ISSUE THREAD

**Issue by Starvin86** [pulsejet/memories#92]
When running ./occ memories:index i get the error.

All output:
musl libc (x86_64)
Version 1.2.2
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname
An unhandled exception has been thrown:
TypeError: stripos(): Argument #1 ($haystack) must be of type string, null given in /config/www/nextcloud/apps/memories/lib/Exif.php:418
Stack trace:
#0 /config/www/nextcloud/apps/memories/lib/Exif.php(418): stripos()
#1 /config/www/nextcloud/apps/memories/lib/Exif.php(464): OCA\Memories\Exif::getExiftool()
#2 /config/www/nextcloud/apps/memories/lib/Exif.php(48): OCA\Memories\Exif::initializeStaticExiftoolProc()
#3 /config/www/nextcloud/apps/memories/lib/Command/Index.php(136): OCA\Memories\Exif::ensureStaticExiftoolProc()
#4 /config/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Memories\Command\Index->execute()
#5 /config/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#6 /config/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#7 /config/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#8 /config/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#9 /config/www/nextcloud/console.php(100): OC\Console\Application->run()
#10 /config/www/nextcloud/occ(11): require_once('...')

**Comment by pulsejet** [comment]
Please test with v4.3.3 and reopen if the issue persists.
