### ISSUE TITLE
Share link doesn't copy to clipboard when sharing via web UI

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#925]
**Describe the bug**
Share link does not copy to clipboard. (Mobile works fine)

**To Reproduce**
Select an image and click the 'share' icon.
Create a share link.
Click the Share link to try to copy to clipboard.

**Screenshots**
![image](https://github.com/pulsejet/memories/assets/10717998/7531390b-8b10-42db-88c4-29131d031706)

**Platform:**

- OS: Linux (KDE Neon)
- Browser: Firefox
- Memories Version: 6.1
- Nextcloud Version: 27.1
- PHP Version: 8.2

**Additional context**
Mobile doesn't seem to be affected.

- Any errors in the JS console: None
- Any errors in the Nextcloud server logs: None that i can see that are relevant.

**Comment by pulsejet** [comment]
Firefox-specific regression introduced in 6.1
