### ISSUE TITLE
RAW stacking doesn't work with live/motion photos for Pixel 6a

### ISSUE THREAD

**Issue by llucax** [pulsejet/memories#927]
**Describe the bug**
The new (**amazing** I must say) stacking feature for raw photos doesn't seem to work well with live/motion photos in Google Pixel 6a phones. At least I would expect that photos are still stacked together and they have both the "RAW" marker and the "motion" (play button) marker.

**To Reproduce**
1. Upload a live/motion photo and the accompanying raw from a Google Pixel 6a phone
2. See how they are not stacked together

**Screenshots**
![image](https://github.com/pulsejet/memories/assets/1031485/3c140cbd-00c7-4fc2-a392-e436f535a318)

You can see in here that the first 2 (non montio/live) photos are properly stacked (they are shown only once) but the third is not (a fourth photo which is exactly the same is shown, even when they are the same photo).

**Platform:**

- OS: Linux (Debian)
- Browser: Tested both in Firefox and Chromium
- Memories Version: 6.1.0
- Nextcloud Version: 27.1.3
- PHP Version: 8.1.12

**Additional context**
Looking a bit more closely to this, I realized this is probably because these pictures don't have the exact same name, as motion pictures (at least in Google Pixel 6a) have a `.MP.jpg` extension (and the raw is just `.dng` without the `.MP`), so I'm not sure if this should be a bug report or a feature request. It would be good if this is directly supported by Memories, but otherwise maybe there could be a configuration option to add "suffixes" to ignore while considering stacking.

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

Nope.

**Comment by pulsejet** [comment]
Your diagnosis is right. This is really the reason I don't like matching filenames

**Comment by pulsejet** [comment]
@llucax can you provide a sample pair to test?

**Comment by llucax** [comment]
Of course!

Attaching as a zip to preserve file names (and because silly GitHub doesn't allow to upload .dng files :roll_eyes: 

[PXL_20231105_133609148.zip](https://github.com/pulsejet/memories/files/13435922/PXL_20231105_133609148.zip)

**Comment by pulsejet** [comment]
![image](https://github.com/pulsejet/memories/assets/10709794/422b6057-255e-42b3-affb-748ba424edb8)

**Comment by llucax** [comment]
Amazing! Thanks a lot!

**Comment by dsiemienas03** [comment]
Having the same issue with the pixel 8 pro with file names I am able to attach a zip with both if needed
`PXL_20240112_185531606.RAW-01.COVER.jpg`
`PXL_20240112_185531606.RAW-02.ORIGINAL.dng`

**Comment by llucax** [comment]
Hi, sorry for resurrecting this issue, but before opening a new one I thought I should check first. The Pixel camera es finding more and more creative ways to name files so this *broke* again. Like: 

* `PXL_20240301_111307582.RAW-01.COVER.jpg` / `PXL_20240301_111307582.RAW-02.ORIGINAL.dng` (regular pic)
* `PXL_20240229_154435982.RAW-01.MP.COVER.jpg` / ``PXL_20240229_154435982.RAW-02.ORIGINAL.dng` (moving pic)

I can imagine maintaining this for every crazy manufacturer might be unrealistic, so I was wondering if it couldn't make sense to add some advanced option to use custom regex patterns to be removed when considering pictures to be variations of the same picture for stacking. For example, I could use something like: `\.RAW-[0-9]+\.(MP\.)(COVER|ORIGINAL)`.

**Comment by pulsejet** [comment]
That's completely retarded. Any idea why the JPEG would say RAW, and with a different prefix from the DNG?

**Comment by llucax** [comment]
> That's completely retarded.

I hope you are talking about Google and not me :laughing: 

> Any idea why the JPEG would say RAW, and with a different prefix from the DNG?

Absolutely no idea. My wild guess is they are probably just adding RAW to all files when RAW mode is enabled, but only Google knows I guess. :shrug:
