### ISSUE TITLE
Motion/live photos from Google Pixel 6a doesn't show the animation/video

### ISSUE THREAD

**Issue by llucax** [pulsejet/memories#928]
**Describe the bug**
When viewing a motion/live photo taken with Google Pixel 6a, I can't see the animation. I see the motion photo icon, but the video is never played.

**To Reproduce**
1. Upload a motion picture from a Google Pixel 6a phone
2. Got to Memories
3. Click on the photo
4. See no motion

**Screenshots**
It would have to be a video to be useful, I guess. Let me know if it would be useful and I can upload something.

**Platform:**

- OS: Linux (Debian)
- Browser: Tried Firefox and Chromium
- Memories Version: 6.1.0 (but it never worked for me, I started using Memories at around 4.x or something)
- Nextcloud Version: 27.1.3
- PHP Version: 8.1.12

**Additional context**
Not sure if is a problem with the phone, though, but I thought it is relevant which phone it is, as I found another issue with the same console messages I see and also with a Google phone:

* https://github.com/pulsejet/memories/issues/373

I also tried to extract the video using the sh snippet in that issue and it worked. I copy it here for convenience:

```sh
for i in PXL*.jpg; do \
  ofs=$(grep -F --byte-offset --only-matching --text ftypisom "$i"); \
  ofs=${ofs%:*}; \
  [[ $ofs ]] && dd "if=$i" "of=${i%.jpg}.mp4" bs=$((ofs-4)) skip=1; \
done
```

Here is a sample image in case its useful:

![PXL_20231105_133609148 MP](https://github.com/pulsejet/memories/assets/1031485/e1273cd5-1377-4ed6-b638-d25c2f4d1073)

I never reported this before because I thought it was something Firefox didn't support, as I also can't play the h265 videos that this phone produces in Firefox, but then I found the above issue and thought maybe it is not that.

- Any errors in the JS console?

Only in Firefox:
```
OC.requestToken changed u+ntLQm0RmVXUpr5+YJFLAu5sXv2GZwNcKnG5qyRnpY=:wpqmVGTODQhmfdSqo8UjeHuPwAibYdZqA/CHhfT/qPM= index.js:318:9
Media resource https://example.com/apps/memories/api/video/livephoto/1008182?etag=bba2a3cbe9bff443a7e1ce07312fe9e4&liveid=self__traileroffset%3D3806281&transcode=jtb506fb6400 could not be decoded. memories
Media resource https://example.com/apps/memories/api/video/livephoto/1008182?etag=bba2a3cbe9bff443a7e1ce07312fe9e4&liveid=self__traileroffset%3D3806281&transcode=jtb506fb6400 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_METADATA_ERR (0x806e0006) memories
```

- Any errors in the Nextcloud server logs?
```
{"reqId":"wjlVaV13lkNWFK3LBUB1","level":0,"time":"2023-11-18T23:32:19+00:00","remoteAddr":"94.134.57.8","user":"luca","app":"no app in context","method":"GET","url":"/apps/memories/api/image/preview/1008124?c=93b904677a3d7fb59c230e9c73b0e923&x=1919&y=1080&a=1","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0","version":"27.1.3.2","data":[]}
{"reqId":"mEkaqnL3fWSJM98Ieyx2","level":0,"time":"2023-11-18T23:32:21+00:00","remoteAddr":"94.134.57.8","user":"luca","app":"no app in context","method":"POST","url":"/apps/memories/api/image/multipreview","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0","version":"27.1.3.2","data":[]}
{"reqId":"mEkaqnL3fWSJM98Ieyx2","level":0,"time":"2023-11-18T23:32:21+00:00","remoteAddr":"94.134.57.8","user":"luca","app":"no app in context","method":"POST","url":"/apps/memories/api/image/multipreview","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0","version":"27.1.3.2","data":[]}
{"reqId":"oueMRQuKo2t5BClFLqda","level":0,"time":"2023-11-18T23:32:22+00:00","remoteAddr":"94.134.57.8","user":"luca","app":"no app in context","method":"GET","url":"/apps/memories/api/image/preview/1008486?c=188c62faa7ac3fa116e5002968e34227&x=1919&y=1080&a=1","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0","version":"27.1.3.2","data":[]}
{"reqId":"E85YKN4Og2U6NCDsLOTg","level":0,"time":"2023-11-18T23:32:22+00:00","remoteAddr":"94.134.57.8","user":"luca","app":"no app in context","method":"GET","url":"/apps/memories/api/image/preview/1008642?c=4a621b531961901ffcd47cfc53fe35c5&x=1919&y=1080&a=1","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0","version":"27.1.3.2","data":[]}
```

**Comment by llucax** [comment]
Now I found:

* https://github.com/pulsejet/memories/issues/388

And looking at my extracted video, it seems like it is h265, so maybe that's the issue after all?

**Comment by pulsejet** [comment]
Do you have transcoding working? Live videos should be transcoded too

**Comment by llucax** [comment]
No, I tried one or two times but failed. My nextcloud instance runs in a very cheap VPS, and I think it can't handle the transcoding, but I remember also having some error.

AFAIK h265 is really intensive, especially if there is no hardware acceleration, so that's expected, right? Or should it be able to run in low end machines too?

**Comment by pulsejet** [comment]
Yeah, I don't expect a VPS to transcod h265. So basically there's no solution here, since browsers simply don't support h265.

**Comment by llucax** [comment]
Understood, then it was lack of browser support after all as I initially assumed. Thanks for confirming!
