### ISSUE TITLE
Face rectangle off

### ISSUE THREAD

**Issue by illnesse** [pulsejet/memories#93]
![Screenshot_20221023-010230](https://user-images.githubusercontent.com/40355982/197365483-8bb5a601-149b-48d9-8e4b-66208b72994e.png)

Not sure if recognize messed up here or if something is wrong with the rectangle math, but i have a few hundred of these

**Comment by pulsejet** [comment]
Probably recognize. Does this happen only in some faces or all?

**Comment by illnesse** [comment]
Independent of face but sometimes it affects the whole series of shots, like 10 in a row, can't make out a pattern so far

**Comment by illnesse** [comment]
Thanks, better now, ill test the layout when it's done indexing 👍🏼

**Comment by pulsejet** [comment]
Closing in favor of #170
