### ISSUE TITLE
Suppress indexing errors in case of empty file

### ISSUE THREAD

**Issue by PatrickJosh** [pulsejet/memories#933]
**Is your feature request related to a problem? Please describe.**
Firstly, I'd like to say that I am unsure if this is rather a bug report or a feature request. If I have chosen the wrong template in your opinion, I am sorry.

Sometimes, it happens that files are not successfully uploaded, e.g. by the app for Android. Then, sometimes an empty file (0 bytes in size) is created. Memories still tires to index that file, I guess because of the file extension, I issues errors like the following for each of these files:

```
[memories] Error: Failed to index file /joshua.noeske/files/InstantUpload/Camera/20220814_102903.jpg: No MIMEType in EXIF data: /joshua.noeske/files/InstantUpload/Camera/20220814_102903.jpg

at 2023-11-21T10:04:54+00:00
```

These errors are quite new, at least I cannot remember that they have appeared before version 6.1. Since they fill up the log quite extensively, they are quite annoying.

**Describe the solution you'd like**
It would be nice if you could suppress these messages, or if they were only issued if the file is newly created, modified or if the index is forcibly rebuilt. In the latter case, it would also be nice if you could get a list of all files for which the indexing has failed, since you can then have a look what's wrong with the files.

**Describe alternatives you've considered**
Disabling the error messages completely does not sound like a good idea, at least to me. Maybe there could be a setting with which they can be turned on or off? In this case, it would also be nice to be able to get an overview of the files for which the indexing has failed.

**Additional context**
Server version: (27.1.3)

<details>
<summary>Configuration</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.noescloud.de",
            "cloud.joshuanoeske.de",
            "127.0.0.1"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.3.2",
        "overwrite.cli.url": "https:\/\/cloud.noescloud.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "default_language": "en_GB",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "enabledPreviewProviders": [
            "OC\\Preview\\BMP",
            "OC\\Preview\\GIF",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\PNG",
            "OC\\Preview\\TXT",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Krita",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "default_phone_region": "DE",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "0"
        },
        "htaccess.RewriteBase": "\/",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logfilemode": 384,
        "lost_password_link": "disabled",
        "updater.release.channel": "stable",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "memories.gis_type": 1,
        "memories.exiftool_no_local": true,
        "memories.vod.path": "\/var\/www\/nextcloud-subvolume\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe"
    }
}

```

</details>
PHP: 

```
PHP 8.2.12 (fpm-fcgi) (built: Oct 24 2023 19:22:16)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.12, Copyright (c), by Zend Technologies
```

Memories version: 6.1.0

If you need any additional information, don't hesitate to ask.
Thanks very much!

**Comment by PatrickJosh** [comment]
By the way, I use system perl for the exiftool since the configuration of the binary is rather tricky since I use SELinux in enforcing mode. System perl has version v5.36.1.

**Comment by pulsejet** [comment]
Are these files any use? Maybe we could just get rid of them?

**Comment by PatrickJosh** [comment]
No, not really. I only used them (or rather the error messages) to spot unsuccessful uploads. But that should not be Memories' task. However, in case of file changes, the files should be considered again. Maybe there can be a joint solution for corrupted, i.e. files whose exif data cannot be parsed or are not valid in another way, and empty files.

**Comment by pulsejet** [comment]
Probably https://github.com/pulsejet/memories/issues/917#issuecomment-1821382510

**Comment by pulsejet** [comment]
Zero byte files will simply be skipped now (you can apply the patch above on your system).

> Disabling the error messages completely does not sound like a good idea, at least to me. Maybe there could be a setting with which they can be turned on or off? In this case, it would also be nice to be able to get an overview of the files for which the indexing has failed.

I considered this for a while, but this really isn't our problem to solve. It might make sense to have a separate app or something in the admin panel to track and clean up failed uploads etc.

**Comment by PatrickJosh** [comment]
Thanks very much! I think this is a good solution, as long as files are re-evaluated in case of file changes.

I just installed v6.1.5 and will test it with this version now.

**Comment by PatrickJosh** [comment]
I tested it with an empty file and it worked flawlessly, the re-indexing after the file has changed worked as well. Thank you!
