### ISSUE TITLE
Setting up external hw transcoding on unraid (nvidia)

### ISSUE THREAD

**Issue by jeliastam** [pulsejet/memories#936]
1. search `go-vod` in community apps and click the link in the upper right to get results from DockerHub
2. select the option from `radialapps` and do a test install to generate a template
3. enable `advanced view` in the upper right
4. add `:latest` to the repository to ensure you have the latest version of go-vod!
5.  Under `Extra parameters`, add `--runtime=nvidia`
6. add missing variables/paths as needed (basic view shown):
![image](https://github.com/pulsejet/memories/assets/2113009/f062f58b-42c8-4d86-885a-94e30266e435)

- `/ncdata` should point to your appdata location for nextcloud
- `/data` should point to where all user data for nextcloud is stored
- make sure all volumes are mounted as READ-ONLY

In the memories admin section of nextcloud:
1. Under `Transcoder` set the path to your `go-vod` docker, this probably can be done with docker networks, but I just pointed it to my unraid IP and the go-vod port, ie 47788
2. enable NVENC under `HW Acceleration`
3. enable CUDA scaler in the same section
7. If your videos are stalling playback when trancoding, try enabled the `streaming GOP size workaround` located at the bottom of the settings page (it resolved my playback issues)

**Comment by AhmedAburady** [comment]
I get this error in go-vod container 
Failed to fetch https://192.168.50.91:444/index.php/apps/memories/static/go-vod?arch=x86_64
i tried everything

**Comment by jeliastam** [comment]
can you curl that address from the terminal?
