### ISSUE TITLE
Failed to index file : No MIMEType in EXIF data:

### ISSUE THREAD

**Issue by phirestalker** [pulsejet/memories#938]
**Describe the bug**
In the log I see message like the title for mp4 files.

**To Reproduce**
Enable memories app

**Platform:**

- OS: [e.g. iOS] n/a
- Browser: [e.g. Chrome, Safari] Chrome
- Memories Version: [e.g. 4.1.0] 6.1.0
- Nextcloud Version: [e.g. 25.0.6] 27.1.3
- PHP Version: [e.g. 8.1] 8.2.12

- Any errors in the Nextcloud server logs?
Yes, the mentioned error

As far as I understand, the mime type is not actually stored inside the EXIF data, and movie files have their own metadata tags. I don't know why it would say that. I do not know how long this has been happening because I was checking the logs for another issue.

**Comment by pulsejet** [comment]
Please provide a sample file for which this happens.

> As far as I understand, the mime type is not actually stored inside the EXIF data

exiftool infers the mime type for all files. If it can't be inferred, reading the EXIF failed

**Comment by phirestalker** [comment]
> exiftool infers the mime type for all files. If it can't be inferred, reading the EXIF failed
That makes sense

Well this is embarrassing. It turns out that all those lines were for the same file. That file shows as 0 bytes and the original on my phone won't play either.  I guess there is no bug after all.

**Comment by pulsejet** [comment]
Yep #933 then
