### ISSUE TITLE
public shared album infinite loading

### ISSUE THREAD

**Issue by ereynier** [pulsejet/memories#940]
**Describe the bug**
 I have a public shared album, everything worked fine for a day or two, then when people tried to open it (on phone web app), there was an infinite loading of photos (with the 3 dots, the page is loaded), whereas it works fine in a private window. I tried deleting and recreating the link and the problem came back after a day. They are not connected on Nextcloud and I don't know how to reproduce the bug, it works fine on my phone (on the browser where I am not connected).

**To Reproduce**
I have no idea. Probably share an album and open it on a phone that has never been logged to nextcloud neither have memories webapp installed

**Screenshots**
Just the album page with the spinner but not the photos.

**Platform:**

- OS: Android, IOS
- Browser: Chrome, Safari
- Memories Version: 6.1.0
- Nextcloud Version:: 27.1.3
- PHP Version: 8.2.12

**Additional context**
When the user is on the shared album and the spinner is loading, the 3 same logs are spammed:
```
{"reqId":"k50baQ158gAARWEDbUaI","level":0,"time":"2023-11-22T20:16:37+00:00","remoteAddr":"<hidden IP addres>","user":"--","app":"PHP","method":"GET","url":"/apps/memories/api/config","message":"Creation of dynamic property OCA\\Maps\\Hooks\\FileHooks::$lockingProvider is deprecated at /config/www/nextcloud/apps/maps/lib/Hooks/FileHooks.php#46","userAgent":"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36","version":"27.1.3.2","data":{"app":"PHP"}}
{"reqId":"k50baQ158gAARWEDbUaI","level":0,"time":"2023-11-22T20:16:37+00:00","remoteAddr":"<hidden IP addres>","user":"--","app":"video_converter","method":"GET","url":"/apps/memories/api/config","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36","version":"27.1.3.2","data":{"app":"video_converter"}}
{"reqId":"k50baQ158gAARWEDbUaI","level":0,"time":"2023-11-22T20:16:37+00:00","remoteAddr":"<hidden IP addres>","user":"--","app":"no app in context","method":"GET","url":"/apps/memories/api/config","message":"CSRF check failed","userAgent":"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36","version":"27.1.3.2","exception":{"Exception":"OC\\AppFramework\\Middleware\\Security\\Exceptions\\CrossSiteRequestForgeryException","Message":"CSRF check failed","Code":412,"Trace":[{"file":"/app/www/public/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php","line":96,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\Security\\SecurityMiddleware","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Http/Dispatcher.php","line":129,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/app/www/public/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/app/www/public/lib/base.php","line":1068,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/app/www/public/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/app/www/public/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php","Line":224,"message":"CSRF check failed","exception":{},"CustomMessage":"CSRF check failed"}}
```

**Comment by pulsejet** [comment]
This is helpful!

Does refreshing the page on the device where it doesn't work still cause the same thing?

**Comment by ereynier** [comment]
Yes, the only way to make it work was to copy the link to open it in a private window.

**Comment by pulsejet** [comment]
Do you mind sharing a public shared link to the instance? You can DM me if you like

**Comment by ereynier** [comment]
Can I send it in DM on discord ?

**Comment by pulsejet** [comment]
Sure

**Comment by pulsejet** [comment]
@ereynier can you check if you get the same errors with v6.1.1?

**Comment by ereynier** [comment]
I just tried and still not working...

**Comment by pulsejet** [comment]
Okay how about v6.1.4?

**In case this still doesn't work**: unfortunately the service worker logic was very broken and you might need to clear site data on the affected devices (basically to unregister the stale workers) to be able to update them. One thing that might trigger an update is to visit Memories _outside_ a public link (the link must end in `/apps/memories/`)

**Comment by pulsejet** [comment]
You'll likely need to refresh a couple of times regardless, to load the new app version.

**Comment by ereynier** [comment]
It works! Thanks
