### ISSUE TITLE
State of the automatic indexing: Indexing has not been run yet since installation

### ISSUE THREAD

**Issue by PolishTanker** [pulsejet/memories#941]
**Describe the bug**

After installation, I can't force automatic indexation to work. Or to be more clear, to hide below monits. 
I don't have any information in the logs, even on debug level. Manual indexing from occ is working.
Installation of nextcloud (nginx) don't have any problems and cron is working, nextcloud files have proper permissions.

**To Reproduce**

Install memories on bellow versions of soft and nginx.

**Screenshots**
![image](https://github.com/pulsejet/memories/assets/16049890/885b3070-c76c-46c6-9803-ea30b0b0414b)

**Platform:**

- OS: Debian 11
- Browser: Chrome, Samsung browser, Edge, Opera
- Memories Version: 6.1.0
- Nextcloud Version: 27.1.4
- PHP Version: 8.2 php-fpm

**Additional context**

- Any errors in the JS console? NO
- Any errors in the Nextcloud server logs? NO

**Comment by pulsejet** [comment]
> cron is working

Are you sure? This just indicates the internal cron memories job isn't running.

**Comment by PolishTanker** [comment]
Nextcloud says so, there is no errors from cron. Passwords for example gives signs of life after cron jobs.


![Screenshot_20231124_233339_Samsung Internet](https://github.com/pulsejet/memories/assets/16049890/b90e38b2-d3f3-432f-b217-d1bce737aadf)
![Screenshot_20231124_233158_Samsung Internet](https://github.com/pulsejet/memories/assets/16049890/c4f1f780-3d37-458d-a6b4-4ca37833980d)

**Comment by pulsejet** [comment]
Okay,

1. Any errors in the cron? You could try running cron.php manually
2. Does the jobs table contain the Memories jobs. Something like
    ```sql
    SELECT * FROM oc_jobs WHERE class LIKE '%Memories%'
    ```

**Comment by PolishTanker** [comment]
Manual cron execution from cli is executed without errors.

![Screenshot_20231125_000621_Termux](https://github.com/pulsejet/memories/assets/16049890/67c7252f-6a49-4e86-8ca0-83948af9bfe9)

**Comment by pulsejet** [comment]
That's interesting. Looks like the job did start ~12 hours ago but never completed.
1. What kind of environment is this? If docker, how are you running the cron job
2. Did you get this output before or after you manually ran cron?

**Comment by PolishTanker** [comment]
It is rasbian (debian 11), it is not dockered. Cron job is running from crontab in the same way the official documentation shows. What is weird I rebooted system twice and this output must be there since first run after installation.

**Comment by pulsejet** [comment]
> Did you get this output before or after you manually ran cron?

I meant, did you run the sql commands before or after the manual cron run

**Comment by PolishTanker** [comment]
After

**Comment by PolishTanker** [comment]
I don't understand, after night it started working. All day it didn't work, and now it is.

![image](https://github.com/pulsejet/memories/assets/16049890/a87f3cb7-b81f-42d9-b331-7ea8102da5c4)

**Comment by pulsejet** [comment]
I'm guessing there simply were too many things competing for cron time.
