### ISSUE TITLE
OCC cli options are not available in the web UI.

### ISSUE THREAD

**Issue by seefood** [pulsejet/memories#942]
using the occ to trigger indexing or other actions listed on https://memories.gallery/config/ is not an option for people using a web-only managed instance (e.g. I use one on Hetzner)

**Describe the solution you'd like**
I would like access to that functionality via the Web UI as well.

**Describe alternatives you've considered**
I could nag the support team each time I try a new feature or need to reindex for any reason, but I don't even know if they will help (I never tried, but it seems like a nuisance anyway)

**Comment by pulsejet** [comment]
Running indexing is optional. It should run automatically in the cron job if you doing trigger it.

**Comment by pulsejet** [comment]
https://github.com/pulsejet/memories/issues/514#issuecomment-1482703486

**Comment by seefood** [comment]
Ahh, thanks! I totally missed the news about https://konsoleh.hetzner.com/storage_share_occ.php

**Comment by seefood** [comment]
so I understand memories:places-setup is automaticaly covered by the WebUI. I'll try it again or contact Hetzner.
