### ISSUE TITLE
Unable to merge persons

### ISSUE THREAD

**Issue by escoand** [pulsejet/memories#95]
I'm unable to merge persons. It's always showing `Failed to move [id].`

There is only an info log entry:
```
Deprecated event type for OCP\IDBConnection::CHECK_MISSING_COLUMNS: Symfony\Component\EventDispatcher\GenericEvent is used
```

Nextcloud is on 25.0.0 and Memories on 4.3.3.

**Comment by pulsejet** [comment]
Are you using a shared folder/storage?

**Comment by escoand** [comment]
Similar, a group folder.

**Comment by pulsejet** [comment]
In a group folder I believe you need to be admin to move anything, since admin owns all the faces. Are you?

**Comment by escoand** [comment]
Nobody is the owner of group folders. It'a owned by the group.

But anyway, what do you mean by "move"? I thought it's just tagging in the database.

**Comment by pulsejet** [comment]
Unfortunately that's not how recognize works. Each face tag is "owned" by a user; in case of group folders that'll probably be `admin`. Only that user is allowed to update tags in the folder. The next version would show an error indicating which user can update the face.

If you need shared ownership of faces, file a separate issue.

**Comment by escoand** [comment]
Hmm, this could get difficult https://github.com/nextcloud/groupfolders/issues/1967

**Comment by pulsejet** [comment]
No, that is unrelated. This is about ownership of the folder. Recognize has a separate ownership for the face recognition clusters.

**Comment by escoand** [comment]
With the last update I now know the files are owned by my wife, thanks. But do you see some chance the files get changed by everybody allowed to see/edit the group folder?

**Comment by pulsejet** [comment]
It's possible but complicated. Like I said, file a separate feature request issue.
