### ISSUE TITLE
iOS Bookmarked Progressive Web App Issue With Bottom Margins. Home Bar Obscures 'Explore' Button.

### ISSUE THREAD

**Issue by ConfluxJL** [pulsejet/memories#957]
**Describe the bug**

There is a problem with the bottom margin on iOS in the Progressive Web App.

When you add the site to your home screen and open the app, the three menu buttons appear too low on the screen and are obscured by the Home Bar on iPhones without a physical Home Button.

![image](https://github.com/pulsejet/memories/assets/120368067/71693ebf-cbf9-4c2c-b8f0-60d8bda6dc42)

**To Reproduce**

Prerequisite: Grab an iPhone without a physical home button

1. Add site to Home Screen by tapping share, then tap "Add to Home Screen"

2. Open the sites "app" you just added to your Home Screen

3. Observe the home bar slightly obscuring the 'Explore' button. (As shown in the screenshot above)

**Platform:**

- OS: iOS 17.1.2
- Device: iPhone 15 Pro Max (likely also effects iPhones X, 11, 12, 13, 14, and 15, Pro and Plus versions also)
- Browser: Web App from Safari
- Memories Version: 5.5.3

**Additional context**

Most apps in iOS have a bit of margin between the Home Bar and menu button tabs at the bottom of the screen. (See screenshot of the Phone app for reference)
![image](https://github.com/pulsejet/memories/assets/120368067/a841da08-d209-41f9-badf-174089d85c82)

This is not an issue on the normal website in the Safari app, because Safari's website controls are between the Home Bar and the menu buttons. 

But when the website is saved to the home screen as a PWA (Web App), Safari's website controls are gone and there is no longer anything between the menu buttons and the bottom of the screen, with no additional margin to compensate for the presence of the Home Bar.

**Comment by pulsejet** [comment]
![image](https://github.com/pulsejet/memories/assets/10709794/f6e37271-0377-4021-b06c-c25289952927)
