### ISSUE TITLE
Exiftool test failed in settings

### ISSUE THREAD

**Issue by florealcab** [pulsejet/memories#960]
**Describe the bug**

In system settings of memories app, in the EXIF extraction part, I have a message in red indicating that exiftool test failed for that reason:

failed to copy exiftool-ocdxk959hxs7-12.70 binary from /var/www/vhosts/...path-to-nextcloud-folder.../apps/memories/exiftool-bin/exiftool-amd64-glibc to /tmp/exiftool-ocdxk959hxs7-12.70-aa10999e.

**To Reproduce**

Go to system settings of memories app and see the error.

**Screenshots**
Not needed

**Platform:**

- OS: [e.g. iOS] debian 12
- Browser: [e.g. Chrome, Safari] chromium
- Memories Version: [e.g. 4.1.0] 4.1.5
- Nextcloud Version: [e.g. 25.0.6] 27.1.4
- PHP Version: [e.g. 8.1] 8.2

**Additional context**

I see that exiftool-amd64-glibc is located in bin-ext folder, not in exiftool-bin folder. I can't change location of this script in settings (field is disabled) so maybe it's somewhere in the code?

**Comment by pulsejet** [comment]
Just run `occ maintenance:repair`. If that doesn't work, delete the `memories.exiftool` key in `config.php` and run it again.

**Comment by florealcab** [comment]
I run it, it does not change anything. So U delete memories.exiftool in config.php and I run `occ maintenance:repair` again.

Now I have that:
![image](https://github.com/pulsejet/memories/assets/16965090/14da4532-c89d-4cba-bcf1-08783909bc32)

Is that normal?

Here logs about memories in the last maintenance command:
```
- Repair steps for Memories
     - External table schema seem up to date
     - exiftool binary is configured: perl /secure/www/vhosts/alypie.fr/subdomains/cloud/httpdocs/apps/memories/bin-ext/exiftool/exiftool
     - go-vod binary is configured: /secure/www/vhosts/alypie.fr/subdomains/cloud/httpdocs/apps/memories/bin-ext/go-vod-amd64
     - ffmpeg binary is configured: /usr/bin/ffmpeg
```

**Comment by pulsejet** [comment]
You need to turn off system perl before running the maintenance command.
Anyway, it's fine to leave it as is if you've perl available; it's actually faster to use system perl.
