### ISSUE TITLE
Support for Nextcloud 28

### ISSUE THREAD

**Issue by jorti** [pulsejet/memories#961]
**Describe the bug**
Support for Nextcloud 28 (Hub 7)

**To Reproduce**
Upgrade to Nextcloud 28

**Screenshots**
App is disabled: `Server version 27 or lower is required.`

**Platform:**

- OS: Linux
- Browser: all
- Memories Version: 6.1.5
- Nextcloud Version: 28.0.0
- PHP Version: 8.2.13

**Additional context**
Nexcloud releases: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by ralfi** [comment]
Upgrade from 27.1.4 to 28.0.0 Docker based works whithout any probs

**Comment by jorti** [comment]
I used the container image `docker.io/library/nextcloud:28` and the Memories application was disabled because it requires 27 or lower.

I've rolled back the upgrade for now.

**Comment by ralfi** [comment]
Mmmmh, dont know. But you can remove and install again?

**Comment by jeremehancock** [comment]
I am having the same issue. I am using the official TrueNAS Nextcloud app.

**Comment by pulsejet** [comment]
Official support would land with the next release. For now you can just install memories from the app store and override the version check (enable untested)
