### ISSUE TITLE
.notimeline to hide from timeline

### ISSUE THREAD

**Issue by craiq** [pulsejet/memories#966]
**Is your feature request related to a problem? Please describe.**
I share a folder via memories, that includes highlight fotos and videos - several hundred already. Those videos are pre transcoded, so it's not needed to do this on runtime (delay). 
It's done via a folder, because 
- the album will be sorted from oldest to newest #558 and can't be changed for external user
  - for the grand grand parents it's not feasable to scroll thrue this amount of media with their phones
- there is no view only mode for albums
  - albums have a prominent download and share button (hide this via css already)
  - you should not be able to select the media (fix by css already)
- I can't get HW Transcoding to work (nc running in lxc container on proxmox)
  - a transcoding is needed, as IOS devices won't play the videos recorded with android phones we have otherwise...

Therefore this folder contains duplicates and are shown twice in the timeline.

**Describe the solution you'd like**
To be able to add a .notimeline file to the folder, so
- this folder would be available in the memories folder
- the content would be hidden from the timeline

**Describe alternatives you've considered**
hope for #558 and #907 

I hope this is fast solution. Or see this as push for #558 and #907

**Comment by pulsejet** [comment]
Hidden folders do this IIRC. Any folder starting with `.` in the name are hidden from the timeline, and you can see them in the folders view by turning on the "show hidden folders" option.

> the album will be sorted from oldest to newest

Add a `?sort=timeline` at the end of the share link to make it newest to oldest.

I expect #558 to happen soon, hopefully. Note though that this is for the _list_ of albums, not inside the album itself.

**Comment by craiq** [comment]
thanks a lot for the share link modifikation hint!
Also hiding the folder, was what I was looking for. Thank you!
then see this as a push for #232 / #907
