### ISSUE TITLE
Folder path is broken with latest update (NC 24.0.6, 3.3.3)

### ISSUE THREAD

**Issue by Akruidenberg** [pulsejet/memories#97]
With Nextcloud 24.0.6 and memories 3.3.3, my folder path is not working. Did a force rescan with the occ tool. However, every folder is showing "nothing to show here". Did change the root path multiple times, no luck. Prior versions don't have this issue.

**Comment by pulsejet** [comment]
Please try with v3.3.4 and reopen if persists.
