### ISSUE TITLE
Support for DCI-P3 profile

### ISSUE THREAD

**Issue by dronnikovigor** [pulsejet/memories#972]
**Is your feature request related to a problem? Please describe.**
Hello! I noticed that my photos from iPhone looks a bit different from e.g. Windows Viewer. I found this issue in Nextcloud https://github.com/nextcloud/server/issues/22951. So, only sRGB photos look good, other ones have bad colors.
Do you think it can be possible to fix it in Memories? 
Are there any other solution to correctly display photos?

**Comment by pulsejet** [comment]
Memories doesn't do preview generation at all, so this will need a fix in the server.

**Comment by dronnikovigor** [comment]
Hi! Since Memories now use Imagisk as preview generator, isn't it now an ability to fix this issue? Lots of devices now shot in DCI-P3, not only Apple. Photos looks bad..

**Comment by pulsejet** [comment]
No there has been no behavior change, previews are still generated by the server core. Just to be clear, I do support this change but we simply can't do this here.
