### ISSUE TITLE
Google Takeout Migrated Photos are off by a day on the timeline

### ISSUE THREAD

**Issue by SilleBille** [pulsejet/memories#977]
**Describe the bug**
Photos are sorted based on UTC instead of the photo taken timezone, especially when using Google Takeout migration. As a result, this messes ordering of *certain* photos in the timeline, causing inconsistency between Google Photos and Memories timeline.

**To Reproduce**
From Google Photos, use an image taken in day prior or next to UTC's current date. For example, Use a photo taken at 9PM PST -- The UTC time will be 5AM next day 

**Screenshots**
##### Metadata
<img width="1728" alt="Memories-bug" src="https://github.com/pulsejet/memories/assets/8215572/b03902dd-193e-43f0-b0dd-5feea2fecd79">

##### Timeline misordering
<img width="1633" alt="memories-timeline" src="https://github.com/pulsejet/memories/assets/8215572/b4cd943a-89b0-44ed-8555-bf61185846ae">

**Platform:**

- OS: All platforms
- Browser: All browsers (Tested on Firefox)
- Memories Version: 6.1.5
- Nextcloud Version: 28.0.1 RC1
- PHP Version: 8.1.26

**Additional context**
The issue was first observed when i migrated photos from Google Takeout and applied the EXIF data. However, the photos that are captured directly from Camera and auto-uploaded don't seem to have this issue.

**Sample Image and Json**

| Image | Json | Status |
|--|--|--|
| [IMG_20231127_142203](https://github.com/pulsejet/memories/assets/8215572/c0c99906-ad73-41ba-8f69-d2773ad0f870) | [IMG_20231127_142203.jpg.json](https://github.com/pulsejet/memories/files/13796611/IMG_20231127_142203.jpg.json) | **Correct** |
| [IMG_20231127_210040](https://github.com/pulsejet/memories/assets/8215572/ad4bc95d-0d1f-4965-ac4c-224d375c9275) | [IMG_20231127_210040.jpg.json](https://github.com/pulsejet/memories/files/13796609/IMG_20231127_210040.jpg.json) | **Wrong** |
| [IMG_20231127_210054](https://github.com/pulsejet/memories/assets/8215572/2956021b-0aa5-441e-aa70-adb9fa9e4faf) | [IMG_20231127_210054.jpg.json](https://github.com/pulsejet/memories/files/13796610/IMG_20231127_210054.jpg.json) | **Wrong** |

- Any errors in the JS console? No
- Any errors in the Nextcloud server logs? No

**Comment by pulsejet** [comment]
Please include a sample Image+JSON (the files above would be ideal)

**Comment by SilleBille** [comment]
> Please include a sample Image+JSON (the files above would be ideal)

I have included the corresponding files under additional context. Thanks!
