### ISSUE TITLE
Error: This operation is insecure

### ISSUE THREAD

**Issue by HyCore** [pulsejet/memories#98]
For some reason i can't access my image anymore with this error, nothing seems to show in the log. (last version & NC25)
![image](https://user-images.githubusercontent.com/48274082/197395760-50e64180-b3ae-4adb-836a-b5e4b65fd180.png)

**Comment by pulsejet** [comment]
What's in the js console?

**Comment by HyCore** [comment]
on latest firefox, the website is in https
error in DOM: Uncaught (in promise) DOMException: The operation is insecure.
![image](https://user-images.githubusercontent.com/48274082/197406947-d27026d9-f231-498a-aa1e-e438b03923a5.png)

**Comment by pulsejet** [comment]
Are you browsing in private mode, or is your browser configured to not save any history?

**Comment by HyCore** [comment]
i was in private mode, yes.

**Comment by pulsejet** [comment]
Should be fixed in the next version.

**Comment by HyCore** [comment]
nice, thx
