### ISSUE TITLE
Interrupting scrolling unneccessarily selects an image

### ISSUE THREAD

**Issue by tigrannajaryan** [pulsejet/memories#989]
**Describe the bug:**
Interrupting inertial scrolling unexpectedly selects the image if you tap and hold.

**To Reproduce:**
1. Swipe the list of images and release it to let it scroll inertially. 
2. While it is still scrolling tap and hold any image to stop scrolling. Keep holding.
3. The scrolling stops as expected. However, unexpectedly the image that you hold gets selected.

This behavior does not match the behavior of the default Gallery app, where tap-and-hold stops inertial scrolling, but does NOT select the tapped item.

**Screenshots:**
Not applicable.

**Platform:**

- OS: Android 14
- Browser: N/A, using Memories Android app
- Memories App Version: 6.1.5
- Memories Android App Version: 1.6
- Nextcloud Version: 27.1.4
- PHP Version: 8.1.25
- Phone: S23 Ultra

**Additional context:**
The behavior makes it difficult to scroll/stop/scroll/stop when you are trying to find an image you know is somewhere there.

**Related Issues:**
Possibly related to https://github.com/pulsejet/memories/issues/516. When I tap and release while inertially scrolling the tapped image opens. Again, this is not the behavior the standard Galeries apps has (it simply stops scrolling, without open an image).

**Checklist followed:**
- You are using the latest version of the app. **Yes: 1.6**
- You tried and can replicate the bug. **Yes: replicates every time on my phone**
- You have followed the [configuration steps](https://memories.gallery/config/). **Yes**
- You have looked at the [troubleshooting](https://memories.gallery/troubleshooting/) documentation. **Yes, no relevant doc found**
- You have searched the [open issues](https://github.com/pulsejet/memories/issues) **Yes, found possibly related issue**

**Comment by pulsejet** [comment]
Fixed with latest version

**Comment by tigrannajaryan** [comment]
Thank you @pulsejet

**Comment by tigrannajaryan** [comment]
> Fixed with latest version

@pulsejet Which version is this expected to be fixed in? I have just tried Memories 1.7 and I still see the same issue. Thank you for looking into this.

**Comment by pulsejet** [comment]
You need Memories v7 on the server, I can't repro the bug anymore with v7.

**Comment by tigrannajaryan** [comment]
@pulsejet I updated Memories to v7.0.2 and can confirm that I can no longer repro the bug. Thank you for the fix!
