### ISSUE TITLE
FATAL: Encryption is enabled. Aborted.

### ISSUE THREAD

**Issue by TonyNoIT** [pulsejet/memories#99]
After I tried to - _sudo -u www-data php ./occ memories:index_
Give error 
FATAL: Encryption is enabled. Aborted.

Is this module works with standard encryption on Nextcloud?

**Comment by pulsejet** [comment]
> Is this module works with standard encryption on Nextcloud?

No. Because memories does server-side processing, it cannot support end-to-end encrypted files without leaking information.

**Comment by eltos** [comment]
@pulsejet could you elaborate a bit more on this?  
Nextcloud features two kinds of encryption: 
- Server-side encryption: files on the drive are encrypted, but the server has the keys when a user is logged in
- End-to-end encryption: No way for the server to decrypt files

Is it only the latter or both that are not supported?  
Is it just the occ command for initial indexing of existing files, or the memories app in general not supporting it?  
Is there an alternative way for initial indexing (e.g. deleting and re-uploading all files)?

**Comment by eltos** [comment]
Just tested it with _server-side_ encryption: the occ command fails, but all images uploaded _after_ installation of the Memories app _do_ show up in the timeline. So maybe all it needs to fully support _server-side_ encryption is a method to do the indexing on a per-user basis, e.g. from the welcome screen when a user first opens the app?

**Comment by pulsejet** [comment]
I assumed the issue is about e2e encryption (maybe incorrectly). Not sure how the internals of server-side encryption work, but I'm willing to accept a pull request if we can support this.

**Comment by eltos** [comment]
Might be worth taking a look how the [metadata app](https://github.com/gino0631/nextcloud-metadata) does it. Maybe there is even a way to interface with it directly.

**Comment by TonyNoIT** [comment]
> 

That what I did for my files…
If files uploaded after - everything work 🤷‍♂️

**Comment by eltos** [comment]
Well, actually even the `occ memories:index` command works perfectly fine with server-side encryption. Just comment out that return statement in [lib/Command/Index.php](https://github.com/pulsejet/memories/blob/86de94c210914b5074c0cb073d9164ca900c7f4f/lib/Command/Index.php#L194-L198)
```php
if ($this->encryptionManager->isEnabled()) {
    error_log('FATAL: Encryption is enabled. Aborted.');
    return 1;
}
```
I observed that Nextcloud automatically provides a decrypted copy in `/tmp`, and when [`getExifFromFile`](https://github.com/pulsejet/memories/blob/86de94c210914b5074c0cb073d9164ca900c7f4f/lib/Exif.php#L105) is called the `$path = $file->getStorage()->getLocalFile($file->getInternalPath());` is that temporary (unencrypted) file, so exiftool has no problem reading it. 

Likewise, for the safety-check in [`updateExifDate`](https://github.com/pulsejet/memories/blob/ae03cffdc0fd15b7757107f4b17bf5365dce23d1/lib/Exif.php#L234-L237): I see that you "Don't want to mess these up, definitely", but it actually just works if you are brave enough 😉 

I haven't found official documentation on this unencrypted tmp-file mechanism, this is all inductive reasoning. You probably want to verify that independently. Plus, for E2E encryption, these safety checks might be wise to keep.
