### ISSUE TITLE
Generating video previews without FFMPEG or with a hack?

### ISSUE THREAD

**Issue by q2apro** [pulsejet/memories#997]
I am using Nextcloud by using a "Hetzner Storage Box NX21". They deploy Nextcloud, there is no SSH access and I cannot install ffmpeg.

I asked them why FFMPEG is not installed. They replied:

> Unfortunately, for performance reasons, we cannot support the ffmpeg module.

In other words: None of my videos (using Memories) has a thumbnail.

![image](https://github.com/pulsejet/memories/assets/6764548/9b5bba6a-06dc-48bd-b352-9111c1dc1288)

Question 1: Is there any other way to generate previews?

Question 2 (Hack): 
I have a binary ffmpeg on my Nextcloud storage. It does convert videos on one of my other servers. Can this file be used with Memories? And if so, how to find the correct path. I only have the "file link" path from Nextcloud with e.g. `https://nx1234567.your-storageshare.de/apps/files/?dir=/ffmpeg-folder/latest&fileid=456123` but not the server path to it. Searching the [web](https://help.nextcloud.com/t/where-and-how-are-the-acutal-files-stored/30565/9), I found e.g. `/var/snap/nextcloud/common/nextcloud/data/` and `/mnt/ncdata/`, but I cannot verify it.

However, in the admin panel it shows:

![image](https://github.com/pulsejet/memories/assets/6764548/8df3bc3d-0b47-448f-b0db-31b3c1af4baa)

But no option to define a path.

The ffmpeg path can only be defined at the video streaming section:

![image](https://github.com/pulsejet/memories/assets/6764548/1c284012-b9f0-4bf6-b5af-f0613a2ba570)

**Comment by q2apro** [comment]
I guess the `config.php` cannot be changed with a Docker installation... And I haven't checked their TOS, if this is mentioned.

**Comment by pulsejet** [comment]
With docker, you simply need to exec into the container and edit it. Right now there's no easy way to do this on separate machines.

**Comment by Tomcat9** [comment]
@pulsejet I'm also affected by not having ffmpeg on a managed nextcloud, as Hetzner is a popular service in Germany.

Here's my proposal: I could add a fallback to the memories thumbnail job. When ffmpeg is not available but there is a thumbnail file provided next to the video file, it is stored as thumbnail in nextcloud. This could be an automatic fallback or enabled/disabled in the config tab.

I could then create a script for multiple platforms (at least windows & linux) that generates these thumbnail files in the locally synched nextcloud with ffmpeg. Users without ffmpeg on their nextcloud instance can run this regularly to create video thumbnails and thus improve their memories experience.

I'm a software engineer myself, so I'm sure I can implement this, and provide it as a pull request, with tests and documentation.

The catch: Without a way to run third party modules on the nextcloud instance, this change would need to be integrated into an official memories release.

Is this a good way forward? I will accept your decision, positive or negative. Of course I'd rather not invest the time if there's no way to get it into a release. But if my work doesn't reach the required quality, of course there is no guarantee. I appreciate any thoughts or input on this.

**Comment by julienmueller** [comment]
Got the same problem here with a Hetzner Shared Webspace: No use of FFMPEG possible.
I share photos and videos of my concerts with clients and would love a thumbnail to be displayed.
What @Tomcat9 proposed sounds like a great solution. 

Would it be possible to **assign a thumbnail file** to a video manually or maybe look for a file named "**videofile_name+thumb.png**" or something to add it directly? For people who only upload a video once in a blue moon this could help out immensely, if faced with restrictive web-hosts.
